Add actiontrail resource and datasource
aliyun/terraform-provider-alicloud pull request #2758
Opened 2020-08-24 08:32 UTC by lixue323

2020-08-24 11:16 UTC, zql-tqy commented on website/docs/d/actiontrail_trails.html.markdown
> +  Provides a list of ActionTrail Trails to the user.
Provides a list of ActionTrail Trails to the specified filters.

2020-08-24 11:16 UTC, zql-tqy commented on website/docs/d/actiontrails.html.markdown
> +~> **Warnings:** This resource has been deprecated and please use [alicloud_actiontrail_trails](//www.terraform.io/docs/providers/alicloud/d/actiontrail_trails.html).
-> **DEPRECATED:**

2020-08-24 11:16 UTC, zql-tqy commented on website/docs/r/actiontrail.html.markdown
> +~> **Warnings:** This resource has been deprecated and please use [alicloud_actiontrail_trail](//www.terraform.io/docs/providers/alicloud/r/actiontrail_trail.html).
同上

2020-08-24 11:16 UTC, zql-tqy commented on website/docs/r/actiontrail_trail.html.markdown
> +* `status` - (Optional) The status of ActionTrail Trail. After creation, tracking is turned on by default, and you can set the status value to `Disable` to turn off tracking. Valid values: `Enable`,
缺少 is_organization_trail  参数

2020-08-24 11:16 UTC, zql-tqy commented on website/docs/d/actiontrail_trails.html.markdown
> +This data source provides a list of ActionTrail Trails in an Alibaba Cloud account according to the specified filters.
这个没有版本

2020-08-25 12:20 UTC, zql-tqy commented on website/docs/d/actiontrail_trails.html.markdown
> +* `include_shadow_trails` - (Optional) Whether to show shadow tracking. Default to: `false`.
这个在 schema 中没有默认值吧

2020-08-25 12:20 UTC, zql-tqy commented on website/docs/r/actiontrail_trail.html.markdown
> +* `event_rw` - (Optional) Indicates whether the event is a read or a write event. Valid values: `Read`, `Write`, and `All`. Default to: `Write`.
Default to `Write`.

2020-08-26 02:55 UTC, zql-tqy commented on alicloud/resource_alicloud_actiontrail_trail_test.go
> +func TestAccAlicloudActionTrailTrail_basic(t *testing.T) {
resoruce 和 datasource test 的名称保持一致

2020-08-28 02:07 UTC, xiaozhu36 requested changes

2020-08-28 03:33 UTC, xiaozhu36 requested changes

2020-08-28 03:33 UTC, xiaozhu36 commented on website/docs/d/actiontrails.html.markdown
> +
```
-> **DEPRECATED:**  This datasource has been renamed to `[alicloud_actiontrail_trails](https://www.terraform.io/docs/providers/alicloud/d/actiontrail_trails.html)` from version 1.95.0. 
```

2020-08-28 03:33 UTC, xiaozhu36 commented on website/docs/r/actiontrail.html.markdown
> +
```
-> **DEPRECATED:**  This resource has been renamed to `[alicloud_actiontrail_trail](https://www.terraform.io/docs/providers/alicloud/d/actiontrail_trails.html)` from version 1.95.0. 
```

2020-08-28 06:10 UTC, xiaozhu36 approved these changes

2020-08-28 06:10 UTC, merged