added create emr cluster request params validation
aliyun/terraform-provider-alicloud pull request #2786
Opened 2020-09-03 15:09 UTC by qiyinfei

2020-09-07 11:50 UTC, xiaozhu36 requested changes

2020-09-07 11:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_emr_cluster.go
> +			request.Period = requests.NewInteger(innerPeriod.(int))
I think using a default '1' can replace the checking whether the period value is less than 0.

2020-10-09 06:31 UTC, qiyinfei commented
![image](https://user-images.githubusercontent.com/30532003/95550775-0dc10080-0a3c-11eb-90ee-135942882c46.png)

2020-10-10 08:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=2786) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=2786) before we can accept your contribution.<br/><hr/>**曙影** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=2786) it.</sub>

2020-10-14 02:21 UTC, merged