support kvstore instance and connection
aliyun/terraform-provider-alicloud pull request #2867
Opened 2020-09-24 11:55 UTC by lixue323

2020-09-25 03:50 UTC, liuri1205 commented on alicloud/resource_alicloud_kvstore_instance.go
> -	request.RegionId = client.RegionId
资源如果是 region 级别的，需要保留 `	request.RegionId = client.RegionId`

2020-09-25 03:50 UTC, liuri1205 commented on alicloud/resource_alicloud_kvstore_instance.go
> -	stateConf := BuildStateConf([]string{"Creating", "Active", "Deleting"}, []string{}, d.Timeout(schema.TimeoutDelete), 1*time.Minute, kvstoreService.RdsKvstoreInstanceStateRefreshFunc(d.Id(), []string
删除接口如果是异步的，需要保留

2020-09-25 03:50 UTC, liuri1205 commented on alicloud/resource_alicloud_kvstore_instance_test.go
> +						"vswitch_id":                    CHECKSET,
`vswitch_id`，`zone_id` 没有测试更新接口

2020-09-25 03:50 UTC, liuri1205 commented on website/docs/d/kvstore_connections.html.markdown
> +```
加上 ```terraform

2020-09-25 03:50 UTC, liuri1205 commented on website/docs/d/kvstore_connections.html.markdown
> +  value = "${data.alicloud_kvstore_connections.example.connections.0.connection_string}"
去掉”${}“,使用新语法

2020-09-25 03:50 UTC, liuri1205 commented on website/docs/d/kvstore_connections.html.markdown
> +* `ids` -  A list of MSE Cluster ids.
`ids` 描述信息有误

2020-09-25 03:50 UTC, liuri1205 commented on website/docs/d/kvstore_instances.html.markdown
> +* `status` - (Optional) The status of the KVStore DBInstance.
`status` 需要加上有效值

2020-09-25 03:50 UTC, liuri1205 commented on website/docs/d/kvstore_instances.html.markdown
> +* `architecture_type` - (Optional) The type of the architecture. Valid values: `cluster`, `standard` and `SplitRW`.
新增参数添加版本

2020-09-25 03:50 UTC, liuri1205 commented on website/docs/r/kvstore_connecion.html.markdown
> +  connection_string_prefix = "allocatetestupdate"
格式化

2020-09-25 03:50 UTC, liuri1205 commented on website/docs/r/kvstore_instance.html.markdown
> +resource "alicloud_kvstore_instance" "example" {
模板格式化

2020-09-25 03:50 UTC, liuri1205 commented on website/docs/r/kvstore_instance.html.markdown
> +-> **NOTE:** The `private_ip` must be in the Classless Inter-Domain Routing (CIDR) block of the VSwitch to which the instance belongs.
note 之间添加空行

2020-09-25 05:50 UTC, lixue323 commented on alicloud/data_source_alicloud_kvstore_connections.go
> +		ids = append(ids, convertListToJsonString(d.Get("ids").(*schema.Set).List()))
因为查询公网的接口实例id做为入参，没有出参id

2020-09-27 06:50 UTC, xiaozhu36 requested changes

2020-09-27 06:50 UTC, xiaozhu36 commented on alicloud/service_alicloud_r_kvstore.go
> +func (s *R_kvstoreService) DescribeRedisDbInstance(id string) (object r_kvstore.DBInstanceAttribute, err error) {
DescribeRedisDbInstance 和 DescribeKvstoreInstance 的区别是啥

2020-09-27 06:50 UTC, xiaozhu36 commented on website/docs/r/kvstore_instance.html.markdown
> +* `instance_class` - (Optional) Type of the applied ApsaraDB for Redis instance. It can be retrieved by data source [`alicloud_kvstore_instance_classes`](https://www.terraform.io/docs/providers/alicl
这个为啥变成Optional了

2020-09-27 06:50 UTC, xiaozhu36 commented on website/docs/r/kvstore_instance.html.markdown
> +* `zone_id` - (Optional, Available in 1.99.0+) The ID of the zone.
这个zone id 现在可以修改了？

2020-09-27 06:50 UTC, xiaozhu36 commented on website/docs/r/kvstore_instance.html.markdown
> +* `vswitch_id` - (Optional) The ID of VSwitch.
vswitch ID现在也可以修改了么？
其他的都确认下，如果不能修改，那么保留 ForceNew 的标记

2020-09-27 06:50 UTC, xiaozhu36 commented on website/docs/d/kvstore_connections.html.markdown
> +---
缺少在 alicloud.erb 中注册文档

2020-09-27 06:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_instance_test.go
> +				Config: testAccConfig(map[string]interface{}{
这个地方的测试删除了好多的测试case，请确保所有的属性都覆盖到了

2020-09-27 06:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_instance.go
> +	d.Set("tags", tags)
这个地方是要对tags进行过滤的，但是新的代码中怎么去掉了

2020-09-27 06:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_instance.go
> +	return source
这个啥也没有，为啥还需要一个转换函数

2020-09-27 07:33 UTC, lixue323 commented on website/docs/r/kvstore_instance.html.markdown
> +* `instance_class` - (Optional) Type of the applied ApsaraDB for Redis instance. It can be retrieved by data source [`alicloud_kvstore_instance_classes`](https://www.terraform.io/docs/providers/alicl
新代码支持 capacity， 创建的时候和 instance_class，传一个就行

2020-09-27 07:33 UTC, lixue323 commented on website/docs/r/kvstore_instance.html.markdown
> +* `zone_id` - (Optional, Available in 1.99.0+) The ID of the zone.
可以修改，迁移可用区

2020-09-27 07:36 UTC, lixue323 commented on alicloud/resource_alicloud_kvstore_instance.go
> +	return source
接口录的枚举值是：CLOSE，OPEN, Close, Open, 返回的参数是Close, Open。不让客户使用全大写传入，会出diff，所以在apispec中录入了映射，出参，入参都一样，这样可以覆盖掉api中的枚举值

2020-09-27 07:43 UTC, lixue323 commented on alicloud/resource_alicloud_kvstore_instance.go
> +	d.Set("tags", tags)
之前read中也没对tags进行啥过滤，它就是调用的ListTagResource接口，咱们自动化是，get接口返回了tags,那么直接用这个返回的，apispec也不用录ListTagResource

2020-09-27 11:41 UTC, xiaozhu36 requested changes

2020-09-27 11:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_instance.go
> +	if _, ok := d.GetOk("security_group_id"); ok {
set 的时候，为啥要先通过 d.getOK判断下

2020-09-27 11:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_instance.go
> +	return source
但是这个方法没做任何处理啊

2020-09-27 11:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_instance_test.go
> +						"vswitch_id":                    CHECKSET,
这个好像也还没改

2020-09-27 13:05 UTC, lixue323 commented on alicloud/resource_alicloud_kvstore_instance.go
> +	if _, ok := d.GetOk("security_group_id"); ok {
这些get接口调用都是有条件的，某些属性值不对，比如按量付费就调用不了describeInstanceAutoRenewalAttribute，或者资源没开启过ssl，调用DescribeInstanceSSL就会报错

2020-10-12 11:35 UTC, zql-tqy requested changes

2020-10-12 11:35 UTC, zql-tqy commented on alicloud/resource_alicloud_kvstore_connection_test.go
> +				ImportStateVerifyIgnore: []string{"connection_string_prefix"},
connection_string_prefix 是产品属性么？如果是属性没有返回的就有问题

2020-10-12 11:35 UTC, zql-tqy commented on alicloud/resource_alicloud_kvstore_instance.go
> +				Optional: true,
这个参数的属性由必填变为选填了么？

2020-10-12 11:35 UTC, zql-tqy commented on alicloud/resource_alicloud_kvstore_instance.go
> -	stateConf := BuildStateConf([]string{"Creating", "Active", "Deleting"}, []string{}, d.Timeout(schema.TimeoutDelete), 1*time.Minute, kvstoreService.RdsKvstoreInstanceStateRefreshFunc(d.Id(), []string
如果没有删除的异步等待操作，在文档中 delete 的 timeout 也删掉吧，写从哪个版本开始移除的

2020-10-12 11:35 UTC, zql-tqy commented on alicloud/resource_alicloud_kvstore_instance_test.go
> +				Config: testAccConfig(map[string]interface{}{
这个测试覆盖的全了么

2020-10-12 11:35 UTC, zql-tqy commented on website/docs/r/kvstore_instance.html.markdown
> +* `instance_class` - (Optional) Type of the applied ApsaraDB for Redis instance. It can be retrieved by data source [`alicloud_kvstore_instance_classes`](https://www.terraform.io/docs/providers/alicl
建议文档中进行说明

2020-10-12 11:35 UTC, zql-tqy commented on website/docs/r/kvstore_instance.html.markdown
> +* `vswitch_id` - (Optional) The ID of VSwitch.
是否和产品进行确认？

2020-10-13 07:59 UTC, lixue323 commented on alicloud/resource_alicloud_kvstore_connection_test.go
> +				ImportStateVerifyIgnore: []string{"connection_string_prefix"},
传入的是 connection_string_prefix 返回完整的 connection_string

2020-10-13 08:00 UTC, lixue323 commented on alicloud/resource_alicloud_kvstore_instance.go
> +				Optional: true,
对，和另一个参数填一个就行

2020-10-13 08:00 UTC, lixue323 commented on website/docs/r/kvstore_instance.html.markdown
> +* `instance_class` - (Optional) Type of the applied ApsaraDB for Redis instance. It can be retrieved by data source [`alicloud_kvstore_instance_classes`](https://www.terraform.io/docs/providers/alicl
Note中进行了说明

2020-10-13 08:09 UTC, lixue323 commented on website/docs/r/kvstore_instance.html.markdown
> +* `vswitch_id` - (Optional) The ID of VSwitch.
两个参数二选一，已经在文档中说明了

2020-10-13 10:17 UTC, lixue323 commented on alicloud/resource_alicloud_kvstore_instance.go
> -	stateConf := BuildStateConf([]string{"Creating", "Active", "Deleting"}, []string{}, d.Timeout(schema.TimeoutDelete), 1*time.Minute, kvstoreService.RdsKvstoreInstanceStateRefreshFunc(d.Id(), []string
文档移除了

2020-10-13 10:17 UTC, lixue323 commented on alicloud/resource_alicloud_kvstore_instance_test.go
> +				Config: testAccConfig(map[string]interface{}{
已经补充全了

2020-10-15 08:12 UTC, xiaozhu36 approved these changes

2020-10-15 08:13 UTC, merged