add data source alicloud_cs_edge_kubernetes_clusters and resource alicloud_cs_edge_kubernetes
aliyun/terraform-provider-alicloud pull request #2871
Opened 2020-09-25 09:45 UTC by wawlian

add data source alicloud_cs_edge_kubernetes_clusters and resource alicloud_cs_edge_kubernetes

2020-09-25 09:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=2871) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=2871) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=2871) it.</sub>

2020-10-22 04:43 UTC, zql-tqy requested changes

2020-10-22 04:43 UTC, zql-tqy commented on website/docs/r/cs_edge_kubernetes.html.markdown
> +-> **NOTE:** From version 1.9.4, the provider supports to download kube config, client certificate, client key and cluster ca certificate
这个是个新资源不需要添加这个 version 信息，这个资源从 1.102.0 才支持的，不存在 1.9.4 之类的版本，下面的也是一样

2020-10-22 04:43 UTC, zql-tqy commented on website/docs/r/cs_edge_kubernetes.html.markdown
> +* `version` - (Optional, Available since 1.70.1) Desired Kubernetes version. If you do not specify a value, the latest available version at resource creation is used and no upgrades will occur except
新资源 Available since 1.70.1 也不用加，这是对于已经存在的 resource 添加属性是进行标记的

2020-10-22 04:43 UTC, zql-tqy commented on website/docs/r/cs_edge_kubernetes.html.markdown
> +It is a new field since 1.75.0. You can specific network plugin,log component,ingress component and so on.
还有这个版本

2020-10-22 04:43 UTC, zql-tqy commented on website/docs/r/cs_edge_kubernetes.html.markdown
> +-> **NOTE:** Available in 1.58.0+.
这个也不需要版本

2020-10-22 04:43 UTC, zql-tqy commented on website/docs/r/cs_edge_kubernetes.html.markdown
> +* `install_cloud_monitor` - (Optional) Install cloud monitor agent on ECS. default: true
这种默认值，枚举值写成 \`true\` 形式

2020-10-22 06:10 UTC, wawlian commented on alicloud/data_source_alicloud_cs_edge_kubernetes_clusters.go
> +			return csClient.DescribeClusters("")
不需要传参数，针对一些参数的过滤是通过拿到结果之后再进行内存中的过滤。

2020-10-28 08:22 UTC, merged