Suport FC aysnc invoke config feature.
aliyun/terraform-provider-alicloud pull request #2873
Opened 2020-09-26 15:35 UTC by hryang

2020-09-27 06:45 UTC, liuri1205 commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +sidebar_current: "docs-alicloud-resource-fc"
`sidebar_current` 这个资源名称不完整

2020-09-27 06:45 UTC, liuri1205 commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +# alicloud\_fc\_function_async_invoke_config
`alicloud\_fc\_function_async_invoke_config` 格式不对

2020-09-27 06:45 UTC, liuri1205 commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> + For the detailed information, please refer to the [developer guide](https://www.alibabacloud.com/help/doc-detail/181866.htm).
链接有英文的需要放英文链接

2020-09-27 06:45 UTC, liuri1205 commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +
note 下面空行只要一行

2020-09-27 06:45 UTC, liuri1205 commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +```hcl
改成```terraform

2020-09-27 06:45 UTC, liuri1205 commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +* `id` - Fully qualified Function Compute Sevice and Function name (`example_service_name:example_function_name`) or Alicloud Resource Name (ARN).
id 描述不准确，应该是3 个属性组成的 ID，使用属性名称拼接，不要 example

2020-09-27 06:45 UTC, liuri1205 commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +* `qualifier` - (Optional) Function Compute Function published version, `LATEST`, or Function Compute Alias name.
有默认值需要把默认值描述清楚，如 Default value is `LATEST`.

2020-09-27 06:45 UTC, liuri1205 commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +* `service_name` - (Required) Name of the Function Compute Function, omitting any version or alias qualifier.
属性如果是`ForceNew` 的需要标识为`ForceNew`

2020-09-27 06:46 UTC, liuri1205 commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +
资源CUD 中有超时的需要在文档这里添加超时描述

2020-09-27 12:45 UTC, hryang commented on alicloud/resource_alicloud_fc_function_async_invoke_config.go
> +			State: schema.ImportStatePassthrough,
麻烦给一个示例

2020-09-27 12:46 UTC, hryang commented on alicloud/resource_alicloud_fc_function_async_invoke_config.go
> +		id = fmt.Sprintf("%s:%s", id, qualifier)
上述 id 生成方式保证在 account region 下是唯一的

2020-09-27 12:55 UTC, hryang commented on alicloud/resource_alicloud_fc_function_async_invoke_config.go
> +	if v, ok := d.GetOk("maximum_event_age_in_seconds"); ok {
alicloud_fc_function_async_invoke_config 这个资源，严格来讲，在服务端没有 update（部分更新属性） 这个语义，而是 replace（整体替换）。因此这里的 update 和 create 是类似的。我看 AWS Lambda 也是类似的实现，没有使用 HasChange

2020-09-27 12:59 UTC, hryang commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> + For the detailed information, please refer to the [developer guide](https://www.alibabacloud.com/help/doc-detail/181866.htm).
这里是国际站文档，会根据客户的网站设置自动显示中英文，链接是一样的。

2020-09-27 12:59 UTC, hryang commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +# alicloud\_fc\_function_async_invoke_config
麻烦给一个正确格式示例。

2020-09-27 13:03 UTC, hryang commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +```hcl
hcl 也可以，aws 是这样的。

2020-09-28 02:01 UTC, liuri1205 commented on alicloud/resource_alicloud_fc_function_async_invoke_config.go
> +			State: schema.ImportStatePassthrough,
参考`alicloud_cen_bandwidth_package` resource 和文档

2020-09-28 02:08 UTC, liuri1205 commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +# alicloud\_fc\_function_async_invoke_config
`alicloud\_fc\_function_\async_\invoke_\config `

2020-09-28 02:09 UTC, liuri1205 commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +```hcl
和 alicloud 保持一致吧

2020-09-28 07:45 UTC, hryang commented on alicloud/resource_alicloud_fc_function_async_invoke_config.go
> +			State: schema.ImportStatePassthrough,
对比了下，fc 里的超时是固定的，对用户不可见。没有必要暴露给用户。

2020-09-28 12:38 UTC, zql-tqy requested changes

2020-09-28 12:38 UTC, zql-tqy commented on alicloud/resource_alicloud_fc_function_async_invoke_config.go
> +		return WrapErrorf(err, DefaultErrorMsg, "alicloud_fc_async_invoke_config", "PutFunctionAsyncInvokeConfig", FcGoSdk)
alicloud_fc_function_async_invoke_config

2020-09-28 12:38 UTC, zql-tqy commented on alicloud/resource_alicloud_fc_function_async_invoke_config.go
> +	request.DestinationConfig = parseFCDestinationConfig(d.Get("destination_config").([]interface{}))
这个 destination_config 是选填的，使用 d.getOk 获取

2020-09-28 12:38 UTC, zql-tqy commented on alicloud/resource_alicloud_fc_function_async_invoke_config.go
> +		return WrapErrorf(err, DefaultErrorMsg, "alicloud_fc_async_invoke_config", "PutFunctionAsyncInvokeConfig", FcGoSdk)
同上

2020-09-28 12:38 UTC, zql-tqy commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +The following arguments are optional:
这个去掉吧，属性后面有标注是否选填了

2020-09-28 12:38 UTC, zql-tqy commented on alicloud/resource_alicloud_fc_function_async_invoke_config.go
> +	d.SetId(id)
这个 id 的组成部分，如果创建有返回使用返回的构建 ID，没有返回则使用入参

2020-09-28 12:38 UTC, zql-tqy commented on alicloud/resource_alicloud_fc_function_async_invoke_config.go
> +	if v, ok := d.GetOk("maximum_event_age_in_seconds"); ok {
咱们这边接口也是这样设计的么？只要变更其中一个参数所有的都需要传入吗？
在 Update 接口中所有可变更的参数都需要使用 d.HasChange 此时增加一个 update 变量，如果有变化则调用接口变更，如果没有改变则不需要调用变更接口，防止无效的调用变更接口；

2020-09-28 13:21 UTC, hryang commented on alicloud/resource_alicloud_fc_function_async_invoke_config.go
> +	request.DestinationConfig = parseFCDestinationConfig(d.Get("destination_config").([]interface{}))
这里没问题，如果不存在，d.Get() 返回的是 nil。

2020-09-28 13:27 UTC, hryang commented on alicloud/resource_alicloud_fc_function_async_invoke_config.go
> +	d.SetId(id)
这里返回值和入参是相同的。

2020-09-29 02:36 UTC, zql-tqy commented on website/docs/r/fc_function_async_invoke_config.html.markdown
> +-> **NOTE:** Available in 1.99.0+
1.100.0

2020-10-09 07:16 UTC, xiaozhu36 requested changes

2020-10-09 07:16 UTC, xiaozhu36 commented on alicloud/resource_alicloud_fc_function_async_invoke_config.go
> +	request.DestinationConfig = parseFCDestinationConfig(d.Get("destination_config").([]interface{}))
如果不存在，d.Get() 返回的是nil，那么此时进行类型转化会报错

2020-10-10 01:20 UTC, xiaozhu36 approved these changes

2020-10-10 01:22 UTC, merged