Create cluster support ResourceGroup and ACK-Pro
aliyun/terraform-provider-alicloud pull request #2882
Opened 2020-09-29 11:48 UTC by anserhyb

- Fixed custom image not work.
- Fixed worker_disk_category constraint.

2020-09-29 11:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=2882) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=2882) before we can accept your contribution.<br/><hr/>**司安** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=2882) it.</sub>

2020-10-09 03:08 UTC, zql-tqy requested changes

2020-10-09 03:08 UTC, zql-tqy commented on website/docs/d/cs_managed_kubernetes_clusters.html.markdown
> +  * `resource_group_id` - (Optional, Available in 1.99.0+) The ID of the resource group,by default these cloud resources are automatically assigned to the default resource group.
1.100.0+，另外两个 resource 中应该也添加了 resource_group_id  吧，也需要在文档中添加

2020-10-09 03:08 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_kubernetes.go
> +				//ValidateFunc: validation.StringInSlice([]string{
没有限制了这些注释就直接去掉吧

2020-10-09 03:08 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_kubernetes.go
> +				Type:     schema.TypeString,
该属性是否支持修改？如果不支持修改则需要添加 forceNew 属性

2020-10-09 03:55 UTC, anserhyb commented on alicloud/resource_alicloud_cs_kubernetes.go
> +				Type:     schema.TypeString,
暂不支持修改。

2020-10-09 03:55 UTC, anserhyb commented on alicloud/resource_alicloud_cs_kubernetes.go
> +				//ValidateFunc: validation.StringInSlice([]string{
ok

2020-10-09 03:55 UTC, anserhyb commented on website/docs/d/cs_managed_kubernetes_clusters.html.markdown
> +  * `resource_group_id` - (Optional, Available in 1.99.0+) The ID of the resource group,by default these cloud resources are automatically assigned to the default resource group.
ok

2020-10-09 06:40 UTC, zql-tqy requested changes

2020-10-09 06:40 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_managed_kubernetes.go
> +				Optional: true,
枚举值需要在这里添加 ack.standard，ack.pro.small

2020-10-09 06:40 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +				Optional: true,
这个没有添加 forceNew

2020-10-09 06:40 UTC, zql-tqy commented on website/docs/d/cs_kubernetes_clusters.html.markdown
> +  * `resource_group_id` - (Optional, Available in 1.100.0+) The ID of the resource group,by default these cloud resources are automatically assigned to the default resource group.
(Optional, ForceNew, Available in 1.100.0+) 下面也是一样

2020-10-09 13:05 UTC, closed without merging