add support to enhanced nat gateway
aliyun/terraform-provider-alicloud pull request #2907
Opened 2020-10-14 03:18 UTC by zhengjc2018

2020-10-15 06:47 UTC, xiaozhu36 commented
Please clear the conflicts at first.

2020-10-15 07:36 UTC, chushenmeshile requested changes

2020-10-20 02:54 UTC, zql-tqy requested changes

2020-10-20 02:54 UTC, zql-tqy commented on alicloud/data_source_alicloud_enhanced_nat_available_zones.go
> +		return WrapErrorf(err, DataDefaultErrorMsg, "ListEnhanhcedNatGatewayAvailableZones", request.GetActionName(), AlibabaCloudSdkGoERROR)
ListEnhanhcedNatGatewayAvailableZones 换成 alicloud_enhanced_nat_available_zones

2020-10-20 02:54 UTC, zql-tqy commented on alicloud/data_source_alicloud_enhanced_nat_available_zones.go
> +	}
output_file 怎么没有处理？

2020-10-20 02:54 UTC, zql-tqy commented on alicloud/resource_alicloud_nat_gateway.go
> +	d.Set("nat_type", object.NatType)
vswitch_id 没有返回么？

2020-10-20 02:54 UTC, zql-tqy commented on alicloud/resource_alicloud_nat_gateway.go
> +				Type:         schema.TypeString,
这两个参数是否支持变更？我看在 update 方法中没有支持变更的接口，在 schema 中也没有添加 forceNew 属性

2020-10-20 02:54 UTC, zql-tqy commented on website/docs/d/enhanced_nat_zones.html.markdown
> +}
这个地方增加一个 output，提示用户如何使用查询结果

2020-10-20 02:54 UTC, zql-tqy commented on website/docs/d/enhanced_nat_zones.html.markdown
> +```
\`\`\`terraform

2020-10-20 02:54 UTC, zql-tqy commented on website/docs/d/enhanced_nat_zones.html.markdown
> +* `zones` - A list of available zones. Each element contains the following attributes:
output_file 没有标明

2020-10-20 02:54 UTC, zql-tqy commented on website/docs/d/enhanced_nat_zones.html.markdown
> +-> **NOTE:** Available in 1.101.0+.
1.102.0+

2020-10-20 02:54 UTC, zql-tqy commented on website/docs/r/nat_gateway.html.markdown
> +
这个和上面的有什么区别？分成两个 usage 写，标明使用的不同之处
每个 usage 和上面提出的一样使用 \`\`\`terraform

2020-10-20 02:54 UTC, zql-tqy commented on website/docs/r/nat_gateway.html.markdown
> +* `nat_type` - (Optional, Available in 1.102.0+) The type of nat gateway. Default to `normal`. Valid values: [`normal`, `enhanced`].
如果不支持修改，文档中属性也要添加 forceNew

2020-10-22 13:09 UTC, xiaozhu36 approved these changes

2020-10-22 13:10 UTC, merged