Add kvstore_accounts and Add Asynchronous wait for kvstore_account
aliyun/terraform-provider-alicloud pull request #2952
Opened 2020-10-22 06:57 UTC by lixue323

2020-10-22 12:19 UTC, chushenmeshile requested changes

2020-10-22 12:19 UTC, chushenmeshile commented on website/docs/d/kvstore_accounts.html.markdown
> +* `output_file` - (Optional) File name where to save data source results (after running `terraform plan`).
Status.

2020-10-22 12:19 UTC, chushenmeshile commented on website/docs/r/kvstore_account.html.markdown
> +* `instance_id` - (Required, ForceNew) The Id of instance in which account belongs (The engine version of instance must be 4.0 or 4.0+).
添加版本

2020-10-22 12:19 UTC, chushenmeshile commented on alicloud/resource_alicloud_kvstore_account.go
>  				Sensitive: true,
这个为啥变为require了，不兼容

2020-10-23 02:26 UTC, chushenmeshile requested changes

2020-10-23 02:26 UTC, chushenmeshile commented on alicloud/resource_alicloud_kvstore_account.go
> -	request.InstanceId = d.Get("instance_id").(string)
是否为全局region

2020-10-23 02:26 UTC, chushenmeshile commented on website/docs/r/kvstore_account.html.markdown
> +
删除空行

2020-10-23 02:47 UTC, lixue323 commented on alicloud/resource_alicloud_kvstore_account.go
> -	request.InstanceId = d.Get("instance_id").(string)
此资源不是region级别的，为instance创建账户，所以自动生成去掉了

2020-10-23 02:51 UTC, zql-tqy requested changes

2020-10-23 02:51 UTC, zql-tqy commented on alicloud/data_source_alicloud_kvstore_accounts.go
> +			"account_name": {
需要增加 name_regex 过滤条件，并在测试中增加

2020-10-23 02:51 UTC, zql-tqy commented on alicloud/resource_alicloud_kvstore_account.go
> +	request.AccountPassword = d.Get("account_password").(string)
这个逻辑有些问题，需要调整下

2020-10-23 02:51 UTC, zql-tqy commented on alicloud/resource_alicloud_kvstore_account.go
> +	raw, err := client.WithRKvstoreClient(func(r_kvstoreClient *r_kvstore.Client) (interface{}, error) {
这个之前是有错误重试的，这个再确认下

2020-10-23 02:51 UTC, zql-tqy commented on alicloud/resource_alicloud_kvstore_account.go
> +	if !d.IsNewResource() && (d.HasChange("account_password") || d.HasChange("kms_encrypted_password")) {
!d.IsNewResource() 这个应该是不需要添加的

2020-10-23 02:51 UTC, zql-tqy commented on website/docs/d/kvstore_accounts.html.markdown
> +* `Status.` - (Optional, ForceNew) The status of KVStore Account.
这个去掉 . 首字母小写
这个要添加 枚举值

2020-10-23 02:51 UTC, zql-tqy commented on website/docs/r/kvstore_account.html.markdown
> +```terraform
这个测试保留之前创建 instance 的过程吧，对其中变更的参数进行调整就行了，这样方便用户使用

2020-10-23 02:51 UTC, zql-tqy commented on website/docs/r/kvstore_account.html.markdown
> +The `timeouts` block allows you to specify [timeouts](https://www.terraform.io/docs/configuration-0-11/resources.html#timeouts) for certain actions:
timeout 是新增加的，需要写从哪个版本开始增加的

2020-10-23 03:38 UTC, lixue323 commented on alicloud/resource_alicloud_kvstore_account.go
> +	request.AccountPassword = d.Get("account_password").(string)
下边做了判断，两个都不填会抛错

2020-10-23 03:38 UTC, lixue323 commented on website/docs/r/kvstore_account.html.markdown
> +```terraform
嗯，保留了

2020-10-23 08:07 UTC, merged