Create cluster parameters aligned with the ACK
aliyun/terraform-provider-alicloud pull request #2990
Opened 2020-11-05 13:22 UTC by anserhyb

DeditedK8S:
    timezone、runtime、rds_instance、cluster_domain、custom_san、deletion_protection、
    node_port_range、os_type、platform、taints
ManagedK8S:
    timezone、runtime、rds_instance、cluster_domain、custom_san、deletion_protection、
    node_port_range、os_type、platform、taints、encryption_provider_key
EdgK8S:
    rds_instance、resource_group_id、deletion_protectio

2020-11-06 02:24 UTC, zql-tqy requested changes

2020-11-06 02:24 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_kubernetes.go
> +	// m := l[0].(map[string]interface{})
没用的去掉

2020-11-06 02:24 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
> +					"cluster_id":           os.Getenv("CLUSTER_ID"),
这个需要使用 tf 模板在 dependence 中创建实例并引用，否则我们这边的定期跑 testcase 的时候肯定无法 pass
vswitch_ids 也是一样

2020-11-06 02:24 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
> +					"system_disk_category": "cloud_efficiency",
data_disks 这个测试怎么去掉了

2020-11-06 02:24 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
> +				ImportStateVerifyIgnore: []string{"name", "cluster_id", "vswitch_ids", "instance_types", "node_count", "password", "system_disk_category", "system_disk_size"},
这个在 read 中没有 set，如果 set 了不需要 ignore

2020-11-06 02:24 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_kubernetes_test.go
> +					"runtime":               map[string]interface{}{"Name": "docker", "Version": "19.03.5"},
这个 config 测试数据也不全，check 的数据也不全

2020-11-06 02:24 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_managed_kubernetes_test.go
> +					"deletion_protection":         "false",
同上

2020-11-06 02:24 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_kubernetes.go
> +		if d.HasChange("taints") && !d.IsNewResource() {
还有一部分增加的参数没有 update 操作，同样不支持修改的话就在 schema 中添加 forceNew 属性

2020-11-06 02:53 UTC, anserhyb commented on alicloud/resource_alicloud_cs_kubernetes.go
> +	// d.Set("platform", object.Platform)
因为控制台的接口目前还没透出这些字段，这个管控正在该，改完这里放开。

2020-11-06 02:54 UTC, anserhyb commented on alicloud/resource_alicloud_cs_edge_kubernetes.go
> +			"deletion_protection": {
更新操作下次pr支持。

2020-11-06 03:12 UTC, anserhyb commented on alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
> +					"cluster_id":           os.Getenv("CLUSTER_ID"),
为了测试nodepool在去额外创建一个集群，是不是比较慢了。

2020-11-06 03:13 UTC, chushenmeshile requested changes

2020-11-06 03:13 UTC, chushenmeshile commented on website/docs/r/cs_kubernetes.html.markdown
> +* `master_instance_types` - (**Required**) The instance type of master node. Specify one type for single AZ Cluster, three types for MultiAZ Cluster.
这里不需要加**吧

2020-11-06 03:13 UTC, chushenmeshile commented on website/docs/r/cs_kubernetes.html.markdown
> +* `kms_encryption_context` - (Optional, MapString, Available in 1.57.1+) An KMS encryption context used to decrypt `kms_encrypted_password` before creating or updating a cs kubernetes with `kms_encry
版本号

2020-11-06 06:14 UTC, anserhyb commented on alicloud/resource_alicloud_cs_kubernetes.go
> +	// m := l[0].(map[string]interface{})
yep

2020-11-06 07:05 UTC, anserhyb commented on website/docs/r/cs_kubernetes.html.markdown
> +* `master_instance_types` - (**Required**) The instance type of master node. Specify one type for single AZ Cluster, three types for MultiAZ Cluster.
因为我们的参数很多，用户如何能够一眼找到需要的参数，我特意给加粗了，不知道TF文档规范允许加粗么/

2020-11-06 07:07 UTC, anserhyb commented on website/docs/r/cs_kubernetes.html.markdown
> +* `kms_encryption_context` - (Optional, MapString, Available in 1.57.1+) An KMS encryption context used to decrypt `kms_encrypted_password` before creating or updating a cs kubernetes with `kms_encry
这些都是之前的版本支持的参数，我把所有的参数做了归类，位置有所调整。新增的参数，我都加了（Available in 1.1.04+）

2020-11-09 12:44 UTC, merged

2020-11-19 15:31 UTC, yagrxu commented on alicloud/resource_alicloud_cs_edge_kubernetes.go
> +			"deletion_protection": {
客户如果terraform 版本升级，之前没有设置值，默认值会改变集群的逻辑么？