hbaseue instance type
aliyun/terraform-provider-alicloud pull request #3035
Opened 2020-11-17 13:52 UTC by joyken

hbase/hbaseue

1. ip white/ security group
2. modify instnace type
3. conn addrs
4. account/password

2020-11-17 13:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3035) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3035) before we can accept your contribution.<br/><hr/>**泉韵** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3035) it.</sub>

2020-11-18 09:53 UTC, chushenmeshile requested changes

2020-11-18 09:53 UTC, chushenmeshile commented on alicloud/resource_alicloud_hbase_instance.go
> +
这里是nil?

2020-11-18 09:53 UTC, chushenmeshile commented on alicloud/resource_alicloud_hbase_instance.go
> +
这里不需要判断，可以直接设置吧

2020-11-18 09:53 UTC, chushenmeshile commented on alicloud/resource_alicloud_hbase_instance.go
>  	return nil
account 和password没有设置，是没有返回吗

2020-11-18 09:53 UTC, chushenmeshile commented on alicloud/resource_alicloud_hbase_instance.go
> +		if err != nil {
addDebug加上modifyIpWhitelistGroupReq，剩下的也一样

2020-11-18 09:53 UTC, chushenmeshile commented on alicloud/resource_alicloud_hbase_instance.go
> +			security_groups := strings.Join(expandStringList(securityGroups), ",")
这里不需要判断，可以直接使用strings.join

2020-11-18 09:53 UTC, chushenmeshile commented on alicloud/resource_alicloud_hbase_instance_test.go
> +data "alicloud_zones" "default" {
resourceHBaseConfigVpcColdStorage 没有看到被引用

2020-11-18 09:53 UTC, chushenmeshile commented on website/docs/r/hbase_instance.html.markdown
下个版本是1.104.0，ui_proxy_conn_addrs ，zk_conn_addrs，slb_conn_addrs是Computed放到Attributes Reference下面

2020-11-18 11:45 UTC, quanyun-ali commented on alicloud/resource_alicloud_hbase_instance.go
> +
此没用，在下面赋值了，可以删掉

2020-11-18 11:46 UTC, quanyun-ali commented on alicloud/resource_alicloud_hbase_instance.go
> +
可以

2020-11-18 11:47 UTC, quanyun-ali commented on alicloud/resource_alicloud_hbase_instance.go
>  	return nil
目前account 和 password 仅提供 重置，不提供查询（特别是密码不希望被查询出来）和找回。

2020-11-18 12:08 UTC, quanyun-ali commented on alicloud/resource_alicloud_hbase_instance.go
> +		if err != nil {
OK，已修复

2020-11-19 04:10 UTC, quanyun-ali commented on alicloud/resource_alicloud_hbase_instance.go
> +			security_groups := strings.Join(expandStringList(securityGroups), ",")
因pop，此字段强制，空字符串 导致接口无法调用，此需要额外兼容下。

2020-11-19 04:10 UTC, quanyun-ali commented on alicloud/resource_alicloud_hbase_instance_test.go
> +data "alicloud_zones" "default" {
已添加

2020-11-19 04:11 UTC, quanyun-ali commented on website/docs/r/hbase_instance.html.markdown
done

2020-11-20 07:28 UTC, zql-tqy requested changes

2020-11-20 07:28 UTC, zql-tqy commented on alicloud/resource_alicloud_hbase_instance.go
> +	d.Set("cold_storage_size", 0)
这个直接 set 0 进去会有问题吧， 我看这个属性是个选填的，如果用户指定的不是 0，set 0 进去肯定会有 diff 的

2020-11-20 07:28 UTC, zql-tqy commented on alicloud/resource_alicloud_hbase_instance.go
> +	if d.HasChange("core_disk_size") && d.Get("engine") != "bds" {
这里添加了个限制条件，需要在文档中也进行说明下

2020-11-20 07:28 UTC, zql-tqy commented on website/docs/r/hbase_instance.html.markdown
> +* `account` - (Optional, Available in 1.104.0+) the account of the cluster web ui.
描述的首字母都调整为 大写

2020-11-20 07:28 UTC, zql-tqy commented on alicloud/resource_alicloud_hbase_instance.go
> -				ForceNew:     true,
这个 pay_type 去掉了 forceNew 了，但是在 update 中没看到支持修改的操作

2020-11-20 07:28 UTC, zql-tqy commented on alicloud/resource_alicloud_hbase_instance_test.go
> +			{
测试中没有对 security_groups, account, password 这三个属性进行测试

2020-11-20 07:34 UTC, quanyun-ali commented on alicloud/resource_alicloud_hbase_instance.go
> +	d.Set("cold_storage_size", 0)
OK， 这块先配置回去，

2020-11-20 07:37 UTC, quanyun-ali commented on alicloud/resource_alicloud_hbase_instance.go
> +	if d.HasChange("core_disk_size") && d.Get("engine") != "bds" {
done

2020-11-20 07:37 UTC, quanyun-ali commented on website/docs/r/hbase_instance.html.markdown
> +* `account` - (Optional, Available in 1.104.0+) the account of the cluster web ui.
done

2020-11-20 07:40 UTC, quanyun-ali commented on alicloud/resource_alicloud_hbase_instance.go
> -				ForceNew:     true,
还是forceNew, 暂时缺少更改接口，done

2020-11-25 01:51 UTC, joyken commented on alicloud/resource_alicloud_hbase_instance.go
> +	d.Set("cold_storage_size", 0)
已更新接口，填充有效的值

2020-11-25 01:56 UTC, joyken commented on website/docs/r/hbase_instance.html.markdown
> +* `account` - (Optional, Available in 1.104.0+) the account of the cluster web ui.
同时修正其他行  首字母大写

2020-11-25 01:57 UTC, joyken commented on alicloud/resource_alicloud_hbase_instance_test.go
> +			{
已增加

2020-11-26 01:34 UTC, merged

2020-11-29 16:33 UTC, foo-source commented
Hi @xiaozhu36, terraform init still install previous version. Could you please check?
```
Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/alicloud versions matching "~> 1.0, ~> 1.0, ~> 1.0, ~> 1.0, ~> 1.0"...
- Finding latest version of hashicorp/null...
- Installing hashicorp/alicloud v1.104.0...
- Installed hashicorp/alicloud v1.104.0 (signed by HashiCorp)
- Installing hashicorp/null v3.0.0...
- Installed hashicorp/null v3.0.0 (signed by HashiCorp)
```

2020-11-30 04:58 UTC, foo-source commented
Hi @xiaozhu36, please refer to above issue. Thank you so much.