edas k8s application
aliyun/terraform-provider-alicloud pull request #3039
Opened 2020-11-18 06:47 UTC by Hellojungle

Add resource for EDAS K8s application

2020-11-18 06:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3039) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3039) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3039) it.</sub>

2020-11-19 04:54 UTC, chushenmeshile requested changes

2020-11-19 04:54 UTC, chushenmeshile commented on alicloud/resource_alicloud_edas_k8s_application.go
> +		}
这种写法是不是相当于默认值，可以在schema中写default

2020-11-19 04:54 UTC, chushenmeshile commented on alicloud/resource_alicloud_edas_k8s_application.go
> +				return WrapError(Error("web_container or edas_container_version is needed for creating war k8s application"))
两个参数只取一个有问题吗

2020-11-19 04:54 UTC, chushenmeshile commented on alicloud/resource_alicloud_edas_k8s_application.go
> +			d.SetPartial("image_url")
应该在更新之后设置值，否则更新接口调用失败，也会把修改的值写进state文件

2020-11-19 04:54 UTC, chushenmeshile commented on alicloud/resource_alicloud_edas_k8s_application.go
> +		}
这里应该直接写request.Image = d.Get("image_url").(string)，放到hasChange外面，不需要这么麻烦

2020-11-19 04:54 UTC, chushenmeshile commented on alicloud/resource_alicloud_edas_k8s_application.go
> +		}
这个同上面

2020-11-19 04:54 UTC, chushenmeshile commented on alicloud/resource_alicloud_edas_k8s_application_test.go
> +					}),
这个值为啥写成checkset

2020-11-19 04:54 UTC, chushenmeshile commented on alicloud/resource_alicloud_edas_k8s_application_test.go
> +			},
属性修改需要先一个一个测试，然后再统一修改

2020-11-19 04:54 UTC, chushenmeshile commented on website/docs/r/edas_k8s_application.html.markdown
> +
新的版本号是1.104.0

2020-11-19 04:54 UTC, chushenmeshile commented on website/docs/r/edas_k8s_application.html.markdown
> +* `package_version` - (Optional, Computed) The version number of the deployment package. WAR and FatJar types are required. Please customize its meaning.
Computed 不用写

2020-11-19 05:31 UTC, Hellojungle commented on alicloud/resource_alicloud_edas_k8s_application.go
> +				return WrapError(Error("web_container or edas_container_version is needed for creating war k8s application"))
两个参数必须都存在

2020-11-19 06:05 UTC, chushenmeshile commented on alicloud/resource_alicloud_edas_k8s_application.go
> +				return WrapError(Error("web_container or edas_container_version is needed for creating war k8s application"))
你的判断有问题，应该用或

2020-11-19 06:26 UTC, Hellojungle commented on alicloud/resource_alicloud_edas_k8s_application.go
> +				return WrapError(Error("web_container or edas_container_version is needed for creating war k8s application"))
说错了 至少有一个

2020-11-19 07:48 UTC, Hellojungle commented
修改后的test结果
![rebuild-jar](https://user-images.githubusercontent.com/18479517/99636660-afe1f880-2a7e-11eb-96ce-c35055f99975.jpg)
![rebuild-multi](https://user-images.githubusercontent.com/18479517/99636662-b07a8f00-2a7e-11eb-8498-eb34e185477e.jpg)
![rebuild-basic](https://user-images.githubusercontent.com/18479517/99636657-ace70800-2a7e-11eb-96a5-2e4496740c10.jpg)

2020-11-23 08:45 UTC, chushenmeshile requested changes

2020-11-23 08:45 UTC, chushenmeshile commented on alicloud/resource_alicloud_edas_k8s_application.go
> +				if NotFoundError(err) {
这里只是字符串转int吧，没有notfound错误

2020-11-23 08:45 UTC, chushenmeshile commented on alicloud/resource_alicloud_edas_k8s_application.go
> +				return WrapError(Error("web_container or edas_container_version is needed for creating war k8s application"))
这里是update逻辑，creating修改为update是不是更好些

2020-11-23 08:45 UTC, chushenmeshile commented on alicloud/resource_alicloud_edas_k8s_application_test.go
> +	"package_type":     CHECKSET,
package_type  不需要设置checkset

2020-11-23 08:45 UTC, chushenmeshile commented on website/docs/r/edas_k8s_application.html.markdown
> +
现在版本号变为1.105.0了

2020-11-23 08:45 UTC, chushenmeshile commented on website/docs/r/edas_k8s_application.html.markdown
> +* `liveness` - (Optional) Container survival status monitoring, format such as: {"failureThreshold": 3,"initialDelaySeconds": 5,"successThreshold": 1,"timeoutSeconds": 1,"tcpSocket":{"host":"", "port
json字符串统一下吧，都用``括起来

2020-11-26 12:51 UTC, merged