adapter pvtz datasource and resource
aliyun/terraform-provider-alicloud pull request #3094
Opened 2020-12-03 08:26 UTC by chushenmeshile

2020-12-03 08:59 UTC, zql-tqy requested changes

2020-12-03 08:59 UTC, zql-tqy commented on alicloud/data_source_alicloud_pvtz_zones.go
> +				"vpc_name":    v.(map[string]interface{})["BindVpcs"],
这个都使用的  v.(map[string]interface{})["BindVpcs"] 没问题么？

2020-12-03 08:59 UTC, zql-tqy commented on alicloud/data_source_alicloud_pvtz_zones_test.go
> +			"zones.0.bind_vpcs.#":      "0",
这个能不能创建一个绑定 vpc 的，然后测试下能否查出 vpc 相关信息，可以检测 datasource 中属性是否设置正确

2020-12-03 08:59 UTC, zql-tqy commented on alicloud/resource_alicloud_pvtz_zone.go
> -			"is_ptr": {
这些出参也要兼容，不能直接去掉了

2020-12-03 08:59 UTC, zql-tqy commented on alicloud/resource_alicloud_pvtz_zone_attachment.go
> +	vpcs := object["BindVpcs"].(map[string]interface{})["Vpc"].([]interface{})
这一段为啥调整了，这个一定会返回么？如果不返回断言会失败吧，下面也一样

2020-12-03 08:59 UTC, zql-tqy commented on alicloud/data_source_alicloud_pvtz_zones.go
> +				ForceNew: true,
这个文档中有枚举值

2020-12-03 08:59 UTC, zql-tqy commented on website/docs/d/pvtz_zones.html.markdown
> +* `query_region_id` - (Optional, Available 1.106.0+) query_region_id for zone regionId
query_region_id 这个是啥？标点补齐

2020-12-03 08:59 UTC, zql-tqy commented on website/docs/d/pvtz_zones.html.markdown
> +  * `slave_dns` - Whether to turn on secondary DNS. Value:
纯出参不用标记枚举值

2020-12-03 08:59 UTC, zql-tqy commented on website/docs/d/pvtz_zones.html.markdown
> +* `search_mode` - (Optional, Available 1.106.0+) Search mode. Value:
Valid values:

2020-12-03 08:59 UTC, zql-tqy commented on website/docs/r/pvtz_zone.html.markdown
> -* `record_count` - The count of the Private Zone Record.
出参不全

2020-12-03 08:59 UTC, zql-tqy commented on website/docs/d/pvtz_zones.html.markdown
> -  * `name` - Name of the Private Zone.
这个 name 也要留着，保持兼容

2020-12-03 09:42 UTC, chushenmeshile commented on alicloud/resource_alicloud_pvtz_zone_attachment.go
> +	vpcs := object["BindVpcs"].(map[string]interface{})["Vpc"].([]interface{})
这个是因为调用describeZone方法，返回是map[string]interface{},这里需要手动修改下

2020-12-03 09:45 UTC, chushenmeshile commented on website/docs/d/pvtz_zones.html.markdown
> +* `query_region_id` - (Optional, Available 1.106.0+) query_region_id for zone regionId
list方法查询参数

2020-12-08 01:58 UTC, xiaozhu36 requested changes

2020-12-08 01:58 UTC, xiaozhu36 commented on alicloud/resource_alicloud_pvtz_zone.go
> -		d.SetPartial("lang")
这几个为啥要删掉

2020-12-08 01:58 UTC, xiaozhu36 commented on website/docs/d/pvtz_zones.html.markdown
> +    - Like: fuzzy search.
这个不对吧，应该是 LIKE 吧

2020-12-08 02:24 UTC, chushenmeshile commented on alicloud/resource_alicloud_pvtz_zone.go
> -		d.SetPartial("lang")
这里修改的是remark，只设置remark就可以，上个方法设置是proxy_pattern,和产品沟通过了，此接口只修改proxy_pattern，所以user_client_ip和lang是otherparameter，这两个属性变了不会调用修改接口

2020-12-08 02:24 UTC, chushenmeshile commented on website/docs/d/pvtz_zones.html.markdown
> +    - Like: fuzzy search.
修改了

2020-12-08 04:40 UTC, xiaozhu36 requested changes

2020-12-08 04:40 UTC, xiaozhu36 commented on website/docs/r/pvtz_zone.html.markdown
update time和creation time既然不输出了，文档中直接去掉就好了。另外，对于不输出的computed的变量，要在schema中定义为Removed而不是 Deprecated。

2020-12-08 06:27 UTC, xiaozhu36 approved these changes

2020-12-08 06:27 UTC, merged