adapter zone record datasource and resource
aliyun/terraform-provider-alicloud pull request #3117
Opened 2020-12-10 07:08 UTC by chushenmeshile

2020-12-10 07:52 UTC, zql-tqy requested changes

2020-12-10 07:52 UTC, zql-tqy commented on alicloud/resource_alicloud_pvtz_zone_record.go
> +				ValidateFunc: validation.IntInSlice([]int{1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 3, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 4, 40, 41, 42, 43, 44, 4
这个可以使用 intBetween  这个吧，你这是什么写法
另外这个属性之前是有压制函数的吧

2020-12-10 07:52 UTC, zql-tqy commented on alicloud/resource_alicloud_pvtz_zone_record.go
> +	err = resource.Retry(d.Timeout(schema.TimeoutCreate), func() *resource.RetryError {
之前重试是 5 分钟，现在一分钟能保证重试成功么

2020-12-10 07:52 UTC, zql-tqy commented on alicloud/service_alicloud_pvtz.go
> +		response, err = conn.DoRequest(StringPointer(action), nil, StringPointer("POST"), StringPointer("2018-01-01"), StringPointer("AK"), nil, request, &runtime)
这个之前是有流控重试的

2020-12-10 07:52 UTC, zql-tqy commented on website/docs/d/pvtz_zone_records.html.markdown
> +* `tag` - (Optional, Available 1.108.0+) It is not filled in by default, and queries the current zone resolution records. Fill in "ecs" to query the host name record list under the VPC associated wit
这个支持 tag 过滤，在 records 的输出中没有 tag 的出参么

2020-12-10 07:52 UTC, zql-tqy commented on website/docs/r/pvtz_zone_record.html.markdown
> +* `ttl` - (Optional) The ttl of the Private Zone Record. Default to 60.
Default to \`60\`.

2020-12-10 07:52 UTC, zql-tqy commented on website/docs/r/pvtz_zone_record.html.markdown
> +    - DISABLE: pause parsing.
新增加的 timeout 在文档中也要添加上

2020-12-10 07:52 UTC, zql-tqy commented on alicloud/resource_alicloud_pvtz_zone_record.go
> +				ValidateFunc: validation.StringInSlice([]string{"A", "CNAME", "MX", "PTR", "TXT"}, false),
枚举值和之前相比缺了一个，文档也是

2020-12-10 08:32 UTC, chushenmeshile commented on website/docs/d/pvtz_zone_records.html.markdown
> +* `tag` - (Optional, Available 1.108.0+) It is not filled in by default, and queries the current zone resolution records. Fill in "ecs" to query the host name record list under the VPC associated wit
tag只是一个查询属性，看文档的描述和标签不一样

2020-12-11 02:01 UTC, chushenmeshile commented on website/docs/d/pvtz_zone_records.html.markdown
> +* `tag` - (Optional, Available 1.108.0+) It is not filled in by default, and queries the current zone resolution records. Fill in "ecs" to query the host name record list under the VPC associated wit
tag和正常的标签不一样

2020-12-14 09:54 UTC, merged