rds_disk_encryption
aliyun/terraform-provider-alicloud pull request #3121
Opened 2020-12-11 03:50 UTC by archmagor

支持RDS MySQL、MSSQL、PostgreSQL的云盘加密功能

2020-12-11 03:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3121) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3121) before we can accept your contribution.<br/><hr/>**shiyin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3121) it.</sub>

2020-12-15 10:08 UTC, liuri1205 requested changes

2020-12-15 10:08 UTC, liuri1205 commented on alicloud/resource_alicloud_db_instance.go
> +				return nil, err
`err` -> `WrapError(err)` err 用 WrapError 包裹

2020-12-15 10:24 UTC, archmagor commented on alicloud/resource_alicloud_db_instance.go
> +				return nil, err
OK

2020-12-18 13:16 UTC, merged