Feature: managedk8s support zero node, management nodepool and remove nodepool nodes
aliyun/terraform-provider-alicloud pull request #3131
Opened 2020-12-15 15:59 UTC by anserhyb

1.  professional managed cluster support zero nodes.
2. professional managed cluster support maintenance window.
3. professional managed cluster support management nodepool.
4. nodepool support remove nodepool nodes.
5. alicloud_cs_kubernetes_node_pool support destroy.

2020-12-16 07:55 UTC, zql-tqy requested changes

2020-12-16 07:55 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_kubernetes.go
> +	if !d.IsNewResource() && d.HasChange("maintenance_window") {
这个属性 maintenance_window 在 create 方法中没有进行处理吧，如果 create 中没有进行处理的只是在 update 中进行设置不需要添加 IsNewResource 判断，如过 create 中设置过了且 create 后调用 update 方法才添加这个进行判断

2020-12-16 07:55 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +			_ = removeNodePoolNodes(d, meta, parts)
这个返回的 err 不需要进行处理吗？

2020-12-16 07:55 UTC, zql-tqy commented on alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
> +						"node_count": "1",
下次测试的时候，在前面的 step 中每个 step 测试一个属性的变更，最后一个 step 集体测试可变更属性

2020-12-16 07:55 UTC, zql-tqy commented on website/docs/r/cs_kubernetes_node_pool.html.markdown
> +  cluster_id                   = ${alicloud_cs_managed_kubernetes.default.0.id}
这些引用资源的把  ${} 去掉，直接写 alicloud_cs_managed_kubernetes.default.0.id 
下面的也是一样

2020-12-16 07:55 UTC, zql-tqy commented on website/docs/r/cs_kubernetes_node_pool.html.markdown
> +  * category: the type of the data disks. Valid values:cloud,cloud_efficiency,cloud_ssd and cloud_essd.
枚举值使用反引号
cloud,cloud_efficiency,cloud_ssd and cloud_essd.  -> \`cloud\`, \`cloud_efficiency\`, \`cloud_ssd\` and \`cloud_essd\`.
默认值也使用反引号 \`40\`
下面的也是一样

2020-12-16 11:16 UTC, anserhyb commented on alicloud/resource_alicloud_cs_kubernetes.go
> +	if !d.IsNewResource() && d.HasChange("maintenance_window") {
处理了，1579行。

2020-12-17 02:14 UTC, anserhyb commented on alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
> +						"node_count": "1",
OK

2020-12-21 01:59 UTC, xiaozhu36 requested changes

2020-12-21 01:59 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes.go
> +	}
这个地方为啥要单独判断

2020-12-21 01:59 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +		return WrapErrorf(err, DefaultErrorMsg, d.Id(), "DeleteKubernetesClusterNodes", DenverdinoAliyungo)
这个地方为啥要释放集群

2020-12-21 01:59 UTC, xiaozhu36 commented on website/docs/r/cs_managed_kubernetes.html.markdown
> +* `maintenance_window` - (Optional, Available in 1.109.0+) The cluster maintenance window，effective only in the professional managed cluster. Managed node pool will use it. Detailed below.
1.109.0 已经发布了，这个地方要改成 1.109.1

2020-12-21 01:59 UTC, xiaozhu36 commented on website/docs/r/cs_managed_kubernetes.html.markdown
> +* `maintenance_window` - (Optional, Available in 1.109.0+) The cluster maintenance window，effective only in the professional managed cluster. Managed node pool will use it. Detailed below.
所有涉及到1.109.0的地方都要改

2020-12-21 02:47 UTC, closed without merging