Add sls project tags
aliyun/terraform-provider-alicloud pull request #3144
Opened 2020-12-22 06:44 UTC by xuxiaoahang2018

2020-12-22 06:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3144) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3144) before we can accept your contribution.<br/><hr/>**wb-xxh498912** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3144) it.</sub>

2020-12-23 08:41 UTC, zql-tqy requested changes

2020-12-23 08:41 UTC, zql-tqy commented on website/docs/r/log_project_tags.html.markdown
> +# alicloud\_log\_project_tags
alicloud\\_log\\_project\\_tags

2020-12-23 08:41 UTC, zql-tqy commented on website/docs/r/log_project_tags.html.markdown
> +* `project_name` - The project name.
如果在入参中指定了就不需要在出参中说明了，出参可以写一个 id

2020-12-23 08:41 UTC, zql-tqy commented on website/docs/r/log_project_tags.html.markdown
> +Project tags is a resource used to tag a project. You can use this function to tag a project.
这个添加英文文档链接

2020-12-23 08:41 UTC, zql-tqy commented on website/docs/r/log_project_tags.html.markdown
> +## Module Support
这个不用添加

2020-12-30 09:42 UTC, xuxiaoahang2018 commented
已经更新到了projects resource 资源里面, 关闭该pr

2020-12-30 09:42 UTC, closed without merging