add vpc cidr block resource
aliyun/terraform-provider-alicloud pull request #3152
Opened 2020-12-23 11:20 UTC by zch228

add vpc cidr block resource

2020-12-23 11:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3152) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3152) before we can accept your contribution.<br/><hr/>**wb-chs868772** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3152) it.</sub>

2020-12-24 02:25 UTC, zql-tqy requested changes

2020-12-24 02:25 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_cidr_block.go
> +		}
我理解这里如果 vpcId 查询不到直接报错比较合理

2020-12-24 02:25 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_cidr_block_test.go
> +func TestCidrAlicloudVpc(t *testing.T) {
TestCidrAlicloudVpc  -> TestAccAlicloudVpcCidrBlock

2020-12-24 02:25 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_cidr_block_test.go
> +						"name": fmt.Sprintf("tf_testCidrCheckVpcConfigName%d", rand),
没有 check secondary_cidr_block 属性

2020-12-24 02:25 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_cidr_block_test.go
> +	"route_table_id":    CHECKSET,
这个属性都不是当前资源查询返回的能 check 通过？

2020-12-24 02:25 UTC, zql-tqy commented on website/docs/r/vpc_cidr.html.markdown
> +page_title: "Alicloud: alicloud_vpc_cidr"
alicloud_vpc_cidr_block

2020-12-24 02:25 UTC, zql-tqy commented on website/docs/r/vpc_cidr.html.markdown
> +sidebar_current: "docs-alicloud-resource-vpc-cidr"
docs-alicloud-resource-vpc-cidr-block

2020-12-24 02:25 UTC, zql-tqy commented on website/docs/r/vpc_cidr.html.markdown
> + Provides a resource to call AssociateVpcCidrBlock to add additional IPv4 network segments to the VPC.
添加英文文档链接

2020-12-24 02:25 UTC, zql-tqy commented on website/docs/r/vpc_cidr.html.markdown
> +data "alicloud_vpcs" "vpcs" {
这个 data 不需要添加

2020-12-24 02:25 UTC, zql-tqy commented on website/docs/r/vpc_cidr.html.markdown
> +* `secondary_cidr_block` -  Additional IPv4 network segment to be added.
添加上 (Required, ForceNew)

2020-12-24 02:25 UTC, zql-tqy commented on website/docs/r/vpc_cidr.html.markdown
> +
添加版本
-> \*\*NOTE:\*\* Available in v1.110.0+.

2020-12-24 02:25 UTC, zql-tqy commented on website/docs/r/vpc_cidr.html.markdown
> +
添加 import

2020-12-24 02:25 UTC, zql-tqy commented on website/docs/r/vpc_cidr.html.markdown
> +---
在 alicloud.erb 文档中进行注册

2020-12-24 02:25 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_cidr_block.go
> +		//if IsExceptedError(err, "InvalidInstanceId") {
没用的注释去掉

2020-12-29 02:20 UTC, zql-tqy requested changes

2020-12-29 02:20 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_test.go
> +					}),
这里再添加一个 import 的 step

2020-12-29 02:20 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc.go
> +			d.Set("secondary_cidr_block", i[0].(string))
secondary_cidr_block 支持传入多个么？这里只取第 0 个会不会有遗漏的情况

2020-12-29 02:20 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc.go
> -	if d.IsNewResource() {
为什么把 IsNewResource 去掉？另外你这个 SecondaryCidrBlock 属性在 create 方法中没有没有设置，应该放到 IsNewResource 判断上面去设置

2020-12-29 02:20 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc.go
> +			"SecondaryCidrBlock": d.Get("secondary_cidr_block"),
这个 request 的构建和上面的 ModifyVpcAttribute 保持一致，放在 attributeUpdate 外面去，当 attributeUpdate = true 再进行 get 赋值

2020-12-29 02:20 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc.go
> +			"secondary_cidr_block": {
这个属性在 vpc 的文档中添加上

2021-01-08 14:08 UTC, merged

2021-01-12 13:02 UTC, brianmori commented
These issues can also be closed: #2991 #2753