1. Add resource and datasource for Resource Manager Shared Resource
aliyun/terraform-provider-alicloud pull request #3168
Opened 2020-12-29 04:24 UTC by liuri1205

2. Add resource and datasource for Resource Manager Shared Target

2020-12-29 12:10 UTC, chushenmeshile requested changes

2020-12-29 12:10 UTC, chushenmeshile commented on alicloud/data_source_alicloud_resource_manager_shared_targets.go
> +				if _, ok := idsMap[fmt.Sprint(item["EntityId"])]; !ok {
这里的ids和resource的不一致

2020-12-29 12:10 UTC, chushenmeshile commented on alicloud/resource_alicloud_resource_manager_shared_resource.go
> +			},
文档中这个值只能写VSwitch，这里是不是得写个验证函数

2020-12-30 02:13 UTC, liuri1205 commented on alicloud/data_source_alicloud_resource_manager_shared_targets.go
> +				if _, ok := idsMap[fmt.Sprint(item["EntityId"])]; !ok {
有父子关系的资源，DataSource 的 ids 中的元素是子资源的 ID

2020-12-30 02:19 UTC, liuri1205 commented on alicloud/resource_alicloud_resource_manager_shared_resource.go
> +			},
已补充枚举值

2020-12-30 04:16 UTC, xiaozhu36 approved these changes

2020-12-30 04:16 UTC, merged