add some value check; remove classic
aliyun/terraform-provider-alicloud pull request #3174
Opened 2020-12-30 14:06 UTC by quanyun-ali

1、add some value check: accout, pwd.
2、remove classic, and classic case

2021-01-04 01:39 UTC, zql-tqy requested changes

2021-01-04 01:39 UTC, zql-tqy commented on alicloud/resource_alicloud_hbase_instance.go
> +				ValidateFunc: validation.Any(validation.IntBetween(800, 1000000), validation.IntInSlice([]int{0})),
这些添加的 validate 是之前就存在么，会对之前用户创建的实例造成影响吗这些添加的 validate 是之前就存在么，会对之前用户创建的实例造成影响吗

2021-01-04 01:39 UTC, zql-tqy commented on alicloud/resource_alicloud_hbase_instance_test.go
> -func TestAccAlicloudHBaseInstanceClassic(t *testing.T) {
classic 的测试为什么要去掉？

2021-01-05 10:15 UTC, quanyun-ali commented on alicloud/resource_alicloud_hbase_instance.go
> +				ValidateFunc: validation.Any(validation.IntBetween(800, 1000000), validation.IntInSlice([]int{0})),
以前没有加， 但是老实例也是一定满足此范围，

2021-01-05 10:15 UTC, quanyun-ali commented on alicloud/resource_alicloud_hbase_instance_test.go
> -func TestAccAlicloudHBaseInstanceClassic(t *testing.T) {
国际站已不开放 经典网络

2021-02-03 02:52 UTC, zql-tqy requested changes

2021-02-03 02:52 UTC, zql-tqy commented on alicloud/data_source_alicloud_hbase_instance_types.go
> +				Required: true,
这种增加必填属性的肯定与之前是不兼容的，用户之前的模板增加必填属性后就不能用了

2021-02-03 02:52 UTC, zql-tqy commented on alicloud/data_source_alicloud_hbase_instance_types.go
> +			"master_instance_types": {
这个也不兼容，可以另外增加 master_instance_types 把 types 标记为 Deprecated

2021-02-03 02:52 UTC, zql-tqy commented on alicloud/data_source_alicloud_hbase_instance_types.go
> +		return err
return WrapError(err)

2021-02-03 02:52 UTC, zql-tqy commented on alicloud/data_source_alicloud_hbase_instance_types.go
> +			"region_id": {
必填不兼容，另外 regionId 基本上使用的 clinet 的，这样也方便用户查询后能够直接使用结果创建资源

2021-02-03 02:52 UTC, zql-tqy commented on alicloud/resource_alicloud_hbase_instance.go
> +func engineDiffSuppressFunc(k, old, new string, d *schema.ResourceData) bool {
压制函数放到 diff_suppress_funcs.go 文件中吧

2021-02-03 02:52 UTC, zql-tqy commented on alicloud/resource_alicloud_hbase_instance.go
> +				DiffSuppressFunc: engineDiffSuppressFunc,
确认下压制函数是否会造成不兼容的影响

2021-02-03 02:52 UTC, zql-tqy commented on alicloud/resource_alicloud_hbase_instance_test.go
> +  name_regex = "default-tf--testAcc-00"
这种 datasource 查询的形式，我们这边 CI 跑 test 的时候肯定过不了，查询不到这个 vsw，建议使用默认 vpc 下的查询的 vsw 来进行测试

2021-02-03 02:52 UTC, zql-tqy commented on alicloud/resource_alicloud_hbase_instance_test.go
> +data "alicloud_security_groups" "default" {
安全组也不一定能够查询到，这也会导致 CI 跑 test 失败

2021-02-03 02:52 UTC, zql-tqy commented on website/docs/d/hbase_instance_types.html.markdown
>  ```
\`\`\`terraform

2021-02-03 02:52 UTC, zql-tqy commented on website/docs/d/hbase_instance_types.html.markdown
> +  charge_type = "Postpaid"
新增的查询条件和出参没有在下面标明 版本 1.115.0+

2021-02-03 02:52 UTC, zql-tqy commented on website/docs/r/hbase_instance.html.markdown
> +* `account` - (Optional, Available in 1.105.0+) The account of the cluster web ui. size [0-128].
Size

2021-02-03 08:59 UTC, zql-tqy requested changes

2021-02-03 08:59 UTC, zql-tqy commented on alicloud/resource_alicloud_hbase_instance_test.go
> +  is_default = "true"
vsw 不用使用默认的

2021-02-03 08:59 UTC, zql-tqy commented on alicloud/data_source_alicloud_hbase_instance_types.go
> +			"master_instance_types": {
这个出参结构调整下，使用一个出参 instance_types 然后将 master_instance_types 和 core_instance_types 作为其子属性吧，datasource 通常只有 ids 和 一个出参结构，这样下面 set 的也只需要 set 一个 instance_types；

2021-02-03 09:36 UTC, quanyun-ali commented on alicloud/resource_alicloud_hbase_instance_test.go
> +  is_default = "true"
已删除

2021-02-03 09:37 UTC, quanyun-ali commented on alicloud/data_source_alicloud_hbase_instance_types.go
> +			"master_instance_types": {
提炼一个输出参数，复用types

2021-02-05 05:30 UTC, xiaozhu36 approved these changes

2021-02-07 10:18 UTC, merged