1. Add resource and datasource for TSDB instance
aliyun/terraform-provider-alicloud pull request #3192
Opened 2021-01-06 04:06 UTC by liuri1205

2. Add datasource for TSDB Zones

2021-01-06 07:12 UTC, chushenmeshile requested changes

2021-01-06 07:12 UTC, chushenmeshile commented on alicloud/data_source_alicloud_tsdb_zones.go
> +		return WrapErrorf(err, FailedGetAttributeMsg, action, "$.InstanceList", response)
$.InstanceList 这个值不对吧

2021-01-06 07:12 UTC, chushenmeshile commented on alicloud/data_source_alicloud_tsdb_zones_test.go
> +
不成创建一个资源进行查询测试吗

2021-01-06 07:22 UTC, liuri1205 commented on alicloud/data_source_alicloud_tsdb_zones_test.go
> +
这个是个单纯的查询接口做成的 DataSource，用于查询 instance 的可用区

2021-01-06 07:24 UTC, liuri1205 commented on alicloud/data_source_alicloud_tsdb_zones.go
> +		return WrapErrorf(err, FailedGetAttributeMsg, action, "$.InstanceList", response)
已修改

2021-01-07 03:02 UTC, xiaozhu36 approved these changes

2021-01-07 03:03 UTC, merged