A new datasource and resource ga_bandwidth_package
aliyun/terraform-provider-alicloud pull request #3194
Opened 2021-01-07 07:04 UTC by chushenmeshile

2021-01-07 07:55 UTC, liuri1205 requested changes

2021-01-07 07:55 UTC, liuri1205 commented on alicloud/resource_alicloud_ga_bandwidth_package.go
> +			"payment_type": {
`payment_type` 的入参枚举值统一映射成标准形式，参考 tsdb instance 资源

2021-01-07 07:55 UTC, liuri1205 commented on website/docs/d/ga_bandwidth_packages.html.markdown
> +subcategory: "Ga"
`Ga` 使用全名，参考之前接入的 ga 资源文档

2021-01-07 07:55 UTC, liuri1205 commented on website/docs/r/ga_bandwidth_package.html.markdown
> +For information about Ga Bandwidth Package and how to use it, see [What is Bandwidth Package](https://help.aliyun.com/document_detail/153241.html).
这个没有英文文档么

2021-01-08 07:30 UTC, xiaozhu36 approved these changes

2021-01-08 07:30 UTC, merged