A new resource ga_bandwidth_package_attachment
aliyun/terraform-provider-alicloud pull request #3207
Opened 2021-01-11 09:28 UTC by chushenmeshile

2021-01-11 10:10 UTC, liuri1205 requested changes

2021-01-11 10:10 UTC, liuri1205 commented on alicloud/resource_alicloud_ga_bandwidth_package_attachment_test.go
> +data "alicloud_ga_accelerators" "default"{
这个使用 resource 吧

2021-01-11 10:10 UTC, liuri1205 commented on alicloud/resource_alicloud_ga_bandwidth_package_attachment.go
> +	"log"
fmt

2021-01-11 10:10 UTC, liuri1205 commented on alicloud/resource_alicloud_ga_bandwidth_package_attachment_test.go
> +	"status":         CHECKSET,
绑定的终态需要检查

2021-01-11 10:10 UTC, liuri1205 commented on website/docs/r/ga_bandwidth_package_attachment.html.markdown
> +  accelerator_id       = "example_value"
这个用个示例值，或者依赖资源的引用

2021-01-12 03:38 UTC, xiaozhu36 approved these changes

2021-01-12 06:47 UTC, merged