Add new resource and datasource for brain industrial
aliyun/terraform-provider-alicloud pull request #3209
Opened 2021-01-11 09:36 UTC by lixue323

2021-01-11 10:37 UTC, zql-tqy requested changes

2021-01-11 10:37 UTC, zql-tqy commented on alicloud/data_source_alicloud_brain_industrial_pid_organizations_test.go
> +		existConfig: testAccConfig(map[string]interface{}{
这个 ids 也测试下

2021-01-11 10:37 UTC, zql-tqy commented on alicloud/resource_alicloud_brain_industrial_pid_organization.go
> +	d.Set("pid_organization_name", object["OrganizationName"])
parent_pid_organization_id 没有 set 是 otherParameter ？

2021-01-11 10:37 UTC, zql-tqy commented on website/docs/r/brain_industrial_pid_organization.html.markdown
> +Provides a Brain Industrial Pid Organization resource.
有英文文档链接么？

2021-01-11 10:37 UTC, zql-tqy commented on alicloud/service_alicloud_brain_industrial.go
> +		err = WrapErrorf(err, DefaultErrorMsg, id, action, AlibabaCloudSdkGoERROR)
确认下是否存在资源不存在错误码

2021-01-11 10:37 UTC, zql-tqy commented on website/alicloud.erb
> +                  <ul class="nav">
这个是不是应该插入到 BGP 下面

2021-01-11 11:22 UTC, lixue323 commented on alicloud/service_alicloud_brain_industrial.go
> +		err = WrapErrorf(err, DefaultErrorMsg, id, action, AlibabaCloudSdkGoERROR)
以已经确定过了，目前没有

2021-01-11 11:24 UTC, lixue323 commented on website/docs/r/brain_industrial_pid_organization.html.markdown
> +Provides a Brain Industrial Pid Organization resource.
中英都没有现在

2021-01-11 11:25 UTC, lixue323 commented on alicloud/resource_alicloud_brain_industrial_pid_organization.go
> +	d.Set("pid_organization_name", object["OrganizationName"])
是otherParm

2021-01-12 03:37 UTC, xiaozhu36 approved these changes

2021-01-12 06:23 UTC, merged