Add resource for Eipanycast AnycastEipAddress Attachment
aliyun/terraform-provider-alicloud pull request #3215
Opened 2021-01-13 11:41 UTC by liuri1205

2021-01-13 12:01 UTC, chushenmeshile requested changes

2021-01-13 12:01 UTC, chushenmeshile commented on website/docs/r/eipanycast_anycast_eip_address_attachment.html.markdown
> +
这个不能通过资源关联创建吗

2021-01-14 02:28 UTC, liuri1205 commented on alicloud/provider_test.go
> +
用的埋点 slb instance 测试，如果没有设置，跳过测试

2021-01-14 02:29 UTC, liuri1205 commented on alicloud/resource_alicloud_eipanycast_anycast_eip_address_attach_attachment_test.go
> +					"bind_instance_region_id": "cn-hongkong",
eip目前只支持 cn-hangzhou，slb instance 支持绑定的只支持国外 region，这里采用的埋点测试，注释中有说明

2021-01-14 02:29 UTC, liuri1205 commented on website/docs/r/eipanycast_anycast_eip_address_attachment.html.markdown
> +For information about Eipanycast Anycast Eip Address Attachment and how to use it, see [What is Anycast Eip Address Attachment](https://help.aliyun.com/document_detail/171857.html).
暂时没有英文链接

2021-01-15 08:45 UTC, merged