New resource and datasource for Cms Monitor Group Instances.
aliyun/terraform-provider-alicloud pull request #3267
Opened 2021-02-01 09:05 UTC by zql-tqy

2021-02-02 02:21 UTC, chushenmeshile requested changes

2021-02-02 02:21 UTC, chushenmeshile commented on alicloud/resource_alicloud_cms_monitor_group_instances.go
> +			value += value + "," + InstancesMap["instance_id"].(string)
这个能拼接上吗，value是string类型啊，拼接方式有问题吧

2021-02-02 02:21 UTC, chushenmeshile commented on website/docs/d/cms_monitor_group_instanceses.html.markdown
> +		* `category` - The category of instance.
格式不对

2021-02-03 16:08 UTC, merged

2021-02-08 11:32 UTC, stack72 commented
Hi @xiaozhu36 

There's a spelling mistak on this resource name on this resource - `instanceses` should be `instances` right?