add support to vpc flow log
aliyun/terraform-provider-alicloud pull request #3290
Opened 2021-02-20 06:59 UTC by zhengjc2018

2021-02-22 04:36 UTC, zql-tqy requested changes

2021-02-22 04:36 UTC, zql-tqy commented on website/docs/r/vpc_flow_log.html.markdown
> +Provides a VPC Flow Log resource.
添加英文文档链接

2021-02-22 04:36 UTC, zql-tqy commented on website/docs/r/vpc_flow_log.html.markdown
> +
添加版本

2021-02-22 04:36 UTC, zql-tqy commented on website/docs/r/vpc_flow_log.html.markdown
> +sidebar_current: "docs-alicloud-resource-vpc"
docs-alicloud-resource-vpc-flow-log

2021-02-22 04:36 UTC, zql-tqy commented on alicloud/service_alicloud_vpc.go
> +func (s *VpcService) DescribeFlowLogs(id string) (v vpc.FlowLog, err error) {
都使用 common 形式的吧，后面 provider 都会使用 common 形式

2021-02-26 02:22 UTC, zql-tqy requested changes

2021-02-26 02:22 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_flow_log.go
> +		}
这里要对 status 进行 SetParpartial

2021-02-26 02:22 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_flow_log.go
> +		time.Sleep(10 * time.Second)
这个和上面 create 的一样，下面已经 WaitForVpcFlowLog 了为啥还要 Sleep ？

2021-02-26 02:22 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_flow_log.go
> +	return WrapError(VpcFlowLogService.WaitForVpcFlowLog(d.Id(), Deleted, DefaultTimeoutMedium))
WaitForVpcFlowLog 等待 flow 变成 Deleted 还能查到么？查不到不需要等待 3秒

2021-02-26 02:22 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_flow_log_test.go
> +			},
这里加一个 step 同时变更 flow_log_name，description 和 status 这三个属性

2021-02-26 02:22 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_flow_log_test.go
> +		// 根据自身返回体结构修改
这个注释要么删掉，要么改成英文的

2021-02-26 02:22 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_flow_log.go
> +	d.Set("flow_log_id", object["FlowLogId"].(string))
这个不是 schema中的属性不需要 set，作为 ID 已经在 create 中进行 set 了

2021-02-26 02:22 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_flow_log_test.go
> +				ImportStateVerifyIgnore: []string{"active"},
资源的所有属性在 schema 中都已经进行set 了，应该没有需要 ignore 的属性，另外这个 active 也不是属性

2021-02-26 02:22 UTC, zql-tqy commented on website/docs/r/vpc_flow_log.html.markdown
> +* `active` - (Optaional) Whether active flow log or not. Default value: true.
这个 active 没有去掉，另外 status 变成属性了需要在这里进行添加，下面的出参只有一个 ID

2021-02-26 02:22 UTC, zql-tqy commented on website/docs/r/vpc_flow_log.html.markdown
> +
这个资源有 timeout 需要在文档中进行添加

2021-02-26 02:22 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_flow_log_test.go
> +						"log_store_name": CHECKSET,
这两个值直接check 依赖模板中的 vpc-flow-log-for-eni

2021-03-01 02:24 UTC, xiaozhu36 requested changes

2021-03-01 02:24 UTC, xiaozhu36 commented on website/docs/r/vpc_flow_log.html.markdown
> +-> **NOTE:** While it uses `alicloud_vpc_flow_log` to build a vpc flow log resource, it will be active by default.
If it defaults to active, the status should have a default Active to control it.

2021-03-01 02:24 UTC, xiaozhu36 commented on website/docs/r/vpc_flow_log.html.markdown
> +-> **NOTE:** Available in v1.116.0+
The next version is v1.117.0

2021-03-01 02:24 UTC, xiaozhu36 commented on website/docs/r/vpc_flow_log.html.markdown
> +* `status` - (Optaional, Computed) The status of the VPC Flow Log.
Optional, not Optaional.

2021-03-01 03:51 UTC, merged