Modify ADB DBCluster to common type.
aliyun/terraform-provider-alicloud pull request #3295
Opened 2021-02-24 09:11 UTC by zql-tqy

2021-02-26 07:12 UTC, chushenmeshile requested changes

2021-02-26 07:12 UTC, chushenmeshile commented on alicloud/resource_alicloud_adb_db_cluster_test.go
> +	})
还有其他属性没有支持修改，没有测试全量修改

2021-02-26 07:12 UTC, chushenmeshile commented on website/docs/d/adb_db_clusters.html.markdown
> +* `status` - (Optional, ForceNew) The status of the resource.
枚举值

2021-02-26 07:12 UTC, chushenmeshile commented on website/docs/d/adb_clusters.html.markdown
> +-> **DEPRECATED:**  This resource  has been deprecated from version `1.116.0`. Please use new resource [alicloud_adb_db_clusters](https://www.terraform.io/docs/providers/alicloud/r/adb_db_clusters.ht
resource 改为datasource

2021-04-07 09:32 UTC, liuri1205 requested changes

2021-04-07 09:32 UTC, liuri1205 commented on alicloud/resource_alicloud_adb_db_cluster.go
> +			"db_cluster_class": {
补充枚举值

2021-04-07 09:32 UTC, liuri1205 commented on website/alicloud.erb
>                              </li>
Resource 的文档 erb

2021-04-07 09:32 UTC, liuri1205 commented on website/docs/r/adb_db_cluster.html.markdown
> +resource "alicloud_vpc" "default" {
vpc, vswitch 资源中的属性使用新名称

2021-04-07 09:32 UTC, liuri1205 commented on website/docs/r/adb_db_cluster.html.markdown
> +* `db_cluster_class` - (Optional, ForceNew) The db cluster class.
`db_cluster_class` 新增属性添加可用版本

2021-04-09 06:43 UTC, merged