Add new datasource for ecs snap policy
aliyun/terraform-provider-alicloud pull request #3309
Opened 2021-03-03 01:56 UTC by lixue323

resource alicloud_snapshot_policy renamed to alicloud_ecs_auto_snapshot_policy

2021-03-03 11:25 UTC, zql-tqy requested changes

2021-03-03 11:25 UTC, zql-tqy commented on alicloud/data_source_alicloud_ecs_auto_snapshot_policies_test.go
> +			"policies.0.copied_snapshots_retention_days": "-1",
format

2021-03-03 11:25 UTC, zql-tqy commented on alicloud/resource_alicloud_ecs_auto_snapshot_policy.go
> +	return resourceAlicloudEcsAutoSnapshotPolicyUpdate(d, meta)
这个是不是应该走 Read 方法，所有的属性都在 create 中设置过了吧

2021-03-03 11:25 UTC, zql-tqy commented on alicloud/resource_alicloud_ecs_auto_snapshot_policy_test.go
>  func TestAccAlicloudSnapshotPolicyBasic(t *testing.T) {
这个方法名都改下

2021-03-03 11:25 UTC, zql-tqy commented on website/docs/r/ecs_auto_snapshot_policy.html.markdown
> +
去掉空行

2021-03-04 03:10 UTC, lixue323 commented on alicloud/data_source_alicloud_ecs_auto_snapshot_policies_test.go
> +			"policies.0.copied_snapshots_retention_days": "-1",
format之后就是这个样子的

2021-03-04 06:12 UTC, merged