resource/alicloud_vpc: Upgrade VPC
aliyun/terraform-provider-alicloud pull request #3328
Opened 2021-03-09 10:04 UTC by liuri1205

2021-03-10 02:46 UTC, zql-tqy requested changes

2021-03-10 02:46 UTC, zql-tqy commented on alicloud/data_source_alicloud_vpcs.go
> +				Default:  false,
对于兼容情况，如果 get 方法返回的属性之前存在，此处的 default 应该设置为 true，否则对用户使用造成影响；

2021-03-10 02:46 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc.go
> +	if v, ok := d.GetOk("ipv6_cidr_block"); ok {
这两个属性应该有依赖关系吧

2021-03-10 02:46 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc.go
> +	stateConf := BuildStateConf([]string{}, []string{"Available"}, d.Timeout(schema.TimeoutCreate), 5*time.Second, vpcService.VpcStateRefreshFunc(d.Id(), []string{}))
初始值为 Pending

2021-03-10 02:46 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc.go
> +	d.Set("secondary_cidr_blocks", object["SecondaryCidrBlocks"].(map[string]interface{})["SecondaryCidrBlock"])
SecondaryCidrBlocks 这个有可能不返回情况吧

2021-03-10 02:46 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc.go
> +		d.SetPartial("vpc_name")
ipv6_cidr_block 没有 SetPartial

2021-03-10 02:46 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_test.go
> +			// 默认 VPC 跳过不删除
改成英文注释

2021-03-10 02:46 UTC, zql-tqy commented on alicloud/resource_alicloud_vpc_test.go
> +						"tags.For":     "Test",
加一个集体变更 step

2021-03-10 06:27 UTC, liuri1205 commented on alicloud/data_source_alicloud_vpcs.go
> +				Default:  false,
ok

2021-03-10 06:28 UTC, liuri1205 commented on alicloud/resource_alicloud_vpc.go
> +	d.Set("secondary_cidr_blocks", object["SecondaryCidrBlocks"].(map[string]interface{})["SecondaryCidrBlock"])
这个没有会返回空

2021-03-10 06:30 UTC, liuri1205 commented on alicloud/resource_alicloud_vpc.go
> +		d.SetPartial("vpc_name")
ipv6_cidr_block 不可改

2021-03-10 06:31 UTC, liuri1205 commented on alicloud/resource_alicloud_vpc_test.go
> +						"tags.For":     "Test",
ok

2021-03-11 02:23 UTC, liuri1205 commented on alicloud/resource_alicloud_vpc.go
> +	if v, ok := d.GetOk("ipv6_cidr_block"); ok {
ipv6_cidr_block 目前确认不支持用户设置，已删除入参

2021-03-11 02:23 UTC, liuri1205 commented on alicloud/resource_alicloud_vpc.go
> +	stateConf := BuildStateConf([]string{}, []string{"Available"}, d.Timeout(schema.TimeoutCreate), 5*time.Second, vpcService.VpcStateRefreshFunc(d.Id(), []string{}))
ok

2021-03-12 10:07 UTC, xiaozhu36 requested changes

2021-03-12 10:07 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc.go
>  			},
Why the `ipv6_cidr_block` is computed?

2021-03-12 10:07 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc.go
> +				Deprecated:    "Field 'name' has been deprecated from provider version 1.118.0. New field 'vpc_name' instead.",
The release 1.118.0 has been published and please use the next version

2021-03-15 01:23 UTC, liuri1205 commented on alicloud/resource_alicloud_vpc.go
>  			},
ipv6_cidr_block 虽然是接口入参，但是目前不支持手动设置和变更

2021-03-15 02:28 UTC, xiaozhu36 approved these changes

2021-03-15 02:28 UTC, merged