Add SLS ETL
aliyun/terraform-provider-alicloud pull request #3362
Opened 2021-03-24 07:31 UTC by xuxiaoahang2018

2021-03-24 09:34 UTC, zql-tqy requested changes

2021-03-24 09:34 UTC, zql-tqy commented on alicloud/resource_alicloud_log_etl.go
> +	err := resource.Retry(3*time.Minute, func() *resource.RetryError {
Retry 的 timeout 在 Schama 中进行定义，下面的也是一样

2021-03-24 09:34 UTC, zql-tqy commented on alicloud/resource_alicloud_log_etl_test.go
> +	name := fmt.Sprintf("sls-xuxiaohang-%d", rand)
name 使用 tf-testacc 开头

2021-03-24 09:34 UTC, zql-tqy commented on alicloud/resource_alicloud_log_etl_test.go
> +
添加一个 sweeper 方法，用来删除测试生成的没有被删除的 resource

2021-03-24 09:34 UTC, zql-tqy commented on alicloud/resource_alicloud_log_etl_test.go
> +	    name = "target"
这中名称直接在 name = "${var.name}1"，防止创建完成没有删除掉，下次无法使用该 name 进行创建。

2021-03-24 09:34 UTC, zql-tqy commented on alicloud/resource_alicloud_log_etl_test.go
> +					"etl_name":     "aliyun_etl_test",
这个也直接使用 "${var.name}"

2021-03-24 09:34 UTC, zql-tqy commented on alicloud/resource_alicloud_log_etl_test.go
> +					"description":  "update",
支持变更的属性都测试全了么

2021-03-24 09:34 UTC, zql-tqy commented on alicloud/resource_alicloud_log_etl_test.go
> +						"etl_name":         "aliyun_etl_test",
这里对 config 中设置的属性都要进行check

2021-03-24 09:34 UTC, zql-tqy commented on alicloud/service_alicloud_log.go
> +		if object.Name == id && status != Deleted {
这个是在判断什么？object.Name 和 id 是一样的么

2021-03-29 02:26 UTC, zql-tqy requested changes

2021-03-29 02:26 UTC, zql-tqy commented on alicloud/resource_alicloud_log_etl.go
> +	err := resource.Retry(3*time.Minute, func() *resource.RetryError {
3*time.Minute 替换成 d.Timeout(schema.TimeoutCreate) 使用 schema 中指定的超时时间

2021-03-29 02:26 UTC, zql-tqy commented on alicloud/resource_alicloud_log_etl.go
> +	wait := incrementalWait(3*time.Second, 3*time.Second)
这里也需要替换成 delete 的超时时间

2021-03-29 02:26 UTC, zql-tqy commented on alicloud/resource_alicloud_log_etl_test.go
> +				Config: testAccConfig(map[string]interface{}{
这个 step 放到最后一步与 status 变更为 RUNNING 的放在一起，用来测试实例集体变更属性是否成功

2021-03-29 02:26 UTC, zql-tqy commented on website/alicloud.erb
> +                            <a href="/docs/providers/alicloud/r/log_etl.html">alicloud_log_etl</a>
这个按照字母顺序排列

2021-03-29 02:26 UTC, zql-tqy commented on website/docs/r/log_etl.html.markdown
> +
添加版本

2021-03-29 02:26 UTC, zql-tqy commented on website/docs/r/log_etl.html.markdown
> +
多余的空行都去掉

2021-03-29 02:26 UTC, zql-tqy commented on website/docs/r/log_etl.html.markdown
> +   etl_name = "etl_name"
下面这几个 resource 进行下 fmt

2021-03-29 02:26 UTC, zql-tqy commented on website/docs/r/log_etl.html.markdown
> +* `etl_type` - (Optional) Log service etl type, the default value is ETL.
\`ETL\`
默认值添加反引号，下面的 枚举值 也添加上，句号后面首字母大写，都再检查下

2021-03-29 02:26 UTC, zql-tqy commented on website/docs/r/log_etl.html.markdown
> +
添加上 timeout 部分，可以参考 dcdn_domain

2021-03-29 02:26 UTC, zql-tqy commented on website/docs/r/log_etl.html.markdown
> +* `from_time` - (Optional,Computed) The start time of the processing job, the default starts from the current time.
不需要标记 Computed

2021-04-01 05:47 UTC, xiaozhu36 approved these changes

2021-04-01 06:31 UTC, merged