change launch template resource and support datasource launch templates
aliyun/terraform-provider-alicloud pull request #3364
Opened 2021-03-24 11:06 UTC by lixue323

2021-03-25 09:40 UTC, chushenmeshile requested changes

2021-03-25 09:40 UTC, chushenmeshile commented on alicloud/resource_alicloud_ecs_launch_template.go
> +	if v, ok := d.GetOk("launch_template_name"); ok {
launch_template_name和name冲突，也需要加name

2021-03-25 09:40 UTC, chushenmeshile commented on alicloud/resource_alicloud_ecs_launch_template_test.go
> +						"user_data": CHECKSET,
这里不用checkset吧

2021-03-25 09:40 UTC, chushenmeshile commented on alicloud/resource_alicloud_ecs_launch_template.go
> +				ValidateFunc: validation.StringInSlice([]string{"system", "self", "others", "marketplace", ""}, false),
少默认值

2021-03-25 10:12 UTC, lixue323 commented on alicloud/resource_alicloud_ecs_launch_template.go
> +	if v, ok := d.GetOk("launch_template_name"); ok {
之前手写代码中，删除，并不需要传入name，所以删除没有做兼容

2021-03-27 04:28 UTC, xiaozhu36 approved these changes

2021-03-27 04:28 UTC, merged