change ecs snapshot to common from amp.
aliyun/terraform-provider-alicloud pull request #3403
Opened 2021-04-01 10:58 UTC by lixue323

2021-04-01 12:35 UTC, liuri1205 requested changes

2021-04-01 12:35 UTC, liuri1205 commented on alicloud/resource_alicloud_ecs_snapshot.go
> +	return resourceAlicloudEcsSnapshotUpdate(d, meta)
没有需要在update中设置的参数, 应该走read

2021-04-01 12:35 UTC, liuri1205 commented on alicloud/resource_alicloud_ecs_snapshot_test.go
> +		addDebug(action, response, request)
`debug` 信息不需要

2021-04-01 12:35 UTC, liuri1205 commented on alicloud/resource_alicloud_ecs_snapshot_test.go
> +			return WrapErrorf(err, DataDefaultErrorMsg, "alicloud_ecs_snapshot", action, AlibabaCloudSdkGoERROR)
如果有错误打印 log 就行, 不需要 return err, 需要查询其他符合要求的的继续删除

2021-04-01 12:35 UTC, liuri1205 commented on alicloud/resource_alicloud_ecs_snapshot.go
> +			"category": {
`category ` 枚举值

2021-04-01 12:35 UTC, liuri1205 commented on alicloud/resource_alicloud_snapshot.go
> -			"name": {
`name` 没有兼容

2021-04-01 12:35 UTC, liuri1205 commented on alicloud/service_alicloud_ecs.go
> +		if IsExpectedErrors(err, []string{"InvalidFilterKey.NotFound", "InvalidFilterValue", "InvalidSnapshotIds.Malformed,InvalidStatus.NotFound,InvalidSnapshotType.NotFound", "InvalidSnapshotLinkId.NotFo
有错误码连一块了

2021-04-01 12:35 UTC, liuri1205 commented on website/docs/d/ecs_snapshots.html.markdown
> +-> **NOTE:** Available in v1.121.0+.
版本 120

2021-04-01 12:35 UTC, liuri1205 commented on alicloud/resource_alicloud_ecs_snapshot.go
> +			"instant_access": {
`instant_access ` 枚举值, 默认值

2021-04-01 12:35 UTC, liuri1205 commented on alicloud/resource_alicloud_ecs_snapshot.go
> +			"instant_access_retention_days": {
`instant_access_retention_days ` 范围值

2021-04-02 02:28 UTC, lixue323 commented on alicloud/service_alicloud_ecs.go
> +		if IsExpectedErrors(err, []string{"InvalidFilterKey.NotFound", "InvalidFilterValue", "InvalidSnapshotIds.Malformed,InvalidStatus.NotFound,InvalidSnapshotType.NotFound", "InvalidSnapshotLinkId.NotFo
那就是正常的错误码

2021-04-02 02:32 UTC, lixue323 commented on alicloud/resource_alicloud_ecs_snapshot_test.go
> +			return WrapErrorf(err, DataDefaultErrorMsg, "alicloud_ecs_snapshot", action, AlibabaCloudSdkGoERROR)
查询接口报错！错误需要抛出来，没办法继续往下走

2021-04-02 05:29 UTC, liuri1205 requested changes

2021-04-02 05:29 UTC, liuri1205 commented on website/docs/r/ecs_snapshot.html.markdown
> +* `category` - (Optional, ForceNew) The category of the snapshot.
文档中属性的枚举值描述补充下

2021-04-02 05:35 UTC, liuri1205 requested changes

2021-04-02 05:35 UTC, liuri1205 commented on website/docs/d/snapshots.html.markdown
> +
DataSource 和 resource 文档弃用版本 1.120.0

2021-04-02 06:08 UTC, merged