resource/alicloud_ecs_disk: Deprecates the name and use disk_name instead; Upgrades the its dependence sdk
aliyun/terraform-provider-alicloud pull request #3443
Opened 2021-04-14 09:10 UTC by lixue323

2021-04-15 03:21 UTC, zql-tqy requested changes

2021-04-15 03:21 UTC, zql-tqy commented on alicloud/service_alicloud_ecs.go
> +		return object, WrapErrorf(Error(GetNotFoundMessage("ECS", id)), NotFoundWithResponse, response)
这块自动化的应该有点问题，应该跟上面一样抛出 GetNotFoundMessage("EcsDisk", id) 调整下吧
下面的也是

2021-04-15 03:21 UTC, zql-tqy commented on website/docs/d/ecs_disks.html.markdown
> +	* `` - The name.
这个检查下

2021-04-15 03:21 UTC, zql-tqy commented on website/docs/r/disk.html.markdown
> +-> **DEPRECATED:** This resource has been renamed to [alicloud_ecs_key_pair](https://www.terraform.io/docs/providers/alicloud/r/ecs_key_pair.html) from version 1.122.0.
这个替代资源放错了吧

2021-04-15 03:21 UTC, zql-tqy commented on website/docs/r/ecs_disk.html.markdown
> +* `payment_type` - (Optional) Payment method for disk. Valid values: `PostPaid`, `PrePaid`.
这里的枚举值记得修改

2021-04-15 03:21 UTC, zql-tqy commented on website/docs/r/ecs_disk.html.markdown
> +* `disk_name` - (Optional, Computed) Name of the ECS disk. This name can have a string of 2 to 128 characters, must contain only alphanumeric characters or hyphens, such as "-",".","_", and must not
such as "-", ".", "_", and must not begin or end with a hyphen, and must not begin with \`http://\` or \`https://\`. Default value is \`null\`.

2021-04-15 04:38 UTC, lixue323 commented on alicloud/resource_alicloud_ecs_disk.go
> +				Default:  true,
这个参数，产品说api支持了，但是还没对外开放

2021-04-16 06:58 UTC, liuri1205 requested changes

2021-04-16 06:58 UTC, liuri1205 commented on alicloud/data_source_alicloud_ecs_disks.go
> +	request["MaxResults"] = PageSizeLarge
这个接口同时支持 Page 和 MaxResults 查询, 如果使用了 Page 分页, MaxResults 参数需要过滤掉

2021-04-16 06:58 UTC, liuri1205 commented on alicloud/data_source_alicloud_ecs_disks.go
> +		if nextToken, ok := response["NextToken"].(string); ok && nextToken != "" {
这里也是NextToken 不需要

2021-04-16 06:58 UTC, liuri1205 commented on alicloud/resource_alicloud_ecs_disk_attachment.go
> +	err = resource.Retry(d.Timeout(schema.TimeoutCreate), func() *resource.RetryError {
`d.Timeout(schema.TimeoutCreate)` 这个需要在 schema 中定义, update 中也是一样

2021-04-16 06:58 UTC, liuri1205 commented on website/docs/d/ecs_disks.html.markdown
> +* `payment_type` - (Optional, ForceNew) Payment method for disk.
`payment_type` 枚举值

2021-04-16 06:58 UTC, liuri1205 commented on website/docs/r/ecs_disk_attachment.html.markdown
> +```
terraform

2021-04-25 02:20 UTC, xiaozhu36 requested changes

2021-04-25 02:20 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk_test.go
> +				ImportStateVerifyIgnore: []string{"advanced_features", "auto_pay", "dedicated_block_storage_cluster_id", "dry_run", "encrypt_algorithm", "storage_set_id", "storage_set_partition_number"},
Please check all of ImportStateVerifyIgnore and I think there are some attribute should not be here.

2021-04-25 02:20 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk_attachment_test.go
> +func testAccCheckDiskAttachmentDestroy(s *terraform.State) error {
Is this method also used? I think using new test structure can instead.

2021-04-25 02:20 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk_attachment.go
> +				Optional: true,
I think the bootable and delete_with_instance should have default value.

2021-04-25 02:20 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk_attachment.go
> +	}
I think the block 83-85 can be removed because of it has been useless.

2021-04-25 02:20 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk_attachment.go
> +		disk["Device"] = "/dev/" + disk["Device"].(string)[len("/dev/x"):]
I think there is no need to do more joint jobs.

2021-04-26 02:25 UTC, lixue323 commented on alicloud/resource_alicloud_ecs_disk_test.go
> +				ImportStateVerifyIgnore: []string{"advanced_features", "auto_pay", "dedicated_block_storage_cluster_id", "dry_run", "encrypt_algorithm", "storage_set_id", "storage_set_partition_number"},
这些都是read方法中不返回的，已确认

2021-04-27 02:57 UTC, xiaozhu36 requested changes

2021-04-27 02:57 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecs_disks.go
> +		request["ZoneId"] = v
deprecated availability_zone  and using zone_id instead

2021-04-27 02:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk.go
> +			"availability_zone": {
deprecated the. availability_zone and using zone_id instead.

2021-04-27 02:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk.go
> +		request["Type"] = "online"
expose the `type` to an attaibute.

2021-04-27 07:48 UTC, xiaozhu36 requested changes

2021-04-27 07:48 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecs_disks.go
> +		request["DiskType"] = v
Please check line 399-401.

2021-04-27 07:48 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecs_disks.go
> +	}
If zone_id is specified, availability_zone should be ingored.

2021-04-27 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk.go
> +				ValidateFunc: validation.StringInSlice([]string{"cloud", "cloud_efficiency", "cloud_essd", "cloud_ssd"}, false),
The enum values are not equal to its datasource

2021-04-27 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk.go
> +				Default:  "offline",
Does the type have enum values?

2021-04-27 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk_attachment_test.go
> +	availability_zone = "${data.alicloud_zones.disk.zones.0.id}"
It should be zone_id

2021-04-27 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk_test.go
> +			action = "DeleteDisk"
The line 76 should be action := "DeleteDisk"

2021-04-27 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk_test.go
> +					"availability_zone": "${data.alicloud_zones.default.zones.0.id}",
zone_id

2021-04-27 07:48 UTC, xiaozhu36 commented on website/docs/d/ecs_disks.html.markdown
> +* `availability_zone` - (Optional, ForceNew) ID of the free zone to which the disk belongs.
Please keep sync the attribute with the schema.

2021-04-27 07:48 UTC, xiaozhu36 commented on website/docs/d/ecs_disks.html.markdown
> +	* `auto_snapshot_policy_id` - Query cloud disks based on the automatic snapshot policy ID.
There should not have indent.

2021-04-27 07:48 UTC, xiaozhu36 commented on website/docs/r/ecs_disk.html.markdown
> +  availability_zone = "cn-beijing-b"
Please use the latest attribute name.

2021-04-27 09:51 UTC, lixue323 commented on alicloud/data_source_alicloud_ecs_disks.go
> +		request["DiskType"] = v
新参数diskType, 老参数Type, 做兼容

2021-04-27 09:52 UTC, lixue323 commented on alicloud/resource_alicloud_ecs_disk_test.go
> +			action = "DeleteDisk"
前边已经定义了action，查询接口调用之后，去做删除

2021-04-28 02:25 UTC, xiaozhu36 commented on alicloud/service_alicloud_ecs.go
> +			return object, WrapErrorf(Error(GetNotFoundMessage("ECS:Disk", id)), NotFoundMsg, ProviderERROR, fmt.Sprint(response["RequestId"]))
Why so many error codes?

2021-04-28 02:33 UTC, xiaozhu36 requested changes

2021-04-28 02:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk_test.go
> +				time.Sleep(5 * time.Second)
remove to outside of `for` block.

2021-04-28 02:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk_attachment.go
> +	oldDisk, err := ecsService.DescribeEcsDisk(d.Get("disk_id").(string))
Why there is a describe action?

2021-04-28 02:33 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecs_disks.go
> +			"disk_type": {
I found a default value `all` in the docs.

2021-04-28 02:33 UTC, xiaozhu36 commented on website/docs/r/ecs_disk.html.markdown
> +$ terraform import alicloud_ecs_disk.example <id>
using a fake resource id, not <id>

2021-04-28 06:55 UTC, lixue323 commented on alicloud/resource_alicloud_ecs_disk_attachment.go
> +	oldDisk, err := ecsService.DescribeEcsDisk(d.Get("disk_id").(string))
兼容之前代码，绑定前后，属性可能会改变，如果对比之后改变了，之后会调用更新方法改回来

2021-04-29 12:43 UTC, merged