Resource/alicloud_slb: Update SDK. Deprecated old resource name and a…
aliyun/terraform-provider-alicloud pull request #3499
Opened 2021-04-27 07:08 UTC by liuri1205

…ttributes.

2021-04-29 04:41 UTC, lixue323 commented on alicloud/data_source_alicloud_slb_load_balancers_test.go
> +	alicloudSlbLoadBalancersCheckInfo.dataSourceTestCheck(t, rand, idsConf, tagsConf, nameRegexConf, statusConf, allConf)
老代码中的测试参数，在新的当中也支持一下吧

2021-04-29 04:41 UTC, lixue323 commented on website/docs/r/slb_load_balancer.html.markdown
>  subcategory: "Server Load Balancer (SLB)"
老文档应该是要保留，标记弃用,
-> **DEPRECATED:** This resource has been renamed to [alicloud_slb_load_balancer](https://www.terraform.io/docs/providers/alicloud/r/slb_load_balancer.html) from version 1.122.0.

2021-04-30 07:48 UTC, xiaozhu36 requested changes

2021-04-30 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_slb_load_balancer.go
> +					if d.Get("payment_type").(string) == "Subscription" {
This also need to checking instance_charge_type. And you can refer to https://github.com/aliyun/terraform-provider-alicloud/blob/master/alicloud/diff_suppress_funcs.go#L375

2021-04-30 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_slb_load_balancer.go
> +	if v, ok := d.GetOk("specification"); ok {
Please using load_balancer_spec

2021-04-30 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_slb_load_balancer.go
> +				ValidateFunc: validation.StringInSlice([]string{"PayByBandwidth", "PayByTraffic"}, false),
Please using `validation.StringInSlice([]string{"PayByBandwidth", "PayByTraffic"}, true)` attempt to correct the previous values. It aims to keep sync the value with OpenAPI parameter values.

2021-04-30 07:54 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_slb_load_balancers.go
> +				Removed:  "Field 'master_availability_zone' has removed from v1.122.0 and replace by 'master_zone_id'.",
Please update the next version to 1.123.0

2021-05-14 13:41 UTC, merged