Resource/alicloud_slb_ca_certificate: Upgrade SDK. Deprecated 'name' and replace by 'ca_certificate_name'.
aliyun/terraform-provider-alicloud pull request #3509
Opened 2021-04-29 07:26 UTC by liuri1205

…and replace by 'ca_certificate'.

2021-04-30 07:54 UTC, xiaozhu36 requested changes

2021-04-30 07:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_slb_ca_certificate.go
> +			if NeedRetry(err) {
Please checking the `SlbIsBusy` errors

2021-04-30 10:44 UTC, liuri1205 commented on website/docs/d/slb_ca_certificates.html.markdown
> +  * `created_time` - (Removed from v1.122.0) CA certificate created time.
created_time 和 regionId 不兼容了, 直接 removed

2021-05-12 22:37 UTC, xiaozhu36 requested changes

2021-05-12 22:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_slb_ca_certificate_test.go
> +		return WrapErrorf(err, "List CA certificate failed!")
Why add the `"List CA certificate failed!"`?

2021-05-19 22:05 UTC, merged