resource/alicloud_ecs_network_interface: Renames alicloud_network_interface to alicloud_ecs_network_interface; Deprecates the name and use network_interface_name instead; Upgrades the its dependence sdk
aliyun/terraform-provider-alicloud pull request #3532
Opened 2021-05-13 08:59 UTC by lixue323

2021-05-13 10:37 UTC, liuri1205 requested changes

2021-05-13 10:37 UTC, liuri1205 commented on website/docs/r/ecs_network_interface.html.markdown
> +* `private_ips` - (Optional, Computed, Deprecated in v1.123.0+) Field `name` has been deprecated from provider version 1.123.0. New field `private_ip_address` instead
`private_ips` , `private_ips_count ` 描述有误, 前面都是 `name` , 检查一下

2021-05-13 10:37 UTC, liuri1205 commented on alicloud/resource_alicloud_ecs_network_interface.go
> +				Deprecated:    "Field 'name' has been deprecated from provider version 1.123.0. New field 'private_ip_address' instead",
`private_ips` 弃用信息描述错误

2021-05-13 10:37 UTC, liuri1205 commented on alicloud/resource_alicloud_ecs_network_interface.go
> +				Deprecated:    "Field 'name' has been deprecated from provider version 1.123.0. New field 'secondary_private_ip_address_count' instead",
`private_ips` 弃用信息错误

2021-05-13 10:37 UTC, liuri1205 commented on alicloud/resource_alicloud_ecs_network_interface_attachment_test.go
> +				),
没有 `import` 测试

2021-05-13 10:37 UTC, liuri1205 commented on alicloud/resource_alicloud_network_interface_attachment.go
> -			if IsExpectedErrors(err, NetworkInterfaceInvalidOperations) {
之前的重试错误码需要加上 `NetworkInterfaceInvalidOperations`

2021-05-13 10:37 UTC, liuri1205 commented on alicloud/resource_alicloud_network_interface_attachment.go
> -			if IsExpectedErrors(err, NetworkInterfaceInvalidOperations) {
删除重试错误码

2021-05-14 05:45 UTC, xiaozhu36 requested changes

2021-05-14 05:45 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_network_interface.go
> +				Type:     schema.TypeSet,
1. Why not private_ip_addresses
2. Why not TypeList

2021-05-14 05:45 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_network_interface.go
> +				Deprecated:    "Field 'private_ip' has been deprecated from provider version 1.123.0. New field 'primary_ip_address' instead",
Please modify the version to 1.124.0

2021-05-14 05:45 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_network_interface_attachment.go
> +				ForceNew: true,
I think the `wait_for_network_configuration_ready` should not be ForceNew

2021-05-14 09:48 UTC, lixue323 commented on alicloud/resource_alicloud_ecs_network_interface.go
> +				Type:     schema.TypeSet,
名字已经改成private_ip_addresses，使用TypeSet, 是因为返回顺序与入参不一致

2021-05-17 08:38 UTC, merged