A new resource for Container Registry Enterprise Instance.
aliyun/terraform-provider-alicloud pull request #3560
Opened 2021-05-20 11:32 UTC by cwupup

2021-05-20 11:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3560) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3560) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3560) it.</sub>

2021-05-21 09:57 UTC, lixue323 commented on alicloud/resource_alicloud_cr_ee_instance.go
> +		if NotFoundError(err) {
log.Printf("[DEBUG] Resource alicloud_ecs_disk ecsService.DescribeEcsDisk Failed!!! %s", err)
参照这个，加log信息

2021-05-21 09:57 UTC, lixue323 commented on website/docs/r/cr_ee_instance.html.markdown
> +For information about Container Registry Enterprise Edition instances and how to use it, see [Create a Instance](https://www.alibabacloud.com/help/doc-detail/208144.htm)
英文文档链接

2021-05-21 09:57 UTC, lixue323 commented on website/docs/r/cr_ee_instance.html.markdown
> +* `payment_type` - (Optional, String) Subscription of Container Registry Enterprise Edition instance. Valid values: ["Subscription"].
Valid values: `Subscription`
使用反引号

2021-05-21 10:52 UTC, liuri1205 requested changes

2021-05-21 10:52 UTC, liuri1205 commented on alicloud/resource_alicloud_cr_ee_instance.go
> +			"instance_status": {
`instance_status` , 资源状态对外统一使用 `status`

2021-05-21 10:52 UTC, liuri1205 commented on alicloud/resource_alicloud_cr_ee_instance_test.go
> +}
测试需要怎加 import 测试

2021-05-21 10:52 UTC, liuri1205 commented on alicloud/resource_alicloud_cr_ee_instance_test.go
> +	enable := os.Getenv("ALICLOUD_CR_INSTANCE_TEST_ENABLE")
对于这种只能创建预付费的实例, 这个不要, 直接在 TestAccAlicloudCrEEInstance_Basic 函数前加 Skip 来跳过测试

2021-05-21 10:52 UTC, liuri1205 commented on alicloud/resource_alicloud_cr_ee_instance.go
> +			"period": {
`period ` 支持的枚举值需要加上

2021-05-21 10:52 UTC, liuri1205 commented on alicloud/resource_alicloud_cr_ee_instance.go
> +	for NotFoundError(err) && retryCnt < 5 {
重试使用 resource.Retry 函数在 `DescribeCrEEInstance` 方法中调用接口是实现

2021-05-21 10:52 UTC, liuri1205 commented on alicloud/resource_alicloud_cr_ee_instance.go
> +			"payment_type": {
`payment_type` 属性查询没有返回

2021-05-21 10:56 UTC, liuri1205 requested changes

2021-05-21 10:56 UTC, liuri1205 commented on alicloud/resource_alicloud_cr_ee_instance_test.go
> +					"instance_type":  "Basic",
`instance_type` 和 `instance_name` 作为属性, 需要检查返回值是否和设置的一致

2021-05-21 10:56 UTC, liuri1205 commented on website/docs/r/cr_ee_instance.html.markdown
> +Container Registry Enterprise Edition instance can be imported using the `instance_id`, e.g.
`instance_id` 和 `id` 相同的话, 这里描述使用 `id`

2021-05-21 11:01 UTC, liuri1205 requested changes

2021-05-21 12:13 UTC, cwupup commented on alicloud/resource_alicloud_cr_ee_instance.go
> +			"instance_status": {
还是用instance_status，和openapi保持一致

2021-05-21 12:14 UTC, cwupup commented on alicloud/resource_alicloud_cr_ee_instance.go
> +			"period": {
没有枚举

2021-05-21 12:15 UTC, cwupup commented on alicloud/provider.go
> +			"alicloud_cr_ee_instance":                             resourceAlicloudCrEEInstance(),
以前有资源已经是缩写了，保持一致

2021-05-24 08:50 UTC, liuri1205 commented on alicloud/resource_alicloud_cr_ee_instance.go
> +			"instance_status": {
这个是描述资源状态的, Terraform 接入规范统一使用 `status`, 不用和API 保持一致

2021-05-24 08:54 UTC, liuri1205 requested changes

2021-05-24 08:54 UTC, liuri1205 commented on alicloud/resource_alicloud_cr_ee_instance_test.go
> +					"instance_type":  "Basic",
`instance_type ` 没有check

2021-05-24 08:55 UTC, liuri1205 requested changes

2021-05-24 08:55 UTC, liuri1205 commented on alicloud/resource_alicloud_cr_ee_instance.go
> +		d.Set("payment_type", "Subscription")
`payment_type` 不能写死, 查询接口需要支持返回

2021-05-25 08:13 UTC, xiaozhu36 requested changes

2021-05-25 08:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_ee_instance.go
> +	request.RegionId = "cn-hangzhou"
The Scheme and RegionId should not be hard-code and please use `client.Protocol` and `client.RegionId` instead.

2021-05-25 08:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_ee_instance.go
> +				Type:     schema.TypeInt,
I think the create_time type should be `TypeString`

2021-05-25 08:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_ee_instance.go
> +			Value: "false",
The `custom_oss_bucket ` type is string in the Schema, not bool. Please keep it sync.

2021-05-25 08:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_ee_instance.go
> +	err := resource.Retry(30*time.Second, func() *resource.RetryError {
The retry strategy should be added in the DescribeCrEEInstance not here.

2021-05-25 08:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_ee_instance_test.go
> +				ImportStateVerifyIgnore: []string{"period", "renew_period", "renewal_status", "instance_type", "custom_oss_bucket"},
If the parameter is Required, it should not be ignored. Otherwise, it can not be imported successfully.

2021-05-25 08:13 UTC, xiaozhu36 commented on website/docs/r/cr_ee_instance.html.markdown
> +* `payment_type` - Payment type of Container Registry Enterprise Edition instance.
If the attribute has been defined in the `Argument Reference`, there is no need to define again.

2021-05-25 12:39 UTC, cwupup commented on alicloud/resource_alicloud_cr_ee_instance.go
> +	request.RegionId = "cn-hangzhou"
bssopenapi非region化，需要指定

2021-05-27 03:22 UTC, xiaozhu36 requested changes

2021-05-27 03:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_ee_instance.go
> +	request.RegionId = "cn-hangzhou"
如果使用的是bssopenapi，那么这个地方的RegionId 不需要制定，而是在parameters 中指定就行

2021-05-27 03:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_ee_instance.go
> +	request.RegionId = "cn-hangzhou"
这个也一样

2021-05-27 03:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_ee_instance_test.go
> +				ImportStateVerifyIgnore: []string{"period", "custom_oss_bucket"},
没有返回的参数不能设置为 ForceNew。

2021-05-27 03:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_ee_instance_test.go
> +			testAccPreCheck(t)
如果这个只支持特定的几个region，那么这个地方需要增加一个所支持region的PreCheck

2021-05-27 03:22 UTC, xiaozhu36 commented on website/docs/r/cr_ee_instance.html.markdown
> +* `instance_id` - ID of Container Registry Enterprise Edition instance.
instance_id 在Schema中没有定义，如果不需要，直接去掉。

2021-05-27 10:01 UTC, merged