resource/alicloud_config_rule: Upgrade resource and datasource.
aliyun/terraform-provider-alicloud pull request #3596
Opened 2021-05-31 04:15 UTC by liuri1205

2021-06-01 11:26 UTC, xiaozhu36 requested changes

2021-06-01 11:26 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule_test.go
> +	var v map[string]interface{}
这个不需要skip吧

2021-06-02 02:05 UTC, liuri1205 commented on alicloud/data_source_alicloud_config_rules.go
> +			"status": {
这个 config_rule_state 标识资源状态, 目前我们统一用的是 status, 之前只是当成一般的属性处理

2021-06-02 02:06 UTC, liuri1205 commented on alicloud/resource_alicloud_config_rule_test.go
> +	var v map[string]interface{}
这个也是需要自定义的 FC 规则函数才能测试

2021-06-02 02:08 UTC, liuri1205 commented on alicloud/resource_alicloud_config_rule.go
> +				Optional: true,
这个属性新接口支持的, 统一都是 string 的

2021-06-02 02:25 UTC, liuri1205 commented on alicloud/data_source_alicloud_config_rules.go
> -						"source_maximum_execution_frequency": {
这个是兼容的属性, 没有去掉, 顺序变了, 上面还有的

2021-06-02 02:38 UTC, liuri1205 commented on alicloud/data_source_alicloud_config_rules.go
> +							Type:     schema.TypeString,
测试 datasource 中的出参, int 升级成 string 对s tate 和模板中的引用不会报错.

2021-06-02 02:38 UTC, liuri1205 commented on alicloud/resource_alicloud_config_rule.go
> +				Removed:  "Field 'scope_compliance_resource_id' has been removed from provider version 1.125.0.",
已修改

2021-06-04 09:24 UTC, merged