support acrRegistryInfos / eip
aliyun/terraform-provider-alicloud pull request #3606
Opened 2021-06-03 13:02 UTC by silent-beaters

2021-06-03 13:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3606) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3606) before we can accept your contribution.<br/><hr/>**wb-hxh549296** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3606) it.</sub>

2021-06-04 13:43 UTC, xiaozhu36 commented
HI @silent-beaters Thanks for your PR. Can you add test cases and docs for it?

2021-06-15 01:55 UTC, liuri1205 requested changes

2021-06-15 01:55 UTC, liuri1205 commented on alicloud/resource_alicloud_eci_container_group.go
> +				Type:     schema.TypeList,
`acr_registry_infos` 的子元素是 Object 类型, 这里使用 TypeSet

2021-06-18 03:29 UTC, closed without merging