Feature/ess scalingconf performance level
aliyun/terraform-provider-alicloud pull request #3632
Opened 2021-06-15 11:59 UTC by TalentNing

helloworld

2021-06-15 11:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3632) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3632) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3632) it.</sub>

2021-06-16 02:11 UTC, liuri1205 requested changes

2021-06-16 02:11 UTC, liuri1205 commented on alicloud/data_source_alicloud_ess_scalingconfigurations.go
> +						"system_disk_performance_level": {
新增属性需要在文档中补充描述

2021-06-17 09:26 UTC, TalentNing commented on alicloud/data_source_alicloud_ess_scalingconfigurations.go
> +						"system_disk_performance_level": {
done

2021-06-18 09:06 UTC, merged