DDOS supports international accounts to purchase domestic instances
aliyun/terraform-provider-alicloud pull request #3679
Opened 2021-06-30 06:45 UTC by daniuliduo

Update DDOS supports international accounts to purchase domestic instances

2021-06-30 06:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3679) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3679) before we can accept your contribution.<br/><hr/>**liduo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3679) it.</sub>

2021-06-30 07:25 UTC, liuri1205 requested changes

2021-06-30 07:25 UTC, liuri1205 commented on alicloud/resource_alicloud_ddoscoo_instance.go
> +				Required: false,
1. 有了 `Optional: true` , `Required: false` 可以删掉
2. 新增参数需要在资源文档中描述说明

2021-06-30 07:25 UTC, liuri1205 commented on alicloud/resource_alicloud_ddoscoo_instance.go
> +	client.RegionId = "cn-hangzhou"
这个 `client.RegionId = "cn-hangzhou"` 为啥写死了?

2021-06-30 07:25 UTC, liuri1205 commented on alicloud/resource_alicloud_ddoscoo_instance_test.go
> +			//testAccPreCheckWithTime(t, []int{23})
这个为啥注释了

2021-06-30 07:25 UTC, liuri1205 commented on alicloud/service_alicloud_ddoscoo.go
> +		fmt.Println(object)
调试代码可以去掉

2021-06-30 07:25 UTC, liuri1205 commented on alicloud/service_alicloud_ddoscoo.go
> +		return object, string(Available), nil
这个应该返回 object 中的状态, 而不是直接返回可用

2021-06-30 07:25 UTC, liuri1205 commented on alicloud/resource_alicloud_ddoscoo_instance.go
> +		addDebug(action, response, request)
addDebug 信息放到重试外面

2021-06-30 07:25 UTC, liuri1205 commented on alicloud/resource_alicloud_ddoscoo_instance.go
> +	client.RegionId = "cn-hangzhou"
这个不应该写死, regionId 用户可以指定的

2021-07-01 03:30 UTC, liuri1205 requested changes

2021-07-01 03:30 UTC, liuri1205 commented on alicloud/service_alicloud_ddoscoo.go
> +	request.RegionId = "cn-hangzhou"
这个 	request.RegionId = "cn-hangzhou" 为啥要写死?

2021-07-01 03:30 UTC, liuri1205 commented on website/docs/r/ddoscoo_instance.html.markdown
> +* `product_type` - (Required) Product Type International Account Purchase Domestic Instance Value is ddosco_intl Domestic Account Purchase Domestic Instance Value is ddoscoo. Increase 5 per step, suc
1. `product_type` 是可选入参, 说明默认值, 不能在文档中写成 Required
2. 标明 product_type 支持的版本
3. ddosco_intl, ddoscoo 有效值使用反引号包裹.

2021-07-01 12:04 UTC, xiaozhu36 requested changes

2021-07-01 12:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ddoscoo_instance.go
> +	}
如果product type 跟region有关，那么在创建的时候也需要判断

2021-07-01 12:04 UTC, xiaozhu36 commented on alicloud/service_alicloud_ddoscoo.go
> +		request.RegionId = "ap-southeast-1"
这个地方怎么又是 ap-southeast-1 了

2021-07-02 16:49 UTC, merged