NewResource `alicloud_eip_address`     NewDataSource `alicloud_eip_addresses`
aliyun/terraform-provider-alicloud pull request #3682
Opened 2021-07-01 09:47 UTC by liuri1205

2021-07-06 02:23 UTC, xiaozhu36 requested changes

2021-07-06 02:23 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_eip_addresses.go
> +				Deprecated: "Field 'ip_addresses' has been deprecated from provider version 1.126.0 and it will be remove in the future version. Please use the new attribute 'eip_address' instead.",
这个为啥要弃用啊

2021-07-06 02:23 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_eip_addresses.go
> +				ForceNew: true,
这个在resource中是address_name

2021-07-06 03:44 UTC, liuri1205 commented on alicloud/resource_alicloud_eip_address.go
> +				Default:       PostPaid,
可以不要, 已修改

2021-07-06 03:45 UTC, liuri1205 commented on alicloud/data_source_alicloud_eip_addresses.go
> +				Deprecated: "Field 'ip_addresses' has been deprecated from provider version 1.126.0 and it will be remove in the future version. Please use the new attribute 'eip_address' instead.",
list 接口本身支持了 ip_address  条件查询, 这个自动化代码需要特殊适配, 准备后面版本弃用.

2021-07-06 03:46 UTC, liuri1205 commented on alicloud/data_source_alicloud_eip_addresses.go
> +				ForceNew: true,
list 接口补充映射, 已修改

2021-07-06 07:20 UTC, liuri1205 commented on alicloud/resource_alicloud_eip_address.go
> +				Type:     schema.TypeString,
网络类型, Create 接口的OtherParameter, 已添加枚举值

2021-07-07 05:31 UTC, xiaozhu36 requested changes

2021-07-07 05:31 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_eci_image_caches_test.go
>    vswitch_id        = data.alicloud_vpcs.default.vpcs.0.vswitch_ids.0
这个地方测试case有问题，name 不是以tf-testcase开头的

2021-07-07 05:31 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_eip_addresses.go
> +				Deprecated: "Field 'ip_addresses' has been deprecated from provider version 1.126.0 and it will be remove in the future version. Please use the new attribute 'eip_address' instead.",
这个弃用的信息不对吧，eip_address?

2021-07-07 05:31 UTC, xiaozhu36 commented on website/docs/d/eips.html.markdown
> +-> **DEPRECATED:**  This datasource has been deprecated from version `1.125.0`. Please use new datasource [alicloud_eip_addresses](https://www.terraform.io/docs/providers/alicloud/d/eip_addresses.htm
1.126.0

2021-07-07 05:31 UTC, xiaozhu36 commented on website/docs/r/eip.html.markdown
> +-> **DEPRECATED:**  This resource  has been deprecated from version `1.125.0`. Please use new resource [alicloud_eip_address](https://www.terraform.io/docs/providers/alicloud/r/eip_address.html).
1.126.0

2021-07-07 09:40 UTC, merged