Add new resource alicloud_gpdb_elastic_instance and no longer supports to create new alicloud_gpdb_instance resource
aliyun/terraform-provider-alicloud pull request #3727
Opened 2021-07-14 11:46 UTC by jokerhenson

2021-07-15 06:36 UTC, liuri1205 requested changes

2021-07-15 06:36 UTC, liuri1205 commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +				ValidateFunc: validation.StringInSlice([]string{"Postpaid", "Prepaid"}, false),
`payment_type` 属性参考 `alicloud_tsdb_instance` 资源的方式处理下

2021-07-15 06:36 UTC, liuri1205 commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +	d.Set("instance_spec", convertDBInstanceClassToInstanceSpec(instance["DBInstanceClass"].(string)))
`instance_spec` 属性查询接口要支持返回, 不能通过 `DBInstanceClass` 去特殊处理获取

2021-07-15 06:36 UTC, liuri1205 commented on website/docs/r/gpdb_instance.html.markdown
> +-> **NOTE:**  This resource is used to manage a Reserved Storage Mode instance, and creating new reserved storage mode instance is no longer supported.
标明从哪个版本开始不再支持

2021-07-15 06:36 UTC, liuri1205 commented on website/docs/r/gpdb_elastic_instance.html.markdown
> +* `engine` (Required) Database engine: `gpdb`.
ForceNew 的属性也需要标识

2021-07-15 06:36 UTC, liuri1205 commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +		response, err := conn.DoRequest(StringPointer(action), nil, StringPointer("POST"), StringPointer("2016-05-03"), StringPointer("AK"), nil, request, &util.RuntimeOptions{})
使用 common 调用的接口, 对 err 都需要用 NeedRetry 函数判断进行重试

2021-07-15 08:09 UTC, jokerhenson commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +	d.Set("instance_spec", convertDBInstanceClassToInstanceSpec(instance["DBInstanceClass"].(string)))
先这么搞，下周api修改发布之后再把特殊处理去掉。

2021-07-15 08:10 UTC, jokerhenson commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +	d.Set("instance_spec", convertDBInstanceClassToInstanceSpec(instance["DBInstanceClass"].(string)))
> `instance_spec` 属性查询接口要支持返回, 不能通过 `DBInstanceClass` 去特殊处理获取

先这么搞，下周api修改发布之后再把特殊处理去掉。

2021-07-15 08:33 UTC, liuri1205 requested changes

2021-07-15 08:33 UTC, liuri1205 commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +	if err != nil {
NeedRetry 重试

2021-07-15 08:33 UTC, liuri1205 commented on alicloud/service_alicloud_gpdb.go
> +	response, err = conn.DoRequest(StringPointer(action), nil, StringPointer("POST"), StringPointer("2016-05-03"), StringPointer("AK"), nil, request, &runtime)
NeedRetry 重试

2021-07-15 08:33 UTC, liuri1205 commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +	util "github.com/alibabacloud-go/tea-utils/service"
运行 make fmt 格式化下代码

2021-07-15 10:38 UTC, liuri1205 requested changes

2021-07-15 10:38 UTC, liuri1205 commented on alicloud/resource_alicloud_gpdb_elastic_instance_test.go
> +						"description": fmt.Sprintf("tf-testAccGpdbInstance_6.0"),
查询接口返回的属性都需要 Check 一下

2021-07-16 02:30 UTC, xiaozhu36 requested changes

2021-07-16 02:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +				ForceNew: true,
Does the seg_node_num has validate values or some limitations?

2021-07-16 02:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +			"period": {
Please use the specific resource attribute `payment_duration_unit` instead `period`

2021-07-16 02:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +				ValidateFunc: validation.StringInSlice([]string{"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"}, false),
Please use the specific resource attribute `payment_duration` instead `used_time`

2021-07-16 02:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +				ForceNew: true,
Does the `storage_size` has validate values or some limitations?

2021-07-16 02:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +				Type:     schema.TypeSet,
I think the `security_ip_list` type should be `schema.TypeList`.

2021-07-16 02:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +	if d.HasChange("description") {
The description has been set in the Create API and there should check the ` d.IsNewResource() `

2021-07-16 02:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_elastic_instance.go
> +	}
The block 272-275 is needless and it should be removed.

2021-07-16 02:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_elastic_instance_test.go
> +				),
There missing the updating all attributes testcase.

2021-07-16 02:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_instance.go
> +	return Error("Sorry, creating new reserved storage mode instance is no longer supported since v1.127.0, you can use alicloud_gpdb_elastic_instance to create a flexible storage mode instance instead.
If the OpenAPI does not offline, there can not offline this resource. You can add the statement in its docs by a NOTE

2021-07-16 02:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_instance_test.go
> +func _TestAccAlicloudGpdbInstance_classic(t *testing.T) {
If you want to skip the testcase, you can add a prefix Skip in the testcase name.

2021-07-16 15:07 UTC, merged