add a new resource alicloud_hbr_vault and its datasource
aliyun/terraform-provider-alicloud pull request #3770
Opened 2021-07-26 08:47 UTC by ChenHanZhang

2021-07-26 08:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3770) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3770) before we can accept your contribution.<br/><hr/>**chenhanzhang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3770) it.</sub>

2021-07-26 09:08 UTC, liuri1205 requested changes

2021-07-26 09:08 UTC, liuri1205 commented on alicloud/data_source_alicloud_hbr_vaults_test.go
> +			"status": 				`"ERROR"`,
格式化代码

2021-07-26 09:08 UTC, liuri1205 commented on website/alicloud.erb
> +                  <a href="#">HBR</a>
这个使用全称加简称 `Hybrid Backup Recovery (HBR)`

2021-07-26 09:08 UTC, liuri1205 commented on website/docs/d/hbr_vaults.html.markdown
> +subcategory: "HBR"
这里也是

2021-07-26 09:08 UTC, liuri1205 commented on website/docs/r/hbr_vault.html.markdown
> +For information about HBR Vault and how to use it, see [What is Vault](https://help.aliyun.com/).
这里需要使用产品描述英文链接

2021-07-26 09:08 UTC, liuri1205 commented on website/docs/r/hbr_vault.html.markdown
> +subcategory: "HBR"
这里也是

2021-07-26 09:08 UTC, liuri1205 commented on website/docs/d/hbr_vaults.html.markdown
> +* `status` - (Optional, ForceNew, Computed) Status.
`vault_type `, `status` 描述详细点, 加上枚举值

2021-07-26 09:08 UTC, liuri1205 commented on website/docs/d/hbr_vaults.html.markdown
> +  name_regex = "^my-Vault"
这2个过滤条件可以放到一个 DataSource 中

2021-07-26 09:08 UTC, liuri1205 commented on alicloud/resource_alicloud_hbr_vault_test.go
> +					"vault_name":          "接入测试",
`vault_name` 使用 `name` 变量的值

2021-07-29 06:04 UTC, xiaozhu36 approved these changes

2021-07-29 06:04 UTC, merged