Fix `alicloud_cdn_domain_config` a bug that need to be deleted when updating
aliyun/terraform-provider-alicloud pull request #3835
Opened 2021-08-13 06:17 UTC by xinmu0426

Fix `alicloud_cdn_domain_config` a bug that need to be deleted when updating

2021-08-13 06:22 UTC, xiaozhu36 requested changes

2021-08-13 06:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cdn_domain_config.go
> +			},
config_id and status should be computed.

2021-08-13 06:22 UTC, xiaozhu36 commented on alicloud/service_alicloud_cdn.go
> +	}
Please update the docs

2021-08-18 12:20 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cdn_domain_config.go
> +		if err != nil {
放置debug后,json解析前

2021-08-18 12:20 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cdn_domain_config.go
> +	args := val["FunctionArgs"].(map[string]interface{})["FunctionArg"].([]interface{})
连续强转最好处理一下

2021-08-18 12:20 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cdn_domain_config_test.go
> +			testAccPreCheck(t)
有没有CI跑不了的Region?

2021-08-19 03:16 UTC, xinmu0426 commented on alicloud/resource_alicloud_cdn_domain_config_test.go
> +			testAccPreCheck(t)
都可以跑的

2021-08-19 03:17 UTC, xinmu0426 commented on alicloud/resource_alicloud_cdn_domain_config.go
> +	if len(v.([]interface{})) != 1 {
每次只能配置一条config，创建后大于或者等于1都不可以

2021-08-19 06:18 UTC, merged