New Resource CSG-Gateway and its DataSource
aliyun/terraform-provider-alicloud pull request #3843
Opened 2021-08-14 04:30 UTC by Wanghx0991

2021-08-18 12:48 UTC, xinmu0426 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
> +		action := "ModifyGateway"
这个接口是name和description一起要传么

2021-08-18 12:48 UTC, xinmu0426 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
> +		}
去掉这个err != nil

2021-08-18 12:48 UTC, xinmu0426 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
> +	wait := incrementalWait(3*time.Second, 3*time.Second)
位置挪一下

2021-08-18 12:48 UTC, xinmu0426 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway_test.go
> +				Check: resource.ComposeTestCheckFunc(
description的描述最好能和name相关，如果发生变更要一chanage结尾

2021-08-18 12:48 UTC, xinmu0426 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway_test.go
> +				}),
description更新为回去

2021-08-18 12:48 UTC, xinmu0426 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
> +				if state, vvv := task.(map[string]interface{})["StateCode"]; vvv {
vvvv

2021-08-18 12:48 UTC, xinmu0426 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway_test.go
> +					"gateway_name":      fmt.Sprintf("tf-acctestGatewayName%d", rand),
name

2021-08-18 12:48 UTC, xinmu0426 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway_test.go
> +	default = "tf-testAccCsgName-%d"
只有一个name

2021-08-18 12:48 UTC, xinmu0426 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
> +	addDebug(action, response, request)
debug 位置上移

2021-08-19 05:15 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_cloud_storage_gateway_gateways_test.go
> +	allConf := dataSourceTestAccConfig{
fake数据云产品报错

2021-08-19 05:15 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
> +			"public_network_bandwidth": {
done

2021-08-19 05:15 UTC, Wanghx0991 commented on website/docs/d/cloud_storage_gateway_gateways.html.markdown
> +data "alicloud_cloud_storage_gateway_gateways" "nameRegex" {
done

2021-08-19 05:15 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
> +		action := "ModifyGateway"
是的

2021-08-19 05:15 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway_test.go
> +					}),
done

2021-08-19 06:17 UTC, xiaozhu36 requested changes

2021-08-19 06:17 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cloud_storage_gateway_gateways_test.go
> +  vpc_name   = "tf_test_foo"
用 var.name

2021-08-19 06:17 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cloud_storage_gateway_gateways_test.go
> +  storage_bundle_name = "tf-acctest-gateway_storage_bundle-%d"
这个也一样

2021-08-19 06:17 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cloud_storage_gateway_gateways_test.go
> +  gateway_name = "tf-acctestGatewayName-%d"
还有这个

2021-08-19 06:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
> +				Type:     schema.TypeString,
location, type, gateway_class 应该都有枚举值吧

2021-08-19 06:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
> +				Optional: true,
reason_type有枚举值么？

2021-08-19 06:17 UTC, xiaozhu36 commented on website/docs/r/cloud_storage_gateway_gateway.html.markdown
> +* `gateway_name` - (Optional) gatway name.
这个文档太简单了，没有描述清楚

2021-08-19 06:29 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
> +				Type:     schema.TypeString,
是的, 整体补充了一下,这几个都加上了

2021-08-19 06:29 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
> +				Optional: true,
这个没有

2021-08-19 07:39 UTC, xiaozhu36 requested changes

2021-08-19 07:39 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway_test.go
> +				),
这个地方，所有的枚举值都要遍历修改一遍，对于不能修改的，应该扩展出来一个新的testcase

2021-08-19 07:39 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
> +	action := "DescribeTasks"
这个方法是干啥的

2021-08-19 09:55 UTC, merged