NewResource `alicloud_alb_acl` NewDataSource `alicloud_alb_acls`
aliyun/terraform-provider-alicloud pull request #3853
Opened 2021-08-18 10:38 UTC by super-eggs

NewResource `alicloud_alb_acl`
NewDataSource `alicloud_alb_acls`

2021-08-18 10:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3853) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3853) before we can accept your contribution.<br/><hr/>**guozhiyuan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3853) it.</sub>

2021-08-19 03:04 UTC, xinmu0426 commented on alicloud/resource_alicloud_alb_acl_test.go
> +						"acl_name": name + "_new",
更新那么应该以Update结尾

2021-08-19 03:04 UTC, xinmu0426 commented on alicloud/resource_alicloud_alb_acl_test.go
> +			},
name在更新回去

2021-08-19 03:04 UTC, xinmu0426 commented on alicloud/service_alicloud_alb.go
> +>>>>>>> ba2937355 (alicloud/service_alicloud_alb conflict fixed)
解决冲突

2021-08-19 03:04 UTC, xinmu0426 commented on website/alicloud.erb
> +>>>>>>> ba2937355 (alicloud/service_alicloud_alb conflict fixed)
解决冲突，注意文档位置

2021-08-19 03:04 UTC, xinmu0426 commented on website/docs/d/alb_acls.html.markdown
> +-> **NOTE:** Available in v1.131.0+.
改为132

2021-08-19 03:04 UTC, xinmu0426 commented on website/docs/d/alb_acls.html.markdown
> +* `status` - (Optional, ForceNew) The status of the resource.
枚举值都给加上

2021-08-19 03:04 UTC, xinmu0426 commented on website/docs/r/alb_acl.html.markdown
> +For information about ALB Acl and how to use it, see [What is Acl](https://help.aliyun.com/).
url改了

2021-08-19 03:04 UTC, xinmu0426 commented on website/docs/r/alb_acl.html.markdown
> +
132

2021-08-19 03:04 UTC, xinmu0426 commented on alicloud/resource_alicloud_alb_acl.go
> +				Computed: true,
枚举值补充上

2021-08-19 12:01 UTC, xinmu0426 commented on alicloud/resource_alicloud_alb_acl.go
> +						"description": {
description增加正则

2021-08-20 05:47 UTC, xiaozhu36 requested changes

2021-08-20 05:47 UTC, xiaozhu36 commented on alicloud/resource_alicloud_alb_acl.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
这个entries 是干啥的

2021-08-20 09:35 UTC, xinmu0426 commented on website/docs/r/alb_acl.html.markdown
> +* `status` - The state of the ACL. Valid values: `Provisioning`: The ACL is being created. `Available`: The ACL is available. `Configuring`: The ACL is being configured.
Valid values: F`Available`,`Configuring`后面再展开描绘吧

2021-08-20 09:35 UTC, xinmu0426 commented on website/docs/d/alb_acls.html.markdown
> +* `status` - (Optional, ForceNew) The state of the ACL. Valid values: `Provisioning`: The ACL is being created. `Available`: The ACL is available. `Configuring`: The ACL is being configured.
Valid values: FAvailable,Configuring后面再展开描绘吧

2021-08-23 07:43 UTC, merged