add new resource: sas group
aliyun/terraform-provider-alicloud pull request #3867
Opened 2021-08-19 12:22 UTC by ChenHanZhang

2021-08-19 12:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3867) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3867) before we can accept your contribution.<br/><hr/>**chenhanzhang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3867) it.</sub>

2021-08-20 07:45 UTC, xinmu0426 commented on alicloud/data_source_alicloud_security_center_groups_test.go
> +	groupIdConf := dataSourceTestAccConfig{
改为ids

2021-08-20 07:45 UTC, xinmu0426 commented on alicloud/resource_alicloud_security_center_group.go
> +			},
这个是不是应该改为computed

2021-08-20 07:45 UTC, xinmu0426 commented on website/docs/d/security_center_groups.html.markdown
> +	* `group_name` - GroupName.
描述为the xxx of 这种格式

2021-08-22 11:53 UTC, xiaozhu36 requested changes

2021-08-22 11:53 UTC, xiaozhu36 commented on alicloud/resource_alicloud_security_center_group.go
> +	d.Set("group_name", describeAllGroupsObject["GroupName"])
missing setting `group_id` and please add it.

2021-08-22 11:53 UTC, xiaozhu36 commented on website/docs/d/security_center_groups.html.markdown
> +-> **NOTE:** Available in v1.132.0+.
Please update it to 1.133.0

2021-08-23 03:11 UTC, merged