add new datasource: hbr snapshot
aliyun/terraform-provider-alicloud pull request #3883
Opened 2021-08-23 07:41 UTC by ChenHanZhang

2021-08-23 07:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3883) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3883) before we can accept your contribution.<br/><hr/>**chenhanzhang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3883) it.</sub>

2021-08-23 09:56 UTC, xinmu0426 commented on alicloud/data_source_alicloud_hbr_snapshots_test.go
> +	}
测试参数不完整，比如status，bucket都没有

2021-08-23 09:56 UTC, xinmu0426 commented on website/alicloud.erb
> +                         </li>
文档位置不对，放在了resource里面

2021-08-23 09:56 UTC, xinmu0426 commented on website/docs/d/hbr_snapshots.html.markdown
> +	* `id` - The ID of the Snapshot.
整体的翻译在看下

2021-08-23 09:56 UTC, xinmu0426 commented on alicloud/data_source_alicloud_hbr_snapshots_test.go
> +	}
如果存在case_when，需要写多个例子

2021-08-23 09:57 UTC, xinmu0426 commented on website/docs/d/hbr_snapshots.html.markdown
> +	* `status` - The status of snapshot execution. Possible values: *`COMPLETE` success,  *`PARTIAL_COMPLETE` partially succeeded, *`FAILED` failed.
先写枚举值，在写解释。

2021-08-23 09:57 UTC, xinmu0426 commented on alicloud/common.go
文件有冲突

2021-08-24 03:39 UTC, xiaozhu36 requested changes

2021-08-24 03:39 UTC, xiaozhu36 commented on alicloud/common.go
> +func convertMapListToJsonString(configured []map[string]interface{}) (string, error) {
Please use `convertListMapToJsonString`

2021-08-24 07:37 UTC, merged