NewResource alicloud_sae_ingress NewDataSource alicloud_sae_ingresses
aliyun/terraform-provider-alicloud pull request #3911
Opened 2021-08-26 11:12 UTC by thisnihonglei

2021-08-31 03:27 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_sae_ingresss_test.go
> +    domain = "www.baidu.com"
改一下

2021-08-31 03:27 UTC, Wanghx0991 commented on alicloud/resource_alicloud_sae_ingress_test.go
> +    domain = "www.baidu.com"
改下

2021-08-31 03:27 UTC, Wanghx0991 commented on alicloud/service_alicloud_sae.go
> +		response, err = conn.DoRequest(StringPointer("2019-05-06"), nil, StringPointer("GEY"), StringPointer("AK"), StringPointer(action), request, nil, nil, &util.RuntimeOptions{})
GEY

2021-08-31 03:27 UTC, Wanghx0991 commented on alicloud/service_alicloud_sae.go
> +		return object, WrapError(fmt.Errorf("%s failed, response: %v", "Put "+action, response))
改掉

2021-09-15 10:27 UTC, thisnihonglei commented on alicloud/data_source_alicloud_sae_ingresss_test.go
> +	}
rules 配置无效，是不支持的参数

2021-09-24 10:11 UTC, xiaozhu36 requested changes

2021-09-24 10:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_sae_ingress_test.go
> +		return WrapErrorf(err, FailedGetAttributeMsg, action, "$.Data", response)
error 都应该是用 log.printf 打印出来，然后 return nil

2021-09-24 10:42 UTC, merged