New Datasource alicloud_hbr_backup_jobs, optimize alicloud_hbr_snapshots property and its docs.
aliyun/terraform-provider-alicloud pull request #3950
Opened 2021-09-02 06:58 UTC by ChenHanZhang

…ots property and its documents.

2021-09-02 08:56 UTC, xinmu0426 commented on website/docs/d/hbr_backup_jobs.html.markdown
> +	* `include` - The include path.
补充下描述

2021-09-02 08:56 UTC, xinmu0426 commented on alicloud/data_source_alicloud_hbr_snapshots.go
>  			},
修改状态定义是否正确？

2021-09-02 09:44 UTC, ChenHanZhang commented on website/docs/d/hbr_backup_jobs.html.markdown
> +	* `include` - The include path.
已补充

2021-09-29 10:29 UTC, xiaozhu36 requested changes

2021-09-29 10:29 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_hbr_backup_jobs.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
如果regionId是一个list，那么应该改成 region_ids

2021-09-29 10:29 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_hbr_backup_jobs.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
下面的参数也都一样，为啥是list，但是都不是ids

2021-09-29 10:29 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_hbr_backup_jobs.go
> +		})
如果是这种kvpairs的形式，那么直接在schema中暴露一个 filters 就行，不需要把filter中的所有参数都单独暴露出来，具体的可以参考下：alicloud_express_connect_virtual_border_routers

2021-09-29 10:29 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_hbr_ecs_backup_plans_test.go
> +  name_regex = "hbr-ecs-backup-plan-dont-delete"
hbr-ecs-backup-plan-dont-delete 改成 no-deleteing-hbr-ecs-backup-plan

2021-09-29 13:49 UTC, merged