New resource alicloud_dts_jobmonintor_rule
aliyun/terraform-provider-alicloud pull request #3965
Opened 2021-09-03 09:55 UTC by ChenHanZhang

2021-09-04 03:36 UTC, xinmu0426 commented on alicloud/resource_alicloud_dts_job_monitor_rule.go
> +	}
state type是否有枚举值

2021-09-04 03:36 UTC, xinmu0426 commented on alicloud/resource_alicloud_dts_job_monitor_rule_test.go
> +				}),
这个id是自从哪里来的？

2021-09-04 03:36 UTC, xinmu0426 commented on alicloud/resource_alicloud_dts_job_monitor_rule.go
> +				Computed: true,
phone是否有正则

2021-09-04 03:36 UTC, xinmu0426 commented on alicloud/resource_alicloud_dts_job_monitor_rule_test.go
> +
sweeper 呢

2021-09-04 03:36 UTC, xinmu0426 commented on website/docs/r/dts_job_monitor_rule.html.markdown
> +
这块记得在generate加上注释

2021-09-04 03:36 UTC, xinmu0426 commented on website/docs/r/dts_job_monitor_rule.html.markdown
> +subcategory: "DTS"
改为 Data Transmission  (DTS)

2021-09-04 12:57 UTC, ChenHanZhang commented on alicloud/resource_alicloud_dts_job_monitor_rule.go
> +				Computed: true,
这个官方API上没有描述

2021-09-04 12:57 UTC, ChenHanZhang commented on alicloud/resource_alicloud_dts_job_monitor_rule_test.go
> +				}),
这个ID是账号上创建的一个Job资源。目前Job资源未接入，只能先这样测试，暂时跳过了该测试用例（Skipxxx），等Job资源录入后更新该测试文件

2021-09-04 12:57 UTC, ChenHanZhang commented on alicloud/resource_alicloud_dts_job_monitor_rule.go
> +				Computed: true,
并且phone本身是Computed类型，这个值会受其它资源属性的影响

2021-09-04 12:57 UTC, ChenHanZhang commented on alicloud/resource_alicloud_dts_job_monitor_rule_test.go
> +
该资源无法使用sweeper进行删除tf测试用例创建的实例。原因在于list接口中jobid是必填的，无法遍历所有资源。API：https://next.api.aliyun.com/api/Dts/2020-01-01/DescribeJobMonitorRule

2021-09-04 12:57 UTC, ChenHanZhang commented on alicloud/resource_alicloud_dts_job_monitor_rule.go
> +	}
以补充，但是这个我看了AMP有录入枚举值，但是生成代码里却没有生成

2021-09-04 14:37 UTC, xiaozhu36 requested changes

2021-09-04 14:37 UTC, xiaozhu36 commented on alicloud/connectivity/client.go
> +	client.config.Endpoints[productCode] = "dts.cn-hangzhou.aliyuncs.com"
这个地方的原因调查清楚了么？到底是什么？

2021-09-04 14:37 UTC, xiaozhu36 commented on website/alicloud.erb
> +                  <a href="#">DTS</a>
DTS 有全称么

2021-09-04 15:49 UTC, ChenHanZhang commented on alicloud/connectivity/client.go
> +	client.config.Endpoints[productCode] = "dts.cn-hangzhou.aliyuncs.com"
通过loadEndpoint获取的值是正确的，已纠正

2021-09-05 02:54 UTC, xiaozhu36 requested changes

2021-09-05 02:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_job_monitor_rule_test.go
> +				}),
不要使用真实的信息

2021-09-05 02:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_job_monitor_rule_test.go
> +	var v map[string]interface{}
job 可以在tf中对接么？
是否可以用datasource代替

2021-09-05 03:19 UTC, ChenHanZhang commented on alicloud/resource_alicloud_dts_job_monitor_rule_test.go
> +	var v map[string]interface{}
Job可以对接，但暂未对接，因此还没有DataSource，后续等Job对接上了再修改测试用例

2021-09-05 08:30 UTC, merged