logservice audit support resource directory
aliyun/terraform-provider-alicloud pull request #3983
Opened 2021-09-08 07:35 UTC by lichengseu

log audit service of log_service support resource directory

2021-09-08 07:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3983) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=3983) before we can accept your contribution.<br/><hr/>**licheng** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=3983) it.</sub>

2021-09-08 11:43 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_audit.go
> +	resourceDirectoryType := d.Get("resource_directory_type").(string)
这里用d.getOk 或者 判断下 resourceDirectoryType是否为 nil

2021-09-08 11:43 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_audit.go
> +	d.Set("multi_account", make([]string, 0))
这块是不是有问题

2021-09-08 11:43 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_audit.go
>  }
在写一个针对这个字段的测试用例

2021-09-09 08:54 UTC, xiaozhu36 requested changes

2021-09-09 08:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_audit.go
> +			return WrapError(errors.New("Invalid resource_directory_type, must be one of 'custom' or 'all'"))
这个地方不要这么写，直接在schema中定义validation 就行

2021-09-09 08:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_audit.go
> +	d.Set("multi_account", make([]string, 0))
这个有问题，不要设置空的值

2021-09-09 14:36 UTC, xiaozhu36 requested changes

2021-09-09 14:36 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_audit.go
> +	resourceDirectoryType := d.Get("resource_directory_type").(string)
这个地方需要按照如上的意见修改

2021-09-09 14:36 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_audit_test.go
>  }
请在文档中补充新的属性

2021-09-09 16:24 UTC, lichengseu commented on alicloud/resource_alicloud_log_audit.go
> +	resourceDirectoryType := d.Get("resource_directory_type").(string)
这里d.Get()方法的实现里已经包了getok，所以不用担心nil的情况。

2021-09-09 16:24 UTC, lichengseu commented on alicloud/resource_alicloud_log_audit.go
> +	d.Set("multi_account", make([]string, 0))
已修改，去除该行

2021-09-09 16:43 UTC, lichengseu commented on alicloud/resource_alicloud_log_audit.go
>  }
测试用例已补充到alicloud/resource_alicloud_log_audit_test.go中

2021-09-09 16:54 UTC, lichengseu commented on alicloud/resource_alicloud_log_audit_test.go
>  }
已补充

2021-09-10 02:45 UTC, lichengseu commented on alicloud/resource_alicloud_log_audit.go
> +			return WrapError(errors.New("Invalid resource_directory_type, must be one of 'custom' or 'all'"))
已修改

2021-09-10 07:12 UTC, xiaozhu36 requested changes

2021-09-10 07:12 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_audit.go
> +	resourceDirectoryType := d.Get("resource_directory_type").(string)
这个不一样，如果得到是 nil，那么直接转 string 会报错，改为 d.GetOk

2021-09-10 07:12 UTC, xiaozhu36 commented on website/docs/r/log_audit.html.markdown
> +* `resource_directory_type` - (Optional) Resource Directory type. Optional values are all or custom. If the value is custom, argument multi_account should be provided.
在括号中增加一个 Availeble的tag：(Optional, Available in 1.135.0+)

2021-09-10 10:00 UTC, lichengseu commented on alicloud/resource_alicloud_log_audit.go
> +	resourceDirectoryType := d.Get("resource_directory_type").(string)
![image](https://user-images.githubusercontent.com/10131217/132836772-a8f3368d-5d1b-4845-9784-a18ddd50dad6.png)
这里d.Get()其实就是d.GetOK，如果这个参数是nil，会返回""的

2021-09-10 10:03 UTC, lichengseu commented on website/docs/r/log_audit.html.markdown
> +* `resource_directory_type` - (Optional) Resource Directory type. Optional values are all or custom. If the value is custom, argument multi_account should be provided.
已增加

2021-09-11 00:38 UTC, xiaozhu36 requested changes

2021-09-11 00:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_audit.go
> +	resourceDirectoryType := d.Get("resource_directory_type").(string)
这个地方是没有判断是否有 key 这个值存在的，返回的v有可能就是空，这个必须改

2021-09-11 02:53 UTC, merged