NewResource `alicloud_vpc_nat_ip_cidr` NewDataSource `alicloud_vpc_nat_ip_cidrs`
aliyun/terraform-provider-alicloud pull request #4005
Opened 2021-09-13 08:40 UTC by super-eggs

NewResource `alicloud_vpc_nat_ip_cidr` NewDataSource `alicloud_vpc_nat_ip_cidrs`

2021-09-13 09:15 UTC, xinmu0426 commented on alicloud/data_source_alicloud_vpc_nat_ip_cidrs.go
> +				Type:     schema.TypeString,
remove dry_run

2021-09-13 09:15 UTC, xinmu0426 commented on alicloud/data_source_alicloud_vpc_nat_ip_cidrs.go
> +			},
status 只有一个？

2021-09-13 09:15 UTC, xinmu0426 commented on alicloud/data_source_alicloud_vpc_nat_ip_cidrs.go
> +				Type:     schema.TypeBool,
enable_details 这个是否有用

2021-09-13 09:15 UTC, xinmu0426 commented on alicloud/data_source_alicloud_vpc_nat_ip_cidrs_test.go
> +		}),
去掉natIpCidrConf

2021-09-13 09:15 UTC, xinmu0426 commented on alicloud/resource_alicloud_nat_gateway.go
> +				Computed: true,
这个不是有枚举值么

2021-09-13 09:15 UTC, xinmu0426 commented on website/docs/d/vpc_nat_ip_cidrs.html.markdown
> +* `nat_ip_cidr` - (Optional, ForceNew) The NAT CIDR block to be created. The CIDR block must meet the following conditions: It must be `10.0.0.0/8`, `172.16.0.0/12`, `192.168.0.0/16`, or one of their
是不是应该为 nat_ip_cidrs

2021-09-15 02:07 UTC, xiaozhu36 requested changes

2021-09-15 02:07 UTC, xiaozhu36 commented on alicloud/resource_alicloud_nat_gateway.go
> +			},
对存量资源的修改单独提交一个PR吧

2021-09-15 10:35 UTC, merged