New resource alicloud_dts_subscription_job and its datasource
aliyun/terraform-provider-alicloud pull request #4017
Opened 2021-09-16 07:48 UTC by ChenHanZhang

2021-09-16 08:52 UTC, xinmu0426 commented on alicloud/data_source_alicloud_dts_subscription_jobs_test.go
> +		}),
为啥只测试三个？其他如果确认不是可查的，可以去掉

2021-09-16 08:52 UTC, xinmu0426 commented on alicloud/resource_alicloud_dts_subscription_job.go
> +	d.Set("source_endpoint_engine_name", object["SourceEndpoint"].(map[string]interface{})["EngineName"])
这种不需要都转换吧 object["SourceEndpoint"].(map[string]interface{}) 而且可能panic

2021-09-16 08:52 UTC, xinmu0426 commented on website/alicloud.erb
> +                            <a href="/docs/providers/alicloud/r/dts_subscription_job.html">alicloud_dts_subscription_job</a>
这个位置不对

2021-09-16 08:52 UTC, xinmu0426 commented on website/docs/d/dts_subscription_jobs.html.markdown
> +	* `dts_job_name` - Subscription task name.
文档翻译规范下

2021-09-16 08:52 UTC, xinmu0426 commented on website/docs/d/dts_subscription_jobs.html.markdown
> +* `order_column` - (Optional, ForceNew) The order column.
去掉不必要的查询参数

2021-09-22 13:07 UTC, xiaozhu36 requested changes

2021-09-22 13:07 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_subscription_job.go
> +			"period": {
这个不对吧，period一般只的是具体的计费时长，不是计费单位

2021-09-22 13:07 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_subscription_job_test.go
> +					"db_list":                            "{\\\"tfaccountpri_0\\\":{\\\"name\\\":\\\"tfaccountpri_0\\\",\\\"all\\\":true,\\\"state\\\":\\\"normal\\\"}}",
这个db list 可以结构化么

2021-09-23 02:37 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_dts_subscription_jobs_test.go
> +    source_endpoint_region              = "cn-hangzhou"
这里的region和地域化部署的那个region不是一个语义

2021-09-23 02:37 UTC, ChenHanZhang commented on alicloud/resource_alicloud_dts_subscription_job.go
> +			"period": {
云产品给的就是单位，时长由”UsedTime“这个参数定义

2021-09-23 02:37 UTC, ChenHanZhang commented on alicloud/resource_alicloud_dts_subscription_job_test.go
> +					"db_list":                            "{\\\"tfaccountpri_0\\\":{\\\"name\\\":\\\"tfaccountpri_0\\\",\\\"all\\\":true,\\\"state\\\":\\\"normal\\\"}}",
不行，dblist的结构取决于数据库的表设计，无法结构化定义出来

2021-09-26 06:55 UTC, xiaozhu36 requested changes

2021-09-26 06:55 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_dts_subscription_jobs_test.go
> +  instance_type    = "rds.mysql.s1.small"
这个地方不要写死，要用datasource去查，具体的可以参考下rds account的集成测试

2021-09-26 06:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_subscription_job.go
> +				ValidateFunc: validation.StringInSlice([]string{"PrePaid", "PostPaid"}, false),
payment_type 的值应该用 PayAsYouGo和Subscription

2021-09-26 06:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_subscription_job.go
> +				Computed: true,
job_id 是可以让客户指定的么？

2021-09-26 06:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_subscription_job_test.go
> +				ImportStateVerify: true, ImportStateVerifyIgnore: []string{"source_endpoint_password", "error_phone", "quantity", "payment_duration_unit", "destination_region", "database_count", "delay_notice",
这个地方，好多参数在schema中都没有

2021-09-26 06:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_subscription_job_test.go
> +  instance_type    = "rds.mysql.s1.small"
和上面一样，不要写死，使用datasource动态获取

2021-09-28 13:25 UTC, ChenHanZhang commented on alicloud/resource_alicloud_dts_subscription_job.go
> +		if v.(string) == "PrePaid" {
Subscription

2021-09-29 05:33 UTC, ChenHanZhang commented on website/docs/d/dts_subscription_jobs.html.markdown
> +* `name_regex` - (Optional, ForceNew) A regex string to filter results by Policy Group name.
fix

2021-09-29 05:33 UTC, ChenHanZhang commented on website/docs/d/dts_subscription_jobs.html.markdown
> +* `enable_details` - (Optional) Default to `false`. Set it to `true` can output more details about resource attributes.
delete

2021-09-29 05:52 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_dts_subscription_jobs.go
> +	names := make([]interface{}, 0)
delete

2021-09-29 09:00 UTC, merged