NewResource `alicloud_graph_database_db_instance` NewDataSource `alicloud_graph_database_db_instances`
aliyun/terraform-provider-alicloud pull request #4020
Opened 2021-09-17 08:55 UTC by super-eggs

NewResource `alicloud_graph_database_db_instance`
NewDataSource `alicloud_graph_database_db_instances`

2021-09-17 11:38 UTC, xinmu0426 commented on alicloud/data_source_alicloud_graph_database_db_instances.go
> +			for _, DBInstanceIPArrayArg := range DBInstanceIPArray.([]interface{}) {
强转看下

2021-09-17 11:38 UTC, xinmu0426 commented on alicloud/data_source_alicloud_graph_database_db_instances.go
> +		s = append(s, mapping)
PublicPort 和 Port 为啥会有区别

2021-09-17 11:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_graph_database_db_instance.go
> +			Delete: schema.DefaultTimeout(1 * time.Minute),
Create 和 Update时间统一30min吧

2021-09-17 11:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_graph_database_db_instance.go
> +		for _, DBInstanceIPArrayArg := range DBInstanceIPArray.([]interface{}) {
强转

2021-09-17 11:38 UTC, xinmu0426 commented on website/docs/d/graph_database_db_instances.html.markdown
> +    * `db_instance_storage_type` - Cloud Disk.
这个翻译看下

2021-09-17 11:38 UTC, xinmu0426 commented on website/docs/d/graph_database_db_instances.html.markdown
> +    * `lock_mode` - Instance lock state. Value range: `Unlock`: normal, `ManualLock`: the manual trigger lock, `LockByExpiration`: that represents the instance expires automatically lock, `LockByRest
格式

2021-09-17 11:38 UTC, xinmu0426 commented on website/docs/r/graph_database_db_instance.html.markdown
> +
timeouts 同步改下

2021-09-18 07:23 UTC, xiaozhu36 requested changes

2021-09-18 07:23 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_graph_database_db_instances_test.go
> +  db_instance_network_type = "vpc"
既然是vpc类型的，为啥没有vpc相关的配置

2021-09-18 09:15 UTC, merged