New Resource alicloud_cloudauth_face_config  New Datasource alicloud_…
aliyun/terraform-provider-alicloud pull request #4031
Opened 2021-09-22 08:57 UTC by Wanghx0991

…cloudauth_face_configs

2021-09-22 12:19 UTC, xinmu0426 commented on alicloud/resource_alicloud_cloudauth_face_config.go
> +	}
Lang

2021-09-24 06:35 UTC, xiaozhu36 requested changes

2021-09-24 06:35 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloudauth_face_config_test.go
> +				ImportStateVerify: true, ImportStateVerifyIgnore: []string{"source_ip"},
schema中没有 source_ip 这个属性啊

2021-09-24 06:35 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloudauth_face_config.go
> +				Required: true,
biz_type 有枚举值么

2021-09-24 06:35 UTC, xiaozhu36 commented on website/docs/index.html.markdown
> +* `cddc` - (Optional) Use this to override the default endpoint URL constructed from the `region`. It's typically used to connect to custom ApsaraDB for MyBase endpoints.
这个地方放的code都是 location code，请确认

2021-09-24 07:16 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cloudauth_face_config_test.go
> +				ImportStateVerify: true, ImportStateVerifyIgnore: []string{"source_ip"},
这个是用来标注是哪个平台打过去的请求, 咱们传的时候用的是buildClientToken, 已经去掉

2021-09-24 07:16 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cloudauth_face_config.go
> +				Required: true,
没有的,这个是用户自定义的type

2021-09-24 07:16 UTC, Wanghx0991 commented on website/docs/index.html.markdown
> +* `cddc` - (Optional) Use this to override the default endpoint URL constructed from the `region`. It's typically used to connect to custom ApsaraDB for MyBase endpoints.
已更改

2021-09-24 11:38 UTC, merged