New Resource `alicloud_service_mesh_service_mesh` New Datasource `alicloud_service_mesh_service_meshes`
aliyun/terraform-provider-alicloud pull request #4059
Opened 2021-09-28 06:53 UTC by super-eggs

New Resource `alicloud_service_mesh_service_mesh`
New Datasource `alicloud_service_mesh_service_meshes`

2021-09-28 07:50 UTC, xinmu0426 commented on alicloud/data_source_alicloud_service_mesh_service_meshes.go
> +			"error_message":     object["ServiceMeshInfo"].(map[string]interface{})["ErrorMessage"],
object["ServiceMeshInfo"] 不需要多次转换，以及强转判断下

2021-09-28 07:50 UTC, xinmu0426 commented on alicloud/data_source_alicloud_service_mesh_service_meshes.go
> +			endpointsMap["intranet_api_server_endpoint"] = endpoints.(map[string]interface{})["IntranetApiServerEndpoint"]
endpoints 强转问题

2021-09-28 07:50 UTC, xinmu0426 commented on alicloud/data_source_alicloud_service_mesh_service_meshes.go
> +					accessLogMap := make(map[string]interface{})
accessLog 强转

2021-09-28 07:50 UTC, xinmu0426 commented on alicloud/data_source_alicloud_service_mesh_service_meshes.go
> +					auditMap["enabled"] = audit.(map[string]interface{})["Enabled"]
audit 强转

2021-09-28 07:50 UTC, xinmu0426 commented on alicloud/resource_alicloud_service_mesh_service_mesh_test.go
> +							"tracing": "true",
备注去掉

2021-09-28 08:30 UTC, xinmu0426 commented on alicloud/data_source_alicloud_service_mesh_service_meshes.go
> +			mapping["id"] = fmt.Sprint(object["ServiceMeshInfo"].(map[string]interface{})["ServiceMeshId"])
remove object["ServiceMeshInfo"].(map[string]interface{})

2021-09-28 08:30 UTC, xinmu0426 commented on alicloud/data_source_alicloud_service_mesh_service_meshes.go
> +						accessLogSli = append(accessLogSli, accessLogMap)
&& len(accessLog.(map[string]interface{})) > 0 放在里面吧

2021-09-28 08:30 UTC, xinmu0426 commented on alicloud/data_source_alicloud_service_mesh_service_meshes.go
> +						auditMap["enabled"] = auditArg["Enabled"]
和上面一样

2021-09-28 08:30 UTC, xinmu0426 commented on alicloud/data_source_alicloud_service_mesh_service_meshes.go
> +				loadBalancerMap["pilot_public_eip"] = loadBalancer.(map[string]interface{})["PilotPublicEip"]
强转

2021-09-28 08:30 UTC, xinmu0426 commented on alicloud/resource_alicloud_service_mesh_service_mesh.go
> +					}
强转

2021-09-28 08:30 UTC, xinmu0426 commented on website/docs/r/service_mesh_service_mesh.html.markdown
> +
少force

2021-09-29 08:51 UTC, xiaozhu36 requested changes

2021-09-29 08:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_service_mesh_service_mesh.go
> +			if IsExpectedErrors(err, []string{"ERR404", "InvalidActiveState.ACK", "NameAlreadyExist"}) || NeedRetry(err) {
NameAlreadyExist  这个错误也需要重试么

2021-09-29 10:12 UTC, merged