New Resource alicloud_ecd_user New Datasource alicloud_ecd_users
aliyun/terraform-provider-alicloud pull request #4126
Opened 2021-10-22 07:08 UTC by thisnihonglei

2021-10-31 09:42 UTC, xiaozhu36 requested changes

2021-10-31 09:42 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecd_users_test.go
> +	email       = "testacc%d@alibaba-inc.com"
不要用 alibaba-inc.com 的后缀

2021-10-31 09:42 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_user.go
> +			"password": {
password 应该是 sensitive 的

2021-10-31 09:42 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_user_test.go
> +					"email":       fmt.Sprintf("testacc%d@alibaba-inc.com", rand),
这个也一样

2021-10-31 09:42 UTC, xiaozhu36 commented on website/docs/r/ecd_user.html.markdown
> +For information about Elastic Desktop Service(EDS) User and how to use it, see [What is User](https://help.aliyun.com/document_detail/188382.html).
没有英文文档地址吗

2021-11-01 02:17 UTC, thisnihonglei commented on website/docs/r/ecd_user.html.markdown
> +For information about Elastic Desktop Service(EDS) User and how to use it, see [What is User](https://help.aliyun.com/document_detail/188382.html).
ECD没有英文文档地址

2021-11-01 06:34 UTC, xiaozhu36 requested changes

2021-11-01 06:34 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_user_test.go
> +			},
没有ImportStateVerify

2021-11-01 06:34 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_user_test.go
> +			// 删除资源Api
去掉无用的注释

2021-11-01 08:49 UTC, xiaozhu36 requested changes

2021-11-01 08:49 UTC, xiaozhu36 commented on alicloud/provider.go
> +		config.EdsuserEndpoint = strings.TrimSpace(endpoints["eds-user"].(string))
这个endpoint code eds-user 跟后面的edsuser不一致啊

2021-11-01 08:49 UTC, xiaozhu36 commented on alicloud/provider.go
> +	buf.WriteString(fmt.Sprintf("%s-", m["eds-user"].(string)))
这个也一样

2021-11-03 02:50 UTC, xiaozhu36 requested changes

2021-11-03 02:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_user_test.go
> +			testAccPreCheckWithRegions(t, true, connectivity.EcdSupportRegions)
region的检查要放在上面

2021-11-03 03:40 UTC, merged