New resource alicloud_hbr_ecs_server_backup_plan and its datasource.
aliyun/terraform-provider-alicloud pull request #4144
Opened 2021-10-27 12:52 UTC by ChenHanZhang

2021-10-31 09:50 UTC, xiaozhu36 requested changes

2021-10-31 09:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_hbr_server_backup_plan.go
> +						},
-1 根类型 string 不一致

2021-10-31 09:50 UTC, xiaozhu36 commented on website/docs/r/hbr_server_backup_plan.html.markdown
> +* `detail` - (Required) ECS server backup plan details.
单独抽出来

2021-10-31 13:11 UTC, xiaozhu36 requested changes

2021-10-31 13:11 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_hbr_server_backup_plans.go
> +								Schema: map[string]*schema.Schema{
这个detail 为啥是required？

2021-10-31 13:11 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_hbr_server_backup_plans_test.go
> +		"plans.0.id": CHECKSET,
其他属性的check呢？

2021-10-31 13:40 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_hbr_server_backup_plans.go
> +								Schema: map[string]*schema.Schema{
detail的子项目中有requried元素

2021-11-05 08:32 UTC, xinmu0426 commented on alicloud/data_source_alicloud_hbr_server_backup_plans.go
> +								Schema: map[string]*schema.Schema{
这块是出参，不需要用required，optional

2021-11-05 08:32 UTC, xinmu0426 commented on alicloud/data_source_alicloud_hbr_server_backup_plans_test.go
> +		"plans.0.schedule":                    CHECKSET,
检查补充完整不完整

2021-11-05 08:34 UTC, xinmu0426 commented on website/docs/r/hbr_server_backup_plan.html.markdown
> +-> **NOTE:** Available in v1.141.0+.
142

2021-11-05 08:34 UTC, xinmu0426 commented on website/docs/d/hbr_server_backup_plans.html.markdown
> +-> **NOTE:** Available in v1.141.0+.
142

2021-11-05 10:31 UTC, xinmu0426 commented on alicloud/data_source_alicloud_hbr_server_backup_plans.go
> +			diskLists := make([]string, 0)
expandStringList

2021-11-05 10:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_hbr_server_backup_plan.go
> +		if v["diskIdList"] != nil {
expandStringList

2021-11-05 10:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_hbr_server_backup_plan.go
> +	}
必填不需要这样

2021-11-05 10:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_hbr_server_backup_plan.go
> +	d.Set("retention", fmt.Sprint(formatInt(object["Retention"])))
retention 确定下类型吧，为啥来回转换

2021-11-05 10:31 UTC, xinmu0426 commented on alicloud/data_source_alicloud_hbr_server_backup_plans.go
> +									"destination_retention": {
TypeInt

2021-11-05 10:31 UTC, xinmu0426 commented on alicloud/service_alicloud_hbr.go
> +		"PageSize":   10,
PageSizeLarge

2021-11-05 10:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_hbr_server_backup_plan_test.go
> +func TestAccAlicloudHBRServerBackupPlan_basic0(t *testing.T) {
swapper

2021-11-06 08:15 UTC, merged