New Resource alicloud_ecd_network_package New Datasource alicloud_ecd_network_packages
aliyun/terraform-provider-alicloud pull request #4153
Opened 2021-10-29 02:47 UTC by thisnihonglei

2021-11-04 08:15 UTC, Wanghx0991 commented on website/docs/d/ecd_network_packages.html.markdown
> +-> **NOTE:** Available in v1.141.0+.
142

2021-11-04 08:15 UTC, Wanghx0991 commented on website/docs/d/ecd_network_packages.html.markdown
> +data "alicloud_ecd_network_packages" "default" {}
ids = [alicloud_ecd_network_package.default.id]

2021-11-04 08:15 UTC, Wanghx0991 commented on website/docs/d/ecd_network_packages.html.markdown
> +data "alicloud_ecd_network_packages" "default" {}
改之后 本地试一下 是否正常

2021-11-04 08:15 UTC, Wanghx0991 commented on website/docs/r/ecd_network_package.html.markdown
> +-> **NOTE:** Available in v1.141.0+.
142

2021-11-04 08:15 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_network_package.go
> +			"network_package_id": {
这个是纯出参么? 怎么是Optional

2021-11-04 08:15 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_network_package.go
> +			"network_package_id": {
这个是纯出参么? 怎么是Optional

2021-11-04 08:15 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_network_package.go
> +			"network_package_id": {
创建接口里没有这个字段

2021-11-04 08:15 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_network_package.go
> +
stateConf := BuildStateConf([]string{"Creating"}, []string{"InUse"}, d.Timeout(schema.TimeoutDelete), 5*time.Second, ecdService.EcdNetworkPackageRefreshFunc(d.Id(), []string{}))
	if _, err := stateConf.WaitForState(); err != nil {
		return WrapErrorf(err, IdMsg, d.Id())
	}

2021-11-04 08:15 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_simple_office_site.go
> +				Deprecated:   "Field 'bandwidth' has been deprecated from provider version 1.141.0. you ",
you 删去

2021-11-04 08:15 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_simple_office_site.go
> +	// todo:  you can find configure it using alicloud_ecd_network_package
todo:  you can configure it using alicloud_ecd_network_package

2021-11-05 06:55 UTC, xiaozhu36 requested changes

2021-11-05 06:55 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecd_network_packages_test.go
> +			"packages.0.office_site_name":     fmt.Sprintf("tf-testacc-ecdnetworkpackage%d", rand),
缺少检查的属性

2021-11-05 06:55 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecd_simple_office_sites.go
> +							Deprecated: "Field 'enable_internet_access' has been deprecated from provider version 1.141.0.",
这个参数在上个datasource中没有看到

2021-11-05 06:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_network_package.go
> +			"network_package_id": {
这个不需要啊，这个跟id是一样的

2021-11-05 08:38 UTC, xiaozhu36 requested changes

2021-11-05 08:38 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecd_network_packages_test.go
> +			"packages.0.expired_time":         CHECKSET,
还是缺少啊，个数都对不上

2021-11-05 08:38 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecd_simple_office_sites.go
> +							Deprecated: "Field 'enable_internet_access' has been deprecated from provider version 1.141.0.",
这个你咋解决的，直接在这评论出来

2021-11-05 08:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_network_package.go
> +	d.Set("network_package_id", object["NetworkPackageId"])
这个属性不是没了么？这个资源不是自动生成的么？

2021-11-05 08:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_network_package_test.go
> +	"status": CHECKSET,
属性检查不全

2021-11-05 08:38 UTC, xiaozhu36 commented on website/docs/r/ecd_simple_office_site.html.markdown
> +* `enable_cross_desktop_access` - (Deprecated) Field 'enable_cross_desktop_access' has been deprecated from provider version 1.141.0.
这个参数没有在代码中弃用啊

2021-11-05 15:45 UTC, xiaozhu36 requested changes

2021-11-05 15:45 UTC, xiaozhu36 commented on website/docs/d/ecd_simple_office_sites.html.markdown
> +	* `bandwidth` - Field 'bandwidth' has been deprecated from provider version 1.142.0. you can find it in `alicloud_ecd_network_package`.
语法有问题，you 的Y应该大写。这句话改成： * `bandwidth` - (Depreacted from 1.142.0) The Internet Bandwidth  Peak. It has been deprecated from version 1.142.0 and can be found in the new datasource `alicloud_ecd_network_packages`.

2021-11-05 15:45 UTC, xiaozhu36 commented on website/docs/d/ecd_simple_office_sites.html.markdown
> +	* `enable_internet_access` - Field 'enable_internet_access' has been deprecated from provider version 1.142.0. you can find it in `alicloud_ecd_network_package`.
这个字段本身就不在新的datasource中，你怎么在新的datasource中找到这个字段。改成下面的：
 `enable_internet_access` - (Depreacted from 1.142.0) Whether the Open Internet Access Function.

2021-11-05 15:45 UTC, xiaozhu36 commented on website/docs/r/ecd_simple_office_site.html.markdown
>  * `cen_id` - (Optional, ForceNew) Cloud Enterprise Network Instance ID.
改成： * `bandwidth` - (Depreacted from 1.142.0) The Internet Bandwidth  Peak. It has been deprecated from version 1.142.0 and can be found in the new resource `alicloud_ecd_network_package`.

2021-11-05 15:45 UTC, xiaozhu36 commented on website/docs/r/ecd_simple_office_site.html.markdown
> +* `enable_internet_access` - (Deprecated) Field 'enable_cross_desktop_access' has been deprecated from provider version 1.142.0. you can use resource to `alicloud_ecd_network_package` to create.
改成： `enable_internet_access` - (Depreacted from 1.142.0) Whether the Open Internet Access Function.

2021-11-05 15:45 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_simple_office_site.go
> +				Deprecated: "Field 'enable_internet_access' has been deprecated from provider version 1.142.0.",
既然是弃用的，那么还是应该保留 Optional：true 的配置

2021-11-05 15:45 UTC, xiaozhu36 commented on website/docs/r/ecd_simple_office_site.html.markdown
> +* `enable_internet_access` - Field 'enable_cross_desktop_access' has been deprecated from provider version 1.142.0. you can use resource to `alicloud_ecd_network_package` to create.
这个地方不需要

2021-11-05 15:45 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_simple_office_site.go
>  	d.Set("office_site_name", object["Name"])
既然是弃用的，那么上面这两个set还是应该保留

2021-11-05 15:45 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_simple_office_site.go
> +	// todo: you can configure it using alicloud_ecd_network_package
对于弃用的，这两个请求设置也应该保留

2021-11-05 15:45 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_simple_office_site.go
>  			},
对于弃用的，应该去掉forceNew，增加上computed

2021-11-05 15:45 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecd_simple_office_sites.go
> -			"enable_internet_access":      object["EnableInternetAccess"],
对于弃用的，应该保留对值的set

2021-11-06 08:20 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_simple_office_site.go
> +	// todo: you can configure it using alicloud_ecd_network_package
已设置保留

2021-11-06 12:27 UTC, merged