New Resource `alicloud_gpdb_account` New Datasource `alicloud_gpdb_accounts`
aliyun/terraform-provider-alicloud pull request #4158
Opened 2021-11-01 02:24 UTC by xinmu0426

New Datasource `alicloud_gpdb_accounts`

2021-11-03 07:20 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_gpdb_accounts.go
> +				ValidateFunc: validation.StringInSlice([]string{"0", "1", "3"}, false),
这块转换下语义体感会好些

2021-11-03 07:20 UTC, Wanghx0991 commented on website/docs/d/gpdb_accounts.html.markdown
> +* `status` - (Optional, ForceNew) The status of the account. Valid values: `0`, `1` and `2`.
这块语义转一下吧

2021-11-04 07:40 UTC, xiaozhu36 requested changes

2021-11-04 07:40 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_gpdb_accounts_test.go
> +		}
缺少属性

2021-11-04 07:40 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_gpdb_accounts_test.go
> +}
实例没有指定name，后面无法清理

2021-11-04 07:40 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_account.go
> +	return source
这种用数字 表示状态的不规范问题，有开aone么

2021-11-04 07:40 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_account_test.go
> +  vswitch_id               = length(data.alicloud_vswitches.default.ids) > 0 ? data.alicloud_vswitches.default.ids[0] : concat(alicloud_vswitch.default.*.id, [""])[0]
实例缺少name，后面无法统一清理

2021-11-04 07:57 UTC, xinmu0426 commented on alicloud/resource_alicloud_gpdb_account_test.go
> +  vswitch_id               = length(data.alicloud_vswitches.default.ids) > 0 ? data.alicloud_vswitches.default.ids[0] : concat(alicloud_vswitch.default.*.id, [""])[0]
alicloud_gpdb_elastic_instance按照description清理，db_instance_description 已改为var.name

2021-11-04 07:57 UTC, xinmu0426 commented on alicloud/resource_alicloud_gpdb_account.go
> +	return source
开了

2021-11-04 07:57 UTC, xinmu0426 commented on alicloud/data_source_alicloud_gpdb_accounts_test.go
> +}
alicloud_gpdb_elastic_instance按照description清理，db_instance_description 已改为var.name

2021-11-04 12:35 UTC, merged