New Resource alicloud_cms_dynamic_tag_group New Datasource alicloud_cms_dynamic_tag_groups
aliyun/terraform-provider-alicloud pull request #4160
Opened 2021-11-03 02:51 UTC by thisnihonglei

2021-11-03 08:45 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_cms_dynamic_tag_groups.go
> +							Optional: true,
Computed: true

2021-11-03 08:45 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_cms_dynamic_tag_groups.go
> +										Optional: true,
computed

2021-11-03 08:45 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_cms_dynamic_tag_groups.go
> +										Optional: true,
computed

2021-11-03 08:45 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_cms_dynamic_tag_groups.go
> +							ForceNew: true,
DataSource没有ForceNew

2021-11-03 08:45 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_cms_dynamic_tag_groups.go
> +							ForceNew: true,
下面也一样

2021-11-04 14:43 UTC, Wanghx0991 commented on website/docs/r/cms_dynamic_tag_group.html.markdown
> +> currently, only one combination condition is supported, and Alibaba Cloud will support multiple combination conditions in the future.
这里删去

2021-11-04 14:43 UTC, Wanghx0991 commented on website/docs/r/cms_dynamic_tag_group.html.markdown
> +> An alarm Contact Group is a group of alarm contacts that can contain one or more alarm contacts.
删去

2021-11-04 14:46 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cms_dynamic_tag_group.go
> +		Delete: resourceAlicloudCmsDynamicTagGroupDelete,
Update方法呢?

2021-11-05 05:59 UTC, thisnihonglei commented on website/docs/d/cms_dynamic_tag_groups.html.markdown
> +```terraform
这个是已经format过的

2021-11-05 06:10 UTC, thisnihonglei commented on alicloud/resource_alicloud_cms_dynamic_tag_group.go
> +		Delete: resourceAlicloudCmsDynamicTagGroupDelete,
加上了

2021-11-05 07:46 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cms_dynamic_tag_group_test.go
> +				ImportStateVerify: true, ImportStateVerifyIgnore: []string{"contact_group_list"},
contact_group_list 创建里的必填, 查却插不回来, 把这个Aone开出来

2021-11-05 07:46 UTC, Wanghx0991 commented on alicloud/service_alicloud_cms.go
> +		"PageSize":    50,
const 规范下

2021-11-05 07:49 UTC, thisnihonglei commented on alicloud/resource_alicloud_cms_dynamic_tag_group_test.go
> +				ImportStateVerify: true, ImportStateVerifyIgnore: []string{"contact_group_list"},
好的

2021-11-05 15:51 UTC, xiaozhu36 requested changes

2021-11-05 15:51 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cms_dynamic_tag_groups_test.go
> +		}
属性检查不完全

2021-11-05 15:51 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cms_dynamic_tag_groups_test.go
> +			default = "cloud_group_%d"
为什么不是以 tf-testacc 开头的

2021-11-05 15:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cms_dynamic_tag_group.go
> +				Computed: true,
既然没有update，为啥上面的两个参数不是forcenew的

2021-11-05 15:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cms_dynamic_tag_group_test.go
> +	"contact_group_list.#": CHECKSET,
属性检查不完全

2021-11-05 15:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cms_dynamic_tag_group_test.go
> +	name := fmt.Sprintf("cloud_group_%d", rand)
为啥不是tf-testacc 开头的

2021-11-05 15:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cms_dynamic_tag_group_test.go
> +		"appgroup",
为啥要增加一个appgroup

2021-11-06 08:34 UTC, thisnihonglei commented on alicloud/resource_alicloud_cms_dynamic_tag_group.go
> +				Computed: true,
上面两个参数已加ForceNew

2021-11-06 08:57 UTC, merged