New Resource `alicloud_simple_application_server_firewall_rule`    New Datasource `alicloud_simple_application_server_firewall_rules`
aliyun/terraform-provider-alicloud pull request #4183
Opened 2021-11-09 03:14 UTC by super-eggs

New Resource `alicloud_simple_application_server_firewall_rule`
New Datasource `alicloud_simple_application_server_firewall_rules`

2021-11-10 11:34 UTC, xinmu0426 commented on alicloud/data_source_alicloud_simple_application_server_firewall_rules.go
> +						"port": {
这个看下是不是可以定义为Int

2021-11-10 11:34 UTC, xinmu0426 commented on alicloud/resource_alicloud_simple_application_server_firewall_rule.go
> +				Required: true,
INt

2021-11-10 11:34 UTC, xinmu0426 commented on alicloud/resource_alicloud_simple_application_server_firewall_rule.go
> +	switch source {
提Aone了么

2021-11-11 01:49 UTC, super-eggs commented on alicloud/data_source_alicloud_simple_application_server_firewall_rules.go
> +						"port": {
> 这个看下是不是可以定义为Int

这里不能定义为 int，因为: 「端口的取值范围：1 ~ 65535。使用正斜线（/）隔开起始端口和终止端口，例如：`1024/1055` 表示端口范围1024 ~ 1055。」

2021-11-11 01:51 UTC, super-eggs commented on alicloud/resource_alicloud_simple_application_server_firewall_rule.go
> +				Required: true,
同上。存在 `1024/1055` 这种情况。

2021-11-11 02:02 UTC, super-eggs commented on alicloud/resource_alicloud_simple_application_server_firewall_rule.go
> +	switch source {
已经提了

2021-11-11 06:48 UTC, xiaozhu36 requested changes

2021-11-11 06:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_simple_application_server_firewall_rule.go
> +				Computed: true,
这个参数是在create或者 update中有么？

2021-11-11 09:45 UTC, merged