New Resource `alicloud_simple_application_server_snapshot` New Datasource `alicloud_simple_application_server_snapshots` New Datasource `alicloud_simple_application_server_disks`
aliyun/terraform-provider-alicloud pull request #4196
Opened 2021-11-10 07:12 UTC by super-eggs

New Resource `alicloud_simple_application_server_snapshot`
New Datasource `alicloud_simple_application_server_snapshots`
New Datasource `alicloud_simple_application_server_disks`

2021-11-10 11:41 UTC, xinmu0426 commented on alicloud/data_source_alicloud_simple_application_server_disks.go
> +			},
加一个disk_type

2021-11-10 11:41 UTC, xinmu0426 commented on alicloud/data_source_alicloud_simple_application_server_disks_test.go
> +	allConf := dataSourceTestAccConfig{
这块补一下测试条件

2021-11-10 11:41 UTC, xinmu0426 commented on alicloud/resource_alicloud_simple_application_server_snapshot_test.go
> +				Check: resource.ComposeTestCheckFunc(
这个没用的话去掉

2021-11-12 05:48 UTC, xiaozhu36 requested changes

2021-11-12 05:48 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_simple_application_server_disks_test.go
> +			"disks.#": CHECKSET,
不全，这个问题为啥每次都会有

2021-11-12 06:05 UTC, super-eggs commented on alicloud/data_source_alicloud_simple_application_server_disks_test.go
> +			"disks.#": CHECKSET,
> 不全，这个问题为啥每次都会有

disk 资源是只读资源，只是用来查询。不能确定有几个，所以没有检查其他属性。

2021-11-12 10:23 UTC, merged