New Resource alicloud_ecd_desktop  New Datasource alicloud_ecd_desktops
aliyun/terraform-provider-alicloud pull request #4199
Opened 2021-11-10 10:44 UTC by thisnihonglei

2021-11-11 07:17 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_desktop.go
> +			"tag_key": {
有tags, 这个不需要了, 删去

2021-11-11 07:17 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_desktop.go
> +			"tag_value": {
删去

2021-11-11 07:17 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_desktop.go
> +	if v, ok := d.GetOk("tag_key"); ok {
删去

2021-11-11 07:17 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_desktop.go
> +	if v, ok := d.GetOk("tag_key"); ok {
下同

2021-11-11 07:27 UTC, Wanghx0991 commented on website/docs/r/ecd_desktop.html.markdown
> +* `payment_type` - (Optional, Computed, ForceNew) The payment type of the Desktop. Valid values: `PayAsYouGo`, `Subscription`.
加**NOTE** 强调指出,用户如果不指定该字段, 所选的创建方式是什么, 我看默认是后付费

2021-11-11 07:27 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_desktop_test.go
> +				ImportStateVerify: true, ImportStateVerifyIgnore: []string{"root_disk_size_gib", "auto_renew", "period", "bundle_id", "user_assign_mode", "user_disk_size_gib", "host_name", "period_unit", "stoppe
import里的字段需要对比接口再确认下, 哪些没返回来,哪些返回没放进read方法里做Set
没有的给他开Aone

2021-11-11 07:27 UTC, Wanghx0991 commented on website/alicloud.erb
> +                            <a href="/docs/providers/alicloud/d/ecd_bundles.html">alicloud_ecd_bundles</a>
datasource另外提一个分支,这里记得删去

2021-11-11 07:40 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_desktop.go
> +	if d.HasChange("end_user_ids") {
我看创建里已经涉及了end_user_ids字段, 这里应该还是 !d.IsNewResource&& d.HasChange

2021-11-11 07:40 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_desktop.go
> +	stateConf := BuildStateConf([]string{}, []string{"Running"}, d.Timeout(schema.TimeoutCreate), 10*time.Second, ecdService.EcdDesktopStateRefreshFunc(d.Id(), []string{}))
创建里不用加异步等待, create完直接去调update,在update的最后一步加上这个

2021-11-11 07:40 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_desktop.go
> +		stateConf := BuildStateConf([]string{}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 5*time.Second, ecdService.EcdDesktopStateRefreshFunc(d.Id(), []string{}))
删去,统一加到最后

2021-11-11 07:40 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_desktop.go
> +		request = map[string]interface{}{
这里怎么又重新定义了Request, 那上一步塞进去的regionid, 不就重置了?

2021-11-11 07:46 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecd_desktop.go
> +			"payment_type": {
ModifyDesktopChargeType这个接口加一下,按量付费转换为包年包月, 改完ApiSpec同步一下

2021-11-12 01:56 UTC, thisnihonglei commented on alicloud/data_source_alicloud_ecd_desktops.go
> +			"enable_details": {
没有用到，已删

2021-11-12 02:32 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop.go
> +		request = map[string]interface{}{
改到regionid上面了。

2021-11-16 08:08 UTC, super-eggs commented on alicloud/data_source_alicloud_ecd_desktops_test.go
> +			"desktops.0.end_user_ids.#":       "1",
不全。差一个 payment_type

2021-11-16 08:24 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop.go
> +		stateConf := BuildStateConf([]string{"Updating"}, []string{"NoFlag"}, d.Timeout(schema.TimeoutUpdate), 10*time.Second, ecdService.EcdDesktopManagementFlagRefreshFunc(d.Id(), []string{}))
这个状态值是因为这个更新接口状态变更的时候是“变配中”，但是status中的状态并没有这个“变配中”，status中的“Running”并不是更改完成的终态，所以状态检查等待的时候需要用这个字段来确认是否变配完成，不然这个属性会有diff

2021-11-16 09:22 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop.go
> +		stateConf := BuildStateConf([]string{"Updating"}, []string{"NoFlag"}, d.Timeout(schema.TimeoutUpdate), 10*time.Second, ecdService.EcdDesktopManagementFlagRefreshFunc(d.Id(), []string{}))
这个状态值是因为这个更新接口状态变更的时候是“变配中”，但是status中的状态并没有这个“变配中”，status中的“Running”并不是更改完成的终态，所以状态检查等待的时候需要用这个字段来确认是否变配完成，不然DesktopType属性会有diff

2021-11-16 09:35 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop.go
> +			},
这个没有加是因为创建的时候，选择模板必填参数创建出来的系统是centos，而且AD工作区没办法创建（不是AD用户），host_name这个属性仅支持设置AD工作区下，操作系统类型是Windows的云桌面。

2021-11-17 08:28 UTC, xiaozhu36 requested changes

2021-11-17 08:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_desktop.go
> +				Optional: true,
desktop_id 是干啥的

2021-11-17 08:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_desktop.go
> +				Optional: true,
desktop_type 有枚举值么

2021-11-17 08:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_desktop.go
> +				Optional: true,
period 和 period_unit 都是只有在 Subscription 才有效，这种要增加 DiffSuppress

2021-11-17 08:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_desktop.go
> +			},
stopped_mode 有枚举值么？

2021-11-17 08:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_desktop.go
> +			},
user_assign_mode 有枚举值么？

2021-11-17 08:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_desktop.go
> +	wait := incrementalWait(3*time.Second, 3*time.Second)
457-463 有啥区别

2021-11-17 08:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_desktop_test.go
> +			{
参数没有覆盖全

2021-11-17 08:48 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop.go
> +				Optional: true,
有，已补上

2021-11-17 09:07 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop.go
> +			},
有，已补上

2021-11-17 09:10 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop.go
> +			},
有，已补上

2021-11-17 09:20 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop.go
> +	wait := incrementalWait(3*time.Second, 3*time.Second)
已删除

2021-11-17 09:20 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop.go
> +				Optional: true,
已删除

2021-11-17 10:15 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop_test.go
> +			{
host_name需要企业AD账号的创建的工作区，AD相关资源都没有接入，所以这个参数无法测试，其他的，补全了。

2021-11-17 10:36 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop_test.go
> +			{
payment_type，period，period_unit这些字段也没有覆盖，之前我写了两个测试，测试过创建是可以成功的，后面又删除掉这个测试的原因是：包年包月资源创建后，无法释放，而且删除的时候会去删除用户，工作区，策略，但是这些资源都因为云桌面没有删掉，也都删除报错了，所以删掉了创建包年包月的测试。

2021-11-18 02:01 UTC, xiaozhu36 requested changes

2021-11-18 02:01 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_desktop_test.go
> +}
测试case 不全，1. 没有覆盖所有的可修改的属性； 2. end_user_ids list 的测试应该包含多个值的情况

2021-11-18 02:32 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop.go
> +			request["EndUserId"] = v
有

2021-11-18 02:35 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop.go
> +				ValidateFunc: validation.StringInSlice([]string{"PayAsYouGo", "Subscription"}, false),
之前有过修改payment_type的接口，跑测试的时候，是能修改成功的，但是因为只支持按量付费单向转包年包月，所以如果改成了包年包月，删除接口无法释放，云桌面，用户，工作区，策略，模板，镜像这些资源就会报错。所以现在没有对应的update操作。

2021-11-18 02:36 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop_test.go
> +}
end_user_ids list已添加多个值

2021-11-18 06:29 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop_test.go
> +}
已新加payment_type，period，period_unit，auto_pay这些属性的测试case。

2021-11-18 07:54 UTC, xiaozhu36 requested changes

2021-11-18 07:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_desktop.go
> +		request["EndUserId"] = v
EndUserId 在API中的参数是 EndUserId.N 啊

2021-11-18 07:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_desktop.go
> +			request["EndUserId"] = v
你再仔细看下，在API中参数的格式 是 EndUserId.N，不是 EndUserId

2021-11-18 07:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_desktop_test.go
> +			},
既然已经转成预付费了，那么要测试下预付费实例的续费功能，比如 auto_renew

2021-11-18 07:54 UTC, xiaozhu36 commented on alicloud/service_alicloud_ecd.go
> +		"DesktopId": []string{id},
DesktopId.N

2021-11-18 08:23 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop_test.go
> +			},
已增加auto_renew测试case

2021-11-18 08:30 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop_test.go
> +			},
已增加auto_renew测试

2021-11-19 00:51 UTC, xiaozhu36 requested changes

2021-11-19 00:51 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecd_desktops.go
> +				ValidateFunc: validation.StringInSlice([]string{"Deleted", "Expired", "Pending", "Running", "Starting", "Stopped", "Stopping"}, false),
我看 DescribeDesktops 这个API的入参参数不止上面定义的这些啊

2021-11-19 00:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_desktop_test.go
> +
再添加一个case，要保证在创建的时候把create API中所有的参数都能覆盖，如果不能，那么通过添加多个case来覆盖

2021-11-19 02:24 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_desktop_test.go
> +
目前create API中除了host_name所有的参数都已覆盖，host_name不能覆盖的原因是host_name需要企业AD账号的创建的AD工作区，AD相关资源都没有接入，所以没有办法测试到这个参数。

2021-11-19 03:46 UTC, thisnihonglei commented on alicloud/data_source_alicloud_ecd_desktops.go
> +				ValidateFunc: validation.StringInSlice([]string{"Deleted", "Expired", "Pending", "Running", "Starting", "Stopped", "Stopping"}, false),
自动生成的时候少了一个EndUserId，已加

2021-11-19 13:38 UTC, merged