New Resource `alicloud_cloud_storage_gateway_gateway_cache_disk` New Datasource `alicloud_cloud_storage_gateway_gateway_cache_disks`
aliyun/terraform-provider-alicloud pull request #4217
Opened 2021-11-15 10:38 UTC by super-eggs

New Resource `alicloud_cloud_storage_gateway_gateway_cache_disk` 
New Datasource `alicloud_cloud_storage_gateway_gateway_cache_disks`

2021-11-16 02:23 UTC, xinmu0426 commented on alicloud/data_source_alicloud_cloud_storage_gateway_gateway_cache_disks_test.go
> +  cache_disk_size     = "50"
cache_disk_size     = 50

2021-11-16 02:23 UTC, xinmu0426 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway_cache_disk.go
> +	d.SetId(fmt.Sprint(request["GatewayId"], ":", task["RelatedResourceId"], ":", object["LocalFilePath"]))
这个提个aone，不能从DescribeTasks获取LocalFilePath

2021-11-16 02:23 UTC, xinmu0426 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway_cache_disk.go
> +				Required: true,
disks有取值范围

2021-11-16 02:23 UTC, xinmu0426 commented on website/docs/r/cloud_storage_gateway_gateway_cache_disk.html.markdown
> +  cache_disk_size     = "50"
cache_disk_size     = 50

2021-11-16 02:59 UTC, super-eggs commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway_cache_disk.go
> +	d.SetId(fmt.Sprint(request["GatewayId"], ":", task["RelatedResourceId"], ":", object["LocalFilePath"]))
已提 aone

2021-11-16 06:18 UTC, xiaozhu36 requested changes

2021-11-16 06:18 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cloud_storage_gateway_gateway_cache_disks_test.go
> +}
上面这两个资源，为啥用datasource，而不是直接创建新的

2021-11-16 06:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway_cache_disk.go
> +	request["CacheDiskSizeInGB"] = d.Get("cache_disk_size")
这个属性为啥不是 cache_disk_size_in_gb

2021-11-16 06:39 UTC, super-eggs commented on alicloud/resource_alicloud_cloud_storage_gateway_gateway_cache_disk.go
> +	request["CacheDiskSizeInGB"] = d.Get("cache_disk_size")
AMP平台初期录入时定义的为 cache_disk_size。已改正。

2021-11-16 06:48 UTC, super-eggs commented on alicloud/data_source_alicloud_cloud_storage_gateway_gateway_cache_disks_test.go
> +}
因为缺少查询可用区的API，导致无法创建新的 gateway，已经提aone了。所以采用查询的方式了。

2021-11-17 09:43 UTC, super-eggs commented on alicloud/data_source_alicloud_cloud_storage_gateway_gateway_cache_disks_test.go
> +}
已更新为创建新的 gateway 模式。

2021-11-17 09:49 UTC, merged