New Resource `alicloud_ecd_command` New Datasource `alicloud_ecd_commands`
aliyun/terraform-provider-alicloud pull request #4244
Opened 2021-11-22 09:20 UTC by thisnihonglei

2021-11-26 09:30 UTC, super-eggs commented on alicloud/resource_alicloud_ecd_command.go
> +				ForceNew: true,
去掉：ForceNew

2021-11-26 09:30 UTC, super-eggs commented on alicloud/resource_alicloud_ecd_command_test.go
> +					"desktop_id":      "${alicloud_ecd_desktop.default.id}",
加上 timeout、content_encoding

2021-11-26 09:30 UTC, super-eggs commented on alicloud/resource_alicloud_ecd_command_test.go
> +	"timeout":          NOSET,
"timeout": NOSET,  去掉

2021-11-26 09:30 UTC, super-eggs commented on alicloud/resource_alicloud_ecd_command.go
> +				Computed:     true,
为什么加 Computed？

2021-11-26 09:30 UTC, super-eggs commented on alicloud/resource_alicloud_ecd_command_test.go
> +	bundle_id 		= data.alicloud_ecd_bundles.default.bundles.12.id
为啥是 12 ？

2021-11-26 09:30 UTC, super-eggs commented on alicloud/data_source_alicloud_ecd_commands_test.go
> +			"command_type": `"RunPowerShellScript"`,
提 Aone 了吗？

2021-11-26 09:30 UTC, super-eggs commented on alicloud/data_source_alicloud_ecd_commands_test.go
> +			"commands.0.invoke_desktops.0.invocation_status": CHECKSET,
Success

2021-11-26 09:38 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_command.go
> +	if !d.IsNewResource() && d.HasChange("desktop_id") {
已删除

2021-11-26 09:39 UTC, thisnihonglei commented on alicloud/data_source_alicloud_ecd_commands_test.go
> +			"commands.0.command_type":                        CHECKSET,
已加

2021-11-26 09:39 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_command.go
> +				ForceNew: true,
已去掉

2021-11-26 09:42 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_command_test.go
> +					"desktop_id":      "${alicloud_ecd_desktop.default.id}",
已加

2021-11-26 09:42 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_command_test.go
> +	"timeout":          NOSET,
已去掉

2021-11-26 09:43 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_command.go
> +				Computed:     true,
已去掉

2021-11-26 09:44 UTC, thisnihonglei commented on alicloud/data_source_alicloud_ecd_commands_test.go
> +			"command_type": `"RunPowerShellScript"`,
这里是因为筛选条件command_type传给查询接口没有作用，还是会都返回。已提aone

2021-11-26 09:45 UTC, thisnihonglei commented on alicloud/data_source_alicloud_ecd_commands_test.go
> +			"commands.0.invoke_desktops.0.invocation_status": CHECKSET,
已改

2021-11-26 09:48 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_command_test.go
> +	bundle_id 		= data.alicloud_ecd_bundles.default.bundles.12.id
CommandType脚本类型取值为RunBatScript，RunPowerShellScript，所以需要创建Windows系统的云桌面。这里用模板id控制创建的云桌面的Windows系统的。已改为通过DataSource的name_regex来筛选Windows的模板。

2021-12-04 07:17 UTC, xiaozhu36 requested changes

2021-12-04 07:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecd_command_test.go
> +				ImportStateVerifyIgnore: []string{"timeout", "content_encoding"},
content_encoding 不返回的话，不要设置为forcenew

2021-12-04 08:26 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecd_command_test.go
> +				ImportStateVerifyIgnore: []string{"timeout", "content_encoding"},
已改

2021-12-04 11:20 UTC, merged