New Resource `alicloud_ros_stack_instance` New Datasource `alicloud_ros_stack_instances`
aliyun/terraform-provider-alicloud pull request #4258
Opened 2021-11-23 10:34 UTC by super-eggs

New Resource `alicloud_ros_stack_instance` 
New Datasource `alicloud_ros_stack_instances`

2021-11-24 11:58 UTC, xinmu0426 commented on alicloud/data_source_alicloud_ros_regions.go
> +		request["AcceptLanguage"] = v
这块固定一下吧，en-US

2021-11-24 11:58 UTC, xinmu0426 commented on alicloud/data_source_alicloud_ros_regions.go
> +		request["AcceptLanguage"] = v
这个API有没有region参数

2021-11-24 11:58 UTC, xinmu0426 commented on alicloud/data_source_alicloud_ros_stack_instances.go
> +		request["StackInstanceAccountId"] = v
Required 的话改掉

2021-11-24 11:58 UTC, xinmu0426 commented on alicloud/resource_alicloud_ros_stack_instance.go
> +				ForceNew: true,
正则？

2021-11-24 11:58 UTC, xinmu0426 commented on alicloud/resource_alicloud_ros_stack_instance.go
> +			request["OperationDescription"] = v
这块可能更新不到吧

2021-11-24 11:58 UTC, xinmu0426 commented on alicloud/resource_alicloud_ros_stack_instance_test.go
> +					"timeout_in_minutes": "60",
参数不反会有没有aone

2021-11-24 11:58 UTC, xinmu0426 commented on website/docs/d/ros_stack_instances.html.markdown
> +* `status` - (Optional, ForceNew) The status of the stack instance. Valid values: `CURRENT` or `OUTDATED`. `CURRENT`: The stack corresponding to the stack instance is up to date with the stack group.
枚举值解释加个字标签吧，下面的都改下

2021-11-25 02:11 UTC, super-eggs commented on alicloud/data_source_alicloud_ros_regions.go
> +		request["AcceptLanguage"] = v
> 

没有 region 参数

2021-11-25 02:11 UTC, super-eggs commented on alicloud/data_source_alicloud_ros_regions.go
> +		request["AcceptLanguage"] = v
没有 region 参数

2021-11-25 06:27 UTC, super-eggs commented on alicloud/resource_alicloud_ros_stack_instance_test.go
> +					"timeout_in_minutes": "60",
已提

2021-11-26 12:15 UTC, xiaozhu36 requested changes

2021-11-26 12:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ros_stack_instance.go
> +		"AccountIds":     fmt.Sprintf(`["%s"]`, parts[1]),
对于 List Json，我们通常用的都是 convertListToPortableJsonString

2021-11-27 06:24 UTC, merged