add new resource: resourceAlicloudRdsCloneDbInstance
aliyun/terraform-provider-alicloud pull request #4260
Opened 2021-11-24 03:35 UTC by zhaoguolong-sy2

2021-11-30 03:27 UTC, xinmu0426 commented on website/docs/r/rds_clone_db_instance.html.markdown
> +For information about RDS Clone DB Instance and how to use it, see [What is Clone DB Instance](https://help.aliyun.com/).
https://help.aliyun.com/改为国际站产品链接

2021-11-30 03:27 UTC, xinmu0426 commented on website/docs/r/rds_clone_db_instance.html.markdown
> +```terraform
146

2021-11-30 03:27 UTC, xinmu0426 commented on website/docs/r/rds_clone_db_instance.html.markdown
> +  instance_storage = "30"
给一个可用的模版，并且注意格式

2021-11-30 03:27 UTC, xinmu0426 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				ValidateFunc: validation.StringInSlice([]string{"Postpaid", "Prepaid"}, false),
统一为"PayAsYouGo", "Subscription",参考alicloud_lindorm_instance payment_type 字段

2021-11-30 03:27 UTC, xinmu0426 commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +	var instance map[string]interface{}
去掉无效的注释

2021-11-30 03:27 UTC, xinmu0426 commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +				ImportState:             true,
导入放在最后一步

2021-11-30 03:27 UTC, xinmu0426 commented on website/docs/r/rds_clone_db_instance.html.markdown
> +> This parameter indicates that cloud disk encryption is enabled (cannot be turned off after it is enabled), and **RoleARN** is required * *.
下面的格式检查下

2021-11-30 03:27 UTC, xinmu0426 commented on website/docs/r/rds_clone_db_instance.html.markdown
> +* `create` - (Defaults to 2 mins) Used when create the Clone DB Instance.
时间不对

2021-11-30 03:27 UTC, xinmu0426 commented on website/docs/r/rds_clone_db_instance.html.markdown
> +> The parameter **DBInstanceNetType** determines whether the address is internal or public.
格式不对

2021-11-30 12:53 UTC, xinmu0426 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				Type:         schema.TypeString,
period是不是只有当payment_type PayAsYouGo才生效

2021-11-30 12:53 UTC, xinmu0426 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +		request["VSwitchId"] = vswitchId
vpc id 暴露出来，不需要写成这样的

2021-11-30 12:53 UTC, xinmu0426 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +	d.Set("client_ca_cert", describeDBInstanceSSLObject["ClientCACert"])
int 统一转下 formInt

2021-11-30 12:53 UTC, xinmu0426 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +			return WrapError(err)
这块啥意思

2021-11-30 12:53 UTC, xinmu0426 commented on website/docs/r/rds_clone_db_instance.html.markdown
> +* `server_cert` - (Optional) This parameter is only supported by the RDS PostgreSQL cloud disk version. It indicates the content of the server certificate. If the CAType value is custom, this paramet
文档的属性对不上， (Optional)  ——》 			"server_cert": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},

2021-11-30 12:53 UTC, xinmu0426 commented on website/docs/r/rds_clone_db_instance.html.markdown
> +* `server_cert` - (Optional) This parameter is only supported by the RDS PostgreSQL cloud disk version. It indicates the content of the server certificate. If the CAType value is custom, this paramet
在检查下别的

2021-12-01 10:00 UTC, zhaoguolong-sy2 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +			return WrapError(err)
这是用于修改实例的配置参数的

2021-12-03 02:17 UTC, xinmu0426 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				Type:         schema.TypeString,
文档字段和Schema字段数量不对

2021-12-03 02:49 UTC, zhaoguolong-sy2 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				Type:         schema.TypeString,
已经修复这个问题

2021-12-04 02:19 UTC, xiaozhu36 requested changes

2021-12-04 02:19 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +	}
这个地方为啥要转换

2021-12-04 02:19 UTC, xiaozhu36 commented on website/docs/r/rds_clone_db_instance.html.markdown
> +subcategory: "RDS"
上面的那个 img.png 是什么

2021-12-04 02:19 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +			"pass_word": {
password

2021-12-04 02:19 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +}
这个地方要增加一个testcase，包含所有create的参数

2021-12-06 02:11 UTC, zhaoguolong-sy2 commented on website/docs/r/rds_clone_db_instance.html.markdown
> +subcategory: "RDS"
没有找到img.png

2021-12-06 02:12 UTC, zhaoguolong-sy2 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +			"pass_word": {
不是，就是pass_word

2021-12-06 02:40 UTC, zhaoguolong-sy2 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +	}
因为克隆资源和以前的resource_alicloud_db_instance是同一个资源，所以有些属性尽量保持一致

2021-12-06 06:40 UTC, xiaozhu36 requested changes

2021-12-06 06:40 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				Optional: true,
db_name 和 db_names 的区别是啥

2021-12-06 06:40 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				Default:  false,
这个默认值直接去掉就好了

2021-12-06 06:40 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +			"used_time": {
这个类型应该是 Int 啊

2021-12-06 06:40 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +		modifyDBInstanceDescriptionReq["DBInstanceDescription"] = v
如果是 DBInstanceDescription，那么参数应该定义为 db_instance_description，跟API保持一致就好了

2021-12-06 06:40 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +	}
instance_type 改成 db_instance_class，跟 API保持一致

2021-12-06 06:40 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +	}
instance_storage改成 db_instance_storage

2021-12-06 06:40 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +	}
老的资源不太规范，后面要进行优化，这个还是跟API的具体保持一致吧

2021-12-06 06:40 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +			modifyDBInstanceConnectionStringReq["ConnectionStringPrefix"] = strings.Split(d.Get("connection_string").(string), ".")[0]
这个地方我觉得没必要设置，客户传啥，设置啥

2021-12-06 06:40 UTC, xiaozhu36 commented on website/docs/r/rds_clone_db_instance.html.markdown
> +-> **NOTE:** Available in v1.146.0+.
下一个版本 1.147.0

2021-12-06 06:40 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +			"pass_word": {
password 本身就是一个单词，其他API中都是Password，这个地方就统一为 password

2021-12-06 09:03 UTC, zhaoguolong-sy2 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				Optional: true,
db_name是ModifyDBInstanceTDE这个api的一个可传字段，db_names是CloneDBInstance这个api的一个可传字段

2021-12-06 09:03 UTC, zhaoguolong-sy2 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +			"pass_word": {
好的，统一成password

2021-12-07 02:45 UTC, xiaozhu36 requested changes

2021-12-07 02:45 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				Optional: true,
这两个如果是同一个意思，只是数量上的不同，那么应该合并

2021-12-07 06:10 UTC, merged