resource/alicloud_common_bandwidth_package: Add optional parameter verification
aliyun/terraform-provider-alicloud pull request #4262
Opened 2021-11-24 07:19 UTC by thisnihonglei

2021-12-04 01:54 UTC, xiaozhu36 requested changes

2021-12-04 01:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_common_bandwidth_package_test.go
> +					"zone":                 "cn-hangzhou-h",
这个zone为啥是写死的

2021-12-04 01:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_common_bandwidth_package_test.go
> +func TestAccAlicloudCommonBandwidthPackage_basic2(t *testing.T) {
这个case跟上面的区别是啥

2021-12-09 02:28 UTC, thisnihonglei commented on alicloud/resource_alicloud_common_bandwidth_package_test.go
> +func TestAccAlicloudCommonBandwidthPackage_basic2(t *testing.T) {
覆盖了bandwidth_package_name参数

2021-12-09 02:28 UTC, thisnihonglei commented on alicloud/resource_alicloud_common_bandwidth_package_test.go
> +					"zone":                 "cn-hangzhou-h",
已改

2021-12-31 03:05 UTC, merged