resource/alicloud_nat_gateway: Add optional parameter verification
aliyun/terraform-provider-alicloud pull request #4272
Opened 2021-11-25 08:46 UTC by thisnihonglei

2021-12-03 03:41 UTC, xiaozhu36 requested changes

2021-12-03 03:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_nat_gateway.go
> +		if IsExpectedErrors(err, []string{"Forbidden.PrePaidNatGateway", "INSTANCE_NOT_EXISTS", "IncorrectStatus.NatGateway", "InvalidNatGatewayId.NotFound", "InvalidRegionId.NotFound"}) {
这个错误码不要增加，按照标准的预付费的删除逻辑写

2021-12-03 05:42 UTC, thisnihonglei commented on alicloud/resource_alicloud_nat_gateway.go
> +		if IsExpectedErrors(err, []string{"Forbidden.PrePaidNatGateway", "INSTANCE_NOT_EXISTS", "IncorrectStatus.NatGateway", "InvalidNatGatewayId.NotFound", "InvalidRegionId.NotFound"}) {
已去掉

2021-12-04 02:00 UTC, xiaozhu36 commented on alicloud/resource_alicloud_nat_gateway.go
> +		if IsExpectedErrors(err, []string{"Forbidden.PrePaidNatGateway", "INSTANCE_NOT_EXISTS", "IncorrectStatus.NatGateway", "InvalidNatGatewayId.NotFound", "InvalidRegionId.NotFound"}) {
光去掉不行，delete API中要增加对预付费的处理

2021-12-04 02:00 UTC, xiaozhu36 commented on alicloud/resource_alicloud_nat_gateway.go
> +		if IsExpectedErrors(err, []string{"Forbidden.PrePaidNatGateway", "INSTANCE_NOT_EXISTS", "IncorrectStatus.NatGateway", "InvalidNatGatewayId.NotFound", "InvalidRegionId.NotFound"}) {
并且在文档中要有说明

2021-12-09 03:47 UTC, thisnihonglei commented on alicloud/resource_alicloud_nat_gateway.go
> +		if IsExpectedErrors(err, []string{"Forbidden.PrePaidNatGateway", "INSTANCE_NOT_EXISTS", "IncorrectStatus.NatGateway", "InvalidNatGatewayId.NotFound", "InvalidRegionId.NotFound"}) {
已改

2021-12-31 03:07 UTC, xiaozhu36 requested changes

2021-12-31 03:07 UTC, xiaozhu36 commented on website/docs/r/nat_gateway.html.markdown
> +-> **NOTE:** `PrePaid` VPC NAT Gateway cannot be destroyed and provider will remove it from the state file.
这个写清楚，当 payment_type 是 Subscription 或者 instance_charge_type 是prepaid 的时候是这样

2022-01-04 02:23 UTC, thisnihonglei commented on website/docs/r/nat_gateway.html.markdown
> +-> **NOTE:** `PrePaid` VPC NAT Gateway cannot be destroyed and provider will remove it from the state file.
已改

2022-01-05 01:53 UTC, xiaozhu36 requested changes

2022-01-05 01:53 UTC, xiaozhu36 commented on website/docs/r/nat_gateway.html.markdown
> +-> **NOTE:** The value of this attribute `payment_type` is `Subscription` or `Prepaid`, the VPC NAT Gateway cannot be destroyed and provider will remove it from the state file.
改成如下的内容，并且把如下的内容放在 ## Attributes Reference 上方
“### Deleting `alicloud_nat_gateway` or  removing it from your configuration

The `alicloud_nat_gateway` resource allows you to manage `payment_type = "Subscription"` or `instance_charge_type = "Prepaid"` nat gateway, but Terraform cannot destroy it. 
Deleting the subscription resource or removing it from your configuration
will remove it from your statefile and management, but will not destroy the Nat Gateway.
You can resume managing the subscription nat gateway via the AlibabaCloud Console. “

2022-01-06 03:20 UTC, thisnihonglei commented on website/docs/r/nat_gateway.html.markdown
> +-> **NOTE:** The value of this attribute `payment_type` is `Subscription` or `Prepaid`, the VPC NAT Gateway cannot be destroyed and provider will remove it from the state file.
已改

2022-01-08 12:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4272) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4272) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=4272) it.</sub>

2022-01-08 14:58 UTC, merged