New Resource `alicloud_ecs_dedicated_host_cluster` New Datasource `alicloud_ecs_dedicated_host_clusters`
aliyun/terraform-provider-alicloud pull request #4275
Opened 2021-11-25 09:45 UTC by super-eggs

New Resource `alicloud_ecs_dedicated_host_cluster`
New Datasource `alicloud_ecs_dedicated_host_clusters`

2021-11-25 11:58 UTC, xinmu0426 commented on alicloud/data_source_alicloud_alb_security_policies.go
> +		request["SecurityPolicyIds"] = v
这个为啥要改

2021-11-25 11:58 UTC, xinmu0426 commented on alicloud/resource_alicloud_ecs_dedicated_host_cluster.go
> +				Default:  false,
默认值哪来的

2021-11-25 11:58 UTC, xinmu0426 commented on alicloud/resource_alicloud_ecs_dedicated_host_cluster.go
> +				Optional:     true,
参数都是选填么？

2021-11-25 11:58 UTC, xinmu0426 commented on alicloud/resource_alicloud_ecs_dedicated_host_cluster_test.go
> +func TestAccAlicloudECSDedicatedHostCluster_basic0(t *testing.T) {
sweeper呢

2021-11-26 02:44 UTC, super-eggs commented on alicloud/resource_alicloud_ecs_dedicated_host_cluster.go
> +				Default:  false,
文档中描述的

2021-11-26 02:45 UTC, super-eggs commented on alicloud/data_source_alicloud_alb_security_policies.go
> +		request["SecurityPolicyIds"] = v
这个错误是偶然发现的，属于一个潜在的bug，SecurityPolicyIds 不是 string 类型。

2021-11-26 03:15 UTC, super-eggs commented on alicloud/resource_alicloud_ecs_dedicated_host_cluster.go
> +				Optional:     true,
zone_id 不是选填，已更正。

2021-11-26 10:00 UTC, xiaozhu36 requested changes

2021-11-26 10:00 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecs_dedicated_host_clusters.go
> +													Type:     schema.TypeList,
这个地方不需要local_storage_capacity 这个字节点吧，为啥还要再包一层呢

2021-11-28 09:38 UTC, xiaozhu36 requested changes

2021-11-28 09:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_dedicated_host_cluster.go
> +	if !d.IsNewResource() && d.HasChange("tags") {
!d.IsNewResource() 应该不需要吧

2021-11-28 13:39 UTC, super-eggs commented on alicloud/resource_alicloud_ecs_dedicated_host_cluster.go
> +	if !d.IsNewResource() && d.HasChange("tags") {
不需要，已去掉

2021-12-02 07:01 UTC, merged