resource/alicloud_snat_entry: Add optional parameter verification
aliyun/terraform-provider-alicloud pull request #4276
Opened 2021-11-25 10:15 UTC by thisnihonglei

2021-12-04 02:10 UTC, xiaozhu36 requested changes

2021-12-04 02:10 UTC, xiaozhu36 commented on alicloud/resource_alicloud_snat_entry_test.go
> +			},
这两个参数都有返回啊

2021-12-09 02:50 UTC, thisnihonglei commented on alicloud/resource_alicloud_snat_entry_test.go
> +			},
Requestid:DD8F6026-28CB-52BD-9737-95C8C2AC44F0，我手动创建了一个调用查询接口试了一下，没有返回

2022-01-05 01:57 UTC, xiaozhu36 requested changes

2022-01-05 01:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_snat_entry_test.go
> +			},
不用看具体的值，就看API的response中有没有，如果有这个字段，但是返回值为空，那么给产品开aone

2022-01-07 13:27 UTC, merged