resource/alicloud_express_connect_physical_connection: Add optional parameter verification
aliyun/terraform-provider-alicloud pull request #4280
Opened 2021-11-26 06:30 UTC by thisnihonglei

2021-12-04 02:12 UTC, xiaozhu36 requested changes

2021-12-04 02:12 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_physical_connection.go
> +	//d.Set("circuit_code", object["CircuitCode"])
这个之前是返回的，都是测试过的，如果没有返回，找云产品

2021-12-09 09:28 UTC, thisnihonglei commented on alicloud/resource_alicloud_express_connect_physical_connection.go
> +	//d.Set("circuit_code", object["CircuitCode"])
产品回复这个参数是下单过程丢了，后续他们会修复这个问题。我已提aone

2022-01-05 01:55 UTC, xiaozhu36 requested changes

2022-01-05 01:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_physical_connection.go
> +	//d.Set("circuit_code", object["CircuitCode"])
那现在也不能注释掉，否则，当API修复了之后，terraform 还得改

2022-01-05 01:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_physical_connection_test.go
> +				ImportStateVerifyIgnore: []string{"circuit_code"},
这个也不需要 ignore

2022-01-06 08:53 UTC, thisnihonglei commented on alicloud/resource_alicloud_express_connect_physical_connection.go
> +	//d.Set("circuit_code", object["CircuitCode"])
已打开

2022-01-06 08:53 UTC, thisnihonglei commented on alicloud/resource_alicloud_express_connect_physical_connection_test.go
> +				ImportStateVerifyIgnore: []string{"circuit_code"},
已删除

2022-01-07 13:30 UTC, xiaozhu36 requested changes

2022-01-07 13:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_physical_connection_test.go
> +					"physical_connection_name":         "pc-2zed5mfcrcplrqpmju1vc",
这个name应该是上面定义的

2022-01-24 06:20 UTC, thisnihonglei commented on alicloud/resource_alicloud_express_connect_physical_connection_test.go
> +					"physical_connection_name":         "pc-2zed5mfcrcplrqpmju1vc",
done

2022-01-24 12:53 UTC, merged