resource/alicloud_ecs_dedicated_host: Add optional parameter verification
aliyun/terraform-provider-alicloud pull request #4291
Opened 2021-11-29 09:36 UTC by thisnihonglei

2022-01-05 01:58 UTC, xiaozhu36 requested changes

2022-01-05 01:58 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_dedicated_host.go
> +		if IsExpectedErrors(err, []string{"ChargeTypeViolation", "InvalidDedicatedHostId.NotFound"}) {
预付费的一样的处理逻辑

2022-01-05 01:58 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_dedicated_host_test.go
> +				ImportStateVerifyIgnore: []string{"auto_pay", "detail_fee", "dry_run", "auto_renew", "auto_renew_period", "expired_time"},
相比basic0，这个为啥有这么多ignore

2022-01-06 09:03 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecs_dedicated_host_test.go
> +				ImportStateVerifyIgnore: []string{"auto_pay", "detail_fee", "dry_run", "auto_renew", "auto_renew_period", "expired_time"},
basic0创建没用到auto_renew，auto_renew_period，expired_time这三个属性。这个用到了，然后跑单侧的时候发现不返回。我改了一下，basic0，1，2现在都统一了。不返回的用没用到都加在了ignore里

2022-01-06 09:17 UTC, thisnihonglei commented on alicloud/resource_alicloud_ecs_dedicated_host.go
> +		if IsExpectedErrors(err, []string{"ChargeTypeViolation", "InvalidDedicatedHostId.NotFound"}) {
已改

2022-01-07 13:32 UTC, merged