New Resource `alicloud_cddc_dedicated_host` New Datasource `alicloud_cddc_dedicated_hosts` New Datasource `alicloud_cddc_zones` New Datasource `alicloud_cddc_host_ecs_level_infos`
aliyun/terraform-provider-alicloud pull request #4297
Opened 2021-12-01 06:42 UTC by super-eggs

New Resource `alicloud_cddc_dedicated_host` 
New Datasource `alicloud_cddc_dedicated_hosts`
New Datasource `alicloud_cddc_zones`
New Datasource `alicloud_cddc_host_ecs_level_infos`

2021-12-02 03:24 UTC, xinmu0426 commented on alicloud/data_source_alicloud_cddc_dedicated_hosts_test.go
> +	allConf := dataSourceTestAccConfig{
tag呢

2021-12-02 03:24 UTC, xinmu0426 commented on alicloud/data_source_alicloud_cddc_dedicated_hosts_test.go
> +			"hosts.0.zone_id":                 CHECKSET,
少几个

2021-12-02 03:24 UTC, xinmu0426 commented on alicloud/data_source_alicloud_cddc_zones.go
> +
空格

2021-12-02 03:24 UTC, xinmu0426 commented on alicloud/resource_alicloud_cddc_dedicated_host.go
> +				ValidateFunc: validation.StringInSlice([]string{"1", "0"}, false),
这个和datasource不一致啊

2021-12-02 03:24 UTC, xinmu0426 commented on alicloud/resource_alicloud_cddc_dedicated_host.go
> +			"used_time": {
这个是不是应该是int

2021-12-02 03:24 UTC, xinmu0426 commented on website/docs/d/cddc_dedicated_hosts.html.markdown
> +* `status` - (Optional, ForceNew) The state of the host. Valid values: `0:` The host is being created. `1`: The host is running. `2`: The host is faulty. `3`: The host is ready for deactivation. `4`:
这个换行一下

2021-12-02 03:24 UTC, xinmu0426 commented on website/docs/d/cddc_host_ecs_level_infos.html.markdown
> +* `storage_type` - (Required, ForceNew) The storage type of the host. Valid values: `local_ssd`, `cloud_essd`, `cloud_essd2`, `cloud_essd3` . `local_ssd`: specifies that the host uses local SSDs. `cl
同上

2021-12-02 03:24 UTC, xinmu0426 commented on alicloud/resource_alicloud_cddc_dedicated_host.go
> +			Create: schema.DefaultTimeout(20 * time.Minute),
和文档对不上

2021-12-02 03:24 UTC, xinmu0426 commented on alicloud/resource_alicloud_cddc_dedicated_host.go
> +	case "Subscription":
去掉PayAsYouGo

2021-12-02 10:19 UTC, super-eggs commented on alicloud/resource_alicloud_cddc_dedicated_host.go
> +			"used_time": {
这个没有返回。入参文档定义的是string

2021-12-03 14:46 UTC, xiaozhu36 requested changes

2021-12-03 14:46 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cddc_dedicated_host.go
> +			"os_password": {
这个应该是sensitive

2021-12-03 14:46 UTC, xiaozhu36 commented on alicloud/service_alicloud_cddc.go
> +					if IsThrottling(err) {
为啥不是 NeedRetry

2021-12-03 14:46 UTC, xiaozhu36 commented on alicloud/service_alicloud_cddc.go
> +					if IsThrottling(err) {
这个也是

2021-12-05 04:24 UTC, xiaozhu36 requested changes

2021-12-05 04:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cddc_dedicated_host.go
> +				Required: true,
auto_renew 这个是必填的？

2021-12-05 04:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cddc_dedicated_host.go
> +				Optional:     true,
payment_type 这个参数是否必填跟OpenAPI 的不一致啊。
所有的参数都再检查一遍吧

2021-12-05 04:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cddc_dedicated_host_test.go
> +				ImportStateVerifyIgnore: []string{"image_category", "payment_type", "used_time", "period", "auto_renew", "os_password"},
对于不返回的参数，不能设置为 Forcenew

2021-12-05 04:24 UTC, xiaozhu36 commented on alicloud/service_alicloud_cddc.go
> +				if IsExpectedErrors(err, []string{Throttling}) {
这个没改

2021-12-06 02:58 UTC, super-eggs commented on alicloud/resource_alicloud_cddc_dedicated_host.go
> +				Required: true,
Api文档有调整，已更正。

2021-12-06 07:53 UTC, xiaozhu36 requested changes

2021-12-06 07:53 UTC, xiaozhu36 commented on website/docs/d/cddc_dedicated_host_groups.html.markdown
> +* `name_regex` - (Optional, ForceNew, Available in 1.146.0+) A regex string to filter results by Dedicated Host Group name.
1.147.0

2021-12-06 07:53 UTC, xiaozhu36 commented on website/docs/d/cddc_dedicated_hosts.html.markdown
> +-> **NOTE:** Available in v1.146.0+.
1.147.0

2021-12-07 06:11 UTC, merged