New Datasource `alicloud_emr_clusters`
aliyun/terraform-provider-alicloud pull request #4301
Opened 2021-12-02 02:47 UTC by thisnihonglei

2021-12-02 09:46 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_emr_clusters_test.go
> +
Status的过滤?

2021-12-02 09:46 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_emr_clusters.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
87行的校验值在这里加一下

2021-12-02 09:46 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_emr_clusters_test.go
> +  host_group {
host_group 留2个就行

2021-12-02 09:46 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_emr_clusters_test.go
> +// Ram role Resource for Module
注释去掉

2021-12-02 09:46 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_emr_clusters_test.go
> +			"clusters.0.host_group_list.#":                                "3",
host_group 留2个就行

2021-12-02 09:46 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_emr_clusters.go
> +										//"disk_name": disks["DiskName"],
schema里既然定义了,不该注调啊?

2021-12-02 09:46 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_emr_clusters.go
> +	d.SetId(dataResourceIdHash(ids))
host_pool_info字段Schema定义怎么没有了?

2021-12-02 09:46 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_emr_clusters.go
> +
relate_cluster_info,Schema定义,list里怎么没有?

2021-12-02 09:46 UTC, Wanghx0991 commented on website/docs/d/emr_clusters.html.markdown
> +* `cluster_name` - (Optional, ForceNew) The ClusterName.
cluster name

2021-12-02 09:46 UTC, Wanghx0991 commented on website/docs/d/emr_clusters.html.markdown
> +* `create_type` - (Optional, ForceNew) How to create a cluster. Valid values: `CreateType`, `MANUAL`.
create_type 校验值与Schema里定义的不一样

2021-12-02 09:46 UTC, Wanghx0991 commented on website/docs/d/emr_clusters.html.markdown
> +* `expired_tag_list` - (Optional, ForceNew) The expired tag list.
schema没有定义

2021-12-02 09:46 UTC, Wanghx0991 commented on website/docs/d/emr_clusters.html.markdown
> +* `machine_type` - (Optional, ForceNew) The host type of the cluster. The default is ECS. Valid values: `DOCKER`, `ECS`, `PYHSICAL_MACHINE`.
schema里定义了4个有效值

2021-12-02 09:46 UTC, Wanghx0991 commented on website/docs/d/emr_clusters.html.markdown
> +* `resource_group_id` - (Optional, ForceNew) The ResourceGroupId.
Resource Group Id

2021-12-02 09:46 UTC, Wanghx0991 commented on website/docs/d/emr_clusters.html.markdown
> +* `status_list` - (Optional, ForceNew) The status list.
Valid values: `ABNORMAL`, `CREATE_FAILED`, `CREATING`, `IDLE`, `RELEASED`, `RELEASE_FAILED`, `RELEASING`, `RUNNING`, `WAIT_FOR_PAY`.

2021-12-02 09:46 UTC, Wanghx0991 commented on website/docs/d/emr_clusters.html.markdown
> +	* `access_info` - Cluster connection information.
格式整体缩进注意下

2021-12-02 09:46 UTC, Wanghx0991 commented on website/docs/d/emr_clusters.html.markdown
> +	* `vpc_id` - VPC ID.
The VPC ID.

2021-12-02 09:46 UTC, Wanghx0991 commented on website/docs/d/emr_clusters.html.markdown
> +	* `period` - The package year and month time of the machine group (the number of package months is 1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 24, 36).
The Valid Values :  1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 24, 36

2021-12-02 09:57 UTC, thisnihonglei commented on alicloud/data_source_alicloud_emr_clusters_test.go
> +
已经有statuslist做过滤了，所以当时我没加，现在加上了。

2021-12-02 09:59 UTC, thisnihonglei commented on alicloud/data_source_alicloud_emr_clusters.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
已加

2021-12-02 10:00 UTC, thisnihonglei commented on alicloud/data_source_alicloud_emr_clusters_test.go
> +  host_group {
每一个houst_group的类型不一样，分别是TASK，CORE，MASTER所以是3个

2021-12-02 10:00 UTC, thisnihonglei commented on alicloud/data_source_alicloud_emr_clusters_test.go
> +// Ram role Resource for Module
已去掉

2021-12-02 10:00 UTC, thisnihonglei commented on alicloud/data_source_alicloud_emr_clusters_test.go
> +			"clusters.0.host_group_list.#":                                "3",
每一个houst_group的类型不一样，分别是TASK，CORE，MASTER所以是3个

2021-12-02 10:01 UTC, thisnihonglei commented on alicloud/data_source_alicloud_emr_clusters.go
> +										//"disk_name": disks["DiskName"],
当时注掉是因为接口不返回，后来忘了恢复了，而且这个已提aone

2021-12-02 10:10 UTC, thisnihonglei commented on alicloud/data_source_alicloud_emr_clusters.go
> +	d.SetId(dataResourceIdHash(ids))
自动生成没生成，我手动补上了。

2021-12-02 10:11 UTC, thisnihonglei commented on alicloud/data_source_alicloud_emr_clusters.go
> +
自动生成没生成，我手动补上了。relate_cluster_info不返回，已提aone

2021-12-02 10:11 UTC, thisnihonglei commented on alicloud/data_source_alicloud_emr_clusters.go
> +	d.SetId(dataResourceIdHash(ids))
host_pool_info接口不返回，已提aone

2021-12-02 10:12 UTC, thisnihonglei commented on website/docs/d/emr_clusters.html.markdown
> +* `cluster_name` - (Optional, ForceNew) The ClusterName.
改了

2021-12-02 10:13 UTC, thisnihonglei commented on website/docs/d/emr_clusters.html.markdown
> +* `create_type` - (Optional, ForceNew) How to create a cluster. Valid values: `CreateType`, `MANUAL`.
已改

2021-12-02 10:13 UTC, thisnihonglei commented on website/docs/d/emr_clusters.html.markdown
> +* `expired_tag_list` - (Optional, ForceNew) The expired tag list.
已删除

2021-12-02 10:14 UTC, thisnihonglei commented on website/docs/d/emr_clusters.html.markdown
> +* `machine_type` - (Optional, ForceNew) The host type of the cluster. The default is ECS. Valid values: `DOCKER`, `ECS`, `PYHSICAL_MACHINE`.
已加

2021-12-02 10:15 UTC, thisnihonglei commented on website/docs/d/emr_clusters.html.markdown
> +* `resource_group_id` - (Optional, ForceNew) The ResourceGroupId.
已改

2021-12-02 10:16 UTC, thisnihonglei commented on website/docs/d/emr_clusters.html.markdown
> +* `status_list` - (Optional, ForceNew) The status list.
已加

2021-12-02 10:17 UTC, thisnihonglei commented on website/docs/d/emr_clusters.html.markdown
> +	* `access_info` - Cluster connection information.
已注意

2021-12-02 10:17 UTC, thisnihonglei commented on website/docs/d/emr_clusters.html.markdown
> +	* `vpc_id` - VPC ID.
已改

2021-12-02 10:18 UTC, thisnihonglei commented on website/docs/d/emr_clusters.html.markdown
> +	* `period` - The package year and month time of the machine group (the number of package months is 1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 24, 36).
已改

2021-12-02 10:30 UTC, thisnihonglei commented on alicloud/data_source_alicloud_emr_clusters_test.go
> +
有StatusList的过滤了，所以没加

2021-12-02 10:36 UTC, thisnihonglei commented on alicloud/data_source_alicloud_emr_clusters_test.go
> +
status已删除

2021-12-02 12:00 UTC, xiaozhu36 requested changes

2021-12-02 12:00 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_emr_clusters_test.go
> +}
用 datasource 查

2021-12-03 03:02 UTC, thisnihonglei commented on alicloud/data_source_alicloud_emr_clusters_test.go
> +}
已改成用用 datasource 查

2021-12-03 06:45 UTC, merged