resource/alicloud_dts_synchronization_job: Improved Docs.
aliyun/terraform-provider-alicloud pull request #4311
Opened 2021-12-03 05:51 UTC by ChenHanZhang

2021-12-03 06:25 UTC, xiaozhu36 requested changes

2021-12-03 06:25 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_synchronization_job.go
> +				Required: true,
这个属于非兼容性变更

2021-12-03 06:25 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_synchronization_job.go
> +				ValidateFunc: validation.StringInSlice([]string{"AS400", "DB2", "DMSPOLARDB", "HBASE", "MONGODB", "MSSQL", "MySQL", "ORACLE", "PolarDB", "POLARDBX20", "POLARDB_O", "POSTGRESQL", "TERADATA"}, true
如果不区分大小写，那么需要增加测试

2021-12-03 07:20 UTC, ChenHanZhang commented on alicloud/resource_alicloud_dts_synchronization_job.go
> +				Required: true,
之前这个JobName会有一个默认值，在购买完实例之后就生成了，所以设成了Computed，但是重新校对了一下配置接口的文档，文档上是必填的

2021-12-03 08:22 UTC, ChenHanZhang commented on alicloud/resource_alicloud_dts_synchronization_job.go
> +				ValidateFunc: validation.StringInSlice([]string{"AS400", "DB2", "DMSPOLARDB", "HBASE", "MONGODB", "MSSQL", "MySQL", "ORACLE", "PolarDB", "POLARDBX20", "POLARDB_O", "POSTGRESQL", "TERADATA"}, true
创建同步实例（instance）：https://help.aliyun.com/document_detail/208270.htm； 配置同步任务（job）：https://help.aliyun.com/document_detail/208399.htm。这两个API上的同步类型枚举值（SourceEndpointInstanceType 、DestinationEndpointInstanceType）文档上是存在差异的，有的是大写有的小写，之前测试过MySQL大小写都可以

2021-12-04 01:36 UTC, xiaozhu36 requested changes

2021-12-04 01:36 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_synchronization_job.go
> +				Required: true,
那这个时候也不能改了，我们也在文档上标注为 Required 就行

2021-12-04 01:36 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_synchronization_job.go
> +				ValidateFunc: validation.StringInSlice([]string{"AS400", "DB2", "DMSPOLARDB", "HBASE", "MONGODB", "MSSQL", "MySQL", "ORACLE", "PolarDB", "POLARDBX20", "POLARDB_O", "POSTGRESQL", "TERADATA"}, true
大写的写大写，小写的写小写，对于两个都支持的，保持原样就行了

2021-12-04 07:12 UTC, merged