testcase: Adds a new test case for resource alicloud_instance
aliyun/terraform-provider-alicloud pull request #4329
Opened 2021-12-08 05:54 UTC by thisnihonglei

2022-01-05 02:08 UTC, xiaozhu36 requested changes

2022-01-05 02:08 UTC, xiaozhu36 commented on alicloud/resource_alicloud_instance_test.go
> +				ImportStateVerifyIgnore: []string{"security_enhancement_strategy", "system_disk_performance_level", "data_disks", "dry_run", "force_delete",
security_enhancement_strategy 和 system_disk_performance_level 如果没有返回，要开aone

2022-01-06 09:59 UTC, thisnihonglei commented on alicloud/resource_alicloud_instance_test.go
> +				ImportStateVerifyIgnore: []string{"security_enhancement_strategy", "system_disk_performance_level", "data_disks", "dry_run", "force_delete",
system_disk_performance_level是有返回的，我在security_enhancement_strategy在文档中没有找到该属性介绍，read方法里面也没有set这个属性

2022-01-24 06:40 UTC, thisnihonglei commented on alicloud/resource_alicloud_instance_test.go
> +				ImportStateVerifyIgnore: []string{"security_enhancement_strategy", "system_disk_performance_level", "data_disks", "dry_run", "force_delete",
done

2022-01-24 06:41 UTC, closed without merging