New Resource `alicloud_click_house_backup_policy` New Datasource `alicloud_click_house_backup_policies`
aliyun/terraform-provider-alicloud pull request #4341
Opened 2021-12-09 09:57 UTC by super-eggs

New Resource `alicloud_click_house_backup_policy`
New Datasource `alicloud_click_house_backup_policies`

2021-12-09 11:51 UTC, xinmu0426 commented on alicloud/connectivity/regions.go
> +var ClickHouseSupportRegions = []Region{Hangzhou, Qingdao, Beijing, Shenzhen, Hongkong, Shanghai, Zhangjiakou, Huhehaote, ChengDu, USWest1, USEast1, APSouthEast1, EUCentral1, EUWest1, APNorthEast1, A
这些region，从哪来的

2021-12-09 11:51 UTC, xinmu0426 commented on alicloud/data_source_alicloud_click_house_backup_policies_test.go
> +			"policies.0.preferred_backup_period.#": "2",
数量对不上

2021-12-09 11:51 UTC, xinmu0426 commented on alicloud/resource_alicloud_click_house_backup_policy.go
> +			},
这个是否有枚举值

2021-12-09 11:51 UTC, xinmu0426 commented on alicloud/resource_alicloud_click_house_backup_policy.go
> +	// There is a delay in creation, so need to wait 10 seconds.
这个是否提aone

2021-12-09 11:51 UTC, xinmu0426 commented on alicloud/resource_alicloud_click_house_backup_policy.go
> +	periodList := expandStringList(d.Get("preferred_backup_period").(*schema.Set).List())
这块做下异常判断

2021-12-09 11:51 UTC, xinmu0426 commented on website/docs/r/click_house_backup_policy.html.markdown
> +resource "alicloud_click_house_backup_policy" "example" {
给一个完整的例子

2021-12-09 11:51 UTC, xinmu0426 commented on website/docs/r/click_house_backup_policy.html.markdown
> +For information about Click House Backup Policy and how to use it, see [What is Backup Policy](https://www.alibabacloud.com/help/zh/doc-detail/360341.html).
换成英文文档

2021-12-10 01:58 UTC, super-eggs commented on website/docs/r/click_house_backup_policy.html.markdown
> +For information about Click House Backup Policy and how to use it, see [What is Backup Policy](https://www.alibabacloud.com/help/zh/doc-detail/360341.html).
这个暂时没有英文文档

2021-12-10 02:39 UTC, super-eggs commented on alicloud/connectivity/regions.go
> +var ClickHouseSupportRegions = []Region{Hangzhou, Qingdao, Beijing, Shenzhen, Hongkong, Shanghai, Zhangjiakou, Huhehaote, ChengDu, USWest1, USEast1, APSouthEast1, EUCentral1, EUWest1, APNorthEast1, A
根据 DescribeRegions 返回的可用区域。

2021-12-10 06:00 UTC, super-eggs commented on alicloud/resource_alicloud_click_house_backup_policy.go
> +	// There is a delay in creation, so need to wait 10 seconds.
已改成 用 Switch 作为 status 的判断，status 值 为true 时，表示创建成功，所以不再需要 Sleep 了。

2021-12-10 06:01 UTC, super-eggs commented on alicloud/resource_alicloud_click_house_backup_policy.go
> +			},
这里不可以使用 枚举值，因为这里要求传入一个 Set 类型的值。会存在 ["Monday", "Tuesday"] 多个日期的情况。

2021-12-10 06:22 UTC, xinmu0426 commented on alicloud/resource_alicloud_click_house_backup_policy.go
> +				//ValidateFunc: validation.StringInSlice([]string{"Friday", "Monday", "Saturday", "Sunday", "Thursday", "Tuesday", "Wednesday"}, false),
注释咋去掉了

2021-12-10 06:22 UTC, xinmu0426 commented on website/docs/d/click_house_backup_policies.html.markdown
> +		* `status` - The status of the resource.
结构不对

2021-12-10 09:37 UTC, xiaozhu36 requested changes

2021-12-10 09:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_click_house_backup_policy.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
这个应该是 TypeList 吧

2021-12-10 09:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_click_house_db_cluster.go
> -				request["ClientToken"] = buildClientToken("ModifyDBClusterAccessWhiteList")
这个为啥要删掉

2021-12-10 09:37 UTC, xiaozhu36 commented on website/docs/d/click_house_backup_policies.html.markdown
> +    Provides a list of Click House Backup Policies to the user.
这个格式不对

2021-12-10 10:04 UTC, super-eggs commented on alicloud/resource_alicloud_click_house_db_cluster.go
> -				request["ClientToken"] = buildClientToken("ModifyDBClusterAccessWhiteList")
这个个白名单的属性是我前段时间补的，今天偶然发现当时多写了个 ClientToken，Api 本身是没有这个入参的，就删除了。

2021-12-10 10:26 UTC, super-eggs commented on alicloud/resource_alicloud_click_house_backup_policy.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
这里的备份周期不应该是重复的，应该用 Set 更好吧。

2021-12-10 11:40 UTC, xiaozhu36 requested changes

2021-12-10 11:40 UTC, xiaozhu36 commented on alicloud/resource_alicloud_click_house_backup_policy.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
对于这种基本类型的，我们都统一用list，除非出参的顺序跟入参的不一致

2021-12-10 14:04 UTC, super-eggs commented on alicloud/resource_alicloud_click_house_backup_policy.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
师兄，我在测试之后还是觉得 Set 更合适，原因有2:

1. 创建备份时，备份周期如果设置成 [ "Tuesday","Monday"]，Get 查询返回的是 ["Monday", "Tuesday"]。满足出参的顺序跟入参的不一致条件。
2. 如果创建时为 ["Monday","Tuesday"]，后期用户修改为 [ "Tuesday","Monday"]，我认为不应该出发Update；但是如果配置成 List ，我测试发现是会触发 Update 的，这不符合逻辑，并且在更新后，报 diff 错误。

2021-12-11 03:16 UTC, xiaozhu36 approved these changes

2021-12-11 03:16 UTC, xiaozhu36 commented on alicloud/resource_alicloud_click_house_backup_policy.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
赞

2021-12-11 03:17 UTC, merged