New Datasource `alicloud_rds_backups`
aliyun/terraform-provider-alicloud pull request #4343
Opened 2021-12-10 03:51 UTC by zhaoguolong-sy2

2021-12-15 11:27 UTC, xinmu0426 commented on website/docs/d/rds_backups.html.markdown
> +	  * **System**: automatically initiated by the System
格式？

2021-12-15 11:27 UTC, xinmu0426 commented on website/docs/d/rds_backups.html.markdown
> +	* `backup_status` - Backup task status. **NOTE:** This parameter will only be returned when a task is executed. Value:
格式

2021-12-15 11:33 UTC, xinmu0426 commented on alicloud/data_source_alicloud_rds_backups_test.go
> +		existConfig: testAccCheckAlicloudRdsBackupsDataSourceName(rand, map[string]string{
查询数量不对

2021-12-15 11:33 UTC, xinmu0426 commented on alicloud/data_source_alicloud_rds_backups.go
> +			"id":                           fmt.Sprint(object["BackupId"]),
id 格式不对

2021-12-15 11:33 UTC, xinmu0426 commented on alicloud/data_source_alicloud_rds_backups.go
> +				if _, ok := idsMap[fmt.Sprint(item["BackupId"])]; !ok {
id 格式不对

2021-12-15 11:33 UTC, xinmu0426 commented on alicloud/resource_alicloud_rds_backup.go
> +			Create: schema.DefaultTimeout(20 * time.Minute),
和文档对不上

2021-12-15 11:33 UTC, xinmu0426 commented on alicloud/data_source_alicloud_rds_backups_test.go
> +			"backups.#": "1",
数量不对

2021-12-15 11:33 UTC, xinmu0426 commented on alicloud/data_source_alicloud_rds_backups_test.go
> +    engine = "MySQL"
格式化

2021-12-15 11:33 UTC, xinmu0426 commented on alicloud/resource_alicloud_rds_backup.go
> +	time.Sleep(1 * time.Minute)
为啥还要睡眠

2021-12-15 11:33 UTC, xinmu0426 commented on alicloud/resource_alicloud_rds_backup_test.go
> +	var v map[string]interface{}
补一个所有参数创建的例子

2021-12-15 11:33 UTC, xinmu0426 commented on alicloud/resource_alicloud_rds_backup_test.go
> +	engine_version = "5.6"
格式化

2021-12-15 11:54 UTC, zhaoguolong-sy2 commented on alicloud/resource_alicloud_rds_backup.go
> +	time.Sleep(1 * time.Minute)
是因为当查询备份任务的api，返回Finished，去查询列表接口，还是没有返回这个备份。估计是api那边有一定的延时，所以这块需要等待一分钟之后再走Read的查询

2021-12-15 12:01 UTC, zhaoguolong-sy2 commented on website/docs/d/rds_backups.html.markdown
> +	* `backup_status` - Backup task status. **NOTE:** This parameter will only be returned when a task is executed. Value:
这个是因为缩进两行，而不是四行吧

2021-12-15 12:02 UTC, zhaoguolong-sy2 commented on alicloud/data_source_alicloud_rds_backups_test.go
> +		existConfig: testAccCheckAlicloudRdsBackupsDataSourceName(rand, map[string]string{
这个是因为没有覆盖所有查询条件吗？还是查询出来的数量不是1

2021-12-15 12:09 UTC, zhaoguolong-sy2 commented on alicloud/data_source_alicloud_rds_backups.go
> +			"id":                           fmt.Sprint(object["BackupId"]),
这块我没有明白啥意思。是需要把resource中的id对应起来吗？

2021-12-15 12:19 UTC, xinmu0426 commented on alicloud/data_source_alicloud_rds_backups_test.go
> +		existConfig: testAccCheckAlicloudRdsBackupsDataSourceName(rand, map[string]string{
覆盖所有查询条件

2021-12-17 08:42 UTC, xiaozhu36 requested changes

2021-12-17 14:32 UTC, xiaozhu36 requested changes

2021-12-17 14:32 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_backup.go
> +			return Error("backup resource can not delete now")
`return WrapError(Error("the resource can not be deleted at this time and you can set remove_from_state to true to remove it."))`

2021-12-20 05:59 UTC, xiaozhu36 requested changes

2021-12-20 05:59 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_rds_backups_test.go
> +  default = "testbackup"
这个地方的name要用 tf-testAcc开头，用于后续集中清理残留的资源

2021-12-20 05:59 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_backup.go
> +	time.Sleep(1 * time.Minute)
如果非要等待，在这个地方增加上注释说明下吧

2021-12-20 06:47 UTC, xiaozhu36 requested changes

2021-12-20 06:47 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_backup.go
> +	stateConf := BuildStateConf([]string{}, []string{"Finished"}, d.Timeout(schema.TimeoutUpdate), 20*time.Second, rdsService.RdsBackupStateRefreshFunc(d.Get("db_instance_id").(string), response["Backup
这个地方应该是 schema.TimeoutCreate

2021-12-20 07:49 UTC, merged