New Resource `alicloud_mongodb_serverless_instance` New Datasource `alicloud_mongodb_serverless_instances`
aliyun/terraform-provider-alicloud pull request #4365
Opened 2021-12-14 10:27 UTC by super-eggs

New Resource `alicloud_mongodb_serverless_instance`
New Datasource `alicloud_mongodb_serverless_instances`

2021-12-15 04:00 UTC, xinmu0426 commented on alicloud/data_source_alicloud_mongodb_serverless_instances.go
> +			"expire_time": {
expire_time 和 expire 这两个字段可以去掉

2021-12-15 04:00 UTC, xinmu0426 commented on alicloud/data_source_alicloud_mongodb_serverless_instances_test.go
> +			"names.#": "0",
names 去掉

2021-12-15 04:00 UTC, xinmu0426 commented on alicloud/data_source_alicloud_mongodb_serverless_instances_test.go
> +		testAccPreCheck(t)
预付费加上一月测试一次

2021-12-15 04:00 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_serverless_instance.go
> +
空格

2021-12-15 04:00 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_serverless_instance.go
> +		request["AccountPassword"] = v
必填

2021-12-15 04:00 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_serverless_instance.go
> +		request["EngineVersion"] = v
必填

2021-12-15 04:00 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_serverless_instance_test.go
> +			testAccPreCheck(t)
预付费加上一月测试一次

2021-12-15 04:00 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_serverless_instance.go
> +	if !d.IsNewResource() && d.HasChange("db_instance_storage") && d.HasChange("capacity_unit") {
db_instance_storage 和 capacity_unit 之间的关系是啥

2021-12-15 04:00 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_serverless_instance_test.go
> +		CheckDestroy:  nil,
这个去掉就行

2021-12-15 04:00 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_serverless_instance.go
> +	log.Printf("[WARN] Cannot destroy resource Alicloud Resource Mongodb Server less Instance. Terraform will remove this resource from the state file, however resources may remain.")
Cannot destroy resource Alicloud Resource Mongodb Serverless Subscription Instance

2021-12-15 04:00 UTC, xinmu0426 commented on website/docs/d/mongodb_serverless_instances.html.markdown
> +subcategory: "Mongo DB"
MongoDB

2021-12-15 04:00 UTC, xinmu0426 commented on website/docs/d/mongodb_serverless_instances.html.markdown
> +      * `tag_value` - The value of the tags.
这两个去啊掉 tag_value  tag_value

2021-12-15 04:00 UTC, xinmu0426 commented on website/docs/d/mongodb_serverless_instances.html.markdown
> +  * `charge_type` - The Payment type of the instance.
和datasource 返回的数目对不上

2021-12-15 04:00 UTC, xinmu0426 commented on website/docs/r/mongodb_serverless_instance.html.markdown
> +subcategory: "Mongo DB"
MongoDB

2021-12-15 04:00 UTC, xinmu0426 commented on website/docs/r/mongodb_serverless_instance.html.markdown
> +* `account_password` - (Optional, ForceNew) The password of the database logon account.
定义和resource中对不上

2021-12-15 06:28 UTC, super-eggs commented on alicloud/resource_alicloud_mongodb_serverless_instance.go
> +	if !d.IsNewResource() && d.HasChange("db_instance_storage") && d.HasChange("capacity_unit") {
正确的逻辑是：更新的时候，两者中至少配置一项。已更正。

2021-12-16 09:44 UTC, xiaozhu36 requested changes

2021-12-16 09:44 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_mongodb_serverless_instances.go
> +	request["DBInstanceType"] = "serverless"
这个是参数为啥写死

2021-12-16 09:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_serverless_instance.go
> +	}
这个资源没有paymentType 这个属性么

2021-12-16 09:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_serverless_instance_test.go
> +					"period_price_type":       "Month",
这个能否换成 Day

2021-12-16 09:58 UTC, super-eggs commented on alicloud/resource_alicloud_mongodb_serverless_instance.go
> +	}
没有paymentType属性，这个资源只支持预付费。

2021-12-16 10:00 UTC, super-eggs commented on alicloud/data_source_alicloud_mongodb_serverless_instances.go
> +	request["DBInstanceType"] = "serverless"
因为 DBInstanceDescription 是 副本集实例，分片集群实例，Serverless 实例共用的查询方法。这里 作为常量入参，只能传 `serverless `.

2021-12-16 10:05 UTC, super-eggs commented on alicloud/resource_alicloud_mongodb_serverless_instance_test.go
> +					"period_price_type":       "Month",
可以的，已更改成了Day。

2021-12-17 06:55 UTC, xiaozhu36 requested changes

2021-12-17 06:55 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_mongodb_serverless_instances.go
> +							Type:     schema.TypeSet,
这个应该是typeList 吧

2021-12-17 06:55 UTC, xiaozhu36 commented on website/docs/r/mongodb_serverless_instance.html.markdown
> +* `status` - The instance status. For more information, see the instance Status Table. Valid values: `Creating`, `DBInstanceClassChanging`, `DBInstanceNetTypeChanging`, `Deleting`, `EngineVersionUpgr
如果是在出参中，这个地方没必要把值都列出来

2021-12-17 08:13 UTC, super-eggs commented on alicloud/data_source_alicloud_mongodb_serverless_instances.go
> +							Type:     schema.TypeSet,
这个定义成 `TypeSet` 类型可以方便在 `update` 中，使用求集合差集的函数 `Difference` 来进行部分更新。
```
oraw, nraw := d.GetChange("security_ip_groups")
remove := oraw.(*schema.Set).Difference(nraw.(*schema.Set)).List()
create := nraw.(*schema.Set).Difference(oraw.(*schema.Set)).List()
```

并且，定义白名单组，并不允许重复。

2021-12-17 10:10 UTC, xiaozhu36 requested changes

2021-12-17 10:10 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_mongodb_serverless_instances_test.go
> +  zone_id = data.alicloud_mongodb_zones.default.zones.0.id
这个地方要换成，如果通过datasource查不到，那么要创建一个新的vswitch

2021-12-17 11:13 UTC, merged