New Resource `alicloud_mongodb_audit_policy` New Datasource `alicloud_mongodb_audit_policies`
aliyun/terraform-provider-alicloud pull request #4368
Opened 2021-12-15 10:32 UTC by super-eggs

New Resource `alicloud_mongodb_audit_policy`
New Datasource `alicloud_mongodb_audit_policies`

2021-12-15 11:37 UTC, xinmu0426 commented on alicloud/connectivity/regions.go
> +
空格

2021-12-15 11:37 UTC, xinmu0426 commented on alicloud/data_source_alicloud_mongodb_audit_policies.go
> +		if IsExpectedErrors(err, []string{"InvalidDBInstanceId.NotFound"}) || NotFoundError(err) {
InvalidDBInstanceId.NotFound" 不需要重试

2021-12-15 11:37 UTC, xinmu0426 commented on alicloud/data_source_alicloud_mongodb_audit_policies.go
> +			d.SetId("MongodbAuditPolicy")
d.SetId("")

2021-12-16 10:02 UTC, xiaozhu36 requested changes

2021-12-16 10:02 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_audit_policy.go
> +			"status": {
这个应该是 audit_status

2021-12-16 10:02 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_mongodb_audit_policies.go
> +			return nil
上面的review没有改完

2021-12-16 10:39 UTC, super-eggs commented on alicloud/data_source_alicloud_mongodb_audit_policies.go
> +			d.SetId("MongodbAuditPolicy")
如果没有查到的话，需要配置一个 id，否则会报错。

2021-12-16 10:41 UTC, super-eggs commented on alicloud/data_source_alicloud_mongodb_audit_policies.go
> +			return nil
IsExpectedErrors（） 已去除。   data_source 如果查不到的话，也需要配置一个id，否则会报错。

2021-12-17 06:58 UTC, merged