CS kubernetes nodepool support deploymentSet
aliyun/terraform-provider-alicloud pull request #4371
Opened 2021-12-16 07:08 UTC by saberrey

2021-12-16 07:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4371) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4371) before we can accept your contribution.<br/><hr/>**yuejiarui.yjr** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=4371) it.</sub>

2021-12-20 07:51 UTC, xiaozhu36 requested changes

2021-12-20 07:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +			"deploymentset_id": {
这个参数应该改为 deployment_set_id

2021-12-20 07:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
> +  deployment_set_name = "nodepool_deployment_set"
name的值应该使用 var.name

2021-12-20 07:51 UTC, xiaozhu36 commented on website/docs/r/cs_kubernetes_node_pool.html.markdown
> +-> **NOTE:** From version 1.148.0, support for specifying deploymentSet for node pools.
148已经发布了，下个版本是 1.149.0

2021-12-21 03:03 UTC, saberrey commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +			"deploymentset_id": {
done

2021-12-21 03:03 UTC, saberrey commented on alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
> +  deployment_set_name = "nodepool_deployment_set"
done

2021-12-21 03:03 UTC, saberrey commented on website/docs/r/cs_kubernetes_node_pool.html.markdown
> +-> **NOTE:** From version 1.148.0, support for specifying deploymentSet for node pools.
done

2021-12-22 06:15 UTC, merged