resource/alicloud_pvtz_zone: Support  update sync_status without user_info
aliyun/terraform-provider-alicloud pull request #4372
Opened 2021-12-16 07:27 UTC by Wanghx0991

2021-12-16 08:29 UTC, Wanghx0991 commented on alicloud/resource_alicloud_pvtz_zone.go
> +		if _, ok := d.GetOk("user_info"); !ok {
客户提出应该与控制台功能保持一致, 配置同步任务变更, 应该自动更改, 所以需要查询一次

2021-12-16 08:29 UTC, Wanghx0991 commented on alicloud/resource_alicloud_pvtz_zone.go
> -							Type:     schema.TypeList,
客户做plan的时候发现了diff

2021-12-16 10:03 UTC, xiaozhu36 requested changes

2021-12-16 10:03 UTC, xiaozhu36 commented on alicloud/resource_alicloud_pvtz_zone.go
> -							Type:     schema.TypeList,
这个地方要打包测试下，看下List 和Set 是否相互兼容，我印象中是兼容的

2021-12-17 07:15 UTC, xiaozhu36 requested changes

2021-12-17 07:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_pvtz_zone.go
> +				}
这个报错为啥要直接返回 nil 了

2021-12-17 07:24 UTC, Wanghx0991 commented on alicloud/resource_alicloud_pvtz_zone.go
> +				}
这块还是因为之前说的,控制台通过status管理同步任务, 但接口status,user_info这两个字段都应该是必填项, pvtz的做法是前端查出来自己填进去带给后端,这时会有几个情况:
1. 用户创建资源未配置同步任务
2. 用户创建资源没有配置同步任务, 但status置位了关闭状态(此时会有报错, 是预期中的错误)

2021-12-17 08:09 UTC, merged