testcase: Change vpc and vswitch creation to read
aliyun/terraform-provider-alicloud pull request #4387
Opened 2021-12-20 09:00 UTC by thisnihonglei

2021-12-20 09:07 UTC, thisnihonglei commented on alicloud/resource_alicloud_ssl_vpn_client_cert_test.go
> +	instance_charge_type = "PrePaid"
这里修改这个字段为预付费的原因是查看了当前资源的文档，这个资源现在只支持预付费类型，没有后付费了。

2021-12-20 09:07 UTC, thisnihonglei commented on alicloud/resource_alicloud_vpn_gateway.go
> +		if IsExpectedErrors(err, []string{"InvalidVpnGatewayInstanceId.NotFound", "ForbiddenRelease"}) {
改为预付费后，删除资源时抛出errcode:ForbiddenRelease，所以在这里做预知错误处理

2021-12-20 09:08 UTC, thisnihonglei commented on alicloud/resource_alicloud_ssl_vpn_client_cert_test.go
> +	instance_charge_type = "PrePaid"
这里修改这个字段为预付费的原因是查看了当前资源的文档以及去控制台手动创建测试，发现这个资源现在只支持预付费类型.

2021-12-22 06:44 UTC, xiaozhu36 requested changes

2021-12-22 06:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ssl_vpn_client_cert_test.go
> +		CheckDestroy:  nil,
这两个case是只有国际站的账号才能创建，你是怎么测试的

2021-12-22 06:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpn_gateway.go
> +		if IsExpectedErrors(err, []string{"InvalidVpnGatewayInstanceId.NotFound", "ForbiddenRelease"}) {
ForbiddenRelease 是代表这个资源已经不存在了么

2021-12-22 06:48 UTC, thisnihonglei commented on alicloud/resource_alicloud_vpn_gateway.go
> +		if IsExpectedErrors(err, []string{"InvalidVpnGatewayInstanceId.NotFound", "ForbiddenRelease"}) {
不是，报错信息是：Forbidden to release a prepaid instance within validity period，有效期内无法删除实例

2021-12-24 02:26 UTC, xiaozhu36 requested changes

2021-12-24 02:26 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpn_gateway.go
> +	return nil
对于预付费的要改成这种，对于后付费的，还是应该保留原有的逻辑

2021-12-24 03:02 UTC, xiaozhu36 requested changes

2021-12-24 03:02 UTC, xiaozhu36 commented on website/docs/r/vpn_gateway.html.markdown
> +-> **NOTE:** The resource Cannot destroy. Terraform will remove this resource from the state file, however resources may remain.
要说清楚，只有是预付费的时候才不能删除，

2021-12-24 06:07 UTC, xiaozhu36 requested changes

2021-12-24 06:07 UTC, xiaozhu36 commented on website/docs/r/vpn_gateway.html.markdown
> +-> **NOTE:** If the resource is `PerPaid` type the resource Cannot destroy. Terraform will remove this resource from the state file, however resources may remain.
-> **NOTE:** `PrePaid` VPN gateway cannot  be destroyed and provider will remove it from the state file.

2021-12-28 01:44 UTC, xiaozhu36 requested changes

2021-12-28 01:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ssl_vpn_client_cert_test.go
> +		CheckDestroy:  nil,
如果你的账号可以测试成功，那么这个case就不受账号类型的限制了

2021-12-28 01:53 UTC, thisnihonglei commented on alicloud/resource_alicloud_ssl_vpn_client_cert_test.go
> +		CheckDestroy:  nil,
已去掉

2022-01-05 02:24 UTC, xiaozhu36 requested changes

2022-01-05 02:24 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_vpn_gateways_test.go
> -		testAccPreCheckWithAccountSiteType(t, IntlSite)
后付费的case还是应该保留

2022-01-05 02:24 UTC, xiaozhu36 commented on website/docs/r/vpn_gateway.html.markdown
> +-> **NOTE:** `PrePaid` VPN gateway cannot be destroyed and provider will remove it from the state file.
这个描述跟 nat gateway 的那个保持一致

2022-01-07 06:15 UTC, thisnihonglei commented on website/docs/r/vpn_gateway.html.markdown
> +-> **NOTE:** `PrePaid` VPN gateway cannot be destroyed and provider will remove it from the state file.
已改

2022-01-07 06:15 UTC, thisnihonglei commented on alicloud/data_source_alicloud_vpn_gateways_test.go
> -		testAccPreCheckWithAccountSiteType(t, IntlSite)
已改

2022-01-07 13:24 UTC, merged