New Resource alicloud_cr_chart_namespace New Datasource alicloud_cr_chart_namespaces
aliyun/terraform-provider-alicloud pull request #4391
Opened 2021-12-20 11:56 UTC by Wanghx0991

2021-12-20 14:56 UTC, xiaozhu36 requested changes

2021-12-20 14:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_chart_namespace.go
> +	d.SetId(fmt.Sprint(request["NamespaceName"], ":", request["InstanceId"]))
这个ID应该是 InstanceId：NamespaceName 吧

2021-12-20 14:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_chart_namespace_test.go
> +
单测的呢

2021-12-20 14:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_chart_namespace_test.go
> +	instance_type       = "Advanced"
这个instance先用 datasource查，如果查不到，在创建新的

2021-12-20 14:56 UTC, xiaozhu36 commented on website/alicloud.erb
> +                  <a href="#">CR</a>
这个类目应该是 Container Registry (CR)

2021-12-21 05:07 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chart_namespace_test.go
> +	instance_type       = "Advanced"
Done

2021-12-21 05:07 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chart_namespace_test.go
> +
96.2%

2021-12-21 06:13 UTC, merged