New Resource alicloud_cr_chart_repository;New Datasource alicloud_cr_chart_repositories
aliyun/terraform-provider-alicloud pull request #4393
Opened 2021-12-21 09:22 UTC by Wanghx0991

2021-12-21 11:25 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chart_repository_test.go
> +func TestAccAlicloudCRChartRepository_unit(t *testing.T) {
单测96.2%覆盖率

2021-12-22 06:48 UTC, xiaozhu36 requested changes

2021-12-22 06:48 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cr_chart_repositories_test.go
> +	default = "tftest%d"
这个name 不对吧

2021-12-22 06:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_chart_repository.go
> +			"repo_type": {
这个有枚举值么

2021-12-22 08:30 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chart_namespace.go
> -	err = resource.Retry(1*time.Second, func() *resource.RetryError {
Mock超时未及时删除

2021-12-22 08:30 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chart_repository.go
> +			"repo_type": {
Spec没有录, 已经同步更新了

2021-12-23 07:39 UTC, Wanghx0991 commented on website/docs/r/cloud_storage_gateway_gateway.html.markdown
> +* `gateway_name` - (Required) the name of gateway.
字段一致性校验卡主了, schema里一直是必填

2021-12-23 07:39 UTC, Wanghx0991 commented on website/docs/r/mongodb_sharding_instance.html.markdown
> +* `tags` - (Optional) A mapping of tags to assign to the resource.
字段一致性校验卡主了, schema里tags一直没对外透出

2021-12-23 07:39 UTC, Wanghx0991 commented on website/docs/r/sddp_config.html.markdown
> +* `lang` - (Optional) The language of the request and response. Valid values: `zh`,`en`.
字段一致性校验卡主了, schema里lang一直没对外透出

2021-12-23 08:10 UTC, xiaozhu36 requested changes

2021-12-23 08:10 UTC, xiaozhu36 commented on alicloud/provider.go
> -			"alicloud_rds_clone_db_instance":              resourceAlicloudRdsCloneDbInstance(),
这个为啥要删掉

2021-12-23 08:10 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
> +			replicaSets = append(replicaSets, dds.CreateShardingDBInstanceReplicaSet{ReadonlyReplicas: strconv.Itoa(readonlyReplicas), Storage: strconv.Itoa(nodeStorage), Class: class})
这种修改，你都测了么

2021-12-23 13:17 UTC, Wanghx0991 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
> +			replicaSets = append(replicaSets, dds.CreateShardingDBInstanceReplicaSet{ReadonlyReplicas: strconv.Itoa(readonlyReplicas), Storage: strconv.Itoa(nodeStorage), Class: class})
跑了一下OK的

2021-12-23 13:21 UTC, merged