resource/alicloud_amqp_instance: fix the product_type checkout between domestic account and international account
aliyun/terraform-provider-alicloud pull request #4396
Opened 2021-12-22 04:02 UTC by Wanghx0991

2021-12-22 07:11 UTC, Wanghx0991 commented on website/docs/r/actiontrail.html.markdown
> --> **DEPRECATED:**  This resource has been renamed to [alicloud_actiontrail_trail](https://www.terraform.io/docs/providers/alicloud/r/actiontrail_trail.html) from version 1.95.0.
原有链接失效了

2021-12-22 07:11 UTC, Wanghx0991 commented on website/docs/r/ga_accelerator.html.markdown
> +-> **NOTE:** At present, The `alicloud_ga_accelerator` cannot be deleted. you need to wait until the resource is outdated and released automatically.
展示格式有问题,

2021-12-22 11:04 UTC, xiaozhu36 requested changes

2021-12-22 11:04 UTC, xiaozhu36 commented on alicloud/service_alicloud_bss_open_api.go
> +func (s *BssOpenApiService) QueryAvailableInstances(id, productCode, productType, productType_intl string) (object map[string]interface{}, err error) {
productTypeIntl

2021-12-23 13:23 UTC, xiaozhu36 requested changes

2021-12-23 13:23 UTC, xiaozhu36 commented on alicloud/service_alicloud_bss_open_api.go
> +				request["ProductType"] = productTypeIntl
这个地方，加个productTypeIntl的判空逻辑

2021-12-24 02:20 UTC, closed without merging