New Resource `alicloud_mongodb_sharding_network_public_address`; New Datasource `alicloud_mongodb_sharding_network_addresses`
aliyun/terraform-provider-alicloud pull request #4397
Opened 2021-12-22 06:16 UTC by super-eggs

New Resource `alicloud_mongodb_sharding_network_public_address`
New Datasource `alicloud_mongodb_sharding_network_addresses`

2021-12-22 08:47 UTC, xinmu0426 commented on alicloud/data_source_alicloud_mongodb_sharding_network_addresses.go
> +			mapping["node_id"] = v
这个开aone没

2021-12-22 08:47 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_sharding_network_public_address.go
> +	time.Sleep(5 * time.Minute)
这个配置为timeout

2021-12-23 02:06 UTC, super-eggs commented on alicloud/data_source_alicloud_mongodb_sharding_network_addresses.go
> +			mapping["node_id"] = v
提了 Aone 了。

2021-12-23 02:58 UTC, xiaozhu36 requested changes

2021-12-23 02:58 UTC, xiaozhu36 commented on alicloud/provider.go
> +			"alicloud_mongodb_sharding_network_addresses":          dataSourceAlicloudMongodbShardingNetworkAddresses(),
这个datasource跟resource对应上

2021-12-23 02:58 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_network_public_address.go
> +			},
networkAddress 的信息也要展示出来

2021-12-23 02:58 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_network_public_address.go
> +	time.Sleep(d.Timeout(schema.TimeoutCreate))
为啥 sleep

2021-12-23 02:58 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_network_public_address.go
> +	time.Sleep(d.Timeout(schema.TimeoutDelete))
为啥sleep

2021-12-23 03:07 UTC, super-eggs commented on alicloud/provider.go
> +			"alicloud_mongodb_sharding_network_addresses":          dataSourceAlicloudMongodbShardingNetworkAddresses(),
resource 是只针对分片集群实例的公网连接地址资源，而 datasource 是分片集群实例的公网连接地址资源和内网连接地址资源通用的。所以就区分了命名。

2021-12-23 03:10 UTC, super-eggs commented on alicloud/resource_alicloud_mongodb_sharding_network_public_address.go
> +	time.Sleep(d.Timeout(schema.TimeoutCreate))
调用 AllocatePublicNetworkAddress 接口为 MongoDB 实例申请公网连接地址时，如果NodeId 传入的为 Mongos节点ID，则会改变对应父级实例的状态，但是如果NodeId 传入为 Shard 节点 ID 或 ConfigServer 节点 ID 时，则只会改变对应 Node 子实例节点的状态，对应父级实例的状态值不变。
因为 AllocatePublicNetworkAddress 接口为异步调用，所以目前无法实现统一的状态判断。
这个已提Aone。

2021-12-23 03:11 UTC, super-eggs commented on alicloud/resource_alicloud_mongodb_sharding_network_public_address.go
> +	time.Sleep(d.Timeout(schema.TimeoutDelete))
同上。删除接口也是如此。

2021-12-23 07:01 UTC, xiaozhu36 requested changes

2021-12-23 07:01 UTC, xiaozhu36 commented on alicloud/provider.go
> +			"alicloud_mongodb_sharding_network_addresses":          dataSourceAlicloudMongodbShardingNetworkAddresses(),
那也要分开

2021-12-23 07:01 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_network_public_address.go
> +	time.Sleep(d.Timeout(schema.TimeoutCreate))
那就分情况根据不同的状态进行判断

2021-12-23 13:27 UTC, xiaozhu36 requested changes

2021-12-23 13:27 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_mongodb_sharding_network_public_addresses.go
> +				ValidateFunc: validation.StringInSlice([]string{"VPC", "Classic", "Public"}, false),
对于这个应该不需要指定 network_type 吧

2021-12-24 02:04 UTC, super-eggs commented on alicloud/data_source_alicloud_mongodb_sharding_network_public_addresses.go
> +				ValidateFunc: validation.StringInSlice([]string{"VPC", "Classic", "Public"}, false),
已去除；变成默认只查询公网类型的连接地址信息；

2021-12-24 10:27 UTC, merged