alicloud_ess_scalingconfiguration: Adds new attributes spot_strategy and spot_price_limit
aliyun/terraform-provider-alicloud pull request #4413
Opened 2021-12-25 09:48 UTC by TalentNing

=== RUN   TestAccAlicloudEssScalingconfigurationsDataSource
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource (81.92s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  83.627s

=== RUN   TestAccAlicloudEssScalingconfigurationsDataSource
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource (83.38s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  85.091s

2021-12-25 09:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4413) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4413) before we can accept your contribution.<br/><hr/>**tongkn** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=4413) it.</sub>

2021-12-30 07:47 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ess_scaling_configuration_test.go
> +			},
需要增加一个Update的测试步

2022-01-05 04:06 UTC, TalentNing commented on alicloud/resource_alicloud_ess_scaling_configuration_test.go
> +			},
done

2022-01-05 07:39 UTC, xiaozhu36 requested changes

2022-01-05 07:39 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_scaling_configuration.go
> +				Elem: &schema.Resource{
在resource中应该改为 TypeSet

2022-01-06 11:24 UTC, TalentNing commented on alicloud/resource_alicloud_ess_scaling_configuration.go
> +				Elem: &schema.Resource{
done

2022-01-07 01:48 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ess_scalingconfigurations.go
> +							Elem: &schema.Resource{
在datesource 中应该是 TypeList，在resource中是 TypeSet

2022-01-07 12:45 UTC, merged