New Resource `alicloud_ros_template_scratch`; New Datasource `alicloud_ros_template_scratches`
aliyun/terraform-provider-alicloud pull request #4421
Opened 2021-12-28 08:21 UTC by super-eggs

New Resource `alicloud_ros_template_scratch`
New Datasource `alicloud_ros_template_scratches`

2021-12-28 12:49 UTC, xinmu0426 commented on alicloud/data_source_alicloud_ros_template_scratches_test.go
> +  }
这块的代码格式化下

2021-12-28 12:49 UTC, xinmu0426 commented on alicloud/resource_alicloud_ros_template_scratch.go
> +		update = true
这个位置不对

2021-12-28 12:49 UTC, xinmu0426 commented on website/docs/r/ros_template_scratch.html.markdown
> +  description           = "example_value"
改为 tf_testacc

2021-12-28 12:49 UTC, xinmu0426 commented on website/docs/r/ros_template_scratch.html.markdown
> +* `resource_tags` - (Required) Source label. Up to `10` source labels are supported.
这块的翻译看下：**NOTE:** A maximum of 10 source labels can be configured. 其他的一样的

2021-12-28 12:49 UTC, xinmu0426 commented on website/docs/d/ros_template_scratches.html.markdown
> + * `source_tag` - Source label list.
The Source label list

2021-12-28 12:49 UTC, xinmu0426 commented on alicloud/data_source_alicloud_ros_template_scratches_test.go
> +			"ids": []string{"${alicloud_ros_template_scratch.default.id}"},
enable_details

2021-12-29 02:40 UTC, super-eggs commented on alicloud/resource_alicloud_ros_template_scratch.go
> +		update = true
这里实际测试的时候，preference_parameters 参数在更新时为必填，所以要分开写。

2021-12-30 01:59 UTC, xiaozhu36 requested changes

2021-12-30 01:59 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ros_template_scratch.go
> +				Optional: true,
这种复杂结构应该设置为 TypeSet

2021-12-30 01:59 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ros_template_scratch_test.go
> +		log.Printf("[ERROR] %s get an error: %#v", action, err)
如果有报错，直接返回

2021-12-30 01:59 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ros_template_scratch_test.go
> +		err = resource.Retry(5*time.Minute, func() *resource.RetryError {
以后sweeper 中的超时时间设置为 1min

2021-12-30 01:59 UTC, xiaozhu36 commented on website/docs/d/ros_template_scratches.html.markdown
> + * `stacks` - A list of resource stacks associated with the resource scene.
这个格式不对吧

2021-12-30 12:52 UTC, xiaozhu36 requested changes

2021-12-30 12:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ros_template_scratch_test.go
> +		return fmt.Errorf("[ERROR] %s get an error: %#v", action, err)
不是直接返回错误，而是打印出错误之后，直接return nil

2021-12-30 12:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ros_template_scratch_test.go
> +  }
这个不对吧，应该是 No-Deleting

2021-12-30 12:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ros_template_scratch_test.go
> +}
这个也一样，可以参考下其他的

2021-12-31 07:10 UTC, super-eggs commented on alicloud/resource_alicloud_ros_template_scratch_test.go
> +  }
这里已更改为 "No-Deleting"。这个测试需要保证测试区域里至少存在一个标签为 `{Created": "No-Deleting”}` 的VPC 和 VSwitch。目前采用先查再创建的方式，会因为执行顺序的问题，导致虽然 VPC 或 VSwitch 虽然创建了，但是没有标签值，测试不通过。使用 `depends_on`  显示声明也不行。所以现在采用在测试地区提前创建好对应标签的资源。

2021-12-31 08:49 UTC, super-eggs commented on alicloud/resource_alicloud_ros_template_scratch_test.go
> +}
这里的 VPC 和 VSwitch 查询已去除，因为 `template_scratch` 资源其实并没有实际引用到这两个资源。

2022-01-02 10:52 UTC, xiaozhu36 requested changes

2022-01-02 10:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ros_template_scratch_test.go
> +data "alicloud_vswitches" "default" {}
这个vswitch 是干啥的，还是没改对啊

2022-01-05 01:38 UTC, xiaozhu36 requested changes

2022-01-05 01:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ros_template_scratch_test.go
> +			testAccPreCheckWithEnvVariable(t, "VPC_WITH_NO-DELETING_TAG")
加这个环境变量是啥意思

2022-01-05 01:47 UTC, super-eggs commented on alicloud/resource_alicloud_ros_template_scratch_test.go
> +			testAccPreCheckWithEnvVariable(t, "VPC_WITH_NO-DELETING_TAG")
这个测试需要确保测试区域里至少存在一个标签为 {Created": "No-Deleting”} 的VPC 和 VSwitch。如果采用先查再创建的方式，会因为执行顺序的问题，导致虽然 VPC 或 VSwitch 虽然创建了，但是没有标签值，测试不通过。使用 depends_on 显示声明也不行，因为从Terraform 角度看，vpc 或 VSwitch 和 资源场景其实是没有关联的。 所以现在采用在测试地区提前创建好对应标签的资源。这里加环境变量，是为了约束测试，确保满足测试所需条件。

2022-01-06 07:30 UTC, merged