resource/alicloud_ga_accelerator: Added the time limit of the field duration.
aliyun/terraform-provider-alicloud pull request #4426
Opened 2021-12-28 13:35 UTC by Wanghx0991

2021-12-29 04:03 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ga_accelerator_test.go
> +func TestAccAlicloudGaAccelerator_unit(t *testing.T) {
96.8%

2021-12-30 02:03 UTC, xiaozhu36 requested changes

2021-12-30 02:03 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_accelerator.go
> +		request["Duration"] = duration / 12
直接把 PricingCycle 暴露出来吧

2021-12-30 07:09 UTC, xiaozhu36 requested changes

2021-12-30 07:09 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_accelerator.go
> +			},
这个属于非兼容变更，改成 optional，然后在代码中设置一个默认值 Month，这个设置为 Computed

2021-12-30 11:15 UTC, merged