testcase: Adds a new test case for resource alicloud_cen_transit_router_vpc_attachment
aliyun/terraform-provider-alicloud pull request #4436
Opened 2021-12-29 10:14 UTC by thisnihonglei

2021-12-29 10:15 UTC, thisnihonglei commented on alicloud/resource_alicloud_cen_transit_router_vpc_attachment.go
> -			"auto_create_vpc_route": {
删掉这参数是因为创建接口CreateTransitRouterVpcAttachment文档中没有此参数。

2022-01-24 03:13 UTC, xiaozhu36 requested changes

2022-01-24 03:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cen_transit_router_vpc_attachment.go
> -			"auto_create_vpc_route": {
代码中先不要删，先从文档中下掉

2022-01-24 03:27 UTC, thisnihonglei commented on alicloud/resource_alicloud_cen_transit_router_vpc_attachment.go
> -			"auto_create_vpc_route": {
done

2022-01-24 13:08 UTC, merged