testcase: Adds a new test case for resource alicloud_alb_server_group
aliyun/terraform-provider-alicloud pull request #4445
Opened 2021-12-30 08:15 UTC by thisnihonglei

2022-01-23 10:27 UTC, xiaozhu36 requested changes

2022-01-23 10:27 UTC, xiaozhu36 commented on alicloud/resource_alicloud_alb_server_group_test.go
> +  vpc_name       = var.name
这个为啥要创建新的

2022-01-24 02:54 UTC, thisnihonglei commented on alicloud/resource_alicloud_alb_server_group_test.go
> +  vpc_name       = var.name
已改成查询

2022-01-24 03:14 UTC, xiaozhu36 requested changes

2022-01-24 03:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_alb_server_group_test.go
> +  vpc_name       = var.name
还是在啊

2022-01-24 03:24 UTC, thisnihonglei commented on alicloud/resource_alicloud_alb_server_group_test.go
> +  vpc_name       = var.name
删掉了

2022-01-25 06:02 UTC, merged