testcase: Adds a new test case for resource alicloud_db_instance
aliyun/terraform-provider-alicloud pull request #4453
Opened 2022-01-01 19:37 UTC by thisnihonglei

2022-01-20 02:09 UTC, xiaozhu36 requested changes

2022-01-20 02:09 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance.go
> +		return nil
这个资源不是 alicloud_nat_gateway

2022-01-20 02:09 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance.go
> +		return nil
另外，对应的文档也得改成统一的那种提醒方式

2022-01-24 06:45 UTC, thisnihonglei commented on alicloud/resource_alicloud_db_instance.go
> +		return nil
done

2022-01-24 13:10 UTC, merged