datasource/alicloud_cen_transit_routers: Modify the parameter `transit_router_id` to `Optional`
aliyun/terraform-provider-alicloud pull request #4459
Opened 2022-01-05 06:44 UTC by xinmu0426

datasource/alicloud_cen_transit_routers: Modify the parameter `transit_router_id` to `Optional`

2022-01-05 06:59 UTC, xiaozhu36 requested changes

2022-01-05 06:59 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cen_transit_routers.go
>  	if v, ok := d.GetOk("name_regex"); ok {
还是有问题啊，ids 这个参数没有被使用到

2022-01-05 10:56 UTC, xinmu0426 commented on alicloud/data_source_alicloud_cen_transit_routers.go
>  	if v, ok := d.GetOk("name_regex"); ok {
ids 在 data_source_alicloud_cen_transit_routers 中被设置为了出参，没有当作查询参数使用

2022-01-05 11:10 UTC, xiaozhu36 requested changes

2022-01-05 11:10 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cen_transit_routers.go
>  	if v, ok := d.GetOk("name_regex"); ok {
所以要支持啊，其他的datasource都支持

2022-01-07 11:30 UTC, xiaozhu36 requested changes

2022-01-07 11:30 UTC, xiaozhu36 commented on website/docs/d/cen_transit_routers.html.markdown
> +    * `id` - The ID of the resource, It is formatted to `<cen_id>:<transit_router_id>`.
既然格式变了，文档中还是应该说下，在 1.151.0 版本之前，它的值是多少

2022-01-07 12:43 UTC, merged