New Resource `alicloud_vpc_bgp_group`; New dataSource `alicloud_vpc_bgp_groups`.
aliyun/terraform-provider-alicloud pull request #4465
Opened 2022-01-06 07:14 UTC by super-eggs

New Resource `alicloud_vpc_bgp_group`;
New dataSource `alicloud_vpc_bgp_groups`.

2022-01-06 10:06 UTC, xinmu0426 commented on website/docs/r/vpc_bgp_group.html.markdown
> +* `auth_key` - (Optional) The authentication key of the BGP group.
这快(Optional) 不对

2022-01-06 10:06 UTC, xinmu0426 commented on alicloud/connectivity/regions.go
> +var VPCBgpGroupSupportRegions = []Region{Hangzhou}
只支持杭州？

2022-01-06 10:06 UTC, xinmu0426 commented on alicloud/resource_alicloud_vpc_bgp_group_test.go
> +
sweep

2022-01-06 10:14 UTC, super-eggs commented on alicloud/connectivity/regions.go
> +var VPCBgpGroupSupportRegions = []Region{Hangzhou}
这里因为测试要关联边界路由器，而创建边界路由器所使用的物理专线只有杭州有，所以目前当前测试也只支持杭州。

2022-01-07 03:45 UTC, super-eggs commented on website/docs/r/vpc_bgp_group.html.markdown
> +* `auth_key` - (Optional) The authentication key of the BGP group.
已修正 is_fake_asn 和 local_asn 属性。

2022-01-08 07:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4465) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4465) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=4465) it.</sub>

2022-01-08 14:36 UTC, xiaozhu36 requested changes

2022-01-09 09:42 UTC, xiaozhu36 requested changes

2022-01-09 09:42 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_bgp_group_test.go
> +data "alicloud_express_connect_physical_connections" "default" {}
要跟vswitch一样，查不到要创建一个

2022-01-10 03:33 UTC, super-eggs commented on alicloud/resource_alicloud_vpc_bgp_group_test.go
> +data "alicloud_express_connect_physical_connections" "default" {}
物理专线暂时不能创建，创建后需要走施工流程，施工完成之后才能创建边缘路由器。所以这里只能查询。

2022-01-11 01:55 UTC, merged