testcase/alicloud_nat_gateway: Improves the nat gateway testcases
aliyun/terraform-provider-alicloud pull request #4474
Opened 2022-01-10 06:03 UTC by thisnihonglei

2022-01-10 06:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4474) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4474) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=4474) it.</sub>

2022-01-24 13:12 UTC, xiaozhu36 requested changes

2022-01-24 13:12 UTC, xiaozhu36 commented on alicloud/resource_alicloud_nat_gateway_test.go
> +					testAccCheck(map[string]string{}),
这个是为啥注释掉？是不返回了么？

2022-01-25 02:33 UTC, thisnihonglei commented on alicloud/resource_alicloud_nat_gateway_test.go
> +					testAccCheck(map[string]string{}),
这个字段仅当InstanceChargeType为PrePaid（包年包月公网NAT网关）创建的资源才有效，这里虽然可以update，并且update不报错。但是其实update这一步是没有起到修改作用的。包年包月公网NAT网关，才会返回这个字段。

2022-01-25 03:20 UTC, thisnihonglei commented on alicloud/resource_alicloud_nat_gateway_test.go
> +					testAccCheck(map[string]string{}),
正常的后付费资源，这个spec字段是返回空的

2022-01-25 06:03 UTC, merged