New Resource `alicloud_alidns_address_pool`; New dataSource `alicloud_alidns_address_pools`
aliyun/terraform-provider-alicloud pull request #4476
Opened 2022-01-10 09:18 UTC by super-eggs

New Resource `alicloud_alidns_address_pool`;
New dataSource `alicloud_alidns_address_pools`

2022-01-11 02:12 UTC, xinmu0426 commented on alicloud/resource_alicloud_alidns_address_pool.go
> +	if addressSli, ok := object["Addrs"].(map[string]interface{})["Addr"].([]interface{}); ok {
不要长链路强转

2022-01-11 02:12 UTC, xinmu0426 commented on alicloud/resource_alicloud_alidns_address_pool_test.go
> +			testAccPreCheckWithEnvVariable(t, "ALICLOUD_ICP_DOMAIN_NAME")
预付费实例每月测一次

2022-01-11 02:12 UTC, xinmu0426 commented on alicloud/resource_alicloud_alidns_address_pool_test.go
> +			testAccPreCheckWithEnvVariable(t, "ALICLOUD_ICP_DOMAIN_NAME")
预付费实例每月测一次

2022-01-11 02:12 UTC, xinmu0426 commented on alicloud/data_source_alicloud_alidns_address_pools_test.go
> +		testAccPreCheckWithEnvVariable(t, "ALICLOUD_ICP_DOMAIN_NAME")
预付费实例每月测一次

2022-01-11 02:12 UTC, xinmu0426 commented on website/docs/r/alidns_address_pool.html.markdown
> +* `attribute_info` - (Required) The source region of the address.
attribute_info 也应该写为代码块

2022-01-14 07:11 UTC, xiaozhu36 requested changes

2022-01-14 07:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_alidns_address_pool_test.go
> +func TestAccAlicloudAlidnsAddressPool_basic0(t *testing.T) {
sweep 呢

2022-01-14 07:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_alidns_address_pool_test.go
> +			},
instance id 也不返回么

2022-01-14 07:14 UTC, super-eggs commented on alicloud/resource_alicloud_alidns_address_pool_test.go
> +			},
Api 不返回

2022-01-14 07:16 UTC, super-eggs commented on alicloud/resource_alicloud_alidns_address_pool_test.go
> +func TestAccAlicloudAlidnsAddressPool_basic0(t *testing.T) {
DescribeDnsGtmInstanceAddressPools 中 InstanceId 为必填。

2022-01-14 07:28 UTC, merged