New Resource alicloud_ram_security_preference
aliyun/terraform-provider-alicloud pull request #4478
Opened 2022-01-10 11:02 UTC by Wanghx0991

2022-01-10 11:28 UTC, Wanghx0991 commented on alicloud/connectivity/client.go
> -			log.Printf("[ERROR] loading %s endpoint got an error: %#v. Using the endpoint %s instead.", productCode, err, endpoint)
小马提的在深圳region下, 如果location已经返回报错, 应该直接报出,目前是等到最终超时, 返回了一个超时的错误

2022-01-11 02:01 UTC, xiaozhu36 requested changes

2022-01-11 02:01 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_traffic_mirror_filter_egress_rule_test.go
>  	"github.com/aliyun/terraform-provider-alicloud/alicloud/connectivity"
这种格式化的变化，按理说在github ci上在提交的时候就能检查出来，为啥你提交的这个才补上

2022-01-11 07:11 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ram_security_preference_test.go
> +func TestAccAlicloudRAMSecurityPreference_unit(t *testing.T) {
98%

2022-01-11 08:18 UTC, xiaozhu36 requested changes

2022-01-11 08:18 UTC, xiaozhu36 commented on website/docs/r/ram_security_preference.html.markdown
> +* `id` - The resource ID in terraform of Security Preference.
说清楚 ID 是什么

2022-01-11 09:50 UTC, merged