New Resource `alicloud_alidns_access_strategy`; New dataSource `alicloud_alidns_access_strategies`
aliyun/terraform-provider-alicloud pull request #4491
Opened 2022-01-13 03:24 UTC by super-eggs

New Resource `alicloud_alidns_access_strategy`;
New dataSource `alicloud_alidns_access_strategies`

2022-01-13 07:10 UTC, xinmu0426 commented on website/docs/d/alidns_access_strategies.html.markdown
> +* `strategy_mode` - (Required, ForceNew) The type of the access policy. Valid values: `GEO` or `LATENCY`. `GEO`: based on geographic location. `LATENCY`: Based on delay.
Valid values: 
* `GEO`: based on geographic location. 
* `LATENCY`: Based on delay.

2022-01-13 07:10 UTC, xinmu0426 commented on alicloud/data_source_alicloud_alidns_access_strategies.go
> +	action := "DescribeDnsGtmAccessStrategies"
这个list接口不规范 记个aone

2022-01-13 07:10 UTC, xinmu0426 commented on alicloud/data_source_alicloud_alidns_access_strategies_test.go
> +			"ids":        `["${alicloud_alidns_access_strategy.default.id}"]`,
只用name_regex ，加一个allconf

2022-01-13 07:10 UTC, xinmu0426 commented on alicloud/resource_alicloud_alidns_access_strategy.go
> +	if v, ok := object["DefaultMaxReturnAddrNum"]; ok && fmt.Sprint(v) != "0" {
&& fmt.Sprint(v) != "0" 去掉 下同

2022-01-13 07:10 UTC, xinmu0426 commented on alicloud/resource_alicloud_alidns_access_strategy_test.go
> +func TestAccAlicloudAlidnsAccessStrategy_basic0(t *testing.T) {
增加一个最小参数创建实力

2022-01-14 10:53 UTC, xiaozhu36 requested changes

2022-01-14 10:53 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alidns_access_strategies.go
> +			"strategy_mode": {
这个应该有 枚举值吧

2022-01-14 10:53 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alidns_access_strategies_test.go
> +  resource_group_id = data.alicloud_resource_manager_resource_groups.default.groups.0.id
为啥要用 resource group id 过滤

2022-01-16 04:40 UTC, super-eggs commented on alicloud/data_source_alicloud_alidns_access_strategies_test.go
> +  resource_group_id = data.alicloud_resource_manager_resource_groups.default.groups.0.id
已去除

2022-01-16 09:50 UTC, merged