New Resource alicloud_ecs_prefix_list New Datasource alicloud_ecs_prefix_lists
aliyun/terraform-provider-alicloud pull request #4492
Opened 2022-01-13 07:41 UTC by Wanghx0991

2022-01-13 07:45 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecs_prefix_list_test.go
> +func TestAccAlicloudECSPrefixList_unit(t *testing.T) {
98%

2022-01-14 07:26 UTC, xiaozhu36 requested changes

2022-01-14 07:26 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecs_prefix_lists.go
> +				Default:      "",
default 值去掉

2022-01-14 07:26 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecs_prefix_lists_test.go
> +	prefix_list_name = "tftest"
var.name

2022-01-14 07:26 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_prefix_list.go
> +	err = d.Set("prefix_list_name", object["PrefixListName"])
err 不用设置

2022-01-14 07:26 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_prefix_list_test.go
> +func TestAccAlicloudECSPrefixList_basic0(t *testing.T) {
sweeper 呢

2022-01-14 08:30 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_ecs_prefix_lists.go
> +				Default:      "",
修正了

2022-01-14 08:31 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_ecs_prefix_lists_test.go
> +	prefix_list_name = "tftest"
修正了

2022-01-14 08:32 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecs_prefix_list.go
> +	err = d.Set("prefix_list_name", object["PrefixListName"])
修正了

2022-01-14 08:32 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecs_prefix_list_test.go
> +func TestAccAlicloudECSPrefixList_basic0(t *testing.T) {
sweep加了

2022-01-14 10:49 UTC, xiaozhu36 requested changes

2022-01-14 10:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_prefix_list.go
> +	err = resource.Retry(1*time.Second, func() *resource.RetryError {
1秒就不用重试了，如果存在重试，那么就用 timeout设置

2022-01-14 10:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_prefix_list_test.go
> +		"tf-testacc",
只保留最后一个就行了，这个跟你case中实际的name 的设置有关

2022-01-14 10:54 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecs_prefix_list.go
> +	err = resource.Retry(1*time.Second, func() *resource.RetryError {
去掉了 , 这个是为了mock删除超时的错误, 多带上去了

2022-01-14 11:01 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ecs_prefix_list_test.go
> +		"tf-testacc",
修正了

2022-01-14 12:24 UTC, xiaozhu36 approved these changes

2022-01-14 12:24 UTC, merged