datasource/alicloud_alikafka_topics: Adds new attribute id status_name instance_id tags; datasource/alicloud_alikafka_consumer_groups: Adds new attribute id consumer_id instance_id remark tags;
aliyun/terraform-provider-alicloud pull request #4494
Opened 2022-01-13 09:51 UTC by thisnihonglei

2022-01-13 09:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4494) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4494) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=4494) it.</sub>

2022-01-13 10:05 UTC, xiaozhu36 requested changes

2022-01-13 10:05 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alikafka_consumer_groups.go
>  				Type:     schema.TypeList,
不要直接改，要保持兼容

2022-01-13 10:05 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alikafka_topics.go
> +			},
还要在支持一个参数 Topic，跟 GetTopicList 参数保持一致

2022-01-14 01:14 UTC, xiaozhu36 requested changes

2022-01-14 01:14 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alikafka_topics.go
> +			},
这个怎么没加啊

2022-01-14 01:14 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alikafka_topics.go
> +
无用的注释直接去掉

2022-01-14 06:56 UTC, thisnihonglei commented on alicloud/data_source_alicloud_alikafka_topics.go
> +			},
之前的SDK接入，SDK的版本不支持Topic这个参数。

2022-01-14 06:57 UTC, thisnihonglei commented on alicloud/data_source_alicloud_alikafka_topics.go
> +
已去掉

2022-01-14 08:27 UTC, xiaozhu36 requested changes

2022-01-14 08:27 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alikafka_consumer_groups.go
> +		}
加这个错误是干啥

2022-01-14 08:27 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alikafka_instances.go
> +							Type:     schema.TypeMap,
typelist

2022-01-14 08:27 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alikafka_topics.go
> +			},
既然加上了，就要在请求中设置上啊

2022-01-14 13:43 UTC, xiaozhu36 requested changes

2022-01-14 13:43 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alikafka_instances.go
> +		getResp, err := AlikaService.GetAllowedIpList(id)
这个地方要在加一个参数 enable_details，只有当 enable_details 为true 的时候，才循环遍历查询 IPList

2022-01-14 13:43 UTC, xiaozhu36 commented on website/docs/d/alikafka_consumer_groups.html.markdown
> +* `ids` - (Optional, ForceNew, Computed)  A list of ALIKAFKA Consumer Groups IDs.
ids 的格式要说清楚

2022-01-14 13:43 UTC, xiaozhu36 commented on website/docs/d/alikafka_topics.html.markdown
> +* `ids` - (Optional, ForceNew, Computed)  A list of ALIKAFKA Topics IDs.
ids 的格式要说清楚

2022-01-14 13:43 UTC, xiaozhu36 commented on website/docs/d/alikafka_topics.html.markdown
> +  * `id` - The ID of the topic.
id 的格式要说清楚

2022-01-15 03:34 UTC, thisnihonglei commented on alicloud/data_source_alicloud_alikafka_instances.go
> +		getResp, err := AlikaService.GetAllowedIpList(id)
done

2022-01-15 03:34 UTC, thisnihonglei commented on website/docs/d/alikafka_consumer_groups.html.markdown
> +* `ids` - (Optional, ForceNew, Computed)  A list of ALIKAFKA Consumer Groups IDs.
done

2022-01-15 03:34 UTC, thisnihonglei commented on website/docs/d/alikafka_topics.html.markdown
> +* `ids` - (Optional, ForceNew, Computed)  A list of ALIKAFKA Topics IDs.
done

2022-01-15 03:34 UTC, thisnihonglei commented on website/docs/d/alikafka_topics.html.markdown
> +  * `id` - The ID of the topic.
done

2022-01-15 07:51 UTC, merged