resource/alicloud_security_group_rule: support updating prefix_list_id
aliyun/terraform-provider-alicloud pull request #4496
Opened 2022-01-14 04:10 UTC by Wanghx0991

2022-01-14 12:33 UTC, xiaozhu36 requested changes

2022-01-14 12:33 UTC, xiaozhu36 commented on website/docs/r/security_group_rule.html.markdown
> +* `prefix_list_id`- (Optional) The ID of the source/destination prefix list to which you want to control access. **NOTE:** If you specify `cidr_ip`,`source_security_group_id` parameter, this paramete
如果有后面的这个限制，那么 应该增加 Diffsuppress

2022-01-14 12:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_security_group_rule.go
> +		return WrapError(fmt.Errorf("you must specify one of the following field: cidr_ip,source_security_group_id,prefix_list_id"))
三个参数之间逗号之后增加一个空格

2022-01-14 15:25 UTC, Wanghx0991 commented on alicloud/resource_alicloud_security_group_rule.go
> +		return WrapError(fmt.Errorf("you must specify one of the following field: cidr_ip,source_security_group_id,prefix_list_id"))
Done

2022-01-14 15:25 UTC, Wanghx0991 commented on website/docs/r/security_group_rule.html.markdown
> +* `prefix_list_id`- (Optional) The ID of the source/destination prefix list to which you want to control access. **NOTE:** If you specify `cidr_ip`,`source_security_group_id` parameter, this paramete
Done

2022-01-14 15:41 UTC, Wanghx0991 commented on website/docs/r/security_group_rule.html.markdown
> -* `name` - The name of the security group
CI检验出的, schema里没有定义

2022-01-15 02:32 UTC, xiaozhu36 requested changes

2022-01-15 02:32 UTC, xiaozhu36 commented on alicloud/resource_alicloud_security_group_rule.go
> +	_, source_security_group_id_exist := d.GetOk("source_security_group_id")
命名用小驼峰

2022-01-15 03:19 UTC, Wanghx0991 commented on alicloud/diff_suppress_funcs.go
> +	_, SourceSecurityGroupIdExist := d.GetOk("cidr_ip")
纠正了

2022-01-15 03:19 UTC, Wanghx0991 commented on alicloud/resource_alicloud_security_group_rule.go
> +	_, source_security_group_id_exist := d.GetOk("source_security_group_id")
纠正了

2022-01-15 07:52 UTC, merged

2022-01-21 19:59 UTC, zhangyoufu commented
1.152.0 版本，修改 prefix_list_id 后，apply 时报错。

```
Terraform will perform the following actions:

  # alicloud_security_group_rule.ingress will be updated in-place
  ~ resource "alicloud_security_group_rule" "ingress" {
        id                = "sg-j6c1s3l2aopjtk1kcsld:ingress:tcp:7600/7600:::accept:3"
      ~ prefix_list_id    = "pl-j6c07n4j5cgonwrf2ovz" -> "pl-j6c366vdb6tlcdew03x4"
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

alicloud_security_group_rule.ingress: Modifying... [id=sg-j6c1s3l2aopjtk1kcsld:ingress:tcp:7600/7600:::accept:3]
╷
│ Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_security_group_rule.go:280: Resource sg-j6c1s3l2aopjtk1kcsld:ingress:tcp:7600/7600:::accept:3 ModifySecurityGroupRule Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
│ SDK.ServerError
│ ErrorCode: SecurityGroupRule.NotFound
│ Recommend: https://error-center.aliyun.com/status/search?Keyword=SecurityGroupRule.NotFound&source=PopGw
│ RequestId: 3C8A49ED-A331-3901-A0FA-7386923422D2
│ Message: The target security group rule not exist.
```