resource/alicloud_amqp_instance: fix the renewal_status updated issue resource/edas_k8s_application: fix the field package_version
aliyun/terraform-provider-alicloud pull request #4498
Opened 2022-01-14 07:35 UTC by Wanghx0991

2022-01-14 12:27 UTC, xiaozhu36 requested changes

2022-01-14 12:27 UTC, xiaozhu36 commented on alicloud/resource_alicloud_amqp_instance.go
>  	if d.HasChange("renewal_duration_unit") {
上面这个为啥要改啊，没看懂

2022-01-14 14:41 UTC, Wanghx0991 commented on alicloud/errors.go
> -var OperationDeniedDBStatus = []string{"OperationDenied.DBStatus", "OperationDenied.DBInstanceStatus", "OperationDenied.DBClusterStatus", "InternalError", "OperationDenied.OutofUsage", "IncorrectDBIn
这个是一个客户需求，并发创建报错，跟云产品沟通让加一个这个超时重试的错误再试下

2022-01-14 14:41 UTC, Wanghx0991 commented on alicloud/resource_alicloud_amqp_instance.go
>  	if d.HasChange("renewal_duration_unit") {
这个是夜游值班碰到的问题, 用户之前是手动续费的(renewal_status 为Manual, 此时renewal_duration为1), 后续只是将renewal_status 改为了自动续费( 此时renewal_duration未变动) ,因为duration没有变化,请求里只改了renewal_status,  renewal_duration这个字段并没有填入, 服务端返回了报错,:两个需要都填

2022-01-14 14:41 UTC, Wanghx0991 commented on alicloud/resource_alicloud_amqp_instance.go
>  	if d.HasChange("renewal_duration_unit") {
这里就吧两个字段做了统一检查: `不是新资源&&两个字段有一个发生改变,需要都填写,否则报错`

2022-01-14 15:39 UTC, Wanghx0991 commented on alicloud/resource_alicloud_edas_k8s_application.go
> -				Default:  strconv.FormatInt(time.Now().Unix(), 10),
这里也是个值班问题, 用户这个字段没有填入, 创建完成后 做plan有diff

2022-01-14 15:39 UTC, Wanghx0991 commented on alicloud/resource_alicloud_edas_k8s_application.go
> -				Default:  strconv.FormatInt(time.Now().Unix(), 10),
Resource CREATE failed: terraform stack stack_2022-01-13_R08KiyWr0c failure, Code: TerraformError Message: Error: Provider produced inconsistent final plan When expanding the plan for alicloud_edas_k8s_application.default to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/alicloud" produced an invalid new value for .package_version: was cty.StringVal("1642067433"), but now cty.StringVal("1642067458"). This is a bug in the provider, which should be reported in the provider's own issue tracker.

2022-01-15 02:45 UTC, xiaozhu36 requested changes

2022-01-15 02:45 UTC, xiaozhu36 commented on alicloud/resource_alicloud_amqp_instance.go
>  	if d.HasChange("renewal_duration_unit") {
那这个地方应该这样改，在haschange中设置 update = true，然后在外边设置参数，类似下面这样

if !d.IsNewResource() && d.HasChange("renewal_status") {
  update = true
}

也就是说，这几个参数不管什么时候都得传

2022-01-15 03:43 UTC, Wanghx0991 commented on alicloud/resource_alicloud_amqp_instance.go
>  	if d.HasChange("renewal_duration_unit") {
Done

2022-01-15 15:26 UTC, merged