New Resource alicloud_vpc_dpch_options_set_attachment
aliyun/terraform-provider-alicloud pull request #4505
Opened 2022-01-17 09:07 UTC by Wanghx0991

2022-01-17 12:21 UTC, Wanghx0991 commented on alicloud/resource_alicloud_vpc_dhcp_options_set_attachment_test.go
> +func TestAccAlicloudVPCDhcpOptionsSetAttachment_unit(t *testing.T) {
95.7

2022-01-18 08:14 UTC, xiaozhu36 requested changes

2022-01-18 08:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_dhcp_options_set_attachment.go
> +				Type:     schema.TypeString,
这两个应该是 ForceNew 的

2022-01-18 08:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_dhcp_options_set_attachment.go
> +					err = d.Set("status", associateVpcsListItemMap["AssociateStatus"])
这几个 err 不需要

2022-01-18 08:14 UTC, xiaozhu36 commented on website/docs/r/vpc_dhcp_options_set.html.markdown
> +* `associate_vpcs` - (Optional, Deprecated) AssociateVpcs. Number of VPCs that can be associated with each DHCP options set is 10. Field `associate_vpcs` has been deprecated from provider version 1.1
It will be removed. 中的 It 首字母要大写

2022-01-18 08:16 UTC, Wanghx0991 commented on alicloud/resource_alicloud_vpc_dhcp_options_set_attachment.go
> +				Type:     schema.TypeString,
Done

2022-01-18 08:16 UTC, Wanghx0991 commented on alicloud/resource_alicloud_vpc_dhcp_options_set_attachment.go
> +					err = d.Set("status", associateVpcsListItemMap["AssociateStatus"])
Done

2022-01-18 10:47 UTC, merged