datasource/alicloud_alikafka_topics: Adds two internal parameters current_page and page_size to support paging
aliyun/terraform-provider-alicloud pull request #4514
Opened 2022-01-18 10:34 UTC by thisnihonglei

2022-01-18 10:37 UTC, thisnihonglei commented on alicloud/data_source_alicloud_alikafka_topics.go
> +			if IsExpectedErrors(err, []string{"ONS_INVOKE_ERROR"}) {
加这段处理预知错误的代码是因为GetTopicList接口，当CurrentPage=2，PageSize=10，返回的数据不够10个时，会报错："Message": "invoke json request error.. Please check and try again later."，但是当CurrentPage=2，PageSize=1，返回的数据大于1个的时候，接口就会正常返回。

2022-01-19 02:31 UTC, xiaozhu36 requested changes

2022-01-19 02:31 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alikafka_topics.go
> +			"current_page": {
都统一为 page_number和 page_size

2022-01-19 02:31 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alikafka_topics.go
> +			if IsExpectedErrors(err, []string{"ONS_INVOKE_ERROR"}) {
这个不需要加，跟 API的行为保持一致

2022-01-19 02:31 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alikafka_topics.go
> +			},
total count 呢

2022-01-19 03:10 UTC, thisnihonglei commented on alicloud/data_source_alicloud_alikafka_topics.go
> +			},
已加

2022-01-19 03:10 UTC, thisnihonglei commented on alicloud/data_source_alicloud_alikafka_topics.go
> +			"current_page": {
done

2022-01-19 03:11 UTC, thisnihonglei commented on alicloud/data_source_alicloud_alikafka_topics.go
> +			if IsExpectedErrors(err, []string{"ONS_INVOKE_ERROR"}) {
done

2022-01-19 11:00 UTC, merged