resource/alicloud_hbr_nas_backup_plan: remove attribute 'create_time'.
aliyun/terraform-provider-alicloud pull request #4518
Opened 2022-01-20 09:53 UTC by ChenHanZhang

2022-01-20 09:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4518) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4518) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=4518) it.</sub>

2022-01-21 06:30 UTC, xiaozhu36 requested changes

2022-01-21 06:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_hbr_nas_backup_plan.go
> -			},
这些怎么都直接删掉了
如果确实不用了，需要移除，那么就加上 Removed 标记

2022-01-21 07:39 UTC, ChenHanZhang commented on alicloud/resource_alicloud_hbr_nas_backup_plan.go
> -			},
文档上有透出的属性已经标记上Deprecated，文档上未透出的属性没有做修改。Removed标记是指在文档上注明，还是在代码中注明？

2022-01-21 09:19 UTC, xiaozhu36 requested changes

2022-01-21 09:19 UTC, xiaozhu36 commented on alicloud/resource_alicloud_hbr_nas_backup_plan.go
> -	}
弃用的参数，在代码中还是要支持

2022-01-21 09:19 UTC, xiaozhu36 commented on alicloud/resource_alicloud_hbr_nas_backup_plan.go
> -			request["Exclude"] = v
这个地方也是

2022-01-21 09:21 UTC, ChenHanZhang commented on alicloud/resource_alicloud_hbr_nas_backup_plan.go
> -	}
这几个参数不算弃用，原先就是没有透出，这个API是多个资源共用的，所以多生成了这些参数了。detail、include、exclude这几个参数都未透出，因此直接删除没问题的

2022-01-21 09:21 UTC, ChenHanZhang commented on alicloud/resource_alicloud_hbr_nas_backup_plan.go
> -			request["Exclude"] = v
同上，这几个参数不算弃用，原先就是没有透出，这个API是多个资源共用的，所以多生成了这些参数了。detail、include、exclude这几个参数都未透出，因此直接删除没问题的

2022-01-21 09:22 UTC, merged