testcase: Improve the effectiveness of test cases
aliyun/terraform-provider-alicloud pull request #4530
Opened 2022-01-25 02:53 UTC by Wanghx0991

2022-01-25 02:57 UTC, Wanghx0991 commented on alicloud/resource_alicloud_eci_image_cache_test.go
> -					"images":            []string{"registry.cn-beijing.aliyuncs.com/sceneplatform/sae-image-demo:latest"},
镜像已经找不到了

2022-01-25 02:57 UTC, Wanghx0991 commented on scripts/schema_test.go
> +		"alicloud_amqp_instance":[]string{"logistics"},
这块加了下白名单, 填入的不再做校验了

2022-01-26 02:46 UTC, Wanghx0991 commented on alicloud/resource_alicloud_eip_association.go
> +				"InvalidIpStatus.HasBeenUsedBySnatTable", "InvalidIpStatus.HasBeenUsedByForwardEntry", "InvalidStatus.EniStatusNotSupport"}) {
值班的一个问题 删除报错 需要重试

2022-01-26 02:57 UTC, xiaozhu36 requested changes

2022-01-26 02:57 UTC, xiaozhu36 commented on scripts/schema_test.go
> +	// map[resourceName][]string{WhiteField}
删掉无用的注释

2022-01-27 02:23 UTC, Wanghx0991 commented on scripts/schema_test.go
> +	// map[resourceName][]string{WhiteField}
Done

2022-01-27 03:13 UTC, merged