datasource/alicloud_slb_load_balancers: Adds three internal parameters current_page page_size total_count to support paging
aliyun/terraform-provider-alicloud pull request #4534
Opened 2022-01-26 08:41 UTC by thisnihonglei

2022-01-26 09:15 UTC, xiaozhu36 requested changes

2022-01-26 09:15 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_slb_load_balancers.go
> +				Default:  50,
这个为啥有默认值

2022-01-26 09:43 UTC, thisnihonglei commented on alicloud/data_source_alicloud_slb_load_balancers.go
> +				Default:  50,
已删除

2022-01-27 10:21 UTC, thisnihonglei commented on alicloud/data_source_alicloud_slb_load_balancers.go
> +				Default:  100,
文档中最大值是100

2022-01-27 11:10 UTC, merged