New Resource `alicloud_dbfs_snapshot`; New Datasource `alicloud_dbfs_snapshots`
aliyun/terraform-provider-alicloud pull request #4553
Opened 2022-02-08 10:34 UTC by super-eggs

New Resource `alicloud_dbfs_snapshot`;
New Datasource `alicloud_dbfs_snapshots`

2022-02-09 01:59 UTC, super-eggs commented on alicloud/resource_alicloud_dbfs_snapshot_test.go
> +func TestAccAlicloudDBFSSnapshot_unit(t *testing.T) {
单测97.6%覆盖率

2022-02-09 06:35 UTC, xinmu0426 commented on alicloud/data_source_alicloud_dbfs_snapshots_test.go
> +data "alicloud_dbfs_instances" "default" {
直接改为创建吧

2022-02-09 06:35 UTC, xinmu0426 commented on alicloud/resource_alicloud_dbfs_snapshot.go
> +			"fs_id": {
fs_id统一改为instance_id

2022-02-09 06:35 UTC, xinmu0426 commented on alicloud/resource_alicloud_dbfs_snapshot_test.go
> +  name_regex = "default-NODELETING"
直接创建吧

2022-02-09 06:35 UTC, xinmu0426 commented on website/docs/d/dbfs_snapshots.html.markdown
> +
空格

2022-02-09 07:11 UTC, super-eggs commented on alicloud/data_source_alicloud_dbfs_snapshots_test.go
> +data "alicloud_dbfs_instances" "default" {
创建快照的数据库文件系统需要满足已挂载到ECS实例，但是已挂载到ECS实例的数据库文件系统又是不能删除的，所以测试过程会报错。所以这里采用查询的方式。

2022-02-09 07:12 UTC, super-eggs commented on alicloud/resource_alicloud_dbfs_snapshot_test.go
> +  name_regex = "default-NODELETING"
创建快照的数据库文件系统需要满足已挂载到ECS实例，但是已挂载到ECS实例的数据库文件系统又是不能删除的，所以测试过程会报错。所以这里采用查询的方式。

2022-02-11 02:47 UTC, xinmu0426 commented on alicloud/data_source_alicloud_dbfs_snapshots.go
> +package alicloud
标题改一下  New Resource alicloud_dbfs_snapshot; New Datasource alicloud_dbfs_snapshots  还有attachment

2022-02-11 02:47 UTC, xinmu0426 commented on alicloud/resource_alicloud_dbfs_instance.go
> -			"attach_point": {
这几个为啥要删掉

2022-02-11 02:54 UTC, super-eggs commented on alicloud/resource_alicloud_dbfs_instance.go
> -			"attach_point": {
这个几个属性只在 resource 的 Schema 中定义了，单其实并没有使用，并且文档中也没有透出，导致 CI 文档检查不通过。所以就去除了。

2022-02-11 02:58 UTC, super-eggs commented on alicloud/data_source_alicloud_dbfs_snapshots.go
> +package alicloud
已改；

2022-02-11 08:34 UTC, xiaozhu36 requested changes

2022-02-11 08:55 UTC, super-eggs commented on alicloud/data_source_alicloud_dbfs_snapshots_test.go
> +  availability_zone = "cn-hangzhou-i"
需要挂载的的ECS实例，要求与 dbfs 实例的可用区一致。

2022-02-11 08:55 UTC, super-eggs commented on alicloud/resource_alicloud_dbfs_snapshot_test.go
> +  zone_id           = "cn-hangzhou-i"
这里 dbfs_instance 目前杭州地区仅支持I可用区，但是文档中没有 查询可用区的api，所以暂时先写死。
需要挂载的的ECS实例，要求与 dbfs 实例的可用区一致。所以暂时都需要写死。
稍后提 Aone。

2022-02-14 07:09 UTC, merged