New Resource `alicloud_mse_gateway`; New Datasource `alicloud_mse_gateways`
aliyun/terraform-provider-alicloud pull request #4577
Opened 2022-02-15 08:09 UTC by super-eggs

New Resource `alicloud_mse_gateway`;
New Datasource `alicloud_mse_gateways`

2022-02-15 08:15 UTC, super-eggs commented on alicloud/resource_alicloud_mse_gateway_test.go
> +func TestAccAlicloudMseGateway_unit(t *testing.T) {
单测97.7%覆盖率

2022-02-16 02:29 UTC, xinmu0426 commented on alicloud/data_source_alicloud_mse_gateways.go
> +			"order_item": {
这个字段没用的话去掉吧

2022-02-16 02:29 UTC, xinmu0426 commented on alicloud/data_source_alicloud_mse_gateways.go
> +		if fmt.Sprint(response["Code"]) != "200" || fmt.Sprint(response["Success"]) == "false" {
list API为啥会有这个

2022-02-16 02:29 UTC, xinmu0426 commented on alicloud/resource_alicloud_mse_gateway.go
> +	for _, slb := range slbList.([]interface{}) {
slbList.([]interface{}) 加一个判空处理

2022-02-16 02:29 UTC, xinmu0426 commented on alicloud/resource_alicloud_mse_gateway.go
> +	request["DeleteSlb"] = true
DeleteSlb这个字段暴露出去

2022-02-17 08:25 UTC, xiaozhu36 requested changes

2022-02-17 08:25 UTC, xiaozhu36 commented on website/docs/r/mse_gateway.html.markdown
> +-> **NOTE:** Available in v1.156.0+.
版本改下

2022-02-17 09:40 UTC, merged