testcase: Adds new unit test case for resource alicloud_cloud_firewall_control_policy alicloud_security_center_group alicloud_security_center_service_linked_role
aliyun/terraform-provider-alicloud pull request #4580
Opened 2022-02-15 09:35 UTC by thisnihonglei

2022-02-15 09:38 UTC, thisnihonglei commented on alicloud/resource_alicloud_amqp_binding_test.go
> -func testSweepAmqpBinding(region string) error {
sweep报错修复

2022-02-15 09:38 UTC, thisnihonglei commented on alicloud/resource_alicloud_cloud_firewall_control_policy_test.go
> +func TestAccAlicloudCloudFirewallControlPolicy_unit(t *testing.T) {
单测95.9%覆盖率

2022-02-15 09:38 UTC, thisnihonglei commented on alicloud/resource_alicloud_direct_mail_mail_address_test.go
>  func testSweepDirectMailAddress(region string) error {
sweep报错修复

2022-02-15 09:38 UTC, thisnihonglei commented on alicloud/resource_alicloud_direct_mail_receivers_test.go
>  func testSweepDirectMailReceivers(region string) error {
sweep报错修复

2022-02-15 09:38 UTC, thisnihonglei commented on alicloud/resource_alicloud_security_center_group_test.go
> +func TestAccAlicloudSASGroup_unit(t *testing.T) {
单测100%覆盖率

2022-02-15 09:38 UTC, thisnihonglei commented on alicloud/resource_alicloud_security_center_service_linked_role_test.go
> +func TestAccAlicloudSecurityCenterServiceLinkedRole_unit(t *testing.T) {
单测96.7%覆盖率

2022-02-17 05:34 UTC, xiaozhu36 requested changes

2022-02-17 05:34 UTC, xiaozhu36 commented on alicloud/resource_alicloud_direct_mail_mail_address_test.go
> +		if region != string(r) {
这个地方不用判断，如果不支持，直接 return nil 就好了

2022-02-17 07:52 UTC, thisnihonglei commented on alicloud/resource_alicloud_direct_mail_mail_address_test.go
> +		if region != string(r) {
done

2022-02-18 02:01 UTC, thisnihonglei commented on alicloud/resource_alicloud_direct_mail_receivers_test.go
> +func TestSweepDirectMailReceiversAcc(t *testing.T) {
done

2022-02-18 03:30 UTC, merged