New Resource `alicloud_mongodb_sharding_network_private_address`;New Datasource `alicloud_mongodb_sharding_network_private_addresses`
aliyun/terraform-provider-alicloud pull request #4584
Opened 2022-02-16 09:25 UTC by super-eggs

New Resource `alicloud_mongodb_sharding_network_private_address`;
New Datasource `alicloud_mongodb_sharding_network_private_addresses`

2022-02-17 07:29 UTC, super-eggs commented on alicloud/resource_alicloud_mongodb_sharding_network_private_address_test.go
> +func TestAccAlicloudMongodbShardingNetworkPrivateAddress_unit(t *testing.T) {
单测96.4%覆盖率

2022-02-17 09:04 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_sharding_network_private_address.go
> +			"account_name": {
account_name 是否存在默认值

2022-02-17 09:04 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_sharding_network_private_address_test.go
> +func TestAccAlicloudMongoDBShardingNetworkPrivateAddress_basic1(t *testing.T) {
测试用例不用写两个吧

2022-02-17 09:04 UTC, xinmu0426 commented on website/docs/d/mongodb_sharding_network_private_addresses.html.markdown
> +-> **NOTE:** Available in v1.156.0+.
157

2022-02-17 09:29 UTC, super-eggs commented on alicloud/data_source_alicloud_mongodb_sharding_network_private_addresses_test.go
> +			"role":    `"Primary"`,
会。每次内网连接地址会创建出来两个，一个 Primary，一个 Secondary；

2022-02-17 09:31 UTC, super-eggs commented on alicloud/resource_alicloud_mongodb_sharding_network_private_address.go
> +			"account_name": {
没有默认值。account_name 不返回。

2022-02-17 09:34 UTC, super-eggs commented on alicloud/resource_alicloud_mongodb_sharding_network_private_address_test.go
> +func TestAccAlicloudMongoDBShardingNetworkPrivateAddress_basic1(t *testing.T) {
有两种情况，一种 node_id 是 Shard，另一种 node_id 是 ConfigServer。

2022-02-18 03:27 UTC, xiaozhu36 requested changes

2022-02-18 03:27 UTC, xiaozhu36 commented on alicloud/service_alicloud_mongodb.go
> +			if item.(map[string]interface{})["NetworkType"].(string) != "Public" {
这个地方应该直接判断 == “Private” 就行吧

2022-02-18 03:27 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_mongodb_sharding_network_private_addresses.go
> +		if item["NetworkType"].(string) == "Public" {
这个地方应该判断 != “Private”

2022-02-18 03:33 UTC, super-eggs commented on alicloud/service_alicloud_mongodb.go
> +			if item.(map[string]interface{})["NetworkType"].(string) != "Public" {
私网连接 NetworkType 的取值范围：VPC(专有网络)、Classic(经典网络)。
公网连接 NetworkType 的取值范围：Public(公网)。
所以这里使用了 `!= "Public"` 来判断。

2022-02-18 03:34 UTC, super-eggs commented on alicloud/data_source_alicloud_mongodb_sharding_network_private_addresses.go
> +		if item["NetworkType"].(string) == "Public" {
这里原因同上。

2022-02-18 06:45 UTC, merged