testcase: Adds new unit test case for resource alicloud_arms_alert_contact alicloud_arms_alert_contact_group alicloud_arms_prometheus_alert_rule
aliyun/terraform-provider-alicloud pull request #4585
Opened 2022-02-16 10:03 UTC by thisnihonglei

2022-02-17 02:13 UTC, thisnihonglei commented on alicloud/resource_alicloud_arms_alert_contact_group_test.go
> +func TestAccAlicloudArmsAlertContactGroup_unit(t *testing.T) {
单测97.9%覆盖率

2022-02-17 02:13 UTC, thisnihonglei commented on alicloud/resource_alicloud_arms_alert_contact_test.go
> +func TestAccAlicloudArmsAlertContact_unit(t *testing.T) {
单测86.2%覆盖率，覆盖率已无法提升

2022-02-17 02:13 UTC, thisnihonglei commented on website/docs/r/arms_prometheus_alert_rule.html.markdown
> +* `status` - (Computed, ForceNew) The status of the resource. Valid values: `0`, `1`.
github CI报错修改

2022-02-17 08:21 UTC, xiaozhu36 requested changes

2022-02-17 08:21 UTC, xiaozhu36 commented on website/docs/r/arms_prometheus_alert_rule.html.markdown
> -* `prometheus_alert_rule_id` - The first ID of the resource.
这个地方应该是直接把这个参数在代码中增加上，输出出来

2022-02-17 08:58 UTC, thisnihonglei commented on website/docs/r/arms_prometheus_alert_rule.html.markdown
> -* `prometheus_alert_rule_id` - The first ID of the resource.
done

2022-02-18 01:51 UTC, xiaozhu36 requested changes

2022-02-18 01:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_arms_prometheus_alert_rule.go
> +			},
如果只是出参，那么不需要 ForceNew

2022-02-18 02:01 UTC, thisnihonglei commented on alicloud/resource_alicloud_arms_prometheus_alert_rule.go
> +			},
done

2022-02-18 03:28 UTC, xiaozhu36 requested changes

2022-02-18 03:28 UTC, xiaozhu36 commented on website/docs/r/arms_prometheus_alert_rule.html.markdown
> +* `status` - (Computed) The status of the resource. Valid values: `0`, `1`.
如果是纯出参，那么应该放在 Attributes Reference 中

2022-02-18 06:46 UTC, merged