Service linked role
aliyun/terraform-provider-alicloud pull request #4590
Opened 2022-02-17 10:39 UTC by Wanghx0991

2022-02-17 11:00 UTC, Wanghx0991 commented
1. New Resource `alicloud_ram_service_linked_role`
2. resource/alicloud_cen_transit_router_peer_attachment: support updating bandwidth_type with DataTransfer

2022-02-17 11:01 UTC, Wanghx0991 commented
1. New Resource `alicloud_ram_service_linked_role`
2. resource/alicloud_cen_transit_router_peer_attachment: support updating bandwidth_type with DataTransfer

2022-02-18 01:54 UTC, xiaozhu36 requested changes

2022-02-18 01:54 UTC, xiaozhu36 commented on alicloud/provider.go
> +			"alicloud_ram_service_linked_role":                              resourceAlicloudRamServiceLinkedRole(),
即然是 resourcemanager 的资源，那么就把ram改成 resourcemanager

2022-02-18 03:22 UTC, merged