Support Custom Kibana Spec
aliyun/terraform-provider-alicloud pull request #4591
Opened 2022-02-18 07:57 UTC by wangcf-yf

2022-02-18 07:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4591) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4591) before we can accept your contribution.<br/><hr/>**yufan.wcf** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=4591) it.</sub>

2022-02-21 03:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_elasticsearch_instance.go
workflow 测试没过 cla协议也签署下

2022-02-21 03:31 UTC, xinmu0426 commented on alicloud/service_alicloud_elasticsearch.go
>  	client := meta.(*connectivity.AliyunClient)
文档也更新下

2022-02-21 03:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_elasticsearch_instance_test.go
> +		},
加一个			{
				ResourceName:      resourceId,
				ImportState:       true,
				ImportStateVerify: true,
			},

2022-02-21 03:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +	// Kibana node configuration
.(map[string]interface{}) 这个最好坐下 判空处理

2022-02-21 03:33 UTC, xinmu0426 commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +				Type:     schema.TypeString,
pr 标题不合理 看下chanagelog的写法吧

2022-02-21 09:22 UTC, wangcf-yf commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +	// Kibana node configuration
这里不用判空，API透出的节点数据，永不为空

2022-02-25 02:01 UTC, xinmu0426 commented on website/docs/r/elasticsearch_instance.html.markdown
> +* `kibana_node_spec` - (Optional, Available in v1.157.0 +) The kibana node specifications of the Elasticsearch instance. Default is `elasticsearch.n4.small`.
改为 158 另外 kibana_node_spec 的取值范围是什么

2022-02-25 02:01 UTC, xinmu0426 commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +		kibanaNode["amount"] = 1
这些默认值信息没有透出呀

2022-03-04 03:06 UTC, wangcf-yf commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +		kibanaNode["amount"] = 1
不用透出，tf没有这些字段，是产品的限制

2022-03-04 03:11 UTC, wangcf-yf commented on website/docs/r/elasticsearch_instance.html.markdown
> +* `kibana_node_spec` - (Optional, Available in v1.157.0 +) The kibana node specifications of the Elasticsearch instance. Default is `elasticsearch.n4.small`.
规格之前都是从售卖页查询，或者产品文档中查看

2022-03-04 12:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +	if d.Get("kibana_node_spec") != nil && d.Get("kibana_node_spec") != "" {
用 d.GetOk 判断

2022-03-04 12:44 UTC, xiaozhu36 requested changes

2022-03-04 12:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +		kibanaNode := make(map[string]interface{})
用 d.GetOk 判断

2022-04-08 07:32 UTC, merged