**New Resource:** `alicloud_ess_scalinggroup_alb_server_groups`
aliyun/terraform-provider-alicloud pull request #4594
Opened 2022-02-19 09:38 UTC by TalentNing

2022-02-19 09:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4594) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4594) before we can accept your contribution.<br/><hr/>**tongkn** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=4594) it.</sub>

2022-02-21 03:14 UTC, xinmu0426 commented on website/docs/r/ess_scalinggroup_vserver_groups.markdown
>  ## Block vserver_group
另外，麻烦签署下cla协议

2022-02-21 03:14 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_scalinggroup_alb_server_groups.go
> +			// 改下面的东西
注释改为英文吧

2022-02-21 03:14 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_scalinggroup_alb_server_groups.go
> +				Optional: true,
这个字段不应该为Optional

2022-02-21 03:14 UTC, xinmu0426 commented on website/docs/r/ess_scalinggroup_alb_server_groups.html.markdown
> +
增加一个对应的英文介绍页面

2022-02-21 07:58 UTC, TalentNing commented on alicloud/resource_alicloud_ess_scalinggroup_alb_server_groups.go
> +			// 改下面的东西
done

2022-02-21 08:26 UTC, TalentNing commented on website/docs/r/ess_scalinggroup_vserver_groups.markdown
>  ## Block vserver_group
done

2022-02-21 12:30 UTC, xiaozhu36 requested changes

2022-02-21 12:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_scalinggroup_alb_server_groups.go
> +	return &schema.Resource{
这个资源应该写成一个attachment， resourceAlicloudEssScalingGroupAlbServerGroupAttachment，这个资源的有以下属性：scaling_group_id，alb_server_group_id，weigth，port和force，然后这个资源的create就是 Attach，Delete 就是Detach，这个资源的ID是 scaling_group_id:alb_server_group_id
按照以上的逻辑再改下

2022-02-22 06:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	port := strconv.Itoa(d.Get("port").(int))
formatInt（d.Get("port")）

2022-02-22 06:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +		Weight:           strconv.Itoa(d.Get("weight").(int)),
formatInt（d.Get("weight")）

2022-02-22 06:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	strs := strings.Split(id, "_")
主键之间的分隔用 :, 另外不需要单独写分隔方法了 直接使用 ParseResourceId 这个方法

2022-02-22 06:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	d.SetId(combineId(scalingGroupId, albServerGroupId, port))
d.SetId(fmt.Sprint(scalingGroupId, ":", albServerGroupId, ":", port))

2022-02-22 06:38 UTC, xinmu0426 commented on website/docs/r/ess_alb_server_group_attachment.html.markdown
> +description: |- Provides a ESS Attachment resource to attach or remove alb server group.
|-  后面又个换行

2022-02-22 06:38 UTC, xinmu0426 commented on website/docs/r/ess_alb_server_group_attachment.html.markdown
> +For information about alb server group attachment,
多了个换行 For information about alb server group attachment, see [AttachAlbServerGroups](https://www.alibabacloud.com/help/en/doc-detail/266800.html).

2022-02-22 06:38 UTC, xinmu0426 commented on website/docs/r/ess_alb_server_group_attachment.html.markdown
> +* `scaling_group_id` - (Required) ID of the scaling group.
scaling_group_id  alb_server_group_id  port 缺少 ForceNew  说明

2022-02-22 06:38 UTC, xinmu0426 commented on CHANGELOG.md
> +- **New Resource:** `alicloud_ess_scalinggroup_alb_server_groups`
标题 New Resource: `alicloud_ess_alb_server_group_attachment`

2022-02-22 06:59 UTC, TalentNing commented on website/docs/r/ess_alb_server_group_attachment.html.markdown
> +description: |- Provides a ESS Attachment resource to attach or remove alb server group.
done

2022-02-22 06:59 UTC, TalentNing commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	d.SetId(combineId(scalingGroupId, albServerGroupId, port))
done

2022-02-22 06:59 UTC, TalentNing commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	strs := strings.Split(id, "_")
done

2022-02-22 06:59 UTC, TalentNing commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +		Weight:           strconv.Itoa(d.Get("weight").(int)),
done

2022-02-22 06:59 UTC, TalentNing commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	port := strconv.Itoa(d.Get("port").(int))
done

2022-02-22 06:59 UTC, TalentNing commented on website/docs/r/ess_alb_server_group_attachment.html.markdown
> +For information about alb server group attachment,
done

2022-02-22 07:01 UTC, TalentNing commented on website/docs/r/ess_alb_server_group_attachment.html.markdown
> +* `scaling_group_id` - (Required) ID of the scaling group.
done

2022-02-22 07:02 UTC, TalentNing commented on CHANGELOG.md
> +- **New Resource:** `alicloud_ess_scalinggroup_alb_server_groups`
done

2022-02-22 07:53 UTC, TalentNing commented on website/docs/r/ess_scalinggroup_alb_server_groups.html.markdown
> +
done

2022-02-22 08:18 UTC, xiaozhu36 requested changes

2022-02-22 08:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +					return old == "" && new == "true" && d.Id() != ""
force我理解不需要设置 DiffSuppressFunc

2022-02-22 08:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	request.ForceAttach = requests.NewBoolean(d.Get("force").(bool))
这个地方参数应该跟API的对齐，所以上面的 force 应该改成 force_attach

2022-02-22 08:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +			d.Set("force", d.Get("force").(bool))
set 的时候，不需要从 d.Get 中取

2022-02-22 08:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	if err := checkActivityStatus(client, response.ScalingActivityId, request.GetActionName()); err != nil {
使用标准的状态检查机制

2022-02-22 08:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +				Required: true,
weigth 是可以修改么？如果不能修改，那么应该改为 ForceNew

2022-02-22 08:32 UTC, TalentNing commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +					return old == "" && new == "true" && d.Id() != ""
已删除

2022-02-22 08:33 UTC, TalentNing commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	request.ForceAttach = requests.NewBoolean(d.Get("force").(bool))
已修改

2022-02-23 01:59 UTC, xiaozhu36 requested changes

2022-02-23 01:59 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +				Required: true,
这个参数是属性，即然属性无法修改，就必须设置为 forceNew

2022-02-23 01:59 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +				Default:  false,
这个Default 直接去掉

2022-02-23 02:43 UTC, merged