New Resource `alicloud_dcdn_ipa_domain`; New Datasource `alicloud_dcdn_ipa_domains`
aliyun/terraform-provider-alicloud pull request #4600
Opened 2022-02-22 07:13 UTC by super-eggs

New Resource `alicloud_dcdn_ipa_domain`;
New Datasource `alicloud_dcdn_ipa_domains`

2022-02-22 07:14 UTC, super-eggs commented on alicloud/resource_alicloud_dcdn_ipa_domain_test.go
> +func TestAccAlicloudDcdnIpaDomain_unit(t *testing.T) {
单测96.3%覆盖率

2022-02-24 07:13 UTC, xiaozhu36 requested changes

2022-02-24 07:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dcdn_ipa_domain_test.go
> +	}
如果报错了，直接return nil

2022-02-24 07:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dcdn_ipa_domain_test.go
> +					"resource_group_id": os.Getenv("ALICLOUD_RESOURCE_GROUP_ID"),
这个地方不要用环境变量，直接用一个新的资源

2022-02-24 10:52 UTC, merged