resource/alicloud_log_ingestion: add sls ingestion
aliyun/terraform-provider-alicloud pull request #4623
Opened 2022-03-01 09:30 UTC by HuiJing-C

2022-03-01 09:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4623) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4623) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=4623) it.</sub>

2022-03-07 02:14 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_ingestion.go
> +			Update: schema.DefaultTimeout(time.Minute),
和文档对不上

2022-03-07 02:14 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_ingestion.go
> +				Default:  "+0800",
不要有default值

2022-03-07 02:14 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_ingestion.go
> +				Default:  false,
Default 去掉

2022-03-07 02:14 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_ingestion_test.go
> +					"ingestion_name":  "test_ingestion",
ingestion_name 为ForceNew。 不需要更新

2022-03-07 02:14 UTC, xinmu0426 commented on website/docs/r/log_ingestion.html.markdown
> +$ terraform import alicloud_log_ingestion.example tf-log-project:tf-log-logstore:ingestion_name
改为 <project>:<logstore>:<ingetion_name> 吧

2022-03-07 02:33 UTC, HuiJing-C commented on alicloud/resource_alicloud_log_ingestion.go
> +			Update: schema.DefaultTimeout(time.Minute),
都是一分钟，哪里不一样

2022-03-07 02:33 UTC, HuiJing-C commented on alicloud/resource_alicloud_log_ingestion.go
> +				Default:  false,
default不需要了？那Optional就要变为Required了

2022-03-07 02:33 UTC, HuiJing-C commented on website/docs/r/log_ingestion.html.markdown
> +$ terraform import alicloud_log_ingestion.example tf-log-project:tf-log-logstore:ingestion_name
tf-log-project:tf-log-logstore:ingestion_name这不是id格式吗？确定要改成tf-log-project:tf-log-logstore::<ingestion_name>?

2022-03-07 02:43 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_ingestion.go
> +			Update: schema.DefaultTimeout(time.Minute),
规范下写法

2022-03-07 02:43 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_ingestion.go
> +				Default:  false,
这个字段在API中的语义是啥？不需要给他默认值，如有必要，让用户传

2022-03-07 02:44 UTC, xinmu0426 commented on website/docs/r/log_ingestion.html.markdown
> +$ terraform import alicloud_log_ingestion.example tf-log-project:tf-log-logstore:ingestion_name
说明Id是什么样的形式就可以了，给的实例中也不知道啥意思

2022-03-07 06:06 UTC, HuiJing-C commented on website/docs/r/log_ingestion.html.markdown
> +$ terraform import alicloud_log_ingestion.example tf-log-project:tf-log-logstore:ingestion_name
Attributes Reference给了id形式

2022-03-07 06:33 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_ingestion.go
> +				ForceNew: true,
补充一个正则校验

2022-03-07 06:33 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_ingestion.go
> +				Required: true,
补充一个枚举值校验，并且转换为标准的格式，eg h-> hour

2022-03-07 06:35 UTC, xinmu0426 commented on alicloud/provider.go
>  			"alicloud_log_dashboard":                                        resourceAlicloudLogDashboard(),
pr 标题加上更新了sdk

2022-03-07 07:03 UTC, HuiJing-C commented on alicloud/resource_alicloud_log_ingestion.go
> +				Required: true,
interval不是枚举值，只是有特定后缀（m,h,d）的字符串，不用加校验了吧

2022-03-07 07:03 UTC, HuiJing-C commented on alicloud/resource_alicloud_log_ingestion.go
> +				ForceNew: true,
done

2022-03-15 12:20 UTC, xiaozhu36 requested changes

2022-03-15 12:20 UTC, xiaozhu36 commented on website/docs/r/log_ingestion.html.markdown
> +-> **NOTE:** Available in 1.160.0+
下个版本是 1.161.0 了

2022-03-16 09:42 UTC, merged