testcase: Adds new unit test case for resource alicloud_event_bridge_event_source alicloud_event_bridge_event_bus alicloud_ga_listener
aliyun/terraform-provider-alicloud pull request #4633
Opened 2022-03-03 02:33 UTC by thisnihonglei

2022-03-03 02:37 UTC, thisnihonglei commented on alicloud/resource_alicloud_event_bridge_event_bus_test.go
> +func TestAccAlicloudEventBridgeEventBus_unit(t *testing.T) {
单测95.9%覆盖率

2022-03-03 02:37 UTC, thisnihonglei commented on alicloud/resource_alicloud_event_bridge_event_source_test.go
> +func TestAccAlicloudEventBridgeEventSource_unit(t *testing.T) {
单测95.1%覆盖率

2022-03-03 02:37 UTC, thisnihonglei commented on alicloud/resource_alicloud_ga_listener_test.go
> +func TestAccAlicloudGaListener_unit(t *testing.T) {
遇到问题，单测Delete函数中删除的异步等待超时，不能按预期跳出异步等待

2022-03-03 13:49 UTC, xiaozhu36 requested changes

2022-03-03 13:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_event_bridge_event_bus.go
> -	runtime.SetAutoretry(true)
这个不能删，对于支持 ClientToken 的，是允许自动重试的

2022-03-03 13:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_event_bridge_event_bus.go
> -	runtime := util.RuntimeOptions{}
这个也一样

2022-03-03 13:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_event_bridge_event_source.go
> -				Computed: true,
提交前有跑过集成测试么？

2022-03-03 13:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_event_bridge_event_source.go
> +	if !d.IsNewResource() && d.HasChange("external_source_type") {
这个地方为啥要加 !d.IsNewResource()

2022-03-03 13:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_listener.go
> +	var response map[string]interface{}
这个也一样

2022-03-03 13:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_listener.go
> +	if !d.IsNewResource() && d.HasChange("description") {
这个也一样

2022-03-04 02:33 UTC, thisnihonglei commented on alicloud/resource_alicloud_event_bridge_event_bus.go
> -	runtime.SetAutoretry(true)
done

2022-03-04 02:33 UTC, thisnihonglei commented on alicloud/resource_alicloud_event_bridge_event_bus.go
> -	runtime := util.RuntimeOptions{}
done

2022-03-04 02:33 UTC, thisnihonglei commented on alicloud/resource_alicloud_event_bridge_event_source.go
> +	if !d.IsNewResource() && d.HasChange("external_source_type") {
自动生成的，已去掉

2022-03-04 02:33 UTC, thisnihonglei commented on alicloud/resource_alicloud_ga_listener.go
> +	var response map[string]interface{}
done

2022-03-04 07:26 UTC, thisnihonglei commented on alicloud/resource_alicloud_event_bridge_event_source.go
> -				Computed: true,
集成测试发现产品API接口有问题，已联系产品询问问题原因，问题现已解决。

2022-03-04 07:30 UTC, thisnihonglei commented on alicloud/resource_alicloud_event_bridge_event_source.go
> +	if v, ok := d.GetOk("external_source_type"); ok {
产品回复说这里有个限制，Update的时候，externalSourceType不能变化，所以这个参数放在HasChange判断外面

2022-03-04 12:38 UTC, xiaozhu36 requested changes

2022-03-04 12:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_event_bridge_event_source.go
> +	if v, ok := d.GetOk("linked_external_source"); ok {
对于bool类型的，需要用 GetOkExists

2022-03-04 12:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_listener.go
>  			Delete: schema.DefaultTimeout(6 * time.Minute),
create 的timeout 不要删

2022-03-04 12:38 UTC, xiaozhu36 commented on alicloud/service_alicloud_eventbridge.go
> +		resp, err := conn.DoRequest(StringPointer(action), nil, StringPointer("POST"), StringPointer("2020-04-01"), StringPointer("AK"), nil, request, &util.RuntimeOptions{})
这个最后应该是 runtime

2022-03-05 11:17 UTC, thisnihonglei commented on alicloud/resource_alicloud_event_bridge_event_source.go
> +	if v, ok := d.GetOk("linked_external_source"); ok {
done

2022-03-05 11:19 UTC, thisnihonglei commented on alicloud/service_alicloud_eventbridge.go
> +		resp, err := conn.DoRequest(StringPointer(action), nil, StringPointer("POST"), StringPointer("2020-04-01"), StringPointer("AK"), nil, request, &util.RuntimeOptions{})
done

2022-03-05 11:19 UTC, thisnihonglei commented on alicloud/resource_alicloud_ga_listener.go
>  			Delete: schema.DefaultTimeout(6 * time.Minute),
done

2022-04-08 08:05 UTC, closed without merging