testcase: Adds new unit test case for resource testcase: alicloud_resource_manager_folder alicloud_resource_manager_handshake alicloud_ga_ip_set
aliyun/terraform-provider-alicloud pull request #4636
Opened 2022-03-03 09:48 UTC by thisnihonglei

2022-03-03 10:29 UTC, thisnihonglei commented on alicloud/resource_alicloud_ga_ip_set_test.go
> +func TestAccAlicloudGaIpSet_unit(t *testing.T) {
遇到问题，单测Delete函数中删除的异步等待超时，不能按预期跳出异步等待

2022-03-03 10:29 UTC, thisnihonglei commented on alicloud/resource_alicloud_resource_manager_folder_test.go
> +func TestAccAlicloudResourceManagerFolder_unit(t *testing.T) {
单测100%覆盖率

2022-03-03 10:29 UTC, thisnihonglei commented on alicloud/resource_alicloud_resource_manager_handshake_test.go
> +func TestAccAlicloudResourceManagerHandshake_unit(t *testing.T) {
单测100%覆盖率

2022-03-04 09:24 UTC, xiaozhu36 requested changes

2022-03-04 09:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_ip_set.go
>  		},
这个时间先恢复原状，现在自动生成的还有问题

2022-03-04 09:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_ip_set.go
> +	return resourceAlicloudGaIpSetUpdate(d, meta)
这个应该是 read 吧

2022-03-04 09:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_ip_set_test.go
> +			Message: String(errorCode),
以后在Message 的下方都要加上 StatusCode: tea.Int(400),
自动生成的时候已经支持了

2022-03-04 09:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_resource_manager_folder.go
> +	if !d.IsNewResource() && d.HasChange("folder_name") {
这个应该不需要判断 !d.IsNewResource

2022-03-04 09:24 UTC, xiaozhu36 commented on alicloud/service_alicloud_ga.go
> +			return object, WrapErrorf(err, NotFoundMsg, AlibabaCloudSdkGoERROR)
这个地方不应该改

2022-03-04 09:24 UTC, xiaozhu36 commented on alicloud/service_alicloud_resourcemanager.go
> -			return object, err
这个地方也一样

2022-03-04 09:45 UTC, thisnihonglei commented on alicloud/resource_alicloud_ga_ip_set.go
>  		},
done

2022-03-04 09:45 UTC, thisnihonglei commented on alicloud/resource_alicloud_resource_manager_folder.go
> +	if !d.IsNewResource() && d.HasChange("folder_name") {
done

2022-03-04 09:45 UTC, thisnihonglei commented on alicloud/service_alicloud_ga.go
> +			return object, WrapErrorf(err, NotFoundMsg, AlibabaCloudSdkGoERROR)
done

2022-03-04 09:45 UTC, thisnihonglei commented on alicloud/service_alicloud_resourcemanager.go
> -			return object, err
done

2022-03-04 09:45 UTC, thisnihonglei commented on alicloud/resource_alicloud_ga_ip_set.go
>  		},
done

2022-03-04 09:47 UTC, thisnihonglei commented on alicloud/resource_alicloud_ga_ip_set.go
> +	return resourceAlicloudGaIpSetUpdate(d, meta)
done

2022-03-04 09:47 UTC, thisnihonglei commented on alicloud/resource_alicloud_ga_ip_set_test.go
> +			Message: String(errorCode),
done

2022-03-04 09:48 UTC, thisnihonglei commented on alicloud/resource_alicloud_resource_manager_folder.go
> +	if !d.IsNewResource() && d.HasChange("folder_name") {
done

2022-03-04 12:33 UTC, merged