resource/alicloud_mongodb_sharding_instance: Updates its dependence SDK.
aliyun/terraform-provider-alicloud pull request #4650
Opened 2022-03-08 06:19 UTC by super-eggs

resource/alicloud_mongodb_sharding_instance: Updates its dependence SDK.

2022-03-08 06:40 UTC, xinmu0426 commented on website/docs/r/mongodb_sharding_instance.html.markdown
文档缺 description

2022-03-08 06:40 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
>  	"log"
pr 标题加上Support for new parameters `network_type`, `vpc_id`, `protocol_type`, `resource_group_id`

2022-03-08 06:59 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
> -				Type:         schema.TypeString,
engine_version 枚举值陪一下 https://help.aliyun.com/document_detail/61884.html

2022-03-08 06:59 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
> +			"description": {
这个字段可以不要，就按照name来吧 ，

2022-03-08 06:59 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
> +	if v, ok := d.GetOk("vpc_id"); ok {
这块处理的不对

2022-03-08 06:59 UTC, xinmu0426 commented on website/docs/r/mongodb_sharding_instance.html.markdown
> +* `name` - (Optional, Computed, Deprecated from v160.0+) Field `name` has been deprecated from version 1.160.0. Use `description` instead.
这块不需要了

2022-03-08 07:18 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_sharding_instance_test.go
> +			//testAccPreCheckWithTime(t, []int{30})
remove

2022-03-08 07:18 UTC, xinmu0426 commented on alicloud/resource_alicloud_mongodb_sharding_instance_test.go
> +			//testAccPreCheckWithTime(t, []int{1})
remove

2022-03-10 06:36 UTC, xiaozhu36 requested changes

2022-03-10 06:36 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
>  		// check vswitchId in zone
这个地方应该改为 if request["VpcId"] == nil && request["VSwitchId"] != nil

2022-03-10 06:36 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
>  		// check vswitchId in zone
另外，如果vswitch 不为空，network type 为空，那么这是时候要把network type 切换到 vpc 上

2022-03-10 09:57 UTC, super-eggs commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
>  		// check vswitchId in zone
1，这里我将 `request["VpcId"] == nil` 的情况放在了 `request["VSwitchId"] != nil` 的判断里边，因为之前的代码在如果 ZoneId 为空的情况下，会进行查询赋值。
2，NetworkType 为空的逻辑判断已添加。

2022-03-13 01:21 UTC, xiaozhu36 requested changes

2022-03-13 01:21 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
> +				Computed: true,
资源组是支持修改的： https://help.aliyun.com/document_detail/291345.html

2022-03-13 01:21 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
>  		// check vswitchId in zone
这个地方之所以查询，是因为要查到 vswitch 所在的zone和vpc，如果vpc和zone都已经设置了，那么就不需要再查了，日过其中一个没有设置，再查

2022-03-13 01:21 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
> +		err = resource.Retry(d.Timeout(schema.TimeoutCreate), func() *resource.RetryError {
应该是 Timeout Update

2022-03-13 01:21 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
> +		err = resource.Retry(d.Timeout(schema.TimeoutCreate), func() *resource.RetryError {
这个地方也一样

2022-03-14 12:14 UTC, xiaozhu36 requested changes

2022-03-14 12:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
> +			// check vswitchId in zone
这个地方直接改成 if (request["ZoneId"] == nil || request["VpcId"] == nil) && request["VSwitchId"] != nil

2022-03-14 12:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_instance_test.go
> +  		status = "OK"
改成 name_regex = "default"

2022-03-15 02:38 UTC, super-eggs commented on alicloud/resource_alicloud_mongodb_sharding_instance_test.go
> +  		status = "OK"
这里需要对 resource_group_id 进行更新，所以要取到两个值。

2022-03-15 02:48 UTC, super-eggs commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
> +			// check vswitchId in zone
``` golang
if request["VSwitchId"] != nil {
  if request["ZoneId"] == nil || request["VpcId"] == nil {...}
  if request["NetworkType"] == nil {...}
}
```
以后这种逻辑都处理成下面这样吗？

``` golang
if request["VSwitchId"] != nil && (request["ZoneId"] == nil || request["VpcId"] == nil) {...}
if request["VSwitchId"] != nil && request["NetworkType"] == nil {...}
```

2022-03-15 06:19 UTC, xiaozhu36 approved these changes

2022-03-15 06:19 UTC, merged