New data `alicloud_log_alert_resource`, Update resource `alicloud_log_alert`
aliyun/terraform-provider-alicloud pull request #4658
Opened 2022-03-09 09:17 UTC by panawala

2022-03-09 09:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4658) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4658) before we can accept your contribution.<br/><hr/>**huolang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=4658) it.</sub>

2022-03-09 09:38 UTC, xinmu0426 commented on alicloud/provider.go
> +			"alicloud_log_alert_resource":                          dataSourceAlicloudLogAlertResource(),
alicloud_log_alert_resource 这个叫 alicloud_log_alert_service是不是更好些

2022-03-09 09:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_alert_resource.go
> +				request.Language = lang
如果重复调用会不会出错？

2022-03-09 09:38 UTC, xinmu0426 commented on alicloud/provider.go
>  			"alicloud_alidns_instances":                            dataSourceAlicloudAlidnsInstances(),
评论添加下每个测试用例的测试结果

2022-03-09 09:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_alert_resource_test.go
> +resource "alicloud_log_alert_resource" "current_user" {
这块不对吧

2022-03-09 09:38 UTC, xinmu0426 commented on website/docs/r/log_alert.html.markdown
> +Basic Usage for new alert
如果只是不推荐使用老的alert 的话 ，建议直接替换用例，老的直接下线吧

2022-03-09 09:38 UTC, xinmu0426 commented on website/docs/r/log_alert.html.markdown
> +* `dashboard` - (Required, Deprecated) The name of the dashboard associated with the alarm. The name of the instrument cluster associated with the alarm. If there is no such instrument cluster, terra
Deprecated from 1.160.0+

2022-03-09 09:38 UTC, xinmu0426 commented on website/docs/r/log_alert.html.markdown
> +* `dashboard` - (Required, Deprecated) The name of the dashboard associated with the alarm. The name of the instrument cluster associated with the alarm. If there is no such instrument cluster, terra
optional for new alert. 删掉，下同

2022-03-09 09:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_alert.go
> +				Deprecated: "deprecated in new alert",
参考 alicloud_instance Deprecated 的写法

2022-03-09 09:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_alert.go
> -						"logstore": {
不要吧logstore 直接删除

2022-03-09 09:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_alert.go
> +				Elem: &schema.Schema{
和文档定义对不上

2022-03-09 09:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_alert.go
> +							Type:     schema.TypeInt,
配上枚举值校验

2022-03-09 09:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_alert.go
> +							Type:     schema.TypeString,
配上枚举值校验

2022-03-09 09:38 UTC, xinmu0426 commented on alicloud/resource_alicloud_log_alert.go
> +			"labels": {
新增字段都看下，大量文档上定义为 Optioanl 但是 此处为Required

2022-03-10 04:03 UTC, panawala commented
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLogAlert -timeout=300m
=== RUN   TestAccAlicloudLogAlertResourceDataSource
--- PASS: TestAccAlicloudLogAlertResourceDataSource (7.74s)
=== RUN   TestAccAlicloudLogAlert_basic
--- PASS: TestAccAlicloudLogAlert_basic (93.57s)
=== RUN   TestAccAlicloudLogAlert_basic_new
--- PASS: TestAccAlicloudLogAlert_basic_new (96.16s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  197.557s

2022-03-11 02:30 UTC, xinmu0426 commented on alicloud/data_source_alicloud_log_alert_resource_test.go
> +  region        = "cn-hangzhou"
region 不要写死 用 defaultRegionToTest

2022-03-11 02:30 UTC, xinmu0426 commented on alicloud/data_source_alicloud_log_alert_resource.go
> +	region := d.Get("region").(string)
为啥不用client.RegionId

2022-03-16 08:17 UTC, xiaozhu36 requested changes

2022-03-16 08:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_alert.go
> -				Default:  1,
默认值不能直接删除，如果存在系统默认值，那么要加上 Computed：true

2022-03-16 08:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_alert.go
> +				Optional: true,
resource中，对于复杂结构，要使用 TypeSet
下同

2022-03-16 08:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_alert.go
> -	d.Set("notify_threshold", object.Configuration.NotifyThreshold)
对于弃用的，参数，不能直接删除，还是要返回的

2022-03-16 08:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_alert.go
> -	d.Set("notify_threshold", object.Configuration.NotifyThreshold)
可以参考下其他资源属性的弃用是怎么写的

2022-03-16 08:17 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_log_alert_resource_test.go
> +  project       = "test-tf-ut"
这个project 可以是一个假的name么，如果不是，那么应该要创建一个新的

2022-03-18 00:58 UTC, xiaozhu36 requested changes

2022-03-18 00:58 UTC, xiaozhu36 commented on website/docs/r/log_alert.html.markdown
> +* `threshold` - (Optional) Evaluation threshold, alert will not fire until the number of triggers is reached. The default is 1.
对于新增加的字段，只需要在每个字段中标注为从哪个版本开始可用就好了，比如 * `threshold` - (Optional, Available in 1.161.0+)

2022-03-18 04:48 UTC, panawala commented
最新commit测试结果

$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLogAlert -timeout=300m
=== RUN   TestAccAlicloudLogAlertResourceDataSource
--- PASS: TestAccAlicloudLogAlertResourceDataSource (16.80s)
=== RUN   TestAccAlicloudLogAlert_basic
--- PASS: TestAccAlicloudLogAlert_basic (92.25s)
=== RUN   TestAccAlicloudLogAlert_basic_new
--- PASS: TestAccAlicloudLogAlert_basic_new (95.20s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  204.346s

2022-03-18 09:05 UTC, xiaozhu36 requested changes

2022-03-18 09:05 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_alert.go
> +				Default:  "",
如果是空的话，不要 Default

2022-03-18 09:52 UTC, merged