New resource alicloud_cr_chain and its datasource.
aliyun/terraform-provider-alicloud pull request #4696
Opened 2022-03-14 07:40 UTC by ChenHanZhang

2022-03-14 11:34 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chain.go
> +		if v, ok := d.GetOk("description"); ok {
d.Get直接从HasChange里拿出来吧 , 全部传给CR

2022-03-14 11:34 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chain_test.go
> +	if err != nil {
这里直接log.Printf() 然后return nil吧, 别阻塞CI里其他pipeline的流程, 后续也改下

2022-03-14 11:34 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chain_test.go
> +  payment_type        = "Subscription"
用按量付费的, 自动续费的也关闭吧

2022-03-14 11:34 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chain.go
> +		conn, err := client.NewAcrClient()
`conn, err := client.NewAcrClient()` 和err  也从update里抽出来放在update开头

2022-03-14 11:34 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chain.go
> +							Type:     schema.TypeList,
这里为啥List 和 Set交叉用?  复杂结构的Object现在统一用成了TypeSet

2022-03-14 11:34 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_cr_chains_test.go
> +			"ids": `["${alicloud_cr_chain.default.chain_id}"]`,
把enable_details打开测试下, 确保get方法没问题

2022-03-14 11:34 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_cr_chains_test.go
> +  payment_type   = "Subscription"
按量付费  自动续费也要取消

2022-03-14 12:10 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cr_chain_test.go
> +	if err != nil {
done

2022-03-14 12:36 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cr_chain_test.go
> +  payment_type        = "Subscription"
自动续费改成手动续费了

2022-03-14 12:36 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_cr_chains_test.go
> +  payment_type   = "Subscription"
自动续费改成手动续费了

2022-03-16 06:42 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_cr_chains_test.go
> +  payment_type   = "Subscription"
那就改成每月1日进行跑吧  用 testAccPreCheckWithTime 这个

2022-03-16 06:42 UTC, Wanghx0991 commented on website/docs/d/cr_chains.html.markdown
> +## Argument Reference
这个应该是手写的吧?  ## Attributes Reference

2022-03-16 06:42 UTC, Wanghx0991 commented on website/docs/d/cr_chains.html.markdown
> +* `ids` - (Optional, ForceNew, Computed)  A list of Chain IDs.
Computed是不用对外透出的

2022-03-16 06:42 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chain.go
> +	if _, ok := d.GetOk("chain_config"); ok {
d.Get("chain_config").(*schema.Set).List() 这里需要加个判断, chain_config本身是可选字段, 如果用户在模板里没有的话 这样转会panic

2022-03-16 06:42 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chain.go
> +		if err != nil {
移到conn, err := client.NewAcrClient()后面 错误处理

2022-03-16 06:42 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chain.go
> +		request["ChainConfig"], _ = convertCrChainConfigToJsonString(d.Get("chain_config").(*schema.Set).List())
这里也是 必选字段这样转没问题, 但可选字段如果强转是直接会panic

2022-03-16 06:47 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cr_chain.go
> +					for _, fromNode := range routerParameters["from"].(*schema.Set).List() {
统一看一下这种可选字段的强转问题吧

2022-03-16 10:46 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_cr_chains_test.go
> +  payment_type   = "Subscription"
done

2022-03-16 10:47 UTC, ChenHanZhang commented on website/docs/d/cr_chains.html.markdown
> +## Argument Reference
done

2022-03-16 13:46 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cr_chain.go
> +	if _, ok := d.GetOk("chain_config"); ok {
这里在d.GetOK里，如果chain_config没有值不会进的

2022-03-16 13:49 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cr_chain.go
> +		request["ChainConfig"], _ = convertCrChainConfigToJsonString(d.Get("chain_config").(*schema.Set).List())
done

2022-03-16 16:23 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cr_chain.go
> +					for _, fromNode := range routerParameters["from"].(*schema.Set).List() {
done

2022-03-18 12:51 UTC, xiaozhu36 requested changes

2022-03-18 12:51 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cr_chains_test.go
> +		testAccPreCheckWithTime(t, []int{1})
以后去掉这个时间限制

2022-03-18 12:51 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cr_chains_test.go
> +  payment_type   = "Subscription"
以后不用改成 1月跑一次

2022-03-18 12:51 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cr_chains_test.go
> +  count          = length(data.alicloud_cr_ee_instances.default.ids) > 0 ? 0 : 1
这个资源不需要创建，直接用上面的查就好了

2022-03-18 12:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_chain.go
> +							Type:     schema.TypeList,
既然有有序的，那么就都改成List 吧

2022-03-18 12:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_chain_test.go
> +  payment_type        = "Subscription"
这个也一样，直接用查的

2022-03-18 13:12 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_cr_chains_test.go
> +  count          = length(data.alicloud_cr_ee_instances.default.ids) > 0 ? 0 : 1
这个我改成datasource查名为tf-testacc*的instance了，如果不存在还是创建一个

2022-03-18 13:17 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cr_chain_test.go
> +  payment_type        = "Subscription"
同样，如果查到了name_regex为"tf-testaccxxx"的，直接使用DataSource，否则还是需要创建一个

2022-03-18 13:19 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_cr_chains_test.go
> +  payment_type   = "Subscription"
done

2022-03-18 13:19 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_cr_chains_test.go
> +		testAccPreCheckWithTime(t, []int{1})
done

2022-03-18 14:09 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cr_chain.go
> +							Type:     schema.TypeList,
经过打包到本地进行测试，统一为TypeSet测试没问题。之前的diff是create和get的顺序不同，使用list可以严格按照get出的顺序进行create，在tf的测试日志中看到的次序不同，但这个不影响

2022-03-18 14:10 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cr_chain.go
> +							Type:     schema.TypeList,
经过打包到本地进行测试，统一为TypeSet测试没问题。之前的diff是create和get的顺序不同，使用list可以严格按照get出的顺序进行create，在tf的测试日志中看到的次序不同，这个是否有影响？

2022-03-18 14:40 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cr_chains.go
> +				Type:     schema.TypeSet,
datasource 中都是 list

2022-03-18 14:41 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cr_chains_test.go
> +  name        = "my-repo"
用 var.name

2022-03-18 14:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_chain_test.go
> +				ImportStateVerify: true, ImportStateVerifyIgnore: []string{"repo_namespace_name", "repo_name"},
这两个没有返回，有开aone么

2022-03-18 14:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cr_chain_test.go
> +  name               = "my-namespace"
var。name

2022-03-18 14:48 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cr_chain_test.go
> +				ImportStateVerify: true, ImportStateVerifyIgnore: []string{"repo_namespace_name", "repo_name"},
这两个是查询参数，Aone我开一下

2022-03-18 14:55 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_cr_chains.go
> +				Type:     schema.TypeSet,
done

2022-03-18 15:05 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cr_chain_test.go
> +  name               = "my-namespace"
done

2022-03-18 15:05 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_cr_chains_test.go
> +  name        = "my-repo"
done

2022-03-18 15:31 UTC, merged