New Resource `alicloud_vpn_ipsec_server`;New Datasource `alicloud_vpn_ipsec_servers`; data_source/alicloud_vpn_gateways: Adds new parameter `enable_ipsec`.
aliyun/terraform-provider-alicloud pull request #4705
Opened 2022-03-15 07:30 UTC by super-eggs

New Resource `alicloud_vpc_ipsec_server`;
New Datasource `alicloud_vpc_ipsec_servers`

2022-03-15 07:31 UTC, super-eggs commented on alicloud/resource_alicloud_vpc_ipsec_server_test.go
> +func TestAccAlicloudVpcIpsecServer_unit(t *testing.T) {
单测覆盖率:98.1%.

2022-03-15 09:31 UTC, xinmu0426 commented on alicloud/connectivity/regions.go
> +var VPCSupportRegions = []Region{ShanghaiFinance, GuangZhou, APSouthEast3, USEast1, HeYuan, ChengDu, APSouthEast1, USWest1, CnNorth2Gov1, Zhangjiakou, APSouthEast2, Huhehaote, Hongkong, Shenzhen, MEE
这个去掉吧

2022-03-15 09:31 UTC, xinmu0426 commented on alicloud/data_source_alicloud_vpc_ipsec_servers.go
> +			ipsecConfigMap["ipsec_auth_alg"] = ipsecConfig.(map[string]interface{})["IpsecAuthAlg"]
ipsecConfig.(map[string]interface{}) 不需要 写多次吧

2022-03-15 09:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_vpc_ipsec_server.go
> +		},
加上timeouts

2022-03-15 09:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_vpc_ipsec_server.go
> +			ipsecConfigMap["ipsec_auth_alg"] = ipsecConfig.(map[string]interface{})["IpsecAuthAlg"]
ipsecConfig.(map[string]interface{}) 改为一次

2022-03-15 09:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_vpc_ipsec_server.go
> +							Optional: true,
枚举值配置下

2022-03-15 09:51 UTC, super-eggs commented on alicloud/resource_alicloud_vpc_ipsec_server.go
> +							Optional: true,
这个没有枚举值吧？https://help.aliyun.com/document_detail/205454.html

2022-03-16 14:54 UTC, xiaozhu36 requested changes

2022-03-16 14:54 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_vpc_ipsec_servers_test.go
> +	vswitch_id = local.vswitch_id
如果依赖一个预付费的资源，那么用datasource来查询这个资源

2022-03-16 14:54 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_vpc_ipsec_servers_test.go
> +		testAccPreCheckWithTime(t, []int{1})
以后testAccPreCheckWithTime(t, []int{1})这种可以直接去掉了

2022-03-16 14:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_ipsec_server_test.go
> +	instance_charge_type = "PrePaid"
这个地方也是一样

2022-03-16 14:54 UTC, xiaozhu36 commented on website/docs/r/cddc_dedicated_host.html.markdown
> +The following attributes are e\xported:
这个不对吧

2022-03-17 07:04 UTC, xiaozhu36 requested changes

2022-03-17 07:04 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_vpn_gateways_test.go
> +			"enable_ipsec":    `true`,
这个地方能查到么？模板中在创建 vpn 的时候，参数中我看没有指定 enable_ipsec 啊

2022-03-17 07:04 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_vpc_ipsec_servers_test.go
> +  count                = length(data.alicloud_vpn_gateways.default.ids) > 0 ? 0 : 1
这个地方没必要创建新的，直接查吧，即使创建了也删不掉

2022-03-17 07:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_ipsec_server_test.go
> +  count                = length(data.alicloud_vpn_gateways.default.ids) > 0 ? 0 : 1
这个地方也一样

2022-03-17 07:04 UTC, xiaozhu36 commented on website/docs/d/vpc_ipsec_servers.html.markdown
> +subcategory: "VPC"
应该放在 VPN下，这个resource和datasource也应该是 alicloud_vpn_xxx

2022-03-17 07:07 UTC, super-eggs commented on alicloud/data_source_alicloud_vpn_gateways_test.go
> +			"enable_ipsec":    `true`,
可以查到，enable_ipsec 默认是开启的。那我加上吧，这样看起来清楚点。

2022-03-18 01:27 UTC, merged