resource/alicloud_sae_application: Support field  min_ready_instance_ratio datasource/alicloud_sae_applications: fix the type mount_desc issue
aliyun/terraform-provider-alicloud pull request #4707
Opened 2022-03-15 08:27 UTC by Wanghx0991

2022-03-15 08:30 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_sae_applications.go
> -							Type:     schema.TypeString,
生成的有点问题, api返回的是arrayObject, 定义成了string, 在MarkDown里已经加了Note标注

2022-03-15 08:30 UTC, Wanghx0991 commented on alicloud/resource_alicloud_sae_application.go
> +	if d.HasChange("package_version") {
这块用户反馈说不能支持自己定义package_version,之前沟通结论是说给成时间戳形式,  目前跟sae那边开发沟通, 还是开放给用户修改, 如果不传再去给成时间戳的形式

2022-03-18 12:37 UTC, xiaozhu36 requested changes

2022-03-18 12:37 UTC, xiaozhu36 commented on website/docs/d/sae_applications.html.markdown
> +	* `mount_desc` - Mount description information. **NOTE:** Since v1.161.0+, the type of the field `mount_desc` has been converted from a `TypeString` to `TypeSet`. The details see Block mount_desc.
sae application 这个datasource也直接把整个datasoure改成 从 下个版本可用就行了

2022-03-18 12:37 UTC, xiaozhu36 commented on website/docs/r/sae_application.html.markdown
> +* `vpc_id` - (Optional, ForceNew, Available in v1.161.0+) The vpc id.
上面有了，这个地方就不用了

2022-03-18 12:37 UTC, xiaozhu36 commented on website/docs/r/sae_application.html.markdown
> +* `min_ready_instance_ratio` - (Optional,Available in v1.161.0+) Minimum Survival Instance Percentage. **NOTE:** When `min_ready_instances` and `min_ready_instance_ratio` are passed at the same time,
还有这

2022-03-18 15:07 UTC, Wanghx0991 commented on website/docs/r/sae_application.html.markdown
> +* `vpc_id` - (Optional, ForceNew, Available in v1.161.0+) The vpc id.
Done

2022-03-18 15:07 UTC, Wanghx0991 commented on website/docs/r/sae_application.html.markdown
> +* `min_ready_instance_ratio` - (Optional,Available in v1.161.0+) Minimum Survival Instance Percentage. **NOTE:** When `min_ready_instances` and `min_ready_instance_ratio` are passed at the same time,
Done

2022-03-18 15:32 UTC, merged