New Resource `alicloud_mse_znode`; New Datasource `alicloud_mse_znodes`; resource/alicloud_mse_cluster: Add support for output parameters `cluster_id`.
aliyun/terraform-provider-alicloud pull request #4757
Opened 2022-03-21 08:21 UTC by super-eggs

New Resource `alicloud_mse_znode`;
New Datasource `alicloud_mse_znodes`;
resource/alicloud_mse_cluster: Add support for output parameters `cluster_id`.

2022-03-22 06:32 UTC, xinmu0426 commented on alicloud/data_source_alicloud_mse_znodes.go
> +		request["Path"] = "/"
这个默认值不用

2022-03-22 06:32 UTC, xinmu0426 commented on alicloud/resource_alicloud_mse_znode.go
> +		request["Path"] = v
必填不用判断

2022-03-22 06:32 UTC, xinmu0426 commented on website/docs/d/mse_znodes.html.markdown
> +* `path` - (Optional, ForceNew) The Node path. Default: `/`.
Default: `/`. 这个也去掉

2022-03-22 06:32 UTC, xinmu0426 commented on website/docs/r/mse_cluster.html.markdown
> +* `cluster_id` - (Available in v1.162.0+)  The id of Cluster.
为啥又有一个id

2022-03-24 06:45 UTC, super-eggs commented on website/docs/r/mse_cluster.html.markdown
> +* `cluster_id` - (Available in v1.162.0+)  The id of Cluster.
mse_cluster 资源默认使用 InstanceId 属性作为其主键id，其实还有一个属性值为 clusterId。而 mse_znodes 关联 mse_cluster 的 clusterId 属性。

2022-03-24 07:01 UTC, super-eggs commented on alicloud/resource_alicloud_mse_znode_test.go
> +func TestAccAlicloudMseZnode_unit(t *testing.T) {
单侧覆盖率 97%.

2022-03-24 07:14 UTC, xiaozhu36 requested changes

2022-03-24 07:14 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_mse_znodes_test.go
> +  default = "/tf-testAccZnode-%d"
必须得加个/前缀么

2022-03-24 07:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mse_znode_test.go
> +	t.Run("CreateClientAbnormal", func(t *testing.T) {
单元测试改成新的方式，可以请教下 倪洪磊

2022-03-24 07:15 UTC, super-eggs commented on alicloud/data_source_alicloud_mse_znodes_test.go
> +  default = "/tf-testAccZnode-%d"
嗯嗯， path 属性要求以 / 开头。

2022-03-24 09:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mse_znode.go
> +	d.SetId(fmt.Sprint(request["Path"], ":", request["ClusterId"]))
这个反了吧，应该 是 clusterId ：Path 吧

2022-03-24 10:12 UTC, super-eggs commented on alicloud/resource_alicloud_mse_znode.go
> +	d.SetId(fmt.Sprint(request["Path"], ":", request["ClusterId"]))
已改正

2022-03-24 11:50 UTC, merged