datasource/alicloud_alb_rules: Adds output variable `rule_actions.traffic_limit_config`, `rule_actions.traffic_mirror_config` and `rule_conditions.source_ip_config`.  resource/alicloud_alb_rule: Support for new parameters `rule_actions.traffic_limit_config`, `rule_actions.traffic_mirror_config` and `rule_conditions.source_ip_config`.
aliyun/terraform-provider-alicloud pull request #4773
Opened 2022-03-23 08:02 UTC by super-eggs

datasource/alicloud_alb_rules: Adds output variable `rule_actions.traffic_limit_config`, `rule_actions.traffic_mirror_config` and `rule_conditions.source_ip_config`.  resource/alicloud_alb_rule: Support for new parameters `rule_actions.traffic_limit_config`, `rule_actions.traffic_mirror_config` and `rule_conditions.source_ip_config`.

2022-03-23 09:20 UTC, xinmu0426 commented on alicloud/data_source_alicloud_alb_rules.go
>  									},
datasource的测试文件中加一下这些字段

2022-03-23 09:20 UTC, xinmu0426 commented on alicloud/resource_alicloud_alb_rule.go
> +												},
如果存量没有这个字段 ，会出错么

2022-03-23 09:20 UTC, xinmu0426 commented on alicloud/resource_alicloud_alb_rule.go
> +		for _, trafficLimitConfig := range ruleActionsArg["traffic_limit_config"].(*schema.Set).List() {
这块要改下

2022-03-23 09:20 UTC, xinmu0426 commented on website/docs/d/alb_rules.html.markdown
> +        * `source_ip_config` - (Available in 1.162.0+) The Based on source IP traffic matching.
datasource中不需要 (Available in 1.162.0+)

2022-03-24 05:45 UTC, super-eggs commented on alicloud/resource_alicloud_alb_rule.go
> +												},
这个有默认值，已添加 Computed。

2022-03-24 06:17 UTC, super-eggs commented on alicloud/data_source_alicloud_alb_rules.go
>  									},
已添加

2022-03-24 07:22 UTC, xiaozhu36 requested changes

2022-03-24 07:22 UTC, xiaozhu36 commented on website/docs/d/alb_rules.html.markdown
> -        * `type` - The action. Valid values: `ForwardGroup`, `Redirect`, `FixedResponse`, `Rewrite`, `InsertHeader`.
这个为啥删掉

2022-03-24 07:27 UTC, super-eggs commented on website/docs/d/alb_rules.html.markdown
> -        * `type` - The action. Valid values: `ForwardGroup`, `Redirect`, `FixedResponse`, `Rewrite`, `InsertHeader`.
我的理解， datasource 文档里一般不填写 Valid values，并且可选值有新增。可选值新增已经在 resource 文档里添加了， 这里就没必要再描述了。

2022-03-24 07:59 UTC, merged