testcase: Adds new unit test case for resource alicloud_cloud_firewall_control_policy_order alicloud_cloud_firewall_instance alicloud_cms_metric_rule_template
aliyun/terraform-provider-alicloud pull request #4792
Opened 2022-03-25 09:35 UTC by thisnihonglei

2022-03-25 09:36 UTC, thisnihonglei commented on alicloud/resource_alicloud_cloud_firewall_control_policy_order_test.go
> +func TestAccAlicloudCloudFirewallControlPolicyOrder_unit(t *testing.T) {
单测覆盖率97.2%

2022-03-25 09:36 UTC, thisnihonglei commented on alicloud/resource_alicloud_cloud_firewall_instance_test.go
> +func TestAccAlicloudCloudFirewallInstance_unit(t *testing.T) {
单测覆盖率90.0%

2022-03-25 09:36 UTC, thisnihonglei commented on alicloud/resource_alicloud_cms_metric_rule_template_test.go
> +func TestAccAlicloudCloudMonitorServiceMetricRuleTemplate_unit(t *testing.T) {
单测覆盖率97.8%

2022-03-26 10:54 UTC, xiaozhu36 requested changes

2022-03-26 10:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cms_metric_rule_template.go
> +				Optional: true,
这个在update中可以修改啊，那就不应该是 forcenew 的

2022-03-26 19:15 UTC, thisnihonglei commented on alicloud/resource_alicloud_cms_metric_rule_template.go
> +				Optional: true,
done

2022-03-29 02:53 UTC, thisnihonglei commented on alicloud/resource_alicloud_mongodb_sharding_network_private_address.go
> +	stateConf := BuildStateConf([]string{}, []string{"Running"}, d.Timeout(schema.TimeoutCreate), 5*time.Second, ddsService.RdsMongodbDBInstanceStateRefreshFunc(fmt.Sprint(request["DBInstanceId"]), []st
异步等待时间5分钟，改成了5秒

2022-03-29 06:03 UTC, merged