New Resource `alicloud_ecs_image_pipeline`; New Datasource `alicloud_ecs_image_pipelines`; New Datasource `alicloud_ecs_image_support_instance_types`.
aliyun/terraform-provider-alicloud pull request #4798
Opened 2022-03-28 09:32 UTC by super-eggs

New Resource `alicloud_ecs_image_pipeline`;
New Datasource `alicloud_ecs_image_pipelines`;
New Datasource `alicloud_ecs_image_support_instance_types`.

2022-03-28 10:37 UTC, super-eggs commented on alicloud/resource_alicloud_ecs_image_pipeline_test.go
> +func TestAccAlicloudEcsImagePipeline_unit(t *testing.T) {
单测覆盖率 100%.

2022-03-28 11:45 UTC, xinmu0426 commented on website/docs/r/ecs_image_pipeline.html.markdown
> +* `base_image` - (Required, ForceNew) The source image. When you set BaseImageType to IMAGE, set BaseImage to the ID of a custom image. When you set BaseImageType to IMAGE_FAMILY, set BaseImage to th
BaseImageType - > base_image_type   BaseImageType是API中的字段，应该改为tf的字段。其他的都改下

2022-03-28 11:45 UTC, xinmu0426 commented on alicloud/resource_alicloud_ecs_image_pipeline.go
> +				Type:     schema.TypeList,
改为TypeSet 吧

2022-03-28 11:45 UTC, xinmu0426 commented on alicloud/resource_alicloud_ecs_image_pipeline.go
> +				ForceNew: true,
这个少了枚举值，缺少校验的都补一下

2022-03-28 11:45 UTC, xinmu0426 commented on alicloud/resource_alicloud_ecs_image_pipeline.go
> +				ForceNew: true,
正则值

2022-03-28 11:45 UTC, xinmu0426 commented on alicloud/resource_alicloud_ecs_image_pipeline.go
> +				Type:     schema.TypeList,
Typeset

2022-03-28 11:45 UTC, xinmu0426 commented on alicloud/resource_alicloud_ecs_image_pipeline.go
> +func resourceAlicloudEcsImagePipelineUpdate(d *schema.ResourceData, meta interface{}) error {
这个去掉吧

2022-03-28 11:45 UTC, xinmu0426 commented on alicloud/resource_alicloud_ecs_image_pipeline_test.go
> +	dExisted, _ = schema.InternalMap(p["alicloud_ecs_image_pipeline"].Schema).Data(dInit.State(), diff)
这个错误看下

2022-03-29 03:29 UTC, super-eggs commented on alicloud/resource_alicloud_ecs_image_pipeline_test.go
> +	dExisted, _ = schema.InternalMap(p["alicloud_ecs_image_pipeline"].Schema).Data(dInit.State(), diff)
Update 的单元测试多余，已去除

2022-03-30 06:33 UTC, xiaozhu36 requested changes

2022-03-30 06:33 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ecs_image_support_instance_types.go
> +func dataSourceAlicloudEcsImageSupportInstanceTypes() *schema.Resource {
这个datasource没必要写，直接把通过 imageId 查instanceType 的逻辑写在 instance_types 的这个datasource中就行

2022-03-30 06:33 UTC, xiaozhu36 commented on website/docs/d/ecs_image_pipelines.html.markdown
> +* `base_image` - The source image.
缩进

2022-03-30 06:33 UTC, xiaozhu36 commented on website/docs/d/ecs_image_pipelines.html.markdown
> +* `names` - A list of Image Pipeline names.
ids 呢

2022-03-30 09:44 UTC, merged