resource/alicloud_click_house_account: Support updating the account authority configuration
aliyun/terraform-provider-alicloud pull request #4809
Opened 2022-03-30 03:57 UTC by Wanghx0991

2022-03-31 12:41 UTC, xiaozhu36 requested changes

2022-03-31 12:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_click_house_account.go
> +				ValidateFunc: validation.StringInSlice([]string{"all", "readonly,modify"}, false),
readonly,modify 是连起来的一个值？

2022-03-31 12:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_click_house_account_test.go
> +					"dml_authority":      "all",
其他的枚举值也要测试下

2022-04-01 07:51 UTC, Wanghx0991 commented on alicloud/resource_alicloud_click_house_account.go
> +				ValidateFunc: validation.StringInSlice([]string{"all", "readonly,modify"}, false),
跟他们确认过, 是这个值

2022-04-07 02:20 UTC, merged