New Resource `alicloud_alb_listener_additional_acl_attachment`.
aliyun/terraform-provider-alicloud pull request #4816
Opened 2022-03-31 08:40 UTC by super-eggs

New Resource `alicloud_alb_listener_additional_acl_attachment`.

2022-03-31 11:40 UTC, xinmu0426 commented on alicloud/resource_alicloud_alb_listener_acl_attachment.go
> +			Create: schema.DefaultTimeout(1 * time.Minute),
这个时间设为5分钟

2022-04-01 07:26 UTC, super-eggs commented on alicloud/resource_alicloud_alb_listener_acl_attachment_test.go
> +func TestAccAlicloudAlbListenerAclAttachment_unit(t *testing.T) {
单测覆盖率 95%

2022-04-06 06:50 UTC, xiaozhu36 requested changes

2022-04-06 06:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_alb_listener_acl_attachment.go
> +	d.SetId(fmt.Sprintf("%s:%s:%s", d.Get("listener_id"), d.Get("acl_type"), d.Get("acl_id")))
这个id 不包含 acl type 是不是也可以

2022-04-06 07:12 UTC, super-eggs commented on alicloud/resource_alicloud_alb_listener_acl_attachment.go
> +	d.SetId(fmt.Sprintf("%s:%s:%s", d.Get("listener_id"), d.Get("acl_type"), d.Get("acl_id")))
因为一个 listener 统一时间只能配置黑名单或白名单，已调整为二级id。

2022-04-06 09:31 UTC, xiaozhu36 requested changes

2022-04-06 09:31 UTC, xiaozhu36 commented on alicloud/service_alicloud_alb.go
> +		return nil, WrapErrorf(Error(GetNotFoundMessage("ALB", id)), NotFoundWithResponse, response)
ALB 应该改成 alb_listener_acl_attachment

2022-04-06 10:49 UTC, merged