the parameter value of force_attach is not false
aliyun/terraform-provider-alicloud pull request #4824
Opened 2022-04-02 10:02 UTC by fuliu-zln

2022-04-02 10:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4824) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4824) before we can accept your contribution.<br/><hr/>**wb-zln530580** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=4824) it.</sub>

2022-04-14 02:53 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	if len(response.ScalingActivityId) == 0{
这个位置不对吧，为啥在后面判断，已经等于0 应该报错吧

2022-04-14 10:15 UTC, fuliu-zln commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	if len(response.ScalingActivityId) == 0{
这个顺序是对的 
因为无论是否有伸缩活动返回
ALB 都要关联到伸缩组上
不同的是 如果force_attach 是true 会产生伸缩活动
force_attach 是false 不会产生伸缩活动（这个是产品设计 不算报错）

2022-04-14 10:49 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	if len(response.ScalingActivityId) == 0{
那 这块判断的意义是啥

2022-04-14 10:55 UTC, fuliu-zln commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	if len(response.ScalingActivityId) == 0{
如果没有这块判断会认为无论force_attach是什么值
都会产生伸缩活动 会不断的查询这个伸缩活动是否完成了
但是实际上force_attach为false时 不会生成伸缩活动 伸缩活动为null 查询伸缩活动会报错的

2022-04-15 07:26 UTC, xiaozhu36 requested changes

2022-04-15 07:26 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
>  	return nil
这个里面不对吧，create 之后，如果没有修改，应该return read 方法，而不是直接return nil

2022-04-15 08:19 UTC, fuliu-zln commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
>  	return nil
已加

2022-04-16 05:11 UTC, merged