`resource/alicloud_log_alert`: add auto_annotation and power_sql_mode in alert config; update log sdk.
aliyun/terraform-provider-alicloud pull request #4835
Opened 2022-04-07 15:13 UTC by panawala

* update log sdk. 
*  add auto_annotation and power_sql_mode in alert config.

2022-04-07 15:28 UTC, panawala commented
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLogAlert -timeout=300m
=== RUN   TestAccAlicloudLogAlertResourceDataSource
--- PASS: TestAccAlicloudLogAlertResourceDataSource (15.52s)
=== RUN   TestAccAlicloudLogAlert_basic
--- PASS: TestAccAlicloudLogAlert_basic (94.24s)
=== RUN   TestAccAlicloudLogAlert_basic_new
--- PASS: TestAccAlicloudLogAlert_basic_new (96.87s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  (cached)

2022-04-11 05:23 UTC, xiaozhu36 requested changes

2022-04-11 05:23 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_alert.go
> +							ValidateFunc: validation.StringInSlice([]string{"cross_join", "inner_join", "left_join", "right_join", "full_join", "left_exclude", "right_exclude", "concat", "no_join"}, false),
这个为啥要改

2022-04-11 05:23 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_alert.go
> +		autoAnnotation = d.Get("auto_annotation").(bool)
这个地方直接用 
if v, ok := d.GetOk("auto_annotation"); ok  {
  autoAnnotation = v.(bool)
}

2022-04-11 06:02 UTC, panawala commented on alicloud/resource_alicloud_log_alert.go
> +							ValidateFunc: validation.StringInSlice([]string{"cross_join", "inner_join", "left_join", "right_join", "full_join", "left_exclude", "right_exclude", "concat", "no_join"}, false),
这里大小写是要区分的，之前应该是写错了

2022-04-11 06:53 UTC, panawala commented
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLogAlert -timeout=300m
=== RUN   TestAccAlicloudLogAlertResourceDataSource
--- PASS: TestAccAlicloudLogAlertResourceDataSource (15.57s)
=== RUN   TestAccAlicloudLogAlert_basic
--- PASS: TestAccAlicloudLogAlert_basic (93.95s)
=== RUN   TestAccAlicloudLogAlert_basic_new
--- PASS: TestAccAlicloudLogAlert_basic_new (98.50s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  208.407s

2022-04-11 06:54 UTC, panawala commented on alicloud/resource_alicloud_log_alert.go
> +							ValidateFunc: validation.StringInSlice([]string{"cross_join", "inner_join", "left_join", "right_join", "full_join", "left_exclude", "right_exclude", "concat", "no_join"}, false),
这个是大小写敏感，之前应该写的有问题

2022-04-11 07:40 UTC, merged