Feature/eci scaling conf
aliyun/terraform-provider-alicloud pull request #4855
Opened 2022-04-12 08:30 UTC by TalentNing

2022-04-13 03:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_scaling_group.go
> +				Default:  "ECS",
默认值去掉吧，针对新增属性也应该有测试用例

2022-04-13 03:31 UTC, xinmu0426 commented on website/docs/r/ess_eci_scaling_configuration.html.markdown
> +    * `key` - (Optional) The name of the variable. The name can be 1 to 128 characters in length and can contain
这块也都应该写为Blocks

2022-04-13 03:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +		Importer: &schema.ResourceImporter{
增加一个timeout字段配置

2022-04-13 03:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +				Default:  false,
Default 值都去掉吧

2022-04-13 03:31 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +				Optional: true,
加上正则校验，有长度格式要求的都要加上

2022-04-13 03:52 UTC, TalentNing commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +				Optional: true,
暂不提供校验，仅文档说明。

2022-04-13 03:53 UTC, TalentNing commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +				Default:  false,
done

2022-04-13 05:00 UTC, TalentNing commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +				Default:  false,
done

2022-04-13 05:02 UTC, TalentNing commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +		Importer: &schema.ResourceImporter{
done

2022-04-13 07:48 UTC, TalentNing commented on alicloud/resource_alicloud_ess_scaling_group.go
> +				Default:  "ECS",
done

2022-04-13 10:41 UTC, xinmu0426 commented on website/docs/r/ess_scaling_group.html.markdown
> +* `group_type` - (Optional, Available in v1.164.0+) Resource type within scaling group. Optional values: ECS, ECI. Default to ECS.
Valid values : `ECS`, `ECI`.  Default Value:  `ECS`.

2022-04-13 10:41 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +				Optional: true,
为啥不加。scaling_configuration_name  description

2022-04-13 10:41 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +
加上 update = false这种形式的判断 参考resourceAlicloudAlbRuleUpdate

2022-04-13 10:41 UTC, xinmu0426 commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +	if d.Get("force_delete").(bool) {
为啥有两个删除

2022-04-15 02:07 UTC, TalentNing commented on website/docs/r/ess_eci_scaling_configuration.html.markdown
> +    * `key` - (Optional) The name of the variable. The name can be 1 to 128 characters in length and can contain
done

2022-04-15 02:07 UTC, TalentNing commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +				Optional: true,
done

2022-04-15 02:08 UTC, TalentNing commented on website/docs/r/ess_scaling_group.html.markdown
> +* `group_type` - (Optional, Available in v1.164.0+) Resource type within scaling group. Optional values: ECS, ECI. Default to ECS.
done

2022-04-15 02:10 UTC, TalentNing commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +	if d.Get("force_delete").(bool) {
伸缩配置属于伸缩组下资源，伸缩组不允许删除已启用或最后一条伸缩规则，所以这块和原来ess_scaling_configuration资源采用了类似的处理方式，强制删除时，将整个伸缩组删除。

2022-04-15 03:13 UTC, xiaozhu36 requested changes

2022-04-15 03:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +				Optional: true,
这个为啥不是 TypeSet

2022-04-15 03:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +				Type:     schema.TypeList,
还有这个

2022-04-15 03:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_scaling_group.go
> +			//return essClient.CreateScalingGroup(request)
去掉无用的注释

2022-04-15 03:13 UTC, xiaozhu36 commented on alicloud/service_alicloud_ess.go
> +func (s *EssService) DescribeEssScalingGroupById(id string) (object map[string]interface{}, err error) {
这个方法之前应该已经有了吧，为啥还要再写一个

2022-04-15 03:49 UTC, TalentNing commented on alicloud/resource_alicloud_ess_scaling_group.go
> +			//return essClient.CreateScalingGroup(request)
done

2022-04-15 03:50 UTC, TalentNing commented on alicloud/service_alicloud_ess.go
> +func (s *EssService) DescribeEssScalingGroupById(id string) (object map[string]interface{}, err error) {
原方式使用sdk调用方式，新方法使用common request方式。由于原方法依赖的较多，改动点较多，因此本次未对引用位置进行替换。

2022-04-15 07:32 UTC, xiaozhu36 requested changes

2022-04-15 07:32 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_eci_scaling_configuration_test.go
> +							"image":             "registry-vpc.cn-hangzhou.aliyuncs.com/eci_open/alpine:3.5",
这个image url 中的 cn-hangzhou应该改成 从环境变量中拿

2022-04-15 11:34 UTC, TalentNing commented on alicloud/resource_alicloud_ess_eci_scaling_configuration.go
> +						"volume_mounts": {
done

2022-04-15 11:35 UTC, TalentNing commented on alicloud/resource_alicloud_ess_eci_scaling_configuration_test.go
> +							"image":             "registry-vpc.cn-hangzhou.aliyuncs.com/eci_open/alpine:3.5",
done

2022-04-16 03:12 UTC, merged