Test
aliyun/terraform-provider-alicloud pull request #4861
Opened 2022-04-13 06:16 UTC by Wanghx0991

2022-04-14 08:09 UTC, Wanghx0991 commented on alicloud/resource_alicloud_hbr_ots_backup_plan.go
> -				Type:     schema.TypeString,
HBR API的bug, 在使用ots备份的时候该字段无效, 仅在rules中的schedule有效
- 之前合码通过是因为, 在传入schedule的时候, 无报错同时read返回该值
- 对接了下面的rule后, 才发现ots仅在rule中的schedule生效

2022-04-14 08:09 UTC, Wanghx0991 commented on alicloud/resource_alicloud_hbr_restore_job.go
> -			"target_container": {
这两个字段跟云产品确认过, 既没有对外透出,  同时云产品API也没有该字段

2022-04-15 06:41 UTC, xiaozhu36 requested changes

2022-04-15 06:41 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_hbr_backup_jobs.go
> +							Type:     schema.TypeSet,
这个应该是 list

2022-04-15 06:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_hbr_ots_backup_plan.go
> +				Deprecated: "Field 'instance_name' has been deprecated from version 1.163.0. Use 'rules' instead.",
这个描述不太对吧

2022-04-15 06:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_hbr_restore_job.go
> -			"target_container": {
我们的文档中透出了么

2022-04-15 07:12 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_hbr_backup_jobs.go
> +							Type:     schema.TypeSet,
Done

2022-04-15 07:12 UTC, Wanghx0991 commented on alicloud/resource_alicloud_hbr_ots_backup_plan.go
> +				Deprecated: "Field 'instance_name' has been deprecated from version 1.163.0. Use 'rules' instead.",
Done

2022-04-15 07:12 UTC, Wanghx0991 commented on alicloud/resource_alicloud_hbr_restore_job.go
> -			"target_container": {
没有透出, 就是CI检测出来以后发现这几个字段不一致的, 跟产品确认,他们就没有这俩字段

2022-04-15 07:29 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_hbr_backup_jobs.go
> +										Type: schema.TypeList,
修正了

2022-04-16 05:14 UTC, merged