resource/alicloud_cs_kubernetes_addon: Support to modify the custom configuration of the kubernetes cluster addon
aliyun/terraform-provider-alicloud pull request #4875
Opened 2022-04-17 03:24 UTC by saberrey

1. datasource/alicloud_cs_kubernetes_addon_metadata: Add new data source alicloud_cs_kubernetes_addon_metadata.
2. datasource/alicloud_cs_kubernetes_addons: Add new return field config.
3. resource/alicloud_cs_kubernetes_addon: Support to modify the custom configuration of the kubernetes cluster addon.

2022-04-19 06:22 UTC, saberrey commented on website/docs/d/cs_kubernetes_addon_metadata.html.markdown
> +* `cluster_id` - The id of kubernetes cluster.
done

2022-04-19 06:22 UTC, saberrey commented on website/docs/d/cs_kubernetes_addons.html.markdown
> +  * `current_config` - The current custom configuration of the addon.
done

2022-04-19 06:22 UTC, saberrey commented on website/docs/r/cs_kubernetes_addon.html.markdown
> +* `config` - (Optional) The custom configuration of addon. You can checkout the customizable configuration of the addon through datasource `alicloud_cs_kubernetes_addon_metadata`, the returned format
done

2022-04-26 08:18 UTC, xiaozhu36 requested changes

2022-04-26 08:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_addon.go
> +	} else if d.HasChange("config") {
这个地方不应该是 else 吧，如果 version 和 config 同时修改了，怎么办

2022-04-26 09:31 UTC, merged