resource/alicloud_bastionhost_instance: Add support for field `ad_auth_server` and `ldap_auth_server`.
aliyun/terraform-provider-alicloud pull request #4904
Opened 2022-04-24 08:31 UTC by super-eggs

resource/alicloud_bastionhost_instance: Add support for field `ad_auth_server` and `ldap_auth_server`.

2022-05-06 06:56 UTC, xinmu0426 commented on alicloud/common.go
> +				skip = true
这块不需要全部遍历完才推出吧

2022-05-06 06:56 UTC, xinmu0426 commented on website/docs/r/bastionhost_instance.html.markdown
> +* `ldap_auth_server` - (Optional, Available from 1.165.0+) The LDAP auth server of the Instance. See the following `Block ldap_auth_server`.
166 了

2022-05-06 06:56 UTC, xinmu0426 commented on website/docs/r/bastionhost_instance.html.markdown
> +* `ad_auth_server` - (Optional, Available from 1.165.0+) The AD auth server of the Instance. See the following `Block ad_auth_server`.
166 了，另外在文档上 把ad_auth_server，ldap_auth_server  lifecycle那个加上

2022-05-12 04:15 UTC, xiaozhu36 requested changes

2022-05-12 04:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_bastionhost_instance.go
> +				Type:     schema.TypeList,
这个应该是 typeset 吧

2022-05-12 04:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_bastionhost_instance.go
> +				Type:     schema.TypeList,
这个也一样

2022-05-20 12:28 UTC, xiaozhu36 requested changes

2022-05-20 14:37 UTC, super-eggs commented on alicloud/resource_alicloud_bastionhost_instance.go
> +					if len(d1.(*schema.Set).List()) == 0 || len(d2.(*schema.Set).List()) == 0 {
这里的 ad_auth_server.password 是没有返回的，虽然设置了 Sensitive，但是也会报Diff，所以要抑制这个 password 造成的 Diff。
ldap_auth_server.password 同理。

2022-05-25 11:42 UTC, merged