resource/alicloud_adb_db_cluster: support converting the  and 'pay_type'
aliyun/terraform-provider-alicloud pull request #4916
Opened 2022-04-27 07:21 UTC by Wanghx0991

2022-04-28 02:48 UTC, xiaozhu36 requested changes

2022-04-28 02:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_adb_db_cluster.go
> -				ForceNew:      true,
既然这个是弃用的，那么要标记上

2022-04-28 02:48 UTC, xiaozhu36 commented on website/docs/r/adb_cluster.html.markdown
> +environment in the cloud. AN ADB cluster can contain multiple user-created
应该是 An 吧

2022-04-28 07:31 UTC, Wanghx0991 commented on website/docs/r/adb_cluster.html.markdown
> +environment in the cloud. AN ADB cluster can contain multiple user-created
Done

2022-04-28 07:31 UTC, Wanghx0991 commented on alicloud/resource_alicloud_adb_db_cluster.go
> -				ForceNew:      true,
Done

2022-04-29 07:32 UTC, Wanghx0991 commented on alicloud/resource_alicloud_adb_db_cluster_test.go
> +				ImportStateVerifyIgnore: []string{"auto_renew_period", "period", "renewal_status"},
这个我试过, 是因为api返回问题, 如果不是续费状态, 去查接口会返回一个NotFoundError, 所以在read的处理里, 才会去区分如果是预付费的情况下 才会去查找这个API,把 `auto_renew_period`, `renewal_status` 写进state里, 后付费就不再去查找个api了

```shell
[ERROR] terraform-provider-alicloud/alicloud/service_alicloud_adb.go:609: ResourceNotfound!!! Response: map[Items:map[AutoRenewAttribute:[]] PageNumber:1 PageRecordCount:0 RequestId:4E9C0554-2536-5361-9425-499AECB16C6A TotalRecordCount:0]:
        The specified AnalyticDBForMySQL3.0 am-bp1gq4gqxdnm7e7ek is not found.
```

2022-04-29 08:34 UTC, merged