testcase: Adds new unit test case for resource alicloud_ons_topic alicloud_privatelink_vpc_endpoint_connection alicloud_privatelink_vpc_endpoint_service_resource
aliyun/terraform-provider-alicloud pull request #4922
Opened 2022-04-28 10:05 UTC by thisnihonglei

2022-04-28 10:07 UTC, thisnihonglei commented on alicloud/resource_alicloud_ons_topic_test.go
> +func TestAccAlicloudOnsTopic_unit(t *testing.T) {
单测覆盖率94.6%

2022-04-28 10:07 UTC, thisnihonglei commented on alicloud/resource_alicloud_privatelink_vpc_endpoint_connection_test.go
> +func TestAccAlicloudPrivatelinkVpcEndpointConnection_unit(t *testing.T) {
单测覆盖率95.7%

2022-04-28 10:07 UTC, thisnihonglei commented on alicloud/resource_alicloud_privatelink_vpc_endpoint_service_resource_test.go
> +func TestAccAlicloudPrivatelinkVpcEndpointServiceResource_unit(t *testing.T) {
单测覆盖率97.3%

2022-04-29 06:40 UTC, xiaozhu36 requested changes

2022-04-29 09:28 UTC, thisnihonglei commented on website/docs/r/ons_topic.html.markdown
> +* `topic_name` - (Optional, Available in v1.97.0+) Name of the topic. Two topics on a single instance cannot have the same name and the name cannot start with 'GID' or 'CID'. The length cannot exceed
done

2022-04-29 09:46 UTC, merged