testcase: Adds new unit test case for resource alicloud_privatelink_vpc_endpoint alicloud_privatelink_vpc_endpoint_service alicloud_privatelink_vpc_endpoint_service_user
aliyun/terraform-provider-alicloud pull request #4926
Opened 2022-04-29 09:42 UTC by thisnihonglei

2022-04-29 09:44 UTC, thisnihonglei commented on alicloud/resource_alicloud_privatelink_vpc_endpoint_service_test.go
> +func TestAccAlicloudPrivatelinkVpcEndpointService_unit(t *testing.T) {
单测覆盖率99.1%

2022-04-29 09:44 UTC, thisnihonglei commented on alicloud/resource_alicloud_privatelink_vpc_endpoint_service_user_test.go
> +func TestAccAlicloudPrivatelinkVpcEndpointServiceUser_unit(t *testing.T) {
单测覆盖率97.4%

2022-04-29 09:44 UTC, thisnihonglei commented on alicloud/resource_alicloud_privatelink_vpc_endpoint_test.go
> +func TestAccAlicloudPrivatelinkVpcEndpoint_unit(t *testing.T) {
单测覆盖率96.2%

2022-05-05 12:31 UTC, xiaozhu36 requested changes

2022-05-05 12:31 UTC, xiaozhu36 commented on alicloud/resource_alicloud_privatelink_vpc_endpoint_service_test.go
> +func TestAccAlicloudPrivatelinkVpcEndpointService_unit(t *testing.T) {
单元测试的name 都以 TestUnit 开头吧

2022-05-12 04:18 UTC, merged