New Resource `alicloud_ga_accelerator_spare_ip_attachment`; New Datasource `alicloud_ga_accelerator_spare_ip_attachments`;
aliyun/terraform-provider-alicloud pull request #4944
Opened 2022-05-09 01:36 UTC by super-eggs

New Resource `alicloud_ga_accelerator_spare_ip_attachment`;
New Datasource `alicloud_ga_accelerator_spare_ip_attachments`;

2022-05-10 02:53 UTC, xinmu0426 commented on alicloud/data_source_alicloud_ga_accelerator_spare_ip_attachments.go
> +				ForceNew: true,
dry_run这个去掉

2022-05-10 02:53 UTC, xinmu0426 commented on alicloud/resource_alicloud_ga_accelerator_spare_ip_attachment.go
> +				ForceNew: true,
dry_run 不需要ForceNew

2022-05-10 06:45 UTC, super-eggs commented on alicloud/resource_alicloud_ga_accelerator_spare_ip_attachment_test.go
> +func TestAccAlicloudGaAcceleratorSpareIpAttachment_unit(t *testing.T) {
单元测试覆盖率 95.3%

2022-05-12 04:11 UTC, xiaozhu36 requested changes

2022-05-12 04:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_accelerator_spare_ip_attachment_test.go
> +func TestAccAlicloudGaAcceleratorSpareIpAttachment_unit(t *testing.T) {
以后单元测试的名称要改成 TestUnitAlicloudxxxx，具体的可以问问倪洪磊

2022-05-12 10:50 UTC, merged