testcase: Adds new unit test case for resource alicloud_resource_manager_shared_target alicloud_resource_manager_shared_resource alicloud_resource_manager_role
aliyun/terraform-provider-alicloud pull request #4951
Opened 2022-05-10 09:58 UTC by thisnihonglei

2022-05-10 09:59 UTC, thisnihonglei commented on alicloud/resource_alicloud_resource_manager_role_test.go
> +func TestUnitAlicloudResourceManagerRole(t *testing.T) {
单测覆盖率94.9%

2022-05-10 09:59 UTC, thisnihonglei commented on alicloud/resource_alicloud_resource_manager_shared_resource_test.go
> +func TestUnitAlicloudResourceManagerSharedResource(t *testing.T) {
单测覆盖率94.6%

2022-05-10 09:59 UTC, thisnihonglei commented on alicloud/resource_alicloud_resource_manager_shared_target_test.go
> +func TestUniAlicloudResourceManagerSharedTarget(t *testing.T) {
单测覆盖率94.4%

2022-05-12 04:40 UTC, xiaozhu36 requested changes

2022-05-12 04:40 UTC, xiaozhu36 commented on website/docs/r/resource_manager_role.html.markdown
> -* `id` - This ID of Resource Manager role. The value is set to `role_name`.
id 也是有的啊

2022-05-13 13:39 UTC, merged