resource/alicloud_hbr_ots_backup_plan: fix the field type
aliyun/terraform-provider-alicloud pull request #4955
Opened 2022-05-12 08:03 UTC by Wanghx0991

2022-05-13 03:09 UTC, Wanghx0991 commented on scripts/schema_test.go
> +		"alicloud_hbr_ots_backup_plan":      {"vault_id", "instance_name", "ots_detail", "rules", "schedule", "retention", "rule_name", "backup_type"},
这几个字段是HBR根据他们的业务场景反馈的问题, 备份计划这套api,同时支持了4个数据源, OTS是近期新增的数据源,api的文档里大部分字段都是选填, 但根据不同数据源, 在实际调佣的过程中又要求了必填,以及诸如`vault_id`在update中是选填, 但同时因为作为了联合主键,又不支持更改,  如果不改过来, 会有使用体验上的问题,

2022-05-13 04:11 UTC, Wanghx0991 commented on alicloud/resource_alicloud_hbr_ots_backup_plan.go
>  			"ots_detail": {
这几个字段是HBR根据他们的业务场景反馈的问题, 备份计划这套api,同时支持了4个数据源, OTS是近期新增的数据源,api的文档里大部分字段都是选填, 但根据不同数据源, 在实际调佣的过程中又要求了必填,以及诸如vault_id在update中是选填, 但同时因为作为了联合主键,又不支持更改, 如果不改过来, 会有使用体验上的问题,

2022-05-13 06:43 UTC, xiaozhu36 requested changes

2022-05-13 06:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_hbr_ots_backup_plan.go
>  			"ots_detail": {
选填和必填，要跟 Create API 上的对齐，如果API是选填，我们也选填

2022-05-13 06:43 UTC, xiaozhu36 commented on scripts/schema_test.go
> +		"alicloud_nat_gateway":              {"vswitch_id"},
跟 schema 对齐

2022-05-20 07:15 UTC, xiaozhu36 requested changes

2022-05-20 07:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_nat_gateway.go
> -				Optional: true,
vswitch id 不是必填啊，这种情况，也是一样，要跟云产品API对齐

2022-05-20 08:00 UTC, Wanghx0991 commented on alicloud/resource_alicloud_nat_gateway.go
> -				Optional: true,
是必填,
https://help.aliyun.com/document_detail/120219.htm

2022-05-20 14:34 UTC, merged