New Resource: alicloud_ddos_basic_antiddos
aliyun/terraform-provider-alicloud pull request #4973
Opened 2022-05-18 09:13 UTC by Wanghx0991

2022-05-18 12:27 UTC, xiaozhu36 requested changes

2022-05-18 12:27 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ddos_basic_antiddos.go
> +			"ddos_region_id": {
这个regionid 没必要写啊，这个是跟实例的所在的region是一样的，直接使用 provider中的region就行

2022-05-18 12:27 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ddos_basic_antiddos_test.go
> +}
单元测试呢

2022-05-18 12:27 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ddos_basic_antiddos.go
> +package alicloud
这个资源的名字不对吧，既然用的是 ModifyDefenseThreshold，那么把 antiddos 改成 defense_threshold

2022-05-19 04:34 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ddos_basic_antiddos.go
> +package alicloud
Done

2022-05-19 04:34 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ddos_basic_antiddos.go
> +			"ddos_region_id": {
Done

2022-05-19 10:25 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ddos_basic_antiddos_test.go
> +}
Done

2022-05-20 07:12 UTC, xiaozhu36 requested changes

2022-05-20 07:12 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ddos_basic_defense_threshold_test.go
> +func TestAccAlicloudDdosBasicDefenseThreshold_unit(t *testing.T) {
单元测试的标题都改为 TestUnitAlicloudxxx 了

2022-05-20 07:53 UTC, Wanghx0991 commented on alicloud/resource_alicloud_ddos_basic_defense_threshold_test.go
> +func TestAccAlicloudDdosBasicDefenseThreshold_unit(t *testing.T) {
Done

2022-05-20 14:29 UTC, merged