PolarDB: Set Deletion Prevention
aliyun/terraform-provider-alicloud pull request #4985
Opened 2022-05-20 08:08 UTC by Lv0520

2022-05-20 08:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4985) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=4985) before we can accept your contribution.<br/><hr/>**wb01224501** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=4985) it.</sub>

2022-05-24 06:46 UTC, xiaozhu36 requested changes

2022-05-24 06:46 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +				Type:         schema.TypeString,
为啥不直接设置为 TypeBool

2022-05-24 06:46 UTC, xiaozhu36 commented on website/docs/r/polardb_cluster.html.markdown
> +* `deletion_lock` - (Optional, Available in 1.168.0+) turn on table deletion_lock. Valid values are `true`, `false`
下个版本是 169了

2022-05-24 10:32 UTC, Lv0520 commented on website/docs/r/polardb_cluster.html.markdown
> +* `deletion_lock` - (Optional, Available in 1.168.0+) turn on table deletion_lock. Valid values are `true`, `false`
已经修改

2022-05-24 10:33 UTC, Lv0520 commented on alicloud/resource_alicloud_polardb_cluster.go
> +				Type:         schema.TypeString,
已解决

2022-05-27 02:16 UTC, xiaozhu36 requested changes

2022-05-27 02:16 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"deletion_lock": {
1. 从 API的参数上看，这个地方应该定义为 protection
2. 这个参数是资源的属性，需要在通过 Describe API 返回，并且在 read 方法中 set

2022-05-27 05:15 UTC, Lv0520 commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"deletion_lock": {
已经处理完成

2022-05-27 08:50 UTC, xiaozhu36 requested changes

2022-05-27 08:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +	d.Set("protection", clusterAttribute.DeletionLock == 1)
1. 如果这个属性在 Describe API上返回的是 DeletionLock，那么，在schema还是应该定义为 deletion_locl
2. 既然DeletionLock在 Describe API上是int，那么在 schema 上的类型也应该是 int，并且要设置对应的枚举值

2022-05-27 08:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +				ImportStateVerifyIgnore: []string{"modify_type", "protection"},
如果在read中set了，那么这个地方不应该再Ignore掉

2022-05-27 09:58 UTC, Lv0520 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +				ImportStateVerifyIgnore: []string{"modify_type", "protection"},
已经处理

2022-05-28 08:07 UTC, xiaozhu36 requested changes

2022-05-28 08:07 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +				Default:      0,
这个默认值不需要，直接去掉就好了

2022-05-28 08:07 UTC, xiaozhu36 commented on website/docs/r/polardb_cluster.html.markdown
> +* `deletion_lock` - (Optional, Available in 1.169.0+) turn on table deletion_lock. Valid values are 0, 1
说清楚，0 和 1 分别代表什么

2022-05-29 04:41 UTC, Lv0520 commented on website/docs/r/polardb_cluster.html.markdown
> +* `deletion_lock` - (Optional, Available in 1.169.0+) turn on table deletion_lock. Valid values are 0, 1
已处理

2022-05-29 07:03 UTC, merged