New Data Source: data_source_alicloud_cs_kubernetes_metadatda
aliyun/terraform-provider-alicloud pull request #4999
Opened 2022-05-25 07:48 UTC by saberrey

New Data Source: data_source_alicloud_cs_kubernetes_metadatda

2022-05-25 16:43 UTC, saberrey commented on alicloud/data_source_alicloud_cs_kubernetes_metadatda.go
> +	request.ClusterType = tea.String(d.Get("cluster_type").(string))
cluster_type和region是必选字段，剩下的都有判空

2022-05-25 16:46 UTC, saberrey commented on website/docs/r/cs_kubernetes_version.html.markdown
> +---
done，加错了

2022-05-25 16:47 UTC, saberrey commented on alicloud/data_source_alicloud_cs_kubernetes_metadatda.go
> +	if version, ok := d.GetOk("profile"); ok {
done

2022-05-27 08:54 UTC, xiaozhu36 requested changes

2022-05-27 08:54 UTC, xiaozhu36 commented on website/docs/d/cs_kubernetes_version.html.markdown
> +Provides a data source to query the details of the Kubernetes version supported by ACK.
这个Provides 前面应该保留两个空格

2022-05-27 08:58 UTC, saberrey commented on website/docs/d/cs_kubernetes_version.html.markdown
> +Provides a data source to query the details of the Kubernetes version supported by ACK.
done

2022-05-27 09:40 UTC, merged