New Resource `alicloud_tag_meta_tag`;
aliyun/terraform-provider-alicloud pull request #5000
Opened 2022-05-25 08:35 UTC by super-eggs

New Datasource `alicloud_tag_meta_tags`;

2022-05-26 02:05 UTC, xinmu0426 commented on website/docs/d/tag_meta_tags.html.markdown
> +description: |-	Provides a list of Tag Meta Tags to the user.
格式看下

2022-05-26 02:05 UTC, xinmu0426 commented on alicloud/resource_alicloud_tag_meta_tag.go
> +				Optional: true,
正则校验加一下

2022-05-27 02:08 UTC, xiaozhu36 requested changes

2022-05-27 02:08 UTC, xiaozhu36 commented on website/docs/d/tag_meta_tags.html.markdown
> +	 Provides a list of Tag Meta Tags to the user.
格式

2022-05-27 02:08 UTC, xiaozhu36 commented on website/docs/d/tag_meta_tags.html.markdown
> +		* `description` - The description of the tag key.
格式

2022-05-27 02:08 UTC, xiaozhu36 commented on alicloud/resource_alicloud_tag_meta_tag.go
> +	d.SetId(fmt.Sprintf("%s:%s", d.Get("key_name"), d.Get("value_name")))
这个ID有问题啊，如果key name 和 value name 中保存了空格，那么这个ID在导入的时候就失效了

2022-05-27 03:46 UTC, super-eggs commented on alicloud/resource_alicloud_tag_meta_tag.go
> +	d.SetId(fmt.Sprintf("%s:%s", d.Get("key_name"), d.Get("value_name")))
如果用户之前创建的key_name 或 value_name 中包含空格，那可以通过用双引号包含的形式导入。
例如：`terraform import alicloud_tag_meta_tag.default3 ' tf-test- 123:tf-test-222 '`，本地测试可以正常导入。

2022-05-27 08:47 UTC, xiaozhu36 requested changes

2022-05-27 08:47 UTC, xiaozhu36 commented on alicloud/resource_alicloud_tag_meta_tag.go
> +	d.SetId(fmt.Sprintf("%s:%s", d.Get("key_name"), d.Get("value_name")))
这种肯定不行，客户体验不一致了。

2022-05-28 04:03 UTC, merged