New Resource `alicloud_ots_tunnel`; New Datasource `alicloud_ots_tunnels`; Resource/alicloud_ots_table: Support server side encryption;
aliyun/terraform-provider-alicloud pull request #5051
Opened 2022-06-09 07:38 UTC by okingniko

New Datasource `alicloud_ots_tunnels`;
Resource/alicloud_ots_table: Support server side encryption;

2022-06-09 07:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=5051) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=5051) before we can accept your contribution.<br/><hr/>**zhuoran.wzr** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=5051) it.</sub>

2022-06-09 08:04 UTC, okingniko commented on alicloud/connectivity/client.go
> +	otsTunnelConnByInstanceName  map[string]otsTunnel.TunnelClient
TunnelClient是一个interface

2022-06-10 07:29 UTC, super-eggs commented on website/docs/d/ots_tunnels.html.markdown
> +-> **NOTE:** Available in v1.170.0+.
v1.171.0

2022-06-10 07:29 UTC, super-eggs commented on website/docs/r/ots_table.html.markdown
> +* `sse_key_type` - (Optional, Available in 1.170.0+) The key type of OTS server side encryption. Only `SSE_KMS_SERVICE` is allowed.
v1.171.0

2022-06-10 07:29 UTC, super-eggs commented on website/docs/r/ots_tunnel.html.markdown
> +-> **NOTE:** Available in v1.170.0+.
v1.171.0

2022-06-10 07:29 UTC, super-eggs commented on website/docs/r/ots_tunnel.html.markdown
> +## Import
`### Timeouts`

2022-06-10 07:29 UTC, super-eggs commented on alicloud/resource_alicloud_ots_tunnel.go
> +
Timeouts

2022-06-10 07:29 UTC, super-eggs commented on website/docs/d/ots_tunnels.html.markdown
> +* `table_name` - The name of OTS table.
instance_name 和 table_name: (Required)

2022-06-13 09:22 UTC, okingniko commented on alicloud/data_source_alicloud_ots_tunnels.go
> +				MinItems: 1,
去掉了MinItems限制。

2022-06-13 09:23 UTC, okingniko commented on alicloud/resource_alicloud_ots_tunnel.go
> +				ForceNew: true,
参考 alicloud_ots_instance 和 alicloud_ots_table 里 没有限制。

2022-06-13 09:23 UTC, okingniko commented on website/docs/d/ots_tunnels.html.markdown
> +-> **NOTE:** Available in v1.170.0+.
changed to v1.172.0

2022-06-13 09:24 UTC, okingniko commented on alicloud/resource_alicloud_ots_tunnel.go
> +
Add default timeouts

2022-06-13 09:25 UTC, okingniko commented on website/docs/r/ots_tunnel.html.markdown
> +## Import
add timeouts

2022-06-13 09:31 UTC, okingniko commented on website/docs/r/ots_tunnel.html.markdown
> +-> **NOTE:** Available in v1.170.0+.
changed to v1.172.0

2022-06-13 09:31 UTC, okingniko commented on website/docs/d/ots_tunnels.html.markdown
> +* `table_name` - The name of OTS table.
done

2022-06-16 06:21 UTC, xinmu0426 commented on alicloud/data_source_alicloud_ots_tunnels.go
> +			// Computed values
// Computed values 这个去掉吧

2022-06-16 06:21 UTC, xinmu0426 commented on alicloud/data_source_alicloud_ots_tunnels_test.go
> +			"tunnels.0.expired":       "false",
没有channels的出参校验

2022-06-16 06:21 UTC, xinmu0426 commented on alicloud/data_source_alicloud_ots_tunnels_test.go
> +			"tunnels.0.expired":       "false",
加上所有的出参校验

2022-06-16 09:46 UTC, okingniko commented on alicloud/data_source_alicloud_ots_tunnels_test.go
> +			"tunnels.0.expired":       "false",
done，添加channels检校

2022-06-16 09:46 UTC, okingniko commented on alicloud/data_source_alicloud_ots_tunnels_test.go
> +			"tunnels.0.expired":       "false",
done，文档内的出参都覆盖了

2022-06-16 09:46 UTC, okingniko commented on alicloud/data_source_alicloud_ots_tunnels.go
> +			// Computed values
done

2022-06-17 05:58 UTC, okingniko commented
测试结果：

=== RUN   TestAccAlicloudOtsInstancesDataSource
--- PASS: TestAccAlicloudOtsInstancesDataSource (518.90s)
=== RUN   TestAccAlicloudOtsServiceDataSource
--- PASS: TestAccAlicloudOtsServiceDataSource (6.51s)
=== RUN   TestAccAlicloudOtsTablesDataSource_basic
--- PASS: TestAccAlicloudOtsTablesDataSource_basic (521.29s)
=== RUN   TestAccAlicloudOtsTunnelsDataSource_basic
--- PASS: TestAccAlicloudOtsTunnelsDataSource_basic (546.18s)
=== RUN   TestAccAlicloudOtsInstance_basic
--- PASS: TestAccAlicloudOtsInstance_basic (497.54s)
=== RUN   TestAccAlicloudOtsInstanceHighPerformance
--- PASS: TestAccAlicloudOtsInstanceHighPerformance (504.60s)
=== RUN   TestAccAlicloudOtsInstance_multi
--- PASS: TestAccAlicloudOtsInstance_multi (515.71s)
=== RUN   TestAccAlicloudOtsTable_basic
--- PASS: TestAccAlicloudOtsTable_basic (561.48s)
=== RUN   TestAccAlicloudOtsTable_highPerformance
--- PASS: TestAccAlicloudOtsTable_highPerformance (516.48s)
=== RUN   TestAccAlicloudOtsTable_multi
--- PASS: TestAccAlicloudOtsTable_multi (423.90s)
=== RUN   TestAccAlicloudOtsTable_withTableEncryption
--- PASS: TestAccAlicloudOtsTable_withTableEncryption (512.73s)
=== RUN   TestAccAlicloudOtsTunnel_basic
--- PASS: TestAccAlicloudOtsTunnel_basic (516.13s)

2022-06-17 06:10 UTC, xiaozhu36 requested changes

2022-06-17 06:10 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ots_tunnel.go
> +				Default:  "BaseAndStream",
这个地方默认值不要直接指定了，如果在不指定的情况下，API有默认值，那么这个地方直接加上 Computed： true 就好了

2022-06-17 06:10 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ots_tunnel.go
> +				Default:  "BaseAndStream",
另外，如果这个参数不支持修改，那么应该设置为 ForceNew 的

2022-06-18 09:52 UTC, merged