resource/alicloud_cs_managed_kubernetes: Cluster parameter adjustment, discarding node-related parameters
aliyun/terraform-provider-alicloud pull request #5056
Opened 2022-06-10 09:51 UTC by saberrey

1. resource/alicloud_cs_managed_kubernetes: Cluster parameter adjustment, discarding node-related parameters.
2. resource/alicloud_cs_kubernetes_node_pool: Add rds whitelist control.

2022-07-01 07:15 UTC, Wanghx0991 commented on alicloud/resource_alicloud_cs_kubernetes.go
> +		}
return错误抛出外层需要处理判断一下吧

2022-07-01 07:15 UTC, Wanghx0991 commented on website/docs/r/cs_kubernetes.html.markdown
> +* `user_ca` - (Optional) The path of customized CA cert, you can use this CA to sign client certs to connect your cluster.
支持可改的版本标注下

2022-07-12 01:55 UTC, Pangjiping commented on alicloud/common.go
> +func (c SensitiveString) String() string {
done

2022-07-12 01:59 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes.go
> +				Removed:          "Field 'worker_data_disk_size' has been deprecated from provider version 1.174.0. Please use resource 'alicloud_cs_kubernetes_node_pool' to manage cluster worker nodes, by using
有可替代字段，文档中有说明

2022-07-12 02:00 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes.go
> +		}
反序列化错误会返回空map，我觉得不应该阻塞进程抛出这个错误吧

2022-07-12 02:08 UTC, Pangjiping commented on website/docs/r/cs_managed_kubernetes.html.markdown
> +* `cluster_spec` - (Optional, Available in 1.101.0+) The cluster specifications of kubernetes cluster,which can be empty.Valid values:
该字段不是ForceNew的，之前文档写错了，1.101.0
https://github.com/aliyun/terraform-provider-alicloud/pull/2898/files#diff-7f437e5732c0d45cc0234589345c4f714ab5196956f112aa28ae42351c32fd0a

2022-07-16 01:17 UTC, xiaozhu36 requested changes

2022-07-16 01:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes.go
> +				Removed:          "Field 'worker_data_disk_size' has been deprecated from provider version 1.176.0. Please use resource 'alicloud_cs_kubernetes_node_pool' to manage cluster worker nodes, by using
应该是 Deprecated 吧

2022-07-16 01:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes.go
> +				Removed:  "Field 'worker_data_disk_category' has been deprecated from provider version 1.176.0. Please use resource 'alicloud_cs_kubernetes_node_pool' to manage cluster worker nodes, by using fie
还有这个

2022-07-16 01:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes.go
> +		d.Set("cpu_policy", "none")
不要从读取的内容中再set，这个没有任何意义

2022-07-16 01:17 UTC, xiaozhu36 commented on alicloud/common.go
> +		return true
如果 nil，应该返回 false 吧

2022-07-16 01:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
> +  instance_type    = "rds.mysql.s1.small"
不要写死规格，使用 rds 的datasource去动态的查

2022-07-16 01:17 UTC, xiaozhu36 commented on website/docs/r/cs_kubernetes_node_pool.html.markdown
> +-> **NOTE:** From version 1.176.0+, Support `kms_encryption_context`, `rds_instances`, `system_disk_snapshot_policy_id` and `cpu_policy`.
下个版本是 177

2022-07-16 01:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes.go
> +				Deprecated: "Field 'worker_instance_types' has been deprecated from provider version 1.176.0. Please use resource 'alicloud_cs_kubernetes_node_pool' to manage cluster worker nodes, by using field
下个版本是 177

2022-07-16 02:16 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes.go
> +				Removed:          "Field 'worker_data_disk_size' has been deprecated from provider version 1.176.0. Please use resource 'alicloud_cs_kubernetes_node_pool' to manage cluster worker nodes, by using
done

2022-07-16 02:16 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes.go
> +				Removed:  "Field 'worker_data_disk_category' has been deprecated from provider version 1.176.0. Please use resource 'alicloud_cs_kubernetes_node_pool' to manage cluster worker nodes, by using fie
done

2022-07-16 02:19 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes.go
> +		d.Set("cpu_policy", "none")
这个设置默认值的，有些field无法从openapi获取返回值，如果用户使用默认设置的话需要在state文件里透出默认值

2022-07-16 02:21 UTC, Pangjiping commented on website/docs/r/cs_kubernetes_node_pool.html.markdown
> +-> **NOTE:** From version 1.176.0+, Support `kms_encryption_context`, `rds_instances`, `system_disk_snapshot_policy_id` and `cpu_policy`.
done

2022-07-16 02:21 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes.go
> +				Deprecated: "Field 'worker_instance_types' has been deprecated from provider version 1.176.0. Please use resource 'alicloud_cs_kubernetes_node_pool' to manage cluster worker nodes, by using field
done

2022-07-16 02:22 UTC, Pangjiping commented on alicloud/common.go
> +		return true
这个返回true吧，认为nil也是empty，这个是用来判断map中的value，不过也应该应该到不了这个if分支上

2022-07-16 02:29 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
> +  instance_type    = "rds.mysql.s1.small"
done

2022-07-16 07:50 UTC, xiaozhu36 requested changes

2022-07-16 07:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes.go
> +				Deprecated: "Field 'node_port_range' has been deprecated from provider version 1.177.0. Please use resource 'alicloud_cs_kubernetes_node_pool' to manage cluster worker nodes.",
对于要弃用的属性，都不要设置默认值了

2022-07-16 07:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes.go
> +		d.Set("cpu_policy", "none")
无法从openapi中获取的属性，就不要在read中设置了

2022-07-17 01:29 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes.go
> +				Deprecated: "Field 'node_port_range' has been deprecated from provider version 1.177.0. Please use resource 'alicloud_cs_kubernetes_node_pool' to manage cluster worker nodes.",
done

2022-07-19 12:01 UTC, merged