New Resource `alicloud_ecs_instance_set`
aliyun/terraform-provider-alicloud pull request #5063
Opened 2022-06-13 11:05 UTC by xinmu0426

New Resource `alicloud_ecs_instance_set`

2022-06-14 01:56 UTC, xiaozhu36 requested changes

2022-06-14 01:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_instance_set.go
> +				Required:     true,
这个应该是 Optional 的吧

2022-06-14 01:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_instance_set.go
> +				MaxItems: 16,
这个应该是forcenew 的吧

2022-06-14 01:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_instance_set.go
> +				Computed: true,
launch template 的这几个参数为啥是 Computed 的

2022-06-14 01:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_instance_set.go
> +				Optional: true,
这个也是ForceNew 的吧

2022-06-14 01:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_instance_set.go
> +				Type:     schema.TypeString,
这个应该是 bool 类型吧

2022-06-14 01:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_instance_set_test.go
> +}
update 的测试呢？

另外，测试的话，amount 用10

2022-06-14 01:56 UTC, xiaozhu36 commented on alicloud/service_alicloud_ecs.go
> +				request[fmt.Sprintf("ResourceId.%d", i+1)] = key
这个最多支持50个啊，没看见判断啊

2022-06-14 01:56 UTC, xiaozhu36 commented on alicloud/service_alicloud_ecs.go
> +}
文档

2022-06-25 10:54 UTC, xiaozhu36 requested changes

2022-06-25 10:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk.go
> +	if d.IsNewResource() && val.(bool) {
如果 val 不是bool怎么办

2022-06-25 10:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_instance_set.go
> +				ForceNew:     true,
amount 是否必填还是跟API 保持一致吧

2022-06-25 10:54 UTC, xiaozhu36 commented on website/docs/r/ecs_instance_set.html.markdown
> +
这个地方还是要在开头增加一个说明：
1. 该资源用于批量创建一组配置相同的实例资源，但是该资源不推荐使用，优先推荐使用 alicloud_instance
2. 通过该资源管理的实例中，名称是根据 instance_name 和 unique_suffix 自动生成的，除了 tags 这个属性之外，其他所有的属性都不支持批量修改

2022-06-26 09:51 UTC, xinmu0426 commented on alicloud/resource_alicloud_ecs_disk.go
> +	if d.IsNewResource() && val.(bool) {
默认值false，如过不是bool 就跳过更新

2022-06-26 09:51 UTC, xinmu0426 commented on alicloud/resource_alicloud_ecs_instance_set.go
> +				ForceNew:     true,
done

2022-06-26 10:15 UTC, xinmu0426 commented on website/docs/r/ecs_instance_set.html.markdown
> +
done

2022-06-26 10:44 UTC, xiaozhu36 requested changes

2022-06-26 10:44 UTC, xiaozhu36 commented on alicloud/service_alicloud_ecs.go
> +func (s *EcsService) DescribeEcsInstanceSetCloudAssistantStatus(id string) (objects []map[string]interface{}, err error) {
这个方法如果没有用的话就先去掉吧

2022-06-26 10:44 UTC, xiaozhu36 commented on website/docs/r/ecs_instance_set.html.markdown
> +
只支持 tags 这个属性的修改，这个也提下

2022-06-26 10:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_disk.go
> +	if d.IsNewResource() && val.(bool) {
我的意思是如果 val 不是bool类型，那么类型转换的时候会有问题

2022-06-26 12:34 UTC, xinmu0426 commented on alicloud/service_alicloud_ecs.go
> +func (s *EcsService) DescribeEcsInstanceSetCloudAssistantStatus(id string) (objects []map[string]interface{}, err error) {
用到了，现在已经可以通过云助手判断机器是否启动了

2022-06-26 13:30 UTC, merged