New Resource `alicloud_edas_name_space`; New Datasource `alicloud_edas_name_spaces`;
aliyun/terraform-provider-alicloud pull request #5064
Opened 2022-06-14 02:42 UTC by super-eggs

New Resource `alicloud_edas_name_space`;
New Datasource `alicloud_edas_name_spaces`;

2022-06-15 02:07 UTC, xinmu0426 commented on alicloud/resource_alicloud_edas_name_space.go
> +		},
时间

2022-06-15 02:07 UTC, xinmu0426 commented on alicloud/provider.go
> +			"alicloud_edas_name_spaces":                            dataSourceAlicloudEdasNameSpaces(),
name_spaces 改为 namespace 统一改一下

2022-06-15 02:07 UTC, xinmu0426 commented on alicloud/provider.go
> +			"alicloud_edas_name_spaces":                            dataSourceAlicloudEdasNameSpaces(),
name_spaces 改为 namespace 统一改一下

2022-06-17 07:19 UTC, xiaozhu36 requested changes

2022-06-17 07:19 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_edas_namespaces.go
> +			"spaces": {
这个应该是namespaces吧

2022-06-22 08:43 UTC, xiaozhu36 requested changes

2022-06-22 08:50 UTC, super-eggs commented on alicloud/resource_alicloud_edas_namespace.go
> +	d.Set("namespace_name", object["RegionName"])
产品同学把该资源命名为了 `namespace`，所以这里的资源 Name 为了统一，就定义成了 `namespace_name`。并且该命名也是和 Amp 平台一致的。

2022-06-22 12:28 UTC, merged