resource/alicloud_eci_container_group: Adds the enumeration value of the attribute `restart_policy`
aliyun/terraform-provider-alicloud pull request #5066
Opened 2022-06-14 08:44 UTC by thisnihonglei

2022-06-14 08:48 UTC, thisnihonglei commented on alicloud/data_source_alicloud_eci_container_groups.go
> -												"content": {
目前产品接口返回有bug，创建资源后，content字段不返回，更新后content字段返回。已得到产品确认，属性content查询不允许返回。update接口绕开了这个问题，后面产品会修复。所以去掉该字段。

2022-06-17 07:23 UTC, xiaozhu36 requested changes

2022-06-17 07:23 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eci_container_group.go
> +				ValidateFunc: validation.StringInSlice([]string{"Always", "Never", "OnFailure"}, false),
默认值的修复不是这样吧

2022-06-17 07:23 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_eci_container_groups.go
> -												"content": {
针对这个问题，有做打包测试么

2022-06-17 07:25 UTC, thisnihonglei commented on alicloud/data_source_alicloud_eci_container_groups.go
> -												"content": {
这个是木雁提给我的aone，我按照他aone的模板已复现这个问题。确实存在。aone链接：https://work.aone.alibaba-inc.com/issue/42418545

2022-06-17 07:26 UTC, thisnihonglei commented on alicloud/resource_alicloud_eci_container_group.go
> +				ValidateFunc: validation.StringInSlice([]string{"Always", "Never", "OnFailure"}, false),
这个一开始就是错的，官方API文档里是三个枚举值，不是默认值

2022-06-17 07:27 UTC, thisnihonglei commented on alicloud/data_source_alicloud_eci_container_groups.go
> -												"content": {
这个update接口的问题产品后面会修复

2022-06-22 01:04 UTC, merged