resource/alicloud_instance: Support to remove deployment_set_id
aliyun/terraform-provider-alicloud pull request #5075
Opened 2022-06-16 08:45 UTC by MrWolong

2022-06-17 10:19 UTC, Wanghx0991 commented on alicloud/resource_alicloud_instance.go
> +		if v := d.Get("deployment_set_id"); len(v.(string)) == 0 {
Markdown里说清楚, 从哪个版本里, tf支持部署集的移除, 在markdown这个字段里加个**Note:**

2022-06-17 10:34 UTC, MrWolong commented on alicloud/resource_alicloud_instance.go
> +		if v := d.Get("deployment_set_id"); len(v.(string)) == 0 {
已解决

2022-06-22 01:02 UTC, xiaozhu36 requested changes

2022-06-22 02:20 UTC, MrWolong commented on alicloud/resource_alicloud_instance.go
> +		}
这个参数api文档里面云产品还没有同步更新：https://help.aliyun.com/document_detail/91677.html；
但是，openapi上面，已经可以调用了：https://next.api.aliyun.com/api/Ecs/2014-05-26/ModifyInstanceDeployment?params={%22RemoveFromDeploymentSet%22:false}&lang=GO
![image](https://user-images.githubusercontent.com/36806235/174929384-d7b42b0d-9583-421c-9abb-5037055c86fa.png)

2022-06-24 09:05 UTC, MrWolong commented on alicloud/resource_alicloud_instance.go
> +		}
https://work.aone.alibaba-inc.com/issue/42782374

2022-07-04 05:55 UTC, merged