resource/alicloud_ram_role_policy_attachment: Add retry strategy for create and delete.
aliyun/terraform-provider-alicloud pull request #5081
Opened 2022-06-20 06:04 UTC by thisnihonglei

2022-06-22 01:05 UTC, xiaozhu36 requested changes

2022-06-22 01:05 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ram_role_policy_attachment.go
> +			if IsExpectedErrors(err, []string{"Throttling.User"}) {
为啥不直接用 NeedRetry

2022-06-22 10:02 UTC, thisnihonglei commented on alicloud/resource_alicloud_ram_role_policy_attachment.go
> +			if IsExpectedErrors(err, []string{"Throttling.User"}) {
已改为直接用 NeedRetry

2022-06-25 11:10 UTC, xiaozhu36 requested changes

2022-06-25 11:10 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_key_pair.go
> +			Delete: schema.DefaultTimeout(5 * time.Minute),
这个地方改了，文档不需要改么？

2022-06-25 13:39 UTC, merged