data/alicloud_cs_kubernetes_clusters, alicloud_cs_managed_kubernetes_clusters, alicloud_cs_serverless_kubernetes_clusters: support exporting kube config file
aliyun/terraform-provider-alicloud pull request #5090
Opened 2022-06-21 14:06 UTC by Pangjiping

rewrite common function which gets kube config information for ACK

2022-06-22 03:45 UTC, Wanghx0991 commented on alicloud/data_source_alicloud_cs_kubernetes_clusters.go
> +// getKubeConfig get cluster kube config info.
抽出的部分, 放到`service_alicloud_cs.go` 里

2022-06-22 03:45 UTC, Wanghx0991 commented on website/docs/d/cs_kubernetes_clusters.html.markdown
> +  * `kube_config` - (Optional, Available in 1.173.0+) Kubernetes cluster kube config file prefix. For given `kube_config`, the kube config credentials will be stored with the following file name `kub
标注下不指定`kube_config` 文件名样式

2022-06-22 04:59 UTC, Pangjiping commented on website/docs/d/cs_kubernetes_clusters.html.markdown
> +  * `kube_config` - (Optional, Available in 1.173.0+) Kubernetes cluster kube config file prefix. For given `kube_config`, the kube config credentials will be stored with the following file name `kub
done

2022-06-22 05:09 UTC, Pangjiping commented on website/docs/d/cs_kubernetes_clusters.html.markdown
> +  * `kube_config` - (Optional, Available in 1.173.0+) Kubernetes cluster kube config file prefix. For given `kube_config`, the kube config credentials will be stored with the following file name `kub
done

2022-06-22 05:10 UTC, Pangjiping commented on alicloud/data_source_alicloud_cs_kubernetes_clusters.go
> +// getKubeConfig get cluster kube config info.
done

2022-06-29 08:22 UTC, xiaozhu36 requested changes

2022-06-29 08:22 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cs_kubernetes_clusters.go
> +		if filePrefix, ok := d.GetOk("kube_config"); ok && filePrefix.(string) != "" {
如果是前缀的话，应该是 kube_config_file_prefix

2022-07-20 15:51 UTC, merged