resource/resource_alicloud_instance: Refactored 'resourceAliyunInstanceCreate' and added support for new parameter `system_disk`
aliyun/terraform-provider-alicloud pull request #5101
Opened 2022-06-23 11:13 UTC by MrWolong

2022-06-29 02:41 UTC, super-eggs commented on website/docs/r/instance.html.markdown
> +* `system_disk` - (Optional, ForceNew, Available 1.174.0+) The system disk-related parameter. You can set the SystemDisk.StorageClusterId parameter to specify the ID of the dedicated block storage cl
格式有问题。改成：See the following `Block system_disk `.

2022-06-29 02:41 UTC, super-eggs commented on alicloud/resource_alicloud_instance.go
> +			systemDiskMap["EncryptAlgorithm"] = systemDiskArg["encrypt_algorithm"]
encrypt_algorithm 是哪来的？

2022-06-29 02:41 UTC, super-eggs commented on alicloud/resource_alicloud_instance_test.go
> +							"kms_key_id": "${alicloud_kms_key.key.id}",
为啥只测了两个？

2022-06-29 11:20 UTC, MrWolong commented on website/docs/r/instance.html.markdown
> +* `system_disk` - (Optional, ForceNew, Available 1.174.0+) The system disk-related parameter. You can set the SystemDisk.StorageClusterId parameter to specify the ID of the dedicated block storage cl
已修复

2022-06-29 11:20 UTC, MrWolong commented on alicloud/resource_alicloud_instance.go
> +			systemDiskMap["EncryptAlgorithm"] = systemDiskArg["encrypt_algorithm"]
已修复

2022-07-04 05:54 UTC, xiaozhu36 requested changes

2022-07-04 05:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_instance.go
> +				Optional: true,
system_disk的参数都是平铺的，跟其他的参数保持一致吧

2022-07-05 10:39 UTC, MrWolong commented on alicloud/resource_alicloud_instance.go
> +				Optional: true,
已修改

2022-07-07 09:26 UTC, closed without merging