resource_alicloud_edas_k8s_slb_attachment
aliyun/terraform-provider-alicloud pull request #5171
Opened 2022-07-13 02:29 UTC by junfengP

2022-07-13 02:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=5171) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=5171) before we can accept your contribution.<br/><hr/>**之卫** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=5171) it.</sub>

2022-07-13 02:31 UTC, junfengP commented
new resource: resource_alicloud_edas_k8s_slb_attachment

2022-11-07 11:23 UTC, xiaozhu36 requested changes

2022-11-07 11:23 UTC, xiaozhu36 commented on alicloud/resource_alicloud_edas_k8s_application.go
> +				Deprecated: "Field 'internet_slb_port' has been removed, New Resource 'alicloud_edas_k8s_slb_attachment' replaces it",
has been removed 应该改成 has been deprecated

2022-11-07 11:23 UTC, xiaozhu36 commented on alicloud/resource_alicloud_edas_k8s_application.go
> -
从兼容性上将，这几个字段目前还是得保留

2022-11-07 11:23 UTC, xiaozhu36 commented on alicloud/resource_alicloud_edas_k8s_slb_attachment_test.go
> +
没有看到集成测试的case啊

2022-12-05 02:23 UTC, xiaozhu36 requested changes

2022-12-05 02:23 UTC, xiaozhu36 commented on website/docs/r/edas_k8s_slb_attachment.html.markdown
> +```
这个地方要加上 shell 的标签

2022-12-05 02:23 UTC, xiaozhu36 commented on website/docs/r/edas_k8s_slb_attachment.html.markdown
> +* `id` - The resource ID in terraform of EDAS k8s application.
这个地方要说明下，id 的格式是什么

2022-12-06 06:29 UTC, xiaozhu36 requested changes

2022-12-06 09:27 UTC, merged