resource/alicloud_cloud_firewall_control_policy: Add Support for the international site.
aliyun/terraform-provider-alicloud pull request #5173
Opened 2022-07-13 08:07 UTC by thisnihonglei

2022-07-13 09:43 UTC, thisnihonglei commented on alicloud/service_alicloud_cr_ee.go
> +	wait := incrementalWait(3*time.Second, 5*time.Second)
增加用户限流重新逻辑

2022-07-13 10:15 UTC, xiaozhu36 requested changes

2022-07-13 10:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloud_firewall_control_policy.go
> +				Message:    String("NotApplicable"),
这个error 不要这样构建，直接用 fmt.Errorf("%s", response) 来构建就行

2022-07-13 10:15 UTC, xiaozhu36 commented on alicloud/service_alicloud_cr_ee.go
> +			if IsExpectedErrors(err, []string{"Throttling.User"}) {
needRetry

2022-07-14 03:02 UTC, thisnihonglei commented on alicloud/resource_alicloud_cloud_firewall_control_policy.go
> +				Message:    String("NotApplicable"),
done

2022-07-14 03:02 UTC, thisnihonglei commented on alicloud/service_alicloud_cr_ee.go
> +			if IsExpectedErrors(err, []string{"Throttling.User"}) {
done

2022-07-14 08:44 UTC, xiaozhu36 requested changes

2022-07-14 08:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloud_firewall_control_policy.go
> +			return resource.RetryableError(fmt.Errorf("%s", "NotApplicable"))
为啥不直接用 response

2022-07-14 08:49 UTC, thisnihonglei commented on alicloud/resource_alicloud_cloud_firewall_control_policy.go
> +			return resource.RetryableError(fmt.Errorf("%s", "NotApplicable"))
我看之前的资源切换国际站都是用的“ NotApplicable”错误码，所以写成这样，其他人看代码的时候也能一下子知道这里是做一个切换国际站的逻辑，已改成response。

2022-07-14 09:40 UTC, xiaozhu36 requested changes

2022-07-14 09:40 UTC, xiaozhu36 commented on alicloud/service_alicloud_cr_ee.go
> +			if IsExpectedErrors(err, []string{"Throttling.User"}) || NeedRetry(err) {
直接 NeedRetry 就行

2022-07-14 10:26 UTC, thisnihonglei commented on alicloud/service_alicloud_cr_ee.go
> +			if IsExpectedErrors(err, []string{"Throttling.User"}) || NeedRetry(err) {
done

2022-07-16 00:58 UTC, merged