resource/alicloud_cs_kubernetes_node_pool: update sdk and optimize update logic
aliyun/terraform-provider-alicloud pull request #5177
Opened 2022-07-14 08:44 UTC by Pangjiping

sdk还未更新

2022-07-14 14:38 UTC, Pangjiping commented
field-check depends on #5056 
@xiaozhu36

2022-07-15 06:00 UTC, Pangjiping commented
#5181

2022-07-19 12:51 UTC, xiaozhu36 requested changes

2022-07-19 12:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +		if v, ok := d.Get("scaling_config").([]interface{}); ok {
直接用 GetOk

2022-07-19 15:23 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +			Name:         tea.String(d.Get("name").(string)),
done. .(string)是多余的

2022-07-19 15:23 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +		if v, ok := d.Get("scaling_config").([]interface{}); ok {
done

2022-07-20 15:51 UTC, merged