resource/alicloud_cs_kubernetes_xxx: optimize error message
aliyun/terraform-provider-alicloud pull request #5180
Opened 2022-07-14 12:43 UTC by Pangjiping

2022-08-06 08:49 UTC, xiaozhu36 requested changes

2022-08-06 08:49 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cs_edge_kubernetes_clusters.go
> +		return WrapErrorf(err, DataDefaultErrorMsg, d.Id(), "DescribeClusters", DenverdinoAliyungo)
这个地方不应该改，这个时候 id还是空，没有意义，其他的也是

2022-08-08 03:16 UTC, Pangjiping commented on alicloud/data_source_alicloud_cs_edge_kubernetes_clusters.go
> +		return WrapErrorf(err, DataDefaultErrorMsg, d.Id(), "DescribeClusters", DenverdinoAliyungo)
done

2022-08-12 09:51 UTC, saberrey commented on alicloud/resource_alicloud_cs_edge_kubernetes.go
> +			"worker_ram_role_name": {
先去掉吧

2022-08-12 13:08 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_edge_kubernetes.go
> +			"worker_ram_role_name": {
这个是attributes参数，schema里面漏掉了

2022-09-01 12:56 UTC, closed without merging