resource/alicloud_mns_topic_subscription: Changed sdk to common api; Supported for new parameter `push_type`
aliyun/terraform-provider-alicloud pull request #5187
Opened 2022-07-18 11:12 UTC by MrWolong

2022-07-19 08:14 UTC, MrWolong commented on alicloud/resource_alicloud_mns_topic_subscription_test.go
测试用例都通过了
![image](https://user-images.githubusercontent.com/36806235/179695641-8251bed6-713f-49b0-9bfa-472e1bc21c7a.png)
![image](https://user-images.githubusercontent.com/36806235/179701516-d582b896-148f-4973-aaa6-a4bf988adc9f.png)

2022-07-19 09:05 UTC, xinmu0426 commented on alicloud/resource_alicloud_mns_topic_subscription.go
> +			},
这个没有枚举值么

2022-07-19 09:05 UTC, xinmu0426 commented on alicloud/resource_alicloud_mns_topic_subscription.go
> +	d.Set("filter_tag", object["FilterTag"])
foramtInt包装下

2022-07-19 12:16 UTC, xinmu0426 commented on website/docs/r/mns_topic_subscription.html.markdown
> +-> **NOTE:** Available in 1.177.0+.
应该是178了

2022-07-20 02:53 UTC, MrWolong commented on website/docs/r/mns_topic_subscription.html.markdown
> +-> **NOTE:** Available in 1.177.0+.
![image](https://user-images.githubusercontent.com/36806235/179885858-d9866f22-f7fb-41e1-965d-25d6c5b3e3ac.png)
已经发布的是176

2022-07-20 02:54 UTC, MrWolong commented on website/docs/r/mns_topic_subscription.html.markdown
> +* `update` - (Defaults to 30 mins) Used when update the mns topic subscription.
跑第二个用例，用了1500多秒

2022-07-22 10:01 UTC, xiaozhu36 requested changes

2022-07-22 10:01 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mns_topic_subscription.go
> +				Required:     true,
这个属于非兼容了，新增加的参数不可能是必填的，跟产品i再确认下

2022-07-22 10:01 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mns_topic_subscription.go
> +		return WrapErrorf(err, DefaultErrorMsg, "alicloud_message_service_subscription", action, AlibabaCloudSdkGoERROR)
这个为啥变了

2022-07-22 11:09 UTC, MrWolong commented on alicloud/resource_alicloud_mns_topic_subscription.go
> +				Required:     true,
师兄，那边产品说为了对接terraform，mns又新搞了一套open api，目前最新的文档他们经过讨论之后，就打算先不放出。

2022-07-29 02:26 UTC, MrWolong commented on alicloud/resource_alicloud_mns_topic_subscription.go
> +		return WrapErrorf(err, DefaultErrorMsg, "alicloud_message_service_subscription", action, AlibabaCloudSdkGoERROR)
已修改

2022-07-29 02:27 UTC, MrWolong commented on alicloud/resource_alicloud_mns_topic_subscription.go
> +			},
![image](https://user-images.githubusercontent.com/36806235/181670129-f456b49f-b305-48b4-b8c2-3a6790287db6.png)

2022-10-08 07:00 UTC, closed without merging