testcase: fix ci test error for resource/alicloud_cs_managed_kubernetes
aliyun/terraform-provider-alicloud pull request #5249
Opened 2022-08-01 02:39 UTC by Pangjiping

2022-08-01 03:13 UTC, xiaozhu36 requested changes

2022-08-01 03:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_managed_kubernetes_test.go
> -					"deletion_protection": "true",
deletion_protection 这个参数也得测试

2022-08-01 03:50 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_managed_kubernetes_test.go
> -					"deletion_protection": "true",
done

2022-08-02 11:35 UTC, xiaozhu36 requested changes

2022-08-02 11:35 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters_test.go
> +	preRegion := os.Getenv("ALICLOUD_REGION")
如果这个case 只是部分region支持，那么这个地方只需要增加一个 precheck 就行了，不需要单独写

2022-08-06 08:48 UTC, merged