resource/alicloud_alikafka_instance: Changed sdk to common api; Supported for new parameter `kms_key_id`
aliyun/terraform-provider-alicloud pull request #5261
Opened 2022-08-03 10:11 UTC by MrWolong

2022-08-03 11:06 UTC, xinmu0426 commented on alicloud/service_alicloud_alikafka.go
> +	deadline := time.Now().Add(time.Duration(timeout) * time.Second)
这个状态刷新是啥意思

2022-08-03 14:27 UTC, MrWolong commented on alicloud/service_alicloud_alikafka.go
> +	deadline := time.Now().Add(time.Duration(timeout) * time.Second)
等待alikafka的实例状态达到目标状态，主要用在创建和更新操作，alikafka在创建和部署的时候，会有一定延迟，所以必须需要状态刷新。

2022-08-04 05:01 UTC, MrWolong commented on alicloud/service_alicloud_alikafka.go
> +		if fmt.Sprint(object["InstanceId"]) == id && fmt.Sprint(object["TopicNumLimit"]) == topicQuota && fmt.Sprint(object["DiskSize"]) == diskSize && fmt.Sprint(object["IoMax"]) == ioMax && fmt.Sprint(ob
这个跟云产品那边确认了一下，他们的产品在做更新操作的时候，对状态不是很有影响，所以必须用这个方法检测，字段是否更新成功。

2022-08-04 05:02 UTC, MrWolong commented on alicloud/service_alicloud_alikafka.go
> +	deadline := time.Now().Add(time.Duration(timeout) * time.Second)
已更新为状态刷新

2022-08-05 02:51 UTC, xiaozhu36 requested changes

2022-08-05 02:51 UTC, xiaozhu36 commented on alicloud/service_alicloud_alikafka.go
> +func (s *AlikafkaService) WaitForAliKafkaInstanceUpdated(id string, topicQuota string, diskSize string, ioMax string,
如果需要判断这么多参数的话，就直接吧 d 做了参数，然后从d里面取

2022-08-05 08:44 UTC, MrWolong commented on alicloud/service_alicloud_alikafka.go
> +func (s *AlikafkaService) WaitForAliKafkaInstanceUpdated(id string, topicQuota string, diskSize string, ioMax string,
已修复

2022-08-05 09:14 UTC, merged