New Resource alicloud_cms_event_rule
aliyun/terraform-provider-alicloud pull request #5268
Opened 2022-08-05 09:00 UTC by MrWolong

2022-08-05 09:09 UTC, xinmu0426 commented on alicloud/resource_alicloud_cms_event_rule.go
> +			Create: schema.DefaultTimeout(30 * time.Minute),
这快和文档对不上啊，按照实际测试时间写吧

2022-08-05 09:09 UTC, xinmu0426 commented on alicloud/resource_alicloud_cms_event_rule_test.go
> +func TestAccAlicloudCmsEventRule_basic00(t *testing.T) {
加一下sweerper

2022-08-05 09:09 UTC, xinmu0426 commented on alicloud/provider.go
> +			"alicloud_cms_event_rule":                                       resourceAlicloudCmsEventRule(),
datasource呢

2022-08-08 09:37 UTC, MrWolong commented on alicloud/resource_alicloud_cms_event_rule_test.go
> +func TestAccAlicloudCmsEventRule_basic00(t *testing.T) {
已添加

2022-08-08 09:37 UTC, MrWolong commented on alicloud/resource_alicloud_cms_event_rule.go
> +			Create: schema.DefaultTimeout(30 * time.Minute),
已修改

2022-08-08 09:49 UTC, MrWolong commented on alicloud/resource_alicloud_cms_event_rule_test.go
> +	p := Provider().(*schema.Provider).ResourcesMap
单元测试覆盖率：97.7%

2022-08-08 10:34 UTC, MrWolong commented on alicloud/data_source_alicloud_cms_event_rules.go
> +	return &schema.Resource{
1、https://aone.alibaba-inc.com/v2/project/1086837/bug/43820277# 《cms_even_rule：PutEventRule中EventPattern属性文档上显示可创建多个，但是通过查询接口只返回一个》
2、https://aone.alibaba-inc.com/v2/project/1086837/bug/43820433# 《cms_even_rule：PutEventRule中CustomFilters属性无论填什么都报内部错误》
3、https://aone.alibaba-inc.com/v2/project/1086837/bug/43820592# 《cms_even_rule：PutEventRule中EventType属性传入CUSTOM报错》
4、https://aone.alibaba-inc.com/v2/project/1086837/bug/43821130# 《cms_even_rule：DescribeEventRuleAttribute查询EventPattern不完整》

2022-08-09 02:07 UTC, xinmu0426 commented on alicloud/resource_alicloud_cms_event_rule.go
> +				ForceNew: true,
这个有限制条件么

2022-08-09 02:07 UTC, xinmu0426 commented on alicloud/resource_alicloud_cms_event_rule.go
> +			"state": {
改为status,统一一下

2022-08-09 02:14 UTC, MrWolong commented on alicloud/resource_alicloud_cms_event_rule.go
> +				ForceNew: true,
这个没有限制条件

2022-08-09 04:10 UTC, MrWolong commented on alicloud/resource_alicloud_cms_event_rule.go
> +			"state": {
已修复

2022-08-10 03:09 UTC, xinmu0426 commented on alicloud/data_source_alicloud_cms_event_rules.go
> +		request["NamePrefix"] = v
PageNumber 和  PageSize 这种分页问题看下郭志远提的那个新资源，改成一样的

2022-08-10 06:32 UTC, MrWolong commented on alicloud/data_source_alicloud_cms_event_rules.go
> +		request["NamePrefix"] = v
已修改

2022-08-12 05:53 UTC, xiaozhu36 requested changes

2022-08-12 07:50 UTC, MrWolong commented on alicloud/data_source_alicloud_cms_event_rules.go
> +			"event_rules": {
已修改

2022-08-18 09:39 UTC, merged