testcase: Adds new unit test case for resource alicloud_ga_listener alicloud_ga_endpoint_group alicloud_ga_bandwidth_package
aliyun/terraform-provider-alicloud pull request #5283
Opened 2022-08-09 09:43 UTC by thisnihonglei

2022-08-09 09:44 UTC, thisnihonglei commented on alicloud/resource_alicloud_ga_bandwidth_package_test.go
> +func TestUnitAlicloudGaBandwidthPackage(t *testing.T) {
单测覆盖率93.4%

2022-08-09 09:44 UTC, thisnihonglei commented on alicloud/resource_alicloud_ga_endpoint_group_test.go
> +func TestUnitAlicloudGaEndpointGroup(t *testing.T) {
单测覆盖率97.6%

2022-08-09 09:44 UTC, thisnihonglei commented on alicloud/resource_alicloud_ga_listener_test.go
> +func TestUnitAlicloudGaListener(t *testing.T) {
单测覆盖率95.6%

2022-08-10 06:26 UTC, xiaozhu36 requested changes

2022-08-10 06:26 UTC, xiaozhu36 commented on alicloud/service_alicloud_ga.go
> +	}
为啥这个地方判断的是 State，如果API存在不返回的情况，那么需要提交aone让云产品修复

2022-08-11 09:14 UTC, merged