resource/alicloud_emr_cluster: support modify cluster service config …
aliyun/terraform-provider-alicloud pull request #5292
Opened 2022-08-11 12:56 UTC by qiyinfei

…and custom meta user rds

2022-08-11 12:56 UTC, qiyinfei commented
![image](https://user-images.githubusercontent.com/30532003/184138326-67474ec4-2743-4c4e-a87c-c29204fc85bc.png)

![image](https://user-images.githubusercontent.com/30532003/184138364-df6f8791-cef7-4759-b7d3-cee87d302147.png)

2022-08-15 03:26 UTC, qiyinfei commented
![image](https://user-images.githubusercontent.com/30532003/184572152-46566a4e-ce35-448d-9b88-01cb635510f0.png)

![Uploading image.png…]()

2022-08-17 01:22 UTC, xiaozhu36 requested changes

2022-08-17 01:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_emr_cluster.go
> +				Required:     true,
新增的参数不能是 Required 的，这属于非兼容变更

2022-08-17 01:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_emr_cluster.go
> +							Type:     schema.TypeString,
password 要标记为 sensitive

2022-08-17 01:22 UTC, xiaozhu36 commented on website/docs/r/emr_cluster.html.markdown
> +* `resource_group_id` - (Optional, Available in 1.181.0+) The Id of resource group which the emr-cluster belongs.
下个版本是 182

2022-08-17 07:02 UTC, xiaozhu36 requested changes

2022-08-17 07:02 UTC, xiaozhu36 commented on alicloud/resource_alicloud_emr_cluster.go
> +				Default:      "local",
不要加default，如果存在系统默认值是 local，那么设置为 Computed

2022-08-17 08:33 UTC, merged