resource/alicloud_reserved_instance: Supported `period_unit` set to `Month`, and `period` set to `5`
aliyun/terraform-provider-alicloud pull request #5303
Opened 2022-08-15 09:30 UTC by MrWolong

2022-08-16 12:40 UTC, xinmu0426 commented on alicloud/resource_alicloud_reserved_instance.go
> -				Default:      "Year",
不要改这个Default 值

2022-08-16 12:40 UTC, xinmu0426 commented on website/docs/r/reserved_instance.html.markdown
> +* `period` - (Optional, ForceNew) The validity period of the reserved instance. Default value: `1`. **NOTE:** From version 1.181.0, `period` can be set to `5`, when `period_unit` is `Year`.
说明在那个版本开始支持Month

2022-08-16 12:41 UTC, xinmu0426 commented on website/docs/r/reserved_instance.html.markdown
> +* `period_unit` - (Optional, ForceNew) The unit of the validity period of the reserved instance. Valid value: `Month`, `Year`. Default value: `Month`. **NOTE:** From version 1.181.0, `period_unit` ca
Default value: `Year `

2022-08-17 10:55 UTC, MrWolong commented on website/docs/r/reserved_instance.html.markdown
> +* `period_unit` - (Optional, ForceNew) The unit of the validity period of the reserved instance. Valid value: `Month`, `Year`. Default value: `Month`. **NOTE:** From version 1.181.0, `period_unit` ca
已修改

2022-08-17 10:55 UTC, MrWolong commented on alicloud/resource_alicloud_reserved_instance.go
> -				Default:      "Year",
已修改

2022-08-18 01:50 UTC, MrWolong commented on website/docs/r/reserved_instance.html.markdown
> +* `offering_type` - (Optional, ForceNew) Payment type of the RI. Default value: `All Upfront`. **NOTE:** From version 1.182.0, fix the field `offering_type` from `Required` to `Optional`. Valid value
offering_type为可选字段
![image](https://user-images.githubusercontent.com/36806235/185274506-b1564ac7-cf2d-4c13-8e9d-3fb12dda7ba1.png)

2022-08-18 01:51 UTC, MrWolong commented on website/docs/r/reserved_instance.html.markdown
> +* `instance_type` - (Required, ForceNew) Instance type of the RI. For more information, see [Instance type families](https://www.alibabacloud.com/help/doc-detail/25378.html). **NOTE:** From version 1
instance_type为必要字段
![image](https://user-images.githubusercontent.com/36806235/185274639-c2edbf2d-60e7-4787-aaf4-99f0e6374605.png)

2022-08-23 05:16 UTC, xiaozhu36 requested changes

2022-08-23 05:16 UTC, xiaozhu36 commented on website/docs/r/reserved_instance.html.markdown
> +* `instance_type` - (Required, ForceNew) Instance type of the RI. For more information, see [Instance type families](https://www.alibabacloud.com/help/doc-detail/25378.html). **NOTE:** From version 1
如果原来代码中就是 Required，那么不用在后面写那一个note，直接改过来就行

2022-08-23 05:16 UTC, xiaozhu36 commented on website/docs/r/reserved_instance.html.markdown
> +* `instance_type` - (Required, ForceNew) Instance type of the RI. For more information, see [Instance type families](https://www.alibabacloud.com/help/doc-detail/25378.html). **NOTE:** From version 1
另外，改成 183 支持吧

2022-08-23 06:56 UTC, MrWolong commented on website/docs/r/reserved_instance.html.markdown
> +* `instance_type` - (Required, ForceNew) Instance type of the RI. For more information, see [Instance type families](https://www.alibabacloud.com/help/doc-detail/25378.html). **NOTE:** From version 1
已修改

2022-08-24 02:12 UTC, merged