resource/alicloud_ga_listener: Added the field `security_policy_id`
aliyun/terraform-provider-alicloud pull request #5307
Opened 2022-08-16 11:49 UTC by MrWolong

2022-08-16 12:42 UTC, xinmu0426 commented on alicloud/resource_alicloud_ga_listener_test.go
> +	MIIDRjCCAq+gAwIBAgIJAJn3ox4K13PoMA0GCSqGSIb3DQEBBQUAMHYxCzAJBgNV
这个去掉

2022-08-17 08:12 UTC, MrWolong commented on alicloud/resource_alicloud_ga_listener_test.go
> +	MIIDRjCCAq+gAwIBAgIJAJn3ox4K13PoMA0GCSqGSIb3DQEBBQUAMHYxCzAJBgNV
已修复

2022-08-23 05:14 UTC, xiaozhu36 requested changes

2022-08-23 05:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_listener_test.go
> +func TestAccAlicloudGaListener_basic1(t *testing.T) {
不用新起一个case，直接加到上面的case中就行

2022-08-23 05:14 UTC, xiaozhu36 commented on website/docs/r/ga_listener.html.markdown
> +* `security_policy_id` - (Optional, Available in v1.182.0+) The ID of the security policy. **NOTE:** Only HTTPS listeners support this parameter. Valid values:
改成 183 支持吧

2022-08-23 08:01 UTC, MrWolong commented on alicloud/resource_alicloud_ga_listener_test.go
> +func TestAccAlicloudGaListener_basic1(t *testing.T) {
已修改

2022-08-23 08:01 UTC, MrWolong commented on website/docs/r/ga_listener.html.markdown
> +* `security_policy_id` - (Optional, Available in v1.182.0+) The ID of the security policy. **NOTE:** Only HTTPS listeners support this parameter. Valid values:
已修改

2022-08-24 02:14 UTC, xiaozhu36 requested changes

2022-08-24 02:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_listener_test.go
> +  	certificate_id = join("-", [data.alicloud_cas_certificates.default.certificates.0.id, "cn-hangzhou"])
最后加cn-hangzhou是什么意思，如果跟 region有关，应该加当前运行case 的regionid，而不是写死的

2022-08-25 01:41 UTC, MrWolong commented on alicloud/resource_alicloud_ga_listener_test.go
> +  	certificate_id = join("-", [data.alicloud_cas_certificates.default.certificates.0.id, "cn-hangzhou"])
已修复

2022-08-26 06:41 UTC, merged