New Resource `alicloud_dbs_backup_plan`; New Datasource `alicloud_dbs_backup_plans`;
aliyun/terraform-provider-alicloud pull request #5341
Opened 2022-08-26 07:16 UTC by super-eggs

New Resource `alicloud_dbs_backup_plan`;
New Datasource `alicloud_dbs_backup_plans`;

2022-09-01 02:47 UTC, xinmu0426 commented on alicloud/data_source_alicloud_dbs_backup_plans.go
> +				Default:  false,
这个默认值改为true吧

2022-09-01 02:47 UTC, xinmu0426 commented on alicloud/resource_alicloud_dbs_backup_plan.go
> +	stateConf := BuildStateConf([]string{}, []string{"running"}, d.Timeout(schema.TimeoutCreate), 5*time.Second, dbsService.DbsBackupPlanStateRefreshFunc(d.Id(), []string{"stop"}))
有没有可能创建失败

2022-09-01 02:47 UTC, xinmu0426 commented on alicloud/resource_alicloud_dbs_backup_plan.go
> +	err = resource.Retry(d.Timeout(schema.TimeoutCreate), func() *resource.RetryError {
TimeoutCreate 改为 client.GetRetryTimeout(d.Timeout(schema.TimeoutCreate)

2022-09-01 02:47 UTC, xinmu0426 commented on website/docs/r/dbs_backup_plan.html.markdown
> +subcategory: "DBS"
Database Backup(DBS)

2022-09-01 02:47 UTC, xinmu0426 commented on website/docs/r/dbs_backup_plan.html.markdown
> +-> **NOTE:** Available in v1.183.0+.
184

2022-09-01 02:47 UTC, xinmu0426 commented on website/docs/d/dbs_backup_plans.html.markdown
> +subcategory: "DBS"
Database Backup(DBS)

2022-09-01 02:47 UTC, xinmu0426 commented on website/docs/d/dbs_backup_plans.html.markdown
> +-> **NOTE:** Available in v1.183.0+.
184

2022-09-05 03:15 UTC, xiaozhu36 requested changes

2022-09-05 03:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dbs_backup_plan_test.go
> +					"database_region":               "cn-hangzhou",
这个region不要写死

2022-09-05 03:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dbs_backup_plan.go
> +		return "Thursday"
这种不一致的问题有开aone么

2022-09-05 07:43 UTC, super-eggs commented on alicloud/resource_alicloud_dbs_backup_plan.go
> +		return "Thursday"
已提Aone

2022-09-06 08:14 UTC, xiaozhu36 requested changes

2022-09-06 08:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dbs_backup_plan.go
> +	if d.HasChange("status") {
这个地方不需要判断是否是新建么

2022-09-07 02:32 UTC, super-eggs commented on alicloud/resource_alicloud_dbs_backup_plan.go
> +	if d.HasChange("status") {
不需要，这个参数 status 没有在 Create 配置。

2022-09-08 11:17 UTC, merged