resource/alicloud_bastionhost_instance: support for `payment_type`, `renewal_status` `renew_period`.
aliyun/terraform-provider-alicloud pull request #5342
Opened 2022-08-26 07:22 UTC by xinmu0426

resource/alicloud_bastionhost_instance: support for `payment_type`, `renewal_status` `renew_period`.

2022-09-26 06:51 UTC, xiaozhu36 requested changes

2022-09-26 06:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_bastionhost_instance.go
> +			},
这两个属性没有在 read 中set 啊

2022-09-27 03:53 UTC, xinmu0426 commented on alicloud/resource_alicloud_bastionhost_instance.go
> +			},
已添加

2022-09-27 07:34 UTC, xiaozhu36 requested changes

2022-09-27 07:34 UTC, xiaozhu36 commented on alicloud/resource_alicloud_bastionhost_instance.go
> +				DiffSuppressFunc: func(k, old, new string, d *schema.ResourceData) bool {
这个既然不能修改，应该得改成 ForceNew 吧

2022-09-28 07:24 UTC, merged