New Resource `alicloud_nas_smb_acl_attachment` & alicloud_nas_access_rule support `filesystem_type` and Ipv6
aliyun/terraform-provider-alicloud pull request #5353
Opened 2022-08-30 07:39 UTC by feiybox

testing report:

1. alicloud_nas_access_rule support `filesystem_type` and Ipv6
Resource：
![image](https://user-images.githubusercontent.com/30174533/187376577-b68eef6a-bf3c-4780-a318-3ba574094271.png)
Data：
![image](https://user-images.githubusercontent.com/30174533/187376645-eac6314c-ed87-48d7-8412-a6d76a1a794d.png)
Terraform：
![image](https://user-images.githubusercontent.com/30174533/187376861-3971c441-fafe-4f12-8c5c-6f30520ccb1e.png)
![image](https://user-images.githubusercontent.com/30174533/187377043-cc680b30-4cd9-4424-af52-2216a67a9e65.png)
![image](https://user-images.githubusercontent.com/30174533/187377179-d571dca6-af0f-499c-a4cf-57e7cd2c8f6d.png)

2. New Resource `alicloud_nas_smb_acl_attachment`
Resource：
![image](https://user-images.githubusercontent.com/30174533/187377441-80e91023-c737-4475-8b7e-03799da1063a.png)
Terraform：
![image](https://user-images.githubusercontent.com/30174533/187377523-95cfad4e-50b1-4d40-a861-1eec09939eb9.png)
![image](https://user-images.githubusercontent.com/30174533/187377573-eaf83ad9-aa82-4621-ab68-d2477243559b.png)

2022-09-02 03:37 UTC, super-eggs commented on alicloud/resource_alicloud_nas_smb_acl_attachment.go
> +	request["EnableAnonymousAccess"] = d.Get("enable_anonymous_access")
bool 类型取值使用 d.GetOkExists

2022-09-02 03:37 UTC, super-eggs commented on alicloud/resource_alicloud_nas_smb_acl_attachment.go
> +	d.SetId(fmt.Sprint(request["FileSystemId"], ":", request["Keytab"], ":", request["KeytabMd5"]))
为啥要定义成多级id？ 我看查询，更新，删除都只需要 FileSystemId 就可以哇

2022-09-02 03:37 UTC, super-eggs commented on alicloud/service_alicloud_nas.go
> +	parts, err := ParseResourceId(id, 3)
不兼容

2022-09-02 03:37 UTC, super-eggs commented on website/docs/r/nas_smb_acl_attachment.html.markdown
> +-> **NOTE:** Available in v1.34.0+.
1.184.0

2022-09-02 03:37 UTC, super-eggs commented on website/docs/r/nas_access_rule.html.markdown
ID 说明对应调整一下，还有底部的示例

2022-09-07 03:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=5353) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=5353) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: feiybox<br/>:x: wb-wch367513<br/><hr/>**wb-wch367513** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=5353) it.</sub>

2022-09-08 09:31 UTC, super-eggs commented on website/docs/d/nas_access_rules.html.markdown
> +* `ids` - A list of rule IDs, Each element set to `access_rule_id` (Each element formats as `<access_group_name>:<access_rule_id>:<access_rule_id>` before 1.53.0).
这里不需要改。

2022-09-08 09:31 UTC, super-eggs commented on alicloud/resource_alicloud_nas_access_rule.go
> +		request["SourceCidrIp"] = d.Get("source_cidr_ip")
这里测试了吗？我看文档中 SourceCidrIp 为必填

2022-09-08 09:31 UTC, super-eggs commented on website/docs/r/nas_access_rule.html.markdown
> +                                     You must set this parameter to an IPv6 address or CIDR block.
You must set one of "ipv6_source_cidr_ip" and "source_cidr_ip"

2022-09-09 02:08 UTC, super-eggs commented on website/docs/d/nas_access_rules.html.markdown
> +* `ids` - A list of rule IDs, Each element set to `access_rule_id` (Each element formats as `<access_group_name>:<access_rule_id>:<file_system_type>` before 1.53.0).
这里的 ids 应该改成 多级id。

2022-09-13 02:56 UTC, xiaozhu36 requested changes

2022-09-13 02:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_nas_smb_acl_attachment_test.go
> +  zone_id       = "cn-hangzhou-g"
不要写死 可用区，使用 datasource 动态查询

2022-09-13 02:56 UTC, xiaozhu36 commented on website/docs/r/nas_smb_acl_attachment.html.markdown
> +
这个地方要加上import 的示例

2022-09-15 06:34 UTC, xiaozhu36 requested changes

2022-09-15 06:34 UTC, xiaozhu36 commented on website/docs/r/nas_smb_acl_attachment.html.markdown
> +-> **NOTE:** Available in 1.185.0+.
1.185.0 版本已经发布了，下个版本是 1.186.0

2022-09-16 01:43 UTC, merged