resource/alicloud_edge_kubernetes: add new fields `cluster_spec`,`runtime` and `load_balancer_spec`
aliyun/terraform-provider-alicloud pull request #5355
Opened 2022-08-30 13:25 UTC by Pangjiping

2022-09-01 06:12 UTC, xiaozhu36 requested changes

2022-09-01 06:12 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_edge_kubernetes.go
> -			},
这个为啥要去掉

2022-09-01 06:12 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_edge_kubernetes.go
>  			},
optional 改成 required 属于非兼容变更

2022-09-01 06:12 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_edge_kubernetes.go
>  				Type:     schema.TypeString,
这个也一样

2022-09-01 06:12 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_edge_kubernetes.go
> +				Type:     schema.TypeMap,
这个应该是 TypeSet

2022-09-01 07:01 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_edge_kubernetes.go
> +				Type:     schema.TypeMap,
为了和其他集群的模版文件保持对齐，其他都用的map

2022-09-01 07:01 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_edge_kubernetes.go
> -			},
https://help.aliyun.com/document_detail/178718.html

2022-09-05 02:00 UTC, Pangjiping commented
#5219

2022-09-06 09:04 UTC, xiaozhu36 requested changes

2022-09-06 09:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_edge_kubernetes.go
> +				Type:     schema.TypeMap,
这种还是应该改成标准的类型

2022-09-06 10:58 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_edge_kubernetes.go
> +				Type:     schema.TypeMap,
先保持map吧，三种集群用的一样的buildArgs方法，如果改成set就不兼容了需要另起一个方法

2022-09-08 02:23 UTC, xiaozhu36 requested changes

2022-09-08 02:23 UTC, xiaozhu36 commented on website/docs/r/cs_edge_kubernetes.html.markdown
> +* `cluster_spec` - (Optional, Available in 1.184.0+) The cluster specifications of kubernetes cluster,which can be empty. Valid values:
下个版本 185

2022-09-08 09:00 UTC, Pangjiping commented on website/docs/r/cs_edge_kubernetes.html.markdown
> +* `cluster_spec` - (Optional, Available in 1.184.0+) The cluster specifications of kubernetes cluster,which can be empty. Valid values:
done

2022-09-09 09:20 UTC, merged