resource/alicloud_cs_kubernetes_node_pool: change api for nodepool kubelet config
aliyun/terraform-provider-alicloud pull request #5356
Opened 2022-08-30 16:17 UTC by Pangjiping

2022-09-06 09:01 UTC, xiaozhu36 requested changes

2022-09-06 10:03 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +		rolling, err := setRollingPolicy(d.Get("rolling_policy").([]interface{}))
done

2022-09-08 02:17 UTC, xiaozhu36 requested changes

2022-09-08 02:17 UTC, xiaozhu36 commented on website/docs/r/cs_kubernetes_node_pool.html.markdown
> +  * `max_parallelism` - (Optional, Available in 1.184.0+) Maximum parallel number nodes during rolling upgrade. The value of this field should be greater than `0`, and if it's set to a number less th
下个版本是 185了

2022-09-08 02:17 UTC, xiaozhu36 commented on alicloud/errors.go
> +const IdMsgWithTask = IdMsg + "TaskInfo: %s"
针对特殊的错误信息，不建议设置为const

2022-09-08 09:02 UTC, Pangjiping commented on alicloud/errors.go
> +const IdMsgWithTask = IdMsg + "TaskInfo: %s"
把我把它放在csservice里面了，后面有个pr会用到很多次这个

2022-09-08 09:08 UTC, Pangjiping commented on website/docs/r/cs_kubernetes_node_pool.html.markdown
> +  * `max_parallelism` - (Optional, Available in 1.184.0+) Maximum parallel number nodes during rolling upgrade. The value of this field should be greater than `0`, and if it's set to a number less th
done

2022-09-09 09:19 UTC, merged