testcase: Adds new unit test case for resource alicloud_slb_acl alicloud_sddp_instance alicloud_scdn_domain_config
aliyun/terraform-provider-alicloud pull request #5364
Opened 2022-09-01 10:13 UTC by thisnihonglei

2022-09-01 10:36 UTC, thisnihonglei commented on alicloud/resource_alicloud_scdn_domain_config_test.go
> +func TestUnitAlicloudScdnDomainConfig(t *testing.T) {
单测覆盖率93.9%

2022-09-01 10:36 UTC, thisnihonglei commented on alicloud/resource_alicloud_sddp_instance_test.go
> +func TestUnitAlicloudSDDPInstance(t *testing.T) {
单测覆盖率85.6%

2022-09-01 10:39 UTC, thisnihonglei commented on alicloud/resource_alicloud_slb_acl_test.go
> +func TestUnitAlicloudSlbAcl(t *testing.T) {
单测覆盖率94.2%

2022-09-05 03:17 UTC, xiaozhu36 requested changes

2022-09-05 03:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_sddp_instance.go
>  			},
这些为啥要改成 Optional 的？

2022-09-05 03:44 UTC, thisnihonglei commented on alicloud/resource_alicloud_sddp_instance.go
>  			},
这里其实是文档有问题，已调整文档

2022-09-06 08:15 UTC, xiaozhu36 requested changes

2022-09-06 08:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_sddp_instance.go
> +				Optional: true,
这个为啥要改成 Optional 的

2022-09-06 08:32 UTC, thisnihonglei commented on alicloud/resource_alicloud_sddp_instance.go
> +				Optional: true,
这个属性不是只读的，在update接口中是作为选填参数传递的

2022-09-06 11:11 UTC, xiaozhu36 requested changes

2022-09-06 11:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_sddp_instance.go
> +				Optional: true,
如果这样，为啥 集成测试case 中没有对这个属性进行测试，需要补上

2022-09-09 09:34 UTC, thisnihonglei commented on alicloud/resource_alicloud_sddp_instance.go
> +				Optional: true,
if d.HasChange("oss_size") {
		update = true
	}
	if v, ok := d.GetOk("oss_size"); ok {
		parameterMapList = append(parameterMapList, map[string]interface{}{
			"Code":  "UDC",
			"Value": v,
		})
	}
if d.HasChange("udc") {
		update = true
	}
	if v, ok := d.GetOk("udc"); ok {
		parameterMapList = append(parameterMapList, map[string]interface{}{
			"Code":  "UDC",
			"Value": v,
		})
	}
Update这里这两个值修改的时候都是赋值到同一个Code的Value中，测试用例中有udc这个属性的测试，所以没有oss_size

2022-09-16 02:10 UTC, merged