resource/alicloud_cs_managed_kubernetes: Fix migrate bug
aliyun/terraform-provider-alicloud pull request #5371
Opened 2022-09-05 07:57 UTC by Pangjiping

2022-09-06 09:02 UTC, xiaozhu36 requested changes

2022-09-06 09:02 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes.go
> +			log.Printf("[DEBUG] Failed to DescribeCsManagedKubernetes cluster %s", d.Id())
如果有报错，应该直接抛出来

2022-09-06 09:42 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes.go
> +			log.Printf("[DEBUG] Failed to DescribeCsManagedKubernetes cluster %s", d.Id())
这个错误不需要抛出，describe逻辑是做一个保护作用的，不要让这个change逻辑完全依赖于用户的输入，但是在这个接口失败的时候也不应该阻塞这个change。后端会再校验一次的，不会触发误操作

2022-09-08 02:21 UTC, xiaozhu36 requested changes

2022-09-08 02:21 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes.go
> +			log.Printf("[DEBUG] Failed to DescribeCsManagedKubernetes cluster %s", d.Id())
那就把注释加上

2022-09-08 09:11 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes.go
> +			log.Printf("[DEBUG] Failed to DescribeCsManagedKubernetes cluster %s", d.Id())
done

2022-09-09 09:18 UTC, xiaozhu36 requested changes

2022-09-09 09:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes.go
> +			// 不需要跑出错误,后端仍有一次校验逻辑防止误操作
注释要用英文

2022-09-09 09:29 UTC, Pangjiping commented on alicloud/resource_alicloud_cs_kubernetes.go
> +			// 不需要跑出错误,后端仍有一次校验逻辑防止误操作
done

2022-09-09 10:39 UTC, merged