resource/alicloud_lindorm_instance: Adds new attribute `vpc_id` expose the `vpc_id` parameter
aliyun/terraform-provider-alicloud pull request #5373
Opened 2022-09-05 09:11 UTC by thisnihonglei

2022-09-06 08:17 UTC, xiaozhu36 requested changes

2022-09-06 08:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_lindorm_instance.go
> +		if v, ok := request["VPCId"].(string); !ok || v == "" {
如果 vpcid和zoneid都设置了，那这个地方就不用再掉 DescribeVSwitchWithTeadsl了啊

2022-09-06 11:10 UTC, xiaozhu36 requested changes

2022-09-06 11:10 UTC, xiaozhu36 commented on alicloud/resource_alicloud_lindorm_instance.go
> +				Optional: true,
这个应该是 Computed 的吧

2022-09-07 01:56 UTC, thisnihonglei commented on alicloud/resource_alicloud_lindorm_instance.go
> +		if v, ok := request["VPCId"].(string); !ok || v == "" {
done

2022-09-07 01:56 UTC, thisnihonglei commented on alicloud/resource_alicloud_lindorm_instance.go
> +				Optional: true,
done

2022-09-08 11:17 UTC, merged