New Resource: `alicloud_log_oss_export`
aliyun/terraform-provider-alicloud pull request #5440
Opened 2022-09-19 08:13 UTC by panawala

add new resource `alicloud_log_oss_export`

2022-09-21 05:30 UTC, panawala commented
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLogOssExport -timeout=300m
=== RUN   TestAccAlicloudLogOssExport_basic
--- PASS: TestAccAlicloudLogOssExport_basic (73.57s)
=== RUN   TestAccAlicloudLogOssExport_parquest
--- PASS: TestAccAlicloudLogOssExport_parquest (73.52s)
=== RUN   TestAccAlicloudLogOssExport_csv
--- PASS: TestAccAlicloudLogOssExport_csv (73.66s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  220.847s

2022-09-21 07:11 UTC, xiaozhu36 requested changes

2022-09-21 07:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_oss_export_test.go
> +	name := fmt.Sprintf("test-log-oss-export-%d", rand)
测试名称用 tf-testacc 开头，用于后续清理

2022-09-21 07:11 UTC, xiaozhu36 commented on alicloud/service_alicloud_log.go
> +
这个地方为啥要再封一个函数

2022-09-21 07:24 UTC, panawala commented on alicloud/service_alicloud_log.go
> +
这个后面可能在加另外的DescribeLogXXXExport，都会调用DescribeLogExport

2022-09-21 07:24 UTC, panawala commented on alicloud/resource_alicloud_log_oss_export_test.go
> +	name := fmt.Sprintf("test-log-oss-export-%d", rand)
done

2022-09-21 07:40 UTC, panawala commented on alicloud/resource_alicloud_log_oss_export.go
> +				Default:      "none",
done

2022-09-21 08:32 UTC, panawala commented on alicloud/service_alicloud_log.go
> +
DescribeLogExport改成小写的describeLogExport

2022-09-23 01:20 UTC, xiaozhu36 requested changes

2022-09-23 01:20 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_oss_export.go
> +		for _, f := range d.Get("config_columns").(*schema.Set).List() {
对于选填的属性，都需要通过 d.GetOk 来获取值，否则在进行类型转换的时候就会遇到空指针异常

2022-09-23 15:07 UTC, panawala commented on alicloud/resource_alicloud_log_oss_export.go
> +		for _, f := range d.Get("config_columns").(*schema.Set).List() {
done

2022-09-26 03:23 UTC, merged