New Resource `alicloud_message_service_queue`; New Datasource `alicloud_message_service_queues`
aliyun/terraform-provider-alicloud pull request #5444
Opened 2022-09-20 08:18 UTC by MrWolong

2022-09-21 02:12 UTC, MrWolong commented on alicloud/resource_alicloud_message_service_queue_test.go
> +	p := Provider().(*schema.Provider).ResourcesMap
单测覆盖率98.3%

2022-09-21 02:59 UTC, xinmu0426 commented on alicloud/resource_alicloud_message_service_queue.go
> +			"name": {
这个name有限制么，而且我看资源定义上为QueueName啊

2022-09-21 03:00 UTC, xinmu0426 commented on alicloud/resource_alicloud_message_service_queue.go
> +			"name": {
另外一定要以云产品资源定义为准，不要照搬之前的

2022-09-21 03:01 UTC, xinmu0426 commented on alicloud/resource_alicloud_message_service_queue.go
> +			"enable_logging": {
资源定义上不叫这个吧，

2022-09-21 07:30 UTC, MrWolong commented on alicloud/resource_alicloud_message_service_queue.go
> +			"enable_logging": {
已修复

2022-09-28 02:24 UTC, xiaozhu36 requested changes

2022-09-28 02:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_message_service_queue.go
> +		request["EnableLogging"] = v
API上的参数就叫做 LoggingEnabled啊：https://help.aliyun.com/document_detail/35129.html

2022-09-28 03:30 UTC, MrWolong commented on alicloud/resource_alicloud_message_service_queue.go
> +		request["EnableLogging"] = v
mns为了对接tf，设计了一套针对tf的api，在针对tf的api里面，应该为EnableLogging
![image](https://user-images.githubusercontent.com/36806235/192681109-fab92300-eda0-4cc0-b127-80707e78256a.png)

2022-09-29 06:58 UTC, xiaozhu36 requested changes

2022-09-29 06:58 UTC, xiaozhu36 commented on alicloud/resource_alicloud_message_service_queue.go
> +		request["EnableLogging"] = v
如果是这样，那就是他们提供的文档有问题，API文档上也应该是 EnableLogging，这个先跟云产品确认清楚

2022-09-29 08:09 UTC, MrWolong commented on alicloud/resource_alicloud_message_service_queue.go
> +		request["EnableLogging"] = v
师兄，最新的文档里面已经标注，如果是tf使用本接口，应将LoggingEnabled替换为EnableLogging
![image](https://user-images.githubusercontent.com/36806235/192976566-01f01f25-263e-4cc0-98ac-012d5d00db03.png)

2022-09-30 07:07 UTC, merged