resource/alicloud_resource_manager_account: Added the field `abandon_able_check_ids`; Supported for new action `DeleteAccount`
aliyun/terraform-provider-alicloud pull request #5454
Opened 2022-09-25 13:24 UTC by MrWolong

2022-09-28 02:15 UTC, xiaozhu36 requested changes

2022-09-28 02:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_resource_manager_account.go
> +			"abandon_able_check_ids": {
这个字段跟 API中的怎么不一致

2022-09-28 02:15 UTC, xiaozhu36 commented on website/docs/r/resource_manager_account.html.markdown
> +* `abandon_able_check_ids` - (Optional, ForceNew, Available in v1.187.0+) The IDs of the check items that you can choose to ignore for the member deletion. You can obtain the IDs from the datasource
datasource呢

2022-09-28 03:40 UTC, MrWolong commented on website/docs/r/resource_manager_account.html.markdown
> +* `abandon_able_check_ids` - (Optional, ForceNew, Available in v1.187.0+) The IDs of the check items that you can choose to ignore for the member deletion. You can obtain the IDs from the datasource
这个为了规范，分成两个pr写了，一个是加data source：另一个是加字段，和action

2022-09-28 03:42 UTC, MrWolong commented on alicloud/resource_alicloud_resource_manager_account.go
> +			"abandon_able_check_ids": {
写成ids的原因是由于，api文档中虽然是id，但是类型是list类型，如果字段也改成id，用户在使用的时候，可能会产生歧义，直接给这个字段传字符串；ids可以尽可能的避免歧义。

2022-09-29 02:04 UTC, xiaozhu36 requested changes

2022-09-29 02:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_resource_manager_account.go
> +			"abandon_able_check_ids": {
意思是可以传多个check id 值么？

如果是list，那么传入参数的时候是不是得有循环逻辑

2022-09-29 06:33 UTC, MrWolong commented on alicloud/resource_alicloud_resource_manager_account.go
> +			"abandon_able_check_ids": {
![image](https://user-images.githubusercontent.com/36806235/192929368-6e46aa7b-7478-4c0d-9641-0d09b8c2d0f9.png)
师兄，他这个接口设计的属性就是个字符串数组链表啊

2022-09-29 06:57 UTC, xiaozhu36 requested changes

2022-09-29 06:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_resource_manager_account.go
> +			"abandon_able_check_ids": {
这个命名还是跟 API 的参数保持一致吧，改成 abandon_able_check_id

2022-09-29 08:19 UTC, MrWolong commented on alicloud/resource_alicloud_resource_manager_account.go
> +			"abandon_able_check_ids": {
已修复

2022-09-30 06:58 UTC, merged