New Resource `alicloud_api_gateway_plugin`; New Datasource `alicloud_api_gateway_plugins`;
aliyun/terraform-provider-alicloud pull request #5471
Opened 2022-09-27 08:31 UTC by super-eggs

New Resource `alicloud_api_gateway_plugin`;
New Datasource `alicloud_api_gateway_plugins`;

2022-09-27 09:57 UTC, xinmu0426 commented on alicloud/data_source_alicloud_api_gateway_plugins.go
> +			"tag": {
这个重复了，以及换成TypeMap

2022-09-27 09:57 UTC, xinmu0426 commented on alicloud/data_source_alicloud_api_gateway_plugins.go
> +				Default:      "",
Default去掉

2022-09-27 09:57 UTC, xinmu0426 commented on alicloud/data_source_alicloud_api_gateway_plugins.go
> +	if v, ok := d.GetOk("tag"); ok {
这个也看下吧

2022-09-27 09:57 UTC, xinmu0426 commented on alicloud/resource_alicloud_api_gateway_plugin.go
> +	if v, ok := object["Tags"].(map[string]interface{}); ok {
这快先判断下吧，防止panic

2022-09-27 09:57 UTC, xinmu0426 commented on alicloud/resource_alicloud_api_gateway_plugin.go
> +	return resourceAlicloudApiGatewayPluginUpdate(d, meta)
这个是不是改read了

2022-09-27 09:57 UTC, xinmu0426 commented on alicloud/resource_alicloud_api_gateway_plugin.go
> +	if !d.IsNewResource() && d.HasChange("description") {
d.IsNewResource()这些应该都没了

2022-09-27 09:57 UTC, xinmu0426 commented on alicloud/resource_alicloud_api_gateway_plugin.go
> +		err = resource.Retry(d.Timeout(schema.TimeoutUpdate), func() *resource.RetryError {
加上 client.GetRetryTimeout

2022-09-29 03:00 UTC, xiaozhu36 requested changes

2022-09-29 03:08 UTC, super-eggs commented on website/alicloud.erb
> +                  <a href="#">Api Gateway</a>
这是是自动生成的。之前的名称（API Gateway）应该不对，已调整为：Api Gateway

2022-09-29 09:10 UTC, merged