resource/alicloud_gpdb_instance: Refactoring resources.
aliyun/terraform-provider-alicloud pull request #5474
Opened 2022-09-27 10:18 UTC by thisnihonglei

2022-09-28 09:19 UTC, super-eggs commented on alicloud/resource_alicloud_gpdb_instance.go
> +	err = resource.Retry(d.Timeout(schema.TimeoutCreate), func() *resource.RetryError {
client.GetRetryTimeout

2022-09-28 09:19 UTC, super-eggs commented on alicloud/resource_alicloud_gpdb_instance.go
> +		err = resource.Retry(d.Timeout(schema.TimeoutUpdate), func() *resource.RetryError {
client.GetRetryTimeout

2022-09-28 09:19 UTC, super-eggs commented on alicloud/resource_alicloud_gpdb_instance.go
> +		err = resource.Retry(d.Timeout(schema.TimeoutUpdate), func() *resource.RetryError {
client.GetRetryTimeout

2022-09-28 09:19 UTC, super-eggs commented on alicloud/resource_alicloud_gpdb_instance.go
> +		err = resource.Retry(d.Timeout(schema.TimeoutUpdate), func() *resource.RetryError {
client.GetRetryTimeout

2022-09-28 09:19 UTC, super-eggs commented on alicloud/resource_alicloud_gpdb_instance.go
> +		err = resource.Retry(d.Timeout(schema.TimeoutUpdate), func() *resource.RetryError {
client.GetRetryTimeout

2022-09-28 09:19 UTC, super-eggs commented on alicloud/resource_alicloud_gpdb_instance.go
> +		err = resource.Retry(d.Timeout(schema.TimeoutUpdate), func() *resource.RetryError {
client.GetRetryTimeout

2022-09-28 09:19 UTC, super-eggs commented on alicloud/resource_alicloud_gpdb_instance.go
> +	err = resource.Retry(d.Timeout(schema.TimeoutDelete), func() *resource.RetryError {
client.GetRetryTimeout

2022-09-28 09:19 UTC, super-eggs commented on alicloud/resource_alicloud_gpdb_instance.go
> +		stateConf := BuildStateConf([]string{}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 5*time.Second, gpdbService.GpdbDbInstanceStateRefreshFunc(d.Id(), []string{}))
DeleteDBInstance，其他同理

2022-09-28 09:19 UTC, super-eggs commented on website/docs/d/gpdb_instances.html.markdown
> +* `status` - (Optional) The status of the instance.
枚举值

2022-09-28 09:19 UTC, super-eggs commented on alicloud/resource_alicloud_gpdb_instance.go
> +				Deprecated:    "Field 'availability_zone' has been deprecated from version 1.187.0. Use 'payment_type' instead.",
instance_charge_type

2022-09-28 09:19 UTC, super-eggs commented on website/docs/r/gpdb_instance.html.markdown
> +* `availability_zone` - (Optional, ForceNew) Field `availability_zone` has been deprecated from provider version 1.187.0. New field `zone_id` instead.
Deprecated

2022-09-28 09:19 UTC, super-eggs commented on website/docs/r/gpdb_instance.html.markdown
> +* `instance_charge_type` - (Optional, ForceNew) Field `instance_charge_type` has been deprecated from provider version 1.187.0. New field `payment_type` instead.
Deprecated

2022-09-28 09:19 UTC, super-eggs commented on alicloud/resource_alicloud_gpdb_instance_test.go
> +				ImportStateVerifyIgnore: []string{"period", "used_time", "pay_type", "seg_storage_type", "private_ip_address", "instance_spec", "db_instance_class", "resource_group_id", "create_sample_data"},
pay_type？

2022-09-28 09:19 UTC, super-eggs commented on alicloud/data_source_alicloud_gpdb_instances.go
> +	request["PageSize"] = PageSizeLarge
setPagingRequest

2022-09-28 09:24 UTC, thisnihonglei commented on alicloud/resource_alicloud_gpdb_instance.go
> +		err = resource.Retry(d.Timeout(schema.TimeoutUpdate), func() *resource.RetryError {
done

2022-09-28 09:24 UTC, thisnihonglei commented on alicloud/resource_alicloud_gpdb_instance.go
> +		err = resource.Retry(d.Timeout(schema.TimeoutUpdate), func() *resource.RetryError {
done

2022-09-28 09:24 UTC, thisnihonglei commented on alicloud/resource_alicloud_gpdb_instance.go
> +		err = resource.Retry(d.Timeout(schema.TimeoutUpdate), func() *resource.RetryError {
done

2022-09-28 09:24 UTC, thisnihonglei commented on alicloud/resource_alicloud_gpdb_instance.go
> +		err = resource.Retry(d.Timeout(schema.TimeoutUpdate), func() *resource.RetryError {
done

2022-09-28 09:24 UTC, thisnihonglei commented on alicloud/resource_alicloud_gpdb_instance.go
> +	err = resource.Retry(d.Timeout(schema.TimeoutDelete), func() *resource.RetryError {
done

2022-09-28 09:26 UTC, thisnihonglei commented on alicloud/resource_alicloud_gpdb_instance.go
> +		stateConf := BuildStateConf([]string{}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 5*time.Second, gpdbService.GpdbDbInstanceStateRefreshFunc(d.Id(), []string{}))
done

2022-09-28 09:28 UTC, thisnihonglei commented on alicloud/resource_alicloud_gpdb_instance.go
> +				Deprecated:    "Field 'availability_zone' has been deprecated from version 1.187.0. Use 'payment_type' instead.",
done

2022-09-28 09:29 UTC, thisnihonglei commented on website/docs/r/gpdb_instance.html.markdown
> +* `availability_zone` - (Optional, ForceNew) Field `availability_zone` has been deprecated from provider version 1.187.0. New field `zone_id` instead.
done

2022-09-28 09:29 UTC, thisnihonglei commented on website/docs/r/gpdb_instance.html.markdown
> +* `instance_charge_type` - (Optional, ForceNew) Field `instance_charge_type` has been deprecated from provider version 1.187.0. New field `payment_type` instead.
done

2022-09-28 09:30 UTC, thisnihonglei commented on alicloud/resource_alicloud_gpdb_instance_test.go
> +				ImportStateVerifyIgnore: []string{"period", "used_time", "pay_type", "seg_storage_type", "private_ip_address", "instance_spec", "db_instance_class", "resource_group_id", "create_sample_data"},
done

2022-09-28 09:31 UTC, thisnihonglei commented on alicloud/data_source_alicloud_gpdb_instances.go
> +	request["PageSize"] = PageSizeLarge
done

2022-09-29 02:54 UTC, xiaozhu36 requested changes

2022-09-29 02:54 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_gpdb_instances.go
> +						"create_time": {
之前是 creation_time，现在改成 create_time了，这个属于非兼容变更，这个要保持兼容

2022-09-29 02:54 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_gpdb_instances.go
> +						"create_time": {
其他也类似

2022-09-29 02:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_instance.go
> -			Delete: schema.DefaultTimeout(10 * time.Minute),
delete为啥删除了

2022-09-29 02:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_instance.go
> +				Default:      "VPC",
默认值现在不要了吧，如果存在也应该是 Computed的

2022-09-29 02:54 UTC, xiaozhu36 commented on website/docs/d/gpdb_instances.html.markdown
> +Provides a collection of AnalyticDB for PostgreSQL instances according to the specified filters.
两个空格

2022-09-29 03:32 UTC, thisnihonglei commented on alicloud/data_source_alicloud_gpdb_instances.go
> +						"create_time": {
其他属性已兼容，instance_group_count去掉了，API不返回该参数

2022-09-29 06:39 UTC, merged