New Resource `alicloud_bp_studio_application`; New Datasource `alicloud_bp_studio_applications`
aliyun/terraform-provider-alicloud pull request #5475
Opened 2022-09-27 10:38 UTC by MrWolong

2022-10-10 03:05 UTC, MrWolong commented on website/alicloud.erb
> -                            <a href="/docs/providers/alicloud/r/vpc_nat_ip.html">alicloud_vpc_nat_ip</a>
删除这个的原因是，vpc_nat_ip不应该出现在Video Surveillance System下面，应该在vpc下面，由于这个格式有问题，所以在官网文档上面不显示。

2022-10-10 03:17 UTC, xinmu0426 commented on alicloud/data_source_alicloud_bp_studio_applications.go
> +				ForceNew: true,
这个有没有取值范围

2022-10-10 03:17 UTC, xinmu0426 commented on alicloud/data_source_alicloud_bp_studio_applications.go
> +				Type:     schema.TypeInt,
next_token 为啥是int

2022-10-10 03:17 UTC, xinmu0426 commented on alicloud/data_source_alicloud_bp_studio_applications.go
> +		request["NextToken"] = request["NextToken"].(int) + 1
NextToken不应是上次请求的返回么

2022-10-10 03:17 UTC, xinmu0426 commented on alicloud/provider.go
> -			"alicloud_api_gateway_plugin":                                   resourceAlicloudApiGatewayPlugin(),
这个合并有问题

2022-10-10 03:17 UTC, xinmu0426 commented on website/alicloud.erb
> +                  <a href="#">BP Studio</a>
改为
Cloud Architect Design Tools

2022-10-10 03:17 UTC, xinmu0426 commented on website/docs/d/bp_studio_applications.html.markdown
> +subcategory: "BP Studio"
改为
Cloud Architect Design Tools

2022-10-10 03:17 UTC, xinmu0426 commented on website/docs/r/bp_studio_application.html.markdown
> +subcategory: "BP Studio"
改为
Cloud Architect Design Tools

2022-10-10 03:17 UTC, xinmu0426 commented on website/docs/r/bp_studio_application.html.markdown
> +
timeout呢

2022-11-14 07:11 UTC, xiaozhu36 requested changes

2022-11-14 07:11 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_bp_studio_applications_test.go
> +  		resource_group_id   = data.alicloud_resource_manager_resource_groups.default.groups.0.id
上面的这个没改啊

2022-11-14 07:11 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_bp_studio_applications_test.go
> +		area_id = "cn-hangzhou"
region也别写死了

2022-11-14 07:23 UTC, MrWolong commented on alicloud/resource_alicloud_bp_studio_application.go
> +				Elem: &schema.Schema{
已修改

2022-11-14 07:24 UTC, MrWolong commented on alicloud/data_source_alicloud_bp_studio_applications_test.go
> +  		resource_group_id   = data.alicloud_resource_manager_resource_groups.default.groups.0.id
这个资源的template_id指的是模板id，模板id通过在控制台上面手动画模板获取，无法通过api创建，这个id是云速搭的同学提供的。

2022-11-14 07:24 UTC, MrWolong commented on alicloud/data_source_alicloud_bp_studio_applications_test.go
> +		area_id = "cn-hangzhou"
已修改

2022-11-15 03:40 UTC, merged