test
aliyun/terraform-provider-alicloud pull request #5485
Opened 2022-09-29 06:57 UTC by fuliu-zln

2022-09-29 07:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=5485) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=5485) before we can accept your contribution.<br/><hr/>**wb-zln530580** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=5485) it.</sub>

2022-09-29 09:16 UTC, xiaozhu36 requested changes

2022-09-29 10:37 UTC, fuliu-zln commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	}
只是做个变量声明，不过我已经改正了，换了种方式，麻烦再看下

2022-09-29 10:49 UTC, xiaozhu36 requested changes

2022-09-29 10:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	err = resource.Retry(5*time.Minute, func() *resource.RetryError {
这个地方直接使用 err:= 就行啊

2022-09-30 01:40 UTC, fuliu-zln commented on alicloud/resource_alicloud_ess_alb_server_group_attachment.go
> +	err = resource.Retry(5*time.Minute, func() *resource.RetryError {
不行的，resource.Retry(5*time.Minute, func() *resource.RetryError内的err 变量会报错。这个我尝试过

2022-09-30 02:09 UTC, merged