New Resource `alicloud_gpdb_db_instance_plan`; New Datasource `alicloud_gpdb_db_instance_plans`;
aliyun/terraform-provider-alicloud pull request #5509
Opened 2022-10-11 07:45 UTC by super-eggs

New Resource `alicloud_gpdb_db_instance_plan`;
New Datasource `alicloud_gpdb_db_instance_plans`;

2022-10-17 09:52 UTC, MrWolong commented on website/docs/d/gpdb_db_instance_plans.html.markdown
> +-> **NOTE:** Available in v1.188.0+.
应该是-> **NOTE:** Available in v1.189.0+.

2022-10-17 09:53 UTC, MrWolong commented on website/docs/d/gpdb_db_instance_plans.html.markdown
> +  value = data.alicloud_gpdb_db_instance_plans.nameRegex.plans.0.id
这个id没有在plans里面透出啊

2022-10-17 09:58 UTC, MrWolong commented on website/docs/d/gpdb_instances.html.markdown
>  * `resource_group_id` - (Optional) The ID of the enterprise resource group to which the instance belongs.
我看了一下，ci没过的原因是拼写错误，之所以拼写错误是由于云产品的文档里面就是错的。
https://www.alibabacloud.com/help/zh/analyticdb-for-postgresql/latest/instance-statuses
![image](https://user-images.githubusercontent.com/36806235/196148316-abd5b83f-25bd-4be5-ac7d-fc4100589291.png)

2022-10-17 10:00 UTC, MrWolong commented on website/docs/r/gpdb_db_instance_plan.html.markdown
> +* `create` - (Defaults to 1 mins) Used when create the DB Instance Plan.
这个是不是应该在代码里面体现出来啊，我看代码里面这块没有写时间
![image](https://user-images.githubusercontent.com/36806235/196149382-8232bff0-c627-4e86-ab56-c1f4aaba5136.png)

2022-10-17 10:02 UTC, MrWolong commented on alicloud/data_source_alicloud_gpdb_db_instance_plans.go
> +						"db_instance_plan_name": {
缺少一个id字段

2022-10-17 10:02 UTC, MrWolong commented on alicloud/data_source_alicloud_gpdb_db_instance_plans.go
> +					Schema: map[string]*schema.Schema{
缺少一个id字段

2022-10-17 10:05 UTC, MrWolong commented on website/docs/r/gpdb_db_instance_plan.html.markdown
> +-> **NOTE:** Available in v1.188.0+.
应该是-> NOTE: Available in v1.189.0+.
![image](https://user-images.githubusercontent.com/36806235/196150303-4bad96d3-3c30-4cf1-a92e-8bb8146e2976.png)

2022-10-19 08:21 UTC, xiaozhu36 requested changes

2022-10-19 08:21 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_db_instance_plan.go
> +	d.SetId(fmt.Sprint(response["PlanId"], ":", request["DBInstanceId"]))
这个ID应该是 InstanceId：PlanId，因为plan是instance的子资源，这个还是要从spec 上修改过来

2022-10-19 08:21 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_db_instance_plan.go
> +	d.Set("db_instance_plan_id", parts[0])
为啥叫 db_instance_plan_id 而不是 plan_id

2022-10-19 08:23 UTC, MrWolong commented on alicloud/data_source_alicloud_gpdb_db_instance_plans.go
> +			},
这个api还有几个入参没有在字段上体现PlanId，PlanCreateDate，PlanDesc
https://help.aliyun.com/document_detail/449398.html
![image](https://user-images.githubusercontent.com/36806235/196315550-c2f16f59-f3d0-4a2f-a38c-cc890f84a294.png)

2022-10-20 09:01 UTC, super-eggs commented on alicloud/resource_alicloud_gpdb_db_instance_plan.go
> +	d.Set("db_instance_plan_id", parts[0])
因为资源名称叫做 db_instance_plan，采用的【资源名称+id】的定义主键名称的命名规则。

2022-10-20 09:06 UTC, xiaozhu36 requested changes

2022-10-20 09:06 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_gpdb_db_instance_plans.go
> +			"id":                    fmt.Sprint(object["PlanId"], ":", request["DBInstanceId"]),
这个ID为啥还是plan ID在前

2022-10-21 01:31 UTC, xiaozhu36 requested changes

2022-10-21 01:31 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_db_instance_plan.go
> +			"db_instance_plan_id": {
这个为啥定义为 db_instance_plan_id，而不是 plan_id，我看API上都是 PlanId

2022-10-21 08:28 UTC, xiaozhu36 requested changes

2022-10-21 08:28 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_gpdb_db_instance_plans.go
> +			"db_instance_plan_name": object["PlanName"],
这个db_instance_plan_name 也改成 plan_name 吧

2022-10-21 08:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_gpdb_db_instance_plan_test.go
> +					"plan_start_date": "2022-10-16T00:00:00Z",
这个时间写死是不是不行，不会出现过期的情况么？
建议用 time.Now 来代替，后面的plan_end_date 可以是 time.Now + xxx hour

2022-10-21 09:14 UTC, super-eggs commented on alicloud/data_source_alicloud_gpdb_db_instance_plans.go
> +			"db_instance_plan_name": object["PlanName"],
generator中，判断 datasource 是否支持 name_regex 查询，取决于资源是否存在 name，判断资源是否存在 name 用的【资源名称+name】 匹配属性名称的方式。

2022-10-21 09:32 UTC, merged