New Resource `alicloud_service_mesh_extension_provider`; New Datasource `alicloud_service_mesh_extension_providers`
aliyun/terraform-provider-alicloud pull request #5560
Opened 2022-11-01 10:57 UTC by MrWolong

2022-11-03 02:49 UTC, MrWolong commented on website/alicloud.erb
> +                          <li>
在d文件夹里，发现有这个文件，但是没有在erb文件里面

2022-11-03 05:51 UTC, MrWolong commented on alicloud/resource_alicloud_service_mesh_service_mesh.go
>  				Type:     schema.TypeString,
service_mesh_name是有默认值的

2022-11-03 05:52 UTC, MrWolong commented on alicloud/resource_alicloud_service_mesh_service_mesh.go
> +		removed := oraw.([]interface{})
cluster_ids是list类型，之前的写法会报panic

2022-11-03 05:52 UTC, MrWolong commented on alicloud/resource_alicloud_service_mesh_service_mesh_test.go
>  func TestAccAlicloudServiceMeshServiceMesh_basic1(t *testing.T) {
由于权限原因，这个测试用例会失败
![image](https://user-images.githubusercontent.com/36806235/199655563-dd2e6e83-37ff-471b-8ce4-b8ae63ce8985.png)

2022-11-04 03:20 UTC, super-eggs commented on alicloud/resource_alicloud_service_mesh_service_mesh_test.go
>  func TestAccAlicloudServiceMeshServiceMesh_basic1(t *testing.T) {
那就跳过这个测试吧

2022-11-04 10:26 UTC, MrWolong commented on alicloud/resource_alicloud_service_mesh_service_mesh_test.go
>  func TestAccAlicloudServiceMeshServiceMesh_basic1(t *testing.T) {
已修改

2022-11-05 01:10 UTC, xiaozhu36 requested changes

2022-11-05 01:10 UTC, xiaozhu36 commented on website/docs/r/service_mesh_service_mesh.html.markdown
Import 部分要加上 shell 标识

2022-11-07 03:37 UTC, MrWolong commented on website/docs/r/service_mesh_service_mesh.html.markdown
已修改

2022-11-08 02:34 UTC, merged