resource/alicloud_vswitch: Added retry strategy for error code `CreateVSwitch.IncorrectStatus.cbnStatus`
aliyun/terraform-provider-alicloud pull request #5566
Opened 2022-11-04 06:34 UTC by MrWolong

2022-11-04 10:00 UTC, super-eggs commented on alicloud/resource_alicloud_vswitch.go
> +				Required:      true,
这里就和旧版本不兼容了吧

2022-11-04 10:03 UTC, MrWolong commented on alicloud/resource_alicloud_vswitch.go
> +				Required:      true,
主要我看api文档里面是必选的，其次这个tf文档里面标注的也是Required，但是代码里定义的是Optional
![image](https://user-images.githubusercontent.com/36806235/199946266-a996f8f5-0f0c-4916-8991-7ff56d041656.png)
![image](https://user-images.githubusercontent.com/36806235/199946337-45f303af-64e5-4ad3-a84b-62ee0fa3d24d.png)

2022-11-05 01:13 UTC, xiaozhu36 requested changes

2022-11-05 01:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vswitch.go
> +			if IsExpectedErrors(err, []string{"InvalidCidrBlock.Overlapped", "InvalidStatus.RouteEntry", "OperationFailed.IdempotentTokenProcessing", "TaskConflict", "Throttling", "UnknownError", "CreateVSwit
Throttling 的错误应该用 NeedRetry 来代替

2022-11-07 07:15 UTC, MrWolong commented on website/docs/r/vswitch.html.markdown
> -* `availability_zone` - (Required, ForceNew, Deprecated in v1.119.0+) Field `availability_zone` has been deprecated from provider version 1.119.0. New field `zone_id` instead.
修改这个是为了修复ci的字段校验报错，已在字段`zone_id`加上必填说明

2022-11-07 11:19 UTC, merged