resource/alicloud_vpc_prefix_list: Added retry stragety for error code `SystemBusy`, `OperationConflict`, `LastTokenProcessing`, `IncorrectStatus.PrefixList`, `IncorrectStatus.%s`
aliyun/terraform-provider-alicloud pull request #5579
Opened 2022-11-11 06:14 UTC by MrWolong

2022-11-14 14:07 UTC, xiaozhu36 requested changes

2022-11-14 14:07 UTC, xiaozhu36 commented on alicloud/errors.go
> -	throttlingRegex := regexp.MustCompile("^Throttling.*")
这个为啥要改

2022-11-14 14:07 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_prefix_list.go
> +				if IsExpectedErrors(err, []string{"IncorrectStatus.PrefixList", "SystemBusy", "LastTokenProcessing", "IncorrectStatus.%s"}) || NeedRetry(err) {
%s  是啥意思

2022-11-15 02:05 UTC, MrWolong commented on alicloud/errors.go
> -	throttlingRegex := regexp.MustCompile("^Throttling.*")
这次加的重试错误码中，有XXXXX.Throttling这种格式的错误码，而^Throttling.，是匹配不到的，只能匹配到以Throttling.开头的错误码

2022-11-15 03:43 UTC, merged