New Resource `alicloud_log_project_policy`
aliyun/terraform-provider-alicloud pull request #5583
Opened 2022-11-13 07:07 UTC by panawala

New Resource `alicloud_log_project_policy` to set policy for SLS project

2022-11-13 07:22 UTC, panawala commented
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLogProjectPolicy_basic -timeout=300m
=== RUN   TestAccAlicloudLogProjectPolicy_basic
--- PASS: TestAccAlicloudLogProjectPolicy_basic (24.27s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  24.363s

2022-11-15 06:24 UTC, xiaozhu36 requested changes

2022-11-15 06:24 UTC, xiaozhu36 commented on website/docs/r/log_project_policy.html.markdown
> +```
这个地方要加上 shell 的标识

2022-11-15 06:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_project_policy.go
> +			return nil, slsClient.UpdateProjectPolicy(projectName, policy)
为啥要先删除，再更新

2022-11-16 06:10 UTC, panawala commented on website/docs/r/log_project_policy.html.markdown
> +```
done

2022-11-16 06:11 UTC, panawala commented on alicloud/resource_alicloud_log_project_policy.go
> +			return nil, slsClient.UpdateProjectPolicy(projectName, policy)
这里policy为空，就是直接删除了；
不为空时，更新Project policy，一个project对应一个policy

2023-03-23 09:54 UTC, closed without merging