resource/alicloud_cen_transit_router_vpc_attachment: Removed the field `route_table_association_enabled` and `route_table_propagation_enabled`
aliyun/terraform-provider-alicloud pull request #5588
Opened 2022-11-14 09:33 UTC by MrWolong

2022-11-14 09:36 UTC, MrWolong commented on alicloud/resource_alicloud_cen_transit_router_vpc_attachment.go
>  			"route_table_association_enabled": {
废弃原因：
1、这个两个字段开启之后，会与其他资源形成关联，引起TF生命周期不完整，执行销毁操作的时候，会销毁失败，报有资源依赖
2、咨询了云产品的同学，这两个字段由于会引起TF生命周期不完整，所以在AMP上面定义该资源时，没有将这个两个字段定义在里面

2022-11-14 14:10 UTC, xiaozhu36 requested changes

2022-11-15 01:50 UTC, MrWolong commented on alicloud/resource_alicloud_cen_transit_router_vpc_attachment.go
>  			"route_table_association_enabled": {
本质上，当`route_table_association_enabled`，`route_table_propagation_enabled`为`true`的时候，会自动关联创建alicloud_cen_transit_router_route_table_association，alicloud_cen_transit_router_route_table_propagation这两个资源。所以，我们可以通过alicloud_cen_transit_router_route_table_association，alicloud_cen_transit_router_route_table_propagation这两个资源来实现关联，以确保TF的生命周期完整，销毁成功。alicloud_cen_transit_router_route_table_association和alicloud_cen_transit_router_route_table_propagation都已经接入TF。[alicloud_cen_transit_router_route_table_association](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cen_transit_router_route_table_association)

2022-11-15 03:45 UTC, xiaozhu36 requested changes

2022-11-15 03:45 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cen_transit_router_vpc_attachment.go
>  			"route_table_association_enabled": {
ok, 那在 Deprecated 的信息和对应的文档上把这个指导信息写下吧

2022-11-15 04:32 UTC, MrWolong commented on alicloud/resource_alicloud_cen_transit_router_vpc_attachment.go
>  			"route_table_association_enabled": {
已修复

2022-11-15 06:22 UTC, merged