New Resource RDS MySQL DBProxy
aliyun/terraform-provider-alicloud pull request #5596
Opened 2022-11-16 01:44 UTC by zcc01029273

2022-11-16 02:59 UTC, super-eggs commented on website/docs/r/db_proxy.html.markdown
> +-> **NOTE:** Available in v1.192.0+.
1.193.0

2022-11-16 02:59 UTC, super-eggs commented on website/docs/r/db_proxy.html.markdown
> +## Import
### Timeouts

2022-11-16 02:59 UTC, super-eggs commented on alicloud/service_alicloud_rds.go
> +	for {
死循环

2022-11-16 03:02 UTC, super-eggs commented on alicloud/resource_alicloud_db_proxy.go
> +	if err := resource.Retry(60*time.Minute, func() *resource.RetryError {
client.GetRetryTimeout(d.Timeout(schema.TimeoutCreate)

2022-11-16 06:44 UTC, super-eggs commented on alicloud/service_alicloud_rds.go
> +		return nil, nil
return object, WrapErrorf(Error(GetNotFoundMessage("RDS", id)), NotFoundWithResponse, response)

2022-11-16 06:44 UTC, super-eggs commented on alicloud/service_alicloud_rds.go
> +func (s *RdsService) WaitForDBProxy(id string, status Status, timeout int) error {
看下 RdsAccountStateRefreshFunc 的写法吧，推荐统一格式写法

2022-11-16 06:44 UTC, super-eggs commented on alicloud/resource_alicloud_db_proxy.go
> +			"vpc_id": {
必填的情况下，为啥还是 Computed？

2022-11-16 06:44 UTC, super-eggs commented on alicloud/resource_alicloud_db_proxy.go
> +			"instance_network_type": {
instance_network_type 不可修改吧？ 应该为 ForceNew: true。
顺便检查一下其他属性的是否可修改情况。

2022-11-16 06:44 UTC, super-eggs commented on alicloud/resource_alicloud_db_proxy.go
> +	d.Set("vpc_id", request["VPCId"])
为这里为啥要 set vpc_id 和 vswitch_id？

2022-11-16 09:05 UTC, zcc01029273 commented on alicloud/service_alicloud_rds.go
> +		return nil, nil
done

2022-11-16 09:05 UTC, zcc01029273 commented on alicloud/service_alicloud_rds.go
> +func (s *RdsService) WaitForDBProxy(id string, status Status, timeout int) error {
接口特殊，所以这么处理了下

2022-11-16 09:05 UTC, zcc01029273 commented on website/docs/r/db_proxy.html.markdown
> +-> **NOTE:** Available in v1.192.0+.
done

2022-11-16 09:05 UTC, zcc01029273 commented on website/docs/r/db_proxy.html.markdown
> +## Import
done

2022-11-16 09:05 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +	if err := resource.Retry(60*time.Minute, func() *resource.RetryError {
done

2022-11-16 09:05 UTC, zcc01029273 commented on alicloud/service_alicloud_rds.go
> +	for {
done

2022-11-16 09:05 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +			"vpc_id": {
done

2022-11-16 09:06 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +			"instance_network_type": {
done

2022-11-16 09:06 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +	d.Set("vpc_id", request["VPCId"])
done

2022-11-16 09:29 UTC, super-eggs commented on alicloud/resource_alicloud_db_proxy.go
> +
Timeouts: &schema.ResourceTimeout{

2022-11-16 09:29 UTC, super-eggs commented on alicloud/resource_alicloud_db_proxy.go
> +	d.Set("endpoint_id", proxy["DBProxyInstanceName"])
为什么放到 Update 中，应该在 Read 中吧

2022-11-16 09:29 UTC, super-eggs commented on alicloud/resource_alicloud_db_proxy.go
> +	if err := resource.Retry(30*time.Minute, func() *resource.RetryError {
client.GetRetryTimeout(d.Timeout(schema.TimeoutDelete)

2022-11-16 09:29 UTC, super-eggs commented on alicloud/resource_alicloud_db_proxy.go
> +		if err := resource.Retry(30*time.Minute, func() *resource.RetryError {
client.GetRetryTimeout(d.Timeout(schema.TimeoutUpdate)

2022-11-16 09:29 UTC, super-eggs commented on alicloud/resource_alicloud_db_proxy.go
> +			if err := resource.Retry(30*time.Minute, func() *resource.RetryError {
client.GetRetryTimeout(d.Timeout(schema.TimeoutUpdate)

2022-11-16 09:40 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +	d.Set("endpoint_id", proxy["DBProxyInstanceName"])
修改时需要创建产生的数据

2022-11-16 09:40 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +		if err := resource.Retry(30*time.Minute, func() *resource.RetryError {
done

2022-11-16 09:40 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +	if err := resource.Retry(30*time.Minute, func() *resource.RetryError {
done

2022-11-16 09:40 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +
done

2022-11-16 09:42 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +		if err := resource.Retry(30*time.Minute, func() *resource.RetryError {
done

2022-11-16 09:42 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +		if err := resource.Retry(30*time.Minute, func() *resource.RetryError {
done

2022-11-16 09:42 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +		if err := resource.Retry(30*time.Minute, func() *resource.RetryError {
done

2022-11-16 10:05 UTC, super-eggs commented on alicloud/resource_alicloud_db_proxy_test.go
> +				Config: testAccConfig(map[string]interface{}{
这里的测试没有覆盖每个可修改的参数吧？

2022-11-16 10:47 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy_test.go
> +				Config: testAccConfig(map[string]interface{}{
已覆盖

2022-11-16 12:39 UTC, xiaozhu36 requested changes

2022-11-16 12:39 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_proxy.go
> +	d.Set("endpoint_id", proxy["DBProxyInstanceName"])
如果修改时需要创建的数据，那么直接使用查询到的数据proxy["DBProxyInstanceName"]即可，不需要d.set

2022-11-16 13:31 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +	action := "ModifyDBProxy"
开启实际就是创建，关闭实际就是删除，原先的共享代理也是作为一个单独的资源存在的，一个开启、关闭（创建、删除），几个修改接口，几个查询接口

2022-11-16 13:51 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +	action := "ModifyDBProxy"
还有一个这个基本上得在只读实例完成后才执行

2022-11-16 16:02 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +	d.Set("endpoint_id", proxy["DBProxyInstanceName"])
done

2022-11-16 16:02 UTC, zcc01029273 commented on alicloud/provider.go
> +			"alicloud_db_proxy":                           resourceAlicloudDBProxy(),
done

2022-11-16 16:02 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +				ForceNew: true,
done

2022-11-16 16:02 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +	if err := rdsService.WaitForDBProxy(request["DBInstanceId"].(string), Running, 60*60*10); err != nil {
done

2022-11-16 16:04 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_proxy.go
> +	action := "ModifyDBProxy"
启实际就是创建，关闭实际就是删除，原先的共享代理也是作为一个单独的资源存在的，一个开启、关闭（创建、删除），几个修改接口，几个查询接口，还有一个这个基本上得在只读实例完成后才执行，主要是为了读写分离的连接地址

2022-11-16 16:05 UTC, zcc01029273 commented on website/docs/r/db_proxy.html.markdown
> +-> **NOTE:** Available in 1.193.0+.
done

2022-11-18 02:31 UTC, xiaozhu36 requested changes

2022-11-18 02:31 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +		action := "ModifyDBProxyEndpointAddress"
这个API的调用不应该放在这个资源中，应该用一个单独的资源来管理和设置

2022-11-18 02:31 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +	rawData := []byte(endpointInfo["ReadOnlyInstanceWeight"].(string))
schema中定义的参数要尽可能的跟API中的参数对齐

2022-11-18 02:31 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +	rawData := []byte(endpointInfo["ReadOnlyInstanceWeight"].(string))
包括参数类型

2022-11-18 02:31 UTC, xiaozhu36 commented on website/docs/r/rds_db_proxy.html.markdown
> +```
要加上 shell 标签

2022-11-18 03:26 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +	rawData := []byte(endpointInfo["ReadOnlyInstanceWeight"].(string))
这个由于openapi开启、修改与查询里面的名称不是很完美的对齐，所以有点差别，ReadOnlyInstanceWeight这个参数名的是由于，这个资源是替换的共享代理的资源，mysql共享代理的接口4月份下线了，为了方便客户后续继续更好使用所以还是Weight

2022-11-18 03:26 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +		action := "ModifyDBProxyEndpointAddress"
这里修改的是独享开启后默认生成的地址，这个地址只能修改，也不能删除，所以这里也有修改的，新增独享地址的create、update、delete会单独做资源来管理

2022-11-18 04:05 UTC, zcc01029273 commented on website/docs/r/rds_db_proxy.html.markdown
> +```
done

2022-11-21 06:24 UTC, xiaozhu36 requested changes

2022-11-21 06:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +		action := "ModifyDBProxyEndpoint"
这个API ModifyDBProxyEndpoint 应该放在新的资源 DBProxyEndpoint 中，而不是糅合在这个资源 db_proxy 中

2022-11-21 06:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +		action := "ModifyDBProxyEndpoint"
这个API ModifyDBProxyEndpoint 应该放在新的资源 DBProxyEndpoint 中

2022-11-21 06:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +	rawData := []byte(endpointInfo["ReadOnlyInstanceWeight"].(string))
如果对不齐，那么应该跟 查询 中的名称保持一致

2022-11-21 06:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +			},
这里的参数跟这个资源中涉及到的API的参数没有对齐，比如缺少 ResourceGroupId，

2022-11-21 07:41 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +		action := "ModifyDBProxyEndpoint"
这里调用ModifyDBProxyEndpoint是用来修改开启后默认生成的数据，新资源DBProxyEndpoint 也会调用ModifyDBProxyEndpoint来修改创建的数据

2022-11-21 07:41 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +		action := "ModifyDBProxyEndpoint"
这里调用ModifyDBProxyEndpoint是用来修改开启后默认生成的数据，新资源DBProxyEndpoint 也会调用ModifyDBProxyEndpoint来修改创建的数据

2022-11-21 08:48 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +	rawData := []byte(endpointInfo["ReadOnlyInstanceWeight"].(string))
done

2022-11-21 12:20 UTC, xiaozhu36 requested changes

2022-11-21 12:20 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +				Type:     schema.TypeMap,
这个字段在API上的出入参的类型都是 string，这个地方也应该跟API保持一致，改成 typeString

2022-11-21 12:20 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_db_proxy_test.go
> +					}),
Update 中总共有10个参数可以修改，但是测试case中只测试了4个参数的修改

2022-11-22 07:43 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +				Type:     schema.TypeMap,
openapi中输入输出格式是{"主实例ID":"权重","只读实例ID":"权重"...}，所以在代码中这样写的

2022-11-22 07:48 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_proxy_test.go
> +					}),
done

2022-11-22 13:41 UTC, xiaozhu36 requested changes

2022-11-22 13:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_db_proxy_test.go
> +						"${alicloud_db_readonly_instance.default.id}", "500"
这几个一定得放在一起更新么？能否一个一个的更新

2022-11-23 03:23 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_proxy_test.go
> +						"${alicloud_db_readonly_instance.default.id}", "500"
read_only_instance_distribution_type、db_proxy_features、read_only_instance_weight这三个参数相互串联，我修改了下，重新测试了

2022-11-23 03:27 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +				Type:     schema.TypeMap,
准备改来着，结果发现查询的值和修改的输入不一样，查询返回值是"[{\"Availability\":\"Available\",\"DBInstanceId\":\"rr-bp1fbpwn1ufi6c4ld\",\"DBInstanceType\":\"ReadOnly\",\"Weight\":1300},{\"Availability\":\"Available\",\"DBInstanceId\":\"rm-bp1k8p99n264wu6w3\",\"DBInstanceType\":\"Master\",\"Weight\":700}]"，对比了下共享代理的资源，共享代理的字段和这个字段一样的也是用的map，所以还是用map吧，处理对比也方便点

2022-11-25 15:19 UTC, merged