resource/resource_alicloud_db_instance: Added retry stragety and Instance status verification;resource/resource_alicloud_db_instance: Fix payment type conversion;resource/resource_alicloud_db_instance_test: Repair automated testing;
aliyun/terraform-provider-alicloud pull request #5603
Opened 2022-11-21 03:26 UTC by zcc01029273

2022-11-23 04:01 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_instance.go
> +		stateConf := BuildStateConf([]string{}, []string{"Running"}, client.GetRetryTimeout(d.Timeout(schema.TimeoutUpdate)), 3*time.Minute, rdsService.RdsDBInstanceStateRefreshFunc(d.Id(), []string{"Delet
done

2022-11-23 06:01 UTC, super-eggs commented on alicloud/resource_alicloud_db_instance.go
> +		stateConf := BuildStateConf([]string{}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 0, rdsService.RdsDBInstanceStateRefreshFunc(d.Id(), []string{"Deleting"}))
client.GetRetryTimeout(d.Timeout(schema.TimeoutUpdate)

2022-11-23 06:56 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_instance.go
> +		stateConf := BuildStateConf([]string{}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 0, rdsService.RdsDBInstanceStateRefreshFunc(d.Id(), []string{"Deleting"}))
done

2022-11-23 07:07 UTC, super-eggs commented on alicloud/resource_alicloud_db_instance.go
> +		err = resource.Retry(5*time.Minute, func() *resource.RetryError {
5*time.Minute => client.GetRetryTimeout(d.Timeout(schema.TimeoutUpdate)

2022-11-23 07:18 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_instance.go
> +		err = resource.Retry(5*time.Minute, func() *resource.RetryError {
这里是read

2022-11-25 07:27 UTC, xiaozhu36 requested changes

2022-11-25 07:27 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance.go
> -		action := "ModifyDBInstancePayType"
payType == Prepaid  这个判断为啥要去掉，现在是支持预付费转后付费了？

2022-11-25 07:39 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_instance.go
> -		action := "ModifyDBInstancePayType"
api可以支持，前段时间郭志远给我提了个需求就是预付费转后付费的需求aone：46044433

2022-11-25 15:26 UTC, merged