resource/alicloud_reserved_instance: Support new attribute `auto_renew`, `auto_renew_period`, `tags`, `reserved_instance_name`. Supports new output `allocation_status`, `create_time`, `expired_time`, `operation_locks`, `start_time`, `status`.
aliyun/terraform-provider-alicloud pull request #5618
Opened 2022-11-25 08:07 UTC by super-eggs

resource/alicloud_reserved_instance: Support new attribute `auto_renew`, `auto_renew_period`, `tags`, `reserved_instance_name`. Supports new output `allocation_status`, `create_time`, `expired_time`, `operation_locks`, `start_time`, `status`.

2022-11-30 09:43 UTC, MrWolong commented on website/docs/r/reserved_instance.html.markdown
> +* `allocation_status` -  ID of the ReservedInstance.
定义有问题
![image](https://user-images.githubusercontent.com/36806235/204762104-7fc55383-0d78-4627-b146-52391dc411f4.png)

2022-11-30 11:02 UTC, MrWolong commented on alicloud/service_alicloud_ecs.go
> -func (s *EcsService) WaitForReservedInstance(id string, status Status, timeout int) error {
这个为什么删除

2022-12-02 07:27 UTC, super-eggs commented on alicloud/service_alicloud_ecs.go
> -func (s *EcsService) WaitForReservedInstance(id string, status Status, timeout int) error {
修改为 common 形式后，这个也没用了。

2022-12-05 07:12 UTC, xiaozhu36 requested changes

2022-12-05 07:12 UTC, xiaozhu36 commented on alicloud/resource_alicloud_reserved_instance.go
> +				request["RenewalStatus"] = "Normal"
直接在schema中定义为 renewal_status就好了，不用转成 auto_renew

2022-12-05 07:39 UTC, super-eggs commented on alicloud/resource_alicloud_reserved_instance.go
> +				request["RenewalStatus"] = "Normal"
创建接口中使用的是 auto_renew。

2022-12-05 12:12 UTC, xiaozhu36 requested changes

2022-12-05 12:12 UTC, xiaozhu36 commented on alicloud/resource_alicloud_reserved_instance_test.go
> +				),
这个地方要再加一步，自动续费完了要记得关闭，不然这个资源到期一直没法释放

2022-12-09 15:43 UTC, super-eggs commented on alicloud/resource_alicloud_reserved_instance_test.go
> +				),
done

2022-12-10 02:51 UTC, merged