New Resource `alicloud_ocean_base_database`; New Datasource `alicloud_ocean_base_database`
aliyun/terraform-provider-alicloud pull request #5638
Opened 2022-11-30 09:33 UTC by thisnihonglei

2022-12-02 09:11 UTC, super-eggs commented on alicloud/data_source_alicloud_ocean_base_databases_test.go
> +			"databases.0.tables.#":      NOSET,
如果 with_tables = true，这里 tables 也会为空吗？

2022-12-02 09:11 UTC, super-eggs commented on alicloud/data_source_alicloud_ocean_base_databases_test.go
> +  instance_id   = "ob48azzvzketpc"
这里都是要写死吗？不可以创建吗？

2022-12-02 09:11 UTC, super-eggs commented on alicloud/resource_alicloud_ocean_base_database.go
> +			Delete: schema.DefaultTimeout(10 * time.Minute),
加上 Create 和 Update 的Timeouts 配置吧

2022-12-02 09:11 UTC, super-eggs commented on alicloud/resource_alicloud_ocean_base_database.go
> +	err = resource.Retry(d.Timeout(schema.TimeoutCreate), func() *resource.RetryError {
client.GetRetryTimeout(d.Timeout(schema.TimeoutCreate)
下前的也是一样

2022-12-02 09:11 UTC, super-eggs commented on alicloud/resource_alicloud_ocean_base_database.go
> +			"users": {
如果 users 支持更新，那就 应该返回。不返回的话，提Aone

2022-12-02 09:11 UTC, super-eggs commented on alicloud/resource_alicloud_ocean_base_database.go
> +				Computed: true,
instance_id 不返回的话，为啥配置成 Computed 呢

2022-12-02 09:11 UTC, super-eggs commented on alicloud/resource_alicloud_ocean_base_database.go
> +		action := "ModifyDatabaseDescription"
这个资源定义又问题，ModifyDatabaseDescription 接口中 instance_id 为必填，但是属性定义中 instance_id 又为选填

2022-12-08 07:10 UTC, thisnihonglei commented on alicloud/data_source_alicloud_ocean_base_databases_test.go
> +			"tenant_id":   `"t48xt2lc5vqrk"`,
因为这个资源的父资源有问题，还没有接入，这里只能用写死的父资源id

2022-12-08 07:11 UTC, thisnihonglei commented on alicloud/data_source_alicloud_ocean_base_databases_test.go
> +  instance_id   = "ob48azzvzketpc"
是的，都是写死的

2022-12-09 07:48 UTC, xiaozhu36 requested changes

2022-12-09 07:48 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_ocean_base_databases_test.go
> +	default = "tfacccoceanbase%d"
tf-testacc

2022-12-09 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_database.go
> +			"database_names": {
database_names 跟 database_names 的区别是啥

2022-12-09 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_database_test.go
> +					"instance_id": "ob48azzvzketpc",
instance id 不用每次都设置吧

2022-12-09 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_database_test.go
> +	name := fmt.Sprintf("tfacc%v", rand)
tf-testacc

2022-12-09 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_database.go
> +	if v, ok := d.GetOk("users"); ok {
既然可以支持修改，为啥不返回

2022-12-09 07:48 UTC, xiaozhu36 commented on vendor/github.com/aliyun/aliyun-log-go-sdk/client_project_policy.go
> +package sls
为啥要多加sls 的文件

2022-12-09 08:24 UTC, thisnihonglei commented on alicloud/resource_alicloud_ocean_base_database.go
> +			"database_names": {
创建的时候用的是database_name这个字段，修改的时候用的是database_names这个字段

2022-12-09 08:24 UTC, thisnihonglei commented on alicloud/resource_alicloud_ocean_base_database_test.go
> +					"instance_id": "ob48azzvzketpc",
instance id 是必填

2022-12-09 08:33 UTC, thisnihonglei commented on alicloud/resource_alicloud_ocean_base_database.go
> +	if v, ok := d.GetOk("users"); ok {
修改API修改的是用户名及具备的角色列表，DescribeDatabases查询接口返回的时候多一个账号类型，这个已经和云产品说明，他们近期会修复，我再接入下个月资源Tenant的时候，会把这个返回值带上。

2022-12-12 06:55 UTC, xiaozhu36 requested changes

2022-12-12 06:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_database.go
> +			"database_names": {
1. 这个肯定是不允许的，对于统一个属性，只能有一个参数
2. 没看到 database_names 修改的实现逻辑啊，测试case中也没有对应的step

2022-12-12 07:09 UTC, thisnihonglei commented on alicloud/resource_alicloud_ocean_base_database.go
> +			"database_names": {
已去掉databases_name这个属性

2022-12-12 07:16 UTC, xiaozhu36 requested changes

2022-12-12 07:16 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_database_test.go
> +					"instance_id": "ob48azzvzketpc",
必填也不用每个step都要设置啊，在第一步设置了就行啊

2022-12-12 07:16 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_database.go
> +		request["InstanceId"] = v
delete 中为啥还要传 instance id

2022-12-12 07:30 UTC, thisnihonglei commented on alicloud/resource_alicloud_ocean_base_database.go
> +		request["InstanceId"] = v
instance id在delete中是作为选填参数传入的

2022-12-12 07:52 UTC, xiaozhu36 requested changes

2022-12-12 07:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_database_test.go
> +				ImportStateVerifyIgnore: []string{"instance_id", "users"},
instance_id 是必填的属性，这个必须得返回。

2023-03-06 02:02 UTC, closed without merging