New Resource `alicloud_vpc_gateway_route_table_attachment`;
aliyun/terraform-provider-alicloud pull request #5646
Opened 2022-12-01 09:37 UTC by thisnihonglei

2022-12-01 09:41 UTC, thisnihonglei commented on alicloud/resource_alicloud_route_table.go
> +			"associate_type": {
由于新增资源需要网关路由表，所以这里根据API新增路由表类型字段。

2022-12-01 09:41 UTC, thisnihonglei commented on alicloud/resource_alicloud_vpc_ipv4_gateway.go
> +			"enabled": {
因为新增资源需要已激活的ipv4网关，所以新增属性，用来调用新增的EnableVpcIpv4Gateway接口激活网关

2022-12-02 03:01 UTC, xiaozhu36 requested changes

2022-12-02 03:40 UTC, xiaozhu36 requested changes

2022-12-02 03:40 UTC, xiaozhu36 commented on alicloud/resource_alicloud_route_table_test.go
> +					"associate_type":   "Gateway",
如果默认值是 Gateway，那么这个地方不应该变，而是应该再单独写一个值为 vswitch 的测试case

2022-12-02 03:49 UTC, thisnihonglei commented on alicloud/resource_alicloud_route_table_test.go
> +					"associate_type":   "Gateway",
默认值是vswitch

2022-12-12 02:42 UTC, xiaozhu36 requested changes

2022-12-12 02:42 UTC, xiaozhu36 commented on website/docs/r/vpc_gateway_route_table_attachment.html.markdown
> +subcategory: "VPC"
这个应该是 VPN Gateway

2022-12-12 02:42 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_gateway_route_table_attachment.go
> +				Computed: true,
route_table_id 是id 的组成部分，应该是 必填啊

2022-12-12 05:23 UTC, xiaozhu36 requested changes

2022-12-12 05:23 UTC, xiaozhu36 commented on website/docs/r/vpc_gateway_route_table_attachment.html.markdown
> +subcategory: "VPN Gateway"
嗯，这个我看错了，确认了下，还是改成 vpc 吧

2022-12-12 05:23 UTC, xiaozhu36 commented on website/docs/r/vpc_gateway_route_table_attachment.html.markdown
> +* `route_table_id` - (Required, Computed, ForceNew) The ID of the Gateway route table to be bound.
Computed不要

2022-12-12 06:27 UTC, xiaozhu36 requested changes

2022-12-12 06:27 UTC, xiaozhu36 commented on website/docs/r/vpc_gateway_route_table_attachment.html.markdown
> +subcategory: "VPC Gateway"
不是改成 VPC Gateway，是改成 VPC

2022-12-12 06:27 UTC, xiaozhu36 commented on website/docs/r/vpc_gateway_route_table_attachment.html.markdown
> +* `dry_run` - (Optional) The dry run.
这个还是没改啊。对比英文的Openapi文档，看看 dry run 是怎么描述的

2022-12-12 06:44 UTC, merged