New Resource `alicloud_cloud_firewall_vpc_firewall`; New Datasource `alicloud_cloud_firewall_vpc_firewalls`
aliyun/terraform-provider-alicloud pull request #5668
Opened 2022-12-06 13:33 UTC by xiaosier

New Resource `alicloud_cloud_firewall_vpc_firewall`; New Datasource `alicloud_cloud_firewall_vpc_firewalls`

2022-12-07 01:52 UTC, xiaozhu36 requested changes

2022-12-07 01:52 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cloud_firewall_vpc_firewalls.go
> +			"region_no": {
region_no 不用定义，在provider声明的时候就有

2022-12-07 01:52 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cloud_firewall_vpc_firewalls_test.go
> +  vpc_firewall_name = "tf-test"
直接使用 var.name 即可

2022-12-07 01:52 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cloud_firewall_vpc_firewalls_test.go
> +  member_uid        = "1415189284827022"
member_uid 不要写死，可以使用 account 的datasource来自动获取

2022-12-07 01:52 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cloud_firewall_vpc_firewalls_test.go
> +    vpc_id    = "vpc-bp1gcmm64o3caox84v0nz"
vpc_id 可以创建一个新的或者使用 datasource 来获取

2022-12-07 01:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloud_firewall_vpc_firewall.go
> +				Default:  "zh",
默认值改成 Computed

2022-12-07 01:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloud_firewall_vpc_firewall.go
> +			"vpc_firewall_id": {
vpc_firewall_id 应该不是Optional 的

2022-12-07 01:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloud_firewall_vpc_firewall.go
> +	}
如果 lang 不能通过 api 返回，那么直接定义为 Optional，即可，read 中也无需set

2022-12-07 01:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloud_firewall_vpc_firewall.go
> +	}
Delete 中，lang 和 member_uid 时必须的么，如果不是，是不是可以选择去掉

2022-12-07 01:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloud_firewall_vpc_firewall_test.go
> +				Config: testAccConfig(map[string]interface{}{
此处参数的设置规则跟 datasource中的一样

2022-12-07 01:52 UTC, xiaozhu36 commented on website/docs/r/cloud_firewall_vpc_firewall.html.markdown
> +* `id` - (Computed) The ID of the VPC firewall instance.
在 Attributes Reference 中，都是出参，不用加 (Computed) 标签

2022-12-08 14:37 UTC, xiaosier commented on alicloud/data_source_alicloud_cloud_firewall_vpc_firewalls.go
> +			"region_no": {
这个是单独的特性，允许用户指定的。

2022-12-08 14:37 UTC, xiaosier commented on alicloud/data_source_alicloud_cloud_firewall_vpc_firewalls_test.go
> +  member_uid        = "1415189284827022"
已修改。

2022-12-08 14:38 UTC, xiaosier commented on alicloud/data_source_alicloud_cloud_firewall_vpc_firewalls_test.go
> +  vpc_firewall_name = "tf-test"
已修改。

2022-12-08 14:38 UTC, xiaosier commented on alicloud/data_source_alicloud_cloud_firewall_vpc_firewalls_test.go
> +    vpc_id    = "vpc-bp1gcmm64o3caox84v0nz"
已修改。

2022-12-08 14:38 UTC, xiaosier commented on alicloud/resource_alicloud_cloud_firewall_vpc_firewall.go
> +			"vpc_firewall_id": {
已修改

2022-12-08 14:38 UTC, xiaosier commented on alicloud/resource_alicloud_cloud_firewall_vpc_firewall.go
> +				Default:  "zh",
已修改。

2022-12-08 14:38 UTC, xiaosier commented on alicloud/resource_alicloud_cloud_firewall_vpc_firewall.go
> +	}
已修改。

2022-12-08 14:39 UTC, xiaosier commented on alicloud/resource_alicloud_cloud_firewall_vpc_firewall.go
> +	}
这个是必要的。

2022-12-08 14:39 UTC, xiaosier commented on alicloud/resource_alicloud_cloud_firewall_vpc_firewall_test.go
> +				Config: testAccConfig(map[string]interface{}{
已修改

2022-12-08 14:39 UTC, xiaosier commented on website/docs/r/cloud_firewall_vpc_firewall.html.markdown
> +* `id` - (Computed) The ID of the VPC firewall instance.
已修改。

2022-12-08 15:10 UTC, merged