resource/alicloud_slb_load_balancer: Remove the ConflictsWith setting from attribute `payment_type`;resource/alicloud_vpn_gateway_vpn_attachment: Update document information;resource/alicloud_vpn_gateway: Update document information;
aliyun/terraform-provider-alicloud pull request #5674
Opened 2022-12-07 08:57 UTC by thisnihonglei

2022-12-07 08:58 UTC, thisnihonglei commented on alicloud/data_source_alicloud_vpn_gateway_vpn_attachments.go
> -			"vpn_gateway_id": {
已经得到云产品准确答复，该资源不支持用vpn_gateway_id筛查，所以去掉

2022-12-08 06:44 UTC, xiaozhu36 requested changes

2022-12-08 06:44 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_vpn_gateway_vpn_attachments.go
> -			"vpn_gateway_id": {
但是我看DescribeVpnConnections 中有这个参数啊

2022-12-08 06:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_slb_load_balancer.go
>  			"instance_charge_type": {
按照API文档上的规则，instance_charge_type 这个是不是得增加一个压制函数

2022-12-08 06:55 UTC, thisnihonglei commented on alicloud/data_source_alicloud_vpn_gateway_vpn_attachments.go
> -			"vpn_gateway_id": {
云产品说后面这个会下掉

2022-12-08 08:01 UTC, thisnihonglei commented on alicloud/resource_alicloud_slb_load_balancer.go
>  			"instance_charge_type": {
done

2022-12-08 09:50 UTC, xiaozhu36 requested changes

2022-12-08 09:50 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_vpn_gateway_vpn_attachments.go
> -			"vpn_gateway_id": {
那也应该先标记为 Deprecated

2022-12-08 09:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_slb_load_balancer.go
> +					return false
这个在文档中也加个note 吧

2022-12-12 02:35 UTC, xiaozhu36 requested changes

2022-12-12 06:21 UTC, merged