New Resource `alicloud_threat_detection_backup_policy`; New Datasource `alicloud_threat_detection_backup_policies`
aliyun/terraform-provider-alicloud pull request #5684
Opened 2022-12-09 06:32 UTC by MrWolong

2022-12-09 06:47 UTC, super-eggs commented on alicloud/data_source_alicloud_threat_detection_backup_policies_test.go
> +			"policies.0.status":             "enabled",
check policy_region_id

2022-12-09 06:50 UTC, super-eggs commented on alicloud/resource_alicloud_threat_detection_backup_policy.go
> +	if d.HasChange("policy_region_id") {
可修改的属性，需要返回。我看 list 接口有返回

2022-12-09 06:56 UTC, MrWolong commented on alicloud/data_source_alicloud_threat_detection_backup_policies_test.go
> +			"policies.0.status":             "enabled",
因为你没输入，这个值根本不返回，而且这个值必须是非阿里云的机器才填

2022-12-13 03:16 UTC, MrWolong commented on alicloud/resource_alicloud_threat_detection_backup_policy.go
> +	if d.HasChange("policy_region_id") {
已修复

2022-12-13 03:25 UTC, MrWolong commented on alicloud/resource_alicloud_threat_detection_backup_policy_test.go
> +			},
这个值根本不返回，只有非阿里云的机器才填

2022-12-13 03:25 UTC, MrWolong commented on alicloud/resource_alicloud_threat_detection_backup_policy.go
> +		"PolicyVersion": d.Get("policy_version"),
云产品已修复

2022-12-15 12:36 UTC, xiaozhu36 requested changes

2022-12-15 12:36 UTC, xiaozhu36 commented on website/docs/r/threat_detection_backup_policy.html.markdown
> +# alicloud\_ga\_basic\_accelerator
这个名称不对

2022-12-15 12:36 UTC, xiaozhu36 commented on website/docs/r/threat_detection_backup_policy.html.markdown
> +# alicloud\_ga\_basic\_accelerator
这个文档是自动生成的么

2022-12-19 06:52 UTC, MrWolong commented on alicloud/resource_alicloud_threat_detection_backup_policy_test.go
> +		Steps: []resource.TestStep{
如果用例跟自动化生成的用例一致，测试会失败

2022-12-19 06:53 UTC, MrWolong commented on alicloud/connectivity/client.go
> +			endpoint = "tds.aliyuncs.com"
之前在Threatdetection群里确认了，备用endpoint用endpoint = "tds.aliyuncs.com"

2022-12-19 06:55 UTC, MrWolong commented on alicloud/data_source_alicloud_threat_detection_backup_policies_test.go
> +func TestAccAlicloudThreatDetectionBackupPoliciesDataSource(t *testing.T) {
自动化的data source测试用例不完善，没办法使用

2022-12-19 08:57 UTC, MrWolong commented on website/docs/r/threat_detection_backup_policy.html.markdown
> +# alicloud\_ga\_basic\_accelerator
已修复

2022-12-20 05:43 UTC, MrWolong commented on website/docs/d/threat_detection_backup_policies.html.markdown
> +---
拼写有问题，标点符号有问题
![image](https://user-images.githubusercontent.com/36806235/208592557-7c4f94db-45bb-4cbd-b32d-bceb33c1acc1.png)

2022-12-20 05:46 UTC, MrWolong commented on website/docs/d/threat_detection_backup_policies.html.markdown
> +This data source provides the Threat Detection Backup Policies of the current Alibaba Cloud user.
data source主要作用是查找，不需要在文档标注这个吧，历史文档中，只有resource才需要标注。
![image](https://user-images.githubusercontent.com/36806235/208592890-9782b73f-c678-414b-a872-3a2612dd4ca5.png)

2022-12-20 06:24 UTC, MrWolong commented on website/docs/d/threat_detection_backup_policies.html.markdown
> +
ids已经是入参了

2022-12-20 08:42 UTC, MrWolong commented on website/docs/r/threat_detection_backup_policy.html.markdown
> +* `id` - The resource ID in terraform of Backup Policy.
id与status描述不准确，backup_policy_id与page_total是无效的字段。id已经是这个实例的标识了，page_total查询接口并不返回这个字段对应的属性。
![image](https://user-images.githubusercontent.com/36806235/208621287-7354f85a-1a8e-4aeb-bc04-891668ed924c.png)

2022-12-20 08:44 UTC, MrWolong commented on website/docs/r/threat_detection_backup_policy.html.markdown
> +* `policy_region_id` - (Optional) The region ID of the non-Alibaba cloud server.
policy_region_id的描述中，有个多余的符号>，其次[DescribeSupportRegion]后面应该跟的是这个接口的api文档链接。
![image](https://user-images.githubusercontent.com/36806235/208622793-fcf75580-e25d-4288-9474-f295c6ba3fa7.png)

2022-12-21 07:19 UTC, xiaozhu36 requested changes

2022-12-21 07:19 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_threat_detection_backup_policies_test.go
> +  		backup_policy_name = "自动化测试1"
var.name

2022-12-21 07:19 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_backup_policy_test.go
> +					"backup_policy_name": "自动化测试1",
var.name

2022-12-21 07:19 UTC, xiaozhu36 commented on website/docs/r/threat_detection_backup_policy.html.markdown
> +  backup_policy_name = "自动化测试1"
尽量用英文

2022-12-21 07:53 UTC, MrWolong commented on alicloud/data_source_alicloud_threat_detection_backup_policies_test.go
> +  		backup_policy_name = "自动化测试1"
已修复

2022-12-21 07:53 UTC, MrWolong commented on alicloud/resource_alicloud_threat_detection_backup_policy_test.go
> +					"backup_policy_name": "自动化测试1",
已修复

2022-12-21 07:53 UTC, MrWolong commented on website/docs/r/threat_detection_backup_policy.html.markdown
> +  backup_policy_name = "自动化测试1"
已修复

2022-12-22 07:33 UTC, merged