New Resource alicloud_rds_cross_detection_backup_policyadd rds cross region backup policy
aliyun/terraform-provider-alicloud pull request #5701
Opened 2022-12-12 07:00 UTC by zcc01029273

2022-12-15 02:44 UTC, super-eggs commented on website/docs/r/rds_cross_region_backup_policy.html.markdown
> +-> **NOTE:** -> **NOTE:** Available in 1.194.0+.
1.195.0

格式也不对。

2022-12-15 02:47 UTC, super-eggs commented on website/docs/r/rds_cross_region_backup_policy.html.markdown
> +* `backup_enabled` - The status of the overall cross-region backup switch on the instance. Valid values:
`id`

2022-12-15 02:49 UTC, super-eggs commented on alicloud/resource_alicloud_rds_cross_region_backup_policy_test.go
> +		//CheckDestroy:  rac.checkResourceDestroy(),
为啥要注释

2022-12-15 05:38 UTC, zcc01029273 commented on website/docs/r/rds_cross_region_backup_policy.html.markdown
> +-> **NOTE:** -> **NOTE:** Available in 1.194.0+.
done

2022-12-15 05:38 UTC, zcc01029273 commented on website/docs/r/rds_cross_region_backup_policy.html.markdown
> +* `backup_enabled` - The status of the overall cross-region backup switch on the instance. Valid values:
done

2022-12-15 05:38 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_cross_region_backup_policy_test.go
> +		//CheckDestroy:  rac.checkResourceDestroy(),
done

2022-12-15 06:55 UTC, super-eggs commented on website/docs/r/rds_cross_region_backup_policy.html.markdown
> +Provides an RDS instance emote disaster recovery strategy policy resource and used to configure instance emote disaster recovery strategy policy.
文档没有吗？如果有的话，加上链接。

2022-12-15 07:08 UTC, super-eggs commented on alicloud/service_alicloud_rds.go
> +func (s *RdsService) DescribeInstanceCrossBackupPolicy(id string) (map[string]interface{}, error) {
这里只查询 BackupEnabled 为 Enable 的资源就好。 这样销毁操作才是正常的

2022-12-15 10:12 UTC, zcc01029273 commented on alicloud/service_alicloud_rds.go
> +func (s *RdsService) DescribeInstanceCrossBackupPolicy(id string) (map[string]interface{}, error) {
done

2022-12-16 03:49 UTC, xiaozhu36 requested changes

2022-12-16 03:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_cross_region_backup_policy.go
> +				Default:      7,
如果有默认值，不要写死，直接设置为computed

2022-12-16 03:49 UTC, xiaozhu36 commented on alicloud/provider.go
> +			"alicloud_rds_cross_region_backup_policy":     resourceAlicloudRdsCrossRegionBackupPolicy(),
从API上看，这个应该命名为 alicloud_rds_instance_cross_backup_policy

2022-12-16 06:33 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_cross_region_backup_policy.go
> +				Default:      7,
done

2022-12-16 06:33 UTC, zcc01029273 commented on alicloud/provider.go
> +			"alicloud_rds_cross_region_backup_policy":     resourceAlicloudRdsCrossRegionBackupPolicy(),
done

2022-12-23 07:18 UTC, merged