New Resource `alicloud_ecs_elasticity_assurance`; New Datasource `alicloud_ecs_elasticity_assurances`;
aliyun/terraform-provider-alicloud pull request #5733
Opened 2022-12-22 07:56 UTC by super-eggs

New Resource `alicloud_ecs_elasticity_assurance`; 
New Datasource `alicloud_ecs_elasticity_assurances`;

2023-01-05 11:33 UTC, xiaozhu36 requested changes

2023-01-05 11:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_elasticity_assurance.go
> +	return resourceAlicloudEcsElasticityAssuranceRead(d, meta)
看起来tags 不在 create 中啊

2023-01-05 11:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ecs_elasticity_assurance_test.go
> +					"instance_type":                       []string{"ecs.c6.large"},
用datasource instance_types

2023-01-06 03:39 UTC, super-eggs commented on alicloud/resource_alicloud_ecs_elasticity_assurance_test.go
> +					"instance_type":                       []string{"ecs.c6.large"},
done

2023-01-06 03:39 UTC, super-eggs commented on alicloud/resource_alicloud_ecs_elasticity_assurance.go
> +	return resourceAlicloudEcsElasticityAssuranceRead(d, meta)
有的，在第172行

2023-01-06 06:36 UTC, merged