resource/alicloud_db_readwrite_splitting_connection : Repair create SQL Server read write splitting connection fail bug
aliyun/terraform-provider-alicloud pull request #5734
Opened 2022-12-22 10:31 UTC by TingxuanGuo

2022-12-22 10:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=5734) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=5734) before we can accept your contribution.<br/><hr/>**tingxuan.guo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=5734) it.</sub>

2022-12-23 10:22 UTC, xiaozhu36 requested changes

2022-12-23 10:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_readwrite_splitting_connection.go
> -		return resourceAlicloudDBProxyEndpointRead(d, rdsService, proxy["DBProxyInstanceName"].(string))
这段逻辑为啥要删掉

2022-12-23 10:31 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_readwrite_splitting_connection.go
> -		return resourceAlicloudDBProxyEndpointRead(d, rdsService, proxy["DBProxyInstanceName"].(string))
该openAPI，mysql,pgsql已经弃用，当前仅sqlserver引擎使用此功能，sqlserver无此字段逻辑，属于冗余代码故做删除操作。

2022-12-26 01:56 UTC, TingxuanGuo commented
done

2022-12-28 12:44 UTC, merged