New resource alicloud_cen_transit_router_multicast_domain_source and its datasource.
aliyun/terraform-provider-alicloud pull request #5751
Opened 2022-12-27 03:41 UTC by ChenHanZhang

2022-12-27 06:49 UTC, xiaozhu36 requested changes

2022-12-27 06:49 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cen_transit_router_multicast_domain_sources_test.go
> +  vpc_id                             = "vpc-2zesuv0tyo2rqqnwl94ve"
vpc id 为啥是写死的

2022-12-27 06:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cen_transit_router_multicast_domain_source_test.go
> +					"group_ip_address":                   "232.1.1.1",
这几个都是写死的

2022-12-27 06:49 UTC, xiaozhu36 commented on website/docs/r/cen_transit_router_multicast_domain_source.html.markdown
> +```
< transit_router_multicast_domain_id>:<group_ip_address>:<network_interface_id >

2022-12-27 06:57 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cen_transit_router_multicast_domain_source_test.go
> +					"group_ip_address":                   "232.1.1.1",
依赖的前置资源还未合并到主干

2022-12-27 06:59 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_cen_transit_router_multicast_domain_sources_test.go
> +  vpc_id                             = "vpc-2zesuv0tyo2rqqnwl94ve"
这里vpcid是云企业网中的网络节点，可以vpc的datasource查，这里我改下

2022-12-27 07:31 UTC, ChenHanZhang commented on website/docs/r/cen_transit_router_multicast_domain_source.html.markdown
> +```
done

2022-12-29 11:11 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cen_transit_router_multicast_domain_source_test.go
> +					"group_ip_address":                   "232.1.1.1",
前置已合并，已更新

2022-12-29 12:53 UTC, xiaozhu36 requested changes

2022-12-29 12:53 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cen_transit_router_multicast_domain_sources_test.go
> +  vpc_name   = "sdk_rebot_cen_tr_yaochi"
var.name

2022-12-29 12:53 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cen_transit_router_multicast_domain_sources_test.go
> +  vpc_name   = "sdk_rebot_cen_tr_yaochi"
后面的也一样

2022-12-29 13:00 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_cen_transit_router_multicast_domain_sources_test.go
> +}
已经是直接创建了

2022-12-29 13:01 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_cen_transit_router_multicast_domain_sources_test.go
> +  vpc_name   = "sdk_rebot_cen_tr_yaochi"
done

2022-12-29 13:55 UTC, xiaozhu36 requested changes

2022-12-29 13:55 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cen_transit_router_multicast_domain_sources_test.go
> +  zone_id      = "cn-hangzhou-i"
可用区不要写死

2022-12-29 13:55 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_cen_transit_router_multicast_domain_sources_test.go
> +
不能用同一个name么

2022-12-29 13:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cen_transit_router_multicast_domain_source_test.go
> +variable "transit_router_attachment_name" {
这个地方也一样

2022-12-29 13:57 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_cen_transit_router_multicast_domain_sources_test.go
> +  zone_id      = "cn-hangzhou-i"
只能在hangzhou-i和hangzhou-j进行测试

2022-12-30 01:16 UTC, merged