New Resource `alicloud_ebs_disk_replica_pair`; New Datasource `alicloud_ebs_disk_replica_pairs`;
aliyun/terraform-provider-alicloud pull request #5758
Opened 2022-12-28 10:19 UTC by thisnihonglei

2022-12-29 05:06 UTC, xiaosier commented on alicloud/data_source_alicloud_ebs_disk_replica_pairs.go
> +	}
output_file没处理。

2022-12-29 05:06 UTC, xiaosier commented on alicloud/data_source_alicloud_ebs_disk_replica_pairs_test.go
> +  destination_disk_id   = "d-iq8aj6hjpu0m98fyp583"
最终这些还是要改为resource或者DataSource查询。

2022-12-29 05:06 UTC, xiaosier commented on alicloud/resource_alicloud_ebs_disk_replica_pair.go
> +		"RegionId": "cn-hangzhou-onebox-nebula",
最终这里还是要改下。

2022-12-29 05:06 UTC, xiaosier commented on alicloud/resource_alicloud_ebs_disk_replica_pair_test.go
> +					"destination_disk_id":   "d-iq8aj6hjpu0m98fyp585",
最终这里还是要改为resource或者DataSource。

2023-01-09 03:47 UTC, xiaozhu36 requested changes

2023-01-09 03:47 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ebs_disk_replica_pair.go
> +		if v, ok := d.GetOk("pair_name"); ok {
既然这两个都在 create中有设置，那么create 之后直接return read 就可以了

2023-01-09 03:47 UTC, xiaozhu36 commented on website/docs/r/ebs_disk_replica_pair.html.markdown
> +$terraform import alicloud_ebs-disk-replica-pair.example <id>
$ 之后加一个空格

2023-01-10 06:14 UTC, xiaozhu36 requested changes

2023-01-10 06:27 UTC, thisnihonglei commented on alicloud/resource_alicloud_ebs_disk_replica_pair.go
> +	stateConf := BuildStateConf([]string{}, []string{"creating", "created", "initial_syncing", "manual_syncing", "syncing", "normal"}, d.Timeout(schema.TimeoutCreate), 5*time.Second, ebsService.EbsDiskR
有2个，一个created，创建完成。一个normal，当异步复制的当前周期内数据复制完成时，将处于该状态。

2023-01-10 07:13 UTC, xiaozhu36 requested changes

2023-01-10 07:13 UTC, xiaozhu36 commented on website/docs/r/ebs_disk_replica_pair.html.markdown
> +# alicloud_ebs-disk-replica-pair
为什么是中划线

2023-01-10 07:13 UTC, xiaozhu36 commented on website/docs/r/ebs_disk_replica_pair.html.markdown
> +$ terraform import alicloud_ebs-disk-replica-pair.example <id>
还有这个

2023-01-10 08:11 UTC, merged