New DataSource: alicloud_rds_cross_region_backups
aliyun/terraform-provider-alicloud pull request #5762
Opened 2022-12-29 05:48 UTC by zcc01029273

2023-01-03 02:32 UTC, super-eggs commented on website/docs/d/rds_cross_region_backups.html.markdown
> +-> **NOTE:** Available in v1.195.0+.
1.196.0

2023-01-03 02:32 UTC, super-eggs commented on alicloud/data_source_alicloud_rds_cross_region_backups.go
> +			if len(idsMap) > 0 {
如果不支持ids 查询，那这里的逻辑就没有意义

2023-01-03 02:32 UTC, super-eggs commented on alicloud/data_source_alicloud_rds_cross_region_backups.go
> +			"ids": {
为什么不支持 ids 查询？

2023-01-03 03:27 UTC, zcc01029273 commented on website/docs/d/rds_cross_region_backups.html.markdown
> +-> **NOTE:** Available in v1.195.0+.
done

2023-01-03 03:27 UTC, zcc01029273 commented on alicloud/data_source_alicloud_rds_cross_region_backups.go
> +			if len(idsMap) > 0 {
已修改，已测试

2023-01-03 03:28 UTC, zcc01029273 commented on alicloud/data_source_alicloud_rds_cross_region_backups.go
> +			"ids": {
支持，但是ids是查询完，才能知道，加上了，测试正常

2023-01-03 06:03 UTC, xiaozhu36 requested changes

2023-01-03 06:03 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_rds_cross_region_backups.go
> +			"cross_backups": {
改成 backups

2023-01-03 06:03 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_rds_cross_region_backups.go
> +						"id": {
ID为啥是 int

2023-01-03 08:00 UTC, zcc01029273 commented on alicloud/data_source_alicloud_rds_cross_region_backups.go
> +			"cross_backups": {
done

2023-01-03 08:00 UTC, zcc01029273 commented on alicloud/data_source_alicloud_rds_cross_region_backups.go
> +						"id": {
done

2023-01-08 01:50 UTC, xiaozhu36 requested changes

2023-01-08 01:50 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_rds_cross_region_backups.go
> +							Computed: true,
cross_backup_id 和 id 是同一值，那么类型也应该是一样的

2023-01-08 01:51 UTC, xiaozhu36 requested changes

2023-01-08 01:51 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_rds_cross_region_backups_test.go
> +func CrossBackupsTestAccAlicloudRdsCrossRegionBackupsDataSource(t *testing.T) {
那这个地方还是改成 SkipTestAccxxx吧

2023-01-09 03:31 UTC, zcc01029273 commented on alicloud/data_source_alicloud_rds_cross_region_backups_test.go
> +func CrossBackupsTestAccAlicloudRdsCrossRegionBackupsDataSource(t *testing.T) {
done

2023-01-09 03:32 UTC, zcc01029273 commented on alicloud/data_source_alicloud_rds_cross_region_backups.go
> +							Computed: true,
done

2023-01-09 03:38 UTC, xiaozhu36 requested changes

2023-01-09 03:38 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_rds_cross_region_backups.go
> +						"instance_id": {
这个instance_id 是 rds 实例的ID么？如果是的话，类型应该是 String

2023-01-09 03:56 UTC, zcc01029273 commented on alicloud/data_source_alicloud_rds_cross_region_backups.go
> +						"instance_id": {
这个是返回的实例编号，与OpenAPI对齐的

2023-01-09 04:18 UTC, merged