New Resource `alicloud_threat_detection_instance`; New Datasource `alicloud_threat_detection_instances`;
aliyun/terraform-provider-alicloud pull request #5767
Opened 2022-12-29 10:17 UTC by super-eggs

New Resource `alicloud_threat_detection_instance`; 
New Datasource `alicloud_threat_detection_instances`;

2022-12-29 14:02 UTC, xiaozhu36 requested changes

2022-12-29 14:02 UTC, xiaozhu36 commented on website/docs/r/threat_detection_instance.html.markdown
> +* `value` - (Required,Computed) The nth module attribute value configuration.
如果是这样的话，需要提供一个统一的datasource来获取 code 和values

2022-12-29 14:02 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_instance_test.go
> +				ImportStateVerifyIgnore: []string{"modify_type", "parameter", "period", "renewal_status"},
renewal_status 应该是有bss 的openapi可以获取到的

2022-12-30 05:56 UTC, xiaosier commented on website/docs/d/threat_detection_instances.html.markdown
> +This data source provides Threat Detection Instance available to the user.[What is Instance](https://www.alibabacloud.com/help/en/)
这里的文档链接不对。

2022-12-30 05:56 UTC, xiaosier commented on website/docs/r/threat_detection_instance.html.markdown
> +For information about Threat Detection Instance and how to use it, see [What is Instance](https://www.alibabacloud.com/help/en/).
这里的文档链接不对。

2022-12-30 08:29 UTC, xiaozhu36 requested changes

2022-12-30 08:29 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_instance.go
> +				conn.Endpoint = String(connectivity.BssOpenAPIEndpointInternational)
这个地方要确认下，如果国际站的ProductCode 和ProductType 要不要更换。一般国际站的和国内站的code 是不一致的

2022-12-30 08:29 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_instance.go
> +					wait()
这个地方也是一样的

2022-12-30 08:29 UTC, xiaozhu36 commented on website/docs/r/threat_detection_instance.html.markdown
> +$terraform import alicloud_threat_detection_instance.example <id>
如果不支持import，那么这个地方就不要写了

2022-12-30 08:29 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_instance.go
> +			State: schema.ImportStatePassthrough,
不支持import的话，Importer 就不要写了

2023-02-02 07:36 UTC, super-eggs commented on alicloud/resource_alicloud_threat_detection_instance.go
> +				conn.Endpoint = String(connectivity.BssOpenAPIEndpointInternational)
done

2023-02-02 09:52 UTC, xiaozhu36 requested changes

2023-02-02 09:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_nat_gateway_test.go
> +			//{
这些为啥要注释掉

2023-02-02 09:52 UTC, xiaozhu36 commented on website/docs/d/bss_openapi_pricing_modules.html.markdown
> +page_title: "Alicloud: alicloud_bss_open_api_pricing_modules"
这个文件的名字也改下吧

2023-02-03 07:18 UTC, xiaozhu36 requested changes

2023-02-03 07:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_instance.go
> +				Type:     schema.TypeInt,
这个字段能返回么？如果不能，那么不能设置为 Required

2023-02-03 07:18 UTC, xiaozhu36 commented on website/docs/r/threat_detection_instance.html.markdown
> +Threat Detection Instance do not support import.
为啥不支持

2023-02-03 07:49 UTC, super-eggs commented on website/docs/r/threat_detection_instance.html.markdown
> +Threat Detection Instance do not support import.
因为 parameter 参数必填不返回。

2023-02-14 01:01 UTC, merged