alicloud_db_readonly_instance support for security_ips
aliyun/terraform-provider-alicloud pull request #5772
Opened 2022-12-30 07:19 UTC by yangxiaodong19

2022-12-30 07:25 UTC, yangxiaodong19 commented
https://aone.alibaba-inc.com/v2/project/872376/req/47016930   测试附Aone

2023-01-03 02:25 UTC, xiaozhu36 requested changes

2023-01-03 02:25 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_readonly_instance.go
> +	if d.HasChange("security_ips") {
其他属性的变更也需要判断

2023-01-03 02:25 UTC, xiaozhu36 commented on website/docs/r/db_readonly_instance.html.markdown
> +* `security_ips` - (Optional, Available in 1.195.0+) List of IP addresses allowed to access all databases of an instance. The list contains up to 1,000 IP addresses, separated by commas. Supported fo
195 版本已经发布了，改成 196 吧

2023-01-06 08:03 UTC, xiaozhu36 requested changes

2023-01-06 08:03 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_readonly_instance_test.go
>  		},
其他新增的属性也需要测下

2023-01-09 05:18 UTC, yangxiaodong19 commented
新增属性测试结果 附Aone

2023-01-10 01:54 UTC, merged