New Datasource `alicloud_service_catalog_provisioned_product`; New Datasource `alicloud_service_catalog_provisioned_products`;
aliyun/terraform-provider-alicloud pull request #5779
Opened 2023-01-03 02:49 UTC by xiaosier

New Datasource `alicloud_service_catalog_provisioned_product`; New Datasource `alicloud_service_catalog_provisioned_products`;

2023-01-04 11:32 UTC, xiaozhu36 requested changes

2023-01-04 11:32 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_service_catalog_provisioned_products.go
> +						"tags": {
tags 都是统一的map结构

2023-01-04 11:32 UTC, xiaozhu36 commented on alicloud/resource_alicloud_service_catalog_provisioned_product.go
> +			"tags": {
tags 统一成 map 格式

2023-01-04 11:47 UTC, xiaosier commented on alicloud/data_source_alicloud_service_catalog_provisioned_products.go
> +						"tags": {
这个不是标准的tag

2023-01-04 11:48 UTC, xiaosier commented on alicloud/resource_alicloud_service_catalog_provisioned_product.go
> +			"tags": {
这个不是标准的tag

2023-01-04 15:49 UTC, xiaozhu36 requested changes

2023-01-04 15:49 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_service_catalog_product_as_end_users_test.go
> +func skipTestAccAlicloudServiceCatalogProductAsEndUserDataSource(t *testing.T) {
为啥要跳过

2023-01-04 15:49 UTC, xiaozhu36 commented on website/docs/r/service_catalog_provisioned_product.html.markdown
> +* `tag_value` - (Optional) The custom label value entered by the user.It can be up to 128 characters and cannot start with ACS: 'or contain http:// or https://'.
这个地方也按照标准的写法写吧

2023-01-05 01:39 UTC, xiaosier commented on alicloud/data_source_alicloud_service_catalog_product_as_end_users_test.go
> +func skipTestAccAlicloudServiceCatalogProductAsEndUserDataSource(t *testing.T) {
只有子账号的AK才可以执行，不满足线上测试条件。

2023-01-05 11:42 UTC, merged