New Datasource `alicloud_maxcompute_projects`; resource/alicloud_maxcompute_project: Upgrade to a new version of OpenAPI
aliyun/terraform-provider-alicloud pull request #5783
Opened 2023-01-04 06:55 UTC by xiaosier

New Datasource `alicloud_maxcompute_projects`; resource/alicloud_maxcompute_project: Upgrade to a new version of OpenAPI

2023-01-04 11:11 UTC, xiaozhu36 requested changes

2023-01-04 11:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_maxcompute_project.go
> +				Required: true,
不能直接这样去掉，把 name 标记为Deprecated，然后后面逐渐下线吧

2023-01-04 11:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_maxcompute_project.go
> +							Type:     schema.TypeString,
这个应该是 Int 吧

2023-01-04 11:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_maxcompute_project.go
> -				ValidateFunc: validation.StringInSlice([]string{"PayAsYouGo"}, false),
这个参数如果不再支持，标记为 removed

2023-01-04 11:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_maxcompute_project.go
> +	if d.HasChange("properties") || d.IsNewResource() {
这几个在 create 中已经设置过了，这个地方要判断 !d.IsNewResource()

2023-01-04 11:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_maxcompute_project.go
> +				Type:     schema.TypeString,
这个如果有枚举值的话，写一下

2023-01-04 11:11 UTC, xiaozhu36 commented on website/docs/r/maxcompute_project.html.markdown
> +-> **NOTE:** Available in v1.196.0+.
这是当成一个全新的资源来处理了么？

2023-01-04 11:11 UTC, xiaozhu36 commented on website/docs/r/maxcompute_project.html.markdown
> +* `update` - (Defaults to 5 mins) Used when update the Project.
import 呢

2023-01-04 11:55 UTC, xiaosier commented on alicloud/resource_alicloud_maxcompute_project.go
> +				Required: true,
改为remove了。

2023-01-04 11:55 UTC, xiaosier commented on alicloud/resource_alicloud_maxcompute_project.go
> -				ValidateFunc: validation.StringInSlice([]string{"PayAsYouGo"}, false),
改了。

2023-01-04 11:55 UTC, xiaosier commented on alicloud/resource_alicloud_maxcompute_project.go
> +	if d.HasChange("properties") || d.IsNewResource() {
这里不能这么判断，因为部分需要在update中设置。

2023-01-04 11:56 UTC, xiaosier commented on alicloud/resource_alicloud_maxcompute_project.go
> +				Type:     schema.TypeString,
加了。

2023-01-04 11:56 UTC, xiaosier commented on website/docs/r/maxcompute_project.html.markdown
> +-> **NOTE:** Available in v1.196.0+.
改了。

2023-01-04 11:56 UTC, xiaosier commented on website/docs/r/maxcompute_project.html.markdown
> +* `update` - (Defaults to 5 mins) Used when update the Project.
这个暂时不支持import，他们在处理，完成后再支持。

2023-01-04 15:43 UTC, xiaozhu36 requested changes

2023-01-04 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_maxcompute_project.go
> +				ValidateFunc: validation.StringInSlice([]string{"PAYASYOUGO", "SUBSCRIPTION", "DEV"}, false),
枚举值都统一为大驼峰，比如PayAsYouGo

2023-01-04 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_maxcompute_project.go
> +	if d.HasChange("properties") || d.IsNewResource() {
上面的comment也一样么？

2023-01-04 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_maxcompute_project.go
> +	if d.HasChange("properties") || d.IsNewResource() {
另外，如果是这样，那么  d.IsNewResource() 不需要写

2023-01-04 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_maxcompute_project.go
>  			State: schema.ImportStatePassthrough,
如果不支持import，那么这个Importer 需要去掉

2023-01-05 01:55 UTC, xiaosier commented on alicloud/resource_alicloud_maxcompute_project.go
> +				ValidateFunc: validation.StringInSlice([]string{"PAYASYOUGO", "SUBSCRIPTION", "DEV"}, false),
改了。

2023-01-05 01:55 UTC, xiaosier commented on alicloud/resource_alicloud_maxcompute_project.go
>  			State: schema.ImportStatePassthrough,
去掉了。

2023-01-05 12:18 UTC, merged