New Resource `alicloud_express_connect_vbr_pconn_association`; New Datasource `alicloud_express_connect_vbr_pconn_associations`;
aliyun/terraform-provider-alicloud pull request #5784
Opened 2023-01-04 07:02 UTC by super-eggs

New Resource `alicloud_express_connect_vbr_pconn_association`;
New Datasource `alicloud_express_connect_vbr_pconn_associations`;

2023-01-06 08:39 UTC, MrWolong commented on alicloud/data_source_alicloud_express_connect_vbr_pconn_associations.go
> +	if v, ok := d.GetOk("page_number"); ok && v.(int) > 0 {
可以用common.go文件中的setPagingRequest()

2023-01-06 08:43 UTC, MrWolong commented on alicloud/data_source_alicloud_express_connect_physical_connections.go
> +			"tags": tagsSchema(),
增加了字段，没有在相应的测试文件中增加测试用例啊

2023-01-09 09:41 UTC, xiaozhu36 requested changes

2023-01-09 09:41 UTC, xiaozhu36 commented on website/docs/r/express_connect_vbr_pconn_association.html.markdown
> +$ terraform import alicloud_express_connect_vbr_pconn_association.example <VbrId:PhysicalConnectionId>
`<VbrId>:<PhysicalConnectionId>`

2023-01-09 09:51 UTC, merged