New Datasource data_source_alicloud_instance_keywords ; Query the reserved keywords of an ApsaraDB RDS instance
aliyun/terraform-provider-alicloud pull request #5785
Opened 2023-01-04 08:20 UTC by TingxuanGuo

2023-01-04 09:13 UTC, super-eggs commented on website/docs/d/instance_keywords.html.markdown
> +
`-> **NOTE:** Available in 1.196.0+`

2023-01-04 09:13 UTC, super-eggs commented on website/docs/d/instance_keywords.html.markdown
> +* `key` - (Required) The type of reserved keyword to query. Valid values:
改成： ```Valid values: `account`, `database`.```

2023-01-04 09:13 UTC, super-eggs commented on website/docs/d/instance_keywords.html.markdown
> +
output_file

2023-01-04 09:13 UTC, super-eggs commented on alicloud/data_source_alicloud_instance_keywords.go
> +				Required:     true,
ForceNew

2023-01-05 03:30 UTC, TingxuanGuo commented on website/docs/d/instance_keywords.html.markdown
> +
已增加

2023-01-05 03:30 UTC, TingxuanGuo commented on website/docs/d/instance_keywords.html.markdown
> +* `key` - (Required) The type of reserved keyword to query. Valid values:
已订正

2023-01-05 03:30 UTC, TingxuanGuo commented on website/docs/d/instance_keywords.html.markdown
> +
已添加

2023-01-05 03:31 UTC, TingxuanGuo commented on alicloud/data_source_alicloud_instance_keywords.go
> +				Required:     true,
已添加

2023-01-05 10:32 UTC, super-eggs commented on website/docs/d/instance_keywords.html.markdown
> +* `key` - (Required) The type of reserved keyword to query. Valid values: `account`, `database`.
ForceNew

2023-01-06 03:30 UTC, TingxuanGuo commented on website/docs/d/instance_keywords.html.markdown
> +* `key` - (Required) The type of reserved keyword to query. Valid values: `account`, `database`.
已订正

2023-01-09 01:52 UTC, xiaozhu36 requested changes

2023-01-09 01:52 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_instance_keywords.go
> +							Computed: true,
既然是一个list，看起来不需要 words 这一层啊，直接使用 keywords 就行

2023-01-09 05:36 UTC, TingxuanGuo commented on alicloud/data_source_alicloud_instance_keywords.go
> +							Computed: true,
已修改

2023-01-09 09:42 UTC, xiaozhu36 requested changes

2023-01-09 09:42 UTC, xiaozhu36 commented on website/docs/d/instance_keywords.html.markdown
> +    Operation to query the reserved keywords of an ApsaraDB RDS instance. The reserved keywords cannot be used for the usernames of accounts or the names of databases.
这个地方保留两个空格就行

2023-01-09 10:13 UTC, TingxuanGuo commented on website/docs/d/instance_keywords.html.markdown
> +    Operation to query the reserved keywords of an ApsaraDB RDS instance. The reserved keywords cannot be used for the usernames of accounts or the names of databases.
已订正

2023-01-09 11:05 UTC, merged