resource/alicloud_vpc_ipv4_gateway: Fixes the EnableVpcIpv4Gateway error when creating the resource
aliyun/terraform-provider-alicloud pull request #5790
Opened 2023-01-05 02:38 UTC by thisnihonglei

2023-01-05 03:33 UTC, thisnihonglei commented on alicloud/resource_alicloud_lindorm_instance.go
> +			"service_type": {
增加这个属性是因为用户需要根据ServiceType判断是不是多可用区实例

2023-01-05 06:46 UTC, xiaozhu36 requested changes

2023-01-05 06:46 UTC, xiaozhu36 commented on alicloud/resource_alicloud_lindorm_instance.go
> -				ForceNew:     true,
这个移除了，但是没有看到有修改 disk_category 的新增代码啊

2023-01-05 06:46 UTC, xiaozhu36 commented on website/docs/r/vpn_gateway_vpn_attachment.html.markdown
> +* `customer_gateway_id` - (Required) The ID of the customer gateway.
说清楚从哪个版本开始支持修改

2023-01-05 06:46 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpn_gateway_vpn_attachment.go
>  	if update {
测试用例呢

2023-01-05 08:36 UTC, thisnihonglei commented on alicloud/resource_alicloud_lindorm_instance.go
> -				ForceNew:     true,
该字段指定创建ssd的话，如果有essd资源，优先用essd，用户传入ssd返回essd，所以值不相同，用户这里因为ForceNew会导致摧毁资源重建，所以这里Terraform做兼容，允许该字段变更

2023-01-05 11:35 UTC, xiaozhu36 requested changes

2023-01-05 11:35 UTC, xiaozhu36 commented on website/docs/r/lindorm_instance.html.markdown
> +* `disk_category` - (Required) The disk type of instance. Valid values: `capacity_cloud_storage`, `cloud_efficiency`, `cloud_essd`, `cloud_ssd`, `local_ssd_pro`, `local_hdd_pro`.
不对啊，这个不需要改吧

2023-01-05 11:35 UTC, xiaozhu36 commented on website/docs/r/vpn_gateway_vpn_attachment.html.markdown
> +* `customer_gateway_id` - (Required,  Available in v1.196.0+) The ID of the customer gateway. Latest version supports modifications.
不要用 Latest version，你看看其他的怎么写的

2023-01-06 02:14 UTC, xiaozhu36 requested changes

2023-01-06 02:14 UTC, xiaozhu36 commented on website/docs/r/vpn_gateway_vpn_attachment.html.markdown
> +-> **NOTE:** From version 1.196.0, `customer_gateway_id` can be modified.
这个note直接加在属性描述的后面

2023-01-06 02:26 UTC, merged