New Resource `alicloud_express_connect_virtual_physical_connection`; New Datasource `alicloud_express_connect_virtual_physical_connections`;
aliyun/terraform-provider-alicloud pull request #5793
Opened 2023-01-05 10:08 UTC by super-eggs

New Resource `alicloud_express_connect_virtual_physical_connection`;
New Datasource `alicloud_express_connect_virtual_physical_connections`;

2023-01-06 07:50 UTC, MrWolong commented on alicloud/data_source_alicloud_express_connect_virtual_physical_connections_test.go
> +		"connections.#": "0",
缺少names校验

2023-01-06 07:50 UTC, MrWolong commented on alicloud/data_source_alicloud_express_connect_virtual_physical_connections_test.go
> +		"ids.#":                                            "1",
缺names

2023-01-06 08:03 UTC, MrWolong commented on alicloud/service_alicloud_express_connect.go
> +func (s *ExpressConnectService) ExpressConnectVirtualPhysicalConnectionStateRefreshFunc(d *schema.ResourceData, failStates []string) resource.StateRefreshFunc {
我看创建，删除，更新操作都没用到状态刷新，为什么还要写这个

2023-01-09 03:44 UTC, xiaozhu36 requested changes

2023-01-09 03:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_virtual_physical_connection_test.go
> +	default = "1437805838282454"
这个使用 account的datasource去查

2023-01-09 06:15 UTC, super-eggs commented on alicloud/resource_alicloud_express_connect_virtual_physical_connection_test.go
> +	default = "1437805838282454"
师兄，这个 vpconn_ali_uid 参数要求填一个有效的对方账户id，所以不能使用 account 查询。

2023-01-09 07:33 UTC, super-eggs commented on alicloud/resource_alicloud_express_connect_virtual_physical_connection_test.go
> +	default = "1437805838282454"
已使用 ALICLOUD_EXPRESS_CONNECT_UID 环境变量代替。

2023-01-09 08:19 UTC, merged