New resource alicloud_rds_ddr_db_instance
aliyun/terraform-provider-alicloud pull request #5794
Opened 2023-01-06 06:35 UTC by zcc01029273

2023-01-09 08:42 UTC, super-eggs commented on website/docs/r/rds_ddr_db_instance.html.markdown
> +- When `storage_auto_scale="Enable"`, do not perform `instance_storage` check. when `storage_auto_scale="Disable"`, if the instance itself `instance_storage`has changed. You need to manually revise t
格式

2023-01-09 08:42 UTC, super-eggs commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +				Default:      Postpaid,
去掉 Default， 使用 Computed.
下面也是一样

2023-01-09 08:42 UTC, super-eggs commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +	err = resource.Retry(d.Timeout(schema.TimeoutUpdate), func() *resource.RetryError {
client.GetRetryTimeout(d.Timeout(schema.TimeoutCreate))

2023-01-09 08:42 UTC, super-eggs commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +	stateConf := BuildStateConf([]string{"Creating"}, []string{"Running"}, d.Timeout(schema.TimeoutCreate), 3*time.Minute, rdsService.RdsDBInstanceStateRefreshFunc(d.Id(), []string{"Deleting"}))
Creating 不是终态吧？

2023-01-09 08:42 UTC, super-eggs commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +	stateConf := BuildStateConf([]string{"DBInstanceClassChanging", "DBInstanceNetTypeChanging", "CONFIG_ENCRYPTING", "SSL_MODIFYING"}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 60*time.Seco
这个没必要

2023-01-09 08:42 UTC, super-eggs commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +	if d.HasChange("instance_storage") {
!d.IsNewResource() &&

再检查一下别的参数，如果该参数在创建中存在，那么就需要排除刚刚创建的情况

2023-01-09 08:42 UTC, super-eggs commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +	if d.HasChange("instance_name") {
!d.IsNewResource() &&

2023-01-09 08:44 UTC, super-eggs commented on alicloud/resource_alicloud_rds_ddr_db_instance_test.go
> +					"restore_time":             "2022-12-29T19:08:52Z",
像这种日期，不要写死，改成实时计算获取。

2023-01-10 06:45 UTC, zcc01029273 commented on website/docs/r/rds_ddr_db_instance.html.markdown
> +- When `storage_auto_scale="Enable"`, do not perform `instance_storage` check. when `storage_auto_scale="Disable"`, if the instance itself `instance_storage`has changed. You need to manually revise t
done

2023-01-10 06:46 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +				Default:      Postpaid,
done

2023-01-10 06:46 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +	err = resource.Retry(d.Timeout(schema.TimeoutUpdate), func() *resource.RetryError {
done

2023-01-10 06:46 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +	stateConf := BuildStateConf([]string{"DBInstanceClassChanging", "DBInstanceNetTypeChanging", "CONFIG_ENCRYPTING", "SSL_MODIFYING"}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 60*time.Seco
done

2023-01-10 06:46 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +	if d.HasChange("instance_storage") {
done

2023-01-10 06:46 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +	if d.HasChange("instance_name") {
done

2023-01-10 06:47 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance_test.go
> +					"restore_time":             "2022-12-29T19:08:52Z",
这个也是灾备集无法确定几时生成，无法进行自动化查询，所以自己模拟的自动化test

2023-01-10 07:32 UTC, super-eggs commented on alicloud/resource_alicloud_rds_ddr_db_instance_test.go
> +					"backup_set_id":            "7190112",
这个 id 不能写死，需要通过创建或者查询。

2023-01-10 07:34 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance_test.go
> +					"backup_set_id":            "7190112",
这个也是灾备集无法确定几时生成，无法进行自动化查询，所以自己模拟的自动化test

2023-01-13 07:21 UTC, super-eggs commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +func findKmsRoleArnDdr(client *connectivity.AliyunClient, k string) (string, error) {
放到 service 文件中吧

2023-01-13 07:59 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +func findKmsRoleArnDdr(client *connectivity.AliyunClient, k string) (string, error) {
done

2023-02-02 07:22 UTC, xiaozhu36 requested changes

2023-02-02 07:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +				Required: true,
engine 应该有枚举值吧

2023-02-02 07:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +	action := "CheckCreateDdrDBInstance"
这个为啥要check

2023-02-02 07:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_ddr_db_instance_test.go
> +func SkipTestAccAlicloudRdsDdrDBInstanceMysql(t *testing.T) {
为啥要跳过

2023-02-02 07:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_ddr_db_instance_test.go
> +				ImportStateVerifyIgnore: []string{"force_restart", "restore_type", "backup_set_id"},
如果这几个参数不能返回，那么这个参数不能设置为 forceNew和 Required

2023-02-02 07:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_ddr_db_instance_test.go
> +					"source_db_instance_name":  "rm-bp1xt083q1n1z8pnm",
source region和 instance name 不要写死，应该动态获取

2023-02-02 07:25 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +	action := "CheckCreateDdrDBInstance"
check是为了校验用这个异地灾备集是否可以进行恢复

2023-02-02 07:26 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance_test.go
> +func SkipTestAccAlicloudRdsDdrDBInstanceMysql(t *testing.T) {
跳过是因为实例异地灾备集的生生成时间是未知的，所有后面定期跑的话得跳过

2023-02-02 07:27 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance_test.go
> +					"source_db_instance_name":  "rm-bp1xt083q1n1z8pnm",
因为实例异地灾备集的生生成时间是未知的，所以模拟的进行了自动化测试

2023-02-03 09:54 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +			"instance_charge_type": {
done

2023-02-03 09:54 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance.go
> +				Required: true,
done

2023-02-03 09:54 UTC, zcc01029273 commented on alicloud/provider.go
> +			"alicloud_rds_ddr_db_instance":                resourceAlicloudRdsDdrDBInstance(),
done

2023-02-03 09:54 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_db_instance_test.go
> +				ImportStateVerifyIgnore: []string{"force_restart", "restore_type", "backup_set_id"},
done

2023-02-03 11:37 UTC, xiaozhu36 requested changes

2023-02-03 11:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_ddr_instance.go
> +					return d.Get("engine").(string) != "PostgreSQL" && d.Get("engine").(string) != "MySQL" && d.Get("engine").(string) != "SQLServer"
engine 支持的枚举值跟这个不符

2023-02-03 11:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_ddr_instance.go
> +	request := map[string]interface{}{
这个地方为啥要check

2023-02-03 11:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_ddr_instance.go
> +		log.Printf("[WARN] Cannot destroy Subscription resource: alicloud_db_instance. Terraform will remove this resource from the state file, however resources may remain.")
这个地方应该是 alicloud_ddr_instance 吧

2023-02-03 11:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_ddr_instance_test.go
> +func SkipTestAccAlicloudRdsDdrInstanceMysql(t *testing.T) {
为啥要跳过

2023-02-03 11:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_ddr_instance_test.go
> +				ImportStateVerifyIgnore: []string{"force_restart", "restore_type", "restore_time", "source_region", "source_db_instance_name"},
没有返回的属性，不能设置为 ForceNew 和 Required

2023-02-03 11:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_ddr_instance_test.go
> +					"source_db_instance_name":  "rm-bp11z3hzfl507n5g3",
这两个属性不要写死

2023-02-06 02:37 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_instance_test.go
> +					"source_db_instance_name":  "rm-bp11z3hzfl507n5g3",
done

2023-02-06 02:37 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_instance_test.go
> +				ImportStateVerifyIgnore: []string{"force_restart", "restore_type", "restore_time", "source_region", "source_db_instance_name"},
done

2023-02-06 02:38 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_instance.go
> +		log.Printf("[WARN] Cannot destroy Subscription resource: alicloud_db_instance. Terraform will remove this resource from the state file, however resources may remain.")
done

2023-02-06 02:38 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_instance.go
> +					return d.Get("engine").(string) != "PostgreSQL" && d.Get("engine").(string) != "MySQL" && d.Get("engine").(string) != "SQLServer"
done

2023-02-06 02:38 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_instance.go
> +	request := map[string]interface{}{
check是为了校验备份是否可以进行恢复，避免无效的创建

2023-02-06 02:39 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_ddr_instance_test.go
> +func SkipTestAccAlicloudRdsDdrInstanceMysql(t *testing.T) {
原实例灾备集生成的时间是不确定的，所以线上自动化跑需要跳过

2023-02-07 06:21 UTC, xiaozhu36 requested changes

2023-02-07 06:21 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_ddr_instance.go
> +				ValidateFunc: validation.StringInSlice([]string{string(MySQL), string(SQLServer)}, false),
从后面的代码中看，这个地方应该还有pg 的枚举值吧

2023-02-07 06:21 UTC, merged