Reconfiguration Resource `alicloud_router_interface`;Reconfiguration Datasource `alicloud_router_interfaces`
aliyun/terraform-provider-alicloud pull request #5831
Opened 2023-01-12 07:28 UTC by thisnihonglei

2023-01-12 10:18 UTC, super-eggs commented on alicloud/resource_alicloud_router_interface.go
> +		err = resource.Retry(client.GetRetryTimeout(d.Timeout(schema.TimeoutUpdate)), func() *resource.RetryError {
TimeoutDelete

2023-01-13 02:50 UTC, xiaozhu36 requested changes

2023-01-13 02:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_router_interface.go
> +		Delete: resourceAlicloudExpressConnectRouterInterfaceDelete,
既然这个改了，那么文件名和这个资源的函数名也都统一下

2023-01-13 02:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_router_interface.go
> +			},
这个里面弃用的也一样

2023-01-13 06:36 UTC, xiaozhu36 requested changes

2023-01-13 06:36 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_router_interface.go
> +				Computed: true,
这个应该有枚举值吧

2023-01-13 06:36 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_router_interface.go
> +				Type:     schema.TypeString,
这个也一样

2023-01-13 06:36 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_router_interface.go
> +		return "Subscription"
PayByTraffic 确定对应的是预付费么？这个不对吧

2023-01-13 06:36 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_router_interface_test.go
> +}
支持变更的不止这几个属性，其他的属性呢？
另外，增加一个预付费的测试用例

2023-01-13 06:36 UTC, xiaozhu36 commented on alicloud/resource_alicloud_instance.go
> +	if v, ok := d.GetOkExists("spot_duration"); ok {
这个为啥要改？如果要改，单独放一个PR

2023-01-13 06:36 UTC, xiaozhu36 commented on website/docs/d/router_interfaces.html.markdown
> +-> **DEPRECATED:**  This resource  has been deprecated from version `1.197.0`. Please use new resource [alicloud_express_connect_router_interfaces](https://www.terraform.io/docs/providers/alicloud/d/
这个是datasource，不是 resource

2023-01-13 06:36 UTC, xiaozhu36 commented on website/docs/r/express_connect_router_interface.html.markdown
> +* `payment_type` - (ForceNew,Optional) The payment methods for router interfaces. Valid Values: `PrePaid`, `PostPaid`.
这个枚举值跟schema中的不一致啊

2023-01-13 06:36 UTC, xiaozhu36 commented on website/docs/r/express_connect_router_interface.html.markdown
> +* `status` - The status of the resource. Valid Values: `Idle`, `AcceptingConnecting`, `Connecting`, `Activating`, `Active`, `Modifying`, `Deactivating`, `Inactive`, `Deleting`.
status 不是一个纯出参啊，为啥放到这个地方

2023-01-16 01:59 UTC, thisnihonglei commented on alicloud/resource_alicloud_express_connect_router_interface_test.go
> +}
其他的属性因为资源是vpc-vpc所以不支持健康检查，vpc-vbr才支持。所以这里没办法修改。

2023-01-16 14:56 UTC, xiaozhu36 requested changes

2023-01-16 14:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_router_interface_test.go
> +}
那能不能写一个支持健康检查的测试用例

2023-01-16 14:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_router_interface.go
> +				Type:     schema.TypeInt,
period 支持返回么？如果不支持，不能设置为forceNew

2023-01-16 14:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_router_interface_test.go
> +			},
这两个参数如果不能返回，那么就不应该设置为forceNew

2023-01-17 02:18 UTC, thisnihonglei commented on alicloud/resource_alicloud_express_connect_router_interface_test.go
> +}
这个功能暂时有些问题，API现在没办法支持，先透出参数，近期会上线支持

2023-01-17 02:20 UTC, thisnihonglei commented on website/docs/r/express_connect_router_interface.html.markdown
> +* `opposite_vpc_instance_id` - The opposite vpc instance id of the router on the other side.
这些参数在上面都没有设置过

2023-01-17 14:22 UTC, xiaozhu36 requested changes

2023-01-17 14:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_router_interface_test.go
> +}
如果API有问题，那么相关的参数目前不能透出，等上线了再透出支持

2023-01-30 10:14 UTC, xiaozhu36 requested changes

2023-01-30 10:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_express_connect_router_interface.go
> +				Type:     schema.TypeString,
这个status有枚举值么

2023-01-30 10:14 UTC, xiaozhu36 commented on website/docs/d/express_connect_router_interfaces.html.markdown
> +-> **NOTE:** Available in 1.197.0+
下个版本是 198了

2023-02-14 10:30 UTC, xiaozhu36 requested changes

2023-02-14 10:30 UTC, xiaozhu36 commented on website/docs/r/router_interface_connection.html.markdown
> +-> **DEPRECATED:**  This resource  has been deprecated from version `1.197.0`. Please use new resource [alicloud_express_connect_router_interface](https://www.terraform.io/docs/providers/alicloud/r/a
这个版本号不对吧

2023-02-15 07:10 UTC, merged