resource/alicloud_rds_account : Resets permissions of the privileged account.
aliyun/terraform-provider-alicloud pull request #5836
Opened 2023-01-13 10:12 UTC by TingxuanGuo

2023-01-16 08:22 UTC, xiaozhu36 requested changes

2023-01-16 08:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_account.go
> +	if !d.IsNewResource() && d.Get("reset_permission_flag").(bool) {
这个地方应该用 haschange

2023-01-16 08:33 UTC, TingxuanGuo commented on alicloud/resource_alicloud_rds_account.go
> +	if !d.IsNewResource() && d.Get("reset_permission_flag").(bool) {
这里的逻辑为，当 reset_permission_flag = true 并且 account_type/type = “Super” 时，才触发高权限账号重置权限操作。
若采用 d.HasChange("reset_permission_flag")作为判断条件，当 reset_permission_flag (true -> false)变更是，也会进入if判断。所以这里直接采用传入的 reset_permission_flag 标志作为条件进行判断。

2023-01-17 02:09 UTC, TingxuanGuo commented on alicloud/resource_alicloud_rds_account.go
> +	if !d.IsNewResource() && d.Get("reset_permission_flag").(bool) {
@xiaozhu36 已修改，done

2023-02-02 06:16 UTC, xiaozhu36 requested changes

2023-02-02 06:16 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_account.go
> +				Default:  false,
用 d.GetOkExist来判断

2023-02-02 08:19 UTC, TingxuanGuo commented on alicloud/resource_alicloud_rds_account.go
> +				Default:  false,
@xiaozhu36 done

2023-02-07 06:26 UTC, merged