resource/alicloud_route_entry: Added retry strategy for error code `IncorrectStatus.VpcPeer`,`UnknownError`;resource/alicloud_ecs_network_interface: Added retry strategy for error code `IncorrectVSwitchStatus`;resource/alicloud_instance: Fixed attribute `spot_duration` the bug;
aliyun/terraform-provider-alicloud pull request #5839
Opened 2023-01-16 07:37 UTC by thisnihonglei

2023-01-16 07:38 UTC, thisnihonglei commented on alicloud/resource_alicloud_instance.go
> +	if v, ok := d.GetOkExists("spot_duration"); ok {
这里做改动是因为属性spot_duration传入0值的时候无效

2023-01-16 08:05 UTC, thisnihonglei commented on alicloud/data_source_alicloud_vpc_dhcp_options_sets.go
> -						"associate_vpcs": {
这里删掉这个属性是因为查看了API文档，文档中就没有这个属性，而且之前这个属性也并没有用到，只是在这里定义了放着。缺少AssociateVpcCount属性，已经定义并返回。

2023-01-16 08:28 UTC, xiaozhu36 requested changes

2023-01-16 14:47 UTC, xiaozhu36 requested changes

2023-01-16 14:47 UTC, xiaozhu36 commented on website/docs/r/vswitch.html.markdown
> +
这个示例可以运行通过么？

2023-01-17 02:11 UTC, thisnihonglei commented on website/docs/r/vswitch.html.markdown
> +
![image](https://user-images.githubusercontent.com/28996379/212794635-3ffb8989-54c5-4a5d-81c4-ab1b224fb462.png)

2023-01-18 07:21 UTC, merged