New Datasource `alicloud_dts_instances`; New Resource `alicloud_dts_instance`;
aliyun/terraform-provider-alicloud pull request #5841
Opened 2023-01-17 10:09 UTC by super-eggs

New Datasource `alicloud_dts_instances`;
New Resource `alicloud_dts_instance`;

2023-02-03 07:58 UTC, MrWolong commented on alicloud/data_source_alicloud_dts_instances_test.go
> +func TestAccAlicloudDtsInstanceDataSource(t *testing.T) {
缺少name_regex的测试用例

2023-02-03 07:59 UTC, MrWolong commented on alicloud/data_source_alicloud_dts_instances_test.go
> +		"ids.#":                   "1",
缺少name_regex校验

2023-02-03 08:02 UTC, MrWolong commented on website/docs/d/dts_instances.html.markdown
> +-> **NOTE:** Available in 1.197.0+
-> **NOTE:** Available in 1.198.0+

2023-02-03 08:04 UTC, MrWolong commented on website/docs/d/dts_instances.html.markdown
> +* `resource_group_id` - (ForceNew,Optional) Resource Group ID
缺少name_regex

2023-02-03 08:04 UTC, MrWolong commented on website/docs/r/dts_instance.html.markdown
> +-> **NOTE:** Available in v1.197.0+.
-> NOTE: Available in 1.198.0+

2023-02-03 08:18 UTC, MrWolong commented on alicloud/resource_alicloud_dts_instance.go
> +		},
![image](https://user-images.githubusercontent.com/36806235/216547942-4ffd59c3-3840-44e6-81e9-22677c31cd30.png)

2023-02-03 08:20 UTC, MrWolong commented on alicloud/service_alicloud_dts.go
> +func (s *DtsService) DescribeDtsInstance(id string) (object map[string]interface{}, err error) {
我看这个资源有status属性，不需要状态刷新吗？

2023-02-07 02:33 UTC, super-eggs commented on alicloud/service_alicloud_dts.go
> +func (s *DtsService) DescribeDtsInstance(id string) (object map[string]interface{}, err error) {
AMP 中录入的，Api 均为同步请求

2023-02-07 06:08 UTC, xiaozhu36 requested changes

2023-02-07 06:08 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_dts_instances_test.go
> +  destination_region               = "cn-beijing"
这两个region 不要写死

2023-02-07 06:08 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_instance.go
> +				Type:     schema.TypeBool,
auto_pay 应该作为一个常量，在API调用的时候直接设置为 true

2023-02-07 06:08 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_instance_test.go
> +				ImportStateVerifyIgnore: []string{"compute_unit", "database_count", "used_time", "sync_architecture"},
再检查下，不能返回的属性不能设置为 ForceNew和Required的

2023-02-07 06:08 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dts_subscription_job.go
> +				Required: true,
这种应该属于非兼容变更了

2023-02-07 06:08 UTC, xiaozhu36 commented on website/docs/r/dts_instance.html.markdown
> +# alicloud_dts_instance
有了这个资源，其他的几个dts 的instance是不是可以标记为弃用了

2023-02-07 07:28 UTC, super-eggs commented on website/docs/r/dts_instance.html.markdown
> +# alicloud_dts_instance
done

2023-02-07 07:28 UTC, super-eggs commented on alicloud/data_source_alicloud_dts_instances_test.go
> +  destination_region               = "cn-beijing"
done

2023-02-07 07:28 UTC, super-eggs commented on alicloud/resource_alicloud_dts_subscription_job.go
> +				Required: true,
文档中标记的为 Required，并且文档中也为 Required。所以并不会不兼容。

2023-02-07 09:14 UTC, merged