New Resource `alicloud_nlb_load_balancer_security_group_attachment`
aliyun/terraform-provider-alicloud pull request #5858
Opened 2023-01-30 07:11 UTC by thisnihonglei

2023-01-30 09:26 UTC, super-eggs commented on alicloud/resource_alicloud_nlb_load_balancer_security_group_attachment.go
> +			Delete: schema.DefaultTimeout(1 * time.Minute),
与文档不一致。

2023-01-30 09:26 UTC, super-eggs commented on website/docs/r/nlb_load_balancer_security_group_attachment.html.markdown
> +$terraform import alicloud_nlb_load_balancer_security_group_attachment.example <LoadBalancerId:SecurityGroupId>
改成：`$ terraform import alicloud_nlb_load_balancer_security_group_attachment.example <LoadBalancerId>:<SecurityGroupId>`
这个已经修复了，你拉一下最新的生成器代码吧

2023-01-30 09:26 UTC, super-eggs commented on alicloud/service_alicloud_nlb.go
> +func (s *NlbService) DescribeNlbLoadBalancerSecurityGroupAttachment(id string) (object map[string]interface{}, err error) {
这里的查询，并不能确认 实例与安全组的关联状态吧？

2023-01-31 07:06 UTC, xiaozhu36 requested changes

2023-01-31 07:06 UTC, xiaozhu36 commented on alicloud/resource_alicloud_nlb_load_balancer_security_group_attachment.go
> +				Type:     schema.TypeBool,
属性如果没有返回，那么不应该设置为 ForceNew

2023-01-31 07:06 UTC, xiaozhu36 commented on alicloud/resource_alicloud_nlb_load_balancer_security_group_attachment.go
> +				ForceNew: true,
security_group_id 是 id 的一部分，这个应该设置为 Required

2023-01-31 09:58 UTC, thisnihonglei commented
![image](https://user-images.githubusercontent.com/28996379/215728242-c3b40e55-8fea-4f3c-b4a8-45342f115038.png)

2023-01-31 12:33 UTC, merged