update by common api & support system_disk_encrypted
aliyun/terraform-provider-alicloud pull request #5873
Opened 2023-02-02 02:31 UTC by fuliu-zln

2023-02-02 02:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=5873) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=5873) before we can accept your contribution.<br/><hr/>**张利男** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=5873) it.</sub>

2023-02-07 03:30 UTC, super-eggs commented on alicloud/resource_alicloud_ess_scaling_configuration.go
> +				ForceNew: true,
system_disk_encrypted 如果可以更改，那就不能设置为 ForceNew

2023-02-07 03:30 UTC, super-eggs commented on alicloud/resource_alicloud_ess_scaling_configuration_test.go
> +					"system_disk_encrypted": "false",
这个测试应该不会触发，默认不是 false 吗？

2023-02-07 03:30 UTC, super-eggs commented on website/docs/r/ess_scaling_configuration.html.markdown
> +* `system_disk_encrypted` - (Optional, Available in 1.197.0+) Whether to encrypt the system disk.
1.198.0

2023-02-07 03:30 UTC, super-eggs commented on alicloud/resource_alicloud_ess_scaling_configuration.go
> +		request["Tags"] = strings.TrimSuffix(tags, ",") + "}"
这里可以使用 convertMaptoJsonString()

2023-02-07 03:30 UTC, super-eggs commented on alicloud/resource_alicloud_ess_scaling_configuration.go
> +		_, err = conn.DoRequest(StringPointer(action), nil, StringPointer("POST"), StringPointer("2014-08-28"), StringPointer("AK"), nil, request, &util.RuntimeOptions{})
最好配置一下重试逻辑：
```
wait := incrementalWait(3*time.Second, 3*time.Second)
		err = resource.Retry(client.GetRetryTimeout(d.Timeout(schema.TimeoutUpdate)), func() *resource.RetryError {
			resp, err := conn.DoRequest(StringPointer(action), nil, StringPointer("POST"), StringPointer("2014-08-28"), StringPointer("AK"), nil, request, &util.RuntimeOptions{})
			if err != nil {
				if NeedRetry(err) {
					wait()
					return resource.RetryableError(err)
				}
				return resource.NonRetryableError(err)
			}
			addDebug(action, resp, request)
			return nil
		})
```

2023-02-07 07:28 UTC, fuliu-zln commented on alicloud/resource_alicloud_ess_scaling_configuration.go
> +				ForceNew: true,
done

2023-02-07 07:29 UTC, fuliu-zln commented on alicloud/resource_alicloud_ess_scaling_configuration_test.go
> +					"system_disk_encrypted": "false",
done

2023-02-07 07:37 UTC, fuliu-zln commented on alicloud/resource_alicloud_ess_scaling_configuration.go
> +		request["Tags"] = strings.TrimSuffix(tags, ",") + "}"
done

2023-02-07 07:42 UTC, fuliu-zln commented on alicloud/resource_alicloud_ess_scaling_configuration.go
> +		_, err = conn.DoRequest(StringPointer(action), nil, StringPointer("POST"), StringPointer("2014-08-28"), StringPointer("AK"), nil, request, &util.RuntimeOptions{})
done

2023-02-08 06:36 UTC, super-eggs commented on website/docs/r/ess_scaling_configuration.html.markdown
> +* `system_disk_encrypted` - (Optional, Available in 1.198.0+) Whether to encrypt the system disk.
1.198.0 已经发了，下一个版本 1.199.0

2023-02-09 06:01 UTC, fuliu-zln commented on website/docs/r/ess_scaling_configuration.html.markdown
> +* `system_disk_encrypted` - (Optional, Available in 1.198.0+) Whether to encrypt the system disk.
done

2023-02-14 02:50 UTC, xiaozhu36 requested changes

2023-02-14 02:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_scaling_configuration.go
> +				Default:  false,
这个Default不用写，本身就是默认false

2023-02-14 02:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_scaling_configuration.go
> +			if NeedRetry(err) {
这个NeedRetry 中不包含IncorrectScalingGroupStatus，所以对这个错误码的重试还是需要保留

2023-02-14 02:50 UTC, xiaozhu36 commented on alicloud/service_alicloud_ess.go
> +//************
无用的行直接删掉

2023-02-14 06:51 UTC, fuliu-zln commented on alicloud/resource_alicloud_ess_scaling_configuration.go
> +				Default:  false,
done

2023-02-14 07:02 UTC, fuliu-zln commented on alicloud/resource_alicloud_ess_scaling_configuration.go
> +			if NeedRetry(err) {
done

2023-02-14 09:02 UTC, merged