resource/alicloud_emr_cluster_new: Added new resource alicloud_emr_cl…
aliyun/terraform-provider-alicloud pull request #5892
Opened 2023-02-12 08:54 UTC by qiyinfei

resource/alicloud_emr_cluster_new: Added new resource alicloud_emr_cluster_new which based on EMR's new version openAPI

![image](https://user-images.githubusercontent.com/30532003/218301733-ee8681dd-3a04-4475-9aab-776e54994502.png)

![image](https://user-images.githubusercontent.com/30532003/218301739-2bed7bad-8ac8-46ee-9e31-065737650393.png)

2023-02-15 10:25 UTC, super-eggs commented on alicloud/data_source_alicloud_emrv2_clusters_test.go
> +			"clusters.0.tags.#":            "2",
clusters 中有个参数没校验，检查一下

2023-02-15 10:25 UTC, super-eggs commented on alicloud/data_source_alicloud_emrv2_clusters.go
> +			"tags": tagsSchema(),
没看到 tags 的测试用例

2023-02-15 10:25 UTC, super-eggs commented on alicloud/resource_alicloud_emrv2_cluster.go
> +			"applications": {
必填是需要返回的，不然无法实现资源导入

2023-02-15 10:25 UTC, super-eggs commented on alicloud/resource_alicloud_emrv2_cluster.go
> +			"node_attributes": {
必填不返回

2023-02-15 10:25 UTC, super-eggs commented on alicloud/resource_alicloud_emrv2_cluster_test.go
> +							"zone_id":           "cn-hangzhou-i",
zone_id 不应该写死，在非杭州地区测试应该不行吧

2023-02-15 10:25 UTC, super-eggs commented on alicloud/resource_alicloud_emrv2_cluster.go
> +			"node_groups": {
必填不返回

2023-02-15 10:25 UTC, super-eggs commented on alicloud/resource_alicloud_emrv2_cluster.go
> +		d.SetPartial("host_group")
写错了吧，没有host_group属性

2023-02-15 10:25 UTC, super-eggs commented on alicloud/resource_alicloud_emrv2_cluster.go
> +				Default:      "PayAsYouGo",
不需要配置 Default，配置成 Computed: true,

2023-02-15 10:25 UTC, super-eggs commented on alicloud/resource_alicloud_emrv2_cluster.go
> +			"client_token": {
不需要定义成属性。
request["ClientToken"] = buildClientToken("Api名字")

2023-02-20 02:18 UTC, super-eggs commented on website/docs/r/emrv2_cluster.html.markdown
> +
缺少 `### Timeouts`

2023-02-20 02:18 UTC, super-eggs commented on alicloud/resource_alicloud_emrv2_cluster.go
> +				MinItems: 1,
这个不需要

2023-02-20 02:18 UTC, super-eggs commented on alicloud/resource_alicloud_emrv2_cluster.go
> +			"resource_group_id": {
这个有默认值吗？如果有配置成 Computed = true

2023-02-20 02:18 UTC, super-eggs commented on alicloud/resource_alicloud_emrv2_cluster.go
> +			"applications": {
这个值应该是不可修改的吧？ 可以返回并且不可修改的属性要配置成 ForceNew: true。检查一下其他属性吧

2023-02-20 02:26 UTC, qiyinfei commented on alicloud/resource_alicloud_emrv2_cluster.go
> +			"resource_group_id": {
这个参数没有默认值

2023-02-20 07:48 UTC, xiaozhu36 requested changes

2023-02-20 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_emrv2_cluster.go
> +						"auto_pay_order": {
自动支付不需要对外暴露，直接实现在代码中，并设置为自动支付

2023-02-20 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_emrv2_cluster.go
> +						"auto_pay_order": {
这个也一样

2023-02-20 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_emrv2_cluster.go
> +							Default:      "NoSpot",
默认值去掉，如果客户不设置，但是系统会设置，那么需要将该属性设置为 Computed：true，其他的默认值也类似

2023-02-20 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_emrv2_cluster.go
> +						"v_switch_ids": {
改成 vswitch_ids

2023-02-20 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_emrv2_cluster.go
> +										Type:     schema.TypeInt,
这个count 是干啥的

2023-02-20 07:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_emrv2_cluster_test.go
> +					}),
这个测试里面没有覆盖所有的测试属性和变更逻辑，需要补充

2023-02-20 07:54 UTC, qiyinfei commented on alicloud/resource_alicloud_emrv2_cluster.go
> +										Type:     schema.TypeInt,
这个是EMR集群节点数据盘的块数

2023-02-21 06:05 UTC, xiaozhu36 requested changes

2023-02-21 06:05 UTC, xiaozhu36 commented on alicloud/resource_alicloud_emrv2_cluster_test.go
> +			{
缺少 update 的step

2023-02-21 06:05 UTC, xiaozhu36 commented on alicloud/resource_alicloud_emrv2_cluster_test.go
> +			{
并且对于update阶段，单个step 需要支持对单个属性的测试

2023-02-21 06:05 UTC, xiaozhu36 commented on alicloud/service_alicloud_emr.go
> +		return object, WrapErrorf(Error(GetNotFoundMessage("EmrCluster", id)), NotFoundMsg, AlibabaCloudSdkGoERROR)
这个地方要使用 NotFoundWithResponse 来将response一并输出，以便于在遇到问题时可以快速定位问题

2023-02-21 06:05 UTC, xiaozhu36 commented on website/docs/d/emrv2_clusters.html.markdown
> +# alicloud\_emr\_clusters_new
这个标识不对

2023-02-21 07:45 UTC, merged