polardb support encryption with CMK
aliyun/terraform-provider-alicloud pull request #5899
Opened 2023-02-15 08:04 UTC by mengliux

polardb support encryption with CMK

2023-02-17 08:34 UTC, super-eggs commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"tde_region": {
这个属性没有使用呀？

2023-02-17 09:22 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"tde_region": {
这个参数read有返回的

2023-02-17 09:22 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"tde_region": {
这个参数read有返回的

2023-02-17 09:56 UTC, super-eggs commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"tde_region": {
纯出参？如果是纯出参，为啥要配置 Optional

2023-02-17 10:44 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"tde_region": {
去掉啦

2023-02-21 11:27 UTC, xiaozhu36 requested changes

2023-02-21 11:27 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +		return "", WrapError(Error("The user KMS is not open. Please open it first and then try again."))
这个是啥意思？如果没有开通，有可以自动化开通的办法吗？

2023-02-21 11:27 UTC, xiaozhu36 commented on website/docs/r/polardb_cluster.html.markdown
> +* `encryption_key` - (Optional, Available in 1.199.0+) The ID of the custom key. `encryption_key` cannot be modified after TDE is opened.
下个版本 1.200.0

2023-02-22 02:56 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +		return "", WrapError(Error("The user KMS is not open. Please open it first and then try again."))
如果用户想自定义秘钥，就是查看用户KMS是否开通了，如果 AuthorizationState 为1开通，为0是没有开通，没有开通的话提示需要先开通KMS，可以通过秘钥平台创建秘钥  https://kms.console.aliyun.com/cn-beijing/key/list

2023-02-22 02:57 UTC, mengliux commented on website/docs/r/polardb_cluster.html.markdown
> +* `encryption_key` - (Optional, Available in 1.199.0+) The ID of the custom key. `encryption_key` cannot be modified after TDE is opened.
ok

2023-03-10 02:28 UTC, xiaozhu36 requested changes

2023-03-10 02:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +func getKmsRoleArn(client *connectivity.AliyunClient, d *schema.ResourceData) (string, error) {
这个新增的API如果没有用到，去掉

2023-03-10 02:55 UTC, closed without merging