resource/alicloud_db_instance : Create serverless instance.
aliyun/terraform-provider-alicloud pull request #5911
Opened 2023-02-20 06:32 UTC by TingxuanGuo

#feat: Serverless instance functions
1. Create serverless instance: resource_alicloud_db_instance
2. Update serverless instance, ServerlessConfig params : resource_alicloud_db_instance
3. Query serverless zones: data_source_alicloud_db_zones
4. Query serverless instance classes: data_source_alicloud_db_instance_classes
5. Clone serverless instance: resource_alicloud_rds_clone_db_instance

add by tingxuan.guo 2023-02-20

2023-02-22 10:33 UTC, super-eggs commented on alicloud/resource_alicloud_db_instance.go
> +				Type:     schema.TypeSet,
这里改成 typeList 吧

2023-02-22 10:33 UTC, super-eggs commented on alicloud/resource_alicloud_db_instance_test.go
> +						"serverless_config.#":      "1",
验证一下子属性

2023-02-22 10:33 UTC, super-eggs commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				Type:     schema.TypeSet,
这里也是， TypeList

2023-02-23 05:33 UTC, TingxuanGuo commented on website/docs/r/db_instance.html.markdown
> +* `serverless_config` - (Optional, Available in 1.200.0+) The settings of the serverless instance. This parameter is required when you create a serverless instance.
done

2023-02-23 05:33 UTC, TingxuanGuo commented on website/docs/r/rds_clone_db_instance.html.markdown
> +* `serverless_config` - (Optional, Available in 1.200.0+) The settings of the serverless instance. This parameter is required when you create a serverless instance.
done

2023-02-23 05:33 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_instance.go
> +				Type:     schema.TypeSet,
done

2023-02-23 05:33 UTC, TingxuanGuo commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				Type:     schema.TypeSet,
done

2023-02-23 06:42 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_instance_test.go
> +						"serverless_config.#":      "1",
done

2023-02-23 09:27 UTC, super-eggs commented on alicloud/resource_alicloud_db_instance_test.go
> +	resourceId := "alicloud_db_instance.default"
加上地区限制。

2023-02-24 01:33 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_instance_test.go
> +	resourceId := "alicloud_db_instance.default"
done

2023-02-28 02:33 UTC, xiaozhu36 requested changes

2023-02-28 02:33 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_db_zones.go
> +		request["CommodityCode"] = "rds_serverless_public_cn"
如果是国际站的账号，这个code 应该是啥

2023-02-28 02:33 UTC, xiaozhu36 commented on website/docs/r/db_instance.html.markdown
> +-> **NOTE:** Available in 1.200.0+. This parameter takes effect only when you create an ApsaraDB RDS for MySQL instance.
这个note直接加在参数描述的后面

2023-02-28 02:33 UTC, xiaozhu36 commented on website/docs/r/db_instance.html.markdown
> +-> **NOTE:** Available in 1.200.0+. This parameter takes effect only when you create an ApsaraDB RDS for MySQL instance.
其他的也一样

2023-02-28 02:35 UTC, TingxuanGuo commented on alicloud/data_source_alicloud_db_zones.go
> +		request["CommodityCode"] = "rds_serverless_public_cn"
通过OpenAPI做过数据对比，国际站与国内站使用不同的CommodityCode查询，返回数据一致，无需区分。

2023-02-28 03:09 UTC, TingxuanGuo commented on website/docs/r/db_instance.html.markdown
> +-> **NOTE:** Available in 1.200.0+. This parameter takes effect only when you create an ApsaraDB RDS for MySQL instance.
done

2023-03-02 08:24 UTC, merged