resource/alicloud_eip_address: Adds new attribute `log_project`,`log_store`.
aliyun/terraform-provider-alicloud pull request #5917
Opened 2023-02-21 06:58 UTC by thisnihonglei

2023-02-21 07:00 UTC, thisnihonglei commented on alicloud/resource_alicloud_eip_address.go
> +	if object["Status"] == "ON" {
这里做判断是因为在调用DescribeHighDefinitionMonitorLogAttribute 之前，需要找到调用SetHighDefinitionMonitorLogStatus的请求，HighDefinitionMonitorLogStatus为OFF状态的eip不允许查询

2023-02-21 07:02 UTC, xiaozhu36 requested changes

2023-02-21 07:02 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eip_address.go
> +				Required: true,
非兼容变更

2023-02-21 07:02 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eip_address.go
> +				Required: true,
非兼容变更

2023-02-21 07:41 UTC, xiaozhu36 requested changes

2023-02-21 07:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eip_address.go
>  				Computed: true,
枚举值

2023-02-21 07:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eip_address_test.go
> +					"log_store":   "hdmonitor",
用新建的project

2023-02-21 07:41 UTC, xiaozhu36 commented on website/docs/r/eip_address.html.markdown
> +* `status` - (Optional, Available in v1.199.0+) The status of the EIP. Valid values:  `Associating`: The EIP is being associated. `Unassociating`: The EIP is being disassociated. `InUse`: The EIP is
这个描述跟实际设置的值也不符啊

2023-02-21 07:41 UTC, xiaozhu36 commented on website/docs/r/eip_address.html.markdown
> +* `status` - (Optional, Available in v1.199.0+) The status of the EIP. Valid values:  `Associating`: The EIP is being associated. `Unassociating`: The EIP is being disassociated. `InUse`: The EIP is
这个status表示的是 EIP 的状态，你的这个PR我理解是要标识EIP是否开启高精度秒级监控，这是两回事啊

2023-02-28 09:23 UTC, thisnihonglei commented on alicloud/resource_alicloud_eip_address.go
> +			"high_definition_monitor_log_status": {
这里为了考虑兼容性，新建属性控制是否开启高精度秒级监控

2023-02-28 09:23 UTC, thisnihonglei commented on alicloud/resource_alicloud_eip_address.go
> +	if object["HDMonitorStatus"] == "ON" {
这里做判断是因为在调用DescribeHighDefinitionMonitorLogAttribute 之前需要开启秒级监控，HDMonitorStatus 为OFF状态的eip不允许查询

2023-02-28 13:09 UTC, merged