`resource/alicloud_log_store` add attribute `hot_ttl` and `mode`
aliyun/terraform-provider-alicloud pull request #5923
Opened 2023-02-22 15:36 UTC by panawala

`resource/alicloud_log_store` add attribute `hot_ttl` and `mode`

2023-02-22 15:39 UTC, panawala commented
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLogStore_basic -timeout=300m
=== RUN   TestAccAlicloudLogStore_basic
--- PASS: TestAccAlicloudLogStore_basic (89.75s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  89.848s

2023-02-23 08:34 UTC, xiaozhu36 requested changes

2023-02-23 08:34 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_store.go
> +	}
如果不支持，那么直接将这个属性设置为 ForceNew即可，不需要这行的判断

2023-02-23 08:34 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_store.go
> +		}
如果是这个逻辑的话，HotTTL 应该设置为 Computed，这个就代表了一种默认值

2023-02-27 03:25 UTC, panawala commented on alicloud/resource_alicloud_log_store.go
> +	}
设置为ForceNew可能会造成Logstore删除并重建，这个风险较大，相对来说使用错误提示更安全些

2023-03-17 08:51 UTC, xiaozhu36 requested changes

2023-03-17 08:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_store.go
> +	}
如果出于这个考虑，那么不能在这个地方报错，需要在schema中增加 diff suppress，当出现属性不一致的情况，不允许产生diff，并且需要在文档中增加note说明，该属性不支持修改。

2023-03-20 11:17 UTC, panawala commented on alicloud/resource_alicloud_log_store.go
> +	}
> 如果出于这个考虑，那么不能在这个地方报错，需要在schema中增加 diff suppress，当出现属性不一致的情况，不允许产生diff，并且需要在文档中增加note说明，该属性不支持修改。

done

2023-03-23 03:21 UTC, xiaozhu36 requested changes

2023-03-23 03:21 UTC, xiaozhu36 commented on alicloud/resource_alicloud_log_store.go
> +					return true
1. 如果有默认值，应该设置为Comupted
2. 这个不能直接return true，当old 和 new 都不为空，并且两者不相等的时候，才要return true

2023-03-23 03:58 UTC, panawala commented on alicloud/resource_alicloud_log_store.go
> +					return true
done

2023-03-27 02:15 UTC, merged