resource/alicloud_db_readonly_instance : Read-only instance adaptation pay as you go.
aliyun/terraform-provider-alicloud pull request #5936
Opened 2023-02-28 07:01 UTC by TingxuanGuo

2023-03-02 08:22 UTC, super-eggs commented on alicloud/resource_alicloud_db_readonly_instance.go
> +				Default:      Postpaid,
使用 Computed 来替换 Default。

2023-03-02 08:22 UTC, super-eggs commented on alicloud/resource_alicloud_db_readonly_instance.go
> +			request["UsedTime"] = d.Get("period")
request["UsedTime"] = period

2023-03-02 08:22 UTC, super-eggs commented on alicloud/resource_alicloud_db_readonly_instance.go
> +			"db_instance_storage_type": {
不能修改要加 ForceNew

2023-03-07 08:54 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_readonly_instance.go
> +				Default:      Postpaid,
done

2023-03-07 08:54 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_readonly_instance.go
> +			request["UsedTime"] = d.Get("period")
done

2023-03-07 08:54 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_readonly_instance.go
> +			"db_instance_storage_type": {
已补充，db_instance_storage_type字段修改逻辑

2023-03-07 09:14 UTC, super-eggs commented on alicloud/resource_alicloud_db_readonly_instance.go
> +		if v, ok := d.GetOkExists("instance_type"); ok && v.(string) != "" {
这 3 个地方都改成 GetOk。

2023-03-07 09:23 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_readonly_instance.go
> +		if v, ok := d.GetOkExists("instance_type"); ok && v.(string) != "" {
done

2023-03-08 06:08 UTC, xiaozhu36 requested changes

2023-03-08 06:08 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_readonly_instance.go
> +				Default:      Postpaid,
默认值去掉

2023-03-08 06:08 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_readonly_instance_test.go
> +				),
最后要改成不自动续费

2023-03-08 06:12 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_readonly_instance_test.go
> +				),
自动化测试中，包含包年包月转按量付费，转按量付费后，自动续费会被删除掉。

2023-03-08 06:28 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_readonly_instance.go
> +				Default:      Postpaid,
只读实例原逻辑
1. instance_charge_type 无此字段,OpenAPI这个字段是必传，TF写死的入参为按量付费

因此，客户原先使用时不会关注此字段，存在默认值的话，针对原先组好TF文件的客户，这次改动是无感知的，不会影响他们原先组好的TF文本的使用。
如果改为无默认值，当前评估影响范围。
1. 原先组好TF文件的客户都没有该字段的入参，所有创建只读实例的客户都需要修改TF文件。
2. 所有TF自动化测试的创建只读也需要同步更改，不然创建会SDK报错

2023-03-10 04:03 UTC, merged