New Resource `alicloud_alb_load_balancer_common_bandwidth_package_attachment`;New Datasource `alicloud_alb_load_balancer_common_bandwidth_package_attachments`
aliyun/terraform-provider-alicloud pull request #5937
Opened 2023-02-28 08:51 UTC by thisnihonglei

2023-02-28 09:37 UTC, MrWolong commented on alicloud/data_source_alicloud_alb_load_balancer_common_bandwidth_package_attachments.go
> +	if v, ok := d.GetOk("load_balancer_id"); ok {
load_balancer_id是必填的，不需要判断，直接传值吧

2023-02-28 09:41 UTC, MrWolong commented on alicloud/resource_alicloud_alb_load_balancer_common_bandwidth_package_attachment.go
> +	stateConf := BuildStateConf([]string{}, []string{"Active"}, d.Timeout(schema.TimeoutDelete), 5*time.Second, albService.AlbLoadBalancerCommonBandwidthPackageAttachmentStateRefreshFunc(d.Id(), []strin
销毁之后的终态也是Active吗？

2023-02-28 09:42 UTC, MrWolong commented on website/docs/d/alb_load_balancer_common_bandwidth_package_attachments.html.markdown
> +This data source provides Alb Load Balancer Common Bandwidth Package Attachment available to the user.[What is Load Balancer Common Bandwidth Package Attachment](https://www.alibabacloud.com/help/en/
data source链接有问题

2023-02-28 09:42 UTC, MrWolong commented on website/docs/d/alb_load_balancer_common_bandwidth_package_attachments.html.markdown
> +The following arguments are supported:
缺少一个ids入参的描述

2023-02-28 09:43 UTC, MrWolong commented on website/docs/d/alb_load_balancer_common_bandwidth_package_attachments.html.markdown
> +The following attributes are exported in addition to the arguments listed above:
缺少出参id的描述

2023-02-28 09:44 UTC, MrWolong commented on website/docs/r/alb_load_balancer_common_bandwidth_package_attachment.html.markdown
> +* `dry_run` - (Computed,Optional) Whether to PreCheck this request only. Value:-**true**: sends a check request and does not bind the shared bandwidth package to the load balancing instance. Check it
dry_run字段没有computed啊
![image](https://user-images.githubusercontent.com/36806235/221814991-510b2ea2-fde6-4ab8-847c-fec675edb878.png)

2023-02-28 09:58 UTC, thisnihonglei commented on alicloud/resource_alicloud_alb_load_balancer_common_bandwidth_package_attachment.go
> +	stateConf := BuildStateConf([]string{}, []string{"Active"}, d.Timeout(schema.TimeoutDelete), 5*time.Second, albService.AlbLoadBalancerCommonBandwidthPackageAttachmentStateRefreshFunc(d.Id(), []strin
是的，当负载均衡实例处于Active状态时，表示共享带宽包解除成功

2023-03-01 12:40 UTC, xiaozhu36 requested changes

2023-03-01 12:40 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_alb_load_balancer_common_bandwidth_package_attachments.go
> +func dataSourceAlicloudAlbLoadBalancerCommonBandwidthPackageAttachments() *schema.Resource {
这个attachments 不需要 datasource

2023-03-02 02:59 UTC, merged