resource/alicloud_express_connect_router_interface: Fix a bug where the read function filter was not working;resource/alicloud_havip_attachment: Adds new attribute `instance_type`;resource/alicloud_drds_instance: Adds new attribute `mysql_version`;
aliyun/terraform-provider-alicloud pull request #5951
Opened 2023-03-02 06:51 UTC by thisnihonglei

2023-03-02 06:52 UTC, thisnihonglei commented on alicloud/resource_alicloud_vpc_peer_connection.go
> +				Required: true,
这个是和API文档对齐，文档中该属性是必填。

2023-03-02 08:57 UTC, thisnihonglei commented on alicloud/resource_alicloud_havip_attachment.go
> +			"instance_type": {
只有白名单用户可以操作HaVip资源，所以测试用例没有增加该属性

2023-03-02 09:04 UTC, xiaozhu36 requested changes

2023-03-02 09:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_havip_attachment.go
> +			"instance_type": {
如果是不可改的话，那应该是ForceNew
另外，这个有默认值么

2023-03-02 09:05 UTC, xiaozhu36 requested changes

2023-03-02 09:05 UTC, xiaozhu36 commented on alicloud/resource_alicloud_havip_attachment.go
> +			"instance_type": {
把我们的测试账号让加成白名单，必须得测

2023-03-06 09:21 UTC, thisnihonglei commented on alicloud/resource_alicloud_havip_attachment.go
> +			"instance_type": {
![image](https://user-images.githubusercontent.com/28996379/223068636-2ffa32f6-3b60-4673-9ea8-21d057053d53.png)

2023-03-06 09:29 UTC, thisnihonglei commented on alicloud/resource_alicloud_havip_attachment_test.go
> +func TestAccAlicloudVPCHavipAttachment_basic(t *testing.T) {
![image](https://user-images.githubusercontent.com/28996379/223070273-fa4173cb-8a38-4c66-b566-b1370f38c2d8.png)

2023-03-14 09:44 UTC, thisnihonglei commented on alicloud/resource_alicloud_havip_attachment_test.go
> +func TestAccAlicloudVPCHavipAttachment_basic2(t *testing.T) {
![image](https://user-images.githubusercontent.com/28996379/224961015-4592fc83-da1d-445c-99bb-45da1c0415bc.png)

2023-03-14 10:39 UTC, merged