resource/alicloud_drds_instance: Adds new attribute `mysql_version`
aliyun/terraform-provider-alicloud pull request #5953
Opened 2023-03-02 07:58 UTC by thisnihonglei

2023-03-02 09:06 UTC, xiaozhu36 requested changes

2023-03-02 09:06 UTC, xiaozhu36 commented on alicloud/resource_alicloud_drds_instance.go
> +				ForceNew: true,
运行其他的测试了么？这个有默认值么

2023-03-08 09:16 UTC, thisnihonglei commented on alicloud/resource_alicloud_drds_instance_test.go
> +func TestAccAlicloudDRDSInstance_MySQLVersion(t *testing.T) {
![image](https://user-images.githubusercontent.com/28996379/223672458-ce9afeb4-301b-4ec7-9ab9-0c512712620c.png)

2023-03-08 09:45 UTC, thisnihonglei commented on alicloud/resource_alicloud_drds_instance.go
> +				ForceNew: true,
其他的测试也都跑过了，有默认值

2023-03-08 09:48 UTC, xiaozhu36 requested changes

2023-03-08 09:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_drds_instance.go
> +				ForceNew: true,
如果有默认值，那么其他的case 的check 上要增加上对默认值的检查

2023-03-08 10:16 UTC, thisnihonglei commented on alicloud/resource_alicloud_drds_instance.go
> +				ForceNew: true,
加上了，测试也跑了
![image](https://user-images.githubusercontent.com/28996379/223686171-d85a7f41-8376-4a9c-b943-ecf26e13d9f1.png)

2023-03-09 11:02 UTC, merged