New Resource `alicloud_dcdn_waf_rule`; New Datasource `alicloud_dcdn_waf_rules`;
aliyun/terraform-provider-alicloud pull request #5969
Opened 2023-03-07 09:04 UTC by super-eggs

New Resource `alicloud_dcdn_waf_rule`;
New Datasource `alicloud_dcdn_waf_rules`;

2023-03-09 10:23 UTC, MrWolong commented on alicloud/data_source_alicloud_dcdn_waf_rules.go
> +	//dcdnService := DcdnService{client}
有注释

2023-03-09 10:29 UTC, MrWolong commented on alicloud/data_source_alicloud_dcdn_waf_rules.go
> +						"policy_id": {
policy_id不是string类型，是long
![image](https://user-images.githubusercontent.com/36806235/223997045-1712a919-4604-43eb-9578-e6b9158cdbb5.png)

2023-03-09 10:31 UTC, MrWolong commented on alicloud/data_source_alicloud_dcdn_waf_rules_test.go
> +	idsConf := dataSourceTestAccConfig{
缺少query_args测试用例

2023-03-09 10:40 UTC, MrWolong commented on alicloud/resource_alicloud_dcdn_waf_rule.go
> +			"policy_id": {
类型跟接口文档不一致
![image](https://user-images.githubusercontent.com/36806235/223999786-f0de3325-fa89-407b-8594-89673daf54b8.png)

2023-03-09 11:26 UTC, MrWolong commented on alicloud/service_alicloud_dcdn.go
> +func (s *DcdnService) DcdnWafRuleStateRefreshFunc(id string, failStates []string) resource.StateRefreshFunc {
这个资源并没有用到状态刷新啊

2023-03-09 11:29 UTC, MrWolong commented on website/docs/d/dcdn_waf_rules.html.markdown
> +* `ids` - A list of Waf Rule IDs.
ids本身就是入参

2023-03-09 11:29 UTC, MrWolong commented on alicloud/data_source_alicloud_dcdn_waf_rules.go
> +			"enable_details": {
这个字段在代码中没有用到

2023-03-09 11:29 UTC, MrWolong commented on website/docs/d/dcdn_waf_rules.html.markdown
> +The following arguments are supported:
缺少enable_details描述

2023-03-09 11:31 UTC, MrWolong commented on website/docs/r/dcdn_waf_rule.html.markdown
> +* `cc_status` - (Optional) Specifies whether to enable rate limiting. Valid values: on and off. **NOTE:** This parameter is required when policy is of type `custom_acl`.
Valid values: `on` and `off`.

2023-03-09 11:32 UTC, MrWolong commented on website/docs/r/dcdn_waf_rule.html.markdown
> +* `effect` - (Optional) The effective scope of the rate limiting blacklist. If you set ccStatus to on, you must configure this parameter. Valid values: rule (takes effect for the current rule) and se
Valid values: `rule` and `service`.

2023-03-09 11:34 UTC, MrWolong commented on website/docs/r/dcdn_waf_rule.html.markdown
> +* `key` - (Optional) The match field.
![image](https://user-images.githubusercontent.com/36806235/224011367-78d8dca3-eee3-4e5a-bb38-79d64ad6aa58.png)

2023-03-09 11:36 UTC, MrWolong commented on website/docs/r/dcdn_waf_rule.html.markdown
> +#### Block Status
没有字段有这个block
![image](https://user-images.githubusercontent.com/36806235/224011704-761a37da-ccb0-4200-92e0-55de16f8e84e.png)

2023-03-09 11:57 UTC, xiaozhu36 requested changes

2023-03-09 11:57 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_dcdn_waf_rules.go
> +			"enable_details": {
没有用到就去掉

2023-03-09 11:57 UTC, xiaozhu36 commented on alicloud/service_alicloud_dcdn.go
> +func (s *DcdnService) DcdnWafRuleStateRefreshFunc(id string, failStates []string) resource.StateRefreshFunc {
没有用到就删除掉

2023-03-10 01:46 UTC, super-eggs commented on website/docs/r/dcdn_waf_rule.html.markdown
> +#### Block Status
需要搜索 `Block Status`，而不是 `#### Block Status`

2023-03-10 03:57 UTC, xiaozhu36 requested changes

2023-03-10 03:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dcdn_waf_rule_test.go
> +					"rule_name":   "ip_blacklist",
这个rule name 为啥不是变量

2023-03-10 03:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dcdn_waf_rule_test.go
> +					"policy_id":     "${alicloud_dcdn_waf_policy.default.id}",
还有这个

2023-03-10 07:15 UTC, merged