resource/alicloud_security_group_rule: Changed sdk to common api
aliyun/terraform-provider-alicloud pull request #5988
Opened 2023-03-14 07:52 UTC by MrWolong

2023-03-19 03:29 UTC, MrWolong commented on alicloud/resource_alicloud_security_group_rule_test.go
> +func TestAccAlicloudECSSecurityGroupEgressRuleOtherIpv6(t *testing.T) {
由于末尾/0的ipv6_cidr_ip使用旧版SDK会bug，查询只返回::/0，所以增加了两个新的单测，用来测试调用common api，传递末尾/0的ipv6_cidr_ip是否可以正常返回期望值

2023-03-21 01:32 UTC, MrWolong commented on alicloud/resource_alicloud_security_group_rule.go
> +	ecsService := EcsService{client}
alicloud_security_group_rule涉及到的接口，目前只有create操作中的两个接口有改动，其他的操作涉及到的接口都与sdk一致

2023-03-24 16:23 UTC, xiaozhu36 requested changes

2023-03-24 16:23 UTC, xiaozhu36 commented on alicloud/resource_alicloud_security_group_rule.go
> +	if !cidrIpExist && !ipv6CidrIpExist && !sourceSecurityGroupIdExist && !prefixListIdExist {
这个判断条件可以直接在schema中用 AtLeastOneOf 来实现

2023-03-27 01:46 UTC, MrWolong commented on alicloud/resource_alicloud_security_group_rule.go
> +	if !cidrIpExist && !ipv6CidrIpExist && !sourceSecurityGroupIdExist && !prefixListIdExist {
已修复

2023-03-27 06:17 UTC, merged