resource/alicloud_polardb_cluster: polardb support cluster category SENormal
aliyun/terraform-provider-alicloud pull request #6000
Opened 2023-03-16 03:28 UTC by mengliux

resource/alicloud_polardb_cluster: polardb support cluster category SENormal

2023-03-17 02:44 UTC, super-eggs commented on alicloud/resource_alicloud_polardb_cluster.go
> +	wait := incrementalWait(2*time.Second, 0*time.Second)
wait := incrementalWait(3*time.Second, 3*time.Second)

2023-03-17 02:44 UTC, super-eggs commented on alicloud/resource_alicloud_polardb_cluster.go
> +	err = resource.Retry(d.Timeout(schema.TimeoutCreate), func() *resource.RetryError {
client.GetRetryTimeout(d.Timeout(schema.TimeoutCreate))

2023-03-17 02:44 UTC, super-eggs commented on alicloud/resource_alicloud_polardb_cluster.go
> +	d.SetId(response["DBClusterId"].(string))
fmt.Sprint(response["DBClusterId"])

2023-03-17 02:44 UTC, super-eggs commented on alicloud/resource_alicloud_polardb_cluster.go
> +		resultStorageSpace, _ := clusterInfo["StorageSpace"].(json.Number).Int64()
formatInt()

2023-03-17 02:44 UTC, super-eggs commented on alicloud/resource_alicloud_polardb_cluster.go
> +				} else {
这个 else 就没用了吧？

2023-03-17 02:44 UTC, super-eggs commented on alicloud/resource_alicloud_polardb_cluster.go
> +func convertPolarDBStorageTypeDescribeRequest(source string) string {
都匹配不上，应该直接返回 source

2023-03-17 02:44 UTC, super-eggs commented on alicloud/resource_alicloud_polardb_cluster.go
> +				Optional:     true,
不可修改吧？ ForceNew

2023-03-17 02:44 UTC, super-eggs commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"storage_space": {
ForceNew

2023-03-17 02:44 UTC, super-eggs commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +				ImportStateVerifyIgnore: []string{"modify_type", "hot_standby_cluster"},
为啥要忽略 hot_standby_cluster 呢？

2023-03-17 02:44 UTC, super-eggs commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"hot_standby_cluster": {
ForceNew

2023-03-17 02:49 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +				ImportStateVerifyIgnore: []string{"modify_type", "hot_standby_cluster"},
因为只有入参，没有接口可以查到

2023-03-17 02:56 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"hot_standby_cluster": {
ok

2023-03-17 02:56 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"storage_space": {
ok

2023-03-17 02:58 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +				Optional:     true,
ok

2023-03-17 03:47 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +		resultStorageSpace, _ := clusterInfo["StorageSpace"].(json.Number).Int64()
经过沟通，返参范围在10G-32000G，GB与byte转化大于10位数字，所以继续用 Int64()

2023-03-17 03:47 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +		resultStorageSpace, _ := clusterInfo["StorageSpace"].(json.Number).Int64()
![image](https://user-images.githubusercontent.com/82444619/225807866-33e3388b-95fc-49dc-bfc6-e9efd476ef72.png)

2023-03-17 03:56 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +func convertPolarDBStorageTypeDescribeRequest(source string) string {
ok

2023-03-17 07:23 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"hot_standby_cluster": {
沟通后因为无返回值已去掉。

2023-03-23 03:02 UTC, xiaozhu36 requested changes

2023-03-23 03:02 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +			},
新增的三个属性中，有两个是可以修改的，这个要在测试case上体现出来

2023-03-24 02:42 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +			},
已沟通暂时不支持，已增加forcenew

2023-03-31 02:19 UTC, xiaozhu36 requested changes

2023-03-31 02:19 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +		vpc_id = "vpc-uf66as8kuoklao1e3qfbn"
zone_id 和 vpc_id 不要写死，这个地方应该保持原状

2023-03-31 02:41 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +		vpc_id = "vpc-uf66as8kuoklao1e3qfbn"
已改回原样

2023-04-03 10:33 UTC, xiaozhu36 requested changes

2023-04-03 10:33 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_polardb_node_classes.go
> +				for _, availableResource := range supportedEngine.AvailableResources {
这个地方为啥要区分 mysql

2023-04-04 01:43 UTC, mengliux commented on alicloud/data_source_alicloud_polardb_node_classes.go
> +				for _, availableResource := range supportedEngine.AvailableResources {
为了兼容集成测试方法 TestAccAlicloudPolarDBClusterUpdate

2023-04-04 01:43 UTC, mengliux commented on alicloud/data_source_alicloud_polardb_node_classes.go
> +				}
为了兼容集成测试方法 TestAccAlicloudPolarDBClusterUpdate

2023-04-04 01:43 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					"db_node_class":     "polar.mysql.mmx4.xlarge",
这个动态获取不到

2023-04-07 10:27 UTC, mengliux commented on alicloud/data_source_alicloud_polardb_node_classes.go
> +				for _, availableResource := range supportedEngine.AvailableResources {
修改撤回了

2023-04-07 10:27 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					"db_node_class":     "polar.mysql.mmx4.xlarge",
修改撤回

2023-04-07 10:27 UTC, mengliux commented on alicloud/data_source_alicloud_polardb_node_classes.go
> +				}
修改撤回

2023-04-11 15:11 UTC, xiaozhu36 requested changes

2023-04-11 15:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +		return WrapErrorf(err, DefaultErrorMsg, d.Id(), action, AlibabaCloudSdkGoERROR)
这个时候 d.Id 是空，不应该改

2023-04-11 15:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					"db_node_class":       "polar.mysql.x4.medium.c",
这个 db_node_class 应该用data source 查询到的

2023-04-13 07:22 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +		return WrapErrorf(err, DefaultErrorMsg, d.Id(), action, AlibabaCloudSdkGoERROR)
好的

2023-04-13 07:22 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					"db_node_class":       "polar.mysql.x4.medium.c",
ok

2023-04-13 12:07 UTC, merged