resource/alicloud_cloud_connect_network_grant: Fixed the panic error caused by `cen_uid` type
aliyun/terraform-provider-alicloud pull request #6011
Opened 2023-03-17 09:47 UTC by MrWolong

2023-03-17 09:48 UTC, MrWolong commented on alicloud/resource_alicloud_cloud_connect_network_grant.go
> +				Type:     schema.TypeInt,
sdk中的类型是int，不是string

2023-03-17 09:48 UTC, xiaozhu36 requested changes

2023-03-17 09:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cloud_connect_network_grant.go
>  				Required: true,
不兼容变更

2023-03-18 17:04 UTC, MrWolong commented on alicloud/resource_alicloud_cloud_connect_network_grant.go
>  				Required: true,
已修复

2023-03-19 09:02 UTC, merged