New Resource `alicloud_compute_nest_service_instance`; New Datasource `alicloud_compute_nest_service_instances`
aliyun/terraform-provider-alicloud pull request #6015
Opened 2023-03-22 03:16 UTC by MrWolong

2023-04-26 08:29 UTC, MrWolong commented on alicloud/resource_alicloud_compute_nest_service_instance_test.go
> +					"service_id":             "service-0a15dbf13e4049daaf66",
目前云产品没有提供对外发布的接口用于查询service，只能明文

2023-04-26 09:05 UTC, xiaozhu36 requested changes

2023-04-26 09:05 UTC, xiaozhu36 commented on alicloud/resource_alicloud_compute_nest_service_instance_test.go
> +				ImportStateVerifyIgnore: []string{"resource_group_id", "parameters"},
资源组ID是资源组的属性，这个必须得返回

2023-05-08 09:18 UTC, MrWolong commented on alicloud/resource_alicloud_compute_nest_service_instance_test.go
> +				ImportStateVerifyIgnore: []string{"resource_group_id", "parameters"},
已修复

2023-05-08 09:18 UTC, MrWolong commented on alicloud/resource_alicloud_compute_nest_service_instance.go
> +		if NotFoundError(err) {
已修复

2023-05-09 01:58 UTC, xiaozhu36 requested changes

2023-05-09 01:58 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_compute_nest_service_instances_test.go
> +    		operation_end_time   = "1681367579000"
这个时间戳表示的时间是什么时候，如果运行测试的时间不在这个时间段，会怎么样

2023-05-09 01:58 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_compute_nest_service_instances_test.go
> +  		service_id        = "service-dd475e6e468348799f0f"
这个service id 为啥是写死的

2023-05-09 01:58 UTC, xiaozhu36 commented on alicloud/resource_alicloud_compute_nest_service_instance.go
> +			"pay_type": {
这个是自动生成的么？如果是自动生成的，那么应该是 payment_type

2023-05-09 02:39 UTC, MrWolong commented on alicloud/resource_alicloud_compute_nest_service_instance.go
> +			"pay_type": {
这个自动生成的拼写有问题，paymeny_type，我这边让云产品他们改一下

2023-05-12 06:39 UTC, MrWolong commented on alicloud/data_source_alicloud_compute_nest_service_instances_test.go
> +    		operation_end_time   = "1681367579000"
operation_start_time是2023-04-12T06:32:59Z，operation_end_time是2023-04-13T06:32:59Z，不在这个时间段也不影响，可以正常创建，这个时间段是用户期望的代运维时间

2023-05-12 06:42 UTC, MrWolong commented on alicloud/data_source_alicloud_compute_nest_service_instances_test.go
> +  		service_id        = "service-dd475e6e468348799f0f"
目前云产品没有提供对外发布的接口用于创建，查询service，所以只能明文。serviceId代表这个每个计算巢的服务，需要服务商来进行创建，而不是用户，云产品提供的这几个都是用于测试的。

2023-05-18 02:38 UTC, xiaozhu36 requested changes

2023-05-18 02:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_compute_nest_service_instance.go
> +			"name": {
这个应该定义为 service_instance_name

2023-05-18 02:38 UTC, xiaozhu36 commented on website/docs/d/compute_nest_service_instances.html.markdown
> +* `name` - (Optional, ForceNew) The name of the filter. Valid Values: `*Name*`, `ServiceInstanceName`, `ServiceInstanceId`, `ServiceId`, `Version`, `Status`, `DeployType`, `ServiceType`, `OperationSt
Name前后为啥要*号

2023-05-18 05:17 UTC, MrWolong commented on website/docs/d/compute_nest_service_instances.html.markdown
> +* `name` - (Optional, ForceNew) The name of the filter. Valid Values: `*Name*`, `ServiceInstanceName`, `ServiceInstanceId`, `ServiceId`, `Version`, `Status`, `DeployType`, `ServiceType`, `OperationSt
已修复

2023-05-18 05:17 UTC, MrWolong commented on alicloud/resource_alicloud_compute_nest_service_instance.go
> +			"name": {
已修复

2023-05-18 06:10 UTC, xiaozhu36 approved these changes

2023-05-18 08:07 UTC, xiaozhu36 approved these changes

2023-05-18 08:35 UTC, xiaozhu36 approved these changes

2023-05-18 08:47 UTC, closed without merging