New Datasource `alicloud_eflo_subnets`; New Resource `alicloud_eflo_subnet`;
aliyun/terraform-provider-alicloud pull request #6019
Opened 2023-03-23 10:06 UTC by super-eggs

New Datasource `alicloud_eflo_subnets`;
New Resource `alicloud_eflo_subnet`;

2023-04-19 17:10 UTC, xiaozhu36 requested changes

2023-04-19 17:10 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eflo_subnet_test.go
> +					"type":        "OOB",
type 是可选的，在第一步中不需要设置；cidr 也一样

2023-04-20 08:39 UTC, super-eggs commented on alicloud/resource_alicloud_eflo_subnet.go
> +	if d.HasChange("subnet_name") {
已修正

2023-04-21 02:58 UTC, xiaozhu36 requested changes

2023-04-21 02:58 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eflo_subnet.go
> +		if IsExpectedErrors(err, []string{"1003"}) || NotFoundError(err) {
错误码不规范

2023-04-23 08:45 UTC, super-eggs commented on alicloud/resource_alicloud_eflo_subnet.go
> +		if IsExpectedErrors(err, []string{"1003"}) || NotFoundError(err) {
done

2023-04-26 11:37 UTC, xiaozhu36 approved these changes

2023-04-27 09:40 UTC, xiaozhu36 approved these changes

2023-04-28 01:42 UTC, xiaozhu36 approved these changes

2023-04-28 02:20 UTC, merged