resource_alicloud_havip: Add new features
aliyun/terraform-provider-alicloud pull request #6053
Opened 2023-04-06 02:00 UTC by ChenHanZhang

2023-04-06 07:18 UTC, ChenHanZhang commented
这个pr不要merge哈

2023-04-07 02:38 UTC, xiaozhu36 requested changes

2023-04-07 02:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_havip.go
>  			},
description的这个限制去掉了？

2023-04-07 02:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_havip.go
> +				Deprecated:    "Field 'havip_name' has been deprecated from provider version 1.201.3. New field 'ha_vip_name' instead.",
下个版本是 1.203.0

2023-04-07 02:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_havip.go
>  				wait()
Throttling 本身就在 NeedRetry 中
OperationFailed.Throttling 如果也是流控，那么应该统一到 NeedRetry 中

2023-04-07 02:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_havip.go
>  		if NotFoundError(err) {
以后所有的资源中，read 这个地方需要改成 if !d.IsNewResource() && NotFoundError(err)

2023-04-07 02:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_havip.go
> +	d.Set("havip_name", d.Get("ha_vip_name"))
havip_name 的处理逻辑应该跟 新的保持一致

2023-04-07 02:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_havip.go
> +			}
这段代码存在的意义是啥

2023-04-07 02:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_havip.go
> +	if d.HasChange("tags") {
tags 的update，每个云产品的service中都会有一个公共的，可以直接用，而不用每个都单独生成： SetResourceTags

2023-04-07 02:38 UTC, xiaozhu36 commented on alicloud/service_alicloud_vpc_v2.go
> +	object0, err := s.describeVpcHavipDescribeHaVipsApi(id)
为啥要用单独的一个方法来获取

2023-04-07 02:38 UTC, xiaozhu36 commented on website/docs/d/havips.html.markdown
> +# alicloud_vpc_havips
provider中注册的 alicloud_havips , 不是 alicloud_vpc_havips

2023-04-10 01:55 UTC, ChenHanZhang commented on alicloud/resource_alicloud_havip.go
>  			},
资源定义上已经去掉这个限制了

2023-04-10 02:02 UTC, ChenHanZhang commented on alicloud/resource_alicloud_havip.go
> +				Deprecated:    "Field 'havip_name' has been deprecated from provider version 1.201.3. New field 'ha_vip_name' instead.",
已修复，这里将自动获取最新的下一版本填入

2023-04-10 02:44 UTC, ChenHanZhang commented on website/docs/d/havips.html.markdown
> +# alicloud_vpc_havips
已修复，将从映射表中取存量的Terraform命名

2023-04-10 02:58 UTC, ChenHanZhang commented on alicloud/resource_alicloud_havip.go
>  				wait()
这里直接取的CloudSpec中定义的错误码。生成的时候逻辑会调整：对于已知的流控错误码将过滤掉。OperationFailed.Throttling 将添加到needretry中

2023-04-10 03:18 UTC, ChenHanZhang commented on alicloud/service_alicloud_vpc_v2.go
> +	object0, err := s.describeVpcHavipDescribeHaVipsApi(id)
这里是为了命名规范，给定一个产品和资源，可以知道在service中的方法名。至于封装api的方式，是为了多get api并存的时候可以进行编排，不同api的“资源不存在”、“重试”等错误码可能不同，因此按api的调用方式将这些api中的逻辑封装到各自函数中好些

2023-04-10 03:19 UTC, ChenHanZhang commented on alicloud/resource_alicloud_havip.go
>  		if NotFoundError(err) {
为什么需要加 IsNewResource ？

2023-04-10 03:28 UTC, ChenHanZhang commented on alicloud/resource_alicloud_havip.go
> +			}
这里的判定是多余的，已去掉

2023-04-13 05:03 UTC, ChenHanZhang commented on alicloud/resource_alicloud_havip.go
> +	if d.HasChange("tags") {
已支持同一产品的tag函数统一生成，这里会进行调整

2023-04-13 05:13 UTC, ChenHanZhang commented on alicloud/resource_alicloud_havip.go
>  		if NotFoundError(err) {
已修复

2023-04-13 05:17 UTC, ChenHanZhang commented on alicloud/resource_alicloud_havip.go
> +	d.Set("havip_name", d.Get("ha_vip_name"))
havip_name 是 ha_vip_name 的别名，旧的字段。这里处理时有单独的逻辑，因为同标准属性字段等价，标准属性在前边的处理时可能会做些转换，这里直接取对应的标准属性字段值就好了，这样不用多次转换

2023-04-26 02:03 UTC, closed without merging