New Resource `alicloud_rds_db_instance_endpoint`
aliyun/terraform-provider-alicloud pull request #6056
Opened 2023-04-07 02:53 UTC by zcc01029273

2023-04-07 16:01 UTC, xiaozhu36 requested changes

2023-04-10 06:18 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_instance_endpoint.go
> +	if _, err := stateConf.WaitForState(); err != nil {
done

2023-04-10 06:18 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_instance_endpoint.go
> +	if _, err := stateConf.WaitForState(); err != nil {
done

2023-04-10 06:20 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_instance_endpoint_test.go
> +resource "alicloud_vswitch" "default" {
这个创建的vpc和vswitch是为了给修改vpc和vswitch用的，因为查询的时候不确定某个vpc下有这个zone的vswtich

2023-04-11 15:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_db_instance_endpoint.go
> +		return WrapError(endpointErr)
这个地方需要判断是否是新资源，同时是否为notfound error：

	if err != nil {
		if !d.IsNewResource() && NotFoundError(err) {
			log.Printf("[DEBUG] Resource alicloud_rds_db_instance rdsService.DescribeDBInstanceEndpoints Failed!!! %s", err)
			d.SetId("")
			return nil
		}
		return WrapError(err)
	}

2023-04-12 03:12 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_instance_endpoint.go
> +		return WrapError(endpointErr)
done

2023-04-13 02:32 UTC, merged