New Resource alicloud_tag_policy_attachment
aliyun/terraform-provider-alicloud pull request #6071
Opened 2023-04-12 05:31 UTC by fuliu-zln

2023-04-12 05:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6071) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6071) before we can accept your contribution.<br/><hr/>**张利男** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=6071) it.</sub>

2023-04-12 09:26 UTC, MrWolong commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +		Create: resourceAlicloudTagAttachmentCreate,
改一下

2023-04-12 09:29 UTC, MrWolong commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +	d.SetId(fmt.Sprintf("%v:%v:%v", request["PolicyId"], request["TargetId"], request["TargetType"]))
既然都set到Id里了，涉及到的字段都必须设置成必填

2023-04-12 09:39 UTC, MrWolong commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +		Create: resourceAlicloudTagAttachmentCreate,
![image](https://user-images.githubusercontent.com/36806235/231418380-47cc9289-17e3-41a8-9ac0-68cb5ceb4cbe.png)
改

2023-04-12 09:45 UTC, MrWolong commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +	for _, v := range object.([]interface{}) {
这块逻辑放在service里面，具体参考service_alicloud_cbn.go文件中的DescribeCenTransitRouterMulticastDomainAssociation和resource_alicloud_cen_transit_router_multicast_domain_association.go文件中的resourceAlicloudCenTransitRouterMulticastDomainAssociationRead

2023-04-12 09:55 UTC, MrWolong commented on website/docs/r/tag_policy_attachment.html.markdown
> +see [What is Attach Policy](https://www.alibabacloud.com/help/en/resource-management/latest/attach-policy).
Policy Attachment

2023-04-12 09:56 UTC, MrWolong commented on website/docs/r/tag_policy_attachment.html.markdown
> +  policy_id   = "p-de62a0bf400e4b69****"
policy_id哪个资源可以创建，example写详细点

2023-04-12 10:00 UTC, MrWolong commented on website/docs/r/tag_policy_attachment.html.markdown
> +Tag Policy Attachment can be imported using the id, e.g.
shell命令呢？

2023-04-12 10:00 UTC, MrWolong commented on website/docs/r/tag_policy_attachment.html.markdown
> +  policy_id   = "p-de62a0bf400e4b69****"
policy_id哪个资源可以创建，example写详细点

2023-04-12 10:08 UTC, MrWolong commented on alicloud/resource_alicloud_tag_policy_attachment_test.go
> +						"target_id":   "1619897336813314",
"target_id":   CHECKSET

2023-04-13 08:39 UTC, fuliu-zln commented on website/docs/r/tag_policy_attachment.html.markdown
> +* `id` - This ID of this resource. It is formatted to `<policy_Id>`:`<target_Id>`:`<target_type>`.
done

2023-04-13 08:39 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_policy_attachment_test.go
> +						"target_id":   "1619897336813314",
done

2023-04-13 08:39 UTC, fuliu-zln commented on alicloud/service_alicloud_tag.go
> +func (s *TagService) DescribeTagPolicyAttachment(id string) (object interface{}, err error) {
done

2023-04-13 08:40 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_policy_attachment_test.go
> +					"target_id":   "1619897336813314",
done

2023-04-13 08:40 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +	for _, v := range object.([]interface{}) {
done

2023-04-13 08:40 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +	d.SetId(fmt.Sprintf("%v:%v:%v", request["PolicyId"], request["TargetId"], request["TargetType"]))
done

2023-04-13 08:48 UTC, fuliu-zln commented on website/docs/r/tag_policy_attachment.html.markdown
> +  policy_id   = "p-de62a0bf400e4b69****"
done

2023-04-13 08:52 UTC, fuliu-zln commented on website/docs/r/tag_policy_attachment.html.markdown
> +Tag Policy Attachment can be imported using the id, e.g.
done

2023-04-13 08:55 UTC, fuliu-zln commented on website/docs/r/tag_policy_attachment.html.markdown
> +see [What is Attach Policy](https://www.alibabacloud.com/help/en/resource-management/latest/attach-policy).
done

2023-04-13 09:34 UTC, MrWolong commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +	if v, ok := d.GetOk("target_type"); ok {
既然是必填的，直接request[""] = d.Get("")

2023-04-13 09:35 UTC, MrWolong commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +			"target_type": {
不可改加ForceNew

2023-04-13 09:51 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +			"target_type": {
done

2023-04-13 10:25 UTC, MrWolong commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +			"target_id": {
target_id可改吗？

2023-04-13 10:25 UTC, MrWolong commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +	err = resource.Retry(client.GetRetryTimeout(d.Timeout(schema.TimeoutUpdate)), func() *resource.RetryError {
![image](https://user-images.githubusercontent.com/36806235/231731342-5e5fe0ac-1782-468d-89cd-2e885c2b3a78.png)

2023-04-13 10:26 UTC, MrWolong commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +	err = resource.Retry(d.Timeout(schema.TimeoutDelete), func() *resource.RetryError {
err = resource.Retry(client.GetRetryTimeout(

2023-04-13 10:27 UTC, MrWolong commented on website/docs/r/tag_policy_attachment.html.markdown
> +* `target_id` - (Required) The ID of the tag policy.
改

2023-04-13 11:04 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +			"target_id": {
不可修改 且这个[resource_alicloud_tag_policy_attachment.go] 是没有更新操作

2023-04-13 11:06 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +	err = resource.Retry(client.GetRetryTimeout(d.Timeout(schema.TimeoutUpdate)), func() *resource.RetryError {
OK 已经修改成schema.TimeoutCreate了

2023-04-13 11:10 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +	err = resource.Retry(d.Timeout(schema.TimeoutDelete), func() *resource.RetryError {
done

2023-04-14 01:29 UTC, MrWolong commented on alicloud/resource_alicloud_tag_policy_attachment.go
> +			"target_id": {
![Uploading image.png…]()

2023-04-14 01:31 UTC, MrWolong commented on website/docs/r/tag_policy_attachment.html.markdown
> +* `policy_id` - (Required) The ID of the tag policy.
你字段定义的是啥属性，就要加啥，只有Required吗？

2023-04-14 02:36 UTC, fuliu-zln commented on website/docs/r/tag_policy_attachment.html.markdown
> +* `policy_id` - (Required) The ID of the tag policy.
三个属性均已加上ForceNew

2023-04-14 03:00 UTC, MrWolong commented on alicloud/service_alicloud_tag.go
> +		return object, WrapErrorf(Error(GetNotFoundMessage("TagPolicy:ListTargetsForPolicy", id)), NotFoundWithResponse, response)
Tag:PolicyAttachment

2023-04-14 03:01 UTC, MrWolong commented on alicloud/service_alicloud_tag.go
> +		return object, WrapErrorf(Error(GetNotFoundMessage("TagPolicy:ListTargetsForPolicy", id)), NotFoundWithResponse, response)
Tag:PolicyAttachment

2023-04-14 03:14 UTC, fuliu-zln commented on alicloud/service_alicloud_tag.go
> +		return object, WrapErrorf(Error(GetNotFoundMessage("TagPolicy:ListTargetsForPolicy", id)), NotFoundWithResponse, response)
done

2023-04-14 03:14 UTC, fuliu-zln commented on alicloud/service_alicloud_tag.go
> +		return object, WrapErrorf(Error(GetNotFoundMessage("TagPolicy:ListTargetsForPolicy", id)), NotFoundWithResponse, response)
done

2023-04-14 05:17 UTC, MrWolong commented on alicloud/resource_alicloud_tag_policy_attachment_test.go
> +		return &ResourcemanagerService{testAccProvider.Meta().(*connectivity.AliyunClient)}
ResourcemanagerService
![image](https://user-images.githubusercontent.com/36806235/231947755-e3a01967-c203-4d03-b2b3-37a9b3389c3f.png)

2023-04-14 05:23 UTC, MrWolong commented on website/docs/r/tag_policy_attachment.html.markdown
> +
The following attributes are exported:

2023-04-14 05:28 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_policy_attachment_test.go
> +		return &ResourcemanagerService{testAccProvider.Meta().(*connectivity.AliyunClient)}
done

2023-04-14 05:28 UTC, fuliu-zln commented on website/docs/r/tag_policy_attachment.html.markdown
> +
done

2023-04-14 07:02 UTC, MrWolong commented on alicloud/resource_alicloud_tag_policy_attachment_test.go
> +resource "alicloud_ram_user" "this" {
alicloud_ram_user这个资源有用到吗？没有yo用到就删掉
![image](https://user-images.githubusercontent.com/36806235/231968327-de0ed9b4-6118-49d7-966a-d13b8668179d.png)

2023-04-14 10:16 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_policy_attachment_test.go
> +resource "alicloud_ram_user" "this" {
done

2023-04-18 06:23 UTC, MrWolong commented on alicloud/service_alicloud_tag.go
> +			return object, WrapErrorf(Error(GetNotFoundMessage("Tag:Policy", id)), NotFoundWithResponse, response)
改，"Tag:PolicyAttachment"
![image](https://user-images.githubusercontent.com/36806235/232689229-af1dab81-cadb-4c56-a3be-58346a588c58.png)

2023-04-18 06:25 UTC, MrWolong commented on website/docs/r/tag_policy_attachment.html.markdown
> +-> **NOTE:** Available in v1.203.0+.
v1.204.0

2023-04-18 06:26 UTC, MrWolong commented on website/docs/r/tag_policy_attachment.html.markdown
> +* `id` - The resource ID in terraform of Policy Attachment. It formats as `<policy_Id>`:`<target_Id>`:`<target_type>`.
改
![image](https://user-images.githubusercontent.com/36806235/232689857-1c55b8e2-5d39-489c-9c32-76ca55887338.png)

2023-04-18 06:30 UTC, fuliu-zln commented on website/docs/r/tag_policy_attachment.html.markdown
> +* `id` - The resource ID in terraform of Policy Attachment. It formats as `<policy_Id>`:`<target_Id>`:`<target_type>`.
done

2023-04-18 08:26 UTC, fuliu-zln commented on alicloud/service_alicloud_tag.go
> +			return object, WrapErrorf(Error(GetNotFoundMessage("Tag:Policy", id)), NotFoundWithResponse, response)
done

2023-04-19 01:50 UTC, xiaozhu36 approved these changes

2023-04-19 17:14 UTC, xiaozhu36 requested changes

2023-04-20 01:38 UTC, xiaozhu36 approved these changes

2023-04-20 01:55 UTC, fuliu-zln commented on alicloud/connectivity/regions.go
> +var TagPolicySupportRegions = []Region{Shanghai}
目前tag 是双中心，上海和新加坡，新加坡的region支持读，另外从open api 透给用户的region的取值只有上海，所以就把新加坡地区的给去了。这个和tag团队的洛蒙昨天沟通过，也在群里有说明。

2023-04-20 07:43 UTC, merged