resource/alicloud_cs_kubernetes_addon: Optimize component lifecycle management
aliyun/terraform-provider-alicloud pull request #6091
Opened 2023-04-19 10:23 UTC by saberrey

resource/alicloud_cs_kubernetes_addon: Optimize component lifecycle management

2023-04-21 02:50 UTC, xiaozhu36 requested changes

2023-04-21 02:50 UTC, xiaozhu36 commented on alicloud/connectivity/client.go
> +	openapi "github.com/alibabacloud-go/darabonba-openapi/v2/client"
这个为啥要改

2023-04-21 02:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_addon.go
> +		if NotFoundError(err) {
这个地方要加上一个 !d.IsNewResource判断

2023-04-21 02:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_addon.go
> +	if err != nil && !NotFoundError(err) {
如果是 NotFoundError，会怎么样

2023-04-21 02:52 UTC, saberrey commented on alicloud/connectivity/client.go
> +	openapi "github.com/alibabacloud-go/darabonba-openapi/v2/client"
cs新的sdk底层依赖的darabonba-openapi切换到了v2，这个文件中client的初始化只有cs的client用到了这个依赖，需要切换下v2

2023-04-21 03:00 UTC, saberrey commented on alicloud/resource_alicloud_cs_kubernetes_addon.go
> +	if err != nil && !NotFoundError(err) {
这里是因为csClient.DescribeCsKubernetesAddonStatus(clusterId, name)返回的err里可能为not found，因为not found对于create是预期的，所以需要做下判断

2023-04-21 03:02 UTC, saberrey commented on alicloud/resource_alicloud_cs_kubernetes_addon.go
> +	if err != nil && !NotFoundError(err) {
之所以要先DescribeCsKubernetesAddonStatus是因为，我们创建集群的时候会默认安装一些组件，所以这里安装的组件可能是集群中已经存在的，所以需要先describe一下

2023-04-21 03:06 UTC, saberrey commented on alicloud/resource_alicloud_cs_kubernetes_addon.go
> +		if NotFoundError(err) {
done

2023-04-24 02:01 UTC, xiaozhu36 approved these changes

2023-04-24 05:29 UTC, xiaozhu36 approved these changes

2023-04-24 07:03 UTC, xiaozhu36 approved these changes

2023-04-25 03:38 UTC, xiaozhu36 approved these changes

2023-04-25 06:38 UTC, xiaozhu36 approved these changes

2023-04-26 02:20 UTC, xiaozhu36 approved these changes

2023-04-26 09:14 UTC, xiaozhu36 approved these changes

2023-04-27 03:19 UTC, xiaozhu36 approved these changes

2023-04-27 04:58 UTC, xiaozhu36 approved these changes

2023-04-27 06:09 UTC, xiaozhu36 approved these changes

2023-04-27 07:19 UTC, xiaozhu36 approved these changes

2023-04-27 08:31 UTC, xiaozhu36 approved these changes

2023-04-27 09:46 UTC, xiaozhu36 approved these changes

2023-04-28 02:41 UTC, xiaozhu36 approved these changes

2023-04-28 06:37 UTC, merged