resource/alicloud_db_instance, resource/alicloud_rds_clone_db_instance, datasource/alicloud_db_zones, datasource/alicloud_db_instance_classes, docs/db_instance_classes, docs/db_zones, docs/db_instance, docs/rds_clone_db_instance : Adapt to MySQL Serverless high availability, SQLServer Serverless and PostgreSQL Serverless function.
aliyun/terraform-provider-alicloud pull request #6093
Opened 2023-04-20 07:41 UTC by TingxuanGuo

2023-04-23 09:55 UTC, super-eggs commented on alicloud/connectivity/regions.go
> -var MySQLServerlessSupportRegions = []Region{Hangzhou}
这里为啥要改呢

2023-04-23 09:55 UTC, super-eggs commented on alicloud/resource_alicloud_db_instance.go
> +							Optional: true,
针对必填改选填，在测试用例中应该增加对应测试

2023-04-23 09:55 UTC, super-eggs commented on alicloud/resource_alicloud_db_instance.go
>  					Schema: map[string]*schema.Schema{
serverless_config 只能配置一组的话，应该加上限制。MaxItems: 1

2023-04-23 09:56 UTC, TingxuanGuo commented on alicloud/connectivity/regions.go
> -var MySQLServerlessSupportRegions = []Region{Hangzhou}
因为名字描述不准确了，之前接入的时候仅MySQL支持Serverless，现在MySQL PostgreSQL SQLServer 三个引擎都支持Serverless了，所以修改了命名。

2023-04-26 11:32 UTC, xiaozhu36 requested changes

2023-04-26 11:32 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance.go
> +				if category, ok := d.GetOk("Category"); ok {
schema 中没有 Category 这个属性

2023-04-26 11:32 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance.go
> +					v["min_capacity"].(float64),
这两个参数是必填的么

2023-04-26 11:32 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance_test.go
> +			},
在serverless 模式下，其他的属性也需要测试变更

2023-04-26 11:32 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				},
为什么要加这个 DiffSuppressFunc

2023-04-26 11:32 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +	instance, err := rdsService.DescribeDBInstance(d.Get("source_db_instance_id").(string))
为啥要加这个逻辑

2023-04-26 11:32 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +}
为啥要保留一个MssqlHAServerless，而不是直接创建新的

2023-04-27 02:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance.go
> +					v["min_capacity"].(float64),
既然是必填，那么在scheme的定义中，不应该改成 optional

2023-04-27 02:31 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance_test.go
> +			},
不是吧，实例名称，实例规格，引擎版本等，都不能修改？

2023-04-27 02:32 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				},
如果是这样，需要在文档中明确说明

2023-04-27 02:32 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_instance.go
> +					v["min_capacity"].(float64),
已订正

2023-04-27 02:43 UTC, xiaozhu36 requested changes

2023-04-27 02:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +					}),
import 的测试

2023-04-27 02:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +				),
缺少import 的测试

2023-04-27 02:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +}
“需要通过手动下发备份” 这个是啥意思，操作Terraform的用户还需要再通过控制台手动下发么？
没有OpenAPI可以获取到已经结束的备份么？
如果存在“当前已经存在一个正在运行的备份任务”的情况，那么需要在resource中增加重试逻辑，否则无法做到自动化

2023-04-27 02:44 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_instance_test.go
> +			},
1. 实例名称，可以修改，我补充一下这个的自动化测试案例。
2. 实例规格，不可修改，Serverless 为自动弹性变配实例，故不同Serverless版本，实例规格仅存在唯一一个。
3. 引擎版本，不可修改，当前 Serverless 版本升级功能还不支持。

2023-05-04 01:50 UTC, TingxuanGuo commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				},
已在文档中补充说明

2023-05-05 06:37 UTC, TingxuanGuo commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +}
已经新增重试机制，已合并至master

2023-05-05 06:38 UTC, TingxuanGuo commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +					}),
done

2023-05-05 06:38 UTC, TingxuanGuo commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +				),
done

2023-05-08 02:45 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_instance_test.go
> +			},
done

2023-05-08 03:00 UTC, xiaozhu36 requested changes

2023-05-08 03:32 UTC, TingxuanGuo commented on alicloud/resource_alicloud_db_instance.go
> +		d.Set("serverless_config", serverlessConfig)
done

2023-05-08 03:32 UTC, TingxuanGuo commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +			return nil
done

2023-05-08 03:33 UTC, TingxuanGuo commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +			d.SetId("")
done

2023-05-08 12:20 UTC, xiaozhu36 approved these changes

2023-05-09 03:52 UTC, xiaozhu36 approved these changes

2023-05-09 09:02 UTC, xiaozhu36 approved these changes

2023-05-12 02:32 UTC, xiaozhu36 approved these changes

2023-05-15 02:36 UTC, xiaozhu36 approved these changes

2023-05-16 02:02 UTC, closed without merging