resource/alicloud_eci_container_group: Supported multiple `vswitch_id` for ECI
aliyun/terraform-provider-alicloud pull request #6094
Opened 2023-04-21 10:23 UTC by MrWolong

2023-07-13 09:13 UTC, xiaozhu36 requested changes

2023-07-13 09:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eci_container_group.go
> +					}
这个逻辑是干啥的

2023-07-13 09:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eci_container_group.go
> +				ForceNew: true,
资源组不支持修改

2023-07-13 09:31 UTC, MrWolong commented on alicloud/resource_alicloud_eci_container_group.go
> +					}
该需求是为了支持用户输入多个交换机id，但是云产品这块的逻辑是，用户可以输入多个交换机id，但是最终查询返回只有一个。所以这块加了压制函数，如果用户传入了1个交换机id则ok，如果输入多个，则压制。

2023-07-14 05:44 UTC, MrWolong commented on alicloud/resource_alicloud_eci_container_group.go
> +				ForceNew: true,
已修复

2023-07-14 09:04 UTC, xiaozhu36 requested changes

2023-07-17 03:13 UTC, xiaozhu36 requested changes

2023-07-17 03:13 UTC, xiaozhu36 commented on website/docs/r/eci_container_group.html.markdown
> +**NOTE:** From version 1.208.0, You can specify up to 10 `vswitch_id`. Separate multiple vSwitch IDs with commas (,), such as vsw-***,vsw-***.
这个 NOTE 上需要补充下，设置了多个 vswitch 之后，最终只有一个生效。

2023-07-17 03:13 UTC, xiaozhu36 commented on website/docs/r/eci_container_group.html.markdown
> +**NOTE:** From version 1.208.0, You can specify up to 10 `vswitch_id`. Separate multiple vSwitch IDs with commas (,), such as vsw-***,vsw-***.
只要生效的vswitch 在这些vswitch 中，那么就会忽略diff

2023-07-20 03:54 UTC, MrWolong commented on website/docs/r/eci_container_group.html.markdown
> +**NOTE:** From version 1.208.0, You can specify up to 10 `vswitch_id`. Separate multiple vSwitch IDs with commas (,), such as vsw-***,vsw-***.
已修复

2023-07-21 05:30 UTC, xiaozhu36 approved these changes

2023-07-21 08:55 UTC, closed without merging