resource_alicloud_config_rule: Automatic generation.
aliyun/terraform-provider-alicloud pull request #6095
Opened 2023-04-21 12:35 UTC by ChenHanZhang

2023-04-21 13:19 UTC, xiaozhu36 requested changes

2023-04-21 13:19 UTC, xiaozhu36 commented on website/docs/r/config_rule.html.markdown
> +$ terraform import alicloud_config_rule.example
最后的ID呢

2023-04-21 13:19 UTC, xiaozhu36 commented on website/docs/r/config_rule.html.markdown
> +* `risk_level` - (Required) The risk level of the resources that are not compliant with the rule. Valid values:  1: critical 2: warning 3: info
既然spec 上没有配置枚举值，为啥文档中可以生成枚举值

2023-04-21 13:19 UTC, xiaozhu36 commented on alicloud/service_alicloud_config_v2.go
> +func (s *ConfigServiceV2) describeConfigRuleGetConfigRuleApi(id string) (object map[string]interface{}, err error) {
这个地方单独封装一个函数的目的是什么？

2023-04-21 13:19 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule.go
> +			if IsExpectedErrors(err, []string{}) || NeedRetry(err) {
没有错误码，为啥还要写 IsExpectedErrors

2023-04-21 13:19 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule.go
> +				Type:     schema.TypeSet,
复杂结构，以后优先以list为主，如果存在顺序问题，再设计为set

2023-04-21 15:33 UTC, ChenHanZhang commented on website/docs/r/config_rule.html.markdown
> +* `risk_level` - (Required) The risk level of the resources that are not compliant with the rule. Valid values:  1: critical 2: warning 3: info
这里是文档中的描述，不是配置的枚举值

2023-04-21 15:34 UTC, ChenHanZhang commented on website/docs/r/config_rule.html.markdown
> +$ terraform import alicloud_config_rule.example
这个ID没有地方能知道格式，我补充一下 <id> 的表示方式

2023-04-21 15:35 UTC, ChenHanZhang commented on alicloud/service_alicloud_config_v2.go
> +func (s *ConfigServiceV2) describeConfigRuleGetConfigRuleApi(id string) (object map[string]interface{}, err error) {
这里会优化一下，仅存在一个api时不进行封装。多个api时，每个api单独封装

2023-04-21 15:35 UTC, ChenHanZhang commented on alicloud/service_alicloud_config_v2.go
> +func (s *ConfigServiceV2) describeConfigRuleGetConfigRuleApi(id string) (object map[string]interface{}, err error) {
这里实现的时候按循环api数组实现的，所以目前一个api和多个api，生成的模板是一样的

2023-04-21 15:36 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_rule.go
> +			if IsExpectedErrors(err, []string{}) || NeedRetry(err) {
这里需要优化一下，去掉多余的判断

2023-04-24 07:52 UTC, xiaozhu36 requested changes

2023-04-24 07:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule.go
> -		return WrapError(Error("[ERROR] Argument 'source_detail_message_type' or 'config_rule_trigger_types' must be set one!"))
这个去掉的逻辑，说明config_rule_trigger_types 是必填的，那么这个时候，需要在schema中用 ExactlyOneOf 代替 ConflictWith

2023-04-24 07:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule.go
> -		return WrapError(Error("[ERROR] Argument 'scope_compliance_resource_types' or 'resource_types_scope' must be set one!"))
这个地方也一样

2023-04-24 07:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule.go
> +	d.Set("scope_compliance_resource_types", d.Get("resource_types_scope"))
这个地方为啥要用d.Get，如果跟 config_rule_trigger_types 的值一样的话，应该直接用  object["config_rule_trigger_types"] 啊

2023-04-24 07:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule.go
> +	if !d.IsNewResource() && (d.HasChange("config_rule_trigger_types") || d.HasChange("source_detail_message_type")) {
以后这种多个hasChange 的，可以用 HasChanges 函数

2023-04-24 07:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule.go
> +		if d.HasChange("scope_compliance_resource_types") {
里面为啥又要判断 haschange

2023-04-24 07:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule_test.go
> +					"resource_group_ids_scope":   "rg-acfmvoh45rhcfly",
上面的case 用的是新创建的资源组ID，这个地方是写死的

2023-04-24 07:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule_test.go
> +					"rule_name":                  "tf-cicd-rule-by-root-ak-check",
rule name 应该用 var.name

2023-04-24 07:52 UTC, xiaozhu36 commented on alicloud/service_alicloud_config_v2.go
> +			return nil, "", nil
这个判断不需要，如果怕空指针，直接用 fmt.Sprint

2023-04-24 07:58 UTC, ChenHanZhang commented on alicloud/data_source_alicloud_config_rules_test.go
> +  name_regex = "${alicloud_instance.default.instance_name}"
这里创建的新的实例，原先这种查询没办法保障存在可用的实例

2023-04-24 08:01 UTC, ChenHanZhang commented on alicloud/service_alicloud_config_v2.go
> +	instanceMap["account_id"] = objectRaw["AccountId"]
存在list当get以及其它过滤条件情况，这里转一层更通用

2023-04-24 08:44 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_rule.go
> -		return WrapError(Error("[ERROR] Argument 'source_detail_message_type' or 'config_rule_trigger_types' must be set one!"))
已优化，冗余的同名属性加上ExactlyOneOf描述

2023-04-24 08:49 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_rule.go
> +	d.Set("scope_compliance_resource_types", d.Get("resource_types_scope"))
已修复

2023-04-24 09:22 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_rule.go
> +	if !d.IsNewResource() && (d.HasChange("config_rule_trigger_types") || d.HasChange("source_detail_message_type")) {
ok，已经修复

2023-04-24 09:23 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_rule.go
> +		if d.HasChange("scope_compliance_resource_types") {
得知道具体是哪个字段发生了变更

2023-04-24 09:43 UTC, ChenHanZhang commented on alicloud/service_alicloud_config_v2.go
> +			return nil, "", nil
已修复

2023-04-25 02:15 UTC, xiaozhu36 requested changes

2023-04-25 02:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule.go
>  				ConflictsWith: []string{"source_detail_message_type"},
有了 ExactlyOneOf 之后，就不需要 ConflictsWith 了

2023-04-25 02:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule.go
> +		}
既然都是单独判断，为啥要写在一个if block 中

2023-04-25 02:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule.go
> +		if d.HasChange("scope_compliance_resource_types") {
为啥不在最外层判断

2023-04-25 02:15 UTC, xiaozhu36 commented on alicloud/service_alicloud_config_v2.go
> +	instanceMap["account_id"] = objectRaw["AccountId"]
通用在哪儿

2023-04-25 02:32 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_rule.go
>  				ConflictsWith: []string{"source_detail_message_type"},
已修复

2023-04-25 02:46 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_rule.go
> +		}
已优化

2023-04-25 02:47 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_rule.go
> +		if d.HasChange("scope_compliance_resource_types") {
已优化

2023-04-25 11:41 UTC, xiaozhu36 requested changes

2023-04-25 11:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule.go
> +				ConflictsWith: []string{"config_rule_trigger_types"},
有了上面的ExactlyOneOf的之后，这个地方的 ConflictsWith 就可以去掉了

2023-04-25 11:41 UTC, xiaozhu36 commented on alicloud/tags.go
> +				tagKey = v.(string)
这个地方为啥要改，API中应该没有这种下划线的参数吧

2023-04-25 12:18 UTC, xiaozhu36 requested changes

2023-04-25 12:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule.go
> +	sourceDetails2Raw := sourceDetails2RawObj.([]interface{})
这个地方有空指针的风险

2023-04-25 12:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_rule_test.go
> +					"description":                "检查根账户访问密钥是否存在，如果存在视为“不合规”。",
step 0 放必填字段

2023-04-25 13:20 UTC, xiaozhu36 approved these changes

2023-04-26 01:34 UTC, xiaozhu36 approved these changes

2023-04-26 01:58 UTC, merged