resource/alicloud_polardb_cluster: polardb support cluster serverless
aliyun/terraform-provider-alicloud pull request #6098
Opened 2023-04-25 02:35 UTC by mengliux

resource/alicloud_polardb_cluster: polardb support cluster serverless

2023-04-26 09:51 UTC, xiaozhu36 requested changes

2023-04-26 09:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +			if d.HasChange("scale_min") || d.HasChange("scale_max") || d.HasChange("allow_shut_down") || d.HasChange("scale_ro_num_min") || d.HasChange("scale_ro_num_max") {
使用 HasChanges

2023-04-26 09:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +				Computed: true,
既然这几个参数都是只有在 设置 serverless_type 的时候才有效，那么他们需要增加 DiffSupporess

2023-04-26 09:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					}),
对于可修改的参数，每个都需要一个单独的step来测试是否能单独更新

2023-04-26 09:51 UTC, xiaozhu36 commented on website/docs/r/polardb_cluster.html.markdown
> +* `allow_shut_down` - (Optional, Available in v1.204.0+) Specifies whether to enable the no-activity suspension feature. Default value: false. Valid values are `true`, `false`.
既然这些参数有取值范围，那么应该在schema中定义上 ValidationFunc

2023-04-27 10:17 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +			if d.HasChange("scale_min") || d.HasChange("scale_max") || d.HasChange("allow_shut_down") || d.HasChange("scale_ro_num_min") || d.HasChange("scale_ro_num_max") {
已解决

2023-04-27 10:17 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +				Computed: true,
已增加

2023-04-27 10:18 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					}),
已修改

2023-04-27 10:18 UTC, mengliux commented on website/docs/r/polardb_cluster.html.markdown
> +* `allow_shut_down` - (Optional, Available in v1.204.0+) Specifies whether to enable the no-activity suspension feature. Default value: false. Valid values are `true`, `false`.
已加

2023-04-27 11:14 UTC, xiaozhu36 requested changes

2023-04-27 11:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					}),
不止这两个参数可以修改吧，其他所有需要修改的参数都要测一遍的

2023-04-28 02:48 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					}),
嗯嗯，都增加了，我开始理解成把暂停开关和暂停时长拆开测试

2023-04-28 02:58 UTC, xiaozhu36 approved these changes

2023-04-28 08:15 UTC, xiaozhu36 approved these changes

2023-04-28 11:56 UTC, merged