New resource: resource_alicloud_config_remediation.
aliyun/terraform-provider-alicloud pull request #6100
Opened 2023-04-26 03:18 UTC by ChenHanZhang

2023-04-26 09:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_remediation.go
> +	if !d.IsNewResource() && d.HasChange("remediation_template_id") {
既然都在 Create 中设置过了，Create 可以直接return read

2023-04-26 09:22 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_remediation.go
> +			log.Printf("[DEBUG] Resource alicloud_config_remediation .DescribeConfigRemediation Failed!!! %s", err)
.DescribeConfigRemediation 最前面的 点 是干啥的

2023-04-26 09:23 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_remediation_test.go
> +					"remediation_type":        "OOS",
非必填的不应该出现在step 0 中

2023-04-26 09:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_remediation_test.go
> +
还应该再加一个step 0 包含所有参数的case

2023-04-26 09:25 UTC, xiaozhu36 commented on website/docs/r/config_remediation.html.markdown
> +  remediation_type        = "OOS"
这个地方的 Region Id， resourceType，resourceId 都应该是具体的值吧

2023-04-27 01:27 UTC, ChenHanZhang commented on website/docs/r/config_remediation.html.markdown
> +  remediation_type        = "OOS"
按原始用例上录入的目前就是{regionId}这种形式

2023-04-27 01:33 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_remediation.go
> +	if !d.IsNewResource() && d.HasChange("remediation_template_id") {
已修复，之前没过滤ClientToken，Update中多一个ClientToken

2023-04-27 01:40 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_remediation_test.go
> +					"remediation_type":        "OOS",
目前资源用例透出时，step0是包含了所有属性的，已记录并后续迭代资源用例，目前先暂时在生成器上过滤

2023-04-27 02:05 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_remediation_test.go
> +
已修复

2023-04-27 02:51 UTC, xiaozhu36 requested changes

2023-04-27 02:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_remediation.go
> +	if !d.IsNewResource() && d.HasChange("remediation_template_id") {
既然create之后直接返回了 read，那么就不需要 !d.IsNewResource() 判断了

2023-04-27 02:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_remediation_test.go
> +					"remediation_type":        "OOS",
params 看起来是json，那么在schema中要有json 的validation，不然但凡少写一个逗号就失败了

2023-04-27 02:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_config_remediation_test.go
> +					"remediation_type":        "OOS",
“目前先暂时在生成器上过滤” 现在看起来还没过滤啊

2023-04-27 02:51 UTC, xiaozhu36 commented on website/docs/r/config_remediation.html.markdown
> +* `params` - (Required) Remediation parameter.
如果是jsonstring，最好标记出来 JsonString

2023-04-27 02:56 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_remediation_test.go
> +					"remediation_type":        "OOS",
这几个就是必填的

2023-04-27 04:25 UTC, ChenHanZhang commented on website/docs/r/config_remediation.html.markdown
> +* `params` - (Required) Remediation parameter.
已优化

2023-04-27 04:39 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_remediation.go
> +	if !d.IsNewResource() && d.HasChange("remediation_template_id") {
已修复

2023-04-27 04:41 UTC, ChenHanZhang commented on alicloud/resource_alicloud_config_remediation_test.go
> +					"remediation_type":        "OOS",
已修复

2023-04-27 05:30 UTC, xiaozhu36 approved these changes

2023-04-27 05:57 UTC, merged