resource/alicloud_adb_db_cluster: Added the field `elastic_io_resource_size` and `disk_performance_level`
aliyun/terraform-provider-alicloud pull request #6116
Opened 2023-05-04 10:34 UTC by MrWolong

2023-05-26 02:22 UTC, xiaozhu36 requested changes

2023-05-26 02:22 UTC, xiaozhu36 commented on website/docs/r/adb_db_cluster.html.markdown
> +* `disk_performance_level` - (Optional, Computed, Available in 1.206.0+) The ESSD performance level.
这两个值应该怎么传入？文档上要写清楚

2023-05-26 09:44 UTC, MrWolong commented on website/docs/r/adb_db_cluster.html.markdown
> +* `disk_performance_level` - (Optional, Computed, Available in 1.206.0+) The ESSD performance level.
已修复

2023-05-30 07:59 UTC, xiaozhu36 requested changes

2023-05-30 07:59 UTC, xiaozhu36 commented on website/docs/r/adb_db_cluster.html.markdown
>  * `tags` - (Optional) A mapping of tags to assign to the resource.
既然有枚举值，那么应该在schema中定义出来

2023-05-30 08:46 UTC, MrWolong commented on alicloud/resource_alicloud_adb_db_cluster_test.go
> +					"elastic_io_resource_size": "12Core96GB",
新加的字段比较特殊，目前只能在杭州，张家口，北京，上海，深圳，青岛，广州等一些地区使用，如果在这些地区使用的话，compute_resource字段的值要变动，跟其他测试用例中的值不同，所以，新加了一个用例

2023-05-30 09:22 UTC, MrWolong commented on alicloud/resource_alicloud_adb_db_cluster_test.go
>  	"compute_resource":    "",
compute_resource没有Computed属性
![image](https://github.com/aliyun/terraform-provider-alicloud/assets/36806235/06f65373-bd3e-43e6-84e9-82f23d1e055d)

2023-06-08 07:15 UTC, MrWolong commented on website/docs/r/adb_db_cluster.html.markdown
>  * `tags` - (Optional) A mapping of tags to assign to the resource.
已修改

2023-06-09 03:48 UTC, xiaozhu36 requested changes

2023-06-09 03:48 UTC, xiaozhu36 commented on website/docs/r/adb_db_cluster.html.markdown
> +-> **NOTE:** Removing alicloud_adb_cluster from your configuration. The alicloud_adb_cluster resource allows you to manage your adb cluster, but Terraform cannot destroy it if your cluster type is pr
这个地方不应该这样改，直接把这段挪到 Example 的下方

2023-06-09 09:22 UTC, MrWolong commented on website/docs/r/adb_db_cluster.html.markdown
> +-> **NOTE:** Removing alicloud_adb_cluster from your configuration. The alicloud_adb_cluster resource allows you to manage your adb cluster, but Terraform cannot destroy it if your cluster type is pr
已修复

2023-06-15 08:49 UTC, xiaozhu36 requested changes

2023-06-15 08:49 UTC, xiaozhu36 commented on website/docs/r/adb_db_cluster.html.markdown
> +-> **NOTE:** Removing alicloud_adb_cluster from your configuration. The alicloud_adb_cluster resource allows you to manage your adb cluster, but Terraform cannot destroy it if your cluster type is Pr
这个NOTE 应该放在 ## Example Usage 下面，并且以 ### 的三级标题

2023-06-15 09:58 UTC, MrWolong commented on website/docs/r/adb_db_cluster.html.markdown
> +-> **NOTE:** Removing alicloud_adb_cluster from your configuration. The alicloud_adb_cluster resource allows you to manage your adb cluster, but Terraform cannot destroy it if your cluster type is Pr
已修复

2023-06-15 11:51 UTC, xiaozhu36 requested changes

2023-06-15 11:51 UTC, xiaozhu36 commented on website/docs/r/adb_db_cluster.html.markdown
> +### Removing alicloud_adb_cluster from your configuration.
不是放在这，是放在example 结束之后，也就是 ## Argument Reference 上方

2023-06-16 01:48 UTC, MrWolong commented on website/docs/r/adb_db_cluster.html.markdown
> +### Removing alicloud_adb_cluster from your configuration.
已修复

2023-06-16 02:53 UTC, xiaozhu36 approved these changes

2023-06-16 09:23 UTC, merged