resource/alicloud_vpc: Adds new attribute classic_link_enabled.
aliyun/terraform-provider-alicloud pull request #6119
Opened 2023-05-06 07:55 UTC by ChenHanZhang

2023-05-30 06:30 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_vpc.go
> +	if v, ok := d.GetOkExists("enable_ipv6"); ok {
操作私有属性，不用判定HasChange，设置有值的时候随着api的调用传入即可

2023-05-31 06:31 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc.go
> +				ForceNew: true,
dry_run 不应该是ForceNew的

2023-05-31 06:31 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vswitch.go
> +			"resource_group_id": {
资源组需要支持更新

2023-05-31 06:31 UTC, ChenHanZhang commented on website/docs/r/vpc.html.markdown
> +-> **NOTE:** Available in v1.206.0+.
这个信息不正确，去掉

2023-05-31 06:31 UTC, ChenHanZhang commented on website/docs/r/vpc.html.markdown
> +* `resource_group_id` - (Optional, Computed) The ID of the resource group to which the VPC belongs.
资源组的可用版本信息

2023-05-31 06:31 UTC, ChenHanZhang commented on website/docs/r/vswitch.html.markdown
> -You can use to the existing [vpc module](https://registry.terraform.io/modules/alibaba/vpc/alicloud)
这个信息还是要维护起来

2023-05-31 06:31 UTC, ChenHanZhang commented on website/docs/r/vswitch.html.markdown
> -* `zone_id` - (Optional, ForceNew, Available in 1.119.0+) The AZ for the switch. **Note:** Required for a VPC switch.
看下生成器为什么丢失了zone_id

2023-05-31 06:31 UTC, ChenHanZhang commented on website/docs/r/vswitch.html.markdown
> +* `tags` - (Optional, Map) The tags of VSwitch.
tags、vswitch_name、enable_ipv6、ipv6_cidr_block_mask 的版本信息丢失了

2023-05-31 06:34 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_vpc_test.go
> +				Config: testAccConfig(map[string]interface{}{
done

2023-05-31 06:35 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_vpc.go
> +	if v, ok := d.GetOkExists("enable_ipv6"); ok {
done

2023-05-31 06:35 UTC, ChenHanZhang commented on website/docs/r/vpc_vpc.html.markdown
> +  -*ChinaMobile**: China Mobile (single line).
done

2023-05-31 06:36 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc.go
> +				ForceNew: true,
done

2023-05-31 06:39 UTC, ChenHanZhang commented on website/docs/r/vpc.html.markdown
> +-> **NOTE:** Available in v1.206.0+.
done

2023-05-31 06:40 UTC, ChenHanZhang commented on website/docs/r/vpc.html.markdown
> +* `resource_group_id` - (Optional, Computed) The ID of the resource group to which the VPC belongs.
done

2023-05-31 06:48 UTC, ChenHanZhang commented on website/docs/r/vswitch.html.markdown
> -resource "alicloud_vpc" "vpc" {
这里以前的示例更加丰富，需要考虑生成器如何生成指定的多个测试用例，目前仅生成一个。这里先将以前的用例补充回来。

2023-05-31 06:59 UTC, ChenHanZhang commented on website/docs/r/vswitch.html.markdown
> +* `tags` - (Optional, Map) The tags of VSwitch.
done

2023-05-31 07:17 UTC, ChenHanZhang commented on website/docs/r/vswitch.html.markdown
> -resource "alicloud_vpc" "vpc" {
done

2023-05-31 07:18 UTC, ChenHanZhang commented on website/docs/r/vswitch.html.markdown
> -* `zone_id` - (Optional, ForceNew, Available in 1.119.0+) The AZ for the switch. **Note:** Required for a VPC switch.
done

2023-05-31 07:18 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vswitch.go
> +			"resource_group_id": {
已确认VSwitch暂时不支持资源组，去除定义

2023-05-31 09:50 UTC, xiaozhu36 requested changes

2023-05-31 09:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc.go
> +			"vswitch_ids": {
这个vswitch_ids没必要透出

2023-05-31 09:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc.go
> +				Type:     schema.TypeString,
已经有 id 了，不需要 vpc_id 了

2023-05-31 09:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vswitch.go
> +				Computed: true,
这个也一样

2023-05-31 09:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vswitch_test.go
> +				ImportStateVerifyIgnore: []string{"enable_ipv6", "ipv6_cidr_block_mask"},
ipv6_cidr_block_mask 不应该被 ignore

2023-06-01 00:35 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc.go
> +				Computed: true,
试了可以，系统默认值就是 172.16.0.0/12

2023-06-01 00:40 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc.go
> +				Computed:      true,
route_table_id是标准的属性名，同以前的router_table_id

2023-06-01 01:02 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc.go
> +				Computed:      true,
这个属性是需要保留的

2023-06-01 01:02 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc.go
> +				Type:     schema.TypeString,
done

2023-06-01 01:08 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_test.go
> +					}),
生成逻辑的缺陷，目前资源测试用例录入n步后，生成的Terraform测试步骤会处理为：
1. 资源用例第1步中如果存在必填值，则将用例中第1步只取必填保留，剩下的其它非必填的m个可改属性，会拆分为m步；
2. 资源用例第2到n步中的所有可改属性，按单个属性更新的方式拆分为 (n-1)*m 步。
所有录入的时候，第一步全填值并且存在较多的可改属性，第二、三步中的可改属性重复，那么生成的时候就反复修改。
这里可以进一步优化一下生成逻辑。

2023-06-01 01:29 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc.go
> +			"vswitch_ids": {
done，后续滤除除status和create_time之外其它的所有只读属性，除存量已经透出的字段，后续新增的只读属性在Resource上不再透出

2023-06-01 02:36 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vswitch.go
> +				Computed: true,
done

2023-06-01 02:43 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vswitch_test.go
> +				ImportStateVerifyIgnore: []string{"enable_ipv6", "ipv6_cidr_block_mask"},
ipv6_cidr_block_mask 实际在spec上的定义就是一个操作私有属性，目前Spec上一个出参仅能对应一个属性，api上的这个对应参数映射到了另一个属性（Ipv6Block）上了。所以这个属性是个操作私有属性，因此生成的时候这里被ignore了。
这里考虑对spec进行扩展，支持在资源属性上直接定义JSONNata，这样就可以当成普通属性正常取值。

2023-06-01 05:42 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_test.go
> +					}),
done

2023-06-01 12:08 UTC, xiaozhu36 requested changes

2023-06-01 12:08 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_test.go
> +var AlicloudVpcVpcMap3113 = map[string]string{}
computed 的check set 下吧

2023-06-02 02:02 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_test.go
> +var AlicloudVpcVpcMap3113 = map[string]string{}
done

2023-06-02 03:10 UTC, xiaozhu36 approved these changes

2023-06-02 03:41 UTC, merged