resource/alicloud_vpc_prefix_list: Adds new attribute ResourceGroupId, Tags etc.
aliyun/terraform-provider-alicloud pull request #6128
Opened 2023-05-08 10:16 UTC by ChenHanZhang

2023-05-09 01:43 UTC, xiaozhu36 requested changes

2023-05-09 01:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_prefix_list.go
> -				ValidateFunc: validation.StringInSlice([]string{"IPV4", "IPV6"}, false),
这个枚举值为啥要去掉

2023-05-09 01:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_prefix_list.go
> +				Computed: true,
owner_id 统一过滤掉

2023-05-09 01:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_prefix_list.go
> +				Type:     schema.TypeString,
这些正则限制为啥都去掉了

2023-05-09 01:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_prefix_list.go
> +				Type:     schema.TypeSet,
entrys 和 entries 的关系是啥

2023-05-09 01:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_prefix_list.go
> +				Elem: &schema.Resource{
这个纯出参的属性，需要对外输出么？

2023-05-09 01:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_prefix_list.go
> +			log.Printf("[DEBUG] Resource alicloud_vpc_prefix_list DescribeVpcPrefixList Failed!!! %s", err)
如果查更多的属性报错，这个地方不用多余的判断，直接报错就行

2023-05-09 01:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_prefix_list.go
> -
从删除的重试逻辑上看，这个删除应该是异步的吧

2023-05-16 15:12 UTC, xiaozhu36 requested changes

2023-05-17 06:43 UTC, xiaozhu36 requested changes

2023-05-17 06:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_prefix_list.go
> +	}
1. entrys 和 entries的类型都是 set，但是参数设置的方式为啥不一样
2. entrys 应该在前面吧

2023-05-17 06:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_prefix_list.go
>  	if d.HasChange("entrys") {
这个已经在Create中设置过了

2023-05-17 06:43 UTC, xiaozhu36 commented on website/docs/r/vpc_prefix_list.html.markdown
> -* `entrys` - (Optional) The CIDR address block list of the prefix list. See the following `Block entrys`.
entrys 应该标记为 Deprecated

2023-05-17 09:40 UTC, ChenHanZhang commented on website/docs/r/vpc_prefix_list.html.markdown
> -* `entrys` - (Optional) The CIDR address block list of the prefix list. See the following `Block entrys`.
done

2023-05-17 09:49 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_prefix_list.go
>  	if d.HasChange("entrys") {
done

2023-05-17 09:51 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_prefix_list.go
> +	}
这里的生成是可重入的

2023-05-17 09:51 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_prefix_list.go
> +				Type:     schema.TypeString,
done

2023-05-17 12:21 UTC, xiaozhu36 requested changes

2023-05-17 12:21 UTC, xiaozhu36 commented on website/docs/r/vpc_prefix_list.html.markdown
> +* `entrys` - (Deprecated) Field 'entrys' has been deprecated from provider version 1.205.0. New field 'entries' instead.
Deprecated from xxx

2023-05-18 03:28 UTC, xiaozhu36 approved these changes

2023-05-18 03:38 UTC, merged