resource/alicloud_havip: Adds new attribute ResourceGroupId, Tags etc.
aliyun/terraform-provider-alicloud pull request #6129
Opened 2023-05-09 01:31 UTC by ChenHanZhang

2023-05-15 08:01 UTC, xiaozhu36 requested changes

2023-05-15 08:01 UTC, xiaozhu36 commented on website/docs/r/havip.html.markdown
> +  zone_id      = "cn-shanghai-a"
不要写死，使用 zones 的datasource

2023-05-15 08:01 UTC, xiaozhu36 commented on website/docs/r/havip.html.markdown
> +* `resource_group_id` - (Computed, Optional) The ID of the resource group to which the VPC belongs.
描述不对

2023-05-16 15:09 UTC, xiaozhu36 requested changes

2023-05-16 15:09 UTC, xiaozhu36 commented on alicloud/resource_alicloud_havip.go
> +			"havip_name": {
嗯，如果是这样的话，资源名字是不是也应该改

2023-05-17 00:46 UTC, ChenHanZhang commented on alicloud/resource_alicloud_havip.go
> +			"havip_name": {
Spec上定义的资源名为HaVip，如果要对齐的话是需要改的

2023-05-17 12:13 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_ha_vip.go
> +	d.Set("region_id", objectRaw["RegionId"])
这里需要过滤已经忽略的属性

2023-05-17 15:28 UTC, xiaozhu36 approved these changes

2023-05-18 02:41 UTC, xiaozhu36 approved these changes

2023-05-18 04:37 UTC, merged