resource/alicloud_vpc_public_ip_address_pool: Adds new attribute ResourceGroupId, Tags etc.
aliyun/terraform-provider-alicloud pull request #6134
Opened 2023-05-10 10:58 UTC by ChenHanZhang

2023-05-10 11:47 UTC, xiaozhu36 requested changes

2023-05-10 11:47 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_public_ip_address_pool.go
> +	request = make(map[string]interface{})
参数定义和初始化可以设置到一起么

2023-05-10 11:47 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_public_ip_address_pool.go
> +	stateConf := BuildStateConf([]string{}, []string{""}, d.Timeout(schema.TimeoutDelete), 5*time.Second, vpcServiceV2.VpcPublicIpAddressPoolStateRefreshFunc(d.Id(), "Status", []string{}))
如果没有target status，那么保留为空，不要写“”

2023-05-10 11:47 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_public_ip_address_pool_test.go
> +					"public_ip_address_pool_name": "rdk-update",
name 的update 应该是在原来的基础上修改吧

2023-05-10 11:47 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_public_ip_address_pool_test.go
> +			},
schema中没有 resource_type 这个属性啊

2023-05-10 11:47 UTC, xiaozhu36 commented on website/docs/r/vpc_public_ip_address_pool.html.markdown
具体的地址丢了

2023-05-10 11:47 UTC, xiaozhu36 commented on website/docs/r/vpc_public_ip_address_pool.html.markdown
> +-> **NOTE:** Available in v1.205.0+.
这个为啥要改

2023-05-10 11:47 UTC, xiaozhu36 commented on website/docs/r/vpc_public_ip_address_pool.html.markdown
> +  region_id                   = "cn-beijing"
有 region id 这个属性么

2023-05-10 13:17 UTC, xiaozhu36 requested changes

2023-05-10 13:17 UTC, xiaozhu36 commented on alicloud/service_alicloud_vpc_v2.go
> +			if IsExpectedErrors(err, []string{"OperationConflict", "IncorrectStatus.%s", "SystemBusy", "ServiceUnavailable", "OperationFailed.LastTokenProcessing", "LastTokenProcessing"}) || NeedRetry(err) {
查询不需要重试吗

2023-05-10 13:17 UTC, xiaozhu36 commented on website/docs/r/vpc_public_ip_address_pool.html.markdown
> +  resource_group_id           = alicloud_resource_manager_resource_group.defaultRg.id
依赖资源一并生成

2023-05-10 13:17 UTC, xiaozhu36 commented on website/docs/r/vpc_public_ip_address_pool.html.markdown
> +* `total_ip_num` - Total ip number of PublicIpAddressPool.
只需要设置只读属性

2023-05-11 08:28 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_public_ip_address_pool_test.go
> +			},
done

2023-05-11 08:28 UTC, ChenHanZhang commented on website/docs/r/vpc_public_ip_address_pool.html.markdown
> +* `create_time` - The creation time of the resource.
这里只需要生成只读的属性

2023-05-11 08:50 UTC, CodeSpaceiiii commented on alicloud/resource_alicloud_vpc_public_ip_address_pool.go
> +			if IsExpectedErrors(err, []string{"OperationConflict", "IncorrectStatus.%s", "SystemBusy", "ServiceUnavailable", "OperationFailed.LastTokenProcessing", "LastTokenProcessing", "IncorrectStatus.Publ
这个%s的处理再看一下。

2023-05-12 03:35 UTC, xiaozhu36 requested changes

2023-05-12 03:35 UTC, xiaozhu36 commented on website/docs/r/vpc_public_ip_address_pool.html.markdown
> +
第二个资源组changeRg没有被用到，直接去掉

2023-05-12 03:35 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_public_ip_address_pool.go
> +	stateConf := BuildStateConf([]string{}, []string{"Created"}, d.Timeout(schema.TimeoutCreate), 5*time.Second, vpcServiceV2.VpcPublicIpAddressPoolStateRefreshFunc(d.Id(), "Status", []string{}))
如果pending时间小于5秒，就不pending了

2023-05-12 05:57 UTC, xiaozhu36 approved these changes

2023-05-12 06:29 UTC, xiaozhu36 approved these changes

2023-05-12 06:38 UTC, merged