New Resource:alicloud_tag_meta_tag
aliyun/terraform-provider-alicloud pull request #6137
Opened 2023-05-11 07:34 UTC by fuliu-zln

2023-05-11 07:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6137) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6137) before we can accept your contribution.<br/><hr/>**张利男** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=6137) it.</sub>

2023-07-10 09:28 UTC, MrWolong commented on alicloud/resource_alicloud_tag_meta_tag.go
> +	err = resource.Retry(client.GetRetryTimeout(d.Timeout(schema.TimeoutUpdate)), func() *resource.RetryError {
改
![image](https://github.com/aliyun/terraform-provider-alicloud/assets/36806235/871e61d2-4449-4855-9698-aae464662f20)

2023-07-10 09:29 UTC, MrWolong commented on website/docs/r/tag_meta_tag.html.markdown
> +-> **NOTE:** Available in v1.206.0+.
改

2023-07-11 06:16 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_meta_tag.go
> +	err = resource.Retry(client.GetRetryTimeout(d.Timeout(schema.TimeoutUpdate)), func() *resource.RetryError {
done

2023-07-11 06:27 UTC, fuliu-zln commented on website/docs/r/tag_meta_tag.html.markdown
> +-> **NOTE:** Available in v1.206.0+.
done

2023-07-11 07:31 UTC, xiaozhu36 requested changes

2023-07-11 07:40 UTC, fuliu-zln commented on website/docs/r/tag_meta_tag.html.markdown
> +subcategory: "Tag Meta Tag"
![image](https://github.com/aliyun/terraform-provider-alicloud/assets/85548684/f3f16549-e1f2-446e-ab83-e7ae12ec9578)
根据Tag同学提供的，这边修改成TAG

2023-07-13 06:29 UTC, xiaozhu36 approved these changes

2023-07-13 08:30 UTC, closed without merging