resource/alicloud_polardb_backup_policy: polardb support backup policy
aliyun/terraform-provider-alicloud pull request #6147
Opened 2023-05-16 02:03 UTC by mengliux

resource/alicloud_polardb_backup_policy: polardb support backup policy

2023-06-02 09:05 UTC, xiaozhu36 requested changes

2023-06-06 05:42 UTC, xiaozhu36 requested changes

2023-06-06 05:42 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_backup_policy_test.go
> +		"data_level2_backup_another_region_retention_period": CHECKSET,
computed 的不止这些

2023-06-06 05:42 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_backup_policy_test.go
> +				ImportStateVerifyIgnore: []string{"log_backup_another_region_region", "log_backup_another_region_retention_period"},
对于 API不能返回的，不能甚至设置为 computed

2023-06-06 05:42 UTC, xiaozhu36 commented on website/docs/r/polardb_backup_policy.html.markdown
> +* `log_backup_another_region_retention_period` - (Optional, Available in 1.207.0+) The retention period of cross-region log backups. Default value: OFF. Valid values are `0`, `30 to 7300`, `-1`.
有枚举值的，要在schema中定义出来

2023-06-07 10:06 UTC, mengliux commented on website/docs/r/polardb_backup_policy.html.markdown
> +* `log_backup_another_region_retention_period` - (Optional, Available in 1.207.0+) The retention period of cross-region log backups. Default value: OFF. Valid values are `0`, `30 to 7300`, `-1`.
已定义，并测试符合预期

2023-06-07 10:07 UTC, mengliux commented on alicloud/resource_alicloud_polardb_backup_policy_test.go
> +				ImportStateVerifyIgnore: []string{"log_backup_another_region_region", "log_backup_another_region_retention_period"},
已解决

2023-06-07 10:07 UTC, mengliux commented on alicloud/resource_alicloud_polardb_backup_policy_test.go
> +		"data_level2_backup_another_region_retention_period": CHECKSET,
已都加了

2023-06-07 11:37 UTC, xiaozhu36 requested changes

2023-06-07 11:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_backup_policy.go
> +					ValidateFunc: validation.StringInSlice([]string{"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"}, false),
所有的 validation.xxx 都改为 xxx，比如 validation.StringInSlice 改成 StringInSlice

2023-06-07 11:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_backup_policy.go
> +		d.Set("data_level1_backup_retention_period", dataLevel1BackupRetentionPeriod)
这个地方不用类型转换，直接设置就行： d.Set("data_level1_backup_retention_period", object["DataLevel1BackupRetentionPeriod"])

2023-06-08 02:18 UTC, mengliux commented on alicloud/resource_alicloud_polardb_backup_policy.go
> +		d.Set("data_level1_backup_retention_period", dataLevel1BackupRetentionPeriod)
已经修改

2023-06-08 02:19 UTC, mengliux commented on alicloud/resource_alicloud_polardb_backup_policy.go
> +					ValidateFunc: validation.StringInSlice([]string{"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"}, false),
已去掉

2023-06-08 02:56 UTC, xiaozhu36 approved these changes

2023-06-08 08:37 UTC, xiaozhu36 approved these changes

2023-06-09 02:38 UTC, xiaozhu36 requested changes

2023-06-09 02:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_backup_policy.go
> +	logBackupRetentionPeriod, _ := logBackupPolicy["LogBackupRetentionPeriod"].(json.Number).Int64()
这个地方为啥要进行类型转换，不能直接set 么

2023-06-09 02:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_backup_policy.go
> +		d.Set("data_level2_backup_another_region_retention_period", dataLevel2BackupAnotherRegionRetentionPeriod)
这个地方为啥要类型转换，而不是直接set

2023-06-09 02:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_backup_policy.go
> +	enableBackupLog, _ := logBackupPolicy["EnableBackupLog"].(json.Number).Int64()
还有这个

2023-06-09 07:34 UTC, mengliux commented on alicloud/resource_alicloud_polardb_backup_policy.go
> +	logBackupRetentionPeriod, _ := logBackupPolicy["LogBackupRetentionPeriod"].(json.Number).Int64()
可以的，当时考虑的多了，改过来了

2023-06-09 07:34 UTC, mengliux commented on alicloud/resource_alicloud_polardb_backup_policy.go
> +	enableBackupLog, _ := logBackupPolicy["EnableBackupLog"].(json.Number).Int64()
可以的，当时考虑的多了，改过来了

2023-06-09 08:12 UTC, xiaozhu36 approved these changes

2023-06-09 09:07 UTC, merged