resource/alicloud_db_instance : Support for serverless instance creation.
aliyun/terraform-provider-alicloud pull request #6155
Opened 2023-05-17 06:03 UTC by TingxuanGuo

2023-05-17 06:46 UTC, xiaozhu36 approved these changes

2023-05-18 06:19 UTC, xiaozhu36 requested changes

2023-05-18 06:19 UTC, xiaozhu36 commented on website/docs/r/db_instance.html.markdown
> +Provides an RDS instance resource.
这个地方需要保留两个空格

2023-05-18 06:24 UTC, TingxuanGuo commented on website/docs/r/db_instance.html.markdown
> +Provides an RDS instance resource.
done

2023-05-18 06:51 UTC, xiaozhu36 approved these changes

2023-05-22 07:55 UTC, xiaozhu36 approved these changes

2023-05-24 06:47 UTC, xiaozhu36 approved these changes

2023-05-25 10:05 UTC, xiaozhu36 approved these changes

2023-05-29 05:28 UTC, xiaozhu36 approved these changes

2023-05-30 06:00 UTC, xiaozhu36 approved these changes

2023-06-01 01:52 UTC, xiaozhu36 approved these changes

2023-06-02 01:24 UTC, merged