resource/alicloud_vpc_flow_log: Adds new attribute AggregationInterval,ResourceGroupId,Tags,TrafficPath etc.
aliyun/terraform-provider-alicloud pull request #6161
Opened 2023-05-18 08:50 UTC by ChenHanZhang

2023-05-18 09:25 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_flow_log.go
> +	if v, ok := d.GetOk("log_store_name"); ok {
必填的属性，不需要多一次判断

2023-05-18 09:25 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_flow_log.go
> +		if v, ok := d.GetOk("description"); ok {
HasChange下不需要再多一次判定

2023-05-18 11:53 UTC, xiaozhu36 requested changes

2023-05-18 11:53 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_flow_log.go
> +		request["TrafficPath"] = trafficPathMaps
148-150不能合并为一行么？

2023-05-18 11:53 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_flow_log.go
> +			if IsExpectedErrors(err, []string{"TaskConflict", "OperationFailed.LastTokenProcessing", "LastTokenProcessing", "IncorrectStatus", "InvalidHdMonitorStatus", "OperationConflict", "ServiceUnavailabl
缺少了UnknowError，确定可以去掉么？

2023-05-18 11:53 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_flow_log.go
> +		}
这个代码块没必要

2023-05-19 02:05 UTC, xiaozhu36 approved these changes

2023-05-19 02:25 UTC, merged