resource/alicloud_cen_bandwidth_package_attachment: Added retry stragety for error code `InvalidOperation.CenBandwidthLimitsNotZero`
aliyun/terraform-provider-alicloud pull request #6169
Opened 2023-05-22 07:55 UTC by MrWolong

2023-05-26 02:20 UTC, xiaozhu36 approved these changes

2023-05-30 07:50 UTC, xiaozhu36 requested changes

2023-05-30 07:50 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cen_bandwidth_package_attachment.go
> +		},
timeout 的信息需要在文档中声明出来

2023-05-30 08:39 UTC, MrWolong commented on alicloud/resource_alicloud_cen_bandwidth_package_attachment.go
> +		},
已修复

2023-05-30 11:16 UTC, xiaozhu36 approved these changes

2023-05-31 06:48 UTC, merged