resource/alicloud_ddoscoo_domain_resource: Removed the `ForceNew` for field `proxy_types` and `rs_type`, supports modifying them online
aliyun/terraform-provider-alicloud pull request #6173
Opened 2023-05-24 06:40 UTC by MrWolong

2023-05-26 02:28 UTC, xiaozhu36 requested changes

2023-05-26 02:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ddoscoo_domain_resource_test.go
> +							"proxy_ports": []string{"80"},
list 类型的，多测几个值

2023-05-30 03:29 UTC, MrWolong commented on alicloud/resource_alicloud_ddoscoo_domain_resource_test.go
> +							"proxy_ports": []string{"80"},
已修改

2023-05-30 07:47 UTC, xiaozhu36 requested changes

2023-05-30 08:38 UTC, MrWolong commented on alicloud/resource_alicloud_ddoscoo_domain_resource_test.go
> +					"real_servers": []string{"qq.com"},
已修复

2023-05-30 11:17 UTC, xiaozhu36 approved these changes

2023-06-02 01:27 UTC, xiaozhu36 requested changes

2023-06-02 01:27 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ddoscoo_domain_resource_test.go
> +					"real_servers": []string{"qq.com", "baidu.com", "alibaba.com"},
这个还是没改啊

2023-06-02 01:50 UTC, MrWolong commented on alicloud/resource_alicloud_ddoscoo_domain_resource_test.go
> +					"real_servers": []string{"qq.com", "baidu.com", "alibaba.com"},
已修复

2023-06-02 07:22 UTC, xiaozhu36 approved these changes

2023-06-02 07:28 UTC, merged