resource/alicloud_cdn_domain: adds new attributes: check_url, certificate_config.cert_id, certificate_config.cert_region.
aliyun/terraform-provider-alicloud pull request #6176
Opened 2023-05-24 11:52 UTC by ChenHanZhang

…cate_config.cert_id, certificate_config.cert_region.

2023-05-26 07:05 UTC, xiaozhu36 requested changes

2023-05-26 07:05 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cdn_domain_new_test.go
> +							"cert_id":                   "10162346",
这个应该用资源引用

2023-05-26 07:05 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cdn_domain_new_test.go
> -							"private_key":        testPrivateKey,
有几个删掉的属性没测到啊

2023-05-29 07:28 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cdn_domain_new.go
> +func resourceAliCloudCdnDomain() *schema.Resource {
这里的命名冲突了，之前cdn存在一个资源名为 CdnDomain ，之后改版创建了一个新的资源名为 CdnDomainNew，两个版本完全不同。目前Spec上的CDN-Domain，对应的是DomainNew

2023-05-29 07:29 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cdn_domain_new.go
> +func resourceAliCloudCdnDomain() *schema.Resource {
也就是说alicloud_cdn_domain这个code已经被占用了，而且同alicloud_cdn_domain_new完全不兼容。新生成的实际上是后者。

2023-05-29 07:30 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cdn_domain_new_test.go
> +							"cert_id":                   "10162346",
cert_id这个证书需要控制台上传，同账号绑定的，无法使用资源引用

2023-05-29 07:40 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cdn_domain_new_test.go
> -							"private_key":        testPrivateKey,
force_set 已经从新版api上移除，肖瑶表示这个参数是不安全的特性，原本就不建议用户使用，新版api不再提供支持。
此外，之前的 certificate_config 下 server_certificate_status 表示 certificate_config 是否启用，但是代码逻辑里做了两个适配：
1. 当certificate_config下其它项有值时，server_certificate_status默认开启=on；
2. 为了关闭certificate_config，即调用接口并传入server_certificate_status=off，需要将certificate_config进行移除；

这两点，可以从之前的代码实现，以及测试用例中的书写方式验证。但这种方式不推荐，因此，新版按标准的方式进行配置项的管理，server_certificate_status开启与关闭，以实际设定值为准，不在编排中使用默认行为

2023-05-30 03:06 UTC, xiaozhu36 requested changes

2023-05-30 03:06 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cdn_domain_new.go
> +			sourcesMap["weight"], _ = strconv.Atoi(sourceModelChild1Raw["Weight"].(string))
sourceModelChild1Raw["Priority"].(string) 是会存在空指针的情况，使用 ok 判断，如果不OK，set为零值

2023-05-30 03:06 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cdn_domain_new.go
> +			sourcesMap["weight"], _ = strconv.Atoi(sourceModelChild1Raw["Weight"].(string))
其他也类似

2023-05-30 03:06 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cdn_domain_new.go
> +	oldConfig := d.Get("certificate_config").([]interface{})
非必填的，而且涉及到类型转换的，用 d.GetOk

2023-05-30 03:06 UTC, xiaozhu36 commented on website/docs/r/cdn_domain_new.html.markdown
> +  default = "tf-testacc-example"
以后示例中的name 统一改为 terraform-example，尽量不要带有 test

2023-05-30 03:07 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cdn_domain_new.go
> +							Default:      80,
这里去不掉，服务端没有默认值实现，兼容已有的port实现

2023-05-31 00:53 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cdn_domain_new.go
> -							ValidateFunc: validation.StringInSlice([]string{"1", "0"}, false),
done

2023-05-31 00:53 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cdn_domain_new.go
> +			sourcesMap["weight"], _ = strconv.Atoi(sourceModelChild1Raw["Weight"].(string))
done

2023-05-31 00:53 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cdn_domain_new.go
> +		if v, ok := d.GetOk("certificate_config.0.cert_name"); ok {
这里还是需要GetOk的判定，这个接口cert_name不能传空值

2023-05-31 00:53 UTC, ChenHanZhang commented on alicloud/resource_alicloud_cdn_domain_new.go
> +		if v, ok := d.GetOk("certificate_config.0.cert_name"); ok {
d.GetOk 会判定是否非空值，字符串的空值就是空串，空串时就不传值

2023-05-31 02:14 UTC, ChenHanZhang commented on website/docs/r/cdn_domain_new.html.markdown
> +* `resource_group_id` - (Optional, Computed) The ID of the resource group.
done

2023-05-31 08:57 UTC, xiaozhu36 approved these changes

2023-06-01 07:56 UTC, xiaozhu36 approved these changes

2023-06-01 22:43 UTC, merged