New resource/alicloud_redis_tair_instance.
aliyun/terraform-provider-alicloud pull request #6178
Opened 2023-05-25 04:46 UTC by ChenHanZhang

2023-05-25 07:41 UTC, ChenHanZhang commented on website/docs/r/kvstore_tair_instance.html.markdown
> +For information about Redis Tair Instance and how to use it, see [What is Tair Instance](https://www.alibabacloud.com/help/en/).
这里的链接，需要维护到镇元上去。

2023-05-26 06:57 UTC, xiaozhu36 requested changes

2023-05-26 06:57 UTC, xiaozhu36 commented on alicloud/provider.go
> +			"alicloud_kvstore_tair_instance":              resourceAliCloudRedisTairInstance(),
这个是不是可以直接命名为 alicloud_redis_tair_instance

2023-05-26 06:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_tair_instance.go
> +				Default:  "false",
默认值

2023-05-26 06:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_tair_instance.go
> +				Default:      "Immediately",
这个也一样

2023-05-26 06:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_tair_instance.go
> +				Computed: true,
version没有枚举值么

2023-05-26 06:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_tair_instance.go
> +				Required: true,
instance_type 没有枚举值么

2023-05-26 06:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_tair_instance.go
> +			"new_password": {
为啥会有 new_password

2023-05-26 06:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_tair_instance.go
> +				Optional: true,
period 没有枚举值么？另外，这个应该是 int类型吧

2023-05-26 06:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_tair_instance.go
> +				ForceNew: true,
resource_group_id 需要支持修改

2023-05-26 06:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_tair_instance.go
> +				Default:      2,
默认值

2023-05-26 06:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_tair_instance.go
> +			"vpc_cloud_instance_id": {
vpc_cloud_instance_id 跟 vpc_id 的区别是啥

2023-05-26 06:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_tair_instance_test.go
> +					"instance_class":     "tair.rdb.1g",
instance_class 是不是可以通过 datasource 动态获取

2023-05-29 03:17 UTC, ChenHanZhang commented on alicloud/provider.go
> +			"alicloud_kvstore_tair_instance":              resourceAliCloudRedisTairInstance(),
done。这里一开始延续了老生成器上其pipcode逻辑，已经修改掉，后续存量的code生成，除非已经做了code级别的映射，新的资源类型以spec code为准。

2023-05-29 03:17 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kvstore_tair_instance.go
> +				Default:  "false",
done

2023-05-29 03:17 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kvstore_tair_instance.go
> +				Default:      "Immediately",
done

2023-05-29 03:17 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kvstore_tair_instance.go
> +				Default:      2,
done

2023-05-31 02:10 UTC, ChenHanZhang commented on alicloud/resource_alicloud_redis_tair_instance.go
> +				Type:     schema.TypeString,
api上是一个string类型，同api保持一致

2023-05-31 02:10 UTC, ChenHanZhang commented on alicloud/resource_alicloud_redis_tair_instance.go
> +			"engine_version": {
文档上没有枚举值，只说明默认取1.0，不需要配置

2023-05-31 02:10 UTC, ChenHanZhang commented on alicloud/resource_alicloud_redis_tair_instance.go
> +			"instance_class": {
同上，文档中注明了规格的查询链接

2023-05-31 02:13 UTC, ChenHanZhang commented on alicloud/resource_alicloud_redis_tair_instance.go
> +				Type:     schema.TypeInt,
文档上存在取值范围1024~65535，需要补充回去

2023-05-31 10:18 UTC, xiaozhu36 requested changes

2023-05-31 10:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_redis_tair_instance_test.go
> +					"instance_class":     "tair.rdb.1g",
这个instance class 是不是应该用 datasource来动态获取

2023-05-31 10:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_redis_tair_instance_test.go
> +					}),
这个值跟第一步的一样

2023-05-31 10:18 UTC, xiaozhu36 commented on alicloud/resource_alicloud_redis_tair_instance.go
> +			"auto_pay": {
auto_pay 应该是常量硬编码到代码中

2023-05-31 10:18 UTC, xiaozhu36 commented on website/docs/r/redis_tair_instance.html.markdown
> +  vpc_name    = "${var.name}1"
不需要 “${}” 格式

2023-05-31 10:18 UTC, xiaozhu36 commented on website/docs/r/redis_tair_instance.html.markdown
> +
预付费不能删除的时候，需要增加上note 信息

2023-06-01 11:54 UTC, xiaozhu36 requested changes

2023-06-01 11:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_redis_tair_instance.go
> +				Optional: true,
password 需要设置为 sensitive

2023-06-01 11:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_redis_tair_instance.go
> +				Type:     schema.TypeString,
如果不是多级ID，instance id 不需要再输出一次

2023-06-01 11:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_redis_tair_instance_test.go
> +var AlicloudRedisTairInstanceMap3340 = map[string]string{}
所有computed的需要在map中check出来

2023-06-02 00:28 UTC, ChenHanZhang commented on alicloud/resource_alicloud_redis_tair_instance.go
> +				Optional: true,
done，新增一条规则，password需要设置敏感字段

2023-06-02 00:42 UTC, ChenHanZhang commented on alicloud/resource_alicloud_redis_tair_instance.go
> +				Type:     schema.TypeString,
done

2023-06-02 00:42 UTC, ChenHanZhang commented on alicloud/resource_alicloud_redis_tair_instance.go
> +				Optional: true,
done，新增一条规则，password需要设置敏感字段

2023-06-02 00:42 UTC, ChenHanZhang commented on alicloud/resource_alicloud_redis_tair_instance_test.go
> +var AlicloudRedisTairInstanceMap3340 = map[string]string{}
done

2023-06-02 03:04 UTC, xiaozhu36 requested changes

2023-06-02 03:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_redis_tair_instance_test.go
> +	"status":            CHECKSET,
这个地方不全吧，比如 effective_time

2023-06-02 05:57 UTC, ChenHanZhang commented on alicloud/resource_alicloud_redis_tair_instance_test.go
> +	"status":            CHECKSET,
done，effective_time是操作私有属性，但配置了默认值，导致生成的时候被视为Computed类型，因而这里的校验自动加上了CHECKSET，已优化

2023-06-02 06:22 UTC, xiaozhu36 approved these changes

2023-06-02 06:35 UTC, merged