Improves the docs example
aliyun/terraform-provider-alicloud pull request #6180
Opened 2023-05-25 07:34 UTC by susu9527

2023-05-25 07:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6180) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6180) before we can accept your contribution.<br/><hr/>**wb-ssc771735** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=6180) it.</sub>

2023-05-29 08:21 UTC, xiaozhu36 requested changes

2023-05-29 08:21 UTC, xiaozhu36 commented on website/docs/r/ecs_snapshot.html.markdown
> +  instance_type        = "ecs.n4.small"
实例规格也一样

2023-05-29 08:21 UTC, xiaozhu36 commented on website/docs/r/vpn_route_entry.html.markdown
> +  vpc_name   = "tf_test"
example 中的name，尽量不要用 test ，可以用 terraform-example

2023-05-29 08:21 UTC, xiaozhu36 commented on website/docs/r/vswitch.html.markdown
> +  enable_details              = true
enable_details 就不用设置了

2023-05-29 10:05 UTC, susu9527 commented on website/docs/r/ecs_capacity_reservation.html.markdown
> +
已改

2023-05-29 10:06 UTC, susu9527 commented on website/docs/r/ecs_capacity_reservation.html.markdown
> +  zone_ids = ["cn-hangzhou-g"]
已改

2023-05-29 10:06 UTC, susu9527 commented on website/docs/r/ecs_snapshot.html.markdown
> +  image_id             = "ubuntu_18_04_64_20G_alibase_20190624.vhd"
已改

2023-05-29 10:06 UTC, susu9527 commented on website/docs/r/ecs_snapshot.html.markdown
> +  instance_type        = "ecs.n4.small"
已改

2023-05-29 10:06 UTC, susu9527 commented on website/docs/r/vpn_route_entry.html.markdown
> +  vpc_name   = "tf_test"
已改

2023-05-29 10:06 UTC, susu9527 commented on website/docs/r/vswitch.html.markdown
> +  enable_details              = true
已改

2023-05-29 11:22 UTC, xiaozhu36 requested changes

2023-05-29 11:22 UTC, xiaozhu36 commented on website/docs/r/ecs_key_pair_attachment.html.markdown
> +  instance_type        = "ecs.n4.small"
这几个还是没改啊

2023-05-29 11:22 UTC, xiaozhu36 commented on website/docs/r/ecs_launch_template.html.markdown
> +    name_regex = "^default-NODELETING$"
vpc 这种改成创建新的vpc 资源

2023-05-29 11:22 UTC, xiaozhu36 commented on website/docs/r/ecs_launch_template.html.markdown
> +  default = "example_value"
改成 terraform-example

2023-05-29 11:22 UTC, xiaozhu36 commented on website/docs/r/vpn_ipsec_server.html.markdown
> +  vpc_name   = "tf_test_foo"
这个name

2023-05-29 11:22 UTC, xiaozhu36 commented on website/docs/r/vswitch.html.markdown
> +  vswitch_name = "tf_test_foo"
这个

2023-05-30 03:30 UTC, xiaozhu36 requested changes

2023-05-30 03:30 UTC, xiaozhu36 commented on website/docs/r/ecs_key_pair_attachment.html.markdown
> +  depends_on    = [alicloud_ecs_key_pair.example, alicloud_instance.example]
这个地方不需要 depends_on

2023-05-30 03:30 UTC, xiaozhu36 commented on website/docs/r/ecs_key_pair_attachment.html.markdown
> +  key_pair_name = "terraform-example"
key pair name 应该直接引用alicloud_ecs_key_pair.example.key_pair_name

2023-05-30 03:44 UTC, xiaozhu36 requested changes

2023-05-30 03:44 UTC, xiaozhu36 commented on website/docs/r/ecs_snapshot.html.markdown
> +  depends_on = [alicloud_ecs_disk.example, alicloud_ecs_disk_attachment.example]
这个也一样，不需要depend_on

2023-05-30 07:46 UTC, closed without merging