resource/alicloud_quotas_quota_application: adds new attributes application_id, create_time, effective_time.
aliyun/terraform-provider-alicloud pull request #6183
Opened 2023-05-25 11:35 UTC by ChenHanZhang

2023-05-26 06:44 UTC, xiaozhu36 requested changes

2023-05-26 06:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_quotas_quota_application_test.go
> +func SkipTestAccAlicloudQuotasQuotaApplication_basic3294_twin(t *testing.T) {
这个为啥跳过

2023-05-26 06:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_quotas_quota_application.go
> +			"env_language": {
新增加的属性要在title 上体现出来

2023-05-26 06:44 UTC, xiaozhu36 commented on website/docs/r/quotas_quota_application.html.markdown
> +* `audit_mode` - (Optional, ForceNew, Computed) Quota audit mode. Value:-Sync: Synchronize auditing. The quota center automatically approves, and the approval result is returned immediately, but the
两个枚举值要换行并且使用无需列表形式展示

2023-05-26 06:44 UTC, xiaozhu36 commented on website/docs/r/quotas_quota_application.html.markdown
> +* `quota_category` - (Optional, ForceNew) The quota type.-CommonQuota (default): Generic quota.-FlowControl:API rate quota.-WhiteListLabel: Equity quota.
这个也一样

2023-05-26 07:02 UTC, ChenHanZhang commented on alicloud/resource_alicloud_quotas_quota_application_test.go
> +func SkipTestAccAlicloudQuotasQuotaApplication_basic3294_twin(t *testing.T) {
不可重复创建，这个和紫盈对过，Quota申请需要到云产品审批，审批动作不完成，这个用例就不能重复执行，而且其中的配额数只能增加不能减少，另外这个资源不可删除的。所以本地测试通过后跳过了。

2023-05-29 05:54 UTC, ChenHanZhang commented on alicloud/resource_alicloud_quotas_quota_application.go
> -				Default:      0,
和紫盈确认核对，notice_type只支持0和3

2023-05-29 05:54 UTC, ChenHanZhang commented on alicloud/resource_alicloud_quotas_template_quota.go
> +func resourceAliCloudQuotasTemplateQuota() *schema.Resource {
资源名已经同紫盈确认，命名为TemplateQuota

2023-05-29 05:54 UTC, ChenHanZhang commented on alicloud/resource_alicloud_quotas_template_quota.go
> +			"notice_type": {
需要确认一下是否存在枚举值

2023-05-29 05:54 UTC, ChenHanZhang commented on alicloud/resource_alicloud_quotas_template_quota.go
> +		d.SetPartial("desire_value")
不是多个update，不需要SetPartial

2023-05-29 06:57 UTC, ChenHanZhang commented on alicloud/resource_alicloud_quotas_quota_application.go
> -				Type:     schema.TypeFloat,
done

2023-05-29 07:07 UTC, ChenHanZhang commented on alicloud/resource_alicloud_quotas_template_quota.go
> +		d.SetPartial("desire_value")
done

2023-05-31 05:45 UTC, ChenHanZhang commented on alicloud/resource_alicloud_quotas_quota_application.go
> +			"env_language": {
done

2023-05-31 05:48 UTC, ChenHanZhang commented on website/docs/r/quotas_quota_alarm.html.markdown
> +Provides a Quotas Quota Alarm resource. .
多一个句号

2023-05-31 11:46 UTC, xiaozhu36 requested changes

2023-06-01 05:47 UTC, ChenHanZhang commented on website/docs/r/quotas_quota_alarm.html.markdown
> +Provides a Quotas Quota Alarm resource. .
done

2023-06-02 01:40 UTC, ChenHanZhang commented on alicloud/resource_alicloud_quotas_quota_alarm_test.go
> +var AlicloudQuotasQuotaAlarmMap2901 = map[string]string{}
done

2023-06-02 01:40 UTC, ChenHanZhang commented on alicloud/resource_alicloud_quotas_quota_application.go
> +	log.Printf("[WARN] Cannot destroy resource AliCloud Resource Quota Application. Terraform will remove this resource from the state file, however resources may remain.")
done

2023-06-02 01:55 UTC, ChenHanZhang commented on alicloud/resource_alicloud_quotas_quota_application.go
> -				Default:      0,
done

2023-06-02 03:07 UTC, xiaozhu36 approved these changes

2023-06-02 03:41 UTC, merged