resource/alicloud_ga_listener: Fixed `proxy_protocol` invalid error
aliyun/terraform-provider-alicloud pull request #6184
Opened 2023-05-26 08:37 UTC by MrWolong

2023-05-30 09:10 UTC, MrWolong commented on alicloud/resource_alicloud_ga_listener_test.go
> -				ResourceName:            resourceId,
删除原因是，接口本身就返回的

2023-05-30 09:52 UTC, MrWolong commented on alicloud/resource_alicloud_ga_listener_test.go
> -				ImportStateVerifyIgnore: []string{"accelerator_id", "proxy_protocol"},
accelerator_id和proxy_protocol，查询接口是可以正常返回的

2023-05-31 06:59 UTC, xiaozhu36 requested changes

2023-05-31 06:59 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_listener.go
>  			"proxy_protocol": {
validation.StringInSlice 相关的要修改下

2023-05-31 08:06 UTC, MrWolong commented on alicloud/resource_alicloud_ga_listener.go
>  			},
已修复

2023-05-31 08:50 UTC, MrWolong commented on website/docs/r/ga_listener.html.markdown
> +* `proxy_protocol` - (Optional, Computed) The proxy protocol of the listener. Default value is `false`. Valid values:
已修复

2023-06-02 01:26 UTC, xiaozhu36 approved these changes

2023-06-02 07:23 UTC, xiaozhu36 approved these changes

2023-06-02 07:39 UTC, merged