New resource/alicloud_vpc_route_table; New resource/alicloud_vpc_network_acl; resource/alicloud_vpc_gateway_route_table_attachment: add new attribute create_time; resource/alicloud_vpc_ipv6_egress_rule: optimized implementation; resource/alicloud_vpc_traffic_mirror_filter: adds new attributes egress_rules, ingress_rules, resource_group_id, tags; resource/alicloud_vpc_traffic_mirror_session: adds new attributes resource_group_id, tags.
aliyun/terraform-provider-alicloud pull request #6186
Opened 2023-05-30 01:32 UTC by ChenHanZhang

2023-06-01 11:50 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_gateway_route_table_attachment.go
>  		Read:   resourceAlicloudVpcGatewayRouteTableAttachmentRead,
done

2023-06-01 11:51 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_gateway_route_table_attachment.go
> -func resourceAlicloudVpcGatewayRouteTableAttachmentUpdate(d *schema.ResourceData, meta interface{}) error {
done

2023-06-01 11:52 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_ipv6_egress_rule.go
> -				ValidateFunc: validation.StringLenBetween(2, 256),
done

2023-06-01 11:52 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_ipv6_egress_rule.go
> -				ValidateFunc: validation.StringMatch(regexp.MustCompile("^[a-zA-Z\u4E00-\u9FA5][\u4E00-\u9FA5A-Za-z0-9_-]{2,128}$"), "The name must be `2` to `128` characters in length, and can contain letters,
done

2023-06-02 02:47 UTC, ChenHanZhang commented on website/docs/r/network_acl.html.markdown
> --> **NOTE:** Available in 1.43.0+. Currently, the resource are only available in Hongkong(cn-hongkong), India(ap-south-1), and Indonesia(ap-southeast-1) regions.
这里的版本需要维护

2023-06-02 02:47 UTC, ChenHanZhang commented on website/docs/r/network_acl.html.markdown
> +* `description` - (Optional) Give the description information of the direction rule.
描述信息需要补全

2023-06-02 02:47 UTC, ChenHanZhang commented on website/docs/r/route_table.html.markdown
> +-> **NOTE:** Available in v1.206.0+.
route_table没有初始可用版本

2023-06-02 02:47 UTC, ChenHanZhang commented on website/docs/r/vpc_traffic_mirror_filter.html.markdown
> --> **NOTE:** Available in v1.140.0+.
版本信息

2023-06-02 02:47 UTC, ChenHanZhang commented on website/docs/r/vpc_traffic_mirror_filter.html.markdown
> +* `destination_port_range` - (Optional, ForceNew) DestinationPortRange.
描述过于简单，要同api文档保持一致

2023-06-02 02:47 UTC, ChenHanZhang commented on website/docs/r/vpc_traffic_mirror_filter.html.markdown
> -* `dry_run` - (Optional) The dry run.
dry_run丢失

2023-06-02 02:47 UTC, ChenHanZhang commented on website/docs/r/vpc_traffic_mirror_session.html.markdown
> -For information about VPC Traffic Mirror Session and how to use it, see [What is Traffic Mirror Session](https://www.alibabacloud.com/help/en/doc-detail/261364.htm).
这里的链接是否可以直接维护到spec上，目前暂时在生成器上维护

2023-06-02 03:00 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_network_acl.go
> +							Optional: true,
有限定范围，但比较复杂，无法通过一个正则表达式表达：
当入方向规则的Protocol（协议类型）为all、icmp或gre时，端口范围为-1/-1，表示不限制端口。
当入方向规则的Protocol（协议类型）为tcp或udp时，端口范围为1~65535，格式为1/200或80/80，表示端口1到端口200或端口80。

2023-06-02 05:52 UTC, ChenHanZhang commented on website/docs/r/vpc_traffic_mirror_session.html.markdown
> -For information about VPC Traffic Mirror Session and how to use it, see [What is Traffic Mirror Session](https://www.alibabacloud.com/help/en/doc-detail/261364.htm).
done

2023-06-02 05:52 UTC, ChenHanZhang commented on website/docs/r/vpc_traffic_mirror_filter.html.markdown
> -* `dry_run` - (Optional) The dry run.
done

2023-06-02 05:52 UTC, ChenHanZhang commented on website/docs/r/vpc_traffic_mirror_filter.html.markdown
> +* `destination_port_range` - (Optional, ForceNew) DestinationPortRange.
done

2023-06-02 05:52 UTC, ChenHanZhang commented on website/docs/r/vpc_traffic_mirror_filter.html.markdown
> --> **NOTE:** Available in v1.140.0+.
done

2023-06-02 05:52 UTC, ChenHanZhang commented on website/docs/r/route_table.html.markdown
> +-> **NOTE:** Available in v1.206.0+.
done

2023-06-02 05:52 UTC, ChenHanZhang commented on website/docs/r/network_acl.html.markdown
> +* `description` - (Optional) Give the description information of the direction rule.
done

2023-06-02 05:52 UTC, ChenHanZhang commented on website/docs/r/network_acl.html.markdown
> --> **NOTE:** Available in 1.43.0+. Currently, the resource are only available in Hongkong(cn-hongkong), India(ap-south-1), and Indonesia(ap-southeast-1) regions.
done

2023-06-02 05:52 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_gateway_route_table_attachment.go
> -			"dry_run": {
done

2023-06-02 05:53 UTC, ChenHanZhang commented on alicloud/provider.go
> +			"alicloud_vpc_network_acl":                    resourceAliCloudVpcNetworkAcl(),
done

2023-06-02 05:53 UTC, ChenHanZhang commented on website/docs/r/vpc_network_acl.html.markdown
> +For information about Vpc Network Acl and how to use it, see [What is Network Acl](https://www.alibabacloud.com/help/en/).
done

2023-06-02 05:53 UTC, ChenHanZhang commented on website/docs/r/vpc_ipv6_egress_rule.html.markdown
> +* `description` - (Optional, ForceNew, Available in v1.142.0+) Description.
done

2023-06-02 05:53 UTC, ChenHanZhang commented on website/docs/r/vpc_ipv6_egress_rule.html.markdown
> +resource "alicloud_vpc_ipv6_egress_rule" "default" {
done

2023-06-02 05:53 UTC, ChenHanZhang commented on website/docs/r/vpc_gateway_route_table_attachment.html.markdown
> +  -**Creating**: The function is being created.
done

2023-06-02 05:53 UTC, ChenHanZhang commented on website/docs/r/vpc_gateway_route_table_attachment.html.markdown
> +
done

2023-06-02 06:33 UTC, xiaozhu36 requested changes

2023-06-02 06:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_route_table.go
> +			"vswitch_ids": {
这个需要输出么？

2023-06-02 06:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_ipv6_egress_rule_test.go
>  					"instance_id":           "${data.alicloud_vpc_ipv6_addresses.default.ids.0}",
为啥这个地方不直接用 alicloud_vpc_ipv6_gateway.example

2023-06-02 06:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_traffic_mirror_session.go
> +				Required: true,
补回了么？

2023-06-02 06:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vpc_traffic_mirror_session.go
> +				Optional: true,
补回了么

2023-06-02 06:33 UTC, xiaozhu36 commented on website/docs/r/network_acl.html.markdown
> -  }
这个示例为啥删掉

2023-06-02 06:47 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_ipv6_egress_rule_test.go
>  					"instance_id":           "${data.alicloud_vpc_ipv6_addresses.default.ids.0}",
done

2023-06-02 07:23 UTC, ChenHanZhang commented on website/docs/r/network_acl.html.markdown
> -  }
自动生成的例子比较简单，这些先改回原先的例子，考虑一下示例代码怎么进行维护。目前示例代码是之前从已发布的测试用例中取最新的生成，场景相对简单。

2023-06-02 07:29 UTC, ChenHanZhang commented on alicloud/resource_alicloud_route_table.go
> +			"vswitch_ids": {
VSwitchIds之前在生成器上标记了是Computed类型，所以透出了。已去掉

2023-06-02 07:35 UTC, ChenHanZhang commented on website/docs/r/network_acl.html.markdown
> -  }
done

2023-06-02 07:50 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_traffic_mirror_filter.go
> -				ValidateFunc: validation.All(validation.StringLenBetween(1, 256), validation.StringDoesNotMatch(regexp.MustCompile(`(^http://.*)|(^https://.*)`), "The description cannot start with `http://` or `
done

2023-06-02 07:50 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_traffic_mirror_filter.go
> -			request["DryRun"] = v
done

2023-06-02 07:50 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_traffic_mirror_session.go
> -				ValidateFunc: validation.StringMatch(regexp.MustCompile("^[a-zA-Z\u4E00-\u9FA5][\u4E00-\u9FA5A-Za-z0-9_-]{2,128}$"), "The name must be `2` to `128` characters in length and can contain digits, un
done

2023-06-02 07:50 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vpc_traffic_mirror_session.go
> +				Type:     schema.TypeInt,
done

2023-06-02 07:50 UTC, ChenHanZhang commented on website/docs/r/vpc_gateway_route_table_attachment.html.markdown
> -For information about VPC Gateway Route Table Attachment and how to use it, see [What is Gateway Route Table Attachment](https://www.alibabacloud.com/help/doc-detail/174112.htm).
done

2023-06-02 09:23 UTC, merged