New resource/alicloud_cbwp_common_bandwidth_package.
aliyun/terraform-provider-alicloud pull request #6187
Opened 2023-05-30 01:39 UTC by ChenHanZhang

2023-06-09 01:49 UTC, ChenHanZhang commented on alicloud/resource_alicloud_common_bandwidth_package.go
> +			Create: schema.DefaultTimeout(5 * time.Minute),
这里的时间不能变短

2023-06-09 01:49 UTC, ChenHanZhang commented on alicloud/resource_alicloud_common_bandwidth_package.go
> +			"create_time": {
体现到标题上

2023-06-09 01:49 UTC, ChenHanZhang commented on alicloud/resource_alicloud_common_bandwidth_package.go
> -				ValidateFunc: validation.StringLenBetween(2, 256),
长度限制

2023-06-09 01:49 UTC, ChenHanZhang commented on alicloud/resource_alicloud_common_bandwidth_package.go
> +				ValidateFunc: StringInSlice([]string{"BGP", "BGP_PRO", "ChinaTelecom", "ChinaUnicom", "ChinaMobile", "ChinaTelecom_L2", "ChinaUnicom_L2", "ChinaMobile_L2"}, false),
丢失了BGP_FinanceCloud

2023-06-09 01:49 UTC, ChenHanZhang commented on alicloud/resource_alicloud_common_bandwidth_package.go
> -				ValidateFunc: validation.IntBetween(10, 100),
取值范围

2023-06-09 01:49 UTC, ChenHanZhang commented on website/docs/r/common_bandwidth_package.html.markdown
> +
存在不可删除的资源类型要说明

2023-06-09 02:20 UTC, ChenHanZhang commented on alicloud/resource_alicloud_common_bandwidth_package.go
> +			Create: schema.DefaultTimeout(5 * time.Minute),
done

2023-06-09 02:20 UTC, ChenHanZhang commented on alicloud/resource_alicloud_common_bandwidth_package.go
> +			"create_time": {
done

2023-06-09 02:21 UTC, ChenHanZhang commented on alicloud/resource_alicloud_common_bandwidth_package.go
> -				ValidateFunc: validation.StringLenBetween(2, 256),
done

2023-06-09 02:21 UTC, ChenHanZhang commented on alicloud/resource_alicloud_common_bandwidth_package.go
> +				ValidateFunc: StringInSlice([]string{"BGP", "BGP_PRO", "ChinaTelecom", "ChinaUnicom", "ChinaMobile", "ChinaTelecom_L2", "ChinaUnicom_L2", "ChinaMobile_L2"}, false),
done

2023-06-09 02:21 UTC, ChenHanZhang commented on alicloud/resource_alicloud_common_bandwidth_package.go
> -				ValidateFunc: validation.IntBetween(10, 100),
done

2023-06-09 03:01 UTC, ChenHanZhang commented on website/docs/r/common_bandwidth_package.html.markdown
> +
done

2023-06-13 05:36 UTC, xiaozhu36 requested changes

2023-06-13 05:36 UTC, xiaozhu36 commented on website/docs/r/common_bandwidth_package.html.markdown
> +* `payment_type` - The billing type of the Internet Shared Bandwidth instance. Value:PayAsYouGo: Billing by VolumeSubscription: Package year and month.
payment_type 这个不是入参么？
另外，Subscription 跟前面的单词连起来了

2023-06-13 05:36 UTC, xiaozhu36 commented on website/docs/r/common_bandwidth_package.html.markdown
> +$ terraform import alicloud_cbwp_common_bandwidth_package.example <id>
资源类型不对

2023-06-13 08:10 UTC, ChenHanZhang commented on website/docs/r/common_bandwidth_package.html.markdown
> +$ terraform import alicloud_cbwp_common_bandwidth_package.example <id>
done，之前模板中使用的变量有误

2023-06-13 08:18 UTC, ChenHanZhang commented on website/docs/r/common_bandwidth_package.html.markdown
> +* `payment_type` - The billing type of the Internet Shared Bandwidth instance. Value:PayAsYouGo: Billing by VolumeSubscription: Package year and month.
不是入参，是出参，入参有另外一个名为internet_charge_type的字段用户指定购买的带宽类型。在https://next.api.aliyun.com/document/Vpc/2016-04-28/DescribeCommonBandwidthPackages 这个API上有另一个名为InstanceChargeType的字段代表实例的付费类型（共享带宽实例的计费类型：PostPaid：按量计费；PrePaid：包年包月。）。描述文档有问题已修改。

2023-06-14 07:58 UTC, xiaozhu36 requested changes

2023-06-14 07:58 UTC, xiaozhu36 commented on alicloud/resource_alicloud_common_bandwidth_package_test.go
> +				ImportStateVerifyIgnore: []string{"force", "zone", "force"},
重复了

2023-06-15 00:25 UTC, ChenHanZhang commented on alicloud/resource_alicloud_common_bandwidth_package_test.go
> +				ImportStateVerifyIgnore: []string{"force", "zone", "force"},
done

2023-06-15 08:36 UTC, xiaozhu36 requested changes

2023-06-15 08:36 UTC, xiaozhu36 commented on alicloud/resource_alicloud_common_bandwidth_package.go
> +				Computed: true,
bool 类型默认就是 false，因此此处不需要设置 Computed

2023-06-15 09:07 UTC, ChenHanZhang commented on alicloud/resource_alicloud_common_bandwidth_package.go
> +				Computed: true,
done，优化生成器，bool类型移除Computed标记

2023-06-15 09:53 UTC, xiaozhu36 approved these changes

2023-06-15 11:00 UTC, merged