resource/alicloud_alb_load_balancer: Added the limit of the field `tags`
aliyun/terraform-provider-alicloud pull request #6191
Opened 2023-05-30 06:41 UTC by MrWolong

2023-05-31 06:57 UTC, xiaozhu36 requested changes

2023-05-31 06:57 UTC, xiaozhu36 commented on website/docs/r/alb_load_balancer.html.markdown
> +* `tags` - (Optional) A mapping of tags to assign to the resource. **NOTE:** From version 1.206.0, The Key of `tags` cannot begin with "aliyun", "acs:", "http://", "https://", "ack" or "ingress".
这个From version 1.206.0去掉，任何时候都不能设置那些tag

2023-05-31 07:22 UTC, MrWolong commented on website/docs/r/alb_load_balancer.html.markdown
> +* `tags` - (Optional) A mapping of tags to assign to the resource. **NOTE:** From version 1.206.0, The Key of `tags` cannot begin with "aliyun", "acs:", "http://", "https://", "ack" or "ingress".
已修复

2023-06-02 01:24 UTC, xiaozhu36 requested changes

2023-06-02 01:24 UTC, xiaozhu36 commented on website/docs/r/alb_load_balancer.html.markdown
> +* `tags` - (Optional) A mapping of tags to assign to the resource. **NOTE:** Whenever, The Key of `tags` cannot begin with "aliyun", "acs:", "http://", "https://", "ack" or "ingress".
Whenever,  去掉

2023-06-02 01:51 UTC, MrWolong commented on website/docs/r/alb_load_balancer.html.markdown
> +* `tags` - (Optional) A mapping of tags to assign to the resource. **NOTE:** Whenever, The Key of `tags` cannot begin with "aliyun", "acs:", "http://", "https://", "ack" or "ingress".
已修复

2023-06-02 07:22 UTC, xiaozhu36 approved these changes

2023-06-02 09:17 UTC, merged