resource/alicloud_rds_clone_db_instance:Add MySQL Cluster Edition Clone
aliyun/terraform-provider-alicloud pull request #6201
Opened 2023-06-01 08:13 UTC by zcc01029273

2023-06-02 01:16 UTC, xiaozhu36 requested changes

2023-06-02 01:16 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				ValidateFunc: validation.StringInSlice([]string{"AlwaysOn", "Basic", "Finance", "HighAvailability", "serverless_basic", "cluster"}, false),
validation.xxx，统一改为 xxx

2023-06-02 01:16 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +	ra := resourceAttrInit(resourceId, cloneInstanceBasicMap)
对于 Computed 的属性，需要在 cloneInstanceBasicMap 中增加上检查

2023-06-02 01:16 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +			},
既然是新的类型 cluster，那么其他相关属性的变更也要测试下

2023-06-05 05:42 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_clone_db_instance.go
> +				ValidateFunc: validation.StringInSlice([]string{"AlwaysOn", "Basic", "Finance", "HighAvailability", "serverless_basic", "cluster"}, false),
done

2023-06-05 05:42 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +	ra := resourceAttrInit(resourceId, cloneInstanceBasicMap)
done

2023-06-05 05:43 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_clone_db_instance_test.go
> +			},
done

2023-06-05 07:05 UTC, xiaozhu36 approved these changes

2023-06-08 02:46 UTC, xiaozhu36 approved these changes

2023-06-08 09:55 UTC, xiaozhu36 approved these changes

2023-06-09 05:40 UTC, xiaozhu36 approved these changes

2023-06-09 06:35 UTC, xiaozhu36 approved these changes

2023-06-12 02:28 UTC, xiaozhu36 approved these changes

2023-06-12 02:44 UTC, xiaozhu36 approved these changes

2023-06-12 07:36 UTC, merged