resource/alicloud_sae_application_scaling_rule: Added the field `namespace_short_id` and `enable_micro_registration`
aliyun/terraform-provider-alicloud pull request #6202
Opened 2023-06-01 09:27 UTC by MrWolong

2023-06-01 09:33 UTC, MrWolong commented on alicloud/resource_alicloud_sae_namespace_test.go
> +func TestAccAlicloudSAENamespace_basic1(t *testing.T) {
增加了一个只有namespace_short_id，没有namespace_id的测试用例

2023-06-02 07:25 UTC, xiaozhu36 requested changes

2023-06-02 07:25 UTC, xiaozhu36 commented on alicloud/resource_alicloud_sae_namespace.go
> +				ExactlyOneOf: []string{"namespace_id", "namespace_short_id"},
不用在两个字段上都写 ExactlyOneOf

2023-06-02 07:50 UTC, MrWolong commented on alicloud/resource_alicloud_sae_namespace.go
> +				ExactlyOneOf: []string{"namespace_id", "namespace_short_id"},
已修复

2023-06-02 08:17 UTC, xiaozhu36 approved these changes

2023-06-02 08:28 UTC, merged