resource/alicloud_cms_site_monitor: Supported `interval` set to `30`, `60`
aliyun/terraform-provider-alicloud pull request #6217
Opened 2023-06-06 08:01 UTC by MrWolong

2023-06-07 11:26 UTC, xiaozhu36 requested changes

2023-06-07 11:26 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cms_site_monitor.go
> +				ValidateFunc: validation.IntInSlice([]int{1, 5, 15, 30, 60}),
validation 去掉

2023-06-07 11:26 UTC, xiaozhu36 commented on website/docs/r/cms_site_monitor.html.markdown
> +#### Timeouts
Timeouts 前面改成两个井号

2023-06-08 03:28 UTC, MrWolong commented on alicloud/resource_alicloud_cms_site_monitor.go
> +				ValidateFunc: validation.IntInSlice([]int{1, 5, 15, 30, 60}),
已修复

2023-06-08 03:28 UTC, MrWolong commented on website/docs/r/cms_site_monitor.html.markdown
> +#### Timeouts
已修复

2023-06-08 09:31 UTC, xiaozhu36 approved these changes

2023-06-08 09:44 UTC, merged