resource/alicloud_kms_key: Added the field tags
aliyun/terraform-provider-alicloud pull request #6222
Opened 2023-06-07 09:00 UTC by MrWolong

2023-06-07 11:28 UTC, xiaozhu36 requested changes

2023-06-07 11:28 UTC, xiaozhu36 commented on website/docs/r/kms_key.html.markdown
> +* `is_enabled` - (Deprecated) Field `is_enabled` has been deprecated from provider version 1.85.0. New field `key_state` instead.
改成 Deprecated since xxx

2023-06-07 11:28 UTC, xiaozhu36 commented on website/docs/r/kms_key.html.markdown
> +-> **NOTE:** Available since v1.85.0+.
最后的加号也去掉

2023-06-07 11:28 UTC, xiaozhu36 commented on website/docs/r/kms_key.html.markdown
> +* `tags` - (Optional, Available in v1.207.0+) A mapping of tags to assign to the resource.
Available since v1.207.0

2023-06-08 03:23 UTC, MrWolong commented on website/docs/r/kms_key.html.markdown
> +* `is_enabled` - (Deprecated) Field `is_enabled` has been deprecated from provider version 1.85.0. New field `key_state` instead.
已修复

2023-06-08 03:23 UTC, MrWolong commented on website/docs/r/kms_key.html.markdown
> +-> **NOTE:** Available since v1.85.0+.
已修复

2023-06-08 03:24 UTC, MrWolong commented on website/docs/r/kms_key.html.markdown
> +* `tags` - (Optional, Available in v1.207.0+) A mapping of tags to assign to the resource.
已修复

2023-06-09 02:24 UTC, MrWolong commented on website/docs/r/kms_key.html.markdown
> +* `is_enabled` - (Deprecated since v1.85.0) Field `is_enabled` has been deprecated from provider version 1.85.0. New field `key_state` instead.
已修复

2023-06-09 03:50 UTC, xiaozhu36 approved these changes

2023-06-09 05:39 UTC, merged