Auto gen eip
aliyun/terraform-provider-alicloud pull request #6225
Opened 2023-06-08 02:25 UTC by ChenHanZhang

2023-06-09 06:09 UTC, ChenHanZhang commented on website/docs/r/eip_segment_address.html.markdown
> +* `netmode` - (Optional, ForceNew) 当前属性没有在镇元上录入属性描述，请补充后再生成代码。.
描述信息有问题

2023-06-09 06:52 UTC, ChenHanZhang commented on website/docs/r/eip_address.html.markdown
> +For information about EIP Address and how to use it, see [What is Address](https://www.alibabacloud.com/help/en/).
done

2023-06-09 06:52 UTC, ChenHanZhang commented on website/docs/r/eip_segment_address.html.markdown
> +* `netmode` - (Optional, ForceNew) 当前属性没有在镇元上录入属性描述，请补充后再生成代码。.
done

2023-06-09 08:08 UTC, ChenHanZhang commented on alicloud/resource_alicloud_eip_segment_address.go
> +				ValidateFunc: StringInSlice([]string{"BGP", "BGP_PRO", "ChinaTelecom", "ChinaUnicom", "ChinaMobile", "ChinaTelecom_L2", "ChinaUnicom_L2", "ChinaMobile_L2"}, false),
少一个BGP_FinanceCloud

2023-06-09 08:19 UTC, ChenHanZhang commented on alicloud/resource_alicloud_eip_segment_address.go
> +				ValidateFunc: StringInSlice([]string{"BGP", "BGP_PRO", "ChinaTelecom", "ChinaUnicom", "ChinaMobile", "ChinaTelecom_L2", "ChinaUnicom_L2", "ChinaMobile_L2"}, false),
done

2023-06-13 05:49 UTC, xiaozhu36 requested changes

2023-06-13 05:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eip_address.go
> +			"bandwidth_package_id": {
bandwidth_package_id 这个是干啥的

2023-06-13 05:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eip_segment_address.go
> +				Type:     schema.TypeString,
这个应该有枚举值或者取值范围

2023-06-13 05:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eip_segment_address.go
> +				ForceNew: true,
这个也一样

2023-06-13 05:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eip_segment_address.go
> +	d.Set("status", objectRaw["Status"])
其他的属性呢

2023-06-13 05:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eip_segment_address_test.go
> +				ImportStateVerifyIgnore: []string{"bandwidth", "eip_mask", "internet_charge_type", "isp", "netmode"},
对于不返回的属性，不要设置为ForceNew

2023-06-13 05:49 UTC, xiaozhu36 commented on website/docs/r/eip_address.html.markdown
> +subcategory: "EIP"
这个为啥要改

2023-06-13 05:49 UTC, xiaozhu36 commented on website/docs/r/eip_address.html.markdown
> +  - **Available**: Available.
出参中的枚举值就不用设置了，永远只有一个值 Available

2023-06-13 05:49 UTC, xiaozhu36 commented on website/docs/r/eip_segment_address.html.markdown
> +If you are a whitelist user with single-line bandwidth, you can also select the following types:
中间留一个空行，会导致不会缩进了

2023-06-13 05:49 UTC, xiaozhu36 commented on website/docs/r/eip_segment_address.html.markdown
> +
这个地方为啥留这么多空行

2023-06-13 06:17 UTC, ChenHanZhang commented on alicloud/resource_alicloud_eip_address.go
> +			"bandwidth_package_id": {
带宽包ID，之前要透出可以修改的，并且存在默认值因此标记为Computed，但测试过程中存在一些问题暂时不对接

2023-06-13 06:25 UTC, ChenHanZhang commented on website/docs/r/eip_address.html.markdown
> +subcategory: "EIP"
产品的subcategory映射未补上，已修复

2023-06-13 06:32 UTC, ChenHanZhang commented on website/docs/r/eip_segment_address.html.markdown
> +
这里有个“无法删除的资源类型信息”的占位，已优化

2023-06-13 06:43 UTC, ChenHanZhang commented on website/docs/r/eip_segment_address.html.markdown
> +If you are a whitelist user with single-line bandwidth, you can also select the following types:
done

2023-06-13 06:47 UTC, ChenHanZhang commented on alicloud/resource_alicloud_eip_segment_address_test.go
> +				ImportStateVerifyIgnore: []string{"bandwidth", "eip_mask", "internet_charge_type", "isp", "netmode"},
如果不存在更新接口，则所有可指定的属性都是ForceNew的，这个是Terraform框架的要求

2023-06-13 07:09 UTC, ChenHanZhang commented on alicloud/resource_alicloud_eip_segment_address.go
> +				Type:     schema.TypeString,
done

2023-06-13 07:09 UTC, ChenHanZhang commented on alicloud/resource_alicloud_eip_segment_address.go
> +				ForceNew: true,
done

2023-06-13 07:44 UTC, ChenHanZhang commented on website/docs/r/eip_address.html.markdown
> +  - **Available**: Available.
done

2023-06-13 07:45 UTC, ChenHanZhang commented on alicloud/resource_alicloud_eip_address.go
> +			"bandwidth_package_id": {
done

2023-06-14 08:03 UTC, xiaozhu36 approved these changes

2023-06-15 08:40 UTC, xiaozhu36 approved these changes

2023-06-15 09:19 UTC, merged