rds resource addition retry
aliyun/terraform-provider-alicloud pull request #6237
Opened 2023-06-15 06:21 UTC by zcc01029273

2023-06-25 14:31 UTC, xiaozhu36 requested changes

2023-06-25 14:31 UTC, xiaozhu36 commented on website/docs/r/db_instance.html.markdown
> +### Create an RDS MySQL instance with specific parameters
这个地方不应该改

2023-06-26 02:06 UTC, zcc01029273 commented on website/docs/r/db_instance.html.markdown
> +### Create an RDS MySQL instance with specific parameters
done

2023-06-26 02:36 UTC, xiaozhu36 approved these changes

2023-07-06 01:34 UTC, closed without merging