resource/alicloud_ga_endpoint_group: Added the field enable_proxy_protocol
aliyun/terraform-provider-alicloud pull request #6250
Opened 2023-06-21 10:25 UTC by MrWolong

2023-06-28 03:42 UTC, xiaozhu36 requested changes

2023-06-28 03:42 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_endpoint_group_test.go
> +					},
第一步应该只需要必填的和forcenew 的属性

2023-06-28 05:39 UTC, MrWolong commented on alicloud/resource_alicloud_ga_endpoint_group_test.go
> +					},
因为tags是在update中创建的，所以这个主要是为了测试用户第一次创建实例的时候，如果传入了tags，是否会生效。

2023-06-29 08:21 UTC, MrWolong commented on alicloud/resource_alicloud_ga_endpoint_group_test.go
> +func TestAccAlicloudGaEndpointGroup_basic01(t *testing.T) {
增加一个单测用来测试创建时设置tags的场景

2023-06-29 09:43 UTC, merged