resource/alicloud_ga_bandwidth_package: Added the field tags
aliyun/terraform-provider-alicloud pull request #6257
Opened 2023-06-26 06:25 UTC by MrWolong

2023-06-28 03:51 UTC, xiaozhu36 requested changes

2023-06-28 03:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_bandwidth_package_test.go
> +					"tags": map[string]string{
这个也一样，为啥第一步就要设置optional的

2023-06-29 08:20 UTC, MrWolong commented on alicloud/resource_alicloud_ga_bandwidth_package_test.go
> +					"tags": map[string]string{
已修复

2023-06-29 08:26 UTC, MrWolong commented on alicloud/resource_alicloud_ga_bandwidth_package_test.go
> +func TestAccAlicloudGaBandwidthPackage_basic1(t *testing.T) {
增加一个单测用来测试创建时设置tags的场景

2023-06-29 09:24 UTC, xiaozhu36 approved these changes

2023-06-29 09:43 UTC, merged