docs: Improves the cen docs example
aliyun/terraform-provider-alicloud pull request #6258
Opened 2023-06-26 06:27 UTC by susu9527

2023-06-28 02:16 UTC, xiaozhu36 requested changes

2023-06-28 02:16 UTC, xiaozhu36 commented on website/docs/r/cen_transit_router_vpn_attachment.html.markdown
> -  }
这些配置为啥要去掉

2023-06-28 02:24 UTC, susu9527 commented on website/docs/r/cen_transit_router_vpn_attachment.html.markdown
> -  }
不是删了属性，是删了一个Example，之前是有两个Example，默认的里面没有alicloud_cen_transit_router_cidr资源会创建失败，另一个有alicloud_cen_transit_router_cidr可用创建成功，就把默认的那个Example删掉了

2023-07-05 07:45 UTC, xiaozhu36 approved these changes

2023-07-05 07:46 UTC, merged