resource/alicloud_ga_basic_accelerator: Added the field tags
aliyun/terraform-provider-alicloud pull request #6260
Opened 2023-06-26 08:09 UTC by MrWolong

2023-06-28 03:52 UTC, xiaozhu36 requested changes

2023-06-28 03:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_basic_accelerator_test.go
> +					"tags": map[string]string{
一样

2023-06-29 08:20 UTC, MrWolong commented on alicloud/resource_alicloud_ga_basic_accelerator_test.go
> +					"tags": map[string]string{
已修复

2023-06-29 09:24 UTC, xiaozhu36 approved these changes

2023-06-29 09:43 UTC, merged