New resource/alicloud_ens_instance.
aliyun/terraform-provider-alicloud pull request #6266
Opened 2023-06-27 08:57 UTC by RabbyGx0

2023-06-27 08:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6266) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6266) before we can accept your contribution.<br/><hr/>**xiequanhang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=6266) it.</sub>

2023-07-05 03:36 UTC, ChenHanZhang commented on alicloud/resource_alicloud_ens_instance_test.go
> +						{
之前说这里的system_disk、image_id是非必填的，但测试会报错，是因为哪个字段有特定取值的时候也需要填这两个字段？检查下文档上有没有把这个情况进行说明

2023-07-05 03:36 UTC, ChenHanZhang commented on website/docs/r/ens_instance.html.markdown
> +* `internet_charge_type` - (Optional) Instance Charge type.it could be BandwidthByDay, 95BandwidthByMonth, PayByBandwidth4thMonth。.
句号，文档上更新下，去掉中文 “。”

2023-07-05 03:36 UTC, ChenHanZhang commented on website/docs/r/ens_instance.html.markdown
> +* `carrier` - (Optional) Operator, required for regional level scheduling, invalid for node level scheduling。.
“。”

2023-07-05 03:36 UTC, ChenHanZhang commented on website/docs/r/ens_instance.html.markdown
> +* `amount` - (Required) The number of instances created, with a minimum of 1 and a maximum of 100。.
“。”

2023-07-05 03:36 UTC, ChenHanZhang commented on website/docs/r/ens_instance.html.markdown
> +* `internet_max_bandwidth_out` - (Required, ForceNew) The maximum public network bandwidth。.
每一个描述都要检查一下，告诉云产品修改镇元上的文档描述

2023-07-05 03:36 UTC, ChenHanZhang commented on website/docs/r/ens_instance.html.markdown
> +  - High-efficiency cloud disk: cloud_efficiency
这里应该写成：
  - cloud_efficiency: High-efficiency cloud disk

枚举值在前，描述在后

2023-07-05 07:24 UTC, ChenHanZhang commented on alicloud/resource_alicloud_ens_instance_test.go
> +							"category": "cloud_efficiency",
这里三个相同的测不出顺序是否一致

2023-07-06 03:27 UTC, xiaozhu36 requested changes

2023-07-06 03:27 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance.go
> +			"ens_region_id": {
这个确定需要么？不能用 cliet.RegionId 代替么

2023-07-06 03:27 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance.go
> +				Type:     schema.TypeString,
password 应该标记为 敏感

2023-07-06 03:27 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance.go
> +			"period": {
period 是 int，为啥 auto_renew_period 是 string

2023-07-06 03:27 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance.go
> +				ValidateFunc: IntBetween(1, 100),
amount 不应该暴露，每次只管理一个资源就行

2023-07-06 05:01 UTC, RabbyGx0 commented on alicloud/resource_alicloud_ens_instance.go
> +			"period": {
period是RunInstance这个接口的字段，AutoRnewPeriod是CreateInstance这个接口的字段

2023-07-06 06:00 UTC, RabbyGx0 commented on alicloud/resource_alicloud_ens_instance.go
> +			"ens_region_id": {
EnsRegionId和RegionId不是一个业务含义

2023-07-06 07:04 UTC, RabbyGx0 commented on alicloud/resource_alicloud_ens_instance.go
> +				ValidateFunc: IntBetween(1, 100),
已改成常量值1

2023-07-06 07:04 UTC, RabbyGx0 commented on alicloud/resource_alicloud_ens_instance.go
> +				Type:     schema.TypeString,
已标记敏感

2023-07-06 07:56 UTC, RabbyGx0 commented on alicloud/resource_alicloud_ens_instance.go
> +			"period": {
period是RunInstance这个接口的字段，在api参数上是int类型；
AutoRnewPeriod是CreateInstance这个接口的字段，在api参数上是string类型

2023-07-11 07:41 UTC, xiaozhu36 requested changes

2023-07-11 07:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance.go
> +				Type:     schema.TypeString,
order_id 是干啥的

2023-07-11 07:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance.go
> +			"period": {
跟 Get API 的response 保持一致

2023-07-11 07:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance.go
> +							Type:     schema.TypeInt,
size 有取值范围限制么

2023-07-11 07:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance.go
> +			"period": {
另外，这个resource中用到 CreateInstance 了么

2023-07-11 07:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance_test.go
> +					"image_id":                   "centos_6_08_64_20G_alibase_20171208",
用 datasource

2023-07-11 07:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance_test.go
> +					"instance_type":              "ens.sn1.tiny",
这个实例规格可以用 datasource么

2023-07-11 07:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance_test.go
> +					"ens_region_id":              "cn-wuxi-telecom_unicom_cmcc-2",
这个region id 有datasource 可以查询么

2023-07-11 07:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance_test.go
> +					"instance_name":              name + "_update",
为啥不是一个一个改

2023-07-12 05:50 UTC, RabbyGx0 commented on alicloud/resource_alicloud_ens_instance.go
> +				Type:     schema.TypeString,
该属性在spec中被定义为资源属性，这也是一个被错误定义的属性，该属性已删除

2023-07-12 05:50 UTC, RabbyGx0 commented on alicloud/resource_alicloud_ens_instance.go
> +			"period": {
CreateInstance是关联资源api，tf没有生成。
AutoRnewPeriod在spec中被定义成了资源属性，但是定义错误，所以tf生成出来了，已经删除。
AutoRnewPeriod不是资源属性但是spec没有检查出来，这个问题需要解决。
period是操作私有属性，并没有在get出参中返回，所以和入参保持一致。

2023-07-12 08:12 UTC, RabbyGx0 commented
暂时还没有对应的datasource可以查

2023-07-12 08:20 UTC, RabbyGx0 commented on alicloud/resource_alicloud_ens_instance.go
> +							Type:     schema.TypeInt,
资源定义已配置，但是云产品不想透出，需要确定是否去掉

2023-07-12 11:43 UTC, xiaozhu36 requested changes

2023-07-12 11:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance_test.go
> +					"image_id":                   "centos_6_08_64_20G_alibase_20171208",
这个是有对应的datasource的 alicloud_images

2023-07-12 11:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ens_instance_test.go
> +					"image_id":                   "centos_6_08_64_20G_alibase_20171208",
另外，尽可能用 ubuntu

2023-07-12 11:43 UTC, xiaozhu36 commented on website/docs/r/ens_instance.html.markdown
> +  image_id                   = "centos_6_08_64_20G_alibase_20171208"
尽可能用ubuntu

2023-07-13 02:13 UTC, ChenHanZhang commented on website/docs/r/ens_instance.html.markdown
> +  image_id                   = "centos_6_08_64_20G_alibase_20171208"
这个不是ecs的实例，是ens的实例，不是同个查询接口哈。ens的images还未对接，这里测试只能暂时写一个固定的image_id，等ens的对接完成后，再修改这个用例

2023-07-13 05:41 UTC, xiaozhu36 approved these changes

2023-07-14 02:45 UTC, xiaozhu36 approved these changes

2023-07-14 03:30 UTC, merged