resource/alicloud_rds_db_database: add retry; resource/alicloud_rds_upgrade_db_instance: add retry; resource/alicloud_rds_db_proxy: add retry.
aliyun/terraform-provider-alicloud pull request #6272
Opened 2023-06-28 02:35 UTC by zcc01029273

resource/alicloud_rds_db_database: add retry; resource/alicloud_rds_upgrade_db_instance: add retry; resource/alicloud_rds_db_proxy: add retry.

2023-06-28 03:03 UTC, xiaozhu36 approved these changes

2023-06-29 12:00 UTC, xiaozhu36 requested changes

2023-06-30 01:41 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +			return nil
done

2023-06-30 01:41 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_db_proxy.go
> +			return nil
done

2023-06-30 02:07 UTC, xiaozhu36 approved these changes

2023-07-03 05:50 UTC, xiaozhu36 approved these changes

2023-07-04 02:19 UTC, xiaozhu36 approved these changes

2023-07-04 02:19 UTC, merged