resource/alicloud_db_backup_policy: add retry; resource/alicloud_db_read_write_splitting_connection: add retry; resource/alicloud_db_readonly_instance: add retry.
aliyun/terraform-provider-alicloud pull request #6273
Opened 2023-06-28 07:56 UTC by zcc01029273

resource/alicloud_db_backup_policy: add retry; resource/alicloud_db_read_write_splitting_connection: add retry; resource/alicloud_db_readonly_instance: add retry.

2023-06-28 09:35 UTC, xiaozhu36 requested changes

2023-06-28 09:35 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_readonly_instance.go
> +			},
既然新增加了属性，那么就在 title 上明确出来

2023-06-28 09:35 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_readonly_instance_test.go
> +				ImportStateVerifyIgnore: []string{"force_restart", "effective_time"},
这个属性不支持返回么

2023-06-28 10:00 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_readonly_instance_test.go
> +				ImportStateVerifyIgnore: []string{"force_restart", "effective_time"},
这个没有，与开发人员沟通了，暂时没有地方查询

2023-06-28 10:03 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_readonly_instance.go
> +			},
done

2023-06-28 11:12 UTC, xiaozhu36 approved these changes

2023-06-30 03:50 UTC, xiaozhu36 approved these changes

2023-07-05 05:52 UTC, xiaozhu36 requested changes

2023-07-05 05:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_connection_test.go
> +		"connection_string": fmt.Sprintf("tf-testacc%s.mysql.germany.rds.aliyuncs.com", rand),
这个不应该改，如果region切换了，这个地方还是无法通过

2023-07-05 06:40 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_connection_test.go
> +		"connection_string": fmt.Sprintf("tf-testacc%s.mysql.germany.rds.aliyuncs.com", rand),
done

2023-07-05 07:19 UTC, xiaozhu36 approved these changes

2023-07-05 14:43 UTC, merged