resource/alicloud_rds_instance_cross_backup_policy: add retry; resource/alicloud_rds_parameter_group: add retry; resource/alicloud_rds_service_linked_role: add retry.
aliyun/terraform-provider-alicloud pull request #6276
Opened 2023-06-28 08:57 UTC by zcc01029273

resource/alicloud_rds_instance_cross_backup_policy: add retry; resource/alicloud_rds_parameter_group: add retry; resource/alicloud_rds_service_linked_role: add retry.

2023-06-28 09:36 UTC, xiaozhu36 approved these changes

2023-06-30 03:50 UTC, xiaozhu36 approved these changes

2023-06-30 05:57 UTC, xiaozhu36 approved these changes

2023-06-30 07:26 UTC, xiaozhu36 requested changes

2023-06-30 07:26 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rds_instance_cross_backup_policy.go
> +	object, err := rdsService.DescribeInstanceCrossBackupPolicy(d.Id())
这个地方不需要加查询啊

2023-06-30 07:28 UTC, zcc01029273 commented on alicloud/resource_alicloud_rds_instance_cross_backup_policy.go
> +	object, err := rdsService.DescribeInstanceCrossBackupPolicy(d.Id())
这个是因为前段时间国际事业部那边反馈的一个问题，比如说开启异地灾备失败的时候，实际上没有这个数据，删除的时候调用修改接口修改状态就会失败，所以加了一个查询进行校验

2023-06-30 13:06 UTC, xiaozhu36 approved these changes

2023-06-30 13:11 UTC, xiaozhu36 approved these changes

2023-07-05 08:18 UTC, xiaozhu36 approved these changes

2023-07-05 08:41 UTC, merged