new resource: alicloud_fcv2_function.
aliyun/terraform-provider-alicloud pull request #6280
Opened 2023-06-30 01:36 UTC by ChenHanZhang

2023-07-06 03:20 UTC, xiaozhu36 requested changes

2023-07-06 03:20 UTC, xiaozhu36 commented on website/docs/r/fcv2_function.html.markdown
> +subcategory: "FCV2"
改成 Function Compute Service V2 (FCV2)

2023-07-06 03:20 UTC, xiaozhu36 commented on alicloud/resource_alicloud_fcv2_function.go
> +				Sensitive: true,
这个为啥是敏感的

2023-07-06 03:20 UTC, xiaozhu36 commented on alicloud/resource_alicloud_fcv2_function_test.go
> +				}),
这个case 是只能在beijing测试么

2023-07-06 08:08 UTC, ChenHanZhang commented on website/docs/r/fcv2_function.html.markdown
> +subcategory: "FCV2"
done

2023-07-06 08:09 UTC, ChenHanZhang commented on alicloud/resource_alicloud_fcv2_function.go
> +				Sensitive: true,
和云产品确认了，不需要设置为敏感属性

2023-07-06 08:10 UTC, ChenHanZhang commented on alicloud/resource_alicloud_fcv2_function_test.go
> +				}),
云产品录入的测试用例只能在beijing测试，查询提供的开服列表：https://help.aliyun.com/document_detail/452705.html
将用例改为仅在hangzhou测试

2023-07-11 01:53 UTC, xiaozhu36 requested changes

2023-07-11 02:55 UTC, ChenHanZhang commented on website/docs/r/fcv2_function.html.markdown
> +  }
这里不是简单的base64(str)的方式来取到这个值，而是通过对zip文件进行base64编码，openssl base64 -A -in code.zip -out base64 这种方式计算得到的

2023-07-11 02:55 UTC, ChenHanZhang commented on alicloud/resource_alicloud_fcv2_function.go
> +				Sensitive: true,
done

2023-07-12 08:27 UTC, ChenHanZhang commented on website/docs/r/fcv2_function.html.markdown
> +  }
文档上的示例改成了通过Object指定的方式

2023-07-12 11:48 UTC, xiaozhu36 approved these changes

2023-07-13 02:04 UTC, xiaozhu36 approved these changes

2023-07-13 02:36 UTC, merged