resource/alicloud_elasticsearch_instance: Add field auto_renew and au…
aliyun/terraform-provider-alicloud pull request #6281
Opened 2023-06-30 06:29 UTC by wangcf-yf

…to_renew_duration

2023-06-30 06:51 UTC, xiaozhu36 requested changes

2023-06-30 06:51 UTC, xiaozhu36 commented on alicloud/resource_alicloud_elasticsearch_instance_test.go
> +			},
第二步要将自动续费的开关关闭

2023-07-13 01:53 UTC, xiaozhu36 requested changes

2023-07-13 01:53 UTC, xiaozhu36 commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +		return err
return wrapError（err）

2023-07-13 01:53 UTC, xiaozhu36 commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +	queryAvailableInstancesObject, err := bssOpenApiService.QueryAvailableInstances(d.Id(), client.RegionId, "elasticsearch", "elasticsearchpre", "elasticsearch", "elasticsearchpre_intl")
使用国际站的账号测试了么

2023-07-13 01:53 UTC, xiaozhu36 commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +			d.Set("auto_renew_duration", renewalDuration)
可以不这样计算，直接把RenewalDurationUnit暴露出来

2023-07-20 06:55 UTC, xiaozhu36 requested changes

2023-07-20 06:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +				Optional:     true,
这两个应该是只有在 prepaid 的时候生效，所以应该加上 DiffSuppressFunc

2023-07-20 06:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +			return nil, WrapError(fmt.Errorf("CreateInstance error: instance_charge_type is PostPaid, fields: period,renew_status,auto_renew_duration,renewal_duration_unit must be null"))
这个判断直接用 DiffSuppress 搞定就可以了

2023-07-20 06:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_elasticsearch_instance_test.go
> +						"master_node_disk_type": MasterNodeEssdDiskType,
新增加的这两个属性也需要在其他的case中增加上相应的 step

2023-07-20 06:55 UTC, xiaozhu36 commented on website/docs/r/elasticsearch_instance.html.markdown
>  * `kibana_node_spec` - (Optional, Available in v1.163.0 +) The kibana node specifications of the Elasticsearch instance. Default is `elasticsearch.n4.small`.
所有的 Available in 都应该改成 Available since

2023-07-20 12:38 UTC, xiaozhu36 requested changes

2023-07-20 12:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +				duration = duration * 12
这个不对吧，为啥要乘12

2023-07-20 12:46 UTC, wangcf-yf commented on alicloud/resource_alicloud_elasticsearch_instance.go
> +				duration = duration * 12
ES 创建API，支持自动续费。不传单位时，默认是月。当前没有把单位传过去，因此乘以12

2023-07-21 10:47 UTC, xiaozhu36 approved these changes

2023-07-25 14:31 UTC, xiaozhu36 requested changes

2023-07-25 14:31 UTC, xiaozhu36 commented on alicloud/resource_alicloud_elasticsearch_instance_test.go
> -					"data_node_disk_size": DataNodeDiskForUpdate,
这些为啥要删掉

2023-07-25 14:31 UTC, xiaozhu36 commented on alicloud/resource_alicloud_elasticsearch_instance_test.go
> -					"public_whitelist": []string{"192.168.0.0/24", "127.0.0.1"},
这个属性的测试怎去掉了

2023-07-25 14:31 UTC, xiaozhu36 commented on website/docs/r/elasticsearch_instance.html.markdown
> +* `renewal_duration_unit` - (Optional, Available since 1.208.0) Auto-Renewal Cycle Unit Values Include: Month: Month. Year: Years. Valid values: `M`, `Y`.
下个版本是 1.208.1

2023-07-25 15:20 UTC, wangcf-yf commented on alicloud/resource_alicloud_elasticsearch_instance_test.go
> -					"public_whitelist": []string{"192.168.0.0/24", "127.0.0.1"},
没有删掉，只是把ES/Kibana 的公私网白名单单独放到了一个TestACC中，TestAccAlicloudElasticsearchInstance_network

2023-07-25 15:20 UTC, wangcf-yf commented on alicloud/resource_alicloud_elasticsearch_instance_test.go
> -					"data_node_disk_size": DataNodeDiskForUpdate,
password/ description 没有删除掉，没有删掉，放到下面了。data_node数据节点的相关配置，也都放到了一起
![image](https://github.com/aliyun/terraform-provider-alicloud/assets/35716021/99fb0de3-9741-46c8-b6c3-4600c3e26cb5)

2023-07-26 07:18 UTC, xiaozhu36 approved these changes

2023-07-27 06:33 UTC, xiaozhu36 approved these changes

2023-07-27 06:33 UTC, merged