resource/alicloud_db_instance: Added the field role_arn
aliyun/terraform-provider-alicloud pull request #6302
Opened 2023-07-11 02:24 UTC by zcc01029273

2023-07-11 06:13 UTC, xiaozhu36 requested changes

2023-07-11 06:13 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance.go
> +			if v, ok := d.GetOk("role_arn"); ok && v.(string) != "" {
这个地方应该改成，如果已经设置了 role_arn，那么就不用调用 findKmsRoleArn 了

2023-07-11 08:33 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_instance.go
> +			if v, ok := d.GetOk("role_arn"); ok && v.(string) != "" {
done

2023-07-12 06:22 UTC, xiaozhu36 approved these changes

2023-07-13 01:44 UTC, merged