resource/alicloud_kvstore_instance: Added the field shard_count
aliyun/terraform-provider-alicloud pull request #6312
Opened 2023-07-13 07:37 UTC by MrWolong

2023-07-13 09:08 UTC, xiaozhu36 requested changes

2023-07-13 09:08 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kvstore_instance.go
> +				ForceNew: true,
这个没有去值范围么

2023-07-13 09:08 UTC, xiaozhu36 commented on website/docs/r/kvstore_instance.html.markdown
> +* `instance_charge_type` - (Optional, Computed, Deprecated since v1.101.0) It has been deprecated from provider version 1.101.0 and `payment_type` instead.
已经启用的，就不用再写 Optional 和 Computed 了

2023-07-13 09:08 UTC, xiaozhu36 commented on website/docs/r/kvstore_instance.html.markdown
> +* `shard_count`- (Optional, ForceNew, Computed, Int, Available since v1.208.0) The number of data shards. This parameter is available only if you create a cluster instance that uses cloud disks. You
Computed 这个标签去掉吧

2023-07-13 09:08 UTC, xiaozhu36 commented on website/docs/r/kvstore_instance.html.markdown
> +* `name` (Required, Deprecated since v1.101.0) Field `parameters` has been deprecated from provider version 1.101.0 and `config` instead.
已经启用了就不用再写 Required 了

2023-07-13 09:27 UTC, MrWolong commented on website/docs/r/kvstore_instance.html.markdown
> +* `instance_charge_type` - (Optional, Computed, Deprecated since v1.101.0) It has been deprecated from provider version 1.101.0 and `payment_type` instead.
已修复

2023-07-13 09:27 UTC, MrWolong commented on website/docs/r/kvstore_instance.html.markdown
> +* `name` (Required, Deprecated since v1.101.0) Field `parameters` has been deprecated from provider version 1.101.0 and `config` instead.
已修复

2023-07-13 09:27 UTC, MrWolong commented on website/docs/r/kvstore_instance.html.markdown
> +* `shard_count`- (Optional, ForceNew, Computed, Int, Available since v1.208.0) The number of data shards. This parameter is available only if you create a cluster instance that uses cloud disks. You
已修复

2023-07-14 06:56 UTC, xiaozhu36 approved these changes

2023-07-14 08:53 UTC, xiaozhu36 approved these changes

2023-07-20 15:04 UTC, xiaozhu36 approved these changes

2023-07-21 01:48 UTC, merged