resource/alicloud_ddoscoo_instance: Added the field edition and ip
aliyun/terraform-provider-alicloud pull request #6317
Opened 2023-07-14 05:45 UTC by MrWolong

2023-07-14 05:45 UTC, MrWolong commented on alicloud/connectivity/regions.go
> +var DdoscooInstanceSupportedRegions = []Region{Hangzhou}
增加一个用来测试国内的region

2023-07-14 07:29 UTC, xiaozhu36 requested changes

2023-07-14 07:29 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ddoscoo_instance.go
> +				Required:     true,
这个属于不兼容啊，新增的属性只能是选填的

2023-07-14 08:26 UTC, MrWolong commented on alicloud/resource_alicloud_ddoscoo_instance.go
> +				Required:     true,
已修复

2023-07-17 02:08 UTC, xiaozhu36 requested changes

2023-07-17 02:08 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ddoscoo_instance.go
> +				Default:      "coop",
为啥要加 默认值

2023-07-17 03:09 UTC, MrWolong commented on alicloud/resource_alicloud_ddoscoo_instance.go
> +				Default:      "coop",
跟云产品确认了一下，以前没有高级版advance，只有专业版coop，所以不传这个值的时候，默认使用的是coop，后来云产品增加了advance，但是advance目前并没有对外开放，只能打标才能使用，目前，如果edition不传值的话，默认会使用advance，就会导致资源创建失败。考虑到资源的兼容性，以前在没有advance这个规格，且没有接入edition这个字段的时候，不设置editon，资源默认使用coop，可以创建成功，所以设置了默认值coop。

2023-07-20 15:10 UTC, xiaozhu36 requested changes

2023-08-02 07:52 UTC, MrWolong commented on alicloud/resource_alicloud_ddoscoo_instance.go
> +				Default:      "coop",
这个必须要加默认值，云产品对这个参数有两步校验，第一步是会对进行购买的模块进行校验你，这个云产品已经在南天门上配置了coop，第二步是询价，询价这个跟云产品确认了一下，这个没办法在南天门上配置，只能手动传入，不传的话，就会报错。

2023-08-04 08:36 UTC, xiaozhu36 approved these changes

2023-08-07 04:55 UTC, xiaozhu36 approved these changes

2023-09-22 10:11 UTC, MrWolong commented on alicloud/service_alicloud_ddoscoo.go
> -	request["RegionId"] = "cn-hangzhou"
接口文档中没有RegionId这个属性

2023-09-22 10:11 UTC, MrWolong commented on alicloud/service_alicloud_ddoscoo.go
> -	request["RegionId"] = "cn-hangzhou"
接口文档中没有RegionId这个属性

2023-09-22 10:11 UTC, MrWolong commented on alicloud/service_alicloud_ddoscoo.go
> -	request.RegionId = "cn-hangzhou"
接口文档中没有RegionId这个属性

2023-09-22 12:15 UTC, xiaozhu36 requested changes

2023-09-22 12:15 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ddoscoo_instance.go
> +				Default:      1,
不返回的属性，不能有默认值

2023-09-25 06:39 UTC, MrWolong commented on alicloud/resource_alicloud_ddoscoo_instance.go
> +				Default:      1,
period不设置默认值1的话，接口会返回报错MissingParameter，Period must not null when subscription type is Subscription

2023-09-27 04:58 UTC, closed without merging