resource/alicloud_sae_application: Added the field php, image_pull_secrets, programming_language, command_args_v2, envs_v2, custom_host_alias_v2, oss_mount_descs_v2, config_map_mount_desc_v2, liveness_v2, readiness_v2, post_start_v2, pre_stop_v2, sls_configs_v2, tomcat_config_v2, update_strategy_v2, nas_configs, kafka_configs, pvtz_discovery_svc
aliyun/terraform-provider-alicloud pull request #6324
Opened 2023-07-17 10:37 UTC by MrWolong

2023-09-05 14:44 UTC, xiaozhu36 requested changes

2023-09-05 14:44 UTC, xiaozhu36 commented on website/docs/r/sae_application.html.markdown
> +* `enable_grey_tag_route` - (Optional, Bool) The enable grey tag route. Valid values: `true`, `false`.
文档中要说清楚，目前只支持设置为 false 去关闭这个功能，如果需要开通这个功能，只能通过 控制台去修改

2023-09-06 10:21 UTC, MrWolong commented on alicloud/resource_alicloud_sae_application.go
> +				Computed: true,
已修复

2023-09-06 10:21 UTC, MrWolong commented on website/docs/r/sae_application.html.markdown
> +* `enable_grey_tag_route` - (Optional, Bool) The enable grey tag route. Valid values: `true`, `false`.
已修复

2023-09-07 06:01 UTC, xiaozhu36 requested changes

2023-09-07 06:01 UTC, xiaozhu36 commented on alicloud/resource_alicloud_sae_application_test.go
> -			},
这些为啥要删掉

2023-09-07 06:01 UTC, xiaozhu36 commented on alicloud/resource_alicloud_sae_application.go
> +				Removed:  "Field `version_id` has been removed from provider version 1.210.0.",
这些移除的，在API的参数上也已经去掉了么

2023-09-07 06:38 UTC, MrWolong commented on alicloud/resource_alicloud_sae_application.go
> +				Removed:  "Field `version_id` has been removed from provider version 1.210.0.",
在接口文档中已经去掉了，且无法使用。version_id可能是历史问题，一直在代码中，却从来没有使用过。

2023-09-07 09:57 UTC, MrWolong commented on alicloud/resource_alicloud_sae_application_test.go
> -			},
已修复

2023-09-14 07:08 UTC, xiaozhu36 requested changes

2023-09-14 07:34 UTC, MrWolong commented on alicloud/resource_alicloud_sae_application.go
>  			},
已修复

2023-09-14 08:16 UTC, MrWolong commented on alicloud/resource_alicloud_sae_application_test.go
>  }
已修复

2023-09-14 09:00 UTC, closed without merging