resource/alicloud_ga_accelerator: Added the field instance_charge_type and promotion_option_no
aliyun/terraform-provider-alicloud pull request #6330
Opened 2023-07-19 10:32 UTC by MrWolong

2023-07-28 05:53 UTC, xiaozhu36 requested changes

2023-07-28 05:53 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_accelerator.go
> +			"instance_charge_type": {
这个属性是自动对接的么？如果是的话，现在应该都统一为 payment_type 了

2023-07-28 05:53 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_accelerator_test.go
> +			testAccPreCheckWithTime(t, []int{1})
这个去掉

2023-07-28 05:53 UTC, xiaozhu36 commented on website/docs/r/ga_accelerator.html.markdown
这个note可以直接去掉

2023-07-28 06:36 UTC, MrWolong commented on alicloud/resource_alicloud_ga_accelerator.go
> +			"instance_charge_type": {
已修改

2023-07-28 06:36 UTC, MrWolong commented on alicloud/resource_alicloud_ga_accelerator_test.go
> +			testAccPreCheckWithTime(t, []int{1})
已修改

2023-07-28 06:36 UTC, MrWolong commented on website/docs/r/ga_accelerator.html.markdown
已修改

2023-07-31 08:20 UTC, xiaozhu36 requested changes

2023-07-31 08:20 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_accelerator_test.go
> +					"payment_type":    "Subscription",
既然默认值是 Subscription，那么这个地方不应该设置

2023-07-31 08:23 UTC, MrWolong commented on alicloud/resource_alicloud_ga_accelerator_test.go
> +					"payment_type":    "Subscription",
这个是为了校验Subscription这个值，如果用户手动传入，是否可以创建成功。

2023-07-31 08:56 UTC, xiaozhu36 approved these changes

2023-07-31 08:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_accelerator_test.go
> +					"payment_type":    "Subscription",
那应该单独增加一个

2023-07-31 09:11 UTC, merged