resource/alicloud_polardb_cluster: poladb db support upgrad minor ver…
aliyun/terraform-provider-alicloud pull request #6348
Opened 2023-07-24 08:44 UTC by Lv0520

…sion

2023-07-24 09:10 UTC, xiaozhu36 approved these changes

2023-07-28 03:04 UTC, xiaozhu36 requested changes

2023-07-28 03:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> -			},
这个为啥要提到上面去

2023-07-28 03:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +func deleteTDEPolicyAndRole() error {
为啥要定义这个函数

2023-07-28 03:04 UTC, xiaozhu36 commented on website/docs/r/polardb_cluster.html.markdown
> +PolarDB MySQL cluster Turn on TDE encryption
这个地方应该写清楚，开启 TDE 加密的时候，需要确保账号下有一个 xxx role，如果没有的话，可以使用下面的代码进行创建

2023-07-28 03:04 UTC, xiaozhu36 commented on website/docs/r/polardb_cluster.html.markdown
> +-> **NOTE:** If TDE prompts EntityNotExist.Role or NoPermission when enabled, please execute the PolarDB MySQL cluster Turn on TDE encryption script above
这个note 是啥意思，没懂

2023-07-28 03:04 UTC, xiaozhu36 commented on website/docs/r/polardb_cluster.html.markdown
> +* `planned_start_time` - (Optional, Available in v1.209.0+) The earliest time to start executing a scheduled (i.e. within the target time period) kernel version upgrade task. The format is YYYY-MM-DD
所有的 Available in 改成 Available since

2023-07-28 03:49 UTC, Lv0520 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> -			},
就为了先走tde验证，没有特别原因

2023-07-28 03:50 UTC, Lv0520 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +func deleteTDEPolicyAndRole() error {
这个是要删除 tde 相关权限 然后添加权限，如果已经有了权限在跑脚本会报权限已经存在

2023-07-28 03:50 UTC, Lv0520 commented on website/docs/r/polardb_cluster.html.markdown
> +-> **NOTE:** If TDE prompts EntityNotExist.Role or NoPermission when enabled, please execute the PolarDB MySQL cluster Turn on TDE encryption script above
意思就是说，如果开启tde 报这两个错误，拿么就需要执行上面的脚本

2023-07-28 06:08 UTC, xiaozhu36 approved these changes

2023-07-28 09:36 UTC, merged