resource/alicloud_ga_basic_accelerator: Added the field instance_charge_type, cross_border_status, promotion_option_no
aliyun/terraform-provider-alicloud pull request #6349
Opened 2023-07-24 10:06 UTC by MrWolong

2023-07-28 05:56 UTC, xiaozhu36 requested changes

2023-07-28 05:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_basic_accelerator.go
> +				ValidateFunc: StringInSlice([]string{"PREPAY", "POSTPAY"}, false),
一样的问题

2023-07-28 06:37 UTC, MrWolong commented on alicloud/resource_alicloud_ga_basic_accelerator.go
> +				ValidateFunc: StringInSlice([]string{"PREPAY", "POSTPAY"}, false),
已修复

2023-07-31 08:21 UTC, xiaozhu36 requested changes

2023-07-31 08:21 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_basic_accelerator_test.go
> -						"bandwidth_billing_type": "BandwidthPackage",
这个地方应该check computed的属性

2023-07-31 08:46 UTC, MrWolong commented on alicloud/resource_alicloud_ga_basic_accelerator_test.go
> -						"bandwidth_billing_type": "BandwidthPackage",
已在map中添加check computed的属性

2023-07-31 08:53 UTC, xiaozhu36 approved these changes

2023-07-31 09:06 UTC, merged