New Resource: alicloud_arms_prometheus_monitoring; resource/alicloud_arms_remote_write: support remote_write_yaml yaml format.
aliyun/terraform-provider-alicloud pull request #6351
Opened 2023-07-25 04:30 UTC by ChenHanZhang

2023-07-28 02:38 UTC, xiaozhu36 requested changes

2023-07-28 02:38 UTC, xiaozhu36 commented on alicloud/resource_alicloud_arms_prometheus_monitoring.go
> +				Default:      "run",
这个默认值为啥要设置

2023-08-02 08:42 UTC, ChenHanZhang commented on alicloud/resource_alicloud_arms_prometheus_monitoring.go
> +				Default:      "run",
done

2023-08-04 08:25 UTC, xiaozhu36 approved these changes

2023-08-04 08:38 UTC, xiaozhu36 approved these changes

2023-08-04 09:31 UTC, merged