resource/alicloud_oss_bucket: Supports access monitor.
aliyun/terraform-provider-alicloud pull request #6360
Opened 2023-07-27 04:20 UTC by huiguangjun

2023-07-27 05:33 UTC, xiaozhu36 requested changes

2023-07-27 05:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_oss_bucket.go
> +							ValidateFunc: validation.StringInSlice([]string{
这个地方的 validation 的方法，都统一去掉呢 validatation.  前缀，然后改用 provider 自带的方法吧

2023-07-27 05:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_oss_bucket_test.go
> +
对于 Computed 的属性，要在每个testcase 的 testCheck 中加上检查

2023-07-27 05:33 UTC, xiaozhu36 commented on website/docs/r/oss_bucket.html.markdown
> +* `access_monitor` - (Optional, Available in 1.208.1+) A access monitor status of a bucket. See [`access_monitor`](#access_monitor) below.
统一改为 Available since xxx

2023-07-27 06:16 UTC, huiguangjun commented on alicloud/resource_alicloud_oss_bucket.go
> +							ValidateFunc: validation.StringInSlice([]string{
已修改

2023-07-27 06:17 UTC, huiguangjun commented on alicloud/resource_alicloud_oss_bucket_test.go
> +
新增加测试用例，默认步骤已添加对 access_monitor 属性的检查

2023-07-27 06:17 UTC, huiguangjun commented on website/docs/r/oss_bucket.html.markdown
> +* `access_monitor` - (Optional, Available in 1.208.1+) A access monitor status of a bucket. See [`access_monitor`](#access_monitor) below.
已修改

2023-07-27 06:45 UTC, xiaozhu36 requested changes

2023-07-27 06:45 UTC, xiaozhu36 commented on alicloud/resource_alicloud_oss_bucket_test.go
> +
因为是 Computed的，因此为了防止非兼容产生的diff，其他的所有case 的check 中都要加上，测试步骤上可以不设置，但是check上要把 computed的加上

2023-07-27 06:45 UTC, xiaozhu36 commented on alicloud/resource_alicloud_oss_bucket.go
> +								"Enabled",
其他的Validation 也都按照类似的方式处理下吧

2023-07-28 02:31 UTC, huiguangjun commented on website/docs/r/oss_bucket.html.markdown
> +* `access_monitor` - (Optional, Available in 1.208.1+) A access monitor status of a bucket. See [`access_monitor`](#access_monitor) below.
已由另外一个pr 统一修改为 Available since xxx

2023-07-28 02:32 UTC, huiguangjun commented on alicloud/resource_alicloud_oss_bucket.go
> +							ValidateFunc: validation.StringInSlice([]string{
已由另外一个pr 统一去掉 validation

2023-07-28 02:32 UTC, huiguangjun commented on alicloud/resource_alicloud_oss_bucket_test.go
> +
改参数 已去掉 Computed 属性

2023-07-28 06:17 UTC, xiaozhu36 requested changes

2023-07-28 06:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_oss_bucket.go
> +	am := d.Get("access_monitor").([]interface{})
这个地方会有空指针异常，用 GetOk

2023-07-28 06:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_oss_bucket.go
> +	if len(am) == 1 {
判断不需要吧，schema中已经有 MaxItems 的判断了

2023-07-28 06:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_oss_bucket_test.go
> +						"access_monitor.0.status": "Disabled",
既然已经status默认会返回 Disabled，那这个字属性是不是应该设置为 Optional 和 Computed的

2023-07-28 08:26 UTC, xiaozhu36 approved these changes

2023-07-28 08:47 UTC, merged