resource/alicloud_eipanycast_anycast_eip_address_attachment: add new attribute association_mode, pop_locations; resource/alicloud_instance: add new attribute network_interface_id; resource/alicloud_eipanycast_anycast_eip_address: add new attribute resource_group_id.
aliyun/terraform-provider-alicloud pull request #6361
Opened 2023-07-27 05:31 UTC by ChenHanZhang

2023-07-28 02:54 UTC, xiaozhu36 requested changes

2023-07-28 02:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eipanycast_anycast_eip_address_attachment.go
> -				ValidateFunc: validation.StringInSlice([]string{"SlbInstance"}, false),
枚举值怎么去掉了

2023-07-28 02:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eipanycast_anycast_eip_address_attachment.go
> +				Type:     schema.TypeString,
新增加的这个没有枚举值么

2023-07-28 02:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eipanycast_anycast_eip_address_attachment.go
> +		request["ClientToken"] = buildClientToken(action)
&util.RuntimeOptions{} 这个retry 应该直接用 sdk 的重试去做

2023-07-28 02:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_eipanycast_anycast_eip_address_attachment_test.go
> +}
这个地方是不是还应该测试一个 跨境的region

2023-07-28 02:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_vswitch.go
> +				Computed: true,
增加了computed，测试case 的checkmap 不需要更新么

2023-07-28 04:44 UTC, ChenHanZhang commented on alicloud/resource_alicloud_eipanycast_anycast_eip_address_attachment.go
> +				Type:     schema.TypeString,
done

2023-07-28 04:44 UTC, ChenHanZhang commented on alicloud/resource_alicloud_eipanycast_anycast_eip_address_attachment.go
> -				ValidateFunc: validation.StringInSlice([]string{"SlbInstance"}, false),
done

2023-07-28 04:45 UTC, ChenHanZhang commented on alicloud/resource_alicloud_eipanycast_anycast_eip_address_attachment.go
> +		request["ClientToken"] = buildClientToken(action)
done

2023-07-28 04:45 UTC, ChenHanZhang commented on alicloud/resource_alicloud_eipanycast_anycast_eip_address_attachment_test.go
> +}
done

2023-07-28 04:45 UTC, ChenHanZhang commented on alicloud/resource_alicloud_vswitch.go
> +				Computed: true,
并不是所有都返回

2023-07-28 10:05 UTC, xiaozhu36 requested changes

2023-07-28 10:05 UTC, xiaozhu36 commented on website/docs/r/eipanycast_anycast_eip_address.html.markdown
> +* `resource_group_id` - (Optional, Computed, Available since v1.208.0) The ID of the resource group to which the instance belongs.
下个版本208.1

2023-07-28 10:05 UTC, xiaozhu36 commented on alicloud/tags.go
>  		}
CI 没过

return WrapError(Error(fmt.Sprintf("The system disk cannot be queried in this instance %s. Please check whether you have permission to access the API DescribeDisks. Last response is: %v", d.Id, response)))

2023-07-28 10:31 UTC, xiaozhu36 approved these changes

2023-07-31 01:56 UTC, xiaozhu36 approved these changes

2023-07-31 09:22 UTC, xiaozhu36 approved these changes

2023-07-31 09:51 UTC, merged