New Resource: alicloud_event_bridge_api_destination
aliyun/terraform-provider-alicloud pull request #6362
Opened 2023-07-27 07:12 UTC by MrWolong

2023-09-15 03:41 UTC, MrWolong commented on alicloud/service_alicloud_event_bridge_v2.go
> -	if fmt.Sprint(response["Code"]) == "ConnectionNotExist" {
云产品错误码规范之后，这块代码就无效了。可以直接通过期望函数来判断，不需要通过code的值来判断。

2023-09-15 03:41 UTC, MrWolong commented on website/docs/r/event_bridge_connection.html.markdown
> +* `network_type` - (Required) The network type. Valid values: `PublicNetwork`, `PrivateNetwork`. **NOTE:** If you set `network_type` to `PrivateNetwork`, you must configure `vpc_id`, `vswitche_id`, a
文档格式问题，字段后面没有`-`

2023-09-19 01:51 UTC, xiaozhu36 requested changes

2023-09-19 01:51 UTC, xiaozhu36 commented on website/docs/r/event_bridge_api_destination.html.markdown
> +-> **NOTE:** Available since v1.210.1.
既然是新资源，就应该是大版本号

2023-09-28 07:27 UTC, MrWolong commented on website/docs/r/event_bridge_api_destination.html.markdown
> +-> **NOTE:** Available since v1.210.1.
已修复

2023-09-28 07:29 UTC, xiaozhu36 approved these changes

2023-09-28 07:35 UTC, xiaozhu36 approved these changes

2023-09-28 07:42 UTC, closed without merging