New Resource: alicloud_nlb_loadbalancer_common_bandwidth_package_attachment;New Resource: alicloud_nlb_listener_additional_certificate_attachment; alicloud/resource_alicloud_nlb_load_balancer: modify attribute bandwidth_package_id; alicloud/resource_alicloud_nlb_listener: add retry code while removing listener.
aliyun/terraform-provider-alicloud pull request #6365
Opened 2023-07-28 01:26 UTC by ChenHanZhang

2023-07-28 02:42 UTC, xiaozhu36 requested changes

2023-07-28 02:42 UTC, xiaozhu36 commented on alicloud/resource_alicloud_nlb_listener_additional_certificate_attachment.go
> +				Computed: true,
这个为啥是 Optional 的

2023-07-28 02:42 UTC, xiaozhu36 commented on alicloud/resource_alicloud_nlb_loadbalancer_common_bandwidth_package_attachment.go
> +	stateConf := BuildStateConf([]string{}, []string{"Active"}, d.Timeout(schema.TimeoutCreate), 5*time.Second, nlbServiceV2.NlbLoadbalancerCommonBandwidthPackageAttachmentStateRefreshFunc(d.Id(), "Load
attach 之后，nlb_loadbalancer_common_bandwidth_package 在 update 中的等待状态是不是也需要改

2023-08-02 11:24 UTC, ChenHanZhang commented on alicloud/resource_alicloud_nlb_listener_additional_certificate_attachment.go
> +				Computed: true,
spec定义错误，已让云产品更正

2023-08-02 11:25 UTC, ChenHanZhang commented on alicloud/resource_alicloud_nlb_loadbalancer_common_bandwidth_package_attachment.go
> +	stateConf := BuildStateConf([]string{}, []string{"Active"}, d.Timeout(schema.TimeoutCreate), 5*time.Second, nlbServiceV2.NlbLoadbalancerCommonBandwidthPackageAttachmentStateRefreshFunc(d.Id(), "Load
和云产品确认无新的状态

2023-08-04 08:29 UTC, xiaozhu36 approved these changes

2023-08-04 09:41 UTC, xiaozhu36 approved these changes

2023-08-07 05:48 UTC, xiaozhu36 approved these changes

2023-08-07 06:15 UTC, merged