resource/alicloud_oss_bucket: lifecycle_rule supports tag.
aliyun/terraform-provider-alicloud pull request #6372
Opened 2023-07-31 02:12 UTC by huiguangjun

2023-07-31 04:52 UTC, xiaozhu36 requested changes

2023-07-31 04:52 UTC, xiaozhu36 commented on alicloud/resource_alicloud_oss_bucket.go
> +							Optional: true,
阿里云所有的tags 的类型在 terraform 中都统一的是 map，所以这个也统一下吧

2023-07-31 04:52 UTC, xiaozhu36 commented on website/docs/r/oss_bucket.html.markdown
> +* `tag` - (Optional, Available since 1.208.2) The tag of objects that match the rule. You can specify multiple tags. See [`tag`](#lifecycle_rule-tag) below.
208.1 还没发布，先改成 208.1 吧

2023-08-03 03:49 UTC, huiguangjun commented on website/docs/r/oss_bucket.html.markdown
> +* `tag` - (Optional, Available since 1.208.2) The tag of objects that match the rule. You can specify multiple tags. See [`tag`](#lifecycle_rule-tag) below.
已修改

2023-08-04 08:09 UTC, xiaozhu36 approved these changes

2023-08-04 08:26 UTC, merged