resource/alicloud_db_instance: Added the field direction; resource/alicloud_db_readonly_instance: Added the field direction.
aliyun/terraform-provider-alicloud pull request #6379
Opened 2023-08-02 06:30 UTC by zcc01029273

resource/alicloud_db_instance: Added the field direction; resource/alicloud_db_readonly_instance: Added the field direction.

2023-08-03 01:35 UTC, xiaozhu36 requested changes

2023-08-03 01:35 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance_test.go
> +					"auto_upgrade_minor_version": "Manual",
这个case为啥要改

2023-08-03 01:35 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_readonly_instance_test.go
> +				ImportStateVerifyIgnore: []string{"force_restart", "period", "auto_renew_period", "auto_renew"},
放在最后一步测试

2023-08-03 01:39 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_instance_test.go
> +					"auto_upgrade_minor_version": "Manual",
这个是给pg把设置内核小版本自动升级方式放开了，这个字段auto_upgrade_minor_version，test里面把这个字段添加了下

2023-08-03 02:01 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_readonly_instance_test.go
> +				ImportStateVerifyIgnore: []string{"force_restart", "period", "auto_renew_period", "auto_renew"},
done

2023-08-03 03:04 UTC, xiaozhu36 requested changes

2023-08-03 03:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance_test.go
> +					"auto_upgrade_minor_version": "Manual",
如果不是必填的，那么不应该放在step 0，如果想要测试变更，那么可以在后面的step中修改

2023-08-03 03:32 UTC, zcc01029273 commented on alicloud/resource_alicloud_db_instance_test.go
> +					"auto_upgrade_minor_version": "Manual",
done

2023-08-03 06:58 UTC, xiaozhu36 approved these changes

2023-08-03 09:01 UTC, xiaozhu36 approved these changes

2023-08-04 08:01 UTC, xiaozhu36 approved these changes

2023-08-07 06:15 UTC, xiaozhu36 approved these changes

2023-08-08 08:21 UTC, xiaozhu36 approved these changes

2023-08-08 08:42 UTC, xiaozhu36 approved these changes

2023-08-09 01:41 UTC, merged