New Resource: alicloud_tag_meta_tag
aliyun/terraform-provider-alicloud pull request #6384
Opened 2023-08-04 03:21 UTC by fuliu-zln

2023-08-04 03:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6384) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6384) before we can accept your contribution.<br/><hr/>**wb-zln530580** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=6384) it.</sub>

2023-08-04 12:06 UTC, xiaozhu36 requested changes

2023-08-04 12:06 UTC, xiaozhu36 commented on alicloud/resource_alicloud_tag_meta_tag.go
> +	parts, err := ParseResourceId(d.Id(), 2)
这个地方的解析不对吧，如果key中含有冒号，那么这个解析会报错

2023-08-07 02:52 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_meta_tag.go
> +	parts, err := ParseResourceId(d.Id(), 2)
已修改

2023-08-07 07:05 UTC, xiaozhu36 requested changes

2023-08-07 07:05 UTC, xiaozhu36 commented on alicloud/resource_alicloud_tag_meta_tag.go
> +			"key_name": {
这个字段应该跟 API保持一致，用 key

2023-08-07 07:16 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_meta_tag.go
> +				ValidateFunc: validation.StringLenBetween(1, 128),
done

2023-08-07 07:17 UTC, fuliu-zln commented on alicloud/resource_alicloud_tag_meta_tag.go
> +			"key_name": {
done

2023-08-07 11:06 UTC, xiaozhu36 approved these changes

2023-08-08 01:57 UTC, xiaozhu36 requested changes

2023-08-08 01:57 UTC, xiaozhu36 commented on alicloud/provider.go
> -			"alicloud_nas_access_rule":                                      resourceAlicloudNasAccessRule(),
这个nas 的资源为啥要删掉

2023-08-08 01:57 UTC, xiaozhu36 commented on website/docs/r/tag_meta_tag.html.markdown
> +
如果目前只支持 cn-hangzhou，那么要在此处增加note

2023-08-08 02:15 UTC, fuliu-zln commented on website/docs/r/tag_meta_tag.html.markdown
> +
done

2023-08-08 02:59 UTC, xiaozhu36 approved these changes

2023-08-08 03:54 UTC, merged