add CI flow: check the coverage rate of test cases
aliyun/terraform-provider-alicloud pull request #6387
Opened 2023-08-04 09:41 UTC by shanye997

2023-08-04 11:43 UTC, xiaozhu36 requested changes

2023-08-04 11:43 UTC, xiaozhu36 commented on scripts/test_coverage_rate_check.go
> +	testFile  = "alicloud/resource_alicloud_bastionhost_user_group_test.go"
这个地方写死一个文件的作用是啥？

2023-08-04 11:43 UTC, xiaozhu36 commented on scripts/test_coverage_rate_check.go
> +	}
直接 os.Exit(exitCode) 即可

2023-08-04 11:43 UTC, xiaozhu36 commented on scripts/test_coverage_rate_check.go
> +			// fmt.Println(funcName)
无用的注释去掉

2023-08-04 11:43 UTC, xiaozhu36 commented on scripts/test_coverage_rate_check.go
> +		log.Errorf("%s %s 's [Required or Optional] attributes %v have not been tested", fileType, resourceName, string(notCoverStr))
log.Errorf(“resource %s attributes %v missing test cases", resourceName, string(notCoverStr))

2023-08-04 11:43 UTC, xiaozhu36 commented on scripts/test_coverage_rate_check.go
> +		log.Infof("%.2f%% of required or optional] attributes are covered by test cases", coverageRate*100)
log.Infof("resource %s attributes has %.2f%%  testing coverage rate ", resourceName, coverageRate*100)

2023-08-04 11:43 UTC, xiaozhu36 commented on scripts/test_coverage_rate_check.go
> +		log.Infof("100%% of required or optional] attributes are covered by test cases")
这个也一样，改下

2023-08-04 11:43 UTC, xiaozhu36 commented on scripts/test_coverage_rate_check.go
> +		log.Errorf("%s %s 's [non-ForceNew] attributes %v  have not been modified", fileType, resourceName, string(notModifyStr))
这个地方区分非forceNew 的目的是啥

2023-08-07 01:29 UTC, shanye997 commented on scripts/test_coverage_rate_check.go
> +	testFile  = "alicloud/resource_alicloud_bastionhost_user_group_test.go"
这个是测试用的，忘记删掉了，我删掉他

2023-08-07 01:29 UTC, shanye997 commented on scripts/test_coverage_rate_check.go
> +	}
好的

2023-08-07 01:31 UTC, shanye997 commented on scripts/test_coverage_rate_check.go
> +		log.Infof("100%% of required or optional] attributes are covered by test cases")
好的

2023-08-07 01:32 UTC, shanye997 commented on scripts/test_coverage_rate_check.go
> +		log.Errorf("%s %s 's [non-ForceNew] attributes %v  have not been modified", fileType, resourceName, string(notModifyStr))
这个是当时区分一下属性，那我还是按照上面的改一下

2023-08-07 03:56 UTC, merged