testing_coverage_rate_check: check the function name
aliyun/terraform-provider-alicloud pull request #6402
Opened 2023-08-09 05:54 UTC by shanye997

2023-08-09 11:10 UTC, xiaozhu36 requested changes

2023-08-09 11:10 UTC, xiaozhu36 commented on scripts/testing_coverage_rate_check.go
> +				log.Errorf("function name [%s] is not standard", name)
对于不符合规范的测试用例，应该在错误信息中给出指导建议

2023-08-09 12:38 UTC, shanye997 commented on scripts/testing_coverage_rate_check.go
> +				log.Errorf("function name [%s] is not standard", name)
好的

2023-08-10 12:24 UTC, xiaozhu36 requested changes

2023-08-10 12:24 UTC, xiaozhu36 commented on scripts/testing_coverage_rate_check.go
> +				log.Errorf("function name [%s] is not standard. It should start with [TestAccAliCloud]", name)
log.Errorf("testcase %s should start with TestAccAliCloud", name)

2023-08-10 12:44 UTC, xiaozhu36 approved these changes

2023-08-10 12:51 UTC, merged