resource/alicloud_polardb_cluster: poladb db support proxy_type、proxy…
aliyun/terraform-provider-alicloud pull request #6404
Opened 2023-08-10 08:26 UTC by Lv0520

…_class、loose_polar_log_bin

2023-08-21 02:02 UTC, xiaozhu36 requested changes

2023-08-21 02:02 UTC, xiaozhu36 commented on alicloud/validators.go
> +	}
参考其他的 Validation 进行编写，并增加对该 Validation的单元测试

2023-08-21 02:02 UTC, Lv0520 commented on alicloud/resource_alicloud_polardb_cluster.go
> +				ForceNew:         true,
是的

2023-08-22 02:07 UTC, Lv0520 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					"db_node_class":      "polar.mysql.x4.large",
这个接口有多种规格的，如果添加一种新的规格返回的第一条可能不是独享规格的，我这里就测试的独享规格的所以就写死来处理

2023-08-22 14:01 UTC, xiaozhu36 approved these changes

2023-08-22 14:01 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +	if len(clusterAttribute.DBNodes) > 0 {
为啥只比对主可用区

2023-08-24 09:20 UTC, xiaozhu36 requested changes

2023-08-24 09:20 UTC, xiaozhu36 commented on website/docs/r/polardb_cluster.html.markdown
> +* `parameter_group_id` - (Optional, ForceNew, Available since 1.210.0) The ID of the parameter template
这几个不是ForceNew的属性，在文档中不能标记为 ForceNew

2023-08-24 11:34 UTC, xiaozhu36 approved these changes

2023-08-25 06:11 UTC, xiaozhu36 approved these changes

2023-08-28 09:02 UTC, xiaozhu36 approved these changes

2023-08-31 09:17 UTC, xiaozhu36 approved these changes

2023-09-01 05:35 UTC, xiaozhu36 approved these changes

2023-09-01 08:35 UTC, xiaozhu36 approved these changes

2023-09-04 01:42 UTC, xiaozhu36 requested changes

2023-09-04 01:42 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> -				ValidateFunc: IntBetween(20, 32000),
这个限制条件为啥去掉了

2023-09-07 10:57 UTC, xiaozhu36 approved these changes

2023-09-08 14:00 UTC, xiaozhu36 approved these changes

2023-09-11 07:25 UTC, xiaozhu36 approved these changes

2023-09-11 11:17 UTC, merged