ci: Adds the docs example checks
aliyun/terraform-provider-alicloud pull request #6418
Opened 2023-08-16 09:00 UTC by cafeshadown

Added file： .github/workflows/document-example.yml,ci/tasks/docs-example.sh,ci/tasks/docs-example-provider.tf,scripts/docs_example_check.go,ci/tasks/docs-example.yml

2023-08-21 02:28 UTC, xiaozhu36 requested changes

2023-08-21 02:28 UTC, xiaozhu36 commented on .github/workflows/document-example.yml
> +                echo -e "\033[33m[WARNING]\033[0m missing the acceptance examples in the $resourceName, continue..."
缺少文档示例，应该直接报错吧

2023-08-21 02:28 UTC, xiaozhu36 commented on ci/tasks/docs-example.sh
> +          echo "--- FAIL: ${exampleFileName}" | tee -a ${exampleTestRunResultLog}
运行完 apply，如果没有报错，还应该再执行一次 plan， 检查下是否有 diff

2023-08-21 03:29 UTC, cafeshadown reviewed
test

2023-08-24 07:03 UTC, xiaozhu36 requested changes

2023-08-24 07:03 UTC, xiaozhu36 commented on ci/tasks/docs-example-provider.tf
> +      version = "1.200.0"
这个地方为啥写死

2023-08-24 07:12 UTC, cafeshadown commented on ci/tasks/docs-example-provider.tf
> +      version = "1.200.0"
打的本地包 然后运行，参考之前的方案 就写死了

2023-09-01 10:04 UTC, xiaozhu36 requested changes

2023-09-01 10:04 UTC, xiaozhu36 commented on .github/workflows/document-example.yml
> +              echo ${fileName}
这个地方应该还包含一个 datasource example的测试吧： "website/docs/d/"

2023-09-01 12:10 UTC, cafeshadown commented on .github/workflows/document-example.yml
> +              echo ${fileName}
已加入data source相关Example测试

2023-09-01 14:46 UTC, xiaozhu36 requested changes

2023-09-01 14:46 UTC, xiaozhu36 commented on ci/tasks/docs-example-provider.tf
> +      version = "1.209.0-alpha"
这个改成 1.x.0-alpha

2023-09-03 09:58 UTC, xiaozhu36 approved these changes

2023-09-03 09:59 UTC, merged