New Resource: alicloud_kms_instance; New Resource alicloud_kms_network_rule; New Resoruce alicloud_kms_policy.
aliyun/terraform-provider-alicloud pull request #6432
Opened 2023-08-21 09:34 UTC by ChenHanZhang

2023-09-06 15:02 UTC, xiaozhu36 requested changes

2023-09-06 15:02 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kms_network_rule.go
> +	return resourceAliCloudKmsNetworkRuleUpdate(d, meta)
已经都设置了，为啥还是update

2023-09-06 15:02 UTC, xiaozhu36 commented on website/docs/r/kms_instance.html.markdown
> +  vpc_name   = "${var.name}7"
格式

2023-09-11 06:54 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kms_application_access_point.go
> +	return resourceAliCloudKmsApplicationAccessPointUpdate(d, meta)
done, create之后是否需要进行update的判定，在属性为数组类型的时候存在bug，已修复

2023-09-11 06:54 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kms_client_key.go
> +				Optional: true,
done，spec上应增加一个format类型

2023-09-11 06:54 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kms_network_rule.go
> +	return resourceAliCloudKmsNetworkRuleUpdate(d, meta)
同上原因，已修复

2023-09-11 06:54 UTC, ChenHanZhang commented on website/docs/r/kms_instance.html.markdown
> +  vpc_name   = "${var.name}7"
done

2023-09-11 07:02 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kms_instance.go
> +				Optional: true,
done

2023-09-12 15:17 UTC, xiaozhu36 approved these changes

2023-09-13 01:55 UTC, xiaozhu36 requested changes

2023-09-13 01:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kms_client_key_test.go
> +				ImportStateVerifyIgnore: []string{"password", "secret_file"},
既不返回，也非敏感的，不应该设置为forceNew 和 required

2023-09-13 01:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kms_instance.go
> +			"product_type": {
如果用的是 bss 的API，那么这个应该当作常量

2023-09-13 01:55 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kms_instance_test.go
> +				ImportStateVerifyIgnore: []string{"product_type", "product_version", "renew_period", "renew_status"},
同样的问题

2023-09-13 05:04 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kms_client_key_test.go
> +				ImportStateVerifyIgnore: []string{"password", "secret_file"},
secret_file 设置为Optional、ForceNew的了，和alicloud_ram_access_key保持一致

2023-09-13 05:04 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kms_instance.go
> +			"product_type": {
done

2023-09-13 05:04 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kms_instance_test.go
> +				ImportStateVerifyIgnore: []string{"product_type", "product_version", "renew_period", "renew_status"},
product_type已去掉

2023-09-13 10:00 UTC, xiaozhu36 requested changes

2023-09-13 10:00 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kms_instance_test.go
> +						},
这个改成 account 的datasource

2023-09-13 10:00 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kms_instance_test.go
> +							"vswitch_id":   "vsw-bp1wujtnspi1l3gvunvds",
硬编码

2023-09-13 10:00 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kms_instance_test.go
> +func SkipTestAccAlicloudKmsInstance_basic4048_intl(t *testing.T) {
不要跳过

2023-09-13 10:00 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kms_client_key.go
> +			"secret_file": {
改成 private_key_data_file

2023-09-13 10:00 UTC, xiaozhu36 commented on alicloud/resource_alicloud_kms_instance_test.go
> +				ImportStateVerifyIgnore: []string{"product_version", "renew_period", "renew_status"},
renew 的属性可以通过 bss 的OpenAPI 获取到

2023-09-13 10:00 UTC, xiaozhu36 commented on alicloud/service_alicloud_kms_v2.go
> +			return object, WrapErrorf(Error(GetNotFoundMessage("ApplicationAccessPoint", id)), NotFoundMsg, ProviderERROR, fmt.Sprint(response["RequestId"]))
这种不存在的错误码，通过改成 NotFoundMsgWithResponse 吧：
object, WrapErrorf(Error(GetNotFoundMessage("ApplicationAccessPoint", id)), NotFoundMsg, response)

2023-09-14 05:39 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kms_instance_test.go
> +				ImportStateVerifyIgnore: []string{"product_version", "renew_period", "renew_status"},
哪个接口？这几个字段目前还不支持修改，相当于创建的操作私有参数，是不是没必填多编排一个bss的api

2023-09-14 05:41 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kms_instance_test.go
> +func SkipTestAccAlicloudKmsInstance_basic4048_intl(t *testing.T) {
done

2023-09-14 05:41 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kms_instance_test.go
> +						},
资源共享的账号ID，目前不支持其它方式

2023-09-14 05:41 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kms_instance_test.go
> +							"vswitch_id":   "vsw-bp1wujtnspi1l3gvunvds",
同上，这个确认步骤存在先后顺序，目前测试流程中无法做到自动化

2023-09-14 06:13 UTC, ChenHanZhang commented on alicloud/service_alicloud_kms_v2.go
> +			return object, WrapErrorf(Error(GetNotFoundMessage("ApplicationAccessPoint", id)), NotFoundMsg, ProviderERROR, fmt.Sprint(response["RequestId"]))
done

2023-09-14 06:21 UTC, ChenHanZhang commented on alicloud/resource_alicloud_kms_client_key.go
> +			"secret_file": {
done

2023-09-14 13:11 UTC, xiaozhu36 approved these changes

2023-09-15 02:36 UTC, xiaozhu36 approved these changes

2023-09-15 03:10 UTC, xiaozhu36 approved these changes

2023-09-15 04:03 UTC, xiaozhu36 approved these changes

2023-09-15 09:18 UTC, merged