docs: Improves the docs example
aliyun/terraform-provider-alicloud pull request #6434
Opened 2023-08-22 07:39 UTC by susu9527

2023-08-29 14:30 UTC, xiaozhu36 requested changes

2023-08-29 14:30 UTC, xiaozhu36 commented on website/docs/r/nlb_load_balancer.html.markdown
> +* `deletion_protection_enabled` - (Optional, Available in 1.206.0+) Specifies whether to enable deletion protection. Default value: `false`. Valid values:
Available since

2023-08-30 03:13 UTC, susu9527 commented on website/docs/r/nlb_load_balancer.html.markdown
> +* `deletion_protection_enabled` - (Optional, Available in 1.206.0+) Specifies whether to enable deletion protection. Default value: `false`. Valid values:
已改

2023-08-30 06:53 UTC, xiaozhu36 approved these changes

2023-08-30 06:55 UTC, merged