data-source/alicloud_wafv3_domains: Fixed the panic error
aliyun/terraform-provider-alicloud pull request #6454
Opened 2023-08-29 08:21 UTC by MrWolong

2023-08-30 07:11 UTC, xiaozhu36 requested changes

2023-08-30 07:11 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_wafv3_domains.go
> +		//mapping["resource_manager_resource_group_id"] = object["ResourceManagerResourceGroupId"]
这些无用代码删掉

2023-08-30 07:21 UTC, MrWolong commented on alicloud/data_source_alicloud_wafv3_domains.go
> +		//mapping["resource_manager_resource_group_id"] = object["ResourceManagerResourceGroupId"]
已修复

2023-09-01 07:25 UTC, xiaozhu36 approved these changes

2023-09-01 07:49 UTC, merged