resource/alicloud_oos_patch_baseline: rejected_patches, rejected_patches_action.
aliyun/terraform-provider-alicloud pull request #6459
Opened 2023-08-30 09:27 UTC by ChenHanZhang

2023-08-30 15:04 UTC, xiaozhu36 requested changes

2023-08-30 15:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_oos_patch_baseline.go
> +	jsonMarshalResult, err := json.Marshal(objectRaw["ApprovalRules"])
这个err没处理啊

2023-08-31 07:25 UTC, ChenHanZhang commented on alicloud/resource_alicloud_oos_patch_baseline.go
> +	jsonMarshalResult, err := json.Marshal(objectRaw["ApprovalRules"])
done

2023-08-31 15:41 UTC, xiaozhu36 approved these changes

2023-08-31 23:02 UTC, merged