resource/alicloud_ocean_base_instance: modify attribute instance_class supports more specification; docs: Improves the ocean_base_instance docs.
aliyun/terraform-provider-alicloud pull request #6460
Opened 2023-08-30 09:45 UTC by ChenHanZhang

2023-08-31 15:48 UTC, xiaozhu36 requested changes

2023-08-31 15:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_instance.go
> +				Default:  false,
为啥会有这个默认值

2023-08-31 15:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_instance.go
> +				Default:      "delete_all",
之前没有默认值，现在有，这是不兼容的

2023-09-01 10:07 UTC, xiaozhu36 approved these changes

2023-09-06 14:53 UTC, xiaozhu36 requested changes

2023-09-06 14:53 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_instance.go
> +				Optional: true,
这个的抑制函数呢

2023-09-06 14:53 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_instance.go
> +				Required: true,
validate丢了

2023-09-06 14:53 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_instance.go
> -				DiffSuppressFunc: PostPaidDiffSuppressFunc,
这两个也是

2023-09-07 03:21 UTC, ChenHanZhang commented on alicloud/resource_alicloud_ocean_base_instance.go
> +				Optional: true,
done

2023-09-07 03:21 UTC, ChenHanZhang commented on alicloud/resource_alicloud_ocean_base_instance.go
> +				Required: true,
done

2023-09-07 03:21 UTC, ChenHanZhang commented on alicloud/resource_alicloud_ocean_base_instance.go
> -				DiffSuppressFunc: PostPaidDiffSuppressFunc,
done

2023-09-07 08:07 UTC, xiaozhu36 requested changes

2023-09-07 08:07 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ocean_base_instance.go
> +				ForceNew: true,
这个ob_version没有枚举值么？客户怎么知道应该填写什么

2023-09-07 09:51 UTC, ChenHanZhang commented on alicloud/resource_alicloud_ocean_base_instance.go
> +				ForceNew: true,
没有枚举值，目前还没有对应的文档，云产品反馈接口提测中

2023-09-11 05:40 UTC, ChenHanZhang commented on alicloud/resource_alicloud_ocean_base_instance.go
> +				ForceNew: true,
云产品反馈目前该字段的可选值尚无文档，该字段通过接口获取可选值，接口以及文档提测中。目前normandy依赖该属性，该版本增加了资源删除时的资源不存在错误码

2023-09-11 15:12 UTC, xiaozhu36 approved these changes

2023-09-13 01:46 UTC, xiaozhu36 approved these changes

2023-09-13 08:09 UTC, merged