resource/alicloud_ga_endpoint_group: Improved default create and delete timeout
aliyun/terraform-provider-alicloud pull request #6461
Opened 2023-08-31 12:37 UTC by MrWolong

2023-09-01 14:49 UTC, xiaozhu36 requested changes

2023-09-01 14:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ga_endpoint_group_test.go
>  }
既然新增了computed的属性，那么这个地方要进行check

2023-09-04 02:31 UTC, MrWolong commented on alicloud/resource_alicloud_ga_endpoint_group_test.go
>  }
已修复

2023-09-05 05:31 UTC, xiaozhu36 approved these changes

2023-09-05 07:18 UTC, merged