docs: Improves the rm docs example
aliyun/terraform-provider-alicloud pull request #6478
Opened 2023-09-05 06:36 UTC by susu9527

2023-09-14 01:40 UTC, xiaozhu36 requested changes

2023-09-14 01:40 UTC, xiaozhu36 commented on website/docs/r/redis_tair_instance.html.markdown
>  }
这个为啥要写死region

2023-09-14 03:30 UTC, susu9527 commented on website/docs/r/redis_tair_instance.html.markdown
>  }
已改

2023-09-15 10:25 UTC, xiaozhu36 approved these changes

2023-09-19 01:52 UTC, xiaozhu36 approved these changes

2023-09-22 00:55 UTC, xiaozhu36 approved these changes

2023-09-22 01:28 UTC, merged