resource/alicloud_threat_detecation_instance: add new attributes.
aliyun/terraform-provider-alicloud pull request #6479
Opened 2023-09-05 07:10 UTC by ChenHanZhang

2023-09-06 14:50 UTC, xiaozhu36 requested changes

2023-09-11 06:36 UTC, ChenHanZhang commented on alicloud/resource_alicloud_threat_detection_instance.go
> +				Type:         schema.TypeString,
done

2023-09-11 06:37 UTC, ChenHanZhang commented on alicloud/resource_alicloud_threat_detection_instance.go
> +				Deprecated:   "Field 'container_image_scan' has been deprecated from provider version 1.210.0. Container Image security scan. Interval type, value interval:[0,200000].> The step size is 20, that
api参数上加了新的字段，和原先的字段区分开了

2023-09-12 03:28 UTC, ChenHanZhang commented on alicloud/resource_alicloud_threat_detection_instance.go
> +				Deprecated:   "Field 'container_image_scan' has been deprecated from provider version 1.210.0. Container Image security scan. Interval type, value interval:[0,200000].> The step size is 20, that
从产品定义设计上已经区分开了

2023-10-27 07:00 UTC, ChenHanZhang commented on alicloud/resource_alicloud_threat_detection_instance.go
> +				Deprecated:   "Field 'container_image_scan' has been deprecated from provider version 1.210.0. Container Image security scan. Interval type, value interval:[0,200000].> The step size is 20, that
实际上这两个字段相当于新版本和老版本的区别，都可以使用，可以共用

2023-10-30 02:36 UTC, xiaozhu36 requested changes

2023-10-30 02:36 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_instance.go
> +				Deprecated:   "Field 'container_image_scan' has been deprecated from provider version 1.210.0. Container Image security scan. Interval type, value interval:[0,200000].> The step size is 20, that
弃用的版本号改下

2023-10-31 01:44 UTC, xiaozhu36 approved these changes

2023-11-02 06:12 UTC, merged