resource/alicloud_polardb_cluster: support hot_replica_mode
aliyun/terraform-provider-alicloud pull request #6500
Opened 2023-09-14 06:55 UTC by mengliux

resource/alicloud_polardb_cluster: support hot_replica_mode

2023-09-14 09:08 UTC, xiaozhu36 requested changes

2023-09-14 09:08 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +	if !d.IsNewResource() && d.HasChange("hot_replica_mode") {
这个字段，如果没有在 Create 阶段设置，那么这个地方不需要 !d.IsNewResource()

2023-09-14 09:08 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +			resourceDbNodeId = "pi-nodeIdRoIndex"
这个地方写死是什么意思

2023-09-14 09:08 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					"db_node_id":       "pi-nodeIdRoIndex",
不好写死，使用资源引用

2023-09-19 10:17 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +	if !d.IsNewResource() && d.HasChange("hot_replica_mode") {
ok

2023-09-19 10:25 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					"db_node_id":       "pi-nodeIdRoIndex",
因为资源node只能操作只读节点，其他节点在创建集群时默认创建的节点，对于默认节点来说不能在node资源创建，没有完整的周期，所以资源不能接入。
但是，我想到另一种方案：
用户可在dbCluster资源创建时候，传要修改热备的默认节点下标；也可以创建完成后，通过导致入节点ID、热备参数进行修改。

2023-09-19 10:26 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +			resourceDbNodeId = "pi-nodeIdRoIndex"
改了

2023-10-19 06:49 UTC, xiaozhu36 requested changes

2023-10-19 06:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +			if len(v.(string)) > 2 {
为啥要增加长度的判断

2023-10-19 06:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +					if !d.IsNewResource() && NotFoundError(err) {
如果查不到，直接报错就行

2023-10-19 06:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"db_node_id": {
这两个参数的关系是怎样的

2023-10-19 06:49 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +						"hot_replica_mode": "ON",
新增加的属性，不需要单独一个case，直接在一个已有的case 中增加step 就行

另外，如果两个参数没有关系，那么应该单独修改

2023-10-19 06:49 UTC, xiaozhu36 commented on website/docs/r/polardb_cluster.html.markdown
> +* `hot_replica_mode` - (Optional, Available since v1.211.0) Indicates whether the hot standby feature is enabled. Valid values are `ON`, `OFF`. Only MySQL supports.
下个版本是 1.211.2

2023-10-20 03:23 UTC, mengliux commented on website/docs/r/polardb_cluster.html.markdown
> +* `hot_replica_mode` - (Optional, Available since v1.211.0) Indicates whether the hot standby feature is enabled. Valid values are `ON`, `OFF`. Only MySQL supports.
OK

2023-10-20 03:25 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +						"hot_replica_mode": "ON",
OK，放到已有方法 TestAccAliCloudPolarDBCluster_CreateNormal
这是一个接口同时需要的参数

2023-10-20 03:27 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"db_node_id": {
修改节点热备时同时需要这俩参数，已经加了RequiredWith

2023-10-20 03:27 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +					if !d.IsNewResource() && NotFoundError(err) {
ok ,去掉了

2023-10-20 03:28 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +			if len(v.(string)) > 2 {
因为这个参数可以传节点id，也可以传节点的下标，文档中有说明

2023-10-20 03:29 UTC, mengliux commented on alicloud/resource_alicloud_polardb_cluster.go
> +			if len(v.(string)) > 2 {
当是下标，就获取实例的节点id

2023-10-20 03:35 UTC, xiaozhu36 requested changes

2023-10-20 03:35 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +			"db_node_id": {
加错了吧，应该咋 db_node_id 上加 `RequiredWith: []string{"hot_replica_mode"}`

2023-10-20 06:17 UTC, xiaozhu36 approved these changes

2023-10-20 09:05 UTC, closed without merging