resource/alicloud_common_bandwidth_package_attachment: add new attribute ip_type; resource/alicloud_vpc_network_acl_attachment: optimized code implementation; resource/alicloud_vpc_traffic_mirror_filter_egress_rule: add new attribute action; resource/alicloud_vpc_traffic_mirror_ingress_rule: add new attribute action.
aliyun/terraform-provider-alicloud pull request #6514
Opened 2023-09-19 01:20 UTC by ChenHanZhang

2023-09-22 08:31 UTC, xiaozhu36 requested changes

2023-09-22 08:31 UTC, xiaozhu36 commented on website/docs/r/common_bandwidth_package_attachment.html.markdown
> +* `ip_type` - (Optional, Available since v1.210.0) IP type. Set the value to **EIP**, which indicates that the EIP is added to the Internet shared bandwidth.
下个版本是 1.211.0

2023-09-22 08:31 UTC, xiaozhu36 commented on website/docs/r/havip_attachment.html.markdown
> +* `ha_vip_id` - (Optional, ForceNew, Available since v1.18.0) The ID of the HaVip instance.
这个available 版本不对吧

2023-09-22 08:31 UTC, xiaozhu36 commented on website/docs/r/vpc_traffic_mirror_filter_egress_rule.html.markdown
> +* `rule_action` - (Deprecated since v1.201.3). Field 'rule_action' has been deprecated from provider version 1.201.3. New field 'action' instead.
这个版本也不对

2023-09-22 08:31 UTC, xiaozhu36 commented on website/docs/r/vpc_traffic_mirror_filter_ingress_rule.html.markdown
> +* `rule_action` - (Deprecated since v1.201.3). Field 'rule_action' has been deprecated from provider version 1.201.3. New field 'action' instead.
还有这个

2023-09-25 06:59 UTC, ChenHanZhang commented on website/docs/r/vpc_traffic_mirror_filter_ingress_rule.html.markdown
> +* `rule_action` - (Deprecated since v1.201.3). Field 'rule_action' has been deprecated from provider version 1.201.3. New field 'action' instead.
done

2023-09-25 06:59 UTC, ChenHanZhang commented on website/docs/r/vpc_traffic_mirror_filter_egress_rule.html.markdown
> +* `rule_action` - (Deprecated since v1.201.3). Field 'rule_action' has been deprecated from provider version 1.201.3. New field 'action' instead.
done

2023-09-25 07:02 UTC, ChenHanZhang commented on website/docs/r/common_bandwidth_package_attachment.html.markdown
> +* `ip_type` - (Optional, Available since v1.210.0) IP type. Set the value to **EIP**, which indicates that the EIP is added to the Internet shared bandwidth.
done

2023-09-25 07:02 UTC, ChenHanZhang commented on website/docs/r/havip_attachment.html.markdown
> +* `ha_vip_id` - (Optional, ForceNew, Available since v1.18.0) The ID of the HaVip instance.
done

2023-09-26 08:55 UTC, xiaozhu36 approved these changes

2023-09-27 01:03 UTC, xiaozhu36 approved these changes

2023-09-27 03:19 UTC, xiaozhu36 approved these changes

2023-09-27 06:46 UTC, xiaozhu36 approved these changes

2023-09-27 08:56 UTC, xiaozhu36 reviewed
approved

2023-09-27 08:57 UTC, xiaozhu36 approved these changes

2023-09-27 11:13 UTC, merged