New Resource: alicloud_drds_polardbx_instance.
aliyun/terraform-provider-alicloud pull request #6522
Opened 2023-09-20 01:56 UTC by ChenHanZhang

2023-09-22 12:11 UTC, xiaozhu36 requested changes

2023-09-22 12:11 UTC, xiaozhu36 commented on alicloud/provider.go
> +			"alicloud_drds_polardb_x_instance":                              resourceAliCloudDrdsPolardbXInstance(),
这个是不是应该叫做 alicloud_drds_polardbx_instance

2023-09-22 12:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_drds_polardb_x_instance.go
> +	request["ZoneId"] = "null"
这个设置为 null 是啥意思

2023-09-22 12:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_drds_polardb_x_instance_test.go
> +	"create_time": CHECKSET,
包含所有computed 的属性，比如 zone

2023-09-22 12:11 UTC, xiaozhu36 commented on alicloud/resource_alicloud_drds_polardb_x_instance_test.go
> +					"primary_zone":   "cn-hangzhou-h",
写死的杭州，需要支持precheck

2023-09-22 12:11 UTC, xiaozhu36 commented on website/docs/r/drds_polardb_x_instance.html.markdown
> +For information about DRDS Polardb X Instance and how to use it, see [What is Polardb X Instance](https://www.alibabacloud.com/help/en/).
没有文档么？

2023-09-25 05:41 UTC, ChenHanZhang commented on alicloud/provider.go
> +			"alicloud_drds_polardb_x_instance":                              resourceAliCloudDrdsPolardbXInstance(),
done

2023-09-25 05:42 UTC, ChenHanZhang commented on alicloud/resource_alicloud_drds_polardb_x_instance.go
> +	request["ZoneId"] = "null"
和云产品确认，这个参数传固定值null即可，不需要使用到

2023-09-25 05:42 UTC, ChenHanZhang commented on alicloud/resource_alicloud_drds_polardb_x_instance_test.go
> +					"primary_zone":   "cn-hangzhou-h",
done

2023-09-25 05:42 UTC, ChenHanZhang commented on website/docs/r/drds_polardb_x_instance.html.markdown
> +For information about DRDS Polardb X Instance and how to use it, see [What is Polardb X Instance](https://www.alibabacloud.com/help/en/).
done

2023-09-26 02:11 UTC, ChenHanZhang commented on alicloud/resource_alicloud_drds_polardb_x_instance_test.go
> +	"create_time": CHECKSET,
zone 没有被使用到，实际上在底下的参数映射中直接传了 null，已去掉

2023-09-26 08:57 UTC, xiaozhu36 approved these changes

2023-09-27 11:20 UTC, xiaozhu36 reviewed
approved

2023-09-27 11:48 UTC, xiaozhu36 approved these changes
approved

2023-09-27 14:38 UTC, xiaozhu36 approved these changes

2023-09-28 06:07 UTC, xiaozhu36 approved these changes

2023-09-28 06:58 UTC, merged