resource/alicloud_alb_listener: Fixed alb TypeSet bug caused by tf sdk v1.17.2; resource/alicloud_alb_rule: Fixed alb TypeSet bug caused by tf sdk v1.17.2
aliyun/terraform-provider-alicloud pull request #6523
Opened 2023-09-20 07:16 UTC by MrWolong

2023-09-21 14:57 UTC, xiaozhu36 requested changes

2023-09-21 14:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_alb_rule_test.go
>  				}),
这个测试为啥删了

2023-09-21 14:57 UTC, xiaozhu36 commented on alicloud/resource_alicloud_alb_rule_test.go
> -	checkoutSupportedRegions(t, true, connectivity.AlbSupportRegions)
这个为啥删了

2023-09-22 08:58 UTC, MrWolong commented on alicloud/resource_alicloud_alb_rule_test.go
> -	checkoutSupportedRegions(t, true, connectivity.AlbSupportRegions)
单测重复了，已合并到TestAccAliCloudALBRule_basic0中

2023-09-22 09:41 UTC, MrWolong commented on alicloud/resource_alicloud_alb_rule_test.go
>  				}),
单测删除的原因是，冗余了，已经合并到已合并到TestAccAliCloudALBRule_basic0中了。
`dry_run`删除的原因是，保留`dry_run`的测试的话，在执行测试import的时候，会报期望与实际不符的错误，原因是`dry_run`是查询不到的，此时，需要把`dry_run`到保留`ImportStateVerifyIgnore`中。但是将`dry_run`到保留`ImportStateVerifyIgnore`中的话，ci会报attributes ["dry_run"] should not in ImportStateVerifyIgnore array的错误。
![image](https://github.com/aliyun/terraform-provider-alicloud/assets/36806235/16793435-7b5d-4c60-ad98-bff49834b03d)

2023-09-26 02:15 UTC, xiaozhu36 approved these changes

2023-09-27 09:24 UTC, xiaozhu36 approved these changes

2023-09-27 11:04 UTC, merged