New Resource: alicloud_rocketmq_instance; New Resource: alicloud_rocketmq_topic; New Resource: alicloud_rocketmq_consumer_group.
aliyun/terraform-provider-alicloud pull request #6538
Opened 2023-09-25 09:13 UTC by ChenHanZhang

2023-09-26 09:04 UTC, xiaozhu36 requested changes

2023-10-18 12:41 UTC, ChenHanZhang commented on alicloud/resource_alicloud_rocketmq_consumer_group_test.go
> +							"retry_policy":    "DefaultRetryPolicy",
done

2023-10-18 12:44 UTC, ChenHanZhang commented on alicloud/resource_alicloud_rocketmq_topic.go
> +	return resourceAliCloudRocketmqTopicUpdate(d, meta)
done

2023-10-19 02:24 UTC, xiaozhu36 requested changes

2023-10-19 02:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rocketmq_instance_test.go
> +					}),
因为资源一旦加入资源组之后，不能在从里面移出，所以以后针对 resource_group_id 要单独增加上一个 REMOVEKEY 的测试步骤。另外文档上要注明：一旦一个资源加入到资源组以后，只能移动到其他资源组，不能从任意资源组中移出。

2023-10-19 02:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rocketmq_instance.go
> +			"auto_renew_period": {
period 和 auto_renew_period 都是要有枚举值的

2023-10-19 02:24 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rocketmq_instance.go
> +			"auto_renew_period": {
另外，这几个参数都只在预付费的时候生效，如果不增加 DiffSuppress 函数，那么需要在文档上说清楚这几个参数的用法

2023-10-23 01:56 UTC, xiaozhu36 requested changes

2023-10-23 01:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rocketmq_consumer_group.go
> +		if NotFoundError(err) {
这个不对吧，这个地方应该是具体的不存在错误码

2023-10-23 01:56 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rocketmq_instance.go
> +		log.Printf("[WARN] Cannot destroy Subscription resource: alicloud_rocketmq_instance. Terraform will remove this resource from the state file, however resources may remain.")
这个待定

2023-10-23 02:16 UTC, ChenHanZhang commented on alicloud/resource_alicloud_rocketmq_consumer_group.go
> +		if NotFoundError(err) {
spec上没有配置，这里不能确定这个资源不存在错误码和get接口的资源不存在错误码是一致的，资源删除接口也需要double check

2023-10-30 02:27 UTC, xiaozhu36 requested changes

2023-10-30 02:27 UTC, xiaozhu36 commented on alicloud/resource_alicloud_rocketmq_instance_test.go
> +				ImportStateVerifyIgnore: []string{"auto_renew_period", "period", "period_unit"},
auto_renew_period 是有被set 了的

2023-10-30 05:35 UTC, ChenHanZhang commented on alicloud/resource_alicloud_rocketmq_instance_test.go
> +				ImportStateVerifyIgnore: []string{"auto_renew_period", "period", "period_unit"},
这个字段目前没有地方透出，bssopenapi那个也不透出的

2023-10-30 05:36 UTC, ChenHanZhang commented on alicloud/resource_alicloud_rocketmq_instance_test.go
> +				ImportStateVerifyIgnore: []string{"auto_renew_period", "period", "period_unit"},
bssopenapi透出的是renew_period

2023-10-30 08:57 UTC, xiaozhu36 approved these changes

2023-11-02 07:10 UTC, xiaozhu36 approved these changes

2023-11-03 03:11 UTC, merged