New Resource: alicloud_threat_detection_client_file_protect; New Resource: alicloud_threat_detection_file_upload_limit; New Resource: alicloud_threat_detection_client_user_define_rule; New Resource: alicloud_threat_detection_log_meta.
aliyun/terraform-provider-alicloud pull request #6541
Opened 2023-09-26 01:23 UTC by ChenHanZhang

2023-09-26 09:33 UTC, xiaozhu36 requested changes

2023-09-26 09:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_client_file_protect.go
> +				Type:     schema.TypeInt,
这个应该是有约束值的

2023-09-26 09:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_client_file_protect.go
> +				Required: true,
rule_action这个也是

2023-09-26 09:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_client_user_define_rule.go
> +				Type:     schema.TypeInt,
action_type 应该有约束值

2023-09-26 09:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_client_user_define_rule.go
> +				Required: true,
platform 应该有约束值

2023-09-26 09:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_client_user_define_rule.go
> +				Type:     schema.TypeInt,
type 也一样

2023-09-26 09:33 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_file_upload_limit.go
> +				Required: true,
这个应该也是有约束值的

2023-10-18 12:39 UTC, ChenHanZhang commented on alicloud/resource_alicloud_threat_detection_client_file_protect.go
> +				Type:     schema.TypeInt,
done

2023-10-18 12:39 UTC, ChenHanZhang commented on alicloud/resource_alicloud_threat_detection_client_file_protect.go
> +				Required: true,
done

2023-10-18 12:39 UTC, ChenHanZhang commented on alicloud/resource_alicloud_threat_detection_client_user_define_rule.go
> +				Required: true,
done

2023-10-18 12:39 UTC, ChenHanZhang commented on alicloud/resource_alicloud_threat_detection_client_user_define_rule.go
> +				Type:     schema.TypeInt,
done

2023-10-18 12:39 UTC, ChenHanZhang commented on alicloud/resource_alicloud_threat_detection_file_upload_limit.go
> +				Required: true,
done

2023-10-19 02:15 UTC, xiaozhu36 approved these changes

2023-10-23 01:46 UTC, xiaozhu36 requested changes

2023-10-23 01:46 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_file_upload_limit.go
> +func resourceAliCloudThreatDetectionFileUploadLimitDelete(d *schema.ResourceData, meta interface{}) error {
这个为啥删不了

2023-10-23 01:46 UTC, xiaozhu36 commented on alicloud/resource_alicloud_threat_detection_log_meta.go
> +	log.Printf("[WARN] Cannot destroy resource AliCloud Resource Log Meta. Terraform will remove this resource from the state file, however resources may remain.")
还有这个

2023-10-23 02:09 UTC, ChenHanZhang commented on alicloud/resource_alicloud_threat_detection_file_upload_limit.go
> +func resourceAliCloudThreatDetectionFileUploadLimitDelete(d *schema.ResourceData, meta interface{}) error {
账号下唯一的配置项，创建后只能修改

2023-10-23 02:12 UTC, ChenHanZhang commented on alicloud/resource_alicloud_threat_detection_log_meta.go
> +	log.Printf("[WARN] Cannot destroy resource AliCloud Resource Log Meta. Terraform will remove this resource from the state file, however resources may remain.")
同样是账号下预设的几个日志类型，只能开启或者关闭

2023-10-30 02:32 UTC, xiaozhu36 approved these changes

2023-10-30 02:51 UTC, merged