resource/alicloud_cs_kubernetes_addon: Fix addon resource status check bug
aliyun/terraform-provider-alicloud pull request #6561
Opened 2023-10-07 04:32 UTC by saberrey

resource/alicloud_cs_kubernetes_addon: Fix addon resource status check bug.

2023-10-07 06:37 UTC, xiaozhu36 requested changes

2023-10-07 06:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_addon.go
> +	stateConf := BuildStateConf([]string{"initial", "upgrading", "updating", "deleting", "running", "Running", "Upgrading", "Pause"}, []string{"active", "Success", "NoUpgrade"}, d.Timeout(schema.Timeout
既然 pending 的状态这么多，那么不建议列举，直接留空就行，保留 Target status 和 Failed status 的枚举值就行

2023-10-07 06:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_addon.go
> +	stateConf := BuildStateConf([]string{"initial", "upgrading", "updating", "deleting"}, []string{"active", "deleted"}, d.Timeout(schema.TimeoutUpdate), 10*time.Second, csClient.CsKubernetesAddonStateR
这个地方也一样

2023-10-08 01:59 UTC, saberrey commented on alicloud/resource_alicloud_cs_kubernetes_addon.go
> +	stateConf := BuildStateConf([]string{"initial", "upgrading", "updating", "deleting", "running", "Running", "Upgrading", "Pause"}, []string{"active", "Success", "NoUpgrade"}, d.Timeout(schema.Timeout
done

2023-10-08 01:59 UTC, saberrey commented on alicloud/resource_alicloud_cs_kubernetes_addon.go
> +	stateConf := BuildStateConf([]string{"initial", "upgrading", "updating", "deleting"}, []string{"active", "deleted"}, d.Timeout(schema.TimeoutUpdate), 10*time.Second, csClient.CsKubernetesAddonStateR
done

2023-10-08 06:15 UTC, xiaozhu36 approved these changes

2023-10-09 02:26 UTC, xiaozhu36 approved these changes

2023-10-10 08:57 UTC, xiaozhu36 approved these changes

2023-10-11 01:26 UTC, xiaozhu36 approved these changes

2023-10-11 02:32 UTC, merged