resource/alicloud_cs_managed_kubernetes: support control plane log config
aliyun/terraform-provider-alicloud pull request #6570
Opened 2023-10-10 12:43 UTC by sanyangji

2023-10-11 01:28 UTC, xiaozhu36 requested changes

2023-10-11 01:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_managed_kubernetes.go
> -				ForceNew: true,
既然支持修改，那么需要有相关的测试用例

2023-10-12 09:38 UTC, xiaozhu36 approved these changes

2023-10-18 07:59 UTC, sanyangji commented on alicloud/resource_alicloud_cs_managed_kubernetes.go
> +				Computed: true,
如果不设的话，会产生默认值30。

2023-10-19 01:48 UTC, xiaozhu36 approved these changes

2023-10-19 03:31 UTC, xiaozhu36 approved these changes

2023-10-19 06:16 UTC, xiaozhu36 approved these changes

2023-10-19 08:29 UTC, xiaozhu36 approved these changes

2023-10-20 01:47 UTC, xiaozhu36 approved these changes

2023-11-02 06:56 UTC, closed without merging