resource/alicloud_alikafka_instance: Fixed selected_zones invalid error
aliyun/terraform-provider-alicloud pull request #6572
Opened 2023-10-11 06:22 UTC by MrWolong

2023-11-02 08:21 UTC, MrWolong commented on alicloud/resource_alicloud_alikafka_instance.go
> +func formatSelectedZonesReq(configured []interface{}) string {
字段selected_zones在接口中是字符串类型，但是接入的时候以list类型接入的，需要对他进行兼容。
当selected_zones只有一个值时，字符串格式为[["a"],[]]，两个及以上则为，[["a"],["b"]]

2023-11-02 08:41 UTC, xiaozhu36 requested changes

2023-11-02 08:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_alikafka_instance_test.go
> +			// Current, there is an api bug that the service will return an extra key: kafka.offsets.retention.minutes in the config
如果已经解决了，那么这个注释去掉吧

2023-11-02 08:41 UTC, xiaozhu36 commented on alicloud/resource_alicloud_alikafka_instance_test.go
> +					"topic_quota":   "1001",
为啥要加这个

2023-11-02 08:47 UTC, MrWolong commented on alicloud/resource_alicloud_alikafka_instance_test.go
> +					"topic_quota":   "1001",
对topic_quota进行修改动作，否则，单测覆盖率会报错。

2023-11-02 08:48 UTC, MrWolong commented on alicloud/resource_alicloud_alikafka_instance_test.go
> +			// Current, there is an api bug that the service will return an extra key: kafka.offsets.retention.minutes in the config
已修复

2023-11-03 03:25 UTC, xiaozhu36 commented on alicloud/resource_alicloud_alikafka_instance_test.go
> +					"topic_quota":   "1001",
那应该设置为一个单独的 step

2023-11-03 08:07 UTC, MrWolong commented on alicloud/resource_alicloud_alikafka_instance_test.go
> +					"topic_quota":   "1001",
已删除，这个有点问题，topic_quota字段目前不存在与update中

2023-11-03 08:44 UTC, xiaozhu36 approved these changes

2023-12-05 02:27 UTC, ChenHanZhang commented on alicloud/resource_alicloud_alikafka_instance.go
> +				Type:     schema.TypeInt,
这些只读属性为啥透出

2023-12-05 02:27 UTC, ChenHanZhang commented on alicloud/resource_alicloud_alikafka_instance.go
> -	if v, ok := d.GetOk("io_max"); ok {
接口上这个参数不是必填的了吗

2023-12-05 02:47 UTC, MrWolong commented on alicloud/resource_alicloud_alikafka_instance.go
> -	if v, ok := d.GetOk("io_max"); ok {
io_max目前是非必填，io_max和io_max_spec二选一

2023-12-05 02:48 UTC, MrWolong commented on alicloud/resource_alicloud_alikafka_instance.go
> +				Type:     schema.TypeInt,
有个需求，需要透出topic的数量，这个跟云产品确认过了，目前要透出这些字段

2023-12-07 03:56 UTC, ChenHanZhang reviewed
approved

2023-12-14 06:01 UTC, closed without merging