resource/alicloud_polardb_cluster: Support setting lower_case_table_n…
aliyun/terraform-provider-alicloud pull request #6596
Opened 2023-10-18 03:30 UTC by Lv0520

…ames parameter is zero

2023-10-18 09:04 UTC, xiaozhu36 requested changes

2023-10-18 09:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster.go
> +				Default:          "OFF",
如果有默认值，这个地方应该设置为 Computed，然后在文档上写清楚默认值是多少

其他的也类似

2023-10-18 09:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					"lower_case_table_names": "0",
对于所有 Computed 的属性，需要在 Check 上增加上验证

2023-10-18 09:04 UTC, xiaozhu36 commented on alicloud/service_alicloud_polardb.go
> +		if parameterValue := d.Get(i.ParameterName); parameterValue != nil {
这个地方不应该有哪些参数，就单独设置哪些参数，不要先通过 d.Get 获取

2023-10-18 09:04 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					"lower_case_table_names": "0",
另外，既然这些已经返回了，那么在import 的测试步骤中，应该把这些去掉

2023-10-18 11:17 UTC, Lv0520 commented on alicloud/service_alicloud_polardb.go
> +		if parameterValue := d.Get(i.ParameterName); parameterValue != nil {
已处理

2023-10-18 11:17 UTC, Lv0520 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +					"lower_case_table_names": "0",
已处理

2023-10-18 11:17 UTC, Lv0520 commented on alicloud/resource_alicloud_polardb_cluster.go
> +				Default:          "OFF",
已处理

2023-10-19 01:46 UTC, xiaozhu36 approved these changes

2023-10-19 07:34 UTC, xiaozhu36 approved these changes

2023-10-19 11:11 UTC, xiaozhu36 approved these changes

2023-10-20 01:54 UTC, xiaozhu36 requested changes

2023-10-20 01:54 UTC, xiaozhu36 commented on alicloud/resource_alicloud_polardb_cluster_test.go
> +				}),
这个地方为啥要同时设置两个参数

2023-10-20 02:50 UTC, xiaozhu36 approved these changes

2023-10-20 09:13 UTC, merged