New Resource: alicloud_dms_enterprise_authority_template.
aliyun/terraform-provider-alicloud pull request #6605
Opened 2023-10-19 13:21 UTC by ChenHanZhang

2023-10-23 01:48 UTC, xiaozhu36 requested changes

2023-10-23 01:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dms_enterprise_authority_template.go
> +	log.Printf("[WARN] Cannot destroy resource AliCloud Resource Authority Template. Terraform will remove this resource from the state file, however resources may remain.")
这个为啥删不了

2023-10-27 01:54 UTC, ChenHanZhang commented on alicloud/resource_alicloud_dms_enterprise_authority_template.go
> +	log.Printf("[WARN] Cannot destroy resource AliCloud Resource Authority Template. Terraform will remove this resource from the state file, however resources may remain.")
done

2023-10-27 10:17 UTC, xiaozhu36 requested changes

2023-10-27 10:17 UTC, xiaozhu36 commented on alicloud/resource_alicloud_dms_enterprise_authority_template.go
> +		if NotFoundError(err) {
为啥这个地方也用的是通用的不存在错误码

2023-10-27 10:17 UTC, xiaozhu36 commented on alicloud/service_alicloud_dms_enterprise_v2.go
> +		if IsExpectedErrors(err, []string{}) {
这都没有错误码，为啥要生成

2023-10-29 04:01 UTC, ChenHanZhang commented on alicloud/resource_alicloud_dms_enterprise_authority_template.go
> +		if NotFoundError(err) {
生成器问题，已处理

2023-10-29 04:01 UTC, ChenHanZhang commented on alicloud/service_alicloud_dms_enterprise_v2.go
> +		if IsExpectedErrors(err, []string{}) {
生成器问题，已处理

2023-10-30 02:18 UTC, xiaozhu36 approved these changes

2023-10-30 11:33 UTC, xiaozhu36 approved these changes

2023-10-30 11:46 UTC, merged