resource/alicloud_privatelink_vpc_endpoint_service: add new attribute resource_group_id, service_resource_type, service_support_ipv6, zone_affinity_enabled.
aliyun/terraform-provider-alicloud pull request #6616
Opened 2023-10-27 01:54 UTC by ChenHanZhang

2023-10-27 10:21 UTC, xiaozhu36 requested changes

2023-10-27 10:21 UTC, xiaozhu36 commented on alicloud/resource_alicloud_privatelink_vpc_endpoint_service.go
> +		if NotFoundError(err) {
这个为啥要改

2023-10-29 04:17 UTC, ChenHanZhang commented on alicloud/resource_alicloud_privatelink_vpc_endpoint_service.go
> +		if NotFoundError(err) {
spec 没配置，已经补上了。针对删除接口的资源不存在错误码，需要资源测试加上校验

2023-10-30 02:21 UTC, xiaozhu36 approved these changes

2023-10-30 08:52 UTC, merged