resource/alicloud_ess_scaling_group:on_demand_base_capacity and on_demand_percentage_above_base_capacity support set zero & spot_instance_pools value range form [0-10] to [1-10]
aliyun/terraform-provider-alicloud pull request #6619
Opened 2023-10-30 08:40 UTC by fuliu-zln

…mand_percentage_above_base_capacity support set zero & spot_instance_pools value range form [0-10] to [1-10]

2023-10-30 08:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6619) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6619) before we can accept your contribution.<br/><hr/>**wb-zln530580** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=6619) it.</sub>

2023-11-03 11:06 UTC, xiaozhu36 approved these changes

2023-11-06 08:14 UTC, xiaozhu36 requested changes

2023-11-06 08:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_scaling_group.go
> +				//Default:      "ECS",
无用的注释删掉

2023-11-06 08:17 UTC, fuliu-zln commented on alicloud/resource_alicloud_ess_scaling_group.go
> +				//Default:      "ECS",
done

2023-11-06 08:34 UTC, xiaozhu36 approved these changes

2023-11-07 05:47 UTC, xiaozhu36 approved these changes

2023-11-07 06:35 UTC, merged