New Resource: alicloud_arms_environment; New Resource: alicloud_arms_addon_release; New Resource: alicloud_arms_env_feature; New Resource: _alicloud_arms_env_pod_monitor; New Resource: alicloud_arms_env_service_monitor.
aliyun/terraform-provider-alicloud pull request #6627
Opened 2023-11-02 09:43 UTC by ChenHanZhang

2023-11-03 03:23 UTC, xiaozhu36 requested changes

2023-11-03 03:23 UTC, xiaozhu36 commented on alicloud/resource_alicloud_arms_addon_release.go
> +	if !d.IsNewResource() && d.HasChange("values") {
既然两个都是在create 中了，为啥create 之后不直接走 read

2023-11-03 03:23 UTC, xiaozhu36 commented on alicloud/resource_alicloud_arms_env_feature.go
> +	if !d.IsNewResource() && d.HasChange("feature_version") {
同样的问题

2023-11-03 03:23 UTC, xiaozhu36 commented on alicloud/resource_alicloud_arms_env_feature_test.go
> +					"feature_version":  "1.1.17",
确认下是否有validation

2023-11-03 03:23 UTC, xiaozhu36 commented on alicloud/resource_alicloud_arms_env_pod_monitor_test.go
> +					"aliyun_lang":    "en",
aliyun_lang 的validation

2023-11-03 03:23 UTC, xiaozhu36 commented on website/docs/r/arms_env_pod_monitor.html.markdown
> +For information about ARMS Env Pod Monitor and how to use it, see [What is Env Pod Monitor](https://www.alibabacloud.com/help/en/).
这个链接无效

2023-11-15 07:45 UTC, ChenHanZhang commented on alicloud/resource_alicloud_arms_addon_release.go
> +	if !d.IsNewResource() && d.HasChange("values") {
done

2023-11-15 07:46 UTC, ChenHanZhang commented on alicloud/resource_alicloud_arms_env_feature.go
> +	if !d.IsNewResource() && d.HasChange("feature_version") {
done

2023-11-15 07:49 UTC, ChenHanZhang commented on alicloud/resource_alicloud_arms_env_feature_test.go
> +					"feature_version":  "1.1.17",
done

2023-11-15 07:49 UTC, ChenHanZhang commented on alicloud/resource_alicloud_arms_env_pod_monitor_test.go
> +					"aliyun_lang":    "en",
done

2023-11-15 09:43 UTC, ChenHanZhang reviewed
approved

2023-11-17 03:38 UTC, ChenHanZhang reviewed
approved

2023-11-17 05:56 UTC, ChenHanZhang reviewed
approved

2023-11-17 07:24 UTC, ChenHanZhang reviewed
approved

2023-11-17 09:01 UTC, ChenHanZhang reviewed
approved

2023-11-17 11:12 UTC, ChenHanZhang reviewed
approved

2023-11-17 14:15 UTC, ChenHanZhang reviewed
approved

2023-11-17 14:38 UTC, ChenHanZhang reviewed
approved

2023-11-18 06:24 UTC, ChenHanZhang reviewed
approved

2023-11-18 09:11 UTC, ChenHanZhang reviewed
approved

2023-11-18 17:05 UTC, merged