resource/alicloud_bastionhost_instance: check "enable_public_access" value before update
aliyun/terraform-provider-alicloud pull request #6639
Opened 2023-11-08 09:00 UTC by shanye997

2023-11-09 01:31 UTC, xiaozhu36 requested changes

2023-11-09 01:31 UTC, xiaozhu36 commented on alicloud/resource_alicloud_bastionhost_instance.go
> +	if d.HasChange("enable_public_access") || (d.IsNewResource() && !d.Get("enable_public_access").(bool)) {
这个换成在 Create 中set 系统默认值的逻辑吧

2023-11-09 02:18 UTC, xiaozhu36 approved these changes

2023-11-09 08:38 UTC, xiaozhu36 approved these changes

2023-11-13 06:57 UTC, xiaozhu36 approved these changes

2023-11-13 08:47 UTC, ChenHanZhang reviewed
approved

2023-11-13 11:29 UTC, ChenHanZhang reviewed
approved

2023-11-14 11:41 UTC, ChenHanZhang reviewed
approved

2023-11-15 08:16 UTC, merged