resource/alicloud_db_readonly_instance: Add rds mysql HA switch
aliyun/terraform-provider-alicloud pull request #6655
Opened 2023-11-14 06:16 UTC by zwc01090043

2023-11-14 06:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6655) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=6655) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=6655) it.</sub>

2023-11-30 08:34 UTC, xiaozhu36 requested changes

2023-11-30 08:34 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance.go
> +			"force": {
这个属性是用来干啥的

2023-11-30 08:34 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance.go
> +				Deprecated: "The parameter 'zone_id_slave_b' has been deprecated from v1.214.0.",
这个参数弃用了，没有对应的替换参数么

2023-11-30 08:34 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance.go
> +		d.SetPartial("manual_ha_time")
这个node_id 的修改跟 这两个参数有啥关系

2023-11-30 08:34 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance.go
> +	}
这个地方为啥要改

2023-11-30 08:34 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance_test.go
> +"zone_id_slave_b"  该字段已弃用，在OpenAPI已下线，等待云文档更新，置为removed
如果openapi 的参数上已经删除了，那么可以直接修改为 removed，如果openapi 的参数上没有删除，那么应该标记为弃用

2023-11-30 08:34 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance_test.go
> -			},
这个为啥要删掉

2023-11-30 08:34 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance_test.go
> +					}),
在测试完自动续费之后，要将这个资源的续费状态再改为不续费，否则这个资源在测试完成之后永远无法释放

2023-11-30 08:38 UTC, zwc01090043 commented on alicloud/resource_alicloud_db_instance.go
> +			"force": {
主备切换接口需要用到的字段

2023-11-30 08:38 UTC, zwc01090043 commented on alicloud/resource_alicloud_db_instance.go
> +				Deprecated: "The parameter 'zone_id_slave_b' has been deprecated from v1.214.0.",
没有 直接就是废弃了该字段

2023-11-30 08:43 UTC, zwc01090043 commented on alicloud/resource_alicloud_db_instance.go
> +	}
用自定义的server_cert  去测试，测出了问题，这个是和衫也测出来的

2023-12-01 02:09 UTC, xiaozhu36 requested changes

2023-12-01 02:09 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance.go
> +			"force": {
即然是主备切换接口需要用到的字段，使用 DiffSuppressFunc: securityIpsDiffSuppressFunc 的目的是干啥

2023-12-01 02:09 UTC, xiaozhu36 commented on alicloud/resource_alicloud_db_instance_test.go
>  var instanceServerlessMap = map[string]string{
新增的 Computed 属性，需要增加 Checkset 检查

2023-12-01 02:09 UTC, xiaozhu36 commented on website/docs/r/db_instance.html.markdown
> +* `effective_time` - (Optional, ForceNew, Available in v1.213.0+) The time when the switching takes effect. Valid values:
这个参数也是这个版本新加的么？另外，下个版本是 1.214.0

2023-12-01 05:58 UTC, xiaozhu36 requested changes

2023-12-01 08:51 UTC, xiaozhu36 approved these changes

2023-12-07 11:39 UTC, merged