resource/alicloud_cs_kubernetes_node_pool: add new attributes.
aliyun/terraform-provider-alicloud pull request #6918
Opened 2024-01-31 03:10 UTC by sanyangji

2024-01-31 03:11 UTC, ChenHanZhang reviewed
approved

2024-01-31 04:21 UTC, ChenHanZhang reviewed
approved

2024-01-31 06:29 UTC, ChenHanZhang reviewed
approved

2024-02-20 01:49 UTC, ChenHanZhang reviewed
approved

2024-02-20 07:46 UTC, ChenHanZhang reviewed
approved

2024-02-20 09:37 UTC, ChenHanZhang reviewed
approved

2024-02-20 11:58 UTC, ChenHanZhang reviewed
approved

2024-02-21 03:13 UTC, ChenHanZhang reviewed
approved

2024-02-26 03:30 UTC, xiaozhu36 requested changes

2024-02-26 03:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +							ValidateFunc: StringInSlice([]string{"cloud_efficiency", "cloud_ssd", "cloud_essd", "cloud_auto", "cloud"}, true),
这个地方的兼容性需要确认下

2024-02-26 03:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +				Optional: true,
这个 internet_charge_type 有枚举值么

2024-02-26 03:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
>  				Optional: true,
这个 node_name_mode 有枚举值么

2024-02-26 03:30 UTC, xiaozhu36 commented on website/docs/r/cs_kubernetes_node_pool.html.markdown
> +subcategory: "ACK"
这个变了是不是所有的 ack 相关的资源都要变

2024-02-26 03:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
>  				Optional: true,
这个 node_name_mode 有枚举值么

2024-02-26 03:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +				Type:             schema.TypeString,
这个也一样

2024-02-26 03:30 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +			},
这个描述不对吧：Select one of 'security_group_ids 'and 'security_group_ids'.

2024-02-26 07:32 UTC, sanyangji commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +							ValidateFunc: StringInSlice([]string{"cloud_efficiency", "cloud_ssd", "cloud_essd", "cloud_auto", "cloud"}, true),
已更新：旧类型仍然兼容，新增类型补充

2024-02-26 07:32 UTC, sanyangji commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +				Optional: true,
已补充

2024-02-26 07:32 UTC, sanyangji commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
>  				Optional: true,
无。有复杂的规则，通过文档说明

2024-02-26 07:32 UTC, sanyangji commented on website/docs/r/cs_kubernetes_node_pool.html.markdown
> +subcategory: "ACK"
已改回

2024-02-26 07:33 UTC, sanyangji commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +				Type:             schema.TypeString,
单枚举值，已补充

2024-02-26 07:33 UTC, sanyangji commented on alicloud/resource_alicloud_cs_kubernetes_node_pool.go
> +			},
已修改

2024-03-02 09:20 UTC, xiaozhu36 approved these changes

2024-03-07 05:27 UTC, ChenHanZhang reviewed
approved

2024-03-07 05:51 UTC, closed without merging