resource/alicloud_quotas_quota_alarm: Support for international languages.
aliyun/terraform-provider-alicloud pull request #7035
Opened 2024-03-06 06:54 UTC by ChenHanZhang

2024-03-06 07:28 UTC, xiaozhu36 requested changes

2024-03-06 07:28 UTC, xiaozhu36 commented on alicloud/connectivity/client.go
> +	config := &openapi.Config{
config 的构造抽成一个独立的方法，所有的 Client 都是共用的
包括上面的 query

2024-03-06 07:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_quotas_quota_alarm.go
> +		response, err = conn.CallApi(genRpcParam(action, "POST", "2020-05-10"), &openapi.OpenApiRequest{Query: query, Body: request, HostMap: hostMap}, &util.RuntimeOptions{})
POST 最好也直接用方法名来表达掉，rpcPostParam(action, "2020-05-10"))

2024-03-06 07:28 UTC, xiaozhu36 commented on alicloud/common.go
> +func genRpcParam(action, method, version string) *openapi.Params {
gen 这种前缀去掉吧

2024-03-06 07:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_quotas_quota_alarm.go
> +		response, err = conn.CallApi(genRpcParam(action, "POST", "2020-05-10"), &openapi.OpenApiRequest{Query: query, Body: request, HostMap: hostMap}, &util.RuntimeOptions{})
hostMap 是干啥的？如果都是所有调用公用的，是不是也可以封装掉，我理解这个地方就只有Query和Body 两个参数，是不是可以用顺序来指定这两个参数。
另外，如果其中一个参数没有被用到，是不是可以不初始化，直接 nil 就可以

2024-03-11 07:09 UTC, ChenHanZhang commented on alicloud/connectivity/client.go
> +	config := &openapi.Config{
done

2024-03-11 07:09 UTC, ChenHanZhang commented on alicloud/resource_alicloud_quotas_quota_alarm.go
> +		response, err = conn.CallApi(genRpcParam(action, "POST", "2020-05-10"), &openapi.OpenApiRequest{Query: query, Body: request, HostMap: hostMap}, &util.RuntimeOptions{})
done

2024-03-11 07:09 UTC, ChenHanZhang commented on alicloud/resource_alicloud_quotas_quota_alarm.go
> +		response, err = conn.CallApi(genRpcParam(action, "POST", "2020-05-10"), &openapi.OpenApiRequest{Query: query, Body: request, HostMap: hostMap}, &util.RuntimeOptions{})
> POST 最好也直接用方法名来表达掉，rpcPostParam(action, "2020-05-10"))

这个method可能为GET，当参数更合适一些吧

2024-03-11 07:37 UTC, ChenHanZhang commented on alicloud/connectivity/client.go
> +	_result, _err := openapi.NewClient(&openapiConfig)
sdk 官网给的example，这里我优化下

2024-03-11 07:37 UTC, ChenHanZhang commented on alicloud/common.go
> +		Style:       tea.String("RPC"),
不行，还是区分的

2024-03-11 09:06 UTC, ChenHanZhang commented on alicloud/connectivity/config.go
> +	//}
这里就和具体的产品api风格有关了，放到client下进行设置

2024-03-14 06:10 UTC, ChenHanZhang reviewed
approved

2024-03-14 06:25 UTC, merged