docs: Improved the document slb_listener
aliyun/terraform-provider-alicloud pull request #7083
Opened 2024-03-21 09:04 UTC by MrWolong

2024-03-21 12:02 UTC, xiaozhu36 requested changes

2024-03-21 12:02 UTC, xiaozhu36 commented on website/docs/r/slb_listener.html.markdown
> +## Argument Reference HTTP Classic Load Balancer (SLB) Listener
Argument Reference 设置为二级标题，在这个标题之下设置四个三级标题，每个三级标题下对应是不同协议的listerner，另外，标题上去掉 Classic Load Balancer (SLB)

2024-03-22 02:38 UTC, MrWolong commented on website/docs/r/slb_listener.html.markdown
> +## Argument Reference HTTP Classic Load Balancer (SLB) Listener
设置成三级标题之后，ci继续报格式问题，ci建议设置成### listener。
![Uploading image.png…]()

2024-03-29 03:21 UTC, xiaozhu36 requested changes

2024-03-29 03:21 UTC, xiaozhu36 commented on website/docs/r/slb_listener.html.markdown
> +**NOTE:** `bandwidth` is available only in the Chinese mainland.
这个地方改成：-> **NOTE:** Currently, this bandwidth is available on `Domestic Site Account`.

2024-03-29 03:55 UTC, MrWolong commented on website/docs/r/slb_listener.html.markdown
> +**NOTE:** `bandwidth` is available only in the Chinese mainland.
已修复

2024-03-29 05:42 UTC, merged