resource/alicloud_cs_kubernetes_permissions:modify sdk; data_source/alicloud_cs_kubernetes_permissions:fix bug
aliyun/terraform-provider-alicloud pull request #7100
Opened 2024-03-27 06:52 UTC by lijiuxing1

modify sdk and fix bug

2024-03-27 06:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=7100) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/terraform-provider-alicloud?pullRequest=7100) before we can accept your contribution.<br/><hr/>**lijjiuxing** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/terraform-provider-alicloud?pullRequest=7100) it.</sub>

2024-03-29 07:49 UTC, ChenHanZhang reviewed
approved

2024-03-29 09:01 UTC, ChenHanZhang reviewed
approved

2024-04-11 06:19 UTC, ChenHanZhang reviewed
approved

2024-04-12 02:02 UTC, xiaozhu36 requested changes

2024-04-12 02:02 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	return resourceAlicloudCSKubernetesPermissionsRead(d, meta)
这个地方为啥还要再返回read

2024-04-12 02:02 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	return resourceAlicloudCSKubernetesPermissionsRead(d, meta)
这个公共方法中只处理请求处理逻辑就行，不需要涉及 resource 方法的调用

2024-04-12 10:28 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	return resourceAlicloudCSKubernetesPermissionsRead(d, meta)
已修改

2024-04-12 10:28 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	return resourceAlicloudCSKubernetesPermissionsRead(d, meta)
已修改

2024-04-12 10:30 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +		if d.Id() == d.Get("uid").(string) && len(oldPermissionsList) > 0 && len(newPermissionsList) > 0{
本意是认为uid变了的resource，不用diff，直接删所有权限再创建，不过调试发现，uid变了后，不是update操作，而是delete+create，因为我们把uid设置为了id，id变了认为是新资源，所以这儿删除

2024-04-12 10:32 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	d.SetId(d.Get("uid").(string))
已修改

2024-04-17 01:44 UTC, xiaozhu36 requested changes

2024-04-17 01:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
>  func resourceAlicloudCSKubernetesPermissionsRead(d *schema.ResourceData, meta interface{}) error {
read 里面为啥啥也没干

2024-04-17 01:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	d.SetId(uid)
不要在这种辅助方法中set id

2024-04-17 01:44 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +func manageUserPermissions(mode string, d *schema.ResourceData, meta interface{}, permissions []interface{}) error {
这个方法 d 的作用看起来只是为了获取 uid，那么就直接吧 uid 作为一个参数传进来就行了

2024-04-17 09:47 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
>  func resourceAlicloudCSKubernetesPermissionsRead(d *schema.ResourceData, meta interface{}) error {
已修改

2024-04-17 09:47 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	d.SetId(uid)
已修改

2024-04-17 09:47 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +func manageUserPermissions(mode string, d *schema.ResourceData, meta interface{}, permissions []interface{}) error {
已修改

2024-04-18 11:28 UTC, xiaozhu36 requested changes

2024-04-18 11:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	return err
wraperror

2024-04-18 11:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	return nil
update 结束之后要走 read

2024-04-18 11:28 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +		return resource.RetryableError(Error("[ERROR] Describe user permission failed %s error %v", uid, err.Error()))
这个地方retry 查询的目的是什么

2024-04-18 12:07 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +		return resource.RetryableError(Error("[ERROR] Describe user permission failed %s error %v", uid, err.Error()))
后端需要保证这个sdk是被成功调用的，这儿后端逻辑不只做了查询

2024-04-18 12:07 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
>  	uid := d.Get("uid").(string)
已修改

2024-04-18 12:07 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	if err == nil {
已修改

2024-04-18 12:07 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	return nil
已修改

2024-04-19 03:47 UTC, xiaozhu36 requested changes

2024-04-19 03:47 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +		return err
wraperror

2024-04-19 03:47 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	}
如果 perms 没有了，是不是意味着这个资源销毁了，如果是的话，不需要设置 permissions了，直接设置 d.setId("") 就行

2024-04-19 03:47 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	}
另外，permissions 在哪儿设置的呢

2024-04-19 05:53 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +	}
1. perms 没有，不意味着资源被销毁，当前资源允许创建perms为空的对象
2. 因为当前资源设计，将从线上读到的permissions 设置到本地会有异常，因此没有将permissions设置到本地，除非更换新的资源，但是之前沟通过，新资源会修改用户的使用习惯，因此先沿用当前资源

2024-04-19 05:53 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +		return err
已修改

2024-04-19 06:43 UTC, xiaozhu36 requested changes

2024-04-19 06:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +		return WrapErrorf(err, DefaultErrorMsg, ResourceName, "CreateResource", err)
这个地方直接 return WrapError(err) 就行

2024-04-19 06:50 UTC, lijiuxing1 commented on alicloud/resource_alicloud_cs_kubernetes_permissions.go
> +		return WrapErrorf(err, DefaultErrorMsg, ResourceName, "CreateResource", err)
已修改

2024-04-19 06:51 UTC, xiaozhu36 approved these changes

2024-04-19 08:43 UTC, xiaozhu36 approved these changes

2024-04-19 11:54 UTC, merged