resource/alicloud_mongodb_sharding_instance: Added the field config_server_list
aliyun/terraform-provider-alicloud pull request #7136
Opened 2024-04-09 10:53 UTC by MrWolong

2024-04-15 08:12 UTC, MrWolong commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
> +				Type:     schema.TypeSet,
没有问题，兼容的

2024-04-15 08:37 UTC, ChenHanZhang commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
> +				Type:     schema.TypeSet,
这个后端返回实际上是无序的吗？TypeSet会有其它问题，例如任意改一个item会引起全量diff

2024-04-22 07:46 UTC, xiaozhu36 requested changes

2024-04-22 07:46 UTC, xiaozhu36 commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
>  				Computed: true,
这个有最大最小个数限制么

2024-04-22 08:07 UTC, MrWolong commented on alicloud/resource_alicloud_mongodb_sharding_instance.go
>  				Computed: true,
已跟云产品确认，最大只能是1个，已添加item限制。

2024-04-22 08:29 UTC, xiaozhu36 approved these changes

2024-04-26 01:14 UTC, merged