resource/alicloud_cs_managed_kubernetes: add param delete_options for delete operation; resource/alicloud_cs_kubernetes: add param delete_options for delete operation.
aliyun/terraform-provider-alicloud pull request #7241
Opened 2024-05-14 02:07 UTC by sanyangji

2024-05-14 11:48 UTC, xiaozhu36 requested changes

2024-05-14 11:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes_test.go
> +					testAccCheck(map[string]string{})),
要在增加一个只保留一个 delete mode 的step

2024-05-14 11:48 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes.go
>  		if err != nil {
read 里面 set 的逻辑呢？

2024-05-16 16:01 UTC, xiaozhu36 approved these changes

2024-05-17 06:44 UTC, ChenHanZhang reviewed
approved

2024-05-17 09:40 UTC, ChenHanZhang reviewed
approved

2024-05-20 01:43 UTC, merged