resource/alicloud_cs_managed_kubernetes: output error message when failed to upgrade cluster;resource/alicloud_cs_kubernetes: output error message when failed to upgrade cluster;resource/alicloud_cs_edge_kubernetes: output error message when failed to upgrade cluster;resource/alicloud_cs_serveless_kubernetes: output error message when failed to upgrade cluster
aliyun/terraform-provider-alicloud pull request #7248
Opened 2024-05-15 05:06 UTC by sanyangji

2024-05-16 03:35 UTC, xiaozhu36 requested changes

2024-05-16 03:35 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_edge_kubernetes.go
> +		return err
这个为啥要改

2024-05-16 03:35 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_kubernetes.go
> +		return err
加上 wraperror

2024-05-16 03:35 UTC, xiaozhu36 commented on alicloud/resource_alicloud_cs_serverless_kubernetes.go
> +		return err
还有这个

2024-05-16 09:08 UTC, xiaozhu36 approved these changes

2024-05-17 01:39 UTC, ChenHanZhang reviewed
approved

2024-05-17 09:07 UTC, sanyangji commented
resource_alicloud_cs_edge_kubernetes测试结果：
=== RUN   TestAccAliCloudEdgeKubernetes
--- PASS: TestAccAliCloudEdgeKubernetes (2392.77s)
=== RUN   TestAccAliCloudEdgeKubernetes_essd
    provider_test.go:154: Skipping unsupported region eu-central-1. Supported regions: [cn-zhangjiakou cn-huhehaote].
--- SKIP: TestAccAliCloudEdgeKubernetes_essd (0.00s)
=== RUN   TestAccAliCloudEdgeKubernetes_pro
--- PASS: TestAccAliCloudEdgeKubernetes_pro (989.31s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  3384.207s

2024-05-17 09:08 UTC, merged